### ISSUE TITLE
[Группа предметов] Полумесяц неприкаянных духов

### ISSUE THREAD

**Issue by Mandragora1995** [VirginTeam/WotlkCore#1002]
**Ссылки и комментарии:**

http://db.logon3.com/?item=2044
**Что работает не так?**

Можно юзать 2 одинаковых топора

**Как должно работать?**

Можно юзать только 1, так как награда за задание может быть 1 раз. Раньше продавались в лк
Сделайте уникальным этот топор, именно уникальным, что бы не было возможности менять чарки во время боя. Сейчас 2 одинаковых получить нельзя, только дизбаланс от них

**Шаги для воспроизведения ошибки:**

1. Шаг один
2. Шаг два
3. Шаг три

**Текущее обновление ядра:**

14.06.2018
[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by Mandragora1995** [comment]
как пруфы. 
Попробуйте http://db.logon3.com/?quest=98 сделать больше 1 раза 
и вы поймёте, что 2 топора получить нельзя

**Comment by kalipsa988** [comment]
Он прав, проблема такая же как и #487

**Comment by ForesterDev** [comment]
Будет исправлено в обновлении

**Comment by Mandragora1995** [comment]
Можно скриншот с 2мя такими топорами? просто привязки никакой не видно, а исправлено

**Comment by Mandragora1995** [comment]
не работает !

**Comment by Kodekc** [comment]
@Mandragora1995 прикрепите какую-либо информацию, которая подтверждает ваши слова о том, что исправление не работает.

**Comment by Mandragora1995** [comment]
х1 не доступен, не могу скиршот об отсутствии "Уникальный" на предмете сделать, на опен тесте можно прописать этот предмет?

**Comment by Mandragora1995** [comment]
Mandrogor орда

**Comment by Mandragora1995** [comment]
да и в вашей бд нет подписи уникальный на предмете http://db.logon3.com/?item=2044

**Comment by Mandragora1995** [comment]
![default](https://user-images.githubusercontent.com/40275574/41923638-94a9a3a4-7970-11e8-8031-ad83bab25d49.png)
вот скриншот, никакой привязки нет, т е свободно можно 2 надеть

**Comment by Mandragora1995** [comment]
Прошёл почти месяц и до сих пор "исправлено" ?

**Comment by Mandragora1995** [comment]
ну хотя бы этикетку поменяли

**Comment by kalipsa988** [comment]
а чё висит реопен, но тикет закрыт ?

**Comment by kalipsa988** [comment]
похоже опять фикс утерян. Только что на твинке прочекал, нет изменений

**Comment by kalipsa988** [comment]
мне кажется "Уникальный" не вешается нормально. "Уникальный использующийся" можно было бы сделать, пофиг на свап пух в бою, хотя бы не 2 сразу
