### ISSUE TITLE
[Подземелье] ID 4820 - Залы отражений

### ISSUE THREAD

**Issue by gmKroshka** [VirginTeam/WotlkCore#1003]
**Ссылки и комментарии:**

[Залы отражений](http://db.logon3.com/?zone=4820)
[Король Лич](http://db.logon3.com/?npc=37226)

**Что работает не так?**

При ивенте побега от Короля Лича появляющиеся НПЦ не идут в атаку, остаются стоять около Лича. В связи с этим, Лич не двигается, ивент может длиться бесконечно. Для продолжения прохождения подземелья группе необходимо вернуться к Личу, сагрить мобов. В таком случае ивент продолжится и возможно пройти до конца

**Как должно работать?**

Мобы не остаются около Лича, бегут к группе и вступают в бой

**Шаги для воспроизведения ошибки:**

1. Вступить группой в подземелье Залы отражений
2. Запустить ивент с побегом
3. Пройти половину пути

**Текущее обновление ядра:**

204

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by gmRial** [comment]
https://youtu.be/kcD2SYuMQ-Q

**Comment by gmRial** [comment]
Необходимо проверить наличие бага на Орде.

**Comment by gmKroshka** [comment]
Будет исправлено после обновления

**Comment by Kodekc** [comment]
Применено - Build 231
