### ISSUE TITLE
[Заклинание] ID 2645 - Призрачный волк

### ISSUE THREAD

**Issue by kalipsa988** [VirginTeam/WotlkCore#1004]
**Ссылки и комментарии:**

http://db.logon3.com/?spell=2645
**Что работает не так?**

Не верно работает замедло в волке

**Как должно работать?**

Должно замедлять на 50%, а замедляет на 40%
Скорость шамана в волке 7 + 20% = 9.8
Соответственно под 50% замедлом скорость должна быть 4.9 ( у друидов правильно работает)
А на деле под 50% замедлом получается не 4.9, а 7 ( базовая скорость)

**Шаги для воспроизведения ошибки:**

1. Кинуть замедло на 50%
2. Увидеть, что в волке замедло идёт только на 40%

**Текущее обновление ядра:**

15.06.2018

**Comment by Trombocid** [comment]
???????
Призрачный волк  Магия 
Скорость передвижения повышена на 40%. **Эффекты снижения скорости не смогут снизить вашу скорость ниже обычной.**

**Comment by kalipsa988** [comment]
откуда это ?

**Comment by kalipsa988** [comment]
нашёл.
