### ISSUE TITLE
[NPC] ID 35013 - Коралон Страж Огня

### ISSUE THREAD

**Issue by sega693** [VirginTeam/WotlkCore#1008]
**Ссылки и комментарии:**
http://db.logon3.com/?npc=35013 босс
http://db.logon3.com/?spell=66684 Пылающая головня в 10
http://db.logon3.com/?spell=67332 Пылающая головня в 25

**Что работает не так?**
 Пылающая головня всегда кастуется в танка

**Как должно работать?**
> Пылающая головня – Кидает **в случайного игрока** уголь, наносящий 4.388 – 4.612 урона от огня всем игрокам, стоящим в радиусе 4 метра от него. Оставляет на земле огненную лужу.
> Милидд становятся сзади босса, а рдд и хилы распределяются в центре комнаты. Время от времени босс будет кидать Пылающую головню, и если она окажется под ним, то его нужно будет увести из огненной лужи

Должна кастоваться в рандомную цель

**Шаги для воспроизведения ошибки:**

1. Шаг один
2. Шаг два
3. Шаг три

**Текущее обновление ядра:**
Build 204 2018-05-30 12:21:57 +0400

**Comment by ForesterDev** [comment]
Исправлено, будет применено в обновлении
