### ISSUE TITLE
[Задание] ID 536 - На побережье

### ISSUE THREAD

**Issue by Santaria94** [VirginTeam/WotlkCore#1009]
Ссылки и комментарии:

http://db.logon3.com/?quest=536

http://db.logon3.com/?npc=2377
http://db.logon3.com/?npc=2376

Что работает не так?

Низкое заселение квестовых NPC.

Как должно работать?

http://vanillawowdb.com/?npc=2377
http://vanillawowdb.com/?npc=2376

Текущее обновление ядра:

204

**Comment by Kodekc** [comment]
[Существа] ID 2377 - Волнолов из племени Порванного Плавника
* Перезаселены. Было = 8 Стало = 20

[Существа] ID 2376 - Оракул из племени Рваного Плавника
* Перезаселены. Было = 8 Стало = 20

Изменения будут применены в ближайшем обновлении
