### ISSUE TITLE
[Заклинание] ID 1543 - Осветительная ракета

### ISSUE THREAD

**Issue by Gooldark** [VirginTeam/WotlkCore#101]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Что работает не так?**

 а) анимация подсвечивания площади совпадает с активацией ауры.

б) неверная задержка на получение дебафа и установку флары.

Сейчас при использовании флары на ~30 м идет задержка в 0,7 сек

> 3/8 00:48:32.185  SPELL_CAST_SUCCESS,"Осветительная ракета"
3/8 00:48:32.982  SPELL_AURA_APPLIED,"Осветительная ракета",DEBUFF

в) неверное взаимодействие ухода в стелс и флары. На данный момент стелс нельзя использовать находясь в фларе.

**Как должно работать?**

 а) анимация и сама флара не должны совпадать. Анимация работала правильно до починки этого репорта http://forum.wowcircle.com/showthread.php?t=424786 . То есть подсвечивание зоны должно включаться только когда огонек долетит в назначенное место.

б) у флары присутствует задержка наложения которая сильно зависит от расстояния, скорее всего это связанно с тем, что для обновления ауры берется расстояние между целью и охотником, когда должно браться расстояние между центром флары и целью.

т.е. флара должна мгновенно появляться, но флайтайм накладывание ауры должно учитываться от цента флары до цели.

в) Стелс должно быть можно использовать, однако он должен сразу иммуниться.

**Доказательства**

http://www.warcraftmovies.com/movieview.php?id=154831 - 15:20 все 3 цели получили флаер одновременно с большого расстояния без задержки, при этом анимация подсвечивания появилась только на 15:25. 15:58 - на локе дебаф флары появился чуть раньше чем на роге.

http://www.warcraftmovies.com/movieview.php?id=155267 - 5:44 гкд на флару уже пошло, но она появилась на роге с небольшой задержкой.

https://www.youtube.com/watch?v=G_m9hwU75No - в этом видео хант лагает, но даже если так одновременно полученные дебафы должны были отобразиться одновременно, однако видно что на 7:45 прист получил флаер раньше чем рог.

в) https://www.youtube.com/watch?v=srwTw3BoU3s - 0:27 - попытка уйти в стелс обернулась иммуном. 

**Текущее обновление ядра:**

14.04.2017. 153 билд

**Перенесено**

http://forum.wowcircle.com/showthread.php?t=650403

**Comment by ForesterDev** [comment]
В текущей спелл-системе описанное нереализуемо
