### ISSUE TITLE
Сообщение об ограничении общения

### ISSUE THREAD

**Issue by kalambyr18** [VirginTeam/WotlkCore#1012]
**Ссылки и комментарии:**

**Что работает не так?**

Получаю сообщение "Вы должны подождать N часов N минут N секунд, чтобы начать говорить снова " каждые 5 секунд! 
Я понимаю что получил мут , зачем мне каждые 5 секунд об этом говорить? 10 часов это сообщение читать!? 

**Как должно работать?**

Сделайте оповещение ну раз в 10 минут . Зачем каждые 5 секунд об этом спамить!?

**Шаги для воспроизведения ошибки:**

1. мут получить

**Текущее обновление ядра:**

не могу посмотреть  ,у меня мут

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by ForesterDev** [comment]
Возможно у вас есть какой то аддон, который спамит каждые 5 секунд в чат сообщения. Проведите ревизию аддонов

**Comment by kalambyr18** [comment]
Такого аддона у меня нет. Есть на чат аддон WIM . Отключил, релогнулся, бесполезно .

**Comment by gmKroshka** [comment]
Аддон, который периодически в чат писал .save не используете?

**Comment by kalambyr18** [comment]
Нет

**Comment by sega693** [comment]
выруби вообще все аддоны и включай понемногу. Некоторые спамят в какие-то свои каналы, игроку не видно даже этого. Но на чат влияет

**Comment by kalambyr18** [comment]
хм.. пробну , но никакого спама сообщений ни в каких каналах от себя не вижу . спс
