### ISSUE TITLE
[Заклинание] ID 20111, 20112, 20113 - Специализация на двуручном оружии

### ISSUE THREAD

**Issue by xARCHIMEDESx** [VirginTeam/WotlkCore#1013]
### Что работает не так?
Некоректная работа таланта [Специализация на двуручном оружии](http://db.logon3.com/?spell=20113) и, предположительно, его версий [1](http://db.logon3.com/?spell=20111) и [2](http://db.logon3.com/?spell=20112) уровня (их я не проверял).

### Как должно работать?
Талант должен увеличивать урон от оружия и влиять этим на автоатаку, Удар воина Света, Божественную бурю, [Печать праведности](http://db.logon3.com/?spell=21084), [Печать повиновения](http://db.logon3.com/?spell=20375) **UPD: [Печать мщения](http://db.logon3.com/?spell=31801), [Печать порчи](http://db.logon3.com/?spell=53736)** и все заклинания категории Правосудие.
В случае с автоатакой, УВС и Бурей все работает, эти способности мы рассматривать дальше не будем. 
В случаи с Правосудиями и ~~двумя~~ тремя названными печатями талант должен проявлять себя в виде мультипликативного коэффициента (1.02, 1.04, 1.06 в зависимости от уровня).

### Ссылки и комментарии:
**1. Код аддона Dr. Damage:**
`Two-Handed Weapon Specialization (multiplicative - 3.3.3)
[GetSpellInfo(20111)] = { 	[1] = { Effect = 0.02, Melee = true, Spells = { "Attack", "Crusader Strike", "Divine Storm", "Seal of Righteousness", "Seal of Command", "Judgement" }, ModType = "Two-Handed Weapon Specialization" }, },`

Где `Judgement` это:
`["Judgements"] = { 	[GetSpellInfo(21084)] = "Judgement of Righteousness",
[GetSpellInfo(20375)] = "Judgement of Command",
[GetSpellInfo(31801)] = "Judgement of Vengeance",
[GetSpellInfo(53736)] = "Judgement of Corruption",
[GetSpellInfo(20165)] = "Judgement of Light(s)",
[GetSpellInfo(20166)] = "Judgement of Wisdom(s)",
[GetSpellInfo(20164)] = "Judgement of Justice(s)"
},`
То есть, все виды Правосудий в игре.

**2. Вычисления**, сделанные Зороастром@forum.wowcircle.com, которые доказывают присутствие этого мультипликатора в формулах рассчета дамага на примере [Печати](http://db.logon3.com/?spell=21084)/[Правосудия](http://db.logon3.com/?spell=20187) праведности.
Можно посмотреть [сдесь](http://forum.wowcircle.com/showthread.php?t=468714).

### Как должно работать
***
[Печать повиновения](http://db.logon3.com/?spell=20375) и [Правосудие повиновения](http://db.logon3.com/?spell=20467)
Сейчас мультипликативный коэфициент отсутствует, взятие таланта никак не влияет на урон от прока Печати или урон Правосудия. При взятии таланта урон должен увеличиватся на 2/4/6%.

**Печать без таланта**
![wowscrnshot_092318_220028](https://user-images.githubusercontent.com/24897313/45932892-43493d00-bf8c-11e8-8e36-be9b2970796b.jpg)

**Печать с талантом**
![wowscrnshot_092318_221850](https://user-images.githubusercontent.com/24897313/45932923-ca96b080-bf8c-11e8-9b00-dda644db40ac.jpg)

Dr.Damage показывает, что урон должен возрости на 6%, но этого не случилось.

**Правосудие без таланта**
![wowscrnshot_092318_220120](https://user-images.githubusercontent.com/24897313/45932942-32e59200-bf8d-11e8-8315-12c52da1f629.jpg)

**Правосудие с талантом**
![wowscrnshot_092318_221915](https://user-images.githubusercontent.com/24897313/45932952-514b8d80-bf8d-11e8-8292-0c2790f6823f.jpg)

При взятии таланта урон тоже не изменился. Но, мы можем видеть, что значения урона правосудия в рекаунте выше, чем показывает ДрД, даже с талантом. Скорее всего имеет силу супутствующий баг #386
***
[Печать праведности](http://db.logon3.com/?spell=21084) и [Правосудие праведности](http://db.logon3.com/?spell=20187)
А вот с этими печатью и правосудием все хорошо, мультипликативный коэфициент присутствует, дамаг от таланта увеличивается. **UPD: Исправлено точечно за ишью Зороастра, еще когда наш баг-трекер был на форуме, ссылка присутствует немного выше.**

**Печать без таланта**
![wowscrnshot_092318_220544](https://user-images.githubusercontent.com/24897313/45933067-d5524500-bf8e-11e8-9d16-271cfdf3bb5c.jpg)

**Печать с талантом**
![wowscrnshot_092318_222231](https://user-images.githubusercontent.com/24897313/45933071-eb600580-bf8e-11e8-89c3-ef95e3945c86.jpg)

Хотя увеличение на 6% произошло, как и должно, можно увидеть несоответствие рассчитаного ДрД урона с реальным. Сдесь какой-то баг тоже присутствует, скорее всего в формуле рассчета урона печати. Нужно смотреть и создавать отдельное ишью.

**Правосудие без таланта**
![wowscrnshot_092318_220606](https://user-images.githubusercontent.com/24897313/45933093-4b56ac00-bf8f-11e8-8d51-c89298d2219a.jpg)

**Правосудие с талантом**
![wowscrnshot_092318_222300](https://user-images.githubusercontent.com/24897313/45933101-632e3000-bf8f-11e8-8645-520c4595250e.jpg)

Тут все хорошо, талант действует, других багов нет.
***
[Печать мщения](http://db.logon3.com/?spell=31801), [Печать порчи](http://db.logon3.com/?spell=53736)
~~Согласно Dr. Damage, влияние таланта на эти печати (на сам прок и доты) - отсутствует. В нас все работает нормально.~~
**UPD: В реальности талант так же влияет на эту печать. Почему в коде ДрД не написано - не знаю, может плохо смотрел. На скринах легко увидеть рассчитаный прирост в 6%, которого нет в реале.**

**UPD.UPD: После обновления ишью только увидел, что должна апатся и ДоТ часть печати, на скринах ДрД отчетливо это показывает. Как в нас - не проверил, но не думаю, что работает**

**Печать без таланта**
![wowscrnshot_092318_221232](https://user-images.githubusercontent.com/24897313/45933190-91603f80-bf90-11e8-9461-709d4cf7bc9c.jpg)

**Печать с талантом**
![wowscrnshot_092318_222654](https://user-images.githubusercontent.com/24897313/45933195-a8069680-bf90-11e8-9e08-f8dc1c2579f6.jpg)

[Правосудие отмщения](http://db.logon3.com/?spell=31804), [Правосудие порчи](http://db.logon3.com/?spell=53733)
Сейчас мультипликативный коэфициент отсутствует, взятие таланта никак не влияет на урон от Правосудия. При взятии таланта урон должен увеличиватся на 2/4/6%.

**Правосудие без таланта**
![wowscrnshot_092318_221252](https://user-images.githubusercontent.com/24897313/45933236-7641ff80-bf91-11e8-96d3-81c6b75a37f4.jpg)

**Правосудие с талантом**
![wowscrnshot_092318_222707](https://user-images.githubusercontent.com/24897313/45933204-cff5fa00-bf90-11e8-9c18-02143a8320ca.jpg)
***
[Печать Света](http://db.logon3.com/?spell=20165), [Печать мудрости](http://db.logon3.com/?spell=20166), [Печать справедливости](http://db.logon3.com/?spell=20164)
Эти печати отсутствуют в списке печатей, на которые влияет талант, равно как и они сами по себе дамага не наносят, а имеют другой эффект. В нас все работает нормально.

К Правосудиям этих трех печатей тоже должен применятся талант в виде мультипликатора, согласно коду Dr. Damage. Как работает сейчас в нас - не проверял, но думаю, что и тут талант тоже не работает.

### Текущее обновление ядра
~~204~~
218

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by xARCHIMEDESx** [comment]
Додайте лэйбл "Паладин"

**Comment by xARCHIMEDESx** [comment]
Ап на добавление лэйбла!

**Comment by xARCHIMEDESx** [comment]
**UPDATE**
1) Удалил пункт с двойным скалированием, так как он не нашел подтверждения.
2) Раньше я просто сравнивал дамаг без таланта/с талантом опираясь на код ДрД, но затупив включить его в игре. Сейчас, включив ДрД в игре и сравнивая реальный прирост/его отстутствие с рассчетным аддоном, добился более точных чисел.
3) Получил практические доказательства того, что талант должен апать прок печати порчи/мщения, хотя теоретически раньше отклонял это.
4) Залил скрины на каждый пункт.

**Comment by gmRial** [comment]
Исправлено, после обновления.
