### ISSUE TITLE
[NPC] ID 2775 - Мародер из клана Пронзающего Гребня

### ISSUE THREAD

**Issue by Santaria94** [VirginTeam/WotlkCore#1018]
**Ссылки и комментарии:**

http://db.logon3.com/?npc=2775

http://ru.wowhead.com/npc=2775
https://www.youtube.com/watch?v=ysTD_nkf1gs

> Это нага, которую вы должны отстранить от  Death From Below .

**Что работает не так?**

1) Заселены лишние NPC в количестве трех штук.

2) Фраза _"Мародер из клана Пронзающего Гребня кричит: Ты слишком долго **<крал/крала>** наши сокровища. Готовься отправиться на дно!"._ 

**Как должно работать?**

1) Данные NPC должны спавнится только во время задания http://ru.wowhead.com/quest=667
На данный момент три штуки заселены в бухте возле квестодателей и атакуют игроков. Их там быть не должно.

2) Не определяется пол персонажа и NPC говорят **<крал/крала>**

Само задание http://db.logon3.com/?quest=667 работает корректно - наги спавнятся, пушка стреляет. Его фиксить не надо. Нужно только убрать из заселения лишних NPC.

**Текущее обновление ядра:**

204

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by gmKroshka** [comment]
Будет исправлено после обновления
