### ISSUE TITLE
[Общая механика] Пвп флаг

### ISSUE THREAD

**Issue by Gooldark** [VirginTeam/WotlkCore#102]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Речь идет даже не о самом пвп флаге, а механике позволяющей бить цели.
В вове существует несколько видов взаимодействий:
1) Когда фракции не могут между собой взаимодействовать.
Например - синие территории, тут альянс и орда не могут бить друг друга, так же как и хилить.
2) Когда представитель одной фракции не может бить представителя противоположной фракции, в то же время тот кто "неуязвим" может ударить и получить пвп флаг.
3) Когда оба представителя различных фракций могут бить друг друга.
4) Когда оба представителя различных фракций могут только хилить друг друга(соло арена).

Из этих пунктов криво работают 4-ый и 2-ой. Во втором пункте речь идет не только про различные фракции, в принципе про враждебное взаимодействие дуэли/арена.

**Что работает не так?**

а) когда в бою соло арены в одной тиме находятся представители двух фракций, любое взаимодействие между ними сопровождается выделением в таргет того кто пытается взаимодействовать. 
Пример: прист(орда) хилит вара(альянс) и у вара отсутствует таргет, то после начала произнесения заклинания у вара появиться прист в таргете.

б) Ловушки, тотемы, триггеры с лужами, петы, трупы без духа не получают от хозяина пвп ориентацию и сами не могут определить ее.

Пример 1: рог в стелсе(которого не видит хант) может спокойно бегать под носом у пета или стоять на ловушке.
Пример 2: рог не видит ханта(хант в стелсе) не может обезвреживать ловушку/бить пета, при этом пет может спокойно бить рога.
Пример 3: пал/дк разливают лужу, но в эпицентре находиться рог в стелсе, которого они не видят, в итоге лужа исчезает.
Пример 4: лежит труп без духа(труп враждебной цели, ведь есть еще и арена где могут столкнуться представители одной фракции) нежить не может использовать расовую(каннибализм) или дк не может взорвать труп.
Пример 5: охотник без пвп флага ставит ловушку(Взрывная ловушка http://wowroad.info/?spell=49067) под цель с флагом, в итоге ловушка срабатывает, наносит урон, а хант избегает получение пвп флага.
Пример 6: рог в стелсе без пвп флага может спокойно обезвредить ловушку ханта с флагом, при этом не получить пвп флаг.

**Как должно работать?**

а) когда представители разных фракций находятся в одной тиме взаимодействие между ними должно происходить так же как между представителями одной фракции. То есть не должно быть выделение того кто пытается с тобой взаимодействовать.

б) Ловушкам, тотемам, триггерам с лужами, петам, трупам без духа всегда должна передаваться пвп ориентация, так же они должны сами определять ориентацию цели без необходимости идентификацией хозяином. 

**Доказательства**

http://www.warcraftmovies.com/movieview.php?id=115589 - 2:30 рог ест труп без духа

**Текущее обновление ядра:**

14.04.2017. 153 билд

**Comment by Kodekc** [comment]
Не будет представителей разных фракций в одной команде арены.
