### ISSUE TITLE
[Предмет] ID 45038 - Осколок Вал'анира

### ISSUE THREAD

**Issue by kalipsa988** [VirginTeam/WotlkCore#1020]
**Ссылки и комментарии:**

http://db.logon3.com/?item=45038

**Что работает не так?**

Не верный дроп с йогга

**Как должно работать?**

При убийстве йогга дроп осколка должен быть 100%

**Шаги для воспроизведения ошибки:**

1. Убить йогга

**Текущее обновление ядра:**

22.06.2018

**Comment by Kodekc** [comment]
От куда взята информация о дропе в 100%? Даже на wowhead указан 71%, т.е. это только подтверждает, что предмет не падает с таким шансом.

**Comment by kalipsa988** [comment]
https://wowwiki.wikia.com/wiki/Fragment_of_Val%27anyr

**Comment by kalipsa988** [comment]
https://web.archive.org/web/20120110100013/http://ru.wowhead.com:80/item=45038#english-comments 
так же тут
 Razzberry28 на2009-04-21 (Обновление 3.1.1)

https://web.archive.org/web/20120110100013/http://www.wowarmory.com/item-info.xml?i=45038   Йогг-Сарон указан как «Гарантированный», чтобы удалить фрагмент. Более поздние боссы / жесткие режимы, похоже, имеют более высокую скорость снижения.

**Comment by MedoOf** [comment]
http://eu.battle.net/wow/ru/item/45038#tab=dropCreatures
Надеюсь инфе от близов верите? 

Йогг-Сарон | Порождение хаоса | 83 (Босс) | Ульдуар | Гарантированная
-- | -- | -- | -- | --

**Comment by ForesterDev** [comment]
Исправлено. Будет применено в обновлении
