### ISSUE TITLE
[Объект] ID 181334 - Пламя Дарнаса

### ISSUE THREAD

**Issue by Santaria94** [VirginTeam/WotlkCore#1021]
**Ссылки и комментарии:**

http://db.logon3.com/?item=23184
http://ru.wowhead.com/achievement=1145

> Тельдрассил - Деревня Рут'Теран (56, 92). Получите Пламя Дарнасса.

**Что работает не так?**

Пламя расположено  на террасе воинов в Дарнасе, куда его перенесли только в Катаклизме.

**Как должно работать?**

Должно быть в деревне Рут'Теран (56, 92)

**Текущее обновление ядра:**

205

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by ForesterDev** [comment]
Исправлено, будет применено с рестартом
