### ISSUE TITLE
[Задание] ID 11657, 11924 - Поймай факел, Опять жонглирование факелами (Альянс)

### ISSUE THREAD

**Issue by Santaria94** [VirginTeam/WotlkCore#1022]
**Ссылки и комментарии:**

http://db.logon3.com/?quest=11657
http://db.logon3.com/?quest=11924

**Что работает не так?**

Не прописан NPC, который должен давать квесты. Невозможно взять эти задания.

**Как должно работать?**

Задания должен выдавать http://db.logon3.com/?npc=25975

**Текущее обновление ядра:**

205

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by ForesterDev** [comment]
Исправлено, будет применено с рестартом
