### ISSUE TITLE
[Объект] ID 187708 - Отмеченная Жаровня

### ISSUE THREAD

**Issue by Santaria94** [VirginTeam/WotlkCore#1025]
**Ссылки и комментарии:**

http://db.logon3.com/?object=187708

Объект необходим для этих квестов.

http://db.logon3.com/?quest=11922
http://db.logon3.com/?quest=11921
http://db.logon3.com/?quest=11731
http://db.logon3.com/?quest=11924

**Что работает не так?**

Отсутствуют жаровни в Луносвете, Дарнасе
Не хватает 3 жаровень в Экзодаре.

Необходимы для заданий события Огненный солнцеворот.

**Как должно работать?**

Должно быть по 5 объектов неподалеку от квестодателей:

1) http://db.logon3.com/?npc=26113 (Орда)
2) http://db.logon3.com/?npc=25975 (Альянс)

Также над жаровнями должны быть специальные метки, их ID в базе не удалось найти. Можно посмотреть в городах, где жаровни рабочие.

**Текущее обновление ядра:**

205

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by ForesterDev** [comment]
Исправлено, будет применено с рестартом
