### ISSUE TITLE
[Объект] ID 711 - Розыск!

### ISSUE THREAD

**Issue by xaa-xaa** [VirginTeam/WotlkCore#1029]
**Ссылки и комментарии:**

http://db.logon3.com/?object=711

**Что работает не так?**

Для персонажей 71+ уровня начинает предлагает следующие задания:
Орда: 
1. http://db.logon3.com/?quest=12090
2. http://db.logon3.com/?quest=12091
3. http://db.logon3.com/?quest=12089

Альянс: 
1. http://db.logon3.com/?quest=12441
2. http://db.logon3.com/?quest=12442
3. http://db.logon3.com/?quest=12438

**Как должно работать?**

Должна выдавать только http://db.logon3.com/?quest=398 и только игрокам Орды 4+ уровней

**Шаги для воспроизведения ошибки:**

1. Подойти к доске персонажем 71+ уровня с невыполненными вышеописанными заданиями

**Текущее обновление ядра:**

Build 205 2018-06-22 11:00:22 +0400

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by gmKroshka** [comment]
Будет исправлено после обновления
