### ISSUE TITLE
Убийство питомцем кв нпс

### ISSUE THREAD

**Issue by kalambyr18** [VirginTeam/WotlkCore#1036]
**Ссылки и комментарии:**

Любой кв, по котрому нужно убить 1 нпс и получить с того кв айтем . К примеру кв http://ru.wowhead.com/quest=193/охота-на-пантер  , либо кв http://ru.wowhead.com/quest=503/голдир

**Что работает не так?**

При добивании питомцем нпс , с него не падает кв айтем .

**Как должно работать?**

Квестовый айтем должен падать вне зависимости от того убил его игрок или питомец.

**Шаги для воспроизведения ошибки:**

1. Взять квест по которому нужно убить 1 нпс и получить с него айтем 
2, Добить нпс питомцем

**Текущее обновление ядра:**

209

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by kalipsa988** [comment]
тут в принципе не дают лут с мобов, если моба убил только пет
