### ISSUE TITLE
Лихорадка тернистой долины

### ISSUE THREAD

**Issue by kalambyr18** [VirginTeam/WotlkCore#1039]
**Ссылки и комментарии:**

http://ru.wowhead.com/quest=26597/лихорадка-тернистой-долины

**Что работает не так?**

Нпс с которым нужно пообщаться неактивен.

**Как должно работать?**

Нпс должен разговаривать

**Шаги для воспроизведения ошибки:**

1. Взять кв
2, Попробовать пообщаться с нпс

**Текущее обновление ядра:**

209

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by sega693** [comment]
ты ведь уже сам писал про этот кв https://github.com/VirginTeam/WotlkCore/issues/990
