### ISSUE TITLE
[Рейд] Цитадель Ледяной Короны (Режимы сложности)

### ISSUE THREAD

**Issue by Santaria94** [VirginTeam/WotlkCore#1042]
**Ссылки и комментарии:**

http://ru.wowhead.com/icecrown-citadel
https://forum.wowcircle.com/showthread.php?t=205570
https://wowraider.net/message/1191

> В Цитадели Ледяной Короны доступны рейдовые подземелья для 10 и 25 игроков. Одолев всех противников в рейдовом подземелье, игроки получают возможность задействовать режим повышенной сложности для того или иного босса.

> I am not sure you are understanding how the system will work.
We are going back to two difficulty modes - 10-player and 25-player. You choose one, enter the raid, get to a boss, and you can not select between Normal and Heroic mode for this boss. Then you get to the next boss, and you can select again. All of this, of course, is assuming your raid leader has killed Arthas on the same difficulty. If he is not, then all of the bosses will be defaulted to Normal.

> In the upcoming patch we are adding a new feature to the Icecrown raid instance that allows the raid leader to change the instance's difficulty setting on a boss per boss basis. The way the raid leader chooses to switch is the same as now, by right-clicking on the character portrait. The difficulty settings can be changed from inside Icecrown Citadel, with some restrictions. For example, you cannot change the difficulty in combat or during certain events specified by our design team. To enable the ability to change the raid difficulty to heroic, you must first defeat the Lich King on normal mode, as doing so unlocks the heroic version of this raid instance. There is no heroic version of trash; meaning changing the difficulty will only affect boss difficulty.
We chose this particular functionality because we didn't want to use the Trial of the Crusader method, and have four versions on a raid of this size. We felt the Ulduar method of having to know a certain trick to do on the boss was difficult to communicate and tied too heavily to achievements. We might eventually convert Trial of the Crusader over to this new system but Ulduar and Naxxramas will likely never change.

**Что работает не так?**

На данный момент существует четыре независимых друг от друга сохранения рейда - 10 об, 10 гер, 25 об и 25 гер.

**Как должно работать?**

Должно быть только два сохранения в неделю - 10 и 25.
В рамках одного сохранения должна быть возможность выставлять обычную или героическую сложность тому или иному боссу.

**Текущее обновление ядра:**

210

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by ForesterDev** [comment]
Это глобальная фича всех пираток. Не будет изменено
