### ISSUE TITLE
[Игровая механика] Отхил на бг и в открытом мире

### ISSUE THREAD

**Issue by kalipsa988** [VirginTeam/WotlkCore#1044]
**Ссылки и комментарии:**

-

**Что работает не так?**

На бг отхил ниже на 10% чем в открытом мире
https://www.youtube.com/watch?v=xxRI5kqoCPs&t=11s вот видео с сегодняшнего бг
1:36 - кинул хоту на бг, тики можно увидеть на иконке персонажа
2:40 - кинул хоту в открытом мире

**Как должно работать?**

Отхил на бг и в открытом мире должен быть одинаковым

**Шаги для воспроизведения ошибки:**

1. Кинуть хоту в открытом мире
2. Кинуть её же на бг
3. Увидеть разницу

**Текущее обновление ядра:**

12.07.18

**Comment by gmKroshka** [comment]
Рекомендуем к изучению
http://wowwiki.wikia.com/wiki/Patch_3.3.2
