### ISSUE TITLE
Квест Открыть огонь!

### ISSUE THREAD

**Issue by Psihomag** [VirginTeam/WotlkCore#1046]
**Ссылки и комментарии:**

http://ru.wowhead.com/quest=10911/%D0%BE%D1%82%D0%BA%D1%80%D1%8B%D1%82%D1%8C-%D0%BE%D0%B3%D0%BE%D0%BD%D1%8C
Добавьте ссылки с wowhead.com или db.logon3.com на проблемные задания, NPC, заклинания и т.д. 

**Что работает не так?*
Даже после 20 снарядов портал не уничтожается.
Количество мобов такое что в 1 персонажа держать их очень проблематично.
Не виден урон по порталу хотя урон по мобам на лицо.
Фактический результат — тот, который вы наблюдаете 
В конечном счете мобы просто убиват пушку.
Портал так и не загорается.
Даже в пати с 80 лвл мобы все равно пробегают к пушке.
**Как должно работать?**
Количество мобов уменьшено.
Портал загорается и считается засчитаным после 5-10 выстрелов по нему.
Ожидаемый результат — то, чего вы ожидали при выполнении ваших действий. Процесс правильной работы

**Шаги для воспроизведения ошибки:**

1. уменьшение кол-ва мобов в 2 раза
2. Портал загорается от 7-8 выстрелов
3. после загорания считается засчитаным

**Текущее обновление ядра:**

Можно посмотреть в игре, введите в чат команду .server info и скопировать строку начиная с Build с номером и датой. Не забывайте указывать, Live Server или PTR Server, где проводилось тестирование.

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by gmKroshka** [comment]
https://github.com/VirginTeam/WotlkCore/issues/852
