### ISSUE TITLE
[Задание] ID 12261 - Отрезать пути к отступлению

### ISSUE THREAD

**Issue by Razama1234** [VirginTeam/WotlkCore#1050]
**Ссылки и комментарии:**

http://db.logon3.com/?quest=12261

**Что работает не так?**

Не засчитывает квест, хотя пишет, что тотем заряжен.

**Как должно работать?**

Как только появится надпись, что тотем заряжен, можно идти сдавать квестодателю.

**Шаги для воспроизведения ошибки:**

1. Взять квест
2. Защищать тотем до полной зарядки.
3. При появлении надписи, что тотем заряжен, квест не засчитан.

**Текущее обновление ядра:**

Build 210 2018-07-09 14:47:52 +0400

**Comment by gmKroshka** [comment]
https://github.com/VirginTeam/WotlkCore/issues/908
