### ISSUE TITLE
[Задание] ID 11702 - Король Мргл-Мргл (Орда)

### ISSUE THREAD

**Issue by Santaria94** [VirginTeam/WotlkCore#1054]
**Ссылки и комментарии:**

http://db.logon3.com/?quest=11702

**Что работает не так?**

Текст завершения задания:

> Наконец-то прибыла помощь! Судя по твоему виду, ты из Альянса.
Это не плохо... у вас умелые воины. Именно это нам и нужно, в больших количествах.

**Как должно работать?**

> Наконец-то прибыла помощь! Судя по твоему виду, ты из Орды?
Это неплохо… ваши – хорошие воины. Именно это нам и нужно, причем в больших количествах.

**Текущее обновление ядра:**

210

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by gmKroshka** [comment]
Будет применено в обновлении
