### ISSUE TITLE
Admiral Odesyus not working questchain 

### ISSUE THREAD

**Issue by mennelvagor** [VirginTeam/WotlkCore#1059]
I've met the problem with quest in Azuremyst Islands

Quest giver is Admiral Odesyus, located on Odesyus's Landing. 
After completing main quest chains the quest giver have to give me the quest "Bloodcurse legacy", which is new quest chain. The Admiral did not give me the quest and i cant start the quest chain "Bloodcurse legacy" on Bloodmyst Islands (finishing quest Bloodcurse legacy - Capitan Edward Hanes, and starting from him the new quest chain)

**Comment by Rorshah** [comment]
http://db.logon3.com/?quest=9671
Admiral doesn't give this quest but Messenger Hermesius!
