### ISSUE TITLE
[Игровая механика] - Поплавок в рыбной ловле 

### ISSUE THREAD

**Issue by kalipsa988** [VirginTeam/WotlkCore#1060]
**Ссылки и комментарии:**

http://db.logon3.com/?skill=356

**Что работает не так?**

При ловле рыбы, неважно где и при каких условиях, при 10-20 забросах непременно произойдет тот, при котором поплавок неактивен, т.е. рыба "клюет", однако клик по поплавку ни к чему не приводит
**Как должно работать?**

Должен кликаться во все моменты

**Шаги для воспроизведения ошибки:**

1. Сделать много забросов
2. Иногда попадать на неактивный поплавок

**Текущее обновление ядра:**
24.07.2018

**Comment by Kodekc** [comment]
Скрипт рыбной ловли очень кривой и очень старый

**Comment by kalipsa988** [comment]
14.03.19
теперь 100% поплавок не рабочий

**Comment by MiceRus** [comment]
Все никак не поправят. Неужели это так сложно?

**Comment by Kodekc** [comment]
Исправлялось, на сколько актуален репорт?

**Comment by kalipsa988** [comment]
настолько, что вы новые репорты сегодня открывали по этой теме, ток перефразировали там все, а суть та же

**Comment by GmAlleria** [comment]
#1760
