### ISSUE TITLE
[Предмет] ID 34815 - Фиал свежей крови

### ISSUE THREAD

**Issue by Santaria94** [VirginTeam/WotlkCore#1062]
**Ссылки и комментарии:**

http://db.logon3.com/?item=34815
http://ru.wowhead.com/item=34815

> Долбила этого дядьку минут 40, благо ресается быстро. Не выпало ни разу :/ 
Взяла квест //ru.wowhead.com/?quest=11633 - выпало сразу же

> та же самая ситуация. пока шпили не обследовал и не сдал их, фиал не падал

> подтверждаю, пока не сделаешь кв с плащом фиал не падает

**Что работает не так?**

Падает с вероятностью 35% в любое время.

**Как должно работать?**

Должен падать 100%, но только после взятия и выполнения задания - http://db.logon3.com/?quest=11633

**Текущее обновление ядра:**

213

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by Ewropa** [comment]
не падает предмет ни в какое время ,пока не сделаешь задание 11633, баг не воспроизводится
