### ISSUE TITLE
[Подземелье] Ульдуар - Йогг-Сарон

### ISSUE THREAD

**Issue by MedoOf** [VirginTeam/WotlkCore#1064]
**Ссылки и комментарии:**

http://db.logon3.com/?npc=33288
**Что работает не так?**

На 3 фазе, Йогг откидывает всех из мили зон.

**Как должно работать:**
Не должен откидывать. Хз какие тут пруфв нужны, но вот ссылочка на воврайдер и видосик Фёрсткила. 
https://wowraider.net/message/46/Тактика-Йогг-Сарон-%28Yogg-Saron%29%2C-Ульдуар
https://youtu.be/N1Nct6outZ8 видно и миликов и петов
https://youtu.be/ZyuuBwpOfbQ видно и миликов и петов бьющих боса в мили.
Хз кстати, если не нужно делать новые репорты, на 2 фазе щупальца появляются в Йогге и эвейдятся, такого быть не должно, щупальца должны появляться за пределами щита боса.
Лучи смерти должны передвигаться за игроком через 4 тика после появления, но видимо у них ограничена площадь по которой они должны двигаться, т.к. на видео движение небольшое и бьет только в точке прикосновения к земле, четко видно как сова и шп стоят рядом и их не дамажит. У нас луч не двигается, дамажит не в точке прикосновения а с небольшим радиусом, чего быть недолжно.
А еще у нас слишком много черепков в комнатах. Рекомендую посмотреть первую часть видео https://youtu.be/iatGk4TOlEA
UPD: https://www.youtube.com/watch?v=A1cmF1AQ_rk 4.08.2010, еще нет препатча каты. четко видно кота бьющего Йогга.
https://www.youtube.com/watch?v=grT9Awoud_U видно как перед килом сквозь Йога бегают добивающие его и верещащие китайцы.
**Шаги для воспроизведения ошибки:**

1. Перевести Йогга на 3 фазу
2. Пойти попробывать побить его миликом
3. Плакать на плече у девушки

**Текущее обновление ядра:**

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by ForesterDev** [comment]
http://ru.wowhead.com/npc=33288/%D0%B9%D0%BE%D0%B3%D0%B3-%D1%81%D0%B0%D1%80%D0%BE%D0%BD#comments:id=713788

Третья фаза: The Head of the Beast
Мили-дпс могут быть отброшены Йогг-Сароном, когда атакуют его.

По сниффам, на нем висит отбрасывающая аура http://ru.wowhead.com/spell=64022, которая имеет периодичность 1 сек.

**Comment by MedoOf** [comment]
Посмотрите видео, там видно как петы, милики бьют боса, а на одном из видео видно как перед убийством в течении секунд 5 сквозь него бегают различные игроки. Могут быть это явно не отбрасывание сразу когда подходишь, либо у нас завышен радиус этой ауры или она имеет вероятность срабатывания на офе не 100%. Я же не зря выложил несколько разных видео.

**Comment by Jigglypuff715** [comment]
Melee же должны фокусить Бессмертных стражей, и дпсить Йогг-Сарона, только если Бессмертных стражей нет. Ниже пост посмотрите пжалуйсто. Этот же человек пишет

**Comment by Jigglypuff715** [comment]
В течение этой фазы Йогг-Сарон будет кастовать Взгляд безумца, который будет отображаться в качестве фиолетовых лучей между Йогг-Сароном и игроками, смотрящими на него. Этот каст продолжается 4 секунды, по истечении которых дпс могут снова повернуться лицом к боссу. Это – основная причина, по которой хилеры должны всё время смотреть в другую сторону. У взгляда также имеется кулдаун в 12 секунд.

Йогг-Сарон будет также спавнить Бессмертных стражей, которые должны быть оттанкованы и быстро убиты. При спавне они будуть бить хорошо одетого танка на ~25к, но их урон зависит от количества здоровья: чем меньше у них здоровья, тем слабее их удары. Если Торим является одним из помощников, Бессмертных стражей можно убить, в ином случае их нужно танковать в течение всей третьей фазы. Йогг-Сарон будет кастовать Сгущение тьмы для лечения Бессмертных стражей, когда их количество здоровья становится малым. Если Бессмертные стражи танкуются в 20 или менее метрах от Йогг-Сарона, он также будет получать лечение от этого заклинания.

Третья фаза в основном является зерг-фазой, в которой вы должны быстро убить Йогг-Сарона. Кастеры должны фокусить только Йогг-Сарона, и помогать с Бессмертными стражами, только когда они заполоняют милишников. Melee же должны фокусить Бессмертных стражей, и дпсить Йогг-Сарона, только если Бессмертных стражей нет.

**Comment by Jigglypuff715** [comment]
+ при проке комнаты шторма, на видео видно, что черепки не достают ренжой к центру комнаты, у нас центр комнаты шторма = минус почти всё здравомыслие

**Comment by MedoOf** [comment]
Снимите лэйбл нид пруфы, на видео четко видны петы которых вообще не откидывает в течении 20 секунд, https://www.youtube.com/watch?v=grT9Awoud_U с 0:14 и до убийства босса стоит справа волк ханта и бьет Йога. Также там видно слева ретрика, адк и фурика которые бьют босса, из которых откинуло только 1 раз ретрика и то спустя 7 секунд его появления на видео: 0:11-0:18 откидка. 
https://www.youtube.com/watch?v=A1cmF1AQ_rk 6:35 медведь стоит прямо в Йоге и агрит стражей. 6:35-6:42 фурик бежит вдоль Йога и бьет его, откидок нет. 6:44-7:03 кот бьет Йога, плюс появляется видимость фурика рядом с ним. 7:14 вновь тот же кот бьет того Йога на ТОМ ЖЕ САМОМ МЕСТЕ, ЕГО НИРАЗУ НЕ ОТКИНУЛО!

**Comment by MedoOf** [comment]
Если по комнатам, лучам смерти и щупальцам, которые появляются в боссе и невосприимчивы ни к чему, нужны отдельные багрепорты напишите пожалуйста. Но там и так все четко видно. П.С. ВОВХЕД БАЗА ДАННЫХ ОФА, НА ОФЕ СЕЙЧАС ПРЕПАТЧ БФА, МОГУ ЛИ Я НАПИСАТЬ БАГРЕПОРТ И ПОТРЕБОВАТЬ СЕБЕ УРОН КАК НА БФА И ХОДИТЬ СОЛО ФАРМИТЬ ЛИЧА?

**Comment by MedoOf** [comment]
http://www.worldoflogs.com/reports/hv9wkqdo9shzpwnm/details/206/?s=14844&e=14911 Бой состоялся 21.03.2010. Босса били фурик, рога, энх, лок, хант, сова и бдк танк. Четко в логах видно все удары фурика, комбача, энха и даже бдк. Также видно как били древни совы и пет ханта.

**Comment by ForesterDev** [comment]
![image](https://user-images.githubusercontent.com/11771800/43246608-38b0fa6a-90c3-11e8-97da-7cc0fc10e991.png)

Йогг-Сарона и сейчас можно бить в мили-зоне, и чтобы не отбрасывало, надо стоять на максимальной дистанции. А отбрасывать должно тех, кто войдет во внутрь модельки Йогга. Слегка подкорректирую дистанцию активации отбрасывания, но в остальном все работает правильно

**Comment by MedoOf** [comment]
На вашем скрине вторая фаза, на нем щит и он должен отбрасывать все верно. Репорт же про 3 фазу, когда щит с Йогга спадает, проверьте ее, пожалуйста.

**Comment by ForesterDev** [comment]
https://youtu.be/A1cmF1AQ_rk?t=397 видно как на 3 фазе откидывает. Проблема не в том, что он откидывает. Проблема в том, что на 3 фазе у нас отсутствует дистанция ближнего боя до Йогга как таковая. Это будет исправлено в обновлении. Отбрасывание убрано не будет, но дальность его срабатывания будет уменьшена согласно оффу. Ждите применения обновления
