### ISSUE TITLE
[NPC] ID 23876 - Спора

### ISSUE THREAD

**Issue by Santaria94** [VirginTeam/WotlkCore#1065]
Ссылки и комментарии:

http://db.logon3.com/?npc=23876
https://www.youtube.com/watch?v=OWf7JngyPKg

Что работает не так?

Заселение NPC. Их должно быть намного больше 8.

Как должно работать?

Должно быть больше спор.

Текущее обновление ядра:

213

**Comment by Kodekc** [comment]
[Существа] ID 23876 - Спора
* Перезаселены. Было = 8 Стало = 15

Изменения будут применены в ближайшем обновлении
