### ISSUE TITLE
[NPC] ID 24229 - Завывающий смерч

### ISSUE THREAD

**Issue by Santaria94** [VirginTeam/WotlkCore#1066]
Ссылки и комментарии:

http://ru.wowhead.com/npc=24229
http://db.logon3.com/?npc=24229

Что работает не так?

Заселено всего 2 элементаля.

Как должно работать?

Должно быть намного больше.

Текущее обновление ядра:

213

**Comment by Kodekc** [comment]
[Существа] ID 24229 - Завывающий смерч
- Перезаселены. Было = 2 Стало = 12
- Добавлено пару маршрутов движения
Изменения будут применены в ближайшем обновлении
