### ISSUE TITLE
[NPC] ID 3886 - Остроклык Мясник

### ISSUE THREAD

**Issue by kalipsa988** [VirginTeam/WotlkCore#1068]
**Ссылки и комментарии:**

http://db.logon3.com/?npc=3886
**Что работает не так?**

Может находиться в любом месте инста 

**Как должно работать?**

Должен находиться только кухне, во дворе после двери слева вход

**Шаги для воспроизведения ошибки:**

1. Зайти в ктк
2. Походить по инсту

**Текущее обновление ядра:**

25.07.2018

**Comment by Kodekc** [comment]
На основании чего выдвинуто предположение о именно таких местах его появления?

**Comment by kalipsa988** [comment]
как я понял багается скрипт перемещения
![wowscrnshot_022119_184257](https://user-images.githubusercontent.com/29568428/53181526-c092df80-3608-11e9-9354-ab7a65ec58b1.jpg)

**Comment by kalipsa988** [comment]
![wowscrnshot_022119_184312](https://user-images.githubusercontent.com/29568428/53181539-c8eb1a80-3608-11e9-8f3f-b1f16f86d1bf.jpg)

**Comment by kalipsa988** [comment]
в итоге он пропал в текстурах и появился в другой части инста
![wowscrnshot_022119_184740](https://user-images.githubusercontent.com/29568428/53181761-42830880-3609-11e9-9e3e-d4852b6f9209.jpg)

**Comment by kalipsa988** [comment]
> На основании чего выдвинуто предположение о именно таких местах его появления?

на скрине с вовхеда, где босс стоит на кухне.
в любом случае такого перемещения по инсту быть не должно

**Comment by d3rkt8mple** [comment]
Недавно проходил ктк, тоже самое было, босс в первой комнате, до двери с выходом на площадь был, пришел через текстуры.
