### ISSUE TITLE
[Подземелье] Ульдуар - Генерал Везакс

### ISSUE THREAD

**Issue by ghost** [VirginTeam/WotlkCore#1071]
**Ссылки и комментарии:**
http://ru.wowhead.com/spell=63277/темное-сокрушение#used-by-npc 

**Что работает не так?**

Изредка непонятным образом босс забагивается и не кастует Темное сокрушение вообще. Как и из-за чего это происходит не понятно, в ренже обычно по 8 человек. Каст может пропасть посреди боя и вновь вернуться в любой момент, может вообще не возобновиться до убийства Везакса, может вообще не пропадать и работать нормально.
Поставьте метку нужны пруфы, как только у меня появится видео где видно что каст отсутствует я залью его.

**Как должно работать?**

Каст у босса должен быть постоянно в соответствии с его таймерами.

**Шаги для воспроизведения ошибки:**

Причина забагивания неизвестна. Видео пруфа нет. Появятся доказательства залью в этот репорт. Мб кто то другой закинет видосик где видно что босс не кастует.
**Текущее обновление ядра:**

Можно посмотреть в игре, введите в чат команду .server info и скопировать строку начиная с Build с номером и датой. Не забывайте указывать, Live Server или PTR Server, где проводилось тестирование.

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by MedoOf** [comment]
http://www.worldoflogs.com/reports/rjoh0nd08pvmwyrc/
![wowscrnshot_092318_182521](https://user-images.githubusercontent.com/31200901/45931916-bdbe9080-bf7d-11e8-924c-39e00b92b6d3.jpg)
Лог и скрин с рейда за 23.09.2018. В ренже стояло 8 человек, все остальные стояли во фрейме босса на момент его пула. Единственный каст сокрушения прошел когда из фрейма выбежало пара человек, после того как они забежали обратно касты прекратились. Также за весь бой не было ни одного каста вытягивания жизни, видимо причина отсутствия такая же как и у сокрушения.
ВОЗМОЖНО это связано с тем что кроме 8 человек все остальные стоят во фрейме, а может быть и нет)
