### ISSUE TITLE
[Игровая механика] - Аукционы фракций

### ISSUE THREAD

**Issue by GylbertMage** [VirginTeam/WotlkCore#1073]
**Ссылки и комментарии:**

Неблизлайк аукционы.

**Что работает не так?**

Везде один аукцион с налогом 15%.

**Как должно работать?**

Должно быть три аукциона Орда/Альянс/Гоблины
У фракционных аукционов должен быть налог 5%

Ну или если уж объединили все аукционы в один, то тогда и сделайте почту межфракционную, хотя бы в рамках одного аккаунта.

**Текущее обновление ядра:**

Build 213 2018-07-23

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by kalipsa988** [comment]
Такой аук фича л3 вроде как, а предложения в дискорде предлагают

**Comment by GylbertMage** [comment]
Об ошибках игры мне сказали писать сюда! А это ничто иное, как ошибка игры, которая влияет на баланс игры!. Раньше я мог спокойно перекинуть в другую фракцию реагенты/вещи твинку, а сейчас все заполонили чертовы боты, которые воруют все за доли секунды! Поэтому я прошу откатить свою "чудесную" фичу и сделать близлайк, либо сделайте что-нибудь с ботами или сделайте межфрационную почту.

**Comment by kalipsa988** [comment]
Гоблинский аук был межфракционным

**Comment by GylbertMage** [comment]
Как минимум при близлайке - межфракционных аукционов будет меньше. Мне легче будет вычислить ботоводов и зачистить там аукционистов при необходимости. А сейчас допустим в Даларане могут поставить перса и я с этим даже ничего сделать не могу.

**Comment by Rorshah** [comment]
зачистить аукционистов идея хорошая. А как сам-то перекидывать без них будешь ?
Или ты думаешь поставить 5 ботов(10-го уровня) возле каждого непосильная задача ?

**Comment by GylbertMage** [comment]
Будут на всех висеть, то просто зайду в другое время... Опять же определять наличие ботов будет намного проще, а это самое главное. Обеспечить безопасный перенос вещей будет намного проще, а боты через некоторое время сами пропадут, ибо уже такого улова как сейчас у них не будет.

**Comment by GylbertMage** [comment]
Помню времена когда были нормальные аукционы. Вообще никаких проблем не было. А сейчас помойка, налог 15% от продажи и вещи нихрена не переправить...

**Comment by Rorshah** [comment]
Если боты не стоят круглосуточно, то это не боты.
А борьба с ботами и аук - это вещи несвязанные.

Аук соединили по причине малого онлайна. Альянсовский совсем пустой станет
если опять разделить. Не дай бог это произойдет.
Могу предложить перекидывать свои ценные вещи
на 30% меньше текущей ауковской. Перекупать их никто не будет, а налог
за безопасность получится не такой уж и большой.

**Comment by GylbertMage** [comment]
т.е. ты хочешь сказать, что онлайн в .server info рисованный и людей раза в 2-3 меньше на самом деле?

**Comment by Rorshah** [comment]
Я хочу сказать подели количество слотов на три и получишь раздельный аук альянса.

**Comment by GylbertMage** [comment]
Ну тогда господа админы и разработчики, если уж у вас и впрямь так все плохо с онлайном, то вас можно понять. Но если вы все же решились пойти на крайние меры, отклонились от близлайка, то подумайте все-таки над межфракционной почтой, как сделали это ваши партнеры с соседного реалма. Очень удобная штука, игрокам нравится.

**Comment by Kodekc** [comment]
Это не баг, это фича нашего логона

**Comment by GylbertMage** [comment]
хорошие персонажи - ничем не выделяются, приносят пользу. весело наверно будет, когда только такие и останутся.
https://cdn.discordapp.com/attachments/412316469721038858/472864712233713664/5757.png
