### ISSUE TITLE
[Достижение] ID 1297 - Хадонокс низвергнут

### ISSUE THREAD

**Issue by Santaria94** [VirginTeam/WotlkCore#1077]
**Ссылки и комментарии:**

http://db.logon3.com/?achievement=1297

> Убейте Хадонокса в _героическом режиме_, прежде чем он заткет паутиной верхние двери, мешая появляться новым существам.

**Что работает не так?**

Засчитывается на обычном уровне сложности.

https://cdn.discordapp.com/attachments/412316469721038858/472435153852039179/454646.png

**Как должно работать?**

Должно засчитываться только в героике.

**Текущее обновление ядра:**

213

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by ForesterDev** [comment]
Исправлено, будет применено в обновлении
