### ISSUE TITLE
[Предмет] ID 44151 - Поводья синего протодракона

### ISSUE THREAD

**Issue by Santaria94** [VirginTeam/WotlkCore#1078]
**Ссылки и комментарии:**

http://db.logon3.com/?item=44151
http://db.logon3.com/?npc=26693

**Что работает не так?**

Прописан в луте обычной сложности подземелья, причем шанс выпадения немного выше, чем в героике.

**Как должно работать?**

Поводья синего протодракона должны выпадать только в героической сложности подземелья.

**Текущее обновление ядра:**

213

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by kalipsa988** [comment]
а есть какие-то пруфы, что он в об падает ?
ссылаться на одно БД, такое себе

**Comment by ForesterDev** [comment]
Исправлено, будет применено в обновлении
