### ISSUE TITLE
[Задание] ID 7622 - Баланс Света и Тени

### ISSUE THREAD

**Issue by sega693** [VirginTeam/WotlkCore#108]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**
http://db.logon3.com/?quest=7622
http://wowroad.info/?quest=7622 
http://ru.wowhead.com/quest=7622

**Что работает не так?**

Не появляются мобы. Ничего не происходит вообще.

**Как должно работать?**

Должны появляться мобы
https://www.youtube.com/watch?v=IrPy3efZPTo

**Шаги для воспроизведения ошибки:**

1. Надеть http://db.logon3.com/?item=18646
2. Взять квест

**Текущее обновление ядра:**
Build 153 2017-04-13 14:06:16 +0400
Live

**Comment by Trombocid** [comment]
Я всё еще жду кв =\

**Comment by Trombocid** [comment]
Zzz...

**Comment by Trombocid** [comment]
http://forum.wowcircle.com/showthread.php?t=499756 тема уже с довольно основательной бородой, хоть бы слух какой относительно её реализации

**Comment by farbik** [comment]
будет ли фикс в ближайшем времени?
или сделайте просто чтобы квест автоматом защитывало.

**Comment by Trombocid** [comment]
К слову, желающие пройти сей дивный квест, так никуда и не делись.

**Comment by gmOverfire** [comment]
Апать смысла нет, поверьте :)

**Comment by Trombocid** [comment]
Отчего же. Когда-нибудь просто решат прибегнуть к старому, проверенному временем и безотказному способу - импу.

**Comment by gmOverfire** [comment]
Уж чего-чего, а автокомплитов на logon3 не будет точно.

**Comment by farbik** [comment]
прошло полтора года(

**Comment by Trombocid** [comment]
печаль тоска

**Comment by Santaria** [comment]
https://github.com/dalaranwow/dalaran-wow/issues/2436#issuecomment-117711869

**Comment by Kodekc** [comment]
https://github.com/TrinityCore/TrinityCore/issues/11961

**Comment by Climss** [comment]
Прошло 2.5 года, квест до сих пор не работает, когда ожидать ?

**Comment by Climss** [comment]
Актуально
Build 278 2019-11-01 17:15:07 +0400 Logon 3 x1 PvE

**Comment by Trombocid** [comment]
Актуально
Build 305 2020-06-09 22:27:39 +0400

**Comment by sega693** [comment]
Квест починили

**Comment by Kodekc** [comment]
Перепроверили? Нормально работает?

**Comment by sega693** [comment]
Да. Всё отлично, пару раз провалил даже :D Потом сделал
