### ISSUE TITLE
[NPC] ID 37129 - Крок Гроза Плети

### ISSUE THREAD

**Issue by Jigglypuff715** [VirginTeam/WotlkCore#1083]
**Ссылки и комментарии:**

http://db.logon3.com/?npc=37129
http://db.logon3.com/?npc=37126
Если не решить проблему, то возможно ли обойти её, открыв решетку или отвязав Крока от Свалны.
**Что работает не так?**

При вайпе на треше, который активирует Крока http://db.logon3.com/?npc=37129, треш ресается, убивается, а Крок становится на изначальную позицию и больше не запускается. Зачистка треша не помогает, Сестра Свална http://db.logon3.com/?npc=37126 не агрится без Крока, решетка к Валитрии не открывается - расход рейда. 

**Как должно работать?**

Как должно, ну видимо при вайпе на треше рейд не должен заканчиваться, учитывая, что весь треш не по близлайку. 2 хила сели попить ману, танки влетели - вайп, а если анбаф то вовсе..

**Шаги для воспроизведения ошибки:**

1. Заагрить треш у Крока, желательно до средины, побить, умереть.
2. Прибежать, посмотреть как Крок с ними дерется, убить треш, а Крок вернется где стоял вначале. Обидится и не пойдет дальше.
3. Лучше повторить пару раз, с наблюдений других следует, что не 100% багается, когда как.

**Текущее обновление ядра:**
х1 PvE
Build 213 2018-07-23 13:05:07 +0400

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by Rorshah** [comment]
Вроде Крок отагривается если не останется ни одного рейдового чувака с боем.
А если в рейде есть какой-нить афкашер, которого треш не трогает - то все ок.

**Comment by gmRial** [comment]
Исправлено, будет применено в обновлении.
