### ISSUE TITLE
[Задание] ID 12232 - Бомбардировка баллист

### ISSUE THREAD

**Issue by Santaria94** [VirginTeam/WotlkCore#1085]
**Ссылки и комментарии:**

http://ru.wowhead.com/quest=12232
https://www.youtube.com/watch?v=ztGojBWF2Hs&feature=youtu.be

**Что работает не так?**

Визуально остаются после уничтожения.

**Как должно работать?**

Должны взрываться и пропадать как на видео.

**Текущее обновление ядра:**

213

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by ForesterDev** [comment]
Исправлено, будет применено в обновлении
