### ISSUE TITLE
[Задание] ID 12285 - Без головы не возвращайся!

### ISSUE THREAD

**Issue by Santaria94** [VirginTeam/WotlkCore#1086]
**Ссылки и комментарии:**

http://ru.wowhead.com/quest=12285
http://ru.wowhead.com/npc=27951

> Адмирал не атакует - он по игровому событию не должен атаковать.

> Точно, адмирал НЕ АТАКУЕТ. После того, как начинаешь бить генерала адмирал вешает на себя Сферу защиты и ждёт, пока убьёшь генерала. После смерти генерала говорит пафосную речь, обещает встречу в Ледяной Короне, выходит из комнаты и исчезает.

**Что работает не так?**

Адмирала можно сагрить и он атакует находясь под неуязвимостью. Также отсутствует сценка после смерти Верховного генерала Аббендис.

**Как должно работать?**

Адмирал не должен атаковать. Должна быть сценка после смерти генерала Аббендис.

**Текущее обновление ядра:**

213

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by ForesterDev** [comment]
Реализовано, будет применено в обновлении
