### ISSUE TITLE
[Заклинание] id 72267 - Безумный выпад

### ISSUE THREAD

**Issue by MedoOf** [VirginTeam/WotlkCore#1089]
**Ссылки и комментарии:**

http://db.logon3.com/?spell=72267

Возможно также и заклинание со всех других сложностей:
http://db.logon3.com/?spell=72264
http://db.logon3.com/?spell=72265
http://db.logon3.com/?spell=72266

**Что работает не так?**

Завышен урон от способности, также периодический урон игнорирует броню игроков.
http://www.worldoflogs.com/reports/akssulmd26wcnh19/xe/?x=sourceName+%3D+"Кровавая+королева+Лана%27тель"%0D%0AAND+school+%3D+PHYSICAL
Ппал имеет или бис или около бис шмот и в рейде это примерно 70% снижения физурона.
Наш сервер: [18:01:01.652] Кровавая королева Лана'тель hits Стеркобилин 7959 (A: 10334)
[18:01:07.495] Кровавая королева Лана'тель Безумный выпад Furlola 32423 (A: 13352)
7959+10334 = 18293*0,75=13718, что не равняется 32423+13352=45775
[18:01:52.277] Кровавая королева Лана'тель hits Стеркобилин 19255
[18:01:54.213] Кровавая королева Лана'тель Безумный выпад Furlola 31702 (A: 2920, B: 2141)
19255 * 0,75=14442, но никак не 31702+2920+2141=36763

**Как должно работать?**

Способность должна наносить 75% урона от оружия, периодическая часть способности должна учитывать снижение урона от брони, т.к. является физической школой.
http://www.worldoflogs.com/reports/k9lp4yw68u6s1asl/xe/?x=sourceName+%3D+"Blood-Queen+Lana%27thel"%0D%0AAND+school+%3D+PHYSICAL
http://www.worldoflogs.com/reports/rt-fnpskaevlhr3lp63/xe/?s=7759&e=7974&x=sourceName+%3D+"Blood-Queen+Lana%27thel"%0D%0AAND+spell+%3D+"Delirious+Slash"%0D%0A

> [19:15:21.326] Blood-Queen Lana'thel Delirious Slash Riggnaros 4452 (A: 10848)
> [19:15:21.326] Riggnaros afflicted by Delirious Slash from Blood-Queen Lana'thel
> [19:15:24.351] Blood-Queen Lana'thel Delirious Slash Riggnaros 1809 (A: 235)
> [19:15:27.473] Blood-Queen Lana'thel Delirious Slash Riggnaros 2043
> [19:15:30.356] Blood-Queen Lana'thel Delirious Slash Riggnaros 2043
> [19:15:33.297] Blood-Queen Lana'thel Delirious Slash Riggnaros 2043
> [19:15:36.329] Blood-Queen Lana'thel Delirious Slash Riggnaros 2044
> [19:15:36.329] Blood-Queen Lana'thel's Delirious Slash fades from Riggnaros

http://www.worldoflogs.com/reports/c2s9xig393of1ky9/xe/?s=4339&e=4554&x=sourceName+%3D+"Blood-Queen+Lana%27thel"%0D%0AAND+spell+%3D+"Delirious+Slash"%0D%0A

> [23:18:28.158] Blood-Queen Lana'thel Delirious Slash Feraal 7661 (A: 8924)
> [23:18:28.158] Feraal afflicted by Delirious Slash from Blood-Queen Lana'thel
> [23:18:31.137] Blood-Queen Lana'thel Delirious Slash Feraal 2137
> [23:18:34.218] Blood-Queen Lana'thel Delirious Slash Feraal 2137
> [23:18:37.232] Blood-Queen Lana'thel Delirious Slash Feraal 2137
> [23:18:40.146] Blood-Queen Lana'thel Delirious Slash Feraal 2137
> [23:18:43.142] Blood-Queen Lana'thel Delirious Slash Feraal 2137
> [23:18:43.142] Blood-Queen Lana'thel's Delirious Slash fades from Feraal
> 
> [23:20:12.850] Rayelle afflicted by Delirious Slash from Blood-Queen Lana'thel
> [23:20:15.952] Blood-Queen Lana'thel Delirious Slash Rayelle 2322
> [23:20:18.900] Blood-Queen Lana'thel Delirious Slash Rayelle 2321
> [23:20:21.970] Blood-Queen Lana'thel Delirious Slash Rayelle 2580
> [23:20:24.833] Blood-Queen Lana'thel Delirious Slash Rayelle 2580
> [23:20:27.855] Blood-Queen Lana'thel Delirious Slash Rayelle 2579
> [23:20:27.855] Blood-Queen Lana'thel's Delirious Slash fades from Rayelle
> 
> [23:20:05.995] Rayelle gains Ancestral Fortitude from Ailayn
> [23:20:21.063] Ailayn's Ancestral Fortitude fades from Rayelle

Я не представляю какие еще нужны пруфы, если брать исходный урон от доты как 7000-9000 и урон получаемый по логам от 1700 до 2600, причем урон с 1го боя отличается по танку друиду и танку паладину, то предположив что по паладину:
2322/0,9(в рейде был ршам, следовательно на танке был http://db.logon3.com/?spell=16237)=2580, что подтверждается логами и временем спадения бафа
Продолжаем: 2322/0,9/0,94(http://db.logon3.com/?spell=20470 )/0,97(http://db.logon3.com/?spell=25899)/0,97(http://db.logon3.com/?spell=63869)/0,97(http://db.logon3.com/?spell=53711)=3007 - урон который должен получить паладин, без учета всех его талантов и бафов рейда на % снижение урона.
Таким образом получаем что урон от (7000-3007) 3993 до (9000-3007) 5993 срезался чем-то иным.
Рассчитываем процент снижения урона 3993/7000 = 0,57. 5993/9000 = 0,67.
Получить снижение урона на 57-67% возможно только при прожатии способностей с большими кулдаунами, а урон от дот части всегда колеблется от 1700 до 2600 примерно.
Снижение урона броней танка паладина в рейде колеблется от 0.6 до 0.7, Следовательно можно сделать вывод что урон от дот части срезается броней.

**Шаги для воспроизведения ошибки:**

1. Шаг один
2. Шаг два
3. Шаг три

**Текущее обновление ядра:**

31.07.2018. 213 

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by ForesterDev** [comment]
http://et.worldofwarcraft.wikia.com/wiki/Bleed

bleed effects cannot be resisted and ignore armor

**Comment by MedoOf** [comment]
В вики указаны эффекты кровотечений от игроков, если посмотреть логи с ланы везде урон от доты гораздо ниже чем в базе данных, это можно объяснить только снижением от брони, поскольку находиться под % снижением всего урона в течении такого длительного боя невозможно. Тем более уже известна практика когда близы сделали светлую магию только для игроков, а для боссов заменили ее на огонь (валькиры в ивк)

**Comment by MedoOf** [comment]
Откройте репорт, если даже дота не снижается броней. То способность наносит явно не 75% урона от оружия:
Наш сервер: [18:01:01.652] Кровавая королева Лана'тель hits  Стеркобилин 7959 (A: 10334)
[18:01:07.495] Кровавая королева Лана'тель Безумный выпад Furlola 32423 (A: 13352)
7959+10334 = 18293*0,75=13718, что не равняется 32423+13352=45775
[18:01:52.277] Кровавая королева Лана'тель hits  Стеркобилин 19255
[18:01:54.213] Кровавая королева Лана'тель Безумный выпад Furlola 31702 (A: 2920, B: 2141)
19255*0,75=14442, но никак не 31702+2920+2141=36763
Способность при ПРЯМОМ УДАРЕ (речь не о доте от нее сейчас) либо наносит завышенный в 3-4 раза урон, либо игнорирует броню танка. Скорее всего она игнорирует броню, ПРЯМОЙ удар точно не должен игнорировать броню.

**Comment by MedoOf** [comment]
Отвечу той же ссылкой: http://et.worldofwarcraft.wikia.com/wiki/Bleed
AbilitiesEdit
Warrior
Blood Frenzy
Deep Wounds
Rend
Rogue
Garrote
Rupture
Druid
Lacerate
Pounce
Rip
Rake
Hunter
Piercing Shots
Hunter - Cat
Rake
Hunter - Raptor
Savage Rend
Так и не нашел там http://db.logon3.com/?spell=72267

http://www.worldoflogs.com/reports/rt-fnpskaevlhr3lp63/xe/?s=7759&e=7974&x=sourceName+%3D+"Blood-Queen+Lana%27thel"%0D%0AAND+spell+%3D+"Delirious+Slash"%0D%0A

> [19:15:21.326] Blood-Queen Lana'thel Delirious Slash Riggnaros 4452 (A: 10848)
> [19:15:21.326] Riggnaros afflicted by Delirious Slash from Blood-Queen Lana'thel
> [19:15:24.351] Blood-Queen Lana'thel Delirious Slash Riggnaros 1809 (A: 235)
> [19:15:27.473] Blood-Queen Lana'thel Delirious Slash Riggnaros 2043
> [19:15:30.356] Blood-Queen Lana'thel Delirious Slash Riggnaros 2043
> [19:15:33.297] Blood-Queen Lana'thel Delirious Slash Riggnaros 2043
> [19:15:36.329] Blood-Queen Lana'thel Delirious Slash Riggnaros 2044
> [19:15:36.329] Blood-Queen Lana'thel's Delirious Slash fades from Riggnaros

http://www.worldoflogs.com/reports/c2s9xig393of1ky9/xe/?s=4339&e=4554&x=sourceName+%3D+"Blood-Queen+Lana%27thel"%0D%0AAND+spell+%3D+"Delirious+Slash"%0D%0A

> [23:18:28.158] Blood-Queen Lana'thel Delirious Slash Feraal 7661 (A: 8924)
> [23:18:28.158] Feraal afflicted by Delirious Slash from Blood-Queen Lana'thel
> [23:18:31.137] Blood-Queen Lana'thel Delirious Slash Feraal 2137
> [23:18:34.218] Blood-Queen Lana'thel Delirious Slash Feraal 2137
> [23:18:37.232] Blood-Queen Lana'thel Delirious Slash Feraal 2137
> [23:18:40.146] Blood-Queen Lana'thel Delirious Slash Feraal 2137
> [23:18:43.142] Blood-Queen Lana'thel Delirious Slash Feraal 2137
> [23:18:43.142] Blood-Queen Lana'thel's Delirious Slash fades from Feraal

> 
> [23:20:12.850] Rayelle afflicted by Delirious Slash from Blood-Queen Lana'thel
> [23:20:15.952] Blood-Queen Lana'thel Delirious Slash Rayelle 2322
> [23:20:18.900] Blood-Queen Lana'thel Delirious Slash Rayelle 2321
> [23:20:21.970] Blood-Queen Lana'thel Delirious Slash Rayelle 2580
> [23:20:24.833] Blood-Queen Lana'thel Delirious Slash Rayelle 2580
> [23:20:27.855] Blood-Queen Lana'thel Delirious Slash Rayelle 2579
> [23:20:27.855] Blood-Queen Lana'thel's Delirious Slash fades from Rayelle

[23:20:05.995] Rayelle gains Ancestral Fortitude from Ailayn
[23:20:21.063] Ailayn's Ancestral Fortitude fades from Rayelle

Я не представляю какие еще нужны пруфы, если брать исходный урон от доты как 7000-9000 и урон получаемый по логам от 1700 до 2600, причем урон с 1го боя отличается по танку друиду и танку паладину, то предположив что по паладину: 
2322/0,9(в рейде был ршам, следовательно на танке был http://db.logon3.com/?spell=16237)=2580, что подтверждается логами и временем спадения бафа
Продолжаем: 2322/0,9/0,94(http://db.logon3.com/?spell=20470 )/0,97(http://db.logon3.com/?spell=25899)/0,97(http://db.logon3.com/?spell=63869)/0,97(http://db.logon3.com/?spell=53711)=3007 - урон который должен получить паладин, без учета всех его талантов и бафов рейда на % снижение урона.
Таким образом получаем что урон от (7000-3007) 3993 до (9000-3007) 5993 срезался чем-то иным. 
Рассчитываем процент снижения урона 3993/7000 = 0,57. 5993/9000 = 0,67.
Получить снижение урона на 57-67% возможно только при прожатии способностей с большими кулдаунами, а урон от дот части всегда колеблется от 1700 до 2600 примерно.
Снижение урона броней танка паладина в рейде колеблется от 0.6 до 0.7, Следовательно можно сделать вывод что урон от дот части срезается броней. А ссылка разработчика приведена на эффекты кровотечений для игровых спеков и не относится к боссам, в частности Ланатель.

**Comment by xARCHIMEDESx** [comment]
В принципе автор прав, пруфы железобетонные. Никак по другому не объяснить уменьшение этого урона, кроме как броня срезает его, не получается. Хоть это и блид, но логи офа говорят, что должен снижатся урон. Мое предположение - или это исключение, или это на самом деле не блид, а дота с физическим уроном просто, на тики которой действуют все эффекты снижения физ урона.
