### ISSUE TITLE
[NPC] id37955 - Кровавая королева Лана'тель

### ISSUE THREAD

**Issue by MedoOf** [VirginTeam/WotlkCore#1090]
**Ссылки и комментарии:**

http://db.logon3.com/?npc=37955

**Что работает не так?**

Занижен урон от автоатаки в сложности 25гер

http://www.worldoflogs.com/reports/akssulmd26wcnh19/details/211/?s=5049&e=5281

**Как должно работать?**
http://www.worldoflogs.com/reports/k9lp4yw68u6s1asl/details/198/?s=3697&e=3918

**Шаги для воспроизведения ошибки:**

1. Шаг один
2. Шаг два
3. Шаг три

**Текущее обновление ядра:**

31.07.2018 213

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by ForesterDev** [comment]
Подобные репорты не являются объективными. поскольку сложно оценить реальную ситуацию рейдов того времени, что был за танк, какие бафы, проки были на нем и т.д. Модификаторы урона не приходят в сниффах, это предположительные величины.
