### ISSUE TITLE
[Подземелье] ID 4812 - Цитадель Ледяной Короны (героический режим)

### ISSUE THREAD

**Issue by GmAlleria** [VirginTeam/WotlkCore#1095]
**Ссылки и комментарии:**

http://ru.wowhead.com/npc=36597/король-лич
http://db.logon3.com/?npc=36597

**Что работает не так?**

После окончания 50 попыток Король Лич продолжает запускаться

**Как должно работать?**

Должен оставаться на троне и не реагировать на запуск

**Шаги для воспроизведения ошибки:**

1. Израсходовать все попытки для убийства
2. Запустить

**Текущее обновление ядра:**

Последнее обновление ядра: Build 213 2018-07-23 13:05:07 +0400
Live Server

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by Santaria94** [comment]
Интересно, и много ли тех, кто тратит все 50 попыток? Ну и в целом на офе это по другому работало. Об/гер режимы сложности были привязаны к одному кд и переключались прямо внутри рейда, т.е. одних боссов можно было убивать в об, других в гер режиме. Если все попытки сгорали, то режим сложности автоматически переключался на обычный и переключить на героик больше нельзя было до следующего кд.

**Comment by ForesterDev** [comment]
Исправлено. Будет применено в обновлении
