### ISSUE TITLE
Не работает ачивка

### ISSUE THREAD

**Issue by Wet-panties** [VirginTeam/WotlkCore#1096]
**Ссылки и комментарии:**

http://ru.wowhead.com/achievement=1836/%D1%81%D1%82%D0%B0%D1%80%D1%8B%D0%B9-%D1%85%D0%B8%D1%82%D1%80%D1%8E%D0%B3%D0%B0

**Что работает не так?**

Выудить получается. Аддон и чат говорит, что поймал. А в итоге сумки пустые и ачивка не засчитывается.

**Как должно работать?**

Должно засчитать ачивку

**Шаги для воспроизведения ошибки:**

**Текущее обновление ядра:**

Build 213 2018-07-23 13:05:07 +0400

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by GylbertMage** [comment]
> Аддон и чат говорит, что поймал.
Ты опираешься на информацию с аддона, т.е. ты лично не присутствовал, не видел и не лутал его, что говорит о том, что ты использовал фишбот, причем корявый, который запорол вам ачивку. За это вам дружок уже полагается бан, а не проверка ваших фейковых репортов.

**Comment by Wet-panties** [comment]
Да с чего ради? 
Аддон просто собирает инфу о рыбе в локе. 
А лутать 7 у меня автосбор стоит в настрйоках интерфейса. Я просто тыкаю на поплавок. 
И написал, что в чате отобразилось то, что я собрал хитрюгу, но не было уведомления об ачивке. Чекнул сумку - пусто. Чекнул ачивки - тоже.
Прежде чем делать поспешные выводы, рекомендую раскинуть мозгами.

**Comment by sega693** [comment]
Там подтверждение требуется чтоб рыбу взять. Автолут тут никак не поможет. Так что вероятно чел выше прав, и ты ловил ботом, а он лут естественно не подтвердил. Аддон то записывает все что выудил, а не то, что слутал в сумку.
