### ISSUE TITLE
[Задание] ID 11996, 11999

### ISSUE THREAD

**Issue by Santaria94** [VirginTeam/WotlkCore#1099]
**Ссылки и комментарии:**

http://ru.wowhead.com/quest=11996
http://ru.wowhead.com/quest=11999

> This appears to be just a breadcrumb quest. I was able to pick up Rifle the Bodies in Agmar's Hammer before setting foot in the Tuskarr village. So, I don't think this quest is necessary to start the quest chain.

**Что работает не так?**

Для доступа к 11999 требуется выполнение 11996.

**Как должно работать?**

11999 должен быть доступен без преквестов.

**Текущее обновление ядра:**

213

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by gmKroshka** [comment]
Будет исправлено после обновления
