### ISSUE TITLE
[Задание] ID 12009 - Крабовые ловушки Туа'кеа

### ISSUE THREAD

**Issue by Santaria94** [VirginTeam/WotlkCore#1100]
**Ссылки и комментарии:**

http://db.logon3.com/?quest=12009

**Что работает не так?**

Отсутствуют тексты локализации.

**Как должно работать?**

Прогресс
> Сколько крабов тебе удалось раздобыть?

Завершение
> Я простой охотник. Мир внезапно как будто встал с ног на голову. Бессмыслица какая-то.
Надеюсь, тебе удастся поставить его на ноги обратно.

**Текущее обновление ядра:**

213

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by gmKroshka** [comment]
Будет применено после обновления
