### ISSUE TITLE
[Задание] ID 11958 - Чтоб ничего не пропало!

### ISSUE THREAD

**Issue by Santaria94** [VirginTeam/WotlkCore#1101]
**Ссылки и комментарии:**

http://db.logon3.com/?quest=11958

**Что работает не так?**

Отсутствуют тексты локализации.

**Как должно работать?**

Прогресс
> В последнее время природное равновесие то и дело нарушается!
Надеюсь, ты сумеешь помочь нам пережить изменение нашего образа жизни!

Завершение
> Не могу сказать, что мне приятно донимать тебя подобными просьбами. Однако мы делаем все, чтобы как можно быстрее подготовиться к переселению – хотя куда мы переселяемся, мы еще и сами не ведаем.
Мои колдуны говорят мне, что ты здесь затем, чтобы спасти эти земли от Того, Кто Бродит во Мраке.
Надеюсь, что ты спасешь не только земли, но и народы, живущие на них!

**Текущее обновление ядра:**

213

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by gmKroshka** [comment]
Будет исправлено после обновления
