### ISSUE TITLE
[Задание] ID 11960 - Планы на будущее

### ISSUE THREAD

**Issue by Santaria94** [VirginTeam/WotlkCore#1102]
**Ссылки и комментарии:**

http://ru.wowhead.com/quest=11960

**Что работает не так?**

Отсутствуют тексты локализации.

**Как должно работать?**

Прогресс
> Ну, сколько щенков можно было спасти за такое короткое время?

Завершение
> О, тебе удалось спасти многих! Спасибо тебе, <раса>.
Теперь волчеры получат шанс выжить среди нас. Если, конечно, мы сами вообще выживем.
Как думаешь, будет ли у тебя завтра время, чтобы спасти и других лохматиков?

**Текущее обновление ядра:**

213

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by gmKroshka** [comment]
Будет исправлено после обновления
