### ISSUE TITLE
[Задание] ID 12419 - Судьба Рубинового святилища драконов

### ISSUE THREAD

**Issue by Santaria94** [VirginTeam/WotlkCore#1106]
**Ссылки и комментарии:**

http://db.logon3.com/?quest=12419

**Что работает не так?**

Отсутствуют тексты локализации. 

**Как должно работать?**

Прогресс
> Приветствую тебя, <раса>. Я ощущаю присутствие моей рубиновой броши. Передай мне ее.
А что случилось с Далией?

Завершение

> Далию захватила Плеть? Печальный день для всех нас...
Я займусь поисками нового хранителя, когда святилище вновь станет нашим. Спасибо тебе за труды... Рубиновое святилище – священное для нас место, и твои свершения не будут забыты.
Приятно знать, что есть еще такие герои, как ты, я призову тебя в один прекрасный день. А пока он не наступил – пусть странствия укрепляют твою душу и тело.

**Текущее обновление ядра:**

213

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by gmKroshka** [comment]
Проверяйте после обновления
