### ISSUE TITLE
[Задание] ID 12497 - Галакронд и армия Плети

### ISSUE THREAD

**Issue by Santaria94** [VirginTeam/WotlkCore#1107]
**Ссылки и комментарии:**

http://db.logon3.com/?quest=12497

**Что работает не так?**

Отсутствует текст локализации.

Завершение
>[The bravery of mortals never fails to astound me. Death affixes its cold stare upon you and in return you rise to challenge its assertion! It is why your kind is so loved... and so hated.
Even though the Red Dragonflight is entrenched in a war with Malygos, there is something that we can do to help.]

 **Как должно работать?**

Завершение
> Храбрость смертных не перестает поражать меня. Смерть хватает тебя за горло ледяной хваткой, а в ответ ты бросаешь вызов ее притязаниям! За это вас так любят… и так ненавидят.
Хотя красные драконы ведут войну с Малигосом, есть кое-что, в чем мы можем помочь.

**Текущее обновление ядра:**

213

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by gmKroshka** [comment]
Исправлено. Проверяйте после обновления
