### ISSUE TITLE
[Заклинание] ID 51696 - Засада

### ISSUE THREAD

**Issue by Gooldark** [VirginTeam/WotlkCore#1108]
**Ссылки и комментарии:**

http://db.logon3.com/?spell=51696 – Засада
С вероятностью 100% успешное применение способностей "Внезапный удар" и "Удар в спину" заставит противника потерять равновесие, что увеличит время между его атаками в ближнем и дальнем бою на 20%, а также снизит скорость его передвижения на 50% на 8 сек.

**Что работает не так?**

При использовании Внезапный удар(http://db.logon3.com/?spell=48691) и Удар в спину(http://db.logon3.com/?spell=48657) эффект замедления не накладывается на цель

**Как должно работать?**

При использовании Внезапный удар(http://db.logon3.com/?spell=48691) и Удар в спину(http://db.logon3.com/?spell=48657) эффект замедления должен накладывается на цель

**Текущее обновление ядра:**

 Live Server - 05.08.2018

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by gmRial** [comment]
Исправлено, после обновления.
