### ISSUE TITLE
[Задание] ID 12447 - Обсидиановое святилище драконов

### ISSUE THREAD

**Issue by Santaria94** [VirginTeam/WotlkCore#1109]
**Ссылки и комментарии:**

http://db.logon3.com/?quest=12447

**Что работает не так?**

Отсутствует текст локализации.

Завершение
> [I'm trying to decide at which I'm more surprised... that you actually came to the aid of a Black Dragon or that you're still in one piece after speaking with Nalice.
Her words drip venom, but I suppose Wyrmrest can keep even our kind in check sometimes.
Or perhaps it's just the armies of the red dragonflight that are massed around her.]

**Как должно работать?**

Завершение
> Никак не могу решить, чему больше удивляться – тому, что ты действительно пришел на помощь черным драконам или что ты остался цел после общения с Нэлис.
Ее слова источают яд, но, я думаю, в Драконьем Покое могут иногда подумать и о нас тоже.
А может быть, просто вокруг нее кишмя кишат красные драконы...

**Текущее обновление ядра:**

213

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by gmKroshka** [comment]
Проверяйте после обновления
