### ISSUE TITLE
[Задание] ID 12030 - Старейшина Мана'лоа

### ISSUE THREAD

**Issue by Santaria94** [VirginTeam/WotlkCore#1116]
**Ссылки и комментарии:**

http://db.logon3.com/?quest=12030

**Что работает не так?**

Локализация

**Как должно работать?**

Завершение
> Я ждал тебя, <раса>. Я видел, как мимо пролетал твой дух, и почуял мистическое наблюдение, которое велось твоими глазами.
Твоя судьба и судьба калу'аков отныне связаны.

**Текущее обновление ядра:**

213

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by gmKroshka** [comment]
Будет исправлено после обновления
