### ISSUE TITLE
[Задание] ID 12017 - Наживка на крючке

### ISSUE THREAD

**Issue by Santaria94** [VirginTeam/WotlkCore#1120]
**Ссылки и комментарии:**

http://ru.wowhead.com/quest=12017

**Что работает не так?**

Локализация

**Как должно работать?**

Завершение
> Возрадуемся твоему успеху, мой юный друг! В воде разлита кровь – и это кровь нашего врага!
Этот старый рыбак навечно тебе благодарен, а также тебя ждет благодарность всех калу'аков, как только я сообщу им!
Вот, я настаиваю, чтобы ты хоть что-то взял себе в качестве награды. Пожалуйста!

**Текущее обновление ядра:**

213

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by gmKroshka** [comment]
Проверяйте после обновления
