### ISSUE TITLE
[Локализация] Задание ID 13668 - Серебряный Турнир

### ISSUE THREAD

**Issue by Santaria94** [VirginTeam/WotlkCore#1124]
**Ссылки и комментарии:**

http://db.logon3.com/?quest=13668

**Что работает не так?**

Завершение
>I have entered your name in the rolls, <название>. As an aspirant you will train with others who wish to compete in the tournament and hone your mounted combat skills. Once you have proven yourself, you will be allowed to enter the lowest rank of competition on behalf of your capital city.

 **Как должно работать?**

Завершение
>Я внес твое имя в списки, <название>. Теперь ты можешь тренироваться как и другие претенденты на участие в турнире и оттачивать навыки верхового поединка. Докажи, что ты достоин – и ты сможешь участвовать в соревнованиях низкого ранга, защищая честь своей столицы.

**Текущее обновление ядра:**

215

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by Anarom** [comment]
в соревнованиях низшего (было - низкого) ранга - предпоследняя строка.

**Comment by gmKroshka** [comment]
Проверяйте после обновления
