### ISSUE TITLE
[Локализация] Заклинание ID 44555

### ISSUE THREAD

**Issue by Santaria94** [VirginTeam/WotlkCore#1126]
Ссылки и комментарии:

http://db.logon3.com/?spell=44555

Что работает не так?

Название
Чары для наручей - интеллект II

Как должно работать?

Название
Чары для наручей - интеллект V

Текущее обновление ядра:

215

**Comment by ForesterDev** [comment]
Названия заклинаний заложены в DBC клиента, мы никак не можем на него влиять
