### ISSUE TITLE
[Группа предметов] ID 25653 и 32863 - Ездовой хлыст и Бич усмирителя небес

### ISSUE THREAD

**Issue by PlagueDoct0r** [VirginTeam/WotlkCore#1128]
**Ссылки и комментарии:**

https://ru.wowhead.com/item=25653 и http://ru.wowhead.com/item=32863

**Что работает не так?**

Заявленное повышение скорости транспортного средства не происходит.

**Как должно работать?**

Повышение скорости транспортного средства от действия обоих аксессуаров должно составлять +20%.

**Шаги для воспроизведения ошибки:**

1. На персонаже 70-того лвла, будучи полностью анбафнутым на повышение скорости транспортного средства, оседлать маунт и переместиться с условной точки А в точку Б, измерив при этом сколько времени на это потребовалось.
2. Повторить шаг 1, но уже с экипированными аксессуарами (https://ru.wowhead.com/item=25653 и http://ru.wowhead.com/item=32863).
3. Сравнить результаты.

**Текущее обновление ядра:**

Build 217 2018-08-09 16:14:07 +0400

**Comment by Santaria94** [comment]
http://db.logon3.com/?spell=51267
>...ваша скорость передвижения верхом повышается на 20%. Ускорение не суммируется с другими эффектами, увеличивающими скорость передвижения.

http://db.logon3.com/?spell=26023
>...повышает скорость передвижения пешком и верхом на 15%. Эффект не суммируется с другими, влияющими на скорость передвижения.

> http://www.wowwiki.com/Riding_Crop  I tend to trust wowwiki over most sites I visit. Take it for what it's worth.
* This trinket does NOT stack with other mount-speed increasing items.
* This trinket does NOT stack with mount speed increasing effects from spells such as Crusader Aura.
* It does give approximately 1.5% more mounted speed than the Enchant Gloves - Riding Skill/Mithril Spurs/Carrot on a Stick combo (and saves two bag spots). 
This has been tested with visual comparison to other players with varying degrees of speed enhancing items as well as with speed measuring in-game mods.

---

Таким образом увеличение могло быть максимум на 10%, при выполнении вышеназванных условий, т.е. если не было иных бафов на увеличение скорости передвижения.

**Comment by PlagueDoct0r** [comment]
Да, согласен, оказывается я ошибся по поводу "Повышение скорости транспортного средства от действия обоих аксессуаров должно составлять +20%". Но тем не менее, персонаж 70-того лвла, полностью анбафнутый на повышение скорости транспортного средства, не показал никаких отличий от скорости передвижения с экипированными аксессуарами, даже на +10%, соответственно они оба все еще не работают должным образом.
Мне нужно пересоздать тему с корректировками? Или и так будет понятна суть данного бага?

**Comment by gmRial** [comment]
Проверьте скорость макросом
`/script x=GetUnitSpeed("target") DEFAULT_CHAT_FRAME:AddMessage(format("Speed: %d yds/sec",x))`

**Comment by PlagueDoct0r** [comment]
После проверки скорости при помощи макроса указанный баг подтвердился.
При замере персонажем 70-того лвла, анбаф повышение скорости транспортного средства, результат составил 14 yds/sec, при аналогичном замере, но уже с экипированными аксессуарами (https://ru.wowhead.com/item=25653 и http://ru.wowhead.com/item=32863), ситуация не изменилась, и полученные данные вновь были равны 14 yds/sec.

**Comment by gmKroshka** [comment]
Будет исправлено после обновления
