### ISSUE TITLE
Только вперед

### ISSUE THREAD

**Issue by prince21rus** [VirginTeam/WotlkCore#1129]
**Ссылки и комментарии:**
https://wowroad.info/?quest=1190
Добавьте ссылки с wowhead.com или db.logon3.com на проблемные задания, NPC, заклинания и т.д. 

**Что работает не так?**
нет нпс который принимает квест https://wowroad.info/?object=20805 , только охраняемые чертяжи риззла
Фактический результат — тот, который вы наблюдаете 

**Как должно работать?**

Ожидаемый результат — то, чего вы ожидали при выполнении ваших действий. Процесс правильной работы
тот моб который дает квест должен совершить диверсию и выманить нпс который охраняет чертяжи, после чего они должны поменятся на https://wowroad.info/?object=20805
**Шаги для воспроизведения ошибки:**

1. Шаг один https://wowroad.info/?quest=1190
2. Шаг два попробовать его сделать 
3. Шаг три понять что он не работает

**Текущее обновление ядра:**
build 217 2018-08-09 16:14:07 +0400
Можно посмотреть в игре, введите в чат команду .server info и скопировать строку начиная с Build с номером и датой. Не забывайте указывать, Live Server или PTR Server, где проводилось тестирование.

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by gmRial** [comment]
Задание работает, для его выполнения требуется поговорить с НПЦ http://db.logon3.com/?npc=4709, который даст http://db.logon3.com/?quest=1191
Все это есть на вовхед, Вы могли посмотреть там для начала.
