### ISSUE TITLE
[NPC] ID 17556 - Смертоносный опустошитель

### ISSUE THREAD

**Issue by Mandragora1995** [VirginTeam/WotlkCore#1133]
**Ссылки и комментарии:**

http://db.logon3.com/?npc=17556

**Что работает не так?**

а) Нельзая приручить хантом
б) Не верная цветовая моделька

**Как должно работать?**

а) Ханты должны приручать его
б) Цвет модельки должен быть сине-зеленый 
**Шаги для воспроизведения ошибки:**

1. Найти вара с кв на него
2. Открыть клетку
3. Пытаться приручить

**Текущее обновление ядра:**
Build 217 2018-08-09 16:14:07 +0400

**Comment by Santaria94** [comment]
Обновленный окрас он получил в Катаклизме, приручаемым стал там же.
