### ISSUE TITLE
[Задание] ID 12330 - Слабое место Анатолия

### ISSUE THREAD

**Issue by Rorshah** [VirginTeam/WotlkCore#1136]
**Ссылки и комментарии:**

http://db.logon3.com/?quest=12330

**Что работает не так?**

Дротик в татьяну, садимся на лошадь, скачем к Саньку.
До этого момента все прекрасно.
Но квест не засчитывает.

**Как должно работать?**

Квест должно засчитывать

**Шаги для воспроизведения ошибки:**

1. Взять квест
2. Кинуть дротик и привезти Татьяну
3. Ничего не засчитывает.

**Текущее обновление ядра:**

[23:27:28] Ïîñëåäíåå îáíîâëåíèå ÿäðà: Build 217 2018-08-09 16:14:07 +0400

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by farbik** [comment]
Делал данный квест в октябре - все работало отлично, правда анимация разговора после выполнения данного квеста воспроизвелась как после выполнения следующего квеста в цепочке

**Comment by Kodekc** [comment]
В ближайшем обновлении будут применены улучшения к базовой реализации задания.

**Comment by Kodekc** [comment]
Перепроверьте, пожалуйста, в текущем обновлении.
