### ISSUE TITLE
[Заклинание] ID 2894 - Тотем элементаля огня

### ISSUE THREAD

**Issue by Adilogon3** [VirginTeam/WotlkCore#1137]
**Ссылки и комментарии:**

Копипаст из багтрекера логон 1. Элемы и энхи мертвы в пве из за этого бага.
http://wowroad.info/?spell=2894
Дамаг от данного тотема не отображается у других в рекаунте, а значит шаманы не дамажат, а значит спекайся в хила или иди лесом.
На логон починили, у нас нет.

**Что работает не так?**

Тотем элементаля огня не отображается у других в рекаунте.

**Как должно работать?**

должно отображаться

**Шаги для воспроизведения ошибки:**

1. Берешь друга в группу
2. Сравниваешь 2 рекаунта
3. Профит
http://radikal.ru/video/3xOB9eQEG12 
**Текущее обновление ядра:**

Текущее обновление ядра: 217 Сервер логон 3. х 1 пве.

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by MedoOf** [comment]
Это относится и ко второму элементалю, тоже не отображается в рекаунте http://db.logon3.com/?spell=2062

**Comment by gmRial** [comment]
Исправлено, после обновления.
