### ISSUE TITLE
[Задание] ID 12527 -  Прожорливые твари

### ISSUE THREAD

**Issue by Rorshah** [VirginTeam/WotlkCore#1140]
**Ссылки и комментарии:**

http://db.logon3.com/?quest=12527

**Что работает не так?**

после того как василиски накормлены они превращаются в 
http://db.logon3.com/?npc=28203#summoned-by
однако кристаллы с них не берутся.
Лута нет - квест не работает.

**Как должно работать?**

Те в кого превращаются василиски должны лежать на земле
с функцией лута - клик по ним дает в сумку кристалл

**Шаги для воспроизведения ошибки:**

1. набрать крыс
2. накормить василиска
3. лутнуть то что получилось из обожравшегося василиска

**Текущее обновление ядра:**

[17:34:01] Ïîñëåäíåå îáíîâëåíèå ÿäðà: Build 217 2018-08-09 16:14:07 +0400

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by Rorshah** [comment]
Подтверждаю.
Причем обожравшийся василиск никуда не пропадает.
Я прилетел там стоял чей-то чужой. Лутается прекрасно.
Убил его. Накормил нового. Сел на лошадь. И другой тоже лутается.
Надо будет попробовать Синдрагосу лутнуть на пару десятков таликов :)

**Comment by Climss** [comment]
Ораторам выше спасибо.
Актуально, квест адекватно не работает.
Build 273 2019-10-14 14:10:59 +0400 Logon 3 x1 PvE

**Comment by FilDru** [comment]
Квест вообще не работает. При сборе крысы не появляются в инвентаре.
Build 317 2020-07-27 15:01:40 +0400
