### ISSUE TITLE
[NPC] ID 29932 - Эк Cвирепый

### ISSUE THREAD

**Issue by zyxellgit** [VirginTeam/WotlkCore#1141]
**Ссылки и комментарии:**

http://db.logon3.com/?npc=29932 Эк Свирепый
**Что работает не так?**

ну он не бьется, точнее бьется но не убивается

**Как должно работать?**

должен умирать, зараза такой

**Шаги для воспроизведения ошибки:**

![wowscrnshot_081918_225114](https://user-images.githubusercontent.com/29210390/44354390-2b7d2580-a4c3-11e8-8021-9786611d3e05.jpg)

**Текущее обновление ядра:**

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by Santaria94** [comment]
Насколько я помню, он корректно убивается, если сначало убить Мураби - http://db.logon3.com/?npc=29305
Изначально вообще проход к нему должен быть закрыт и открываться только после смерти Мураби.

https://ru.wowhead.com/npc=29932
>The passage to Eck opens up after killing Moorabi. You dont need to do any other bosses.

**Comment by zyxellgit** [comment]
ну тогда дверку добавить надо наверно

**Comment by gmKroshka** [comment]
Будет исправлено после обновления
