### ISSUE TITLE
[Достижение] ID 4525 - Носите каски

### ISSUE THREAD

**Issue by Santaria94** [VirginTeam/WotlkCore#1143]
**Ссылки и комментарии:**

https://ru.wowhead.com/achievement=4525 

**Что работает не так?**

После одного из последних обновлений достижение стало делаться индивидуально, т.е. ачив засчитывается всем, кто не получил урона от сосулек, независимо от того, слакали ли одногруппники или нет. 

**Как должно работать?**

>Расчистите путь к Повелителю Плети Тиранию в Яме Сарона в героическом режиме. Во время первой попытки **ни один участник рейда** не должен получить урона от сосулек.

**Текущее обновление ядра:**

217

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by gmRial** [comment]
#4

**Comment by Santaria94** [comment]
уже не актуально, похоже починили
билд 222
