### ISSUE TITLE
[Задание] PVE: Hellfire Peninsula (Heroic)

### ISSUE THREAD

**Issue by Yabanan** [VirginTeam/WotlkCore#1152]
**Ссылки и комментарии:**

PVE: Hellfire Peninsula (Heroic) - Квест на монеты трансмогрификации.

**Что работает не так?**
После убийства последнего боса в подземелье Бастионы Адского Пламени - задание не засчитывает, критерий для выполнения задания не выполняется.
**Как должно работать?**

Пришел, увидел, победил - квест сделал.

**Шаги для воспроизведения ошибки:**

1. Шаг один - Придти в Бастионы Адского пламени (гер).
2. Шаг два - Убить последнего боса Омора Неодолимого.
3. Шаг три - Не получить прогресс в задании ...

**Текущее обновление ядра:**

Build 217 2018-08-09

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by gmKroshka** [comment]
https://github.com/VirginTeam/WotlkCore/issues/367
