### ISSUE TITLE
Уроки верховой езды в Оргриммаре не сработал (quest ID: 14086)

### ISSUE THREAD

**Issue by Paskudni** [VirginTeam/WotlkCore#1153]
Ссылка на квест:
https://ru.wowhead.com/quest=14086/%D1%83%D1%80%D0%BE%D0%BA%D0%B8-%D0%B2%D0%B5%D1%80%D1%85%D0%BE%D0%B2%D0%BE%D0%B9-%D0%B5%D0%B7%D0%B4%D1%8B-%D0%B2-%D0%BE%D1%80%D0%B3%D1%80%D0%B8%D0%BC%D0%BC%D0%B0%D1%80%D0%B5**

Не пришёл предмет по почте: https://ru.wowhead.com/item=46880/%D0%B1%D1%80%D0%BE%D1%88%D1%8E%D1%80%D0%B0-%D0%BE%D0%B1-%D1%83%D1%80%D0%BE%D0%BA%D0%B0%D1%85-%D0%B2%D0%B5%D1%80%D1%85%D0%BE%D0%B2%D0%BE%D0%B9-%D0%B5%D0%B7%D0%B4%D1%8B
Причина: повышение до 79 уровня через личный кабинет.
Прошу выслать мне предмет для начала квеста.

**Comment by gmRial** [comment]
Обучайтесь без предмета, он не обязательный.
