### ISSUE TITLE
[Предмет] 51964 - Пояс неутомимости

### ISSUE THREAD

**Issue by Mandragora1995** [VirginTeam/WotlkCore#1154]
**Ссылки и комментарии:**

http://db.logon3.com/?item=51964

**Что работает не так?**

Отсутствует метка волшебника 
+5 к выносливости, +5 к интеллекту, +6 к силе заклинаний
**Как должно работать?**

Должна быть эта метка

**Шаги для воспроизведения ошибки:**

1. Выбивать пояс из сумки

**Текущее обновление ядра:**

Последнее обновление ядра: Build 217 2018-08-09 16:14:07 +0400

Можно посмотреть в игре, введите в чат команду .server info и скопировать строку начиная с Build с номером и датой. Не забывайте указывать, Live Server или PTR Server, где проводилось тестирование.

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by Santaria94** [comment]
Не должно быть этой метки
https://ru.wowhead.com/item=51964

>Here Are The Random Enchantments
■...of the Bandit (37.8% chance)
+5 Agility, +5 Stamina, +10 Attack Power
■...of the Monkey (13.4% chance)
+6 Agility, +6 Stamina
■...of the Moon (11.9% chance)
+5 Intellect, +3 Stamina, +5 Spirit
■...of the Vision (11.9% chance)
+8 Spell Power, +4 Intellect, +2 Stamina
■...of the Wild (24.9% chance)
+10 Attack Power, +3 Stamina, +5 Agility

**Comment by Mandragora1995** [comment]
чё то странный факт, у всех поясов 6 меток у этого 1

**Comment by Mandragora1995** [comment]
тем более у плаща из сумки падает метка, которой в бд нет вообще, с символом солнца 4/2/4

**Comment by Mandragora1995** [comment]
тем более, у того же кольчужного пояса, судя по комментария вообще 3 метки только, так что такой себе пруф для отсутствия метки

**Comment by Santaria94** [comment]
>такой себе пруф
У вас же вообще нет никаких пруфов.

> у того же кольчужного пояса, судя по комментария вообще 3 метки только
> тем более у плаща из сумки падает метка, которой в бд нет вообще, с символом солнца 4/2/4
Это репорт по конкретному предмету - Пояс неутомимости. Если есть ошибки в других предметах, то нужно по ним отдельно писать репорты, либо сделать комплексный репорт по этой категории предметов и перечислить все ошибки с пруфами.

**Comment by Mandragora1995** [comment]
https://wowwiki.wikia.com/wiki/Vigorous_Belt_(level_25)
Всё что нашёл, только не понимаю, там вообще 4 метки

**Comment by Santaria94** [comment]
Я смотрю там деятели с нашего сервера наредактировали, сомнительный источник.
> **17:31, March 31, 2018**‎ **Kalipsa988** (Talk | contribs)

Разве что базовый вариант имеет ценность от 2010 года.
http://wowwiki.wikia.com/wiki/Vigorous_Belt_(level_25)?oldid=2173665

**Comment by Mandragora1995** [comment]
ну тогда я не знаю где тубу пруфы брать. На русской вики вообще пояса не нашёл

**Comment by Mandragora1995** [comment]
но все равно у всех поясов 6 меток, 2 метки на СПДшника, а у кожаного 5 меток и 1 на СПДшника, тут по логике вещей всё понятно, как по мне

**Comment by kalipsa988** [comment]
*Возможно можно подождать комментариев Романа, возможно он предоставит какие-то дополнительные пруфы, на основании которых он добавил эту метку на воввики.*
Прошу простить Романа за этот бред, в начале 18го года один человек скинул липовый скрин, если он остался, то скину, который он сам сделал похоже и выдал это за пруфы, а я поверил и не проверил. Извините за это.
А по поводу метки, чекаю старый вов хед, у всех поясов 6 меток, у кожаного 5, хоть там и катаклизм был, но количество меток не менялось, и метки 5/5/6 действительно не было. А поднимать шум из-за того, что кто-то успел выбить тканевый пояс с этой меткой на друля/шамана, не стоит. И ещё раз Простите Романа за вики
