### ISSUE TITLE
[Локализация] Задание ID 10104 - Опасения за судьбу Туурема

### ISSUE THREAD

**Issue by Santaria94** [VirginTeam/WotlkCore#1155]
**Ссылки и комментарии:**

http://db.logon3.com/?quest=10104

**Что работает не так?**

>[I'm flattered that your Broken friend considers me a scholar of his people's relics, but to be honest, I haven't had much chance to study them since my arrival here. It was certainly my intent, but when I arrived, I found that there were other matters that required my attention.]

**Как должно работать?**

>Я, разумеется, польщен тем, что твой друг-сломленный считает меня специалистом по реликвиям его народа, но, если честно, с тех пор, как я сюда прибыл, у меня почти не было возможности их изучать. Конечно, я явился сюда именно ради них, но по прибытии обнаружилось, что здесь есть много куда более важных дел...

**Текущее обновление ядра:**

217

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by gmKroshka** [comment]
Проверяйте после обновления
