### ISSUE TITLE
[Предмет] ID 23565 Облачение Круговерти Пустоты

### ISSUE THREAD

**Issue by Koshmar27** [VirginTeam/WotlkCore#1161]
Предмет
https://wowroad.info/?item=23565
из описания самого предмета:
Использование: вы защищены от всех физических атак и **заклинаний** в течение 6 секунд, но не можете атаковать или использовать физические способности.

Что работает не так?
 
Работоспособность почти идеальна, единственное что не так - пропускает магический дамаг и магический контроль во время действия эффекта предмета. На данный момент эффект как будто у БОПа (паладиновский), который блокирует только физ дамаг, хотя должно блочить весь дамаг и контроль.

Так же неисправна и аналогичная, но более слабая модель доспеха ID 23564
https://wowroad.info/?item=23564

Текущее обновление ядра:
217 
2018-08-09

**Comment by gmRial** [comment]
https://ru.wowhead.com/item=23565
https://ru.wowhead.com/spell=34518
1 в 1 как в нашей бд
http://db.logon3.com/?item=23565
http://db.logon3.com/?spell=34518

**Comment by Librariane** [comment]
Ошибка перевода.
https://www.wowhead.com/item=23565/embrace-of-the-twisting-nether
