### ISSUE TITLE
[Заклинание] ID 6392 - Тотем каменного когтя

### ISSUE THREAD

**Issue by kalambyr18** [VirginTeam/WotlkCore#1162]
**Ссылки и комментарии:**

http://db.logon3.com/?spell=6392

**Что работает не так?**

Вместе с нпс агрит на себя всяких белочек , кроликов (http://db.logon3.com/?npc=721) и прочую живность , что находится в радиусе действия, в итоге багает бой ! Непонятно потом где он что заагрил, бегай ищи этих животных!

**Как должно работать?**

Сомневаюсь что нпс типа http://db.logon3.com/?npc=721 тотем должен агрить.

**Шаги для воспроизведения ошибки:**

Заагрить любого нпс вместе с нпс типа http://db.logon3.com/?npc=721

**Текущее обновление ядра:**

217

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by Santaria94** [comment]
Не воспроизводится

**Comment by kalambyr18** [comment]
Тогда закрывай тему . Видать у меня одного такое

**Comment by kalambyr18** [comment]
стоит символ http://db.logon3.com/?item=45778 мб из за него такой эффект

**Comment by gmRial** [comment]
Оформите заголовок по шаблону https://youtu.be/N_7bwCYAc9s

**Comment by Kodekc** [comment]
Так какой алгоритм забагивания по итогу?
