### ISSUE TITLE
[Задание] ID 11436 - Полетаем?

### ISSUE THREAD

**Issue by Sornick88** [VirginTeam/WotlkCore#1163]
**Ссылки и комментарии:**
Задание ["Полетаем?"](https://ru.wowhead.com/quest=11436) не работает как должно.
**Что работает не так?**
При попытке использование квестового объекта Большая врайкульская гарпунная пушка с помощью кв [итема](https://ru.wowhead.com/item=34078) и  квестового объекта [Рычаг большого гарпуна](https://ru.wowhead.com/object=186894) появляется копье, на которое садится персонаж, НО копье неподвижно висит в воздухе рядом с пушкой.
**Как должно работать?**
[видео прохождения кв на офф серверах](https://www.youtube.com/watch?v=k69UG24ab-Y)
**Шаги для воспроизведения ошибки:**

1. получить квест ["Полетаем?"](https://ru.wowhead.com/quest=11436)
2. использовать кв  [итем](https://ru.wowhead.com/item=34078) на  квестовом объекте [Рычаг большого гарпуна](https://ru.wowhead.com/object=186894)
3. Получить неподвижное копье висящее в воздухе рядом с пушкой и сидящего на нем персонажа

**Текущее обновление ядра:**
Build 217 2018-08-09

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by Skellan** [comment]
Здравствуйте, когда наконец починят это задание? Или хотя бы сделать галочку, что задание выполнено, когда юзаешь рычаг управления гарпуном. Полгода пылится в журнале.

**Comment by Mranswer3** [comment]
Когда исправят этот кв?

**Comment by Kodekc** [comment]
Реализованы базовые скрипты. Могут быть незначительные визуальные недоработки, но в целом, задание можно будет выполнить. Изменения будут применены в ближайшем обновлении

**Comment by Skellan** [comment]
Только что проверил (04.03.2019, 15:55 по Москве). Задание РАБОТАЕТ. Спасибо.
