### ISSUE TITLE
Не рабочий квест  ID 13417     Братья Бронзобороды

### ISSUE THREAD

**Issue by sabo12** [VirginTeam/WotlkCore#1164]
**Ссылки и комментарии:**

https://ru.wowhead.com/quest=13417/%D0%B1%D1%80%D0%B0%D1%82%D1%8C%D1%8F-%D0%B1%D1%80%D0%BE%D0%BD%D0%B7%D0%BE%D0%B1%D0%BE%D1%80%D0%BE%D0%B4%D1%8B 

**Что работает не так?**

квест берется и больше ничего не происходит.никто никуда не летит. и вообще полный ноль.

**Как должно работать?**

Забраться ветролет и прикрывать Бранна от железных дворфов.

**Шаги для воспроизведения ошибки:**

1. Шаг один
2. Шаг два
3. Шаг три

**Текущее обновление ядра:**

Build 217 2018-08-09 16:14:07 +0400

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by gmRial** [comment]
#458
