### ISSUE TITLE
[Задание] ID 11494 - Заряженные молнией артефакты

### ISSUE THREAD

**Issue by Sornick88** [VirginTeam/WotlkCore#1165]
**Ссылки и комментарии:**
Квест [Заряженные молнией артефакты](https://ru.wowhead.com/quest=11494) 
**Что работает не так?**
успешное использование способности ["Сбор информации"](https://ru.wowhead.com/spell=44610) [квестового голема](https://ru.wowhead.com/npc=24825) на квестовый объект [Реликвия железных дворфов](https://ru.wowhead.com/npc=24824) не приводит к выполнению условий квеста.

**Как должно работать?**
успешное использование способности ["Сбор информации"](https://ru.wowhead.com/spell=44610) [квестового голема](https://ru.wowhead.com/npc=24825) на квестовый объект [Реликвия железных дворфов](https://ru.wowhead.com/npc=24824) увеличивает счетчик критерия выполнения квеста.
**Шаги для воспроизведения ошибки:**

1. Взять кв [Заряженные молнией артефакты](https://ru.wowhead.com/quest=11494) 
2. использовать верстак рядом с кв гивером - [Уолт](https://ru.wowhead.com/npc=24807)
3. В облике [голема](https://ru.wowhead.com/npc=24825) дойти до квестового объекта [Реликвия железных дворфов](https://ru.wowhead.com/npc=24824)  и использовать способность ["Сбор информации"](https://ru.wowhead.com/spell=44610)

**Текущее обновление ядра:**

Build 217 2018-08-09

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by gmRial** [comment]
#26
