### ISSUE TITLE
[Задание] ID 12527 - Прожорливые твари

### ISSUE THREAD

**Issue by Aggony26** [VirginTeam/WotlkCore#1168]
**Ссылки и комментарии:**
https://ru.wowhead.com/quest=12527/прожорливые-твари
Добавьте ссылки с wowhead.com или db.logon3.com на проблемные задания, NPC, заклинания и т.д. 

**Что работает не так?**
Кристаллы василисков не собираются
Фактический результат — тот, который вы наблюдаете 
При кормёжке василиска он превращается в спящего, которого нужно собрать, при сборе ничего не происходит, а сам василиск просто исчезает
**Как должно работать?**
При сборе спящего василиска квест должен засчитываться.
Ожидаемый результат — то, чего вы ожидали при выполнении ваших действий. Процесс правильной работы

**Шаги для воспроизведения ошибки:**

1. Взять квест
2. Накормить крысами василисков
3. Собрать их и сдать квест

**Текущее обновление ядра:**

Можно посмотреть в игре, введите в чат команду .server info и скопировать строку начиная с Build с номером и датой. Не забывайте указывать, Live Server или PTR Server, где проводилось тестирование.

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by gmKroshka** [comment]
https://github.com/VirginTeam/WotlkCore/issues/1140
