### ISSUE TITLE
[Предмет] ID 38660 - Колье нежизни

### ISSUE THREAD

**Issue by Aggony26** [VirginTeam/WotlkCore#1169]
**Ссылки и комментарии:**
https://ru.wowhead.com/item=38660/колье-нежизни
Добавьте ссылки с wowhead.com или db.logon3.com на проблемные задания, NPC, заклинания и т.д. 

**Что работает не так?**
Если верить базе знаний то шанс дропа 11%, после убитых 350+ мобов я понял что шанс там явно не 11%, 3 дня пытался выбить ожерелье - безрезультатно.
Фактический результат — тот, который вы наблюдаете 
Ожерелье просто не дропается
**Как должно работать?**
Ожерелье должно дропаться с определённых мобов
Ожидаемый результат — то, чего вы ожидали при выполнении ваших действий. Процесс правильной работы

**Шаги для воспроизведения ошибки:**

1. Убить моба
2. Лутануть с него ожерелье
3. Взять кв с ожерелья и радоваться жизни

**Текущее обновление ядра:**

Можно посмотреть в игре, введите в чат команду .server info и скопировать строку начиная с Build с номером и датой. Не забывайте указывать, Live Server или PTR Server, где проводилось тестирование.

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by gmKroshka** [comment]
Работает верно
Не учтены условия получения
