### ISSUE TITLE
[Заклинание] ID 20582 - Расторопность

### ISSUE THREAD

**Issue by kalipsa988** [VirginTeam/WotlkCore#1174]
**Ссылки и комментарии:**

http://db.logon3.com/?spell=20582

**Что работает не так?**

Не работает, в 5% меткости 0 мисов (не уклонения) по найт эльфу

**Как должно работать?**

По найт эльфу твоего уровня необходимо 7% меткости для 100% попадания, а не 5%

**Шаги для воспроизведения ошибки:**

1. Побить найта в 5% меткости
2. Увидеть отсутствие мисов, максимум уклоны

**Текущее обновление ядра:**

04.09.2018

**Comment by Garlem** [comment]
Если верить комментариям на вовхеде от 2010 года и многим знакомым пвп игрокам, то никакая меткость не перебьёт 2% шанс найт эльфов уклониться от физ ударов. Тоже самое с шансами мисснуть по ретрикам, блад эльфам, фрост магам и т.п.

**Comment by Garlem** [comment]
По поводу рабочести таланта.... я с 5% хита миссал бурей по дереву в мае. Как сейчас не знаю, возможно стоит больше ударов нанести

**Comment by Garlem** [comment]
Другой комментарий с вовхеда с отсылкой на глада. + об этом слышал на стриме от пвп-топов с логона 1.
From what I've been told by a friend who's a rank1 glad and hardcore pvper, you cannot make up for the 2% miss by stacking extra hit in pvp. This was told to me before 4.0 (during ICC), so I'm not sure if things have changed. If he was correct and this never changed, you will ALWAYS have a 2% chance to miss night elves in pvp. That's really powerful.

**Comment by Garlem** [comment]
Я не спорю с тем что должны быть -2% промаха и работают ли они в данный момент, просто пишу, что никакой меткостью они компенсироваться не должны.

**Comment by kalipsa988** [comment]
Ну такой себе пруф, друг говорил (англ комментарий с каты) и пвпшеры на л1

**Comment by Garlem** [comment]
Ну у Вас и этого нет :-)

**Comment by Morfem** [comment]
Стоит проверить взаимодействие этой пассивки с мастерством. Возможно пассивка работает, но работает как показатель "защита" получаемый от рейтинга защиты или разницы комбат/дэф навыка.

**Comment by kalipsa988** [comment]
Причем тут мастерство ? Оно на уклонение влияет только

**Comment by kalipsa988** [comment]
не актуально на 29.01.19, работает
