### ISSUE TITLE
[Заклинание] ID 56344 - На изготовку!

### ISSUE THREAD

**Issue by Gooldark** [VirginTeam/WotlkCore#118]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

ID 56344 - На изготовку!
С вероятностью 100% при срабатывании способностей "Замораживающая ловушка", "Замораживающая стрела" или "Ледяная ловушка" и с вероятностью 6% при нанесении периодического урона способностями "Обжигающая ловушка", "Взрывная ловушка" или "Черная стрела" 2 следующих применения способностей "Чародейский выстрел" или "Разрывной выстрел" не потребуют боеприпасов, маны и времени восстановления. Время восстановления эффекта – 22 сек.

**Что работает не так?**

 ID 56344 - На изготовку! срабатывает от Укус виверны(ID 19386) и Укус змеи(ID 1978)

**Как должно работать?**

D 56344 - На изготовку! должно иметь шанс сработать только при тике(эффект взрыва не входит в шанс прока) Обжигающая ловушка(ID 13795), Взрывная ловушка(ID 13813), Черная стрела(ID 3674)

**Текущее обновление ядра:**

18.04.2017. 153 билд

**Перенесено**

http://forum.wowcircle.com/showthread.php?t=613834

**Comment by ForesterDev** [comment]
Исправлено
