### ISSUE TITLE
[NPC] ID 13417 Сагорн Гривастый Странник <Наставник шаманов>

### ISSUE THREAD

**Issue by GmAlleria** [VirginTeam/WotlkCore#1184]
**Ссылки и комментарии:**

https://ru.wowhead.com/npc=13417 

**Что работает не так?**

Не отображается диалог на обучение

**Как должно работать?**

Отображение диалога "Научи меня путям духов"

**Шаги для воспроизведения ошибки:**

1. Начать диалог с Сагорном

**Текущее обновление ядра:**

Build 217 2018-08-09 16:14:07 +0400

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by gmRial** [comment]
Будет исправлено после обновления.
