### ISSUE TITLE
[Заклинание] ID 7744 - Воля Отрекшихся

### ISSUE THREAD

**Issue by kalipsa988** [VirginTeam/WotlkCore#1187]
**Ссылки и комментарии:**

http://db.logon3.com/?spell=7744 

**Что работает не так?**

Не накладывает 45-ти секундное кд на триньку

**Как должно работать?**

Патч 3.3.0 Примечания
Воля Отрекшихся теперь разделяет 45-секундное кулдаун с аналогичными эффектами, включая Медальон Орды, руны Титан-Кованные, Знаки Орды и т. Д.

**Шаги для воспроизведения ошибки:**

1. Юзануть сам спел
2. Увидеть отсутствие кд
3. Юзануть триньку

**Текущее обновление ядра:**

08.09.2018

**Comment by gmRial** [comment]
#86
