### ISSUE TITLE
[Игровая механика] Зачарование Фамильных плечей

### ISSUE THREAD

**Issue by sega693** [VirginTeam/WotlkCore#1188]
**Ссылки и комментарии:**
например плечи http://db.logon3.com/?item=42985 и чарка http://db.logon3.com/?item=28881

**Что работает не так?**
При отправке почтой по своему аккаунту пишет "Нельзя отправлять по почте персональные предметы"

**Как должно работать?**
Должны свободно передаваться по своему аккаунту. Но само зачарование должно быть неактивным до достижения определенного уровня персонажа

https://ru.wowhead.com/item=28881/начертание-дисциплины#comments:id=965557

> Blizz has gone to making shoulder enchants available to all of your characters (with appropriate level requirements to prevent OP twinks)...so you only have to do the rep (or honor/stone) grind on one toon.
> This applies to Sons of Hodir (req lvl 80), Wintergrasp (req lvl 80), Honor (req lvl 70), Violet Eye (req lvl 70), Aldor (req lvl 64), Scryer (req lvl 64), Argent Dawn (req lvl 55), and Zandalar Tribe (req lvl 55), enchants.
> 
> The enchants can be placed on gear worn by low levels (e.g. BoA gear), but the enchant will be red until the character reaches the required level. The BoA enchants (LK) can be mailed from character to character. For the non BoA enchants (PreBC and BC), you have to have the gear in your inventory to enchant it. It can not be applied through the trade window (so enchanting your lowbie's quest reward gear is out).

https://ru.wowhead.com/item=28889/великое-начертание-защиты#comments:id=712235

> With the change in shoulder-enchant mechanics in 3.1 this enchant can now be applied to BoA-shoulders!
> But you must be >lvl70 to benefit from the enchant but it will help in levelling from 70 to 80 at least.

https://ru.wowhead.com/item=28888/великое-начертание-отмщения#comments:id=712234:reply=101367

> No. After you buy and use it on the BoA shoulders and send it to an alt, the only thing that is required is being level 70 for it to be active. So If your main is exalted, I highly suggest you buy this enchant as soon as your alt dings 70. Since The Aldor/Scryer enchants are the best for any BoA shoulder. 

https://ru.wowhead.com/item=28885/начертание-отмщения#comments:id=949684

> Just enchant my https://www.wowhead.com/?item=42950 with it and it worked.
> The enchant is red and state that I need lvl 64 for the enchant to be active.
> I can still se them on my lvl 34 shaman.

**Шаги для воспроизведения ошибки:**
1. зачарить фамильные плечи
2. попытаться перекинуть почтой твинку

**Текущее обновление ядра:**
Build 217 2018-08-09 16:14:07 +0400

**Comment by ForesterDev** [comment]
Исправлено, будет применено в обновлении
