### ISSUE TITLE
[Заклинание] ID 54458 - Символ шипов

### ISSUE THREAD

**Issue by sega693** [VirginTeam/WotlkCore#1192]
**Ссылки и комментарии:**
http://db.logon3.com/?spell=58163 http://db.logon3.com/?item=43332 Символ
http://db.logon3.com/?spell=467 http://db.logon3.com/?spell=53307 шипы любого лвла

**Что работает не так?**
При попытке ребафнуть Шипы, когда остается более 10мин времени действия, выдает ошибку "Действует более сильное заклинание"

**Как должно работать?**
Должны нормально ребафаться до 1 часа
У паладина аналогичный глиф на кулак работает адекватно.

**Шаги для воспроизведения ошибки:**

1. поставить глиф
2. бафнуть себе шипы
3. попытаться ребафнуть

**Текущее обновление ядра:**
Build 217 2018-08-09 16:14:07 +0400

**Comment by ForesterDev** [comment]
Исправлено, будет применено в обновлении
