### ISSUE TITLE
[Достижение] Защитник Наару

### ISSUE THREAD

**Issue by IpsilonVanila** [VirginTeam/WotlkCore#1194]
**[Защитник Наару](https://ru.wowhead.com/achievement=432/защитник-наару#english-comments)**

На форуме нашел [пост (с гайдом](https://forum.wowcircle.com/showthread.php?t=800427)) что данное достижение работает, но к сожалению это не так. Выполнил всю цепочку квестов, в итоге достижение не получил.

На скриншоте автора, показано что достижение засчитано 6/24/18, актуально ли данное исправление на logo3, x1 PvE и возможно ли мне его еще получить?

**Текущее обновление ядра**
Build 217 2018-08-09 16:14:07 +0400

**Comment by Santaria94** [comment]
У л3 свое ядро и то, что реализовано на л1 может здесь не работать, как и наоборот.
К тому же, выполнение этого достижения не является близлайком на момент патча 3.3.5.

https://ru.wowhead.com/achievement=432
> После выхода патча 3.02 больше нет возможности получить этот титл и достижение.

**Comment by Librariane** [comment]
@IpsilonVanila
получение достижения при выполнении заданий в их версии на ВотЛК было реализовано лишь на серверах логона. У нас получение данного достижения возможно лишь при выполнении заданий бк-версии - т.е. только лишь в случае очень старых персонажей с начала 2009 года.

**Comment by xARCHIMEDESx** [comment]
Нууу, в нас куча вещей, которые не близз-лайк. Что мешает запилить ачивы по квестах на Защитника Наару и Длань Адала?

**Comment by Santaria94** [comment]
Эти ачивки выдавались по сути тем, кто сделал эти квесты еще на бк. А тут получается все кому не лень сделают 80-ми и весь сервер защитников наару и дланей адала. По мне так это бред. Если уж и делать не близлайк, то что-нибудь поинтереснее, например как награду за какой-нибудь эвент.

**Comment by xARCHIMEDESx** [comment]
@Santaria94 Ага, а Первый на сервере Лич25гер давать всем, кому не лень, это норм,да?)

**Comment by Santaria94** [comment]
Такое себе сравнение. Эту ачивку дают не просто за 25 гер, а за прохождение без зонального бафа 30%. Это дает стимул проходить рейд в более сложном режиме и далеко не каждая гильдия может себе это позволить, не говоря уже о том, чтобы брать туда кого попало.

**Comment by xARCHIMEDESx** [comment]
Ну как сказать, на Альянсе Пведракон даже с олл чатом делал) Ничего сложного там вообще нет. А если б эти две ачивки сделали доступными для игроков сейчас - ну думаю, что б проблемма была.

**Comment by kalipsa988** [comment]
а давайте закроем этот ложный репорт и пойдём обсуждать это всё в дискорд
