### ISSUE TITLE
[Задание] Он настоящий!

### ISSUE THREAD

**Issue by IpsilonVanila** [VirginTeam/WotlkCore#1195]
**Ссылки и комментарии:**

Не работает данный квест  [[Он настоящий!] ](https://ru.wowhead.com/quest=27221/он-настоящий)

**Что работает не так?**

НПЦ стоит на месте, но не принимает квест.

**Как должно работать?**

Он должен принимать квест.

**Текущее обновление ядра**
Build 217 2018-08-09 16:14:07 +0400

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by gmRial** [comment]
Задание работает, чистите кеш и перепроверяйте.
