### ISSUE TITLE
[Рейд] Черный Храм (ID 22948 - Гуртогг Кипящая Кровь)

### ISSUE THREAD

**Issue by Santaria94** [VirginTeam/WotlkCore#1196]
**Ссылки и комментарии:**

http://db.logon3.com/?npc=22948

**Что работает не так?**

На фазе боя "Ярость Скверны" босс накладывает на случайную цель одноименный баф Ярость Скверны. В целом все работает правильно, но целью этого заклинания могут быть выбраны питомцы, тотемы, стражи и т.д.

**Как должно работать?**

Данный баф должен накладываться только на игроков, ибо он является важной частью второй фазы, когда случайный участник рейда становится танком до конца этой фазы.

**Текущее обновление ядра:**

217

**Comment by gmKroshka** [comment]
Будет исправлено после обновления
