### ISSUE TITLE
[Группа заданий] ID 11595, 11597 - Оборона крепости Песни Войны

### ISSUE THREAD

**Issue by gmRial** [VirginTeam/WotlkCore#1203]
**Ссылки и комментарии:**

http://db.logon3.com/?quest=11596

http://db.logon3.com/?quest=11595
http://db.logon3.com/?quest=11597

**Что работает не так?**

Задания не выдаются и сдавать их некому.

**Как должно работать?**

Выдать задание должен http://db.logon3.com/?npc=25256
Сдать задание нужно http://db.logon3.com/?npc=25279

**Текущее обновление ядра:**

218

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by Santaria94** [comment]
**11596** открывается после выполнения - http://db.logon3.com/?quest=11586 (близлайк, работает)
>Just below from where you received the quest. Hes standing in the middle of the circle.
Leads to The Defense of Warsong Hold

**11595**, **11597** - косметические квесты, которые должны выдаваться вместо **11596**, если выполнены некоторые квесты классики. 
> Will only greet you like this if you have completed the quest from the Head of Nefarian. Curiously, i actually handed this head to the other guy in Orgrimmar, but Saurfang thought i gave it to him.

> Obviously, Saurfang will only say this is you have the Scarab Lord title. The reason he would recognise you is because Saurfang was the supreme commander of the forces in the AQ War Effort, so he won't be forgetting the guy who rang that gong.

**Comment by gmRial** [comment]
Репорт исключительно о 11595, 11597. 
Условия выдачи прописаны, но их банально некому выдавать и сдавать их так же некому (в случае прописи квеста ГМом).

**Comment by gmRial** [comment]
Будет исправлено после обновления.
