### ISSUE TITLE
[Задание] ID 13267 - Битва за Подгород

### ISSUE THREAD

**Issue by Rialzarre** [VirginTeam/WotlkCore#1206]
**Ссылки и комментарии:**

http://db.logon3.com/?quest=13267
http://db.logon3.com/?npc=31650

**Что работает не так?**

Задание не работает, некому сдавать, нет заселения, ивент не работает.

**Как должно работать?**

https://youtu.be/TwMSBSbe_ZM?t=85

**Текущее обновление ядра:**

218

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by gmKroshka** [comment]
https://forum.wowcircle.com/showthread.php?t=620622
