### ISSUE TITLE
[Задание] ID 6481 - Пробуждение земельника

### ISSUE THREAD

**Issue by cigaretko** [VirginTeam/WotlkCore#1210]
Не работает задание "Пробуждение земельника"

https://ru.wowhead.com/quest=6481/пробуждение-земельника

При нажатии через квестовый предмет "Колдовской кристалл резонита" на находящийся в конце пещеры розовый кристалл должен появиться враг "Гоггерок", но розовый кристалл недоступен для нажатия по нему и вследствие враг не может быть вызван.

Данный кристалл должен подсвечиваться при наведении на него и через нажание на него через квестовый предмет должен сработать призыв "Гоггерока".
Возможно в данной пещере просто отсутствует необходимый кристалл, для взаимодействия с ним.

**Текущее обновление ядра:**

Build 218 2018-09-20 11:38:14 +0400

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by gmRial** [comment]
Не то используете.
http://db.logon3.com/?item=16603 открывает http://db.logon3.com/?object=178145
![image](https://user-images.githubusercontent.com/26819342/46015084-cb455900-c0ea-11e8-8c65-326acdf7b300.png)
Закрыто.
