### ISSUE TITLE
Собачка лока (Заклинание : Пожирание магии)

### ISSUE THREAD

**Issue by Saan9** [VirginTeam/WotlkCore#1211]
Пишу по Причине того что в РС на Халионе Нельзя Вызывать СОбачку Так как Она ДИспелит . Но многие Скажут Просто Сними Авто ДИспел и всё Но Это непомогает Она Продолжает ДИспелить . Думаю Многих Локов Это БЕсит то что ПРиходиться на Хаионна вызывать Беса Вместо Собачки и Место Топа по дамагу ПРиходиться чучуть страдать и БЕгать с БЕсенкам .
(надеюс это мона Исправить)

**Comment by gmRial** [comment]
Оформите репорт, или он будет отклонён.

**Comment by sega693** [comment]
у всех петов автокаст долбанутый же

**Comment by gmRial** [comment]
В любом случае нужен оформленный репорт.

**Comment by Saan9** [comment]
кароче место того чтобы Просто Решить ПРоблему вы за Офармление Топите. Проблема Вся Изложена Почему НЕзя ПРосто ее решить я непонимаю

**Comment by kalipsa988** [comment]
# 1076 на всех петов работает похоже

**Comment by Morfem** [comment]
У кого-то здесь автокаст головного мозга.
1. Выключаем автокаст  пожирания магии (да и любой другой абилки) **в книге**, а не на спеллбаре.
2. Диспел не автокастит.
3. Вы великолепны.

**Comment by sega693** [comment]
1 садимся на маунта
2 слазим
3 открываем спелбук
4 о чудо, автокаст снова включен!
