### ISSUE TITLE
[Задание] ID 10832 - Обучение шитью из огненной чароткани

### ISSUE THREAD

**Issue by gmOpex** [VirginTeam/WotlkCore#1212]
**Ссылки и комментарии:**

https://ru.wowhead.com/quest=10832/

**Что работает не так?**

Использование квестого предмета производится без КД и позволяет бесконечно спамить квестовых НПС бесконечно и очень быстро.

**Как должно работать?**

После использования предмета на нем должно появляться КД на несколько секунд, информации 

**Шаги для воспроизведения ошибки:**

**Текущее обновление ядра:**

[21:33:23] Logon 3 WowCircle Development
[21:33:23] Последнее обновление ядра: Build 218 2018-09-20 11:38:14 +0400
[21:33:23] Игроков онлайн: 3287 (максимум: 4842). Игроков в очереди: 0 (максимум: 0).
[21:33:23] Продолжительность работы сервера: 1 Day(s) 23 Hour(s) 53 Minute(s) 50 Second(s).
[21:33:23] Серверная задержка: 48. Средняя серверная задержка: 19
[21:33:23] Следующее начисление очков арены: 30.09.2018  10:22

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by gmKroshka** [comment]
Будет исправлено после обновления
