### ISSUE TITLE
[Задание] ID 12097 - Сарастра, бич Севера

### ISSUE THREAD

**Issue by Pavlov718** [VirginTeam/WotlkCore#1217]
**Ссылки и комментарии:**
[Сарастра, бич Севера](http://db.logon3.com/?quest=12097)

**Что работает не так?**

Не происходит призыва [НПС Сараста](http://db.logon3.com/?npc=26858)

**Как должно работать?**

Мы должны начать разговор с [НПС Рокхан](http://db.logon3.com/?npc=26859) после чего он должен призвать [НПС Сараста](http://db.logon3.com/?npc=26858)
[Видео пример ](https://www.youtube.com/watch?time_continue=17&v=ymTure-c2uI)
**Шаги для воспроизведения ошибки:**

1. Берем квест
2. Начинаем диалог с [НПС Рокхан](http://db.logon3.com/?npc=26859)

**Текущее обновление ядра:**
218

**Comment by Ewropa** [comment]
А где это написано, что https://ru.wowhead.com/npc=26858 должен кто-то призывать? нип существует в мире и движется по определенному маршруту

```
От Username11 (1,509 – 3·20) 2010-05-04 (Обновление 3.3.3) |   |  
-- | -- | --
Сарастра - могучий ледяной змей, патрулирующая Драконий Погост. В то время как большинство ледяных змеев в этом регионе были с лёгкостью повержены Рокханом и его охотниками на драконов, Сарастра оказалась не простой добычей. У Рокхана кончились охотники и он стал набирать отважных путешественников, чтобы одолеть змея
```

**Comment by Ewropa** [comment]
нип есть на сервере и летает по маршруту

**Comment by Pavlov718** [comment]
Он то есть и летает, но после призыва он должен прилететь. Так даже указано в описани квеста.
