### ISSUE TITLE
[Подземелье] Старые предгорья Хилсбрада

### ISSUE THREAD

**Issue by Santaria94** [VirginTeam/WotlkCore#1224]
**Ссылки и комментарии:**

http://db.logon3.com/?zone=2367

https://ru.wowhead.com/npc=18723
https://ru.wowhead.com/npc=18725

http://db.logon3.com/?quest=10283
http://db.logon3.com/?item=25853

**Что работает не так?**

В подземелье отсутствуют **NPC 18723, 18725** на старте подземелья.

https://cdn.discordapp.com/attachments/412316469721038858/495863740185706506/WoWScrnShot_093018_134349.jpg

Так как **NPC 18723** выдает предмет **25853**, необходимый для эвента по освобождению Тралла, то пройти подземелье без него невозможно.

**Как должно работать?**

**NPC 18723, 18725** должны стоять в подземелье, координаты указаны по ссылкам на wowhead.

**Текущее обновление ядра:**

218

NPC пропали после применения хотфиксов по эвенту "Хмельной фестиваль"
Возможно связано с #661 , фикс того репорта был перед загрузкой обновлений по "Хмельному фестивалю"

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by Kodekc** [comment]
Этот репорт https://github.com/VirginTeam/WotlkCore/issues/661 содержит уже готовые изменения по этому подземелью, после установки на сервер, можете перепроверить ваш список багов. Пока вынужен закрыть его, как дубликат.
