### ISSUE TITLE
[Предмет] ID 11122 - Морковка на палочке

### ISSUE THREAD

**Issue by LifeLie0** [VirginTeam/WotlkCore#1232]
**Ссылки и комментарии:**

http://db.logon3.com/?item=11122#reward-from-quest

**Что работает не так?**

Не увеличивает скорость передвижения верхом

**Как должно работать?**

Увеличивать скорость передвижения верхом на 3% персонажам </=70 уровня

**Шаги для воспроизведения ошибки:**

1. Надеть триньку
2. Встать на "старте" с другим персонажем без триньки, начать забег
3. Увидеть, что скорость передвижения одинаковая

**Текущее обновление ядра:**

Build 221

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by gmKroshka** [comment]
Будет исправлено после обновления
