### ISSUE TITLE
[Заклинание] ID 31687 - Призыв элементаля воды

### ISSUE THREAD

**Issue by LifeLie0** [VirginTeam/WotlkCore#1234]
**Ссылки и комментарии:**

http://db.logon3.com/?spell=31687#modified-by

**Что работает не так?**

При передвижении мага на наземном транспорте, элементаль воды передвигается без увеличенной скорости и "багается" под портретом героя, если тот далеко уехал

**Как должно работать?**

При передвижении мага на наземном транспорте, должен двигаться с такой же скоростью

**Шаги для воспроизведения ошибки:**

1. Призвать элементаля воды
2. Сесть на транспорт, начать движение
3. Увидеть, что элементаль воды отстает от мага и багается под портретом

**Текущее обновление ядра:**

Build 221

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by LifeLie0** [comment]
Примерно такой же баг-репорт был, но там не совсем верно сказано. Исчезать он должен только тогда, когда маг на летающем транспорте

**Comment by Rorshah** [comment]
Если ты про тот:
https://github.com/VirginTeam/WotlkCore/issues/327
То пусть исчезает. Иначе борьба с трешем через который ты проскачешь будет вечной.

**Comment by LifeLie0** [comment]
Так поставил его на защиту и все. Не будет никого атаковать, пока сам не атакуешь. Можешь сам проверить

**Comment by Rorshah** [comment]
ну на данный момент мне все равно.
А вот когда я качался магом это было критично.
И лучше б он исчезал чем бегал рядом.
Но тот репорт именно элементаль с символом - когда он становится полноценным петом.

**Comment by ForesterDev** [comment]
Было исправлено в последнем обновлении
