### ISSUE TITLE
[Группа предметов] - Шаттратские настои

### ISSUE THREAD

**Issue by Santaria94** [VirginTeam/WotlkCore#1238]
**Ссылки и комментарии:**

http://db.logon3.com/?item=32898
http://db.logon3.com/?item=32899
http://db.logon3.com/?item=32900
http://db.logon3.com/?item=32901
http://db.logon3.com/?item=35716
http://db.logon3.com/?item=35717

>Действует как боевой и охранный эликсир одновременно. Эффект сохраняется после смерти.
Действует только в Крепости Бурь, Змеином святилище, Пещерах Времени в горе Хиджал, Черном храме и на Плато Солнечного Колодца

**Что работает не так?**

Когда персонаж покидает указанные локации, то баф настоев полностью пропадает, в том числе и после смерти, когда персонаж оказывается духом на кладбище.

**Как должно работать?**

Баф должен сохраняться на персонаже даже если он покинул рейдовую локацию, но эффект настойки в этом случае должен быть не активен.

**Шаги для воспроизведения ошибки:**

1. Выпить любой из указанных настоев в рейдовой локации.
2. Умереть и переместиться духом на кладбище, либо просто покинуть рейдовую локацию.
3. Проверить наличие бафа настойки.

**Текущее обновление ядра:**

221

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by Kodekc** [comment]
Какая-то доказательная информация есть к этому репорту? Мало просто написать, как должно работать, нужно на что-то ссылаться

**Comment by Santaria94** [comment]
В самом описании предметов написано, что баф от них сохраняется после смерти, но бонус активен только в рейдовых зонах. В комментариях вовхед нет ни одного упоминания, что если после смерти оказаться на кладбище, то баф полностью пропадет. Если бы пропадал, то наверняка хотя бы 1 коммент был бы с советом, что не нужно покидать тело, а подождать пока кто-нибудь из рейда воскресит.
