### ISSUE TITLE
[Игровая механика] Меткость

### ISSUE THREAD

**Issue by kalipsa988** [VirginTeam/WotlkCore#1242]
**Ссылки и комментарии:**

- 

**Что работает не так?**

На первый взгляд кажется, что всё работает нормально, но при капе меткости (5% в пвп) очень редко проходят миссы, замечал на лоу лв, там из уреза меткости только расовая найт эльфов, которая тоже не работает

**Как должно работать?**

При 5% в пвп не должны проходить миссы по противнику твоего уровеня(если он не найт эльф, тогда на 2% больше), а за разницу в 1 уровень, нужно на 1 % больше меткости для 100% попадания

**Шаги для воспроизведения ошибки:**

1. Собрать кап меткости
2. Поиграть против своего уровня
3. Очень маловероятно, но вылетит мисс

**Текущее обновление ядра:**

08.10.2018

**Comment by Kodekc** [comment]
Нет никаких расчётов в репорте, сидите, высчитывайте, раз задались вопросом меткости и хотите доказать ошибку

**Comment by Senatyan** [comment]
Высчитывай и показывай на манекене, а то у тебя не компьютер, а калькулятор который графику 2008 года не может вывезти!
