### ISSUE TITLE
[Игровая механика] Вход/Выход из мира в рейдах

### ISSUE THREAD

**Issue by Santaria94** [VirginTeam/WotlkCore#1243]
**Ссылки и комментарии:**

Вероятно актуально для большинства рейдов. Для полного подтверждения требуются дополнительные тестирования, особенно в ЦЛК/РС.

Если механизм этого бага подтвердится на Короле Личе, то проверьте, пожалуйста, заодно логи последних рейдов, которые делали анбафы.

**Что работает не так?**

Возможность включения в бой с боссом до 40 персонажей в течении одного боя. Возможность выдавать лут и достижения тем, кто не принимал активного участия в бою с боссом. Производится через махинации со входом/выходом из мира.

**Как должно работать?**

В бою с боссом должны участвовать только персонажи, которые присутствовали непосредственно при пуле босса. Все кто зашел в игровой мир после пула должны быть принудительно кикнуты из рейдовой зоны.

Персонаж, который вышел из игрового мира, должен по-прежнему считаться находящимся в рейдовой зоне до тех пор, пока не будет кикнут из рейдовой группы.

**Шаги для воспроизведения ошибки:**

Часть игроков основного состава, которые будут участвовать в бою с боссом, предварительно заходят в комнату с боссом и выходят из мира.
Вместо них заходят игроки (далее вагоны), которые не будут принимать активного участия в убийстве босса и производится пул босса. В этот момент фиксируется начальный состав рейда, который имеет право претендовать на лут с босса и получение достижений.
После пула и фиксации "начального состава", вагоны через второе окно делают релог и их выбивает из мира. После этого их персонажи больше не занимают места в подземелье.
Вместо них заходят игроки основного состава, которые предварительно выходили из мира (пункт 1) и доводят босса до низкого значения здоровья (1-5%)
В этот момент, когда до убийства босса остается совсем немного, часть игроков основного состава снова выходит из мира посредством релога через второе окно.
Вместо них заходят вагоны и добивают босса. Получают достижения и право на лут с босса.

**Текущее обновление ядра:**

221

**Comment by Rorshah** [comment]
В ЦЛК ты не зайдешь если идет бой с босом.
В описанном варианте даже когда вагон вышел из мира,
вновь зашедший окажется на кладбище.

**Comment by Rorshah** [comment]
Укажи конкретный инст в котором ты видел данную фишку.

**Comment by Kodekc** [comment]
Мне кажется, этот репорт описывает одну из старых теорий, если я ошибаюсь, то необходимо больше деталей, так как в таком виде ошибка не воспроизводится

**Comment by Santaria94** [comment]
В низкоуровневых рейдах, а также в ОС, ИК офнутые перед пулом персонажи успешно вводились в бой после его начала. Рейды в которых нужно чистить треш перед боссами, в том числе ЦЛК, не тестировались. ЦЛК на тестовом я самостоятельно вряд ли смогу протестировать, а на игровом не хочу подобные баги тестировать.

**Comment by Santaria94** [comment]
В ЦЛК получилось воспроизвести на Ребраде. Персонажа, который вошел в игровой мир после начала боя, не выкинуло из рейда.

**Comment by Santaria94** [comment]
Проблема скорее все же больше в том, что статус заполненности рейда учитывает только онлайн-персонажей, которые находятся в рейдовой зоне, а персонажи которые оффлайн не учитываются, что и позволяет заводить в рейдовую зону кучу персонажей и производить ротацию прямо в рейде, выключая в оффлайн одних и заводя в онлайн других.

**Comment by Santaria94** [comment]
Игрок, который претендует на лут, должен присутствовать на момент пула босса и на момент его смерти. В промежутке между этими двумя событиями его можно дисконнектнуть вышеописанным способом и завести другого персонажа, который сделает более весомый вклад в ход боя.

Подобный механизм воспроизводился в низкоуровневых рейдах, которые можно протестировать в одиночку. Данные же по тестированию актуальных рейдов предоставить не могу, ибо на тестовом сервере не достаточно инструментов для подобных тестирований.

---

Ну и то, что достижения можно получать подобным способом, уже довольно серьезная проблема.
