### ISSUE TITLE
[Задание] ID 348 - Лихорадка Тернистой долины

### ISSUE THREAD

**Issue by LifeLie0** [VirginTeam/WotlkCore#1246]
**Ссылки и комментарии:**

http://db.logon3.com/?quest=348

**Что работает не так?**

Нельзя никак взаимодействовать с нпс http://db.logon3.com/?npc=1449. Не выдает квест на призыв

**Как должно работать?**

Должен выдавать квест http://db.logon3.com/?quest=349

**Шаги для воспроизведения ошибки:**

1. Взять квест http://db.logon3.com/?quest=348
2. Дойти до нужного нпс
3. Увидеть, забаганую анимацию в его в рука и отсутствие взаимодействия

**Текущее обновление ядра:**

Build 221

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by Ewropa** [comment]
https://github.com/VirginTeam/WotlkCore/issues/990

**Comment by Grandhades** [comment]
актуально!

**Comment by RidrichVi** [comment]
Делал этот кв на 222 билде - всё работает. Перед тем как идти к троллю, выбейте с обитающих рядом горилл "Клык гориллы"и отдайте ему.

**Comment by Rorshah** [comment]
https://github.com/VirginTeam/WotlkCore/issues/824
Его вроде чинили уже.
Даже Кодекс это может.
Поправьте снова.

**Comment by Rorshah** [comment]
Квест сделал по дедовскому методу. Он описан в предыдущем репорте:
Нужно сагрить ближайшую старую горилу, подвести к знахарю.
Он срывается в бой с ней, тем самым разбагивая что там у него багается.
Как только убил горилу сразу запустился ивент с разъяренной горилой и мокком.
Клыки не требуется, доп.задание от знахаря не выдается.

**Comment by Kodekc** [comment]
Переписал скрипт, не должен багаться больше. Выдаёт только одно задание, оно и является верным - http://db.logon3.com/?quest=349. Изменения будут применены в ближайшем обновлении

**Comment by Dymsel** [comment]
Все еще актуально, кв не работает
