### ISSUE TITLE
Кв: Вербовочный троллинг, Идеальные шпионы, Лягушачий десант, Повелительница тигров, Танец духов, Начальная подготовка, Разведать обстановку

### ISSUE THREAD

**Issue by kalambyr18** [VirginTeam/WotlkCore#1250]
**Ссылки и комментарии:**

http://db.logon3.com/?quest=25212
http://db.logon3.com/?quest=25199
http://db.logon3.com/?quest=25444
http://db.logon3.com/?quest=25446
http://db.logon3.com/?quest=25470
http://db.logon3.com/?quest=25480

**Что работает не так?**

Нет нпс , которые дают данные кв (Дун Морог, Дуротар)

**Как должно работать?**

Должны быть нпс , которые дают данные кв .
Всегда на лоу влл можно было выполнить кв и заработать начальную голду с этих кв . 

**Шаги для воспроизведения ошибки:**

**Текущее обновление ядра:**

222

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by Kodekc** [comment]
В Build 219 были отключены события Падение Залазана и Операция Гномреган на постоянной основе

**Comment by kalambyr18** [comment]
Уберите кв" Несколько хороших гномов", сдавать то некому .

**Comment by Kodekc** [comment]
Оно осталось в списке заданий вашего персонажа или NPC выдаёт это задание сейчас?

**Comment by kalambyr18** [comment]
Не знаю как сейчас , но где то дней 5 назад я брал этот кв.

**Comment by zyxellgit** [comment]
так это чо теперь Гордость Черного Копья недоступна? https://ru.wowhead.com/item=54653

**Comment by sega693** [comment]
Да. Можно идти в дискорд вайнить, чтоб обратно включали :D
