### ISSUE TITLE
К Оружию!

### ISSUE THREAD

**Issue by zanku666** [VirginTeam/WotlkCore#1251]
Ссылки и комментарии:

https://ru.wowhead.com/achievement=908/к-оружию#comments

Что работает не так?

Достижение не выполнимо

Как должно работать?

Данное достижение не выполнимо после патча 3.3.3, так как убрали дейли, которые выполняли требования достижения. Предлагаю вернуть даное достижение в игру, для выполнения тем кто не сделал его при предыдущем патче. Можно без дейли, а чтоб засчитывало при реге конкретки (или случайного) где есть пометка "Призыв к оружию" за победу.

Шаги для воспроизведения ошибки:

Шаг один - регнуть бг
Шаг два - выиграть
Шаг три - открыть достижение
Текущее обновление ядра:
222

**Comment by gmRial** [comment]
Обратитесь в дискорд в канал #обратная-связь
