### ISSUE TITLE
[Группа предметов] - Шаттратские настои

### ISSUE THREAD

**Issue by Kodekc** [VirginTeam/WotlkCore#1253]
Ссылки и комментарии:

http://db.logon3.com/?item=32898
http://db.logon3.com/?item=32899
http://db.logon3.com/?item=32900
http://db.logon3.com/?item=32901
http://db.logon3.com/?item=35716
http://db.logon3.com/?item=35717

Private Notes:

https://docs.google.com/spreadsheets/d/1uKq-i39oinbP8lm1nDGApBARXSywL-fPl0_ow7wNJR0

**Comment by Santaria94** [comment]
Пьем любую из этих настоек в бк рейде и вручную отменяем его. В списке бафов настойка хоть и пропадает, но статы от нее сохраняются на персонаже. Пьем другую настойку и также отменяем ее баф. Смотрим на статы - на нас висят бонусы от двух настоек. Так можно повешать на себя эффекты от всех шаттратских настоек.

Если выйти из бк рейда, то при использовании выше названного способа, эффекты не пропадут с персонажа. Если выпить обычную настойку, то она не сбросит эффекты шаттратских.

Таким образом можно повесить на себя ряд бонусных эффектов. Пользуйтесь, пока не пофиксили =)

**Comment by gmRial** [comment]
Исправлено, после обновления.
