### ISSUE TITLE
[Заклинание] - Водяная стрела

### ISSUE THREAD

**Issue by LifeLie0** [VirginTeam/WotlkCore#1254]
**Ссылки и комментарии:**

http://db.logon3.com/?spell=31687
Способность элементаля у магов

**Что работает не так?**

После первого попадания стрелой, 2 и 3 попадание, урон наносится через пару секунд. При первом - моментально. Затем повтор (4 - моментально, 5 и 6 - через пару секунд)

**Как должно работать?**

При каждом достижении цели стрелой, урон должен наноситься моментально

**Шаги для воспроизведения ошибки:**

1. Призвать элементаль, заставить атаковать цель
2. Увидеть, что первая стрела наносит моментальный урон, а 2 и 3 через пару секунд 
3. Цикл повторяется

**Текущее обновление ядра:**

Build 222

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by gmRial** [comment]
Не воспроизводится. Есть видео?

**Comment by LifeLie0** [comment]
Хм. Попробуй с символом извечной воды

**Comment by gmRial** [comment]
Проверялось как с ним, так и без него.

**Comment by Kodekc** [comment]
Репорт будет закрыт в скором времени, если в него не будут добавлены дополнительные сведения

**Comment by Kodekc** [comment]
Репорт закрыт, так и не получилось воспроизвести.
