### ISSUE TITLE
[Рейд] Обсидиановое святилище

### ISSUE THREAD

**Issue by GmAlleria** [VirginTeam/WotlkCore#1255]
**Ссылки и комментарии:**

Добавьте ссылки с wowhead.com или db.logon3.com на проблемные задания, NPC, заклинания и т.д. 

**Что работает не так?**

Во время боя с боссами погибший игрок может вернуться в инстанс

**Как должно работать?**

Во время боя с боссом на инстансе должен быть флаг "идет бой", игроки не должны входить в подземелье во время боя.

**Шаги для воспроизведения ошибки:**

1. Начать бой с одним из боссов
2. Умереть
3. Зайти в инстанс во время боя с боссом

**Текущее обновление ядра:**

Logon 3 WowCircle Development
Последнее обновление ядра: Build 222 2018-10-15 12:05:28 +0400

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by Santaria94** [comment]
Раз уж решили фиксить ОС, то может и эти репорты возьмете на заметку
https://github.com/VirginTeam/WotlkCore/issues/18
https://github.com/VirginTeam/WotlkCore/issues/19

**Comment by ForesterDev** [comment]
Исправлено, будет применено в обновлении
