### ISSUE TITLE
[Предмет] ID 12583 - Роковая пила Чернорука

### ISSUE THREAD

**Issue by Plasmashield** [VirginTeam/WotlkCore#1256]
**Ссылки и комментарии:**

http://db.logon3.com/?item=12583

**Что работает не так?**

Занижен урон. Очень редкие криты.

**Как должно работать?**

Наносит около 250-300 ед. урона, против 324 - 540 ед. урона. Так же(по информации, которую я смог найти) урон должен игнорировать броню и может быть критическим.

**Шаги для воспроизведения ошибки:**

1. Шаг один
2. Шаг два
3. Шаг три

**Текущее обновление ядра:**

Build 222 2018-10-15

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by gmRial** [comment]
Подкрепите в репорт информацию, которую нашли.
