### ISSUE TITLE
[Игровая механика] - Гравирование

### ISSUE THREAD

**Issue by Santaria94** [VirginTeam/WotlkCore#1257]
**Ссылки и комментарии:**

https://ru.wowhead.com/spell=53428
http://db.logon3.com/?spell=54447
http://db.logon3.com/?spell=53342
http://db.logon3.com/?spell=53331
http://db.logon3.com/?spell=54446
http://db.logon3.com/?spell=53323
http://db.logon3.com/?spell=53344
http://db.logon3.com/?spell=70164
http://db.logon3.com/?spell=62158

**Что работает не так?**

Все виды гравирования можно изучить с 40 уровня, т.е. фактически сразу как создан ДК, ибо он стартует с 55 уровня.

**Как должно работать?**

57 уровень - Руна разрушения чар и Руна сокрушения чар
60 уровень - Руна проклятия плети
63 уровень - Руна расколотых мечей и Руна сломанных мечей
70 уровень - Руна павшего рыцаря
73 уровень - Руна каменной горгульи и Руна нерубского панциря

**Текущее обновление ядра:**

Билд 222

**Comment by gmRial** [comment]
> The complete list of Runes is:
> 
> (Заклинание #53341) - Requires level 55
>  Rune of Razorice - Requires level 55
> --- --- ---
> (Заклинание #54447) - Requires level 57 (One-Handed weapons only!)
> (Заклинание #53342) - Requires level 57 (Two-Handed weapons only!)
> --- --- ---
> (Заклинание #53331) - Requires level 60
> --- --- ---
> (Заклинание #54446) - Requires level 63 (One-Handed weapons only!)
> (Заклинание #53323) - Requires level 63 (Two-Handed weapons only!)
> --- --- ---
>  Rune of the Fallen Crusader - Requires level 70 
> --- --- ---
>  Rune of the Stoneskin Gargoyle Requires level 72 (Two-Handed weapons only!)

https://ru.wowhead.com/spell=53428/%D0%B3%D1%80%D0%B0%D0%B2%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5#comments:id=536700

**Comment by gmKroshka** [comment]
Будет исправлено после обновления
