### ISSUE TITLE
[Задание] ID 13141 - Битва за вершину рыцарей

### ISSUE THREAD

**Issue by Roman2104** [VirginTeam/WotlkCore#1259]
**Ссылки и комментарии:**

https://ru.wowhead.com/quest=13141/ 

**Что работает не так?**

Армия нежити побеждает защитников Серебряного Авангарда и убивает игрока.

**Как должно работать?**

защитники Серебряного Авангарда должны побеждать армию нежити.

**Шаги для воспроизведения ошибки:**

1. Берем квест
2. Устанавливаем квест итем (штандарт) в груду черепов.
3. Сражаемся с армией нежити.

**Текущее обновление ядра:** Build 222 2018-10-15 12:05:28 +0400

Можно посмотреть в игре, введите в чат команду .server info и скопировать строку начиная с Build с номером и датой. Не забывайте указывать, Live Server или PTR Server, где проводилось тестирование.

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by ForesterDev** [comment]
Только что сделал квест - если помогать, то квест проходится, а если просто стоять - то нежить победит

**Comment by GmAlleria** [comment]
Если нежить побеждает, паки нежити не пропадают и при повторном запуске задание множатся
