### ISSUE TITLE
[Задание] ID 3982 - Что происходит?

### ISSUE THREAD

**Issue by LifeLie0** [VirginTeam/WotlkCore#1261]
**Ссылки и комментарии:**

http://db.logon3.com/?quest=3982

**Что работает не так?**

Отсутствует скрипт нападения, из-за чего квест нельзя выполнить

**Как должно работать?**

Должны появиться мобы нападающие на Гор'шака

**Шаги для воспроизведения ошибки:**

1. Взять квест
2. Ничего не происходит, квест не сделать

**Текущее обновление ядра:**

Build 222

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by Santaria** [comment]
Дубликат
https://github.com/VirginTeam/WotlkCore/issues/334
