### ISSUE TITLE
Подземелье "Залы Отражений" (героический режим)

### ISSUE THREAD

**Issue by Wildundead** [VirginTeam/WotlkCore#1265]
**Что работает не так?**

Начало фазы побега проблемы с Королем Личем. Во время призыва мобов Король Лич останавливается на месте и не бежит вперед. После убийства мобов он продолжает движение и опять останавливается, призывает и после опять стоит на месте. (Альянс, скриншоты имеются)

**Как должно работать?**

Король Лич после призыва прислужников должен с медленной скоростью двигаться вперед.

**Шаги для воспроизведения ошибки:**

1. Шаг один
2. Шаг два
3. Шаг три

Скриншоты:
1.[http://www.picshare.ru/view/9322909/](url)
2.[http://www.picshare.ru/view/9322910/](url)
Это последняя волна, Лич стоит а мы находимся на середине пути, хотя должны быть у выхода.
3.[http://www.picshare.ru/view/9322910/](url)
После слов Джайны начинается сцена с удушением. Лич с середины дороги вышел из стана и дошел до конца.
**Текущее обновление ядра:**
Build 222 2018-10-15 12:05:28 +0400

**Comment by GmAlleria** [comment]
#1003
