### ISSUE TITLE
[Предмет] ID 50379, 50380 - Потертая рукоять

### ISSUE THREAD

**Issue by Santaria94** [VirginTeam/WotlkCore#1266]
**Ссылки и комментарии:**

http://db.logon3.com/?item=50379
http://db.logon3.com/?item=50380

**Что работает не так?**

Сильно завышен шанс дропа.
А также игроки не видят ее в луте, если начали выполнять цепочку или выполнили ее.

**Как должно работать?**

Процент дропа должен быть примерно 0,05-0,1%

https://ru.wowhead.com/item=50380
https://ru.wowhead.com/item=50379
http://web.archive.org/web/20110624041017/https://www.wowhead.com/item=50380/battered-hilt

На протяжении всего существования предмета, у него крайне мизерный шанс выпадения. Что сейчас, что несколько лет назад цифры практически одинаковые.

Об крайне низком шансе дропа также говорят многочисленные комментарии на вовхед актуальных времен, когда игроки целенаправленно фармили рукоять каждый день, но даже не видели ее в дропе продолжительное время, а также очень высоких ценах на аукционе.

Скока раз ни ходил ни разу не выпала, и тем более на ауке она уже стоит 25к ((
пытались сегодня фармнуть в яме и обычке и героике и нифига(((

Также отмечается, что рукоять продолжала выпадать уже после того, как была сделана цепочка квестов. У нас же ее видят только те, кто еще не начал выполнять кв.

К сожалению, квест можно делать 1 раз, я проверяла. Первый раз мне рукоять выпала (и я ее сролила), когда она падала с неэлитных мобов в Яме Сарона. Второй раз упала неделю назад в Залах отражений, пока не решила, что с ней делать.

**Текущее обновление ядра:**

222

**Comment by Santaria94** [comment]
В случае фикса дропа рукояти, думаю, также стоит удалить все рукояти у игроков, как это было сделано с БоЕ эпиками из ЦЛК.

**Comment by Morfem** [comment]
Ну и в свете недавних событий можно чуть отойти от близзлайка и добавить к наградам пушку для танков.
