### ISSUE TITLE
[Задание] ID 11078 - В небесах останется только один!

### ISSUE THREAD

**Issue by gmKroshka** [VirginTeam/WotlkCore#1276]
**Ссылки и комментарии:**

http://db.logon3.com/?quest=11078

**Что работает не так?**

Один из призываемых драконов (Обсидия) находится в текстуре, атаковать невозможно

**Как должно работать?**

НПЦ после призыва можно атаковать

**Шаги для воспроизведения ошибки:**

1. Взять задание
2. Прилететь в Острогорье по координатам 33.87, 54.59
3. Использовать яйцо Обсидии (при себе иметь 35 апекситовых осколков)
4. Получить НПЦ в текстуре

**Текущее обновление ядра:**

Build 224 2018-10-29 11:24:43 +0400

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by sega693** [comment]
https://github.com/VirginTeam/WotlkCore/issues/962

**Comment by adecvat** [comment]
До сих пор не работает
