### ISSUE TITLE
[Рейд] Руины Ан'Киража

### ISSUE THREAD

**Issue by fivescore** [VirginTeam/WotlkCore#128]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Подземелье: Руины Ан`Киража

**Что работает не так?**

После убийства первого босса (Куриннакс) не появляется нужный НПС (Генерал-лейтенант Андоров)

**Как должно работать?**

После убийства первого босса Куриннакса, спустя некоторое время появляется НПС Генерал-лейтенант Андоров. 
Продавать предметы должен только после убийства Генерала Раджакса. При чём хотя бы раз должен ударить самого босса. (Генерал-лейтенант Андоров)

**Шаги для воспроизведения ошибки:**

1. Убийство первого босса (Куриннакс)
2. НПС не появляется (Генерал-лейтенант Андоров)
3. Шаг три

**Текущее обновление ядра:**

Logon 3 WowCircle Development
Последнее обновление ядра: Build 155 2017-04-20 14:36:20 +0400

**Comment by BruseBenner** [comment]
До сих пор актуально!

**Comment by sega693** [comment]
Сделайте хотя бы чтоб появлялся и продавал сразу, без второго скрипта. Или вообще просто стоял где-то (не в толпе треша).

**Comment by fivescore** [comment]
Ждём 💯

**Comment by BruseBenner** [comment]
Очень долго ожидаем скриптов...

**Comment by Senatyan** [comment]
Надо сходить на офф и заснифать кому - нибудь и всё.

**Comment by ForesterDev** [comment]
Будет реализовано в обновлении
