### ISSUE TITLE
[Задания] ID 8470 - Ритуальный тотем Мертвого Леса

### ISSUE THREAD

**Issue by Sinvoid43** [VirginTeam/WotlkCore#1281]
**Ссылки и комментарии:**

http://db.logon3.com/?quest=8470

Фактический результат — тот, который вы наблюдаете 

При убийстве любого из 3 нпс из которых должна выпасть кв шмотка, она не падает.

**Шаги для воспроизведения ошибки:**

1. Убивать очень много фурболгов
2. Понять, что тотем не выпадет.
3. Шаг три

**Текущее обновление ядра:**

Build 222

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by gmRial** [comment]
http://db.logon3.com/?item=20741
