### ISSUE TITLE
[Предмет] ID 42473 - Символ демона Бездны

### ISSUE THREAD

**Issue by kalambyr18** [VirginTeam/WotlkCore#1282]
**Ссылки и комментарии:**

http://db.logon3.com/?item=42473

**Что работает не так?**

Не работает

**Как должно работать?**

Должен увеличивать хп пета .

**Шаги для воспроизведения ошибки:**

1. Поставить символ 

**Текущее обновление ядра:**

224

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by gmKroshka** [comment]
Будет исправлено после обновления
