### ISSUE TITLE
[Заклинание] ID 68647 - Жуки-трупоеды

### ISSUE THREAD

**Issue by MedoOf** [VirginTeam/WotlkCore#1284]
**Ссылки и комментарии:**

http://db.logon3.com/?spell=68647
http://db.logon3.com/?spell=66118
http://db.logon3.com/?spell=67630
http://db.logon3.com/?spell=68646
**Что работает не так?**

1) На заклинание действуют способности урезающие отхил

> [21:30:33.812] Ануб'арак Жуки-трупоеды  Zev 6924 (R: 1730)
> [21:30:33.812] Ануб'арак Жуки-трупоеды Ануб'арак +4327
> [21:30:33.812] Ануб'арак Жуки-трупоеды Мандос Absorb (8025)
> [21:30:33.812] Ануб'арак Жуки-трупоеды Ануб'арак +4458
> [21:30:33.812] Ануб'арак Жуки-трупоеды Самтыбаба Absorb (9752)
> [21:30:33.812] Ануб'арак Жуки-трупоеды Ануб'арак +6095
> [21:30:33.812] Ануб'арак Жуки-трупоеды Trubach Absorb (10197)
> [21:30:33.812] Ануб'арак Жуки-трупоеды Ануб'арак +5664
> [21:30:33.812] Ануб'арак Жуки-трупоеды Meowth Absorb (7048)
> [21:30:33.812] Ануб'арак Жуки-трупоеды Ануб'арак +4405

2) Источником отхиливающей части заклинания является Анубарак
**Как должно работать?**

1) На заклинание не должно действовать урезание хила на боссе

> [21:33:50.021] Anub'arak Leeching Swarm Caerbear 6420 (R: 1605)
> [21:33:50.021] Anub'arak Leeching Swarm Parole Absorb (16819)
> [21:33:50.021] Anub'arak Leeching Swarm Tiarana 12385 (R: 5308)
> [21:33:50.021] Anub'arak Leeching Swarm Silententity 8347 (R: 927)
> [21:33:50.021] Anub'arak Leeching Swarm Riddly Absorb (5807)
> [21:33:50.021] Anub'arak Leeching Swarm  Lamune Absorb (5640)
> [21:33:50.021] Anub'arak Leeching Swarm Agaeti 5691 (R: 2439)
> [21:33:50.021] Anub'arak Leeching Swarm Juxtaposed 7240 (R: 1810)
> [21:33:50.021] Anub'arak Leeching Swarm Hickok 5683 (R: 2436)
> [21:33:50.021] Anub'arak Leeching Swarm Lyrae 6343 (R: 1586)
> [21:33:50.021] Anub'arak Leeching Swarm Sinter 7147 (R: 794)
> [21:33:50.021] Anub'arak Leeching Swarm Hypidae 8886 (R: 987)
> [21:33:50.021] Anub'arak Leeching Swarm Xeria 6414 (R: 1603)
> [21:33:50.021] Anub'arak Leeching Swarm Zeura 12255 (R: 5252)
> [21:33:50.021] Anub'arak Leeching Swarm Necropolitan 7735 (R: 1934)
> [21:33:50.021] Anub'arak Leeching Swarm Gaiseric 7805 (R: 1951)
> [21:33:50.021] Anub'arak Leeching Swarm Nepenthes Absorb (5221)
> [21:33:50.021] Anub'arak Leeching Swarm Sentieri 7221 (R: 802)
> [21:33:50.021] Anub'arak Leeching Swarm Hurtconveyor 7894 (R: 1973)
> [21:33:50.021] Anub'arak Leeching Swarm Freestyler 8016 (R: 891)
> [21:33:50.021] Anub'arak Leeching Swarm Jeramiah 6485 (R: 1621)
> [21:33:50.021] Anub'arak Leeching Swarm Balder 6779 (R: 1695)
> [21:33:50.021] Anub'arak Leeching Swarm Yozomíko Absorb (6202)
> [21:33:50.391] Anub'arak Leeching Swarm Maegan Absorb (5742)
> [21:33:50.789] Caerbear Leeching Swarm Anub'arak +7383
> [21:33:50.789] Parole Leeching Swarm Anub'arak +19342
> [21:33:50.789] Tiarana Leeching Swarm Anub'arak +14242
> [21:33:50.789] Silententity Leeching Swarm Anub'arak +9599
> [21:33:50.789] Riddly Leeching Swarm Anub'arak +6945
> [21:33:50.789]  Lamune Leeching Swarm Anub'arak +6486
> [21:33:50.789] Agaeti Leeching Swarm Anub'arak +7199
> [21:33:50.789] Juxtaposed Leeching Swarm Anub'arak +8326
> [21:33:50.789] Hickok Leeching Swarm Anub'arak +6536
> [21:33:50.789] Lyrae Leeching Swarm Anub'arak +8024
> [21:33:50.789] Sinter Leeching Swarm Anub'arak +8219
> [21:33:50.789] Maegan Leeching Swarm Anub'arak +6603
> [21:33:50.789] Hypidae Leeching Swarm Anub'arak +10219
> [21:33:50.789] Xeria Leeching Swarm Anub'arak +7376
> [21:33:50.789] Zeura Leeching Swarm Anub'arak +14093
> [21:33:50.789] Necropolitan Leeching Swarm Anub'arak +8895
> [21:33:50.789] Gaiseric Leeching Swarm Anub'arak +8976
> [21:33:50.789] Nepenthes Leeching Swarm Anub'arak +6304
> [21:33:50.789] Sentieri Leeching Swarm Anub'arak +8304
> [21:33:50.789] Hurtconveyor Leeching Swarm Anub'arak +9078
> [21:33:50.789] Freestyler Leeching Swarm Anub'arak +9218
> [21:33:50.789] Jeramiah Leeching Swarm Anub'arak +7756
> [21:33:50.789] Balder Leeching Swarm Anub'arak +7795
> [21:33:50.797] Yozomíko Leeching Swarm Anub'arak +7132

2) Источником исцеляющей части должен быть игрок, а не босс.
**Шаги для воспроизведения ошибки:**

1. Шаг один
2. Шаг два
3. Шаг три

**Текущее обновление ядра:**

05.11.2018
224 билд

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by MedoOf** [comment]
https://forum.wowcircle.com/showthread.php?t=820364
Оказывается на л1 такой же баг, даже больше. Там расписаны модификаторы исцеления жуков от Зороастра.

**Comment by gmKroshka** [comment]
Будет исправлено после обновления

**Comment by MedoOf** [comment]
И для кого оставлял ссылку на репорт с л1(...непонятно.
Ну ладно начнем.
**Что работает не так:**
1) Отхил от способности http://db.logon3.com/?spell=68647 проходит в момент нанесения урона

> [20:47:59.046] Medoff afflicted by Жуки-трупоеды from Ануб'арак
> [20:47:59.958] Ануб'арак Жуки-трупоеды  Medoff 7008 (R: 1752)
> [20:47:59.958]  Medoff Жуки-трупоеды Ануб'арак +7008
> [20:48:00.921] Ануб'арак Жуки-трупоеды  Medoff 5391 (R: 1347)
> [20:48:00.921]  Medoff Жуки-трупоеды Ануб'арак +5391
> [20:48:01.938] Ануб'арак Жуки-трупоеды  Medoff 6982 (R: 1745)
> [20:48:01.938]  Medoff Жуки-трупоеды Ануб'арак +6982
> [20:48:02.844] Ануб'арак Жуки-трупоеды  Medoff 4952 (R: 550)
> [20:48:02.859]  Medoff Жуки-трупоеды Ануб'арак +4952
> [20:48:03.799] Ануб'арак Жуки-трупоеды  Medoff 4565 (R: 507)
> [20:48:03.799]  Medoff Жуки-трупоеды Ануб'арак +4565

2) Коэффициент отхила от http://db.logon3.com/?spell=68647 составляет 100% для 25гер - лог выше. С большой вероятностью, коэффициенты для 10об, 10гер, и 25об также равны 100%, не проверял т.к. еще не ходил в рейды данных сложностей.
3) Отхил от http://db.logon3.com/?spell=68647 не учитывает Mod Healing Done % игроков

> [20:47:59.046] Бешенка afflicted by Жуки-трупоеды from Ануб'арак
> [20:47:59.968] Ануб'арак Жуки-трупоеды Бешенка Absorb (8008)
> [20:48:00.921] Ануб'арак Жуки-трупоеды Бешенка 4707 (A: 2411, R: 1779)
> [20:48:00.921] Бешенка Жуки-трупоеды Ануб'арак +4707
> [20:48:01.938] Ануб'арак Жуки-трупоеды Бешенка 5299 (R: 2271)
> [20:48:01.938] Бешенка Жуки-трупоеды Ануб'арак +5299
> [20:48:02.859] Ануб'арак Жуки-трупоеды Бешенка 7151
> [20:48:02.882] Бешенка Жуки-трупоеды Ануб'арак +7151

Хпал с талантом http://db.logon3.com/?spell=63650

4) Абсорб снижает исцеление

> [20:47:59.046] Бешенка afflicted by Жуки-трупоеды from Ануб'арак
> [20:47:59.968] Ануб'арак Жуки-трупоеды Бешенка Absorb (8008)
> [20:48:00.921] Ануб'арак Жуки-трупоеды Бешенка 4707 (A: 2411, R: 1779)
> [20:48:00.921] Бешенка Жуки-трупоеды Ануб'арак +4707

**Как должно работать:**
1) Должна быть задержка между нанесением урона и исцелением 0.8 секунды

> [21:33:48.504] Xeria afflicted by Leeching Swarm from Anub'arak
> [21:33:50.021] Anub'arak Leeching Swarm Xeria 6414 (R: 1603)
> [21:33:50.789] Xeria Leeching Swarm Anub'arak +7376
> [21:33:51.249] Anub'arak Leeching Swarm Xeria 5612 (R: 2405)
> [21:33:52.001] Xeria Leeching Swarm Anub'arak +6454
> [21:33:52.045] Anub'arak Leeching Swarm Xeria 6163 (R: 1541)
> [21:33:52.840] Xeria Leeching Swarm Anub'arak +7087
> [21:33:53.199] Anub'arak Leeching Swarm Xeria 6090 (R: 677)
> [21:33:54.017] Xeria Leeching Swarm Anub'arak +7003

2) Коэффициент отхила для сложности ИВК25 должен составлять 115% - лог выше.

6414*1.15=7378

Для сложности ИВК10 - 46%

> [23:48:48.161] Jirikhi afflicted by Leeching Swarm from Anub'arak
> [23:48:49.752] Anub'arak Leeching Swarm Jirikhi Absorb (4639)
> [23:48:50.534] Jirikhi Leeching Swarm Anub'arak +3415
> [23:48:50.970] Anub'arak Leeching Swarm Jirikhi 10 (A: 4629, R: 515)
> [23:48:51.736] Jirikhi Leeching Swarm Anub'arak +2134
> [23:48:51.750] Anub'arak Leeching Swarm Jirikhi 4122 (R: 1031)
> [23:48:52.546] Jirikhi Leeching Swarm Anub'arak +1896
> [23:48:52.546] Anub'arak Leeching Swarm Jirikhi 4360
> [23:48:53.341] Jirikhi Leeching Swarm Anub'arak +2005
> [23:48:53.767] Anub'arak Leeching Swarm Jirikhi 3592
> [23:48:54.564] Jirikhi Leeching Swarm Anub'arak +1652
> [23:48:54.573] Anub'arak Leeching Swarm Jirikhi 2519 (R: 280)
> [23:48:55.369] Jirikhi Leeching Swarm Anub'arak +1159
> [23:48:55.774] Anub'arak Leeching Swarm Jirikhi 1960 (R: 490)
> [23:48:56.570] Jirikhi Leeching Swarm Anub'arak +902

1896/4122 = 0,45997
2005/4360 = 0,4598
902/1960 = 0,4602

Для сложности ИК25 - 77.5%

> [22:08:48.116] Zelmira afflicted by Leeching Swarm from Anub'arak
> [22:08:49.676] Anub'arak Leeching Swarm Zelmira 2496
> [22:08:50.472] Zelmira Leeching Swarm Anub'arak +3868
> [22:08:50.956] Anub'arak Leeching Swarm Zelmira 2246
> [22:08:51.697] Zelmira Leeching Swarm Anub'arak +1741
> [22:08:51.798] Anub'arak Leeching Swarm Zelmira 2113
> [22:08:52.515] Zelmira Leeching Swarm Anub'arak +1638
> [22:08:52.875] Anub'arak Leeching Swarm Zelmira 1521 (R: 380)
> [22:08:53.685] Zelmira Leeching Swarm Anub'arak +1178
> [22:08:53.701] Anub'arak Leeching Swarm Zelmira 1473 (R: 368)
> [22:08:54.497] Zelmira Leeching Swarm Anub'arak +1141
> [22:08:54.904] Anub'arak Leeching Swarm Zelmira 1525 (R: 169)
> [22:08:55.682] Zelmira Leeching Swarm Anub'arak +1182
> [22:08:55.776] Anub'arak Leeching Swarm Zelmira 1426 (R: 158)
> [22:08:56.509] Zelmira Leeching Swarm Anub'arak +1105

1741/2246 = 0.77515
1178/1521 = 0.77449
1105/1426 = 0.77489

Для сложности ИК10 - 68%

> [21:54:09.500]  Dragonhell afflicted by Leeching Swarm from Anub'arak
> [21:54:11.061] Anub'arak Leeching Swarm  Dragonhell 1786 (R: 198)
> [21:54:11.809]  Dragonhell Leeching Swarm Anub'arak +1214
> [21:54:12.276] Anub'arak Leeching Swarm  Dragonhell 1625 (R: 180)
> [21:54:13.041]  Dragonhell Leeching Swarm Anub'arak +1105
> [21:54:13.073] Anub'arak Leeching Swarm  Dragonhell 1314 (R: 328)
> [21:54:13.805]  Dragonhell Leeching Swarm Anub'arak +893
> [21:54:13.837] Anub'arak Leeching Swarm  Dragonhell 1608 (R: 689)
> [21:54:14.669]  Dragonhell Leeching Swarm Anub'arak +1093
> [21:54:15.088] Anub'arak Leeching Swarm  Dragonhell 1792 (R: 448)
> [21:54:15.834]  Dragonhell Leeching Swarm Anub'arak +1218
> [21:54:15.849] Anub'arak Leeching Swarm  Dragonhell 1649 (R: 412)
> [21:54:16.660]  Dragonhell Leeching Swarm Anub'arak +1121
> [21:54:17.050] Anub'arak Leeching Swarm  Dragonhell 1507 (R: 377)
> [21:54:17.862]  Dragonhell Leeching Swarm Anub'arak +1024
> [21:54:17.893] Anub'arak Leeching Swarm  Dragonhell 1387 (R: 347)
> [21:54:18.657]  Dragonhell Leeching Swarm Anub'arak +944
> [21:54:19.048] Anub'arak Leeching Swarm  Dragonhell 1354 (R: 580)
> [21:54:19.843]  Dragonhell Leeching Swarm Anub'arak +921
> [21:54:19.913] Anub'arak Leeching Swarm  Dragonhell 1336 (R: 148)
> [21:54:20.658]  Dragonhell Leeching Swarm Anub'arak +909
> [21:54:21.075] Anub'arak Leeching Swarm  Dragonhell 945 (R: 405)
> [21:54:21.856]  Dragonhell Leeching Swarm Anub'arak +642
> [21:54:21.887] Anub'arak Leeching Swarm  Dragonhell 1130 (R: 126)
> [21:54:22.687] Dragonhell Leeching Swarm Anub'arak +769

1024/1507 = 0.67949
921/1354 = 0.6802
769/1130 = 0.6805

Во всех расчетах взяты классы и спеки не имеющие Mod Healing Done % - афлики и маги (фаеры и арканы), что позволяет с уверенностью сказать о таких коэффициентах исцеления. 

3)Ауры игроков влияющие на исходящее исцеление (Mod Healing Done %) должны влиять на отхил от http://db.logon3.com/?spell=68647

> [21:33:48.504] Nepenthes afflicted by Leeching Swarm from Anub'arak
> [21:33:50.021] Anub'arak Leeching Swarm Nepenthes Absorb (5221)
> [21:33:50.789] Nepenthes Leeching Swarm Anub'arak +6304
> [21:33:51.249] Anub'arak Leeching Swarm Nepenthes Absorb (6714)
> [21:33:52.001] Nepenthes Leeching Swarm Anub'arak +8107
> [21:33:52.045] Anub'arak Leeching Swarm Nepenthes 5254 (A: 713, R: 1492)
> [21:33:52.840] Nepenthes Leeching Swarm Anub'arak +7205

5221*1,15*1,05=6304

4) Абсорб не должен снижать или как то влиять на исцеление

> [21:33:48.504] Nepenthes afflicted by Leeching Swarm from Anub'arak
> [21:33:50.021] Anub'arak Leeching Swarm Nepenthes Absorb (5221)
> [21:33:50.789] Nepenthes Leeching Swarm Anub'arak +6304
> [21:33:51.249] Anub'arak Leeching Swarm Nepenthes Absorb (6714)
> [21:33:52.001] Nepenthes Leeching Swarm Anub'arak +8107

**Comment by MedoOf** [comment]
http://www.worldoflogs.com/reports/o9528yd4ghfos3u1/ - лог с х1

**Comment by ForesterDev** [comment]
Данный репорт был исправлен, все добавки к нему не относятся. Нужно создавать новый репорт
