### ISSUE TITLE
[NPC] ID 12129 - Хранитель Ониксии

### ISSUE THREAD

**Issue by ghost** [VirginTeam/WotlkCore#1287]
**Ссылки и комментарии:**

http://db.logon3.com/?npc=12129
http://db.logon3.com/?spell=12097

**Что работает не так?**

Кд способности составляет 35 секунд

**Как должно работать?**

Должен использовать через приблизительно 18 секунд после начала боя с Хранитель Ониксии, висеть 20 секунд (работает) и вновь использоваться через 30 секунд после предыдущего момента каста.
http://www.worldoflogs.com/reports/rt-2mhiwgnxirakja09/
> [17:10:22.838] Onyxian Warder casts Pierce Armor on Pucc
> [17:10:22.989] Pucc afflicted by Pierce Armor from Onyxian Warder
> [17:10:42.986] Onyxian Warder's Pierce Armor fades from Pucc
> [17:10:52.265] Onyxian Warder casts Pierce Armor on Pucc
> [17:10:52.265] Onyxian Warder Pierce Armor Pucc Dodge
> [17:11:32.056] Onyxian Warder casts Pierce Armor on Tydru
> [17:11:32.083] Tydru afflicted by Pierce Armor from Onyxian Warder
> [17:11:52.063] Onyxian Warder's Pierce Armor fades from Tydru
> [17:12:01.900] Onyxian Warder casts Pierce Armor on Pucc
> [17:12:01.900] Onyxian Warder Pierce Armor Pucc Dodge
> [17:12:16.638] Onyxian Warder casts Pierce Armor on Tydru
> [17:12:16.679] Tydru afflicted by Pierce Armor from Onyxian Warder

**Шаги для воспроизведения ошибки:**

1. Шаг один
2. Шаг два
3. Шаг три

**Текущее обновление ядра:**

224 билд

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by MedoOf** [comment]
> [18:15:52.421] Хранитель Ониксии casts Пронзенная броня on Юлакек
> [18:15:52.541] Юлакек afflicted by Пронзенная броня from Хранитель Ониксии
> [18:16:12.389] Хранитель Ониксии's Пронзенная броня fades from Юлакек
> [18:16:27.020] Хранитель Ониксии casts Пронзенная броня on Юлакек
> [18:16:27.020] Хранитель Ониксии Пронзенная броня Юлакек Dodge
> [18:17:02.806] Хранитель Ониксии casts Пронзенная броня on Юлакек
> [18:17:02.983] Юлакек afflicted by Пронзенная броня from Хранитель Ониксии
> [18:17:22.811] Хранитель Ониксии's Пронзенная броня fades from Юлакек
> [18:17:38.632] Хранитель Ониксии casts Пронзенная броня on Юлакек
> [18:17:38.769] Юлакек afflicted by Пронзенная броня from Хранитель Ониксии
> [18:17:58.762] Хранитель Ониксии's Пронзенная броня fades from Юлакек
> [18:18:12.313] Хранитель Ониксии casts Пронзенная броня on Юлакек
> [18:18:12.478] Юлакек afflicted by Пронзенная броня from Хранитель Ониксии
> [18:18:32.470] Хранитель Ониксии's Пронзенная броня fades from Юлакек
> [18:18:47.640] Хранитель Ониксии casts Пронзенная броня on Юлакек

Баф вешается, но необходимо поправить таймеры: из логов видно что дебаф вешается каждые 30 секунд, у нас же он вешается каждые 35 секунд
