### ISSUE TITLE
[NPC] ID 10184 - Ониксия

### ISSUE THREAD

**Issue by ghost** [VirginTeam/WotlkCore#1288]
**Ссылки и комментарии:**
Ссылки с вовхеда потому что в базе логон3 нет способностей
https://ru.wowhead.com/npc=10184
https://ru.wowhead.com/spell=17086/дыхание
https://ru.wowhead.com/spell=18431/раскатистый-рев
https://ru.wowhead.com/spell=18435/огненное-дыхание
https://ru.wowhead.com/spell=18392/огненный-шар
**Что работает не так?**

1) Каст https://ru.wowhead.com/spell=17086/дыхание возможно прервать
2) https://ru.wowhead.com/spell=18392/огненный-шар кастуется с перерывами около 5 секунд, кастуется во время ее движения
3) https://ru.wowhead.com/spell=18435/огненное-дыхание неверная анимация работы способности
4) Каст https://ru.wowhead.com/spell=18431/раскатистый-рев возможно прервать

**Как должно работать?**

1) Каст должен быть непрерываем игроками https://youtu.be/kZwCdWK91dQ?t=71 видно что каст отображается с щитом - следовательно он непрерываем.
2) Должен кастоваться по кд, когда Ониксия перелетает с места на место не должен кастоваться. https://youtu.be/EqShG2iNi0s?t=138
3) Ониксия после каста должна пролететь по прямой в направлении своего взгляда и оставить за собой огненную полосу https://ru.wowhead.com/spell=22191/раскаленная-почва , которая пропадает сразу после окончания движения Ониксии, после этого Ониксия разворачивается лицом к своей цели и снова начинает кастовать фаерболы https://youtu.be/EqShG2iNi0s?t=176

> [16:09:13.194] Onyxia begins to cast Breath
> [16:09:21.135] Onyxia Breath Wolfie Resist
> [16:09:21.135] Onyxia casts Heated Ground
> [16:09:21.223] Onyxia Breath Krimfazag 485 (R: 1316)

4) Каст не должен прерываться https://youtu.be/kZwCdWK91dQ?t=298

**Шаги для воспроизведения ошибки:**

В базе http://db.logon3.com отсутствуют способности https://ru.wowhead.com/spell=18431/раскатистый-рев и https://ru.wowhead.com/spell=18392/огненный-шар

**Текущее обновление ядра:**

224 билд

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by gmKroshka** [comment]
БУдет исправлено после обновления

**Comment by Kodekc** [comment]
Реализовали часть механик, пока репорт выведен из дорожной карты, позже мы вернёмся к нему, требуется переписать почти всё, чтоб реализовать остальное

**Comment by MedoOf** [comment]
Будете доделывать по этому репорту или по пунктам 2,3 создавать отдельные?

**Comment by gmKroshka** [comment]
Репорт не закрыт, баги описаны в первом сообщении. Надобности создавать новый репорт нет

**Comment by Kodekc** [comment]
Прошло много времени, необходимо перепроверить и создать новый репорт с оставшимися ошибками по этому боссу.
