### ISSUE TITLE
Проблема с агро у мишки

### ISSUE THREAD

**Issue by Endromillions** [VirginTeam/WotlkCore#1292]
**https://ru.wowhead.com/spell=52504/%D1%80%D0%B0%D1%81%D1%82%D0%B5%D1%80%D0%B7%D0%B0%D1%82%D1%8C**

Добавьте ссылки с wowhead.com или db.logon3.com на проблемные задания, NPC, заклинания и т.д. 

**в описании скилла надпись, значительно повышает уровень угрозы. по факту имеет средние значения агронабора среди своих скиллов**

Фактический результат — тот, который вы наблюдаете 

**Как должно работать?**

Ожидаемый результат — то, чего вы ожидали при выполнении ваших действий. Процесс правильной работы

****

1. изменения спека на максимальное увелечение силы атаки. для способности "Растерзать"
2. проверка ротации. наличие всех положительно влияющих эффектов.
3. сравнение с другими танчащими классами

**Build 224 20018-10-29 11:24:43**

Можно посмотреть в игре, введите в чат команду .server info и скопировать строку начиная с Build с номером и датой. Не забывайте указывать, Live Server или PTR Server, где проводилось тестирование.

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by gmRial** [comment]
Приведите анализ, как вы пришли к такому выводу.
