### ISSUE TITLE
[Предмет] ID 37012 - Поводья скакуна Всадника без головы

### ISSUE THREAD

**Issue by Manulli** [VirginTeam/WotlkCore#1296]
**Ссылки и комментарии:**

Предмет [Поводья Всадника без головы](https://wowroad.info/?item=37012)

**Что работает не так?**

Неправильно накладывается заклинание:
1) При навыке езды [Умелец](https://wowroad.info/?spell=34092) полет 150% но бег при этом почему-то 60%
2) При любом навыке неправильная анимация полета - вместо той что должна быть воспроизводится как при езде назад вправо, только ускоренно
3) В зонах, где полеты запрещены неправильная анимация прыжка, вместо того что должно быть, он уходит под землю

Ошибки 2 и 3 могут происходить, могут не происходить, с вероятностью 50/50, ошибка возникает в момент вызова маунта.

**Как должно работать?**

Ну примерно как у поводий непобедимого и небесного скакуна. Это один из немногих уникальных маунтов такого типа и очень печально, что ездить на нем не доставляет удовольствия, и даже наоборот, портит впечатления от игры.

**Шаги для воспроизведения ошибки:**

1. Шаг один
Изучить одни из навыков езды
2. Шаг два
Получить поводья
3. Шаг три
Вызвать маунта

Logon 3 WowCircle Development
Build 227 2018-11-13 15:31:18 +0400

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by kalipsa988** [comment]
1й пункт не получается воспроизвести 
2й и 3й дубликат #400

**Comment by Manulli** [comment]
Ну, возможно именного моего сообщения не хватало чтобы починили)

**Comment by xARCHIMEDESx** [comment]
Подтверждаю 1 пункт. Выбил на дк коня на этом ивенте, сел, увидел 60% бега и 150% полета, подумал что визуальный баг или хз что случилось, а так как на этого перса я захожу раз в пол года, забыл.

**Comment by kalipsa988** [comment]
я щас проверял макросом, увы на ОПЕН ТЕСТЕ нет этого маунта, тестил на х1, но у меня фул верховая езда, мб из-за этого

**Comment by Manulli** [comment]
Кроме того, на этом маунте у игрока очень странное положение в пространстве. Чтобы увидеть это, надо залезть на какой-нибудь холм/любое другое неровное пространство: песонаж будет стоять под неестественным к горизонту углом. 
После того, как залетаешь на маунте в здание, происходит дисмаунт, и конкретно после этого коня персонаж некоторое время еще плывет вперед. Чтобы увидеть, что обе эти странности поэксперементируйте сами с этим конем и с любым другим маунтом - разница будет очень заметна. Это, конечно, мелочи (иначе я указал бы это в топике) но кто знает причину этих нестыковок. Может это тоже о чем-то говорит.  В общем маунт забагован конкретно.

**Comment by ForesterDev** [comment]
По 1 пункту - это норма. Все скалирующиеся маунты имеют 60 скорости бега при 150 навыке езды

http://db.logon3.com/?spell=72283
http://db.logon3.com/?spell=71346
http://db.logon3.com/?spell=75617
