### ISSUE TITLE
[Подземелье] Пик Черной Горы (ID 10264 Солакар Пламя Гнева)

### ISSUE THREAD

**Issue by Rialzarre** [VirginTeam/WotlkCore#13]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Скриншоты демонстрирующие проблему, выделение проблемных мест с помощью графических редакторов приветствуются. Для описания ошибок, возникающих только в движении, снимите видео **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Солакар Пламя Гнева (Солакарский огнечервь) http://ru.wowhead.com/npc=10264
Контейнер Огонь отцов http://ru.wowhead.com/object=175245

**Что работает не так?**

При использовании контейнера - ничего не происходит.

**Как должно работать?**

Комментарий с wowhead
>Right-clicking on the item will allow you to loot the green offhand item it contains, and begin the notorious "Father Flame" event, summoning waves of dragonkin until the boss, Solakar Flamewreath, appears

**Текущее обновление ядра:**

PTR Build 20 2017-04-03 15:25:08 +0400

**Comment by Eregeon** [comment]
Когда ожидается исправление? Из-за его отсутствия невозможно собрать т0.5 сет на приста

**Comment by BruseBenner** [comment]
Попытки заскриптовать данного моба есть? или забыли уже про него

**Comment by Santaria** [comment]
Есть скрипты с Носта, возможно можно их адаптировать под наш сервер. Вшиты в файл instance_blackrock_spire.cpp , а не в отдельный как у других боссов.

https://github.com/brian8544/nostalrius-core/blob/development/src/scripts/eastern_kingdoms/burning_steppes/blackrock_spire/instance_blackrock_spire.cpp

**Comment by Climss** [comment]
В разработке, значит за квест все же взялись, надежда есть ? Очень важный босс, с него сетовые плечи жреца D1 и хороший рецепт инженерии.

**Comment by Climss** [comment]
В разработке, значит есть шанс на исправления ? Босс очень важный, с него сетовые плечи жреца D1 и хороший рецепт инженерии.

**Comment by Climss** [comment]
Актуально
Build 276 2019-10-29 15:53:46 +0400 Logon 3 x1 PvE

**Comment by nreiv** [comment]
Актуально
Build 287 2020-02-25
