### ISSUE TITLE
[Игровая механика] иммунитет петов к станам хвостом 

### ISSUE THREAD

**Issue by kalipsa988** [VirginTeam/WotlkCore#1301]
**Ссылки и комментарии:**

-

**Что работает не так?**

У петов нет иммунитета к сбивающие с ног ударам хвостом боссов
Проверял в РС на Халионе

**Как должно работать?**

Должен быть иммунитет с патч-ноута 3.3.0 http://eu.battle.net/wow/ru/game/patch-notes/3-3-0

**Шаги для воспроизведения ошибки:**

1. Начать бой с Халионом 
2. Отправить пета бить(автоматом пойдёт к хвосту)
3. Дождаться удара хвостом и увидеть дебаф на иконке пета

**Текущее обновление ядра:**

16.11.2018

**Comment by ForesterDev** [comment]
В оригинале другая формулировка:
https://wow.gamepedia.com/Patch_3.3.0
Many of the tail sweeps **with knockback** effects will no longer hit players' pets.

У Халиона удар не имеет эффекта отбрасывания, соответственно на него не распространяется патч ноут. Изменение распространяется на http://db.logon3.com/?spell=71077, но этот удар у нас работает корректно и не отбрасывает питомцев
