### ISSUE TITLE
[Игровая механика] Эффект паррихаста у боссов

### ISSUE THREAD

**Issue by MedoOf** [VirginTeam/WotlkCore#1304]
**Что работает не так?**

Паррихаст включен у всех боссов:

> 21:30:01.250] Ануб'арак hits Наркоманко Parry
> [21:30:03.332] Ануб'арак hits Наркоманко Parry
> [21:30:05.250] Ануб'арак hits Наркоманко Parry
> [21:30:08.821] Ануб'арак hits Наркоманко Dodge
> [21:30:08.968] Наркоманко hits Ануб'арак Parry
> [21:30:10.068] Ануб'арак hits Наркоманко 680 (A: 14234)

> [12:48:19.796] Саурфанг Смертоносный hits Шэлли Dodge
> [12:48:20.720] Саурфанг Смертоносный hits Шэлли Absorb (9172)
> [12:48:21.097] Шэлли hits Саурфанг Смертоносный Parry
> [12:48:21.377] Саурфанг Смертоносный hits Шэлли 3729 (A: 5137, B: 2416)

> [12:59:03.140] Гниломорд hits Feeldark 11970 (A: 5172)
> [12:59:05.580] Гниломорд hits Feeldark Miss
> [12:59:08.109] Гниломорд hits Feeldark Parry
> [12:59:08.921] Aalaskka hits Гниломорд Parry
> [12:59:09.765] Гниломорд hits Feeldark 21404

> [13:04:56.218] Тухлопуз hits Шэлли Dodge
> [13:04:57.197] Тухлопуз hits Шэлли 27946 (A: 12630)
> [13:04:58.246] Тухлопуз hits Шэлли Parry
> [13:04:59.312] Тухлопуз hits Шэлли Dodge
> [13:04:59.469] Feeldark hits Тухлопуз Parry
> [13:04:59.786] Тухлопуз hits Шэлли 37759 (A: 3439, B: 2416)

И т.д. на каждом боссе в любом инсте.

**Как должно работать?**

Паррихаст должен быть включен не у всех боссов
https://avengingwrathy.wordpress.com/2010/01/15/bosses-who-parry-haste/

> Most bosses” is a bit of an exaggeration. Last I checked, it was only a few isolated hard-hitting slow-swinging bosses. So far on the compiled list, only Gormok, Jaraxxus (still no idea why they chose to do this on him), Ignis, Kologarn, and Patchwerk have it disabled. If anything, “most bosses” have parry-haste enabled, not disabled.

Как видно из сообщения паррихаст должен быть включен у боссов до обновления 3.2.2 (Призыв Авангарда) кроме: http://db.logon3.com/?npc=33118, http://db.logon3.com/?npc=32930 и http://db.logon3.com/?npc=16028

Боссы из ИВК, Логова Ониксии, ЦЛК и РС приведены в таблице:

> The List
> Halion – Parry Haste Enabled – Confirmed here
> 
> ICC
> Lord Marrowgar – Parry Haste Disabled – Confirmed here, here
> Lady Deathwhisper – Parry Haste Enabled – Confirmed here, here
> Gunship (Saurfang/Bronzebeard) – –
> Deathbringer Saurfang – Parry Haste Disabled – Confirmed here
> Festergut – Parry Haste Disabled – Confirmed here
> Rotface – Parry Haste Disabled – Confirmed here
> Professor Putricide – Parry Haste Disabled – Confirmed here, here
> Prince Taldaram – Parry Haste Disabled – Confirmed here
> Prince Valanar – Parry Haste Disabled – Confirmed here
> Blood-Queen Lana’thel – Parry Haste Disabled – Confirmed here
> Sindragosa – Parry Haste Enabled – Confirmed here
> The Lich King – Parry Haste Disabled – Confirmed here
> Onyxia’s Lair
> Onyxia – Parry Haste Enabled – Confirmed here, here?
> Crusader’s Coliseum
> Gormok the Impaler – Parry Haste Disabled – Confirmed Here
> Acidmaw – Parry Haste Enabled – Confirmed Here
> Dreadscale – Parry Haste Enabled – Confirmed Here, here
> Icehowl – Parry Haste Enabled – Confirmed Here, here
> Lord Jaraxxus – Parry Haste Disabled – Confirmed Here, here
> Faction Champions – Not looking for these as they’re not a tanking encounter
> Fjola Lightbane – Parry Haste Disabled – Confirmed here
> Eydis Darkbane – Parry Haste Disabled – Confirmed here
> Anub’Arak – Parry Haste Disabled – Confirmed here, here

Ссылка на репорт на форуме: https://forum.wowcircle.com/showthread.php?t=537986

**Текущее обновление ядра:**

225

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by Librariane** [comment]
Парирование удара и парри-хаст это не одно и то же.

**Comment by Manulli** [comment]
Имеется в виду

> [13:04:59.312] Тухлопуз hits Шэлли Dodge
> [13:04:59.469] Feeldark hits Тухлопуз Parry
> [13:04:59.786] Тухлопуз hits Шэлли 37759 (A: 3439, B: 2416)

Разница между атаками Тухлого составила 0.4 секунды из-за сработавшего паррихаста

**Comment by MedoOf** [comment]
> [11:23:43.149] Тухлопуз hits Borispol Parry
> [11:23:43.189] Borispol hits Тухлопуз Parry
> [11:23:43.661] Тухлопуз hits Borispol Dodge
> [11:23:44.690] Тухлопуз hits Borispol 40994 (B: 2094)
> [11:23:44.704] Borispol hits Тухлопуз Parry
> [11:23:45.157] Тухлопуз hits Borispol Block (2094)

**Comment by MedoOf** [comment]
> [11:29:26.890] Лорд Ребрад casts Костерез on  Ёшкиннкот
> [11:29:27.187]  Ёшкиннкот hits Лорд Ребрад Parry
> [11:29:27.783] Лорд Ребрад casts Костерез on  Ёшкиннкот

> [11:30:40.812] Лорд Ребрад hits Ёшкиннкот 2858 (A: 14279)
> [11:30:41.484] Палачкотлет hits Лорд Ребрад Parry
> [11:30:41.812] Лорд Ребрад hits Ёшкиннкот Miss

> [11:31:00.546] Лорд Ребрад casts Костерез on Ёшкиннкот
> [11:31:00.921] Палачкотлет hits Лорд Ребрад Parry
> [11:31:01.208] Лорд Ребрад casts Костерез on Ёшкиннкот

[17.03.2019](http://www.worldoflogs.com/reports/k55wn7nr3uh33gbb/xe/?s=363&e=493&x=targetName+%3D+"Лорд+Ребрад"+%0D%0AAND+missType+%3D+MISS_PARRY%0D%0Aor+sourceName+%3D+"Лорд+Ребрад"+%0D%0AAND+%28fullType+%3D+SWING_DAMAGE+OR+fullType+%3D+SWING_MISSED%29%0D%0Aor+%28spell+%3D+"Костерез"+and+type+%3D+TYPE_CAST%29)

**Comment by ForesterDev** [comment]
В последнем логе босс парирует же, а не игрок.

**Comment by MedoOf** [comment]
Ну да. Так а в чем же суть паррихаста? При парировании атаки БОССОМ, его (босса) следующая атака ускоряется. п.с. костерез заменяет автоатаку.

**Comment by ForesterDev** [comment]
Внес корректировки, надо будет проверить на тесте
