### ISSUE TITLE
[Предмет] ID 12363 - Чародейный кристалл

### ISSUE THREAD

**Issue by Homo97Sapiens** [VirginTeam/WotlkCore#1310]
http://db.logon3.com/?item=12363#mined-from-object
https://ru.wowhead.com/item=12363#mined-from-object

Дропрейт на кристаллы у нас сильно занижен: напротив Богатой ториевой жилы с дропрейтом 13% по вовхеду у нас Богатая жила с 3.3% и т. п. 
Кстати, с мешочка с самоцветами дропрейт тоже ниже, чем на вовхеде: 18,6% против 94%.
В комментариях можно найти инфу, что в жиле Хаккари был самый высокий дропрейт, однако больше никакой информации не сохранилось

**Текущее обновление ядра:**

Build 227 2018-11-13 15:31:18 +0400

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by Plasmashield** [comment]
Ув. администрация, только не надо писать, что пруфов нет и дроп близлайк. При близлайк дропе цены не были бы по 700г+ за штуку и барыги тут не при чем.

**Comment by Rorshah** [comment]
пруфов не приведено. Дроп близлайк.
Смотрим коментарии времен 3.3.5:

> От Goldenmoon (150 – 1) 2010-06-19 (Обновление 3.3.3) |  
> If you are farming these for some reason, I would highly advise going to Un'goro Crater. I went here to farm Thorium Ore and in an hour and a half i had about 217 Thorium Ore as well as 6 arcane crystals. Hope you have as much luck as I did =)

6/217=2,8% что крайне похоже на существующие значение.
А на вовхэде щас и монахов можно встретить. Это не значит что срочно нужно их допиливать в 3.3.5

**Comment by sega693** [comment]
камни делить на руду? Ничего что в 1 жиле до 6 кусков руды бывает?

**Comment by Rorshah** [comment]
на 3.3.5 есть статистика.
Просто соберите 11 стаков тория и скажите сколько выпало на них кристалла.

**Comment by Homo97Sapiens** [comment]
> пруфов не приведено. Дроп близлайк.
> Смотрим коментарии времен 3.3.5:
> 
> > От Goldenmoon (150 – 1) 2010-06-19 (Обновление 3.3.3) |  
> > If you are farming these for some reason, I would highly advise going to Un'goro Crater. I went here to farm Thorium Ore and in an hour and a half i had about 217 Thorium Ore as well as 6 arcane crystals. Hope you have as much luck as I did =)
> 
> 6/217=2,8% что крайне похоже на существующие значение.
> А на вовхэде щас и монахов можно встретить. Это не значит что срочно нужно их допиливать в 3.3.5

6 / (217 / 4) = 11% (4 - среднее кол-во тория из богатой жилы).
Монахи - контент 5.x.y, аркан кристаллы - контент классики. В БК ещё меняли классику (добавляли новые поселения, квесты, локации; как оказалось, даже аркан кристаллы добавили в луттаблицу маленьких ториевых жил), а вот после БК из ваниллы только вырезали что-то. Накс там, Ониксию, кучу классовых квестов и т. п.. Так что прежде чем писать, ознакомься с понятием логики.
Кстати, раз ты такой инициативный, то собери 11 стаков тория и приведи сюда статистику. Правда, к делу это никакого отношения не имеет, ведь я и так знаю, что будет около 2% кристаллов на каждую жилу, но хоть займёшься чем-то интересным.

**Comment by Kodekc** [comment]
В веб базе почему-то отображается не правильные шансы дропа, в гейм базе, это выглядит так: камень и руда падает с 100% шансом дропа, 1 из 6 камней может упасть с 25% шансом дропа, где прописано вот такие шансы дропа:
![loot](https://user-images.githubusercontent.com/16691965/84772286-6549e500-afe3-11ea-8d2c-51a9d04461f2.PNG)
