### ISSUE TITLE
[Предмет] ID 29529 - Барабаны битвы

### ISSUE THREAD

**Issue by MedoOf** [VirginTeam/WotlkCore#1312]
**Ссылки и комментарии:**

http://db.logon3.com/?item=29529 

**Что работает не так?**

Действуют на игроков 80 уровня

**Как должно работать?**

Неэффективны, если уровень союзников равен или превышает 80. 

**Текущее обновление ядра:**

225

**Comment by gmKroshka** [comment]
Будет исправлено после обновления
