### ISSUE TITLE
Автоматическое применение способностей Охотника скверны 

### ISSUE THREAD

**Issue by IssueCreatorCircle335** [VirginTeam/WotlkCore#1313]
**Ссылки и комментарии:**

Пожирание магии http://db.logon3.com/?spell=48011
Укус тьмы http://db.logon3.com/?spell=54053
Интеллект скверны http://db.logon3.com/?spell=57567
Эти способности по умолчанию включены на автоматическое применение питомцем.

**Что работает не так?**

Автоматическое применение способностей питомца чернокнижника Охотника Скверны сбрасываются при попадании в новую локацию (рейд, подземелье), при телепортации или перемещении в новый континент, при вызове охотника скверны, при езде верхом/спешивании.

**Как должно работать?**

Настройки автоматического применения способностей, установленные на минипанели или в окне "заклинания и способности"->"Демон" должны сохранятся.
Отображение актуального статуса автоматического применения заклинаний должно быть синхронизированным в окне "заклинания и способности"->"Демон"  и на минипанели питомца.

**Шаги для воспроизведения ошибки:**

1. Вызвать Охотника скверны
2. Отключить автоматическое применение способности (Пожирание магии, Укус тьмы, Интеллект скверны)
3. Сесть верхом и спешится. ИЛИ Вызвать Охотника скверны. ИЛИ Зайти в другую локацию (подземелье).
4. Сравнить статус автоматического применения способностей на минипанели и в окне "заклинания и способности"->"Демон". ИЛИ Вступить в бой и убедится, что питомец автоматически применяет заклинания, которые отключены на минипанели.

**Текущее обновление ядра:**

Build 227 2018-11-13

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by sega693** [comment]
https://github.com/VirginTeam/WotlkCore/issues/1076 у всех петов бывает багается
