### ISSUE TITLE
[Задание] ID 10279 - Логово господина

### ISSUE THREAD

**Issue by gmRial** [VirginTeam/WotlkCore#1314]
**Ссылки и комментарии:**

http://db.logon3.com/?quest=10279

**Что работает не так?**

Если принять квест от другого игрока, то персонаж начинает лететь в Пещеры Времени независимо от его текущего местоположения.

**Как должно работать?**

Игрок должен лететь на драконе только в случае, если он находится рядом с квестгивером.
Косвенное подтверждение

> От Bearak (687 – 1·11) 2009-09-04 (Обновление 3.2.0)
> They have apparently made a change to this quest. I remember, back during BC when I did this on 3-4 characters, that simply talking to the dragon at the top of the Cavern, he would offer you a ride down. Now, he no longer does, as stated above. However, if you accept the quest and stand there for a bit, you'll automatically be mounted on a dragon now and flown down to the bottom.
> 
> I discovered this quite by accident. I have attempted to complete this quest several times, picking it up, trying for the "Fly me down" dialog, running down myself and looking for Andromu to no avail. This time, however, I was alt tabbed out reading posts here on this quest to see if I was missing anything, then tabbed back in. In that amount of time, I had automatically mounted the dragon, and was almost down to the bottom.
> 
> Soo...just be patient, accept the quest and wait a minute. =\

**Шаги для воспроизведения ошибки:**

1. Попросить расшарить квест.
2. Принять квест.

**Текущее обновление ядра:**

227

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by gmKroshka** [comment]
Будет исправлено после обновления
