### ISSUE TITLE
[Заклинание] ID 64867 -  Item - Mage T8 2P Bonus

### ISSUE THREAD

**Issue by MedoOf** [VirginTeam/WotlkCore#1315]
**Ссылки и комментарии:**

http://db.logon3.com/?spell=64867
http://db.logon3.com/?spell=64868 

**Что работает не так?**

Не имеет icd на прок.

> [15:48:25.424] Zev gains Праксис from Zev
> [15:48:27.689] Zev's Праксис is refreshed by Zev
> [15:48:36.893] Zev's Праксис is refreshed by Zev
> [15:48:42.793] Zev's Праксис is refreshed by Zev
> [15:48:48.248] Zev's Праксис is refreshed by Zev
> [15:48:50.089] Zev's Праксис is refreshed by Zev
> [15:48:53.784] Zev's Праксис is refreshed by Zev
> [15:48:55.710] Zev's Праксис is refreshed by Zev
> [15:48:57.628] Zev's Праксис is refreshed by Zev
> [15:48:59.412] Zev's Праксис is refreshed by Zev

> [15:50:35.972] Zev gains Праксис from Zev
> [15:50:40.307] Zev's Праксис is refreshed by Zev
> [15:50:49.943] Zev's Праксис is refreshed by Zev
> [15:50:51.754] Zev's Праксис is refreshed by Zev
> [15:50:55.478] Zev's Праксис is refreshed by Zev
> [15:50:59.067] Zev's Праксис is refreshed by Zev
> [15:51:06.276] Zev's Праксис is refreshed by Zev
> [15:51:08.135] Zev's Праксис is refreshed by Zev

**Как должно работать?**

Должен иметь icd равный 45 секундам.

> Has an ICD of 45 seconds. Just did several tests on dummies spamming fireball and earliest re-proc was 45 seconds after the first.

https://ru.wowhead.com/spell=64868/праксис#comments:id=699318

> [22:30:24.424] Karigen gains Praxis from Karigen
> [22:30:24.909]  Pelarius gains Praxis from  Pelarius
> [22:30:31.299] Asos gains Praxis from Asos
> [22:30:39.424] Karigen's Praxis fades from Karigen
> [22:30:39.987] Pelarius's Praxis fades from Pelarius
> [22:30:46.409] Asos's Praxis fades from Asos
> [22:31:14.315] Pelarius gains Praxis from Pelarius
> [22:31:16.034] Karigen gains Praxis from Karigen
> [22:31:16.580] Asos gains Praxis from Asos
> [22:31:29.377] Pelarius's Praxis fades from Pelarius
> [22:31:30.815] Karigen's Praxis fades from Karigen
> [22:31:31.565] Asos's Praxis fades from Asos
> [22:32:01.518] Pelarius gains Praxis from Pelarius
> [22:32:01.737] Asos gains Praxis from Asos
> [22:32:01.752] Karigen gains Praxis from Karigen
> [22:32:16.643] Pelarius's Praxis fades from Pelarius
> [22:32:16.752] Asos's Praxis fades from Asos
> [22:32:16.752] Karigen's Praxis fades from Karigen
> [22:32:50.315] Karigen gains Praxis from Karigen
> [22:32:54.846] Asos gains Praxis from Asos
> [22:32:59.174] Pelarius gains Praxis from Pelarius

**Шаги для воспроизведения ошибки:**

1. Одеть 2т8
2. Спамить любой скилл вызывающий прок в манекен
3. Увидеть что прок обновляется и не имеет скрытого кд

**Текущее обновление ядра:**

227

**Comment by gmKroshka** [comment]
Будет исправлено после обновления
