### ISSUE TITLE
[Группа заклинаний] Тотемы шамана

### ISSUE THREAD

**Issue by Trombocid** [VirginTeam/WotlkCore#133]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

При обновлении тотема **в последнюю секунду** его действия, обновленный тотем сразу же завершает действие, будто просто упал старый тотем.
<a target="_blank" href="http://radikal.ru"><img src="http://i056.radikal.ru/1704/42/585bb5c3b8dc.jpg" /></a>

**Что работает не так?**

Возможно проблема в отсутствии проверки времени действия сразу после установки тотема +накладывается пинг и обновленный тотем не успевает дожить до следующей проверки.

**Как должно работать?**

Обновленный тотем должен полноценно отработать свой жизненный цикл. 

**Шаги для воспроизведения ошибки:**

1. Ставим тотем
2. Ждем до последней секунды его действия и вызываем повторно этот же тотем
3. Тотем сиюсекундно падает

**Текущее обновление ядра:**

WotLK x1 PvE Build 155 2017-05-20.

**Comment by Riazarre** [comment]
На PTR не удается воспроизвести, нет влияния пинга.

**Comment by Gooldark** [comment]
У этого бага есть второй способ воспроизведения:
если в момент, когда кто-то срезает тотем мили атакой(возможно и спелами, но года 3 назад замечал только с автоатакой), шаман ставит тот же тотем, то новый тотем сразу исчезает. Причем не имеет значение какое расстояние между атакующим и новым тотемом.

Иначе говоря, когда шаман ставит новый тотем, то физически сервер переносит старый тотем на новое место, и добавляет ему время действия.

**Comment by Trombocid** [comment]
Актуально, но опять таки, чтобы воспроизвести нужно попасть в пинг.
Build 305 2020-06-09 22:27:39 +0400

**Comment by ForesterDev** [comment]
Данный репорт из разряда "Нельзя исправить".

Он не воспроизводится на локальном сервере, его невозможно соответственно отладить и написать корректное решение.

Только если в open-source будет выложен корректный фикс
