### ISSUE TITLE
[Броня] id 40440, 40441, 40442, 40443, 40444 Жуткий латный доспех жестокого гладиатора

### ISSUE THREAD

**Issue by PISdid** [VirginTeam/WotlkCore#1331]
**Ссылки и комментарии:**
https://wowroad.info/?item=40440
https://wowroad.info/?item=40441
https://wowroad.info/?item=40442
https://wowroad.info/?item=40443
https://wowroad.info/?item=40444
**Что работает не так?**

У брони в игре отсутствует показатель брони в игре

**Как должно работать?**

При одевании брони, в меню персонажа "Броня" должна расти, а не падать...

**Шаги для воспроизведения ошибки:**

1. Открыть инвентарь
2. Одеть броню
3. Писать в помощь о том, что маг в халате более защищен чем я в латах......

**Текущее обновление ядра:**
logon 3 wowcircle development
build 229 2018-11-29 +0400

**Comment by PISdid** [comment]
Когда поправите? А то купил, а он просто так в инвентаре валяется....

**Comment by PISdid** [comment]
Я Вас очень прошу, ну исправьте это уже пожалуйста, деньги заплатил за это, а услуга получается не оказана....

**Comment by gmRial** [comment]
Будет исправлено в обновлении.
