### ISSUE TITLE
Начисление очков арены

### ISSUE THREAD

**Issue by mishvlad** [VirginTeam/WotlkCore#1332]
**Ссылки и комментарии:**

**Что работает не так?**

По результатам 10 боев на арене начислилось 10 очков арены

**Как должно работать?**

При рейтинге команды ниже 1000 в арене 2*2 начисляется 261 ап

**Шаги для воспроизведения ошибки:**

**Текущее обновление ядра:**

Build 230 2018-11-29 15:47:19 +0400

(Ник Amstrad)

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by gmRial** [comment]
261 ап начисляется в случае, когда у команды рейтинг ~1500
