### ISSUE TITLE
[Заклинание] ID 72446 - Метка павшего воителя

### ISSUE THREAD

**Issue by ghost** [VirginTeam/WotlkCore#1333]
**Ссылки и комментарии:**

http://db.logon3.com/?spell=72446

**Что работает не так?**

Не наносит урон при парировании, уклонение или промахе автоатаки Саурфанга

> [12:47:29.739] Саурфанг Смертоносный hits Feeldark 15550
> [12:47:29.739] Саурфанг Смертоносный Метка падшего воителя Выавы 1778 (A: 5800)
> [12:47:31.047] Саурфанг Смертоносный hits Feeldark Parry
> [12:47:32.329] Саурфанг Смертоносный hits Feeldark 12400
> [12:47:32.329] Саурфанг Смертоносный Метка падшего воителя Выавы 7567
> [12:47:33.656] Саурфанг Смертоносный hits Feeldark Parry
> [12:47:34.932] Саурфанг Смертоносный hits Feeldark 13799
> [12:47:34.932] Саурфанг Смертоносный Метка падшего воителя Выавы Absorb (8373)
> [12:47:36.218] Саурфанг Смертоносный hits Feeldark 694 (A: 12637)
> [12:47:36.218] Саурфанг Смертоносный Метка падшего воителя Выавы 4195 (A: 4264)
> [12:47:37.509] Саурфанг Смертоносный hits Шэлли Miss
> [12:47:39.343] Саурфанг Смертоносный hits Шэлли 8121 (A: 9256, B: 2416)
> [12:47:39.343] Саурфанг Смертоносный Метка падшего воителя Выавы 9168
> [12:47:40.609] Саурфанг Смертоносный hits Шэлли 15006 (B: 2416)
> [12:47:40.609] Саурфанг Смертоносный Метка падшего воителя Выавы 9209
> [12:47:41.943] Саурфанг Смертоносный hits Шэлли 3568 (A: 12637, B: 2416)
> [12:47:41.943] Саурфанг Смертоносный Метка падшего воителя Выавы 9872
> [12:47:43.189] Саурфанг Смертоносный hits Шэлли Parry
> [12:47:44.456] Саурфанг Смертоносный hits Шэлли Parry
> [12:47:45.765] Саурфанг Смертоносный hits Шэлли 16923 (B: 2416)
> [12:47:45.765] Саурфанг Смертоносный Метка падшего воителя Выавы 10703
> [12:47:47.110] Саурфанг Смертоносный hits Шэлли 15664 (B: 2416)
> [12:47:47.110] Саурфанг Смертоносный Метка падшего воителя Выавы 10518
> [12:47:48.421] Саурфанг Смертоносный hits Шэлли Dodge
> [12:47:49.755] Саурфанг Смертоносный hits Шэлли Parry
> [12:47:51.033] Саурфанг Смертоносный hits Шэлли Parry
> [12:47:52.345] Саурфанг Смертоносный hits Шэлли 14773 (B: 2416)
> [12:47:52.345] Саурфанг Смертоносный Метка падшего воителя Выавы Absorb (10208)

**Как должно работать?**

Должна наносить урон в случае, если автоатака Саурфанга была спарирована, танк уклонился или босс промахнулся.

> [19:06:07.980] Deathbringer Saurfang hits Ktorrk Dodge
> [19:06:08.809] Deathbringer Saurfang Mark of the Fallen Champion  Konion 6066
> [19:06:09.345] Deathbringer Saurfang hits Ktorrk 10592 (A: 5352)
> [19:06:10.390] Deathbringer Saurfang Mark of the Fallen Champion  Konion 3083 (A: 3371)
> [19:06:10.531] Deathbringer Saurfang hits Ktorrk 7956 (A: 5389, B: 4388)
> [19:06:11.591] Deathbringer Saurfang Mark of the Fallen Champion  Konion 6682
> [19:06:11.749] Deathbringer Saurfang hits Ktorrk Parry
> [19:06:12.793] Deathbringer Saurfang Mark of the Fallen Champion  Konion 6227
> [19:06:12.948] Deathbringer Saurfang hits Flohfang 9470 (A: 15895)
> [19:06:14.002] Deathbringer Saurfang Mark of the Fallen Champion  Konion 6988
> [19:06:14.170] Deathbringer Saurfang hits Flohfang Miss
> [19:06:15.184] Deathbringer Saurfang Mark of the Fallen Champion  Konion 7115
> [19:06:15.288] Deathbringer Saurfang hits Flohfang Miss
> [19:06:16.429] Deathbringer Saurfang Mark of the Fallen Champion  Konion 7139
> [19:06:16.547] Deathbringer Saurfang hits Flohfang 3831 (A: 20828)
> [19:06:17.598] Deathbringer Saurfang Mark of the Fallen Champion  Konion 7223
> [19:06:17.710] Deathbringer Saurfang hits Flohfang 23918
> [19:06:18.815] Deathbringer Saurfang Mark of the Fallen Champion  Konion 7546

**Текущее обновление ядра:**

230

**Comment by Rorshah** [comment]
С саурфангом реально чето не так.
ДЦ в соло хилит 25.
