### ISSUE TITLE
[Заклинание] ID 68647 - Жуки-трупоеды

### ISSUE THREAD

**Issue by MedoOf** [VirginTeam/WotlkCore#1335]
Что работает не так:

1) Отхил от способности http://db.logon3.com/?spell=68647 проходит в момент нанесения урона

> [20:47:59.046] Medoff afflicted by Жуки-трупоеды from Ануб'арак
> [20:47:59.958] Ануб'арак Жуки-трупоеды Medoff 7008 (R: 1752)
> [20:47:59.958] Medoff Жуки-трупоеды Ануб'арак +7008
> [20:48:00.921] Ануб'арак Жуки-трупоеды Medoff 5391 (R: 1347)
> [20:48:00.921] Medoff Жуки-трупоеды Ануб'арак +5391
> [20:48:01.938] Ануб'арак Жуки-трупоеды Medoff 6982 (R: 1745)
> [20:48:01.938] Medoff Жуки-трупоеды Ануб'арак +6982
> [20:48:02.844] Ануб'арак Жуки-трупоеды Medoff 4952 (R: 550)
> [20:48:02.859] Medoff Жуки-трупоеды Ануб'арак +4952
> [20:48:03.799] Ануб'арак Жуки-трупоеды Medoff 4565 (R: 507)
> [20:48:03.799] Medoff Жуки-трупоеды Ануб'арак +4565

2) Коэффициент отхила от http://db.logon3.com/?spell=68647 составляет 100% для 25гер - лог выше.
Так же для 10гер составляет 100%

> [15:34:38.985] Эльрион afflicted by Жуки-трупоеды from Ануб'арак
> [15:34:39.959] Ануб'арак Жуки-трупоеды Эльрион 3971 (A: 162, R: 1771)
> [15:34:39.970] Эльрион Жуки-трупоеды Ануб'арак +3971
> [15:34:40.843] Ануб'арак Жуки-трупоеды Эльрион 3666 (R: 1571)
> [15:34:40.859] Эльрион Жуки-трупоеды Ануб'арак +3666
> [15:34:41.803] Ануб'арак Жуки-трупоеды Эльрион 3153 (R: 1351)
> [15:34:41.803] Эльрион Жуки-трупоеды Ануб'арак +3153
> [15:34:42.955] Ануб'арак Жуки-трупоеды Эльрион 3201 (R: 800)
> [15:34:42.989] Эльрион Жуки-трупоеды Ануб'арак +3201
> [15:34:43.801] Ануб'арак Жуки-трупоеды Эльрион 2353 (R: 1008)
> [15:34:43.801] Эльрион Жуки-трупоеды Ануб'арак +2353
> [15:34:44.937] Ануб'арак Жуки-трупоеды Эльрион 2717 (R: 301)
> [15:34:44.956] Эльрион Жуки-трупоеды Ануб'арак +2717

С большой вероятностью, коэффициенты для 10об и 25об также равны 100%, не проверял т.к. еще не ходил в рейды данных сложностей.

3) Отхил от http://db.logon3.com/?spell=68647 не учитывает Mod Healing Done % игроков

> [20:47:59.046] Бешенка afflicted by Жуки-трупоеды from Ануб'арак
> [20:47:59.968] Ануб'арак Жуки-трупоеды Бешенка Absorb (8008)
> [20:48:00.921] Ануб'арак Жуки-трупоеды Бешенка 4707 (A: 2411, R: 1779)
> [20:48:00.921] Бешенка Жуки-трупоеды Ануб'арак +4707
> [20:48:01.938] Ануб'арак Жуки-трупоеды Бешенка 5299 (R: 2271)
> [20:48:01.938] Бешенка Жуки-трупоеды Ануб'арак +5299
> [20:48:02.859] Ануб'арак Жуки-трупоеды Бешенка 7151
> [20:48:02.882] Бешенка Жуки-трупоеды Ануб'арак +7151

Хпал с талантом http://db.logon3.com/?spell=63650

4) Абсорб снижает исцеление

> [20:47:59.046] Бешенка afflicted by Жуки-трупоеды from Ануб'арак
> [20:47:59.968] Ануб'арак Жуки-трупоеды Бешенка Absorb (8008)
> [20:48:00.921] Ануб'арак Жуки-трупоеды Бешенка 4707 (A: 2411, R: 1779)
> [20:48:00.921] Бешенка Жуки-трупоеды Ануб'арак +4707

Как должно работать:

1) Должна быть задержка между нанесением урона и исцелением 0.8 секунды

> [21:33:48.504] Xeria afflicted by Leeching Swarm from Anub'arak
> [21:33:50.021] Anub'arak Leeching Swarm Xeria 6414 (R: 1603)
> [21:33:50.789] Xeria Leeching Swarm Anub'arak +7376
> [21:33:51.249] Anub'arak Leeching Swarm Xeria 5612 (R: 2405)
> [21:33:52.001] Xeria Leeching Swarm Anub'arak +6454
> [21:33:52.045] Anub'arak Leeching Swarm Xeria 6163 (R: 1541)
> [21:33:52.840] Xeria Leeching Swarm Anub'arak +7087
> [21:33:53.199] Anub'arak Leeching Swarm Xeria 6090 (R: 677)
> [21:33:54.017] Xeria Leeching Swarm Anub'arak +7003

2) Коэффициент отхила для сложности ИВК25 должен составлять 115% - лог выше.
6414*1.15=7378

Для сложности ИВК10 - 46%

> [23:48:48.161] Jirikhi afflicted by Leeching Swarm from Anub'arak
> [23:48:49.752] Anub'arak Leeching Swarm Jirikhi Absorb (4639)
> [23:48:50.534] Jirikhi Leeching Swarm Anub'arak +3415
> [23:48:50.970] Anub'arak Leeching Swarm Jirikhi 10 (A: 4629, R: 515)
> [23:48:51.736] Jirikhi Leeching Swarm Anub'arak +2134
> [23:48:51.750] Anub'arak Leeching Swarm Jirikhi 4122 (R: 1031)
> [23:48:52.546] Jirikhi Leeching Swarm Anub'arak +1896
> [23:48:52.546] Anub'arak Leeching Swarm Jirikhi 4360
> [23:48:53.341] Jirikhi Leeching Swarm Anub'arak +2005
> [23:48:53.767] Anub'arak Leeching Swarm Jirikhi 3592
> [23:48:54.564] Jirikhi Leeching Swarm Anub'arak +1652
> [23:48:54.573] Anub'arak Leeching Swarm Jirikhi 2519 (R: 280)
> [23:48:55.369] Jirikhi Leeching Swarm Anub'arak +1159
> [23:48:55.774] Anub'arak Leeching Swarm Jirikhi 1960 (R: 490)
> [23:48:56.570] Jirikhi Leeching Swarm Anub'arak +902

1896/4122 = 0,45997
2005/4360 = 0,4598
902/1960 = 0,4602

Для сложности ИК25 - 77.5%

> [22:08:48.116] Zelmira afflicted by Leeching Swarm from Anub'arak
> [22:08:49.676] Anub'arak Leeching Swarm Zelmira 2496
> [22:08:50.472] Zelmira Leeching Swarm Anub'arak +3868
> [22:08:50.956] Anub'arak Leeching Swarm Zelmira 2246
> [22:08:51.697] Zelmira Leeching Swarm Anub'arak +1741
> [22:08:51.798] Anub'arak Leeching Swarm Zelmira 2113
> [22:08:52.515] Zelmira Leeching Swarm Anub'arak +1638
> [22:08:52.875] Anub'arak Leeching Swarm Zelmira 1521 (R: 380)
> [22:08:53.685] Zelmira Leeching Swarm Anub'arak +1178
> [22:08:53.701] Anub'arak Leeching Swarm Zelmira 1473 (R: 368)
> [22:08:54.497] Zelmira Leeching Swarm Anub'arak +1141
> [22:08:54.904] Anub'arak Leeching Swarm Zelmira 1525 (R: 169)
> [22:08:55.682] Zelmira Leeching Swarm Anub'arak +1182
> [22:08:55.776] Anub'arak Leeching Swarm Zelmira 1426 (R: 158)
> [22:08:56.509] Zelmira Leeching Swarm Anub'arak +1105

1741/2246 = 0.77515
1178/1521 = 0.77449
1105/1426 = 0.77489

Для сложности ИК10 - 68%

> [21:54:09.500] Dragonhell afflicted by Leeching Swarm from Anub'arak
> [21:54:11.061] Anub'arak Leeching Swarm Dragonhell 1786 (R: 198)
> [21:54:11.809] Dragonhell Leeching Swarm Anub'arak +1214
> [21:54:12.276] Anub'arak Leeching Swarm Dragonhell 1625 (R: 180)
> [21:54:13.041] Dragonhell Leeching Swarm Anub'arak +1105
> [21:54:13.073] Anub'arak Leeching Swarm Dragonhell 1314 (R: 328)
> [21:54:13.805] Dragonhell Leeching Swarm Anub'arak +893
> [21:54:13.837] Anub'arak Leeching Swarm Dragonhell 1608 (R: 689)
> [21:54:14.669] Dragonhell Leeching Swarm Anub'arak +1093
> [21:54:15.088] Anub'arak Leeching Swarm Dragonhell 1792 (R: 448)
> [21:54:15.834] Dragonhell Leeching Swarm Anub'arak +1218
> [21:54:15.849] Anub'arak Leeching Swarm Dragonhell 1649 (R: 412)
> [21:54:16.660] Dragonhell Leeching Swarm Anub'arak +1121
> [21:54:17.050] Anub'arak Leeching Swarm Dragonhell 1507 (R: 377)
> [21:54:17.862] Dragonhell Leeching Swarm Anub'arak +1024
> [21:54:17.893] Anub'arak Leeching Swarm Dragonhell 1387 (R: 347)
> [21:54:18.657] Dragonhell Leeching Swarm Anub'arak +944
> [21:54:19.048] Anub'arak Leeching Swarm Dragonhell 1354 (R: 580)
> [21:54:19.843] Dragonhell Leeching Swarm Anub'arak +921
> [21:54:19.913] Anub'arak Leeching Swarm Dragonhell 1336 (R: 148)
> [21:54:20.658] Dragonhell Leeching Swarm Anub'arak +909
> [21:54:21.075] Anub'arak Leeching Swarm Dragonhell 945 (R: 405)
> [21:54:21.856] Dragonhell Leeching Swarm Anub'arak +642
> [21:54:21.887] Anub'arak Leeching Swarm Dragonhell 1130 (R: 126)
> [21:54:22.687] Dragonhell Leeching Swarm Anub'arak +769

1024/1507 = 0.67949
921/1354 = 0.6802
769/1130 = 0.6805

Во всех расчетах взяты классы и спеки не имеющие Mod Healing Done % - афлики и маги (фаеры и арканы), что позволяет с уверенностью сказать о таких коэффициентах исцеления.

3) Ауры игроков влияющие на исходящее исцеление (Mod Healing Done %) должны влиять на отхил от http://db.logon3.com/?spell=68647

> [21:33:48.504] Nepenthes afflicted by Leeching Swarm from Anub'arak
> [21:33:50.021] Anub'arak Leeching Swarm Nepenthes Absorb (5221)
> [21:33:50.789] Nepenthes Leeching Swarm Anub'arak +6304
> [21:33:51.249] Anub'arak Leeching Swarm Nepenthes Absorb (6714)
> [21:33:52.001] Nepenthes Leeching Swarm Anub'arak +8107
> [21:33:52.045] Anub'arak Leeching Swarm Nepenthes 5254 (A: 713, R: 1492)
> [21:33:52.840] Nepenthes Leeching Swarm Anub'arak +7205

52211,151,05=6304

4) Абсорб не должен снижать или как то влиять на исцеление

> [21:33:48.504] Nepenthes afflicted by Leeching Swarm from Anub'arak
> [21:33:50.021] Anub'arak Leeching Swarm Nepenthes Absorb (5221)
> [21:33:50.789] Nepenthes Leeching Swarm Anub'arak +6304
> [21:33:51.249] Anub'arak Leeching Swarm Nepenthes Absorb (6714)
> [21:33:52.001] Nepenthes Leeching Swarm Anub'arak +8107

**Comment by MedoOf** [comment]
> [16:43:43.421] Ануб'арак Жуки-трупоеды Муранни 3811 (R: 423)
> [16:43:43.581] Муранни Жуки-трупоеды Ануб'арак +6364
> [16:43:44.439] Ануб'арак Жуки-трупоеды Муранни 3020 (R: 754)
> [16:43:44.542] Муранни Жуки-трупоеды Ануб'арак +6000
> [16:43:45.393] Ануб'арак Жуки-трупоеды Муранни 1672 (R: 418)
> [16:43:45.537] Муранни Жуки-трупоеды Ануб'арак +5380
афлилок. пункт 2 в ивк 10 (46% отхила) не реализован

**Comment by ForesterDev** [comment]
```
Ewer находится под воздействием эффекта "Жуки-трупоеды" Ануб'арака.
"Жуки-трупоеды" Ануб'арака наносит Ewer 20000 единиц урона от сил природы.
"Жуки-трупоеды" Ewer исцеляет Ануб'арака на 9200 единиц здоровья.
"Жуки-трупоеды" Ануб'арака наносит Ewer 16000 единиц урона от сил природы.
"Жуки-трупоеды" Ewer исцеляет Ануб'арака на 7360 единиц здоровья.
"Жуки-трупоеды" Ануб'арака наносит Ewer 12800 единиц урона от сил природы.
"Жуки-трупоеды" Ewer исцеляет Ануб'арака на 5888 единиц здоровья.
"Жуки-трупоеды" Ануб'арака наносит Ewer 10240 единиц урона от сил природы.
"Жуки-трупоеды" Ewer исцеляет Ануб'арака на 4710 единиц здоровья.
"Жуки-трупоеды" Ануб'арака наносит Ewer 8192 единицы урона от сил природы.
"Жуки-трупоеды" Ewer исцеляет Ануб'арака на 3768 единиц здоровья.
"Жуки-трупоеды" Ануб'арака наносит Ewer 6553 единицы урона от сил природы.
```

ивк 10

**Comment by MedoOf** [comment]
Значит при накате на основу что то пошло не так. Жалуются на все сложности, у меня есть лог только с [ивк10](http://www.worldoflogs.com/reports/e49bwq5th4qm5d9l/xe/?x=spell+%3D+"Жуки-трупоеды"), и там вообще непонятный, скачущий коэффициент отхила.

**Comment by MedoOf** [comment]
Реализованы все пункты, кроме 1, задержки между нанесением урона и исцелением нет.

> [18:59:37.858] Ануб'арак Жуки-трупоеды Элкора Absorb (6630)
> [18:59:37.858] Элкора Жуки-трупоеды Ануб'арак +7624
