### ISSUE TITLE
[Игровая механика] Контроль игроков на ID 34607 - Нерубский землеглот

### ISSUE THREAD

**Issue by MedoOf** [VirginTeam/WotlkCore#1337]
**Ссылки и комментарии:**

http://db.logon3.com/?npc=34607
http://db.logon3.com/?spell=20066
http://db.logon3.com/?spell=10955
Мб еще какие-то способности, это те которые точно срабатывают а не должны.

**Что работает не так?**

Мобы контролятся.

**Как должно работать?**

Не должны контролится, восприимчивы только к замедлениям, сбитию каста и станам. форумы типо нубклаба это единственные пруфы. на видео никто и не пытается их контролить, потому что бесполезно
https://www.noob-club.ru/index.php?topic=1100.msg17607#msg17607

**Текущее обновление ядра:**

230

**Comment by gmKroshka** [comment]
Репорт будет закрыт, если не оформите по правилам

**Comment by MedoOf** [comment]
можете закрывать баги, пусть юзают люди, не собираюсь тратить свое время на поиск пруфов которые разраб даже не посмотрит

**Comment by Rorshah** [comment]
Да это хейтер. Сем себе плащиг набагал а теперь типа закройте лазейку.
Э-нет.
Плащики на халявку всем нужны.

**Comment by MedoOf** [comment]
оформил жы. нереально найти видео где их контролят.

**Comment by Rorshah** [comment]
мозгов не хватало контролить. Вот и видео нет.
А на вирджине только таланты играют. Вот за 8 лет доперло до них наконец-то.

**Comment by MedoOf** [comment]
Удалите метку требуется оформление.
