### ISSUE TITLE
[Игровая механика] ID 32865 - Торим (Запуск обычного режима сложности)

### ISSUE THREAD

**Issue by ghost** [VirginTeam/WotlkCore#1339]
**Ссылки и комментарии:**

Таймер запуска обычного режима

**Что работает не так?**

таймер сбит, не соответствует дбму, нужно ждать лишние секунд 10-15 чтобы прокнул об режим

**Как должно работать?**

`local timerHardmode				= mod:NewTimer(175, "TimerHardmode", 62042)` - ДБМ
`self:Bar("hardmode", L["hardmode"], 173, 6673)` - Биг Вигс
https://youtu.be/5q7xGDyQJlg?t=64 - таймеры дбма на видео

**Текущее обновление ядра:**

230

**Comment by MedoOf** [comment]
Удалите требуется оформление

**Comment by Kodekc** [comment]
Скрипт был переписан в недавнем обновлении. Требуется перепроверить данный репорт и сообщить актуальную информацию.
