### ISSUE TITLE
[Поле боя] Берег древних и снижение фпс при открытой статистике поле боя

### ISSUE THREAD

**Issue by Gooldark** [VirginTeam/WotlkCore#134]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Что работает не так?**

Когда игрок на поле боя Берег древних открывает статистику идет резкое снижение фпса, до тех пор пока игрок ее не закроет.

**Как должно работать?**

Фпс снижаться не должно.

**Текущее обновление ядра:**

24.04.2017. 155 билд

**Comment by Kodekc** [comment]
Не воспроизводится. Может из-за какого-то аддона происходит подобное?

**Comment by gmRial** [comment]
Отслеживание достижений/заданий так же влияет на фпс.

**Comment by kalipsa988** [comment]
последний раз замечал то, что ФПС начинал падать при начале боя, отмена слежения ачив, открытие/закрытие статистики не помогало

**Comment by Kodekc** [comment]
Оптимизировано обновление объектов на БГ. Должно исправить проблему с просадкой ФПС на Береге Древних
