### ISSUE TITLE
[Заклинания] ID 73174 - Губительный газ

### ISSUE THREAD

**Issue by ghost** [VirginTeam/WotlkCore#1346]
**Ссылки и комментарии:**

http://db.logon3.com/?spell=73174 

**Что работает не так?**

[Источник урона босс](http://www.worldoflogs.com/reports/iw8fl65kfy7l40wv/xe/?s=8849&e=9063&x=spellID+%3D+73174)

**Как должно работать?**

[Источником урона должен быть игрок](http://www.worldoflogs.com/reports/lkfgldp7rx8dbqan/xe/?s=3463&e=3660&x=spellID+%3D+73174)

**Текущее обновление ядра:**

231

**Comment by MedoOk** [comment]
https://github.com/VirginTeam/WotlkCore/issues/1347#issuecomment-552115164 актуально и для этого

**Comment by ForesterDev** [comment]
Исправлено
