### ISSUE TITLE
[Существа] ID 36897 - Малый слизнюк

### ISSUE THREAD

**Issue by MedoOf** [VirginTeam/WotlkCore#1349]
**Ссылки и комментарии:**

http://db.logon3.com/?npc=36897

**Что работает не так?**

[завышен урон автоатаки](http://www.worldoflogs.com/reports/iw8fl65kfy7l40wv/xe/?s=8502&e=8692&x=sourceName+%3D+"Малый+слизнюк"%0D%0AAND+%28fullType+%3D+SWING_DAMAGE+OR+fullType+%3D+SWING_MISSED%29)
ну там типо надо посчитать и получится что у нас бьет примерно в 2-2,5 раза больше
**Как должно работать?**

[как-то так](http://www.worldoflogs.com/reports/lkfgldp7rx8dbqan/xe/?s=3113&e=3290&x=sourceName+%3D+"Little+Ooze"%0D%0AAND+%28fullType+%3D+SWING_DAMAGE+OR+fullType+%3D+SWING_MISSED%29)

**Текущее обновление ядра:**

231

**Comment by ForesterDev** [comment]
Исправлено
