### ISSUE TITLE
[Заклинание] ID 6358 - Соблазн

### ISSUE THREAD

**Issue by Gooldark** [VirginTeam/WotlkCore#135]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

ID 6358 - Соблазн
Соблазнение, заставляющее замереть противника на 15 sec. Эффект снимается при получении урона. Действует только на гуманоидов.

Баг появился после исправления ошибки, когда петы не хотели двигаться, а затем использовать способности на цель в лосе/при недостатке дальности действия. Есть подозрение что баг вызывается командой "выполнять предыдущую команду" после использования этой способности по причине того, что ID 6358 - Соблазн состоит из двух кастов(наложения и поддержания) и команда "выполнять предыдущую команду" срабатывает сразу после каста наложения, а не разрыва каста поддержания.

**Что работает не так?**

ID 6358 - Соблазн прерывается сразу после наложения, при этом вешается диминишинг

**Как должно работать?**

ID 6358 - Соблазн должно накладываться на цели без проблем

**Шаги для воспроизведения ошибки:**

1. Поставить суккубу в пассивное положение
2. Использовать спел

В случае если суккуб бил уже эту цель или стоял на защите/агрессиве баг не проявляется.

**Текущее обновление ядра:**

25.04.2017. 155 билд

**Comment by andrushk4** [comment]
Полностью поддерживаю автора, а разработчикам просьба исправить этот баг.

**Comment by ForesterDev** [comment]
Протестируйте на OpenTest

**Comment by Gooldark** [comment]
Уже лучше, но похоже если использовать спел через механику, когда пет не достает спелом до цели, то каст продолжает рваться.

https://www.youtube.com/watch?v=N0a6C1OTfi0&feature=youtu.be

**Comment by Gooldark** [comment]
Похоже спел рвется потому что используется его копия, которая не тратит мп пету, эта проблема всех петов касается, нужно будет перенести репорт.

**Comment by andrushk4** [comment]
И хотелось бы еще добавить, когда сам бегаешь и жмешь в движении соблазн, то пет его не вешает, он кастует но эффекта 0.

**Comment by Kodekc** [comment]
Актуально и что именно?
