### ISSUE TITLE
[Заклинание] ID 72443 - Кипящая кровь

### ISSUE THREAD

**Issue by MedoOf** [VirginTeam/WotlkCore#1351]
**Ссылки и комментарии:**

http://db.logon3.com/?spell=72443

**Что работает не так?**

[режется броней](http://www.worldoflogs.com/reports/iw8fl65kfy7l40wv/xe/?s=7757&e=7920&x=spellid+%3D+72443)

**Как должно работать?**

[не должно резаться броней только % модификаторами](http://www.worldoflogs.com/reports/lkfgldp7rx8dbqan/xe/?s=2512&e=2669&x=spellid+%3D+72443)

**Текущее обновление ядра:**

231

**Comment by ForesterDev** [comment]
Исправлено
