### ISSUE TITLE
[Заклинание] ID 75125 - Шторм клинков

### ISSUE THREAD

**Issue by ghost** [VirginTeam/WotlkCore#1352]
**Ссылки и комментарии:**

http://db.logon3.com/?spell=75125

**Что работает не так?**

Балтар двигается во время http://db.logon3.com/?spell=75125

**Как должно работать?**

Должен стоять на месте все время каста http://db.logon3.com/?spell=75125

**Текущее обновление ядра:**

231

**Comment by ForesterDev** [comment]
Должен двигаться
