### ISSUE TITLE
[Заклинание] ID 74509 - Отражающая волна

### ISSUE THREAD

**Issue by MedoOf** [VirginTeam/WotlkCore#1353]
**Ссылки и комментарии:**

http://db.logon3.com/?spell=74509

**Что работает не так?**

http://db.logon3.com/?spell=74509 не используется если перед ним паладин использует в босса http://db.logon3.com/?spell=10308, возможно также работает и с другим станами

**Как должно работать?**

Стан никак не должен влиять на волну

**Текущее обновление ядра:**

231

**Comment by ForesterDev** [comment]
Исправлено
