### ISSUE TITLE
[Заклинание] ID 70823 - Холодное пламя

### ISSUE THREAD

**Issue by zyxellgit** [VirginTeam/WotlkCore#1359]
**Ссылки и комментарии:**

http://db.logon3.com/?spell=70823

Холодное пламя Мгновенное действие Наносит 8000 ед. урона от магии льда раз в 1 с в течение 3 сек..

**Что работает не так?**

Ребрад разливает лужи во время вихря от атак мдд 

**Как должно работать?**
 Каждый раз, как Ребрад настигает жертву и останавливается, он выпускает четыре полосы холодного пламени

**Шаги для воспроизведения ошибки:**

![default](https://user-images.githubusercontent.com/29210390/49667460-ef270280-fa7c-11e8-90a1-affcc2fabb7a.jpg)

вот в чате авторитетно заявляют
**Текущее обновление ядра:**

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by sega693** [comment]
пруфы то где кроме чата?

**Comment by MedoOf** [comment]
да это древняя легенда циркуля, с ядра 2012 года еще, когда на одной из обнов кровотечения действительно вызывали нонстоп спам луж, но это тогда и пофиксили, а слухи до сих пор гуляют по серверу

**Comment by zyxellgit** [comment]
никаких пруфов. только железобетонная уверенность 80% рейдеров что атаки мдд вызывают лужи.
зайти в любой рейд и там будут вопли что мдд налили лужи

**Comment by gmRial** [comment]
Не более чем слухи. Закрыто.
