### ISSUE TITLE
[Общая механика] Защита дебафа земедления с помощью вторичных эффектов

### ISSUE THREAD

**Issue by Gooldark** [VirginTeam/WotlkCore#136]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

а) группа заклинаний к которым относятся
I. ID 31589 - Замедление, ID 58181 - Зараженные раны, ID 51693 - Засада, ID 48466 - Гроза + ID 54873 - Символ грозы, ID 168 - Морозный доспех, ID 7302 - Ледяной доспех.

группа заклинаний к которым относятся
II. ID 1044 - Длань свободы, ID 26889 - Исчезновение, ID 48020 - Демонический круг: телепортация, ID 53271 - Приказ хозяина.

б) 
I. ID 12571 - Вечная мерзлота которая прикреплена к ID 168 - Морозный доспех, ID 7302 - Ледяной доспех, ID 42931 - Конус холода, ID 47610 - Стрела ледяного огня, ID 42842 - Ледяная стрела, ID 12488 - Свирепая снежная буря.

группа заклинаний к которым относятся
II. ID 1044 - Длань свободы, ID 26889 - Исчезновение, ID 48020 - Демонический круг: телепортация, ID 53271 - Приказ хозяина.

**Что работает не так?**

а) группа заклинаний II полностью снимает дебафы группы I.

б) группа заклинаний II полностью снимает дебафы группы I защищенные ID 12571 - Вечная мерзлота

**Как должно работать?**

а) группа заклинаний II должна снимать только замедление скорости бега, снижение скорости атаки/каста от дебафов группы I должны оставаться.

б) группа заклинаний II должна снимать только замедление скорости бега, срез хила от ID 12571 - Вечная мерзлота должен защищать дебафы группы I от полного удаления эффекта.

**Текущее обновление ядра:**

25.04.2017. 155 билд

**Перенесено**

Все доказательства здесь - http://forum.wowcircle.com/showthread.php?t=511189 и в теме 1-ого логона http://forum.wowcircle.com/showthread.php?t=501639

**Comment by kalipsa988** [comment]
http://db.logon3.com/?spell=4060 полностью снимается, фридомом точно, должно сниматься только замедление, а дебаф на понижение спд и урона должен оставаться
