### ISSUE TITLE
(КВЕСТ)-Машина для убийств

### ISSUE THREAD

**Issue by Tirend1** [VirginTeam/WotlkCore#1364]
Машина для убийств (В Долине призрачной луны)

**Ссылки и комментарии:**

https://ru.wowhead.com/quest=10613/%D0%BC%D0%B0%D1%88%D0%B8%D0%BD%D0%B0-%D0%B4%D0%BB%D1%8F-%D1%83%D0%B1%D0%B8%D0%B9%D1%81%D1%82%D0%B2%D0%B0
**Что работает не так?**
Когда юзаеш пульт робот непоявляеться а просто стоиш на месте и тикает время

**Как должно работать?**
Юзаеш пульт.тебя переносят в облике робота и начинаеш за 4 мин убивать 60 големов.Убил отменил пульт.переносит назад в твой облик.
**Шаги для воспроизведения ошибки:**

1. Пульт
2. Появляеться таимер внизу что ты чтота юзаеш но нечего непроисходит
3. Просто нечего непроисходит

**Текущее обновление ядра:**

Можно посмотреть в игре, введите в чат команду .server info и скопировать строку начиная с Build с номером и датой. Не забывайте указывать, Live Server или PTR Server, где проводилось тестирование.
Build 232

**Comment by gmKroshka** [comment]
https://github.com/VirginTeam/WotlkCore/issues/352
