### ISSUE TITLE
[Задание]Cамая опасная ловушка

### ISSUE THREAD

**Issue by Tirend1** [VirginTeam/WotlkCore#1373]
**Ссылки и комментарии:**
https://ru.wowhead.com/quest=11097/%D1%81%D0%B0%D0%BC%D0%B0%D1%8F-%D0%BE%D0%BF%D0%B0%D1%81%D0%BD%D0%B0%D1%8F-%D0%BB%D0%BE%D0%B2%D1%83%D1%88%D0%BA%D0%B0#videos:id=1866т.д. 

**Что работает не так?**

командир небежыт на драку.драконы на битву непоявляються
Квест никак несделать

**Как должно работать?**

Ожидаемый результат — то, чего вы ожидали при выполнении ваших действий. Процесс правильной работы

**Шаги для воспроизведения ошибки:**

1. Командир идёт к команде
2. Драконы появляються
3. 1-2 мин драка и сдаём квест

**Текущее обновление ядра:**

233

**Comment by gmKroshka** [comment]
https://github.com/VirginTeam/WotlkCore/issues/360
