### ISSUE TITLE
[Заклинание] ID 20337 - Сердце рыцаря

### ISSUE THREAD

**Issue by Gooldark** [VirginTeam/WotlkCore#138]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

ID 20337 - Сердце рыцаря
В дополнение к обычному эффекту ваши заклинания категории "Правосудие" повышают вероятность того, что цели заклинания будет нанесен критический удар, на 3%.

**Что работает не так?**

ID 20337 - Сердце рыцаря не привязано к сопутствующим эффектам правосудия.

**Как должно работать?**

ID 20337 - Сердце рыцаря должно исчезать если ID 53407 - Правосудие справедливости; ID 53408 - Правосудие мудрости; ID 20271 - Правосудие света закончилось/было сдиспейлено.

**Шаги для воспроизведения ошибки:**

1. Покачать талант
2. Ударить джагой цель
3. Сдиспейлить джагу

**Текущее обновление ядра:**

25.04.2017. 155 билд

**Перенесено**

Все доказательства здесь http://forum.wowcircle.com/showthread.php?t=505690

**Comment by gmRial** [comment]
Исправлено, после обновления.
