### ISSUE TITLE
[Заклинания] ID 72507 - Мутировавшая чума

### ISSUE THREAD

**Issue by ghost** [VirginTeam/WotlkCore#1380]
**Ссылки и комментарии:**

http://db.logon3.com/?spell=72507

**Что работает не так?**

[Заниженный урон. первый тик 325](http://www.worldoflogs.com/reports/yu8elomjhtjrycxt/xe/?s=2579&e=2884&x=spellID+%3D+72507)
Должен быть 750 согласно формулы от зороастра:

> Базовый урон правильный. Для 25г он равен 250
> Формула расчета урона в зависимости от стаков имеет вид
> D = Base*(k^n), где
> D - урон
> n - количество стаков
> k - коэф., зависящий от уровня сложности подземелья (для 25г он равен 3; для всех остальных сложностей 2,5).
https://github.com/VirginTeam/WotlkCore/issues/889#issuecomment-383080329

Возможно у нас стоит коэф 1.3 а не 3. 250*1,3=325. чисто так предположение
**Как должно работать?**

[Первый тик 750, что совпадает с формулой зороастра](http://www.worldoflogs.com/reports/lkfgldp7rx8dbqan/xe/?s=4386&e=4828&x=spellID+%3D+72507)

**Текущее обновление ядра:**

233

**Comment by ForesterDev** [comment]
![image](https://user-images.githubusercontent.com/11771800/53880232-eb7a2c00-4029-11e9-8fb8-29041378346b.png)
750, возможно режется какими-то эффектами

**Comment by MedoOf** [comment]
http://www.worldoflogs.com/reports/0eonazoxkrzqts73/xe/?x=spellID+%3D+72507 - более новый лог. Я не представляю что может урезать урон в 2-3 раза, это магия, резистов не проходит если верить логам.
Возможно, что существует аое кап урона? Заклинание наносит урон, который нанесло бы 10 целям, тогда получается примерно это снижение 2,5 раза (25 человек, общий урон как для 10)?
