### ISSUE TITLE
[Заклинание] ID 72817 - Могучий вихрь

### ISSUE THREAD

**Issue by MedoOf** [VirginTeam/WotlkCore#1383]
**Ссылки и комментарии:**

http://db.logon3.com/?spell=72817 

**Что работает не так?**

[Снижается броней](http://www.worldoflogs.com/reports/yu8elomjhtjrycxt/xe/?s=3312&e=3511&x=spellID+%3D+72817)

**Как должно работать?**

[Только % модификаторы, видно на шп, фурике](http://www.worldoflogs.com/reports/lkfgldp7rx8dbqan/xe/?s=5390&e=5591&x=spellID+%3D+72817)

**Текущее обновление ядра:**

233

**Comment by ForesterDev** [comment]
Исправлено
