### ISSUE TITLE
[Задание] ID 13481 - Валим отсюда!

### ISSUE THREAD

**Issue by Nattpyre** [VirginTeam/WotlkCore#139]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

По сути, квест является практически полной копией [Я еще жив!](http://ru.wowhead.com/quest=13229) из другой фазы, и должен быть он доступен только для тех, кто этот самый квест не делал. Так же, квест из другой фазы полностью рабочий, а этот почему-то нет. В принципе, наверное можно даже скопировать скрипты из того квеста в этот.

**Что работает не так?**

После взятия квеста NPC не идет по маршруту. Так же квест доступен тогда, когда этого не должно быть. 

**Как должно работать?**

Квест не должен быть доступен, если сделан квест [Я еще жив!](http://ru.wowhead.com/quest=13229). Ну и соответственно NPC должен давать бафф и идти по маршруту, т.е. все то, что он делает в своей версии из другой фазы.

**Шаги для воспроизведения ошибки:**

1. Сделать квест http://ru.wowhead.com/quest=13229
2. Увидеть, что сабж доступен для взятия
3. Взять и его и увидеть, что он не работает.

**Текущее обновление ядра:**

Build 155 2017-04-20 14:36:20 +0400

**Comment by Nattpyre** [comment]
Ах да, забыл еще добавить. NPC [Отец Камарос](http://ru.wowhead.com/npc=31279) из фазы, где квест работает постоянно убиваем мобами, поэтому чтобы получить квест и выполнить его нужно предварительно зачистить место его дислокации и ждать его респа. По идее, до взятия квеста мобы должны его игнорировать.

**Comment by gmOverfire** [comment]
Актуально.
Проблемные НПЦ:
http://db.logon3.com/?npc=32800 - залипают скрипты после боя с НПЦ, не реагирует.
http://db.logon3.com/?npc=31279
