### ISSUE TITLE
[Заклинание] ID 73039 - Могучий вихрь

### ISSUE THREAD

**Issue by MedoOf** [VirginTeam/WotlkCore#1390]
**Ссылки и комментарии:**

http://db.logon3.com/?spell=73039

**Что работает не так?**

[режется броней](http://www.worldoflogs.com/reports/yu8elomjhtjrycxt/xe/?s=3312&e=3511&x=spellID+%3D+73039)

**Как должно работать?**

[не режется, только % таланты и бафы](http://www.worldoflogs.com/reports/rt-r5f2snbjkubaus69/xe/?s=4164&e=4382&x=spellID+%3D+73039)

**Текущее обновление ядра:**

231

**Comment by ForesterDev** [comment]
Уже не актуально
