### ISSUE TITLE
[Заклинание] ID 72814 - Сотрясающий вихрь

### ISSUE THREAD

**Issue by MedoOf** [VirginTeam/WotlkCore#1391]
**Ссылки и комментарии:**

http://db.logon3.com/?spell=72814 

**Что работает не так?**

[влияет броня](http://www.worldoflogs.com/reports/yu8elomjhtjrycxt/xe/?s=3312&e=3511&x=spellID+%3D+72814)

**Как должно работать?**

[только % модификаторы]([](http://www.worldoflogs.com/reports/rt-r5f2snbjkubaus69/xe/?s=4164&e=4382&x=spellID+%3D+72814))

**Текущее обновление ядра:**

231

**Comment by ForesterDev** [comment]
Исправлено
