### ISSUE TITLE
[NPC] ID 18750 - Блестящий угорь

### ISSUE THREAD

**Issue by Santaria** [VirginTeam/WotlkCore#1398]
**Ссылки и комментарии:**

https://ru.wowhead.com/npc=18750

**Что работает не так?**

Заселены только в южной части озера Силмир.

**Как должно работать?**

Должны быть заселены по всему озеру.

**Текущее обновление ядра:**

Build 234

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by Kodekc** [comment]
[Существа] ID 18750 - Блестящий угорь
* Перезаселены. Было = 10 Стало = 15
