### ISSUE TITLE
[Задание] ID 13371 - В ожидании дальнейших распоряжений

### ISSUE THREAD

**Issue by gmOpex** [VirginTeam/WotlkCore#140]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Нет нпс в фазе, нет портала из штормграда к нпс около подгорода.

**Что работает не так?**

После получения задания не появляется портал около Короля Вариана к Подгороду, так же отсутсвуют нпс в нужной фазе около подгорода https://pp.userapi.com/c836528/v836528153/30768/ptt3bhb0ImM.jpg

**Как должно работать?**

Должен создаваться портал к черному входу подгорода, на скриншоте видно куда. В фазе должен появляться сам портал и два нпс ангел ресальщик вроде не от туда.

**Текущее обновление ядра:**
Build 155 2017-04-20 14:36:20 +0400

**Comment by MiceRus** [comment]
скоро 2 года.
Может все-таки перестанете придумывать всякие непонятные Потасовки для 2-3 человек и сделаете то, ради чего народ идет в игру на ПВЕ-сервер - ради квестов.
