### ISSUE TITLE
[NPC] ID 18670 - Железнозуб

### ISSUE THREAD

**Issue by Santaria** [VirginTeam/WotlkCore#1401]
**Ссылки и комментарии:**

http://db.logon3.com/?npc=18670

**Что работает не так?**

Неправильное заселение.

**Как должно работать?**

Волк с именем, должен быть заселен в единственном экземпляре.
Вместо лишних копий, вероятно, должны быть заселены другие волки, характерные для этой локации - https://ru.wowhead.com/npc=18477

**Текущее обновление ядра:**

Build 234

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by Kodekc** [comment]
[Существа] ID 18670 - Железнозуб
* Перезаселены. Было = 24 Стало = 1

[Существа] ID 18477 - Вожак лесных воргов
* Перезаселены. Было = 47 Стало = 80

Изменения будут применены в ближайшем обновлении
