### ISSUE TITLE
[Задание] ID 10915 - Падший экзарх

### ISSUE THREAD

**Issue by Santaria** [VirginTeam/WotlkCore#1403]
**Ссылки и комментарии:**

https://ru.wowhead.com/quest=10915
https://ru.wowhead.com/npc=22452

https://www.youtube.com/watch?v=jDHPdL7NDcE&feature=youtu.be

**Что работает не так?**

Отсутствует фраза от призываемого **NPC 22452**

**Как должно работать?**

Фраза на английском: "You have brought me back too soon! I am weak yet... What is this! Who... It matters not! DIE!"
Фраза на русском: "Ты вернул меня назад слишком рано! Я еще слаб... Что это! Кто... Неважно! УМРИ!"

**Trinity:** https://github.com/TrinityCore/TrinityCore/issues/18598

**Текущее обновление ядра:**

Build 234

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by Kodekc** [comment]
Портированы скрипты с Trinity. Изменения будут применены в ближайшем обновлении
