### ISSUE TITLE
Улучшенное благословение мудрости

### ISSUE THREAD

**Issue by kate18158** [VirginTeam/WotlkCore#1411]
Талант https://db.ezwow.org/?spell=20245 Улучшенное благословение мудрости (Паладин) не работает и соответственно https://db.ezwow.org/?spell=19853 благословение мудрости дает меньше регенерации маны, чем это требуется.

**Comment by Santaria** [comment]
Баг только визуальный, в списке бафов персонажа. Если посмотреть на характеристики персонажа, то там мп5 увеличивается в соответствии с бонусом таланта.
