### ISSUE TITLE
[Заклинание] ID 71821 - Сумеречная кровяная стрела

### ISSUE THREAD

**Issue by MedoOf** [VirginTeam/WotlkCore#1413]
Ссылки и комментарии:

http://db.logon3.com/?spell=71821
http://db.logon3.com/?spell=71480

Что работает не так?

[на наземной и взлетной фазе используется http://db.logon3.com/?spell=71480](http://www.worldoflogs.com/reports/yu8elomjhtjrycxt/xe/?s=3800&e=4080&x=spellid%3D71821%0D%0Aor+spellid+%3D+71480)

Как должно работать?

[на наземной фазе используется http://db.logon3.com/?spell=71821, на взлетной - http://db.logon3.com/?spell=71480](http://www.worldoflogs.com/reports/1eqihkl5ev90v8a3/xe/?s=6340&e=6609&x=spellid%3D71821%0D%0Aor+spellid+%3D+71480)

Текущее обновление ядра:

09.12.2018

**Comment by ForesterDev** [comment]
Исправлено, будет применено в обновлении
