### ISSUE TITLE
[Заклинание] ID 71483 - Кровавый всплеск

### ISSUE THREAD

**Issue by MedoOf** [VirginTeam/WotlkCore#1415]
**Ссылки и комментарии:**

http://db.logon3.com/?spell=71483

**Что работает не так?**

[источник урона босс](http://www.worldoflogs.com/reports/yu8elomjhtjrycxt/xe/?s=3800&e=4080&x=spellid+%3D+71483)

**Как должно работать?**

[источник урона игрок](http://www.worldoflogs.com/reports/1eqihkl5ev90v8a3/xe/?s=6340&e=6609&x=spellid+%3D+71483)

**Текущее обновление ядра:**

09.12.2018

**Comment by ForesterDev** [comment]
Исправлено, будет применено в обновлении
