### ISSUE TITLE
[Заклинание] ID 72640 - Роящиеся тени

### ISSUE THREAD

**Issue by MedoOf** [VirginTeam/WotlkCore#1417]
**Ссылки и комментарии:**

http://db.logon3.com/?spell=72640 

**Что работает не так?**

Отсутствует применение и урон от http://db.logon3.com/?spell=72640

**Как должно работать?**

[лог с офа](http://www.worldoflogs.com/reports/1eqihkl5ev90v8a3/xe/?s=6340&e=6609&x=spellid+%3D+72640%0D%0Aor+spellid+%3D+72637)
Должен наноситься урон пока висит дебаф

**Текущее обновление ядра:**

09.12.2018

**Comment by ForesterDev** [comment]
Исправлено, будет применено в обновлении

**Comment by MedoOf** [comment]
[236 ап, не работает](http://www.worldoflogs.com/reports/9vokfvkdeppg0dtu/xe/?s=5251&e=5480&x=spellid+%3D+72640)
