### ISSUE TITLE
[Заклинание] ID 70946 - Укус вампира

### ISSUE THREAD

**Issue by MedoOf** [VirginTeam/WotlkCore#1418]
**Ссылки и комментарии:**

http://db.logon3.com/?spell=70946

**Что работает не так?**
Скорее всего во всех сложностях используются разные Укус вампира:
http://db.logon3.com/?spell=70946
http://db.logon3.com/?spell=71475
http://db.logon3.com/?spell=71476
http://db.logon3.com/?spell=71477

хм...получается у нас используется http://db.logon3.com/?spell=71477, в то время как в логах офа http://db.logon3.com/?spell=70946, хотя сложность 25гер и там и там.
[1](http://www.worldoflogs.com/reports/yu8elomjhtjrycxt/xe/?s=3800&e=4080&x=spellid+%3D+71729%0D%0Aor+spellid+%3D+70946)

**Как должно работать?**
Должно использоваться одно заклинание для всех сложностей http://db.logon3.com/?spell=70946:
10об:
[1](http://www.worldoflogs.com/reports/97zsehhats3j6zl4/xe/?s=3737&e=3975&x=spell+%3D+"Vampiric+Bite")
[2](http://www.worldoflogs.com/reports/auv3jy8e4u9rvsvh/xe/?s=2601&e=2854&x=spell+%3D+"Vampiric+Bite")
[3](http://www.worldoflogs.com/reports/x2u6w4rje2lllicb/xe/?s=2716&e=2947&x=spell+%3D+"Vampiric+Bite")
10гер:
[1](http://www.worldoflogs.com/reports/pi2yyil7qaih8wgv/xe/?s=4257&e=4447&x=spell+%3D+"Vampiric+Bite")
[2](http://www.worldoflogs.com/reports/dzk7k53iso2b5z67/xe/?s=4984&e=5173&x=spell+%3D+"Vampiric+Bite")
[3](http://www.worldoflogs.com/reports/rt-nj4ubfxclnyvyc6o/xe/?s=1016&e=1209&x=spell+%3D+"Vampiric+Bite")
25об:
[1](http://www.worldoflogs.com/reports/55yojf6blknh14cc/xe/?s=7849&e=8152&x=spell+%3D+"Vampiric+Bite")
[2](http://www.worldoflogs.com/reports/5lotf1efp2r51a2f/xe/?s=11350&e=11661&x=spell+%3D+"Vampiric+Bite")
[3](http://www.worldoflogs.com/reports/9hvj77qexapno5qz/xe/?s=9100&e=9411&x=spell+%3D+"Vampiric+Bite")
25гер:
[как то так](http://www.worldoflogs.com/reports/1eqihkl5ev90v8a3/xe/?s=6340&e=6609&x=spellid+%3D+71729%0D%0Aor+spellid+%3D+70946)
 Еще 3 лога с офа для сложности 25гер в комментарии. везде укус с айди 70946
**Текущее обновление ядра:**

09.12.2018

**Comment by ForesterDev** [comment]
![saas](https://user-images.githubusercontent.com/11771800/51036929-1450e880-15c8-11e9-9773-32ad784843bf.png)
Все логируется

**Comment by Rorshah** [comment]
Посмотрел логи прошлого рейда, укус действительно дает урон.
Все как на офе.
Может у тебя человек с укусом помер, не успев передать его?

**Comment by Rorshah** [comment]
Единственное хочу че добавить. На офе не вижу резистов на укусе.
А у нас резистится.
Особенно во че впечатлило:
[23:22:25.658] Окрил Укус вампира Dave 1737 (A: 5378)

**Comment by MedoOf** [comment]
во первых А - абсорб, во 2 - у нас укус физа как и должно быть, физа не может резиститься

**Comment by Rorshah** [comment]
а вон в тех, последних, вижу абсорб, ага.

**Comment by MedoOf** [comment]
Добавил новую инфу по заклинанию в тело репорта.

**Comment by ForesterDev** [comment]
Либо логи некорректные, либо с другой версии или сервера

в DBC четко указано

Spell difficulty Ids:
Normal 10: 70946
Normal 25: 71475
Heroic 10: 71476
Heroic 25: 71477

И не логично использовать на всех сложностях один и тот же спелл из нормала 10ки

**Comment by Rorshah** [comment]
заложить и использовать разные вещи. Возможно изначально предполагалось, что на разных уровнях сложности будут использованы разные значения уронов.
Но по факту близы пришли к тому что на всех уровнях действует одна величина.

Если есть сомнения в приведенных логах, приведите логи в которых используется укус для 25гер.
Иначе нужно просто сделать как в оригинальном wotlk не смотря на то что там в тултипах написано.

**Comment by MedoOf** [comment]
Все логи точно с 3.3.5а, видно по датам, да и я всегда стараюсь подбирать август-сентябрь 2010, чтобы максимально приближено к нашему серверу было.
Насчет логики...это же близы.
Сколько нужно логов чтобы это считалось пруфом? Я посчитал что 3 логов по всем 4 сложностям хватит. Могу накидать сколько скажешь.
К тому же на вовхеде существует только https://ru.wowhead.com/spell=70946, остальных там нет, понятно что там 8.+ патч, но тоже показательно

**Comment by Kodekc** [comment]
DBC - это то, что заложено в клиенте игры, это не фантазии тринити, они, как и мы, оперируем данными с клиента игры. Не логично использовать одно заклинание на все сложности, так как во многих других подземельях используется именно такая последовательность, одно заклинание - одна версия сложности рейда.

**Comment by MedoOf** [comment]
1 пруф - логи с 3.08 по 24.09 - это патч 3.3.5а
2 пруф - на вовхеде есть только 70946
3 пруф - заклинания для различных сложностей редко имеют айди подрят
При этом у нас всегда логи считались достаточным пруфом, остальное лишь еще больше доказывает правоту репорта

**Comment by Rorshah** [comment]
Тут пруфов на десять репортов. 
Похоже "Уточнить детали" означает - "лень переделывать пусть уж остается так как есть",
а не как можно подумать - "приведите логи с офф-сервера".

**Comment by Kodekc** [comment]
1. Логи это не 100% пруф, на этот сайт могут попасть различные логи, в том числе с пираток
2. На wowhead нет служебных или серверных скриптов и ещё кучи другого, что отпарсили они или им разрешили отпарсить, то и показывают
3. Нет, это не так, таких совпадений достаточно

Уточнить детали я поставил для себя, а не для игроков, чтоб спросить по репорту разработчика, не надо умничать на этот счёт.

**Comment by Rorshah** [comment]
https://github.com/VirginTeam/WotlkCore/issues/894
ну вот тут к примеру с 20 апреля никак нельзя спросить у разработчика.
Очень опасный тэг :)

**Comment by ForesterDev** [comment]
Будет исправлено в обновлении
