### ISSUE TITLE
[Задание] ID 11512 Ледяное сердце Исулдофа 

### ISSUE THREAD

**Issue by Torzag** [VirginTeam/WotlkCore#1421]
**Ссылки и комментарии:**
https://ru.wowhead.com/quest=11512/ледяное-сердце-исулдофа#comments - квест
https://ru.wowhead.com/item=34237/ледяное-сердце-исулдофа - квест итем

**Что работает не так?**
Квест итема нет на месте

**Как должно работать?**
Квест итем должен быть в пещере по координатам 32.79

**Шаги для воспроизведения ошибки:**

1. Взять квест "ледяное-сердце-исулдофа" (https://ru.wowhead.com/quest=11512/ледяное-сердце-исулдофа#comments)
2. Пройти в пещеру по координатам 32.79
3. Увидеть пустое место)

**Текущее обновление ядра:**
Build 235 2018-12-27   Сервер Live

Ник для связи: Torzag

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by Torzag** [comment]
Я записал видео, где в течение 30 минут ничего не появляется.
Ссылка: https://yadi.sk/i/V5wgiTU4mgUYpQ
Прошу проверить.

**Comment by Torzag** [comment]
Сердце появилось по координатам 34:80, что немного отличается от официальных и вводит в заблуждение.
Но это лучше, чем ничего. Если есть возможность, хорошо бы переместить сердце туда, где оно должно быть. Если нет, то репорт можно закрыть)

**Comment by gmRial** [comment]
А с какой целью я дал вам ссылку на объект? Смотрите в нашу базу данных, она показывает актуальное местоположение обектов.
Если находится не там, можете оформить репорт на эту тему.
