### ISSUE TITLE
[Задание] "Марен Грозовая Вершина"

### ISSUE THREAD

**Issue by AlessandraRain** [VirginTeam/WotlkCore#1423]
**Ссылки и комментарии:**

[Марен Грозовая Вершина](https://ru.wowhead.com/quest=1679/%D0%BC%D0%B0%D1%80%D0%B5%D0%BD-%D0%B3%D1%80%D0%BE%D0%B7%D0%BE%D0%B2%D0%B0%D1%8F-%D0%B2%D0%B5%D1%80%D1%88%D0%B8%D0%BD%D0%B0)

**Что работает не так?**

Воин дворф 17 лвл не может взять этот классовый квест у [Гранис Свист Топора <Наставник воинов>](http://db.logon3.com/?npc=1229)

**Как должно работать?**

Гранис Свист Топора должен давать [квест](http://db.logon3.com/?quest=1679) который начинает цепочку для обучения воина оборонительной стойке.

**Шаги для воспроизведения ошибки:**

1. Прийти в Громоварку 
2. Поговорить с Гранис Свист Топора 
3. Нет квеста "Марен Грозовая Вершина"

**Текущее обновление ядра:**
Build 235 2018-12-27 14:53:54 +0400
Сервер WoW Circle 3.3.5a x1 PVE

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by gmRial** [comment]
http://db.logon3.com/?quest=1679
Задание работает исправно.

**Comment by AlessandraRain** [comment]
Кэш еще раз почистила, только что проверила, не работает. Над Гранис Свист Топора нет знака квеста.

**Comment by gmRial** [comment]
Задание исправно.
Проверяйте другие квесты цепочки.

**Comment by AlessandraRain** [comment]
Проверяла. Далее квесты так же не доступны. В списке заданий их нет. Над NPC Марен Грозовая Вершина знака квеста нет так же. 
У моего друга гном воин и у него квест отображается, берется он так же у Гранис Свист Топора. То есть проблема именно у моего персонажа получается. Подскажите пожалуйста, есть ли шанс это как-то исправить? Если нужны скриншоты или ник персонажа, могу все дать.

**Comment by gmRial** [comment]
Индивидуальные проблемы персонаежей решаются в центре поддержки http://logon3.com/support
Приложите ссылку на репорт в заявку.
