### ISSUE TITLE
[Заклинание] ID 69766 - Неустойчивость

### ISSUE THREAD

**Issue by MedoOf** [VirginTeam/WotlkCore#1424]
**Ссылки и комментарии:**

http://db.logon3.com/?spell=69766 

**Что работает не так?**

[источник дебафа босс](http://www.worldoflogs.com/reports/490d2lpn8neb0t8r/xe/?s=5907&e=6300&x=spellID+%3D+69766)

**Как должно работать?**

[источник дебафа игрок](http://www.worldoflogs.com/reports/bgvjeq55ljrgws01/xe/?s=8218&e=8611&x=spellID+%3D+69766)

**Текущее обновление ядра:**

235 билд

**Comment by Rorshah** [comment]
А можно в таких репортах писать на что это влияет.
На работу аддонов или на сложность прохождения.
Или это уровень грамматической ошибки: 
ни на что не влияет, но неприятно тому кто логи читает ?

**Comment by MedoOf** [comment]
Работает
