### ISSUE TITLE
[Игровая механика] Заметки в гильдейском банке

### ISSUE THREAD

**Issue by Santaria** [VirginTeam/WotlkCore#1427]
**Что работает не так?**

1) Любая вносимая информация сохраняется автоматически, без подтверждения.
2) Любой член гильдии, с минимальным доступом к просмотру ячейки, может изменять информацию в заметках, не имея на это прав.

**Как должно работать?**

1) Информация должна сохраняться только при нажатии на кнопку "Сохранить изменения", которая доступна только при наличии прав на редактирование заметок в ГБ.
2) Редактирование заметок должно производиться только теми, у кого есть на это права.

**Текущее обновление ядра:**

Build 235

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by ForesterDev** [comment]
По поводу 1 пункта - это особенность клиента, она вносит изменения при закрытии окна. Причем для сервера нет различия, нажал ли игрок кнопку сохранить изменения либо просто закрыл окно.
По 2 пункту - будет исправлено

**Comment by ForesterDev** [comment]
А что с ними не так?

**Comment by kalipsa988** [comment]
метки рандомные не отображаются, должно было быть не Цирконовое кольцо, а Цирконовое кольцо в печатью меткости и на шмотке статы

**Comment by ForesterDev** [comment]
Нет, нельзя. В пакете клиент получает только ID предмета без указания сгенерированных модификаций

**Comment by Senatyan** [comment]
Я не могу понять из - за этого бага нет смысла ложить кольца в гб? Вроде раньше такого не было. Надо тестануть на л1

**Comment by Santaria** [comment]
Исправлено. Ошибки после обновления не обнаружено. Close.
