### ISSUE TITLE
Респаун любых квестовых итемов в открытом мире

### ISSUE THREAD

**Issue by SirDShadow** [VirginTeam/WotlkCore#1432]
**Ссылки и комментарии:**

Начиная с квеста "Вещи Соланиана" https://ru.wowhead.com/quest=37443/%D0%B2%D0%B5%D1%89%D0%B8-%D1%81%D0%BE%D0%BB%D0%B0%D0%BD%D0%B8%D0%B0%D0%BD%D0%B0 и все остальные квесты, в которых необходимо собрать что-либо, лежащее в открытом мире, или повзаимодействовать с NPC, в том числе исцеление неписей в квесте "Пленники Смертхольма" https://ru.wowhead.com/quest=9164/%D0%BF%D0%BB%D0%B5%D0%BD%D0%BD%D0%B8%D0%BA%D0%B8-%D1%81%D0%BC%D0%B5%D1%80%D1%82%D1%85%D0%BE%D0%BB%D1%8C%D0%BC%D0%B0

**Что работает не так?**

1. После сбора квестового итема или исцеления/убиения/использования NPC предмет или NPC исчезают и не появляются слишком долгое время. Играть вдвоем, не говоря уже о большей группе людей - практически не реально в виду слишком большой потери времени на сбор нужных итемов. На данный момент, для того, чтобы второй участник группы собрал этот же итем или смог повзаимодействовать с NPC нужно ждать не менее 5-ти минут.

2. Следопыт Ведоран (https://ru.wowhead.com/npc=16209/%D1%81%D0%BB%D0%B5%D0%B4%D0%BE%D0%BF%D1%8B%D1%82-%D0%B2%D0%B5%D0%B4%D0%BE%D1%80%D0%B0%D0%BD) отсутствует в принципе.

**Как должно работать?**

1. Респаун или восстановление предметов, возвращение или появление нового NPC после смерти/ухода/исчезновения предыдущего - должно происходить в течение 5-10 секунд.

2. Следопыт Ведоран должен лежать на столе внутри башни, согласно точке на wowhead.

**Шаги для воспроизведения ошибки:**

1. Получить квест "Вещи Соланиана" в начальной локации эльфов крови
2. Собрать любой из необходимых предметов
3. Дождаться повторного появления предмета

**Текущее обновление ядра:**

Build 236 2019-01-21. Live Server.

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by gmRial** [comment]
По п.1 пруфы будут?
По п.2 #568

**Comment by SirDShadow** [comment]
А какие конкретно пруфы необходимы и откуда конкретно их можно достать? На официальных серверах уже давно для каждого персонажа лежит отдельный предмет и не важно подобрал ли кто-то его перед тобой или подбирает вместе с тобой - он только твой. На вовхеде информация по респаунам никогда не давалась. Соответственно, остается только говорить, что я прекрасно помню примерные тайминги как на официальных серверах, так и на своем сервере от mangos, который админил около 10 лет назад. Но на веру, как я понимаю, такая информация воспринята быть не может.
Как вариант - могу предложить посмотреть канадский сервер ванилы и сравнить тайминги появления тех же кактусов в начальной локации орков/троллей по квесту "Кактусовый десерт Галгара" https://ru.wowhead.com/quest=25136/%D0%BA%D0%B0%D0%BA%D1%82%D1%83%D1%81%D0%BE%D0%B2%D1%8B%D0%B9-%D0%B4%D0%B5%D1%81%D0%B5%D1%80%D1%82-%D0%B3%D0%B0%D0%BB%D0%B3%D0%B0%D1%80%D0%B0 При этом в официальном WoTLK эти тайминги были сильно сокращены, но сделайте хотя бы также. Если решите использовать такой способ доказательства - готов в личку дать информацию об этом сервере.
Ну и последнее - вспомните себя, вспомните свою игру в группе (ну не социопат же каждый из вас) и любой квест, где что-то нужно подобрать. Когда и на каком сервере (не считая Virgin) вы ждали появления квест итема больше пяти минут для каждого сопартийца чтобы пойти дальше?!

**Comment by Kodekc** [comment]
Собственно всё индивидуально по каждому заданию, тайминг раньше был 600 секунд, где-то в каких-то заданиях он составляет 300, где-то 120, а где-то 10, сразу исправить все задания не представляется возможным. Точного тайминга нет, как вы и выше написали, что от куда брать доказательства, устанавливается более-менее приемлемое время ожидания, только опять таки, если это задания попало в поле зрения разработчика

**Comment by SirDShadow** [comment]
Насколько я помню из разработок движка mangos, в котором частично участвовал сам, в конфиге сервера указывалось общее значение респауна всех предметов в открытом мире, которые могут быть использованы или подобраны в любом квесте, завершить или начать квест. Не помню точно строку, но что-то вроде QuestItemSpawn там присутствовало. Правильно ли я понимаю, что в случае с данным движком игры такой параметр отсутствует и ввести его невозможно?
Если так, то что поделать, придется довольствоваться тем что есть и кушать что дают, ибо если по каждому квесту отписывать отдельный репорт - никакого времени поиграть не останется...

**Comment by gmRial** [comment]
> Насколько я помню 

https://trinitycore.atlassian.net/wiki/spaces/tc/pages/2130075/Databases

**Comment by SirDShadow** [comment]
Вот, спасибо за наводку. Это не в базы данных лезть надо, а как я и писал выше - в конфиг файл сервера :)

https://trinitycore.atlassian.net/wiki/spaces/tc/pages/2130061/Configuration

Файл worldserver.conf.dist, строка Respawn.DynamicMinimumGameObject = 10, что значит 10 секунд по умолчанию. Но работает это только при включенном динамическом респауне Respawn.DynamicMode, который зависит от количество игроков в зоне. Как-то так.

**Comment by SirDShadow** [comment]
и да, разумеется, эта настройка будет также влиять и на респаун рудных жил и травы

**Comment by Hellsingoff** [comment]
Что за бредни, честное слово.

Играл на офе во времена БК-лича, такой респаун это вполне близлайк. Введены шардинг, ускоренный респ, выделение для каждого игрока собственной копии предмета имели место, но начиная с катаклизма. Да, это удобно, несомненно. Но введение подобной практики очевидно будет НЕ близлайк и сломает баланс тех же руд.

К слову, баланс руд сломан и сейчас - мифрил и титан необычайно редки, гораздо более редкие, чем были на офе, но это другой разговор.

Короче, ввести подобный респ это равносильно введению х0.5 хп и урона мобов "ведь это ускорит прокачку". Или давайте введем х5 рейт дропов вещей и опыта. Хотя подождите-ка... Ведь такие рейты имеют место быть, хоть х100, хоть фан, где сразу дают 80 уровень и бисовый эквип.

Иными словами, вам такой респ может НЕ НРАВИТЬСЯ, но это не значит что ту что-то работает НЕ ПРАВИЛЬНО. В 90% случаев респ работает так, как должен или по крайней мере вменяемо. Исключения и баги имеются, вот на них будьте добры писать тикеты с пруфами по кд респауна. 

Жаловаться же что "респ слишком медленный, ведь на офе ещё с пандарии ввели шардинг и прочее" бесмыссленно, ведь вы пишете в багтрекер ядра вотлк, а не пандарии. В вотлк и на офе был такой респ, его изменили может разве что уже в прекатаклизм патче.

Да, там уже НАЧАЛИ баловаться введением шардинга, ускорением респауна В ЗАВИСИМОСТИ от онлайна игроков в данной зоне (то есть если игроков в зоне слишком много респ ускорялся чтобы не возникало безумных очередей), но ни о каких безумных речах в "несколько секунд респ" всё равно не идёт. 

Элементарно даже если бы перенести с офа систему "респ ускоряется при большой заселенности зоны" - что случится? На офе был онлайн под 25 тысяч единовременных на каждом сервере (я был на термоштепселе) и в стартовой зоне сразу после создания персонажа можно было собирать чуть ли не рейды (ради этого и имеется ограничение, что в рейде нельзя квестить и качаться, на офе легко можно было собрать рейд в 40 рыл только создав персонажа и сделав круг по зоне с кактусами кидая инвайты всем подряд). А тут что? Онлайн в десять раз меньше, большая часть онлайна сидит в столицах/ппг/бг. В стартовой локации дай бог собрать пати в 5 рыл. Какое тут было бы ускорение, если перенести систему офа? Никакое.

Имхо, тикет подлежал закрытию ещё при создании, как он прожил месяц я не понимаю.

**Comment by SirDShadow** [comment]
Воит ну не увидел в словах предыдущего оратора никакой объективности, кроме слов "а я вот играл". Я вот тоже играл на оффе, еще с BC. И никогда не было такой проблемы, с которой мы с женой столкнулись здесь. Ни на одном сервере, ни на оффе, ни на других пиратках, хоть их было и не много, не было такого, чтобы даже группе из двух человек приходилось тупо сидеть и ждать 20 минут для того, чтобы подобрать квестовый итем.
Замечу, так как пруфов не имеется - я не кидаюсь "какашками" как делают некоторые, а просто смирился и мы продолжаем спокойно играть :)
