### ISSUE TITLE
[Рейд] Змеиное святилище (ID 21217 - Скрытень из глубин)

### ISSUE THREAD

**Issue by Santaria** [VirginTeam/WotlkCore#1433]
**Ссылки и комментарии:**

http://db.logon3.com/?npc=21217

**Что работает не так?**

Невозможно убить босса. Он появляется и практически сразу исчезает.

**Как должно работать?**

Босс не должен пропадать.

**Шаги для воспроизведения ошибки:**

1. При помощи "Рыбной ловли" призвать босса
2. Попробовать атаковать его

**Текущее обновление ядра:**

Build 236

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by Santaria** [comment]
Актуально и после хотфиксов

**Comment by Kodekc** [comment]
Раньше работало до обновления 236?

**Comment by farbik** [comment]
его можно убить нырнув в воде
понадобится хилер так как рыбки достаточно больно бьют

**Comment by Santaria** [comment]
Исправлено.
