### ISSUE TITLE
[Задание] ID 11607 - Заблудшие души

### ISSUE THREAD

**Issue by adecvat** [VirginTeam/WotlkCore#1438]
**Ссылки и комментарии:**

Добавьте ссылки с wowhead.com или db.logon3.com на проблемные задания, NPC, заклинания и т.д. 
https://ru.wowhead.com/quest=29752/%D0%B7%D0%B0%D0%B1%D0%BB%D1%83%D0%B4%D1%88%D0%B8%D0%B5-%D0%B4%D1%83%D1%88%D0%B8
**Что работает не так?**
не защитывает при испозовании на нпс 
Фактический результат — тот, который вы наблюдаете 
не защитывает при испозовании на нпс 
**Как должно работать?**
защитывать 

Ожидаемый результат — то, чего вы ожидали при выполнении ваших действий. Процесс правильной работы

**Шаги для воспроизведения ошибки:**

1. Шаг один берём кв 
2. Шаг два используем на моба и защитывает
3. Шаг три здаём кв 

**Текущее обновление ядра:**
: Build 236 2019-01-21 13:51:11 +0400
Можно посмотреть в игре, введите в чат команду .server info и скопировать строку начиная с Build с номером и датой. Не забывайте указывать, Live Server или PTR Server, где проводилось тестирование.

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by gmRial** [comment]
Оформите шапку по шаблону, пожалуйста.

**Comment by GmAlleria** [comment]
Задание для дополнения 5.0.1.15589?
