### ISSUE TITLE
[Группа заклинаний] Дух стаи, гепарда

### ISSUE THREAD

**Issue by Napoliash** [VirginTeam/WotlkCore#144]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

ID 13159 - http://wowroad.info/?spell=13159
ID 5118 - http://wowroad.info/?spell=5118

меня забанили утверждая что я читер, ник в игре Zeferus
на видео (https://youtu.be/9pdiHpFxr3k) которое мне предоставил скорен, гейм мастер забанивший меня, я ничего не понял, где и какой чит у меня разглядели, что к чему мне все объяснил уже другой ГМ, сказав что у меня на видео скорость выше чем обычно, я начал вспоминать все свои действия в инсте, все что могло бы быть связанно со сменой скорости бега....
буквально сутки выясняя за что схлопотал бан, я попытался объяснить все свои действия гму, но выяснил уже сам на практике, когда согильдиец направил меня на тест реалм, там я создал ханта и начал перебирать действия которые предпринял в инсте, чтоб выявить баг, когда выяснил, сообщил, но мне не поверили, в итоге уговорил друга сделать данное видео (https://youtu.be/2-P0OfBq8UI), где уже ему объяснил как активировать баг чтоб в последствии записать и выложить сюда

**Что работает не так?**

дух стаи, при определенной последовательности действий, эффект остается

**Как должно работать?**

отмена духа, и в последствии эффекта увеличения скорости бега

**Шаги для воспроизведения ошибки:**

1. активация "дух стаи"
2. активация "звериный глаз"
3. ручная отмена бафа "дух стаи" у миникарты
4. ручная отмена бафа "звериный глаз"

**Текущее обновление ядра:**
Build 23 2017.04.27 15:48:25 +0400
logon3, public test realm

**Comment by Scoren** [comment]
подтвеждаю, при мне воспроизводили

**Comment by kalipsa988** [comment]
исправилось само собой, проверил только, что
