### ISSUE TITLE
[Группа предметов] Предметы-задания с рейдовых боссов

### ISSUE THREAD

**Issue by Santaria** [VirginTeam/WotlkCore#1440]
**Ссылки и комментарии:**

[ID 21220 - Голова Оссириана Неуязвимого](http://db.logon3.com/?item=21220 )
[ID 21221 - Око К'Туна](http://db.logon3.com/?item=21221 )

[ID 19802 - Сердце Хаккара](http://db.logon3.com/?item=19802 )

[ID 49643 - Голова Ониксии (80 lvl, Орда)](http://db.logon3.com/?item=49643 )
[ID 49644 - Голова Ониксии (80 lvl, Альянс)](http://db.logon3.com/?item=49644 )

[ID 18422 - Голова Ониксии (60 lvl, Орда)](http://db.logon3.com/?item=18422 )
[ID 18423 - Голова Ониксии (60 lvl, Альянс)](http://db.logon3.com/?item=18423 )

[ID 19002 - Голова Нефариана (Орда)](http://db.logon3.com/?item=19002 )
[ID 19003 - Голова Нефариана (Альянс)](http://db.logon3.com/?item=19003 )

[ID 44569 - Ключ к Радужному Средоточию](http://db.logon3.com/?item=44569 )
[ID 44577 - Ключ для доступа к героическому режиму Радужного Средоточия](http://db.logon3.com/?item=44577 )

**Что работает не так?**

Возникает ошибка при распределении лута в режиме "Ответственный за добычу". Предметы невозможно забрать из боссов и передать другим игрокам.

**Как должно работать?**

Предметы должны свободно передаваться ответственным за добычу.

Есть также похожие предметы, у которых данной ошибки нет и их можно передавать без проблем:

[ID 33102 - Кровь Зул'джина](http://db.logon3.com/?item=33102 )
[ID 32385 - Голова Магтеридона](http://db.logon3.com/?item=32385 )
[ID 32405 - Зеленеющая сфера](http://db.logon3.com/?item=32405 ) 

**Текущее обновление ядра:**

Build 237

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by MedoOf** [comment]
http://db.logon3.com/?item=46052 - проверял? просто обычно там групплут стоит и точно сказать не могу

**Comment by Santaria** [comment]
В Ульдуаре Диск и Код вроде бы без проблем передавались. Были, разве что, проблемы с видимостью, если квест у лут-мастера был уже выполнен, но это лечилось передачей прав другому игроку. Но на данный момент тоже точно сказать не смогу. К сожалению, на тестовом сервере невозможно самостоятельно это проверить, но может кому-то из гейм-мастеров будет скучно и они проверят.

**Comment by Santaria** [comment]
Не актуально
