### ISSUE TITLE
[Задание] ID 13482 - Валим отсюда!

### ISSUE THREAD

**Issue by DrOtis** [VirginTeam/WotlkCore#1458]
**Ссылки и комментарии:**

https://ru.wowhead.com/quest=13482/валим-отсюда
https://www.youtube.com/watch?v=0lbI-KotoAE

**Что работает не так?**

После принятия квеста, который предлагает NPC Отец Камарос [npc=32800], ничего не происходит.

**Как должно работать?**

После взятия квеста отец Камарос говорит: "The Light`s blessing be upon you for aiding me in me time of need, имя игрока." "I`ve had my fill of this place. Let us depart." Сказав эти фразы, он начинает движение по тропинке вниз от координат 32,64 до координат 31,57. По пути отца Камароса необходимо защищать от встречающихся на пути враждебных мобов. По завершению пути отец Камарос говорит фразу: "You must tell my brothers that I alive." Засчитывается прогресс выполнения задания. 

**Шаги для воспроизведения ошибки:**

1. Шаг один
2. Шаг два
3. Шаг три

**Текущее обновление ядра:**

Build 237 2019-01-23 11:58:59 +0400 Logon 3 WowCircle x1 PVE Virgin

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by Skellan** [comment]
build 253 2019-04-15 - не работает, ошибка со стоящим NPC актуальна. Просьба исправить
