### ISSUE TITLE
[Задание] ID 10674 - Ловля фантастического света

### ISSUE THREAD

**Issue by Santaria** [VirginTeam/WotlkCore#1467]
**Ссылки и комментарии:**

http://db.logon3.com/?quest=10674

**Что работает не так?**

1) Ловушка ставится, засасывает шарики, но прогресс задания остается неизменным 0/15.
2) Судя по БД отсутствует текст локализации. 

**Как должно работать?**

1) [Репорт на Trinity](https://github.com/TrinityCore/TrinityCore/issues/20660 )
2) Локализация:
```ruby
UPDATE `quest_template_locale` SET `RequestItemsText`='Как понимаю, после нашего разговора вы наловили световых шариков в лагере Разаана? Интересно будет посмотреть на них и понять, что на уме у духов Астрала.', `OfferRewardText`='Эй! Да подожди ты минутку!!!$B$BЭто не смешно...' WHERE `ID`=10674 AND `locale`='ruRU';
```

**Текущее обновление ядра:**

Build 239

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by limnin** [comment]
Данный квест перекрывает лично для меня одну из двух недостающих цепочек, ведущую к достижению "На пиках скал". Наряду с другими неработающими квестами в Острогорье оставляя мне единственный путь - длительный и печальный кач либо репы с Огри'ла (где только дейлики) либо репы с Консорциумом (у которого тоже забагана часть квесты в Пустоверти и репутация требуется превознесение). Огромная просьба починить!

**Comment by Santaria** [comment]
Не актуально

**Comment by Kodekc** [comment]
Локализация будет добавлена в ближайшем обновлении
