### ISSUE TITLE
[NPC] ID 23035 - Анзу

### ISSUE THREAD

**Issue by zyxellgit** [VirginTeam/WotlkCore#1471]
**Ссылки и комментарии:**

Анзу http://db.logon3.com/?npc=23035 

**Что работает не так?**
https://youtu.be/HwwLc7YrBHk Анзу у нас
нет вступительного скрипта или чо там,
нет призыва потомков анзу (аддов)
не использует http://db.logon3.com/?spell=40303 Колдовская бомба

Анзу http://db.logon3.com/?npc=23035 практически манекен
по сравнению с тем что на видео
**Как должно работать?**
https://youtu.be/U-S3wKeWUzQ

**Шаги для воспроизведения ошибки:**

**Текущее обновление ядра:**

Можно посмотреть в игре, введите в чат команду .server info и скопировать строку начиная с Build с номером и датой. Не забывайте указывать, Live Server или PTR Server, где проводилось тестирование.

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by farbik** [comment]
не использует http://db.logon3.com/?spell=40303 Колдовская бомба

кастует, не переживай, не с самого начала боя но кастует
