### ISSUE TITLE
[Задания] ID10994 - В поисках лунного камня

### ISSUE THREAD

**Issue by lisjandra** [VirginTeam/WotlkCore#1475]
**Ссылки и комментарии:**

http://db.logon3.com/?quest=10994

**Что работает не так?**

При нахождении Алтаря лунного камня, возле самого лунного камня УЖЕ стоит NPC Риззл Шустрец

https://ru.wowhead.com/npc=23002/риззл-шустрец

Для того, чтобы квест выполнился, необходимо юзнуть на лунный камень, только потом по сюжету должен появиться этот NPC Риззл Шустрец, стукнуть нас по голове - застанить, выиграв, тем самым, себе время, и кинуться в бега. Мы же его догоняем, убиваем и забираем квестовый итем "Лунный камень из реки Строптивая", необходимый для данного задания. Но так как этот нпс уже стоит возле камня, и стоит он вполне дружественный, зеленого цвета, то... ничего не происходит. Следовательно, убить его нельзя, квестовый итем забрать нельзя, а значит, завершить цепочку кв и получить ворона тоже низя т_т

**Шаги для воспроизведения ошибки:**

1. Найти по заданию NPC Риззл Шустрец
2. Запустить диалог
3. Убедиться в неработоспособности задания

**Текущее обновление ядра:**  Build 240 2019-02-02 11:03:31 +0400

Можно посмотреть в игре, введите в чат команду .server info и скопировать строку начиная с Build с номером и датой. Не забывайте указывать, Live Server или PTR Server, где проводилось тестирование.

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by ruafelianna** [comment]
![default](https://user-images.githubusercontent.com/7500796/52315826-aaaadb00-29c9-11e9-98fb-d03e83e6294e.png)
