### ISSUE TITLE
[Игровая механика] Забаганные цепочки по заданиям Оракулов/Волчеров

### ISSUE THREAD

**Issue by gmRial** [VirginTeam/WotlkCore#1477]
**Ссылки и комментарии:**

https://ru.wowhead.com/quest=12528 - старт цепочки
https://ru.wowhead.com/faction=1104 - волчеры
https://ru.wowhead.com/faction=1105 - оракулы
https://ru.wowhead.com/quest=12581 - бремя героя

**Что работает не так?**

Ранее можно было менять репутацию между фракциями, т.к. были доступны задания https://ru.wowhead.com/quest=12692, https://ru.wowhead.com/quest=12689, https://ru.wowhead.com/quest=12582, https://ru.wowhead.com/quest=12695 без выполнения задания
https://ru.wowhead.com/quest=12581
После исправления всей цепочки, при попытке смены фракции, игроки столкнулись с проблемой невозможности этого действия, по причине невыполнения основной цепочки заданий. Без помощи игровых мастеров дальнейший прогресс становится невозможен.
По причине огромной вариативности выполнения заданий цепочки, и существенного времени обработки запроса, есть вариант по сбросу прогресса по заданиям и репутации у всех игроков.
Исключением можно задать тех, кто выполнил достижение https://ru.wowhead.com/achievement=952

**Текущее обновление ядра:**

Build 240

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by GmAlleria** [comment]
http://db.logon3.com/?quest=12654 (необязательный)

**_Следопыт Гекгек дает задание:_** 
http://db.logon3.com/?quest=12528

**_Шаман Ракжак_**
http://db.logon3.com/?quest=12529

**_Гекгек охотник на горилл_**
http://db.logon3.com/?quest=12530
http://db.logon3.com/?quest=12533
http://db.logon3.com/?quest=12534
http://db.logon3.com/?quest=12532
http://db.logon3.com/?quest=12531

**_Шаман Ракжак_**
http://db.logon3.com/?quest=12535
http://db.logon3.com/?quest=12536

**_Гекгек охотник на горилл_**
http://db.logon3.com/?quest=12537
http://db.logon3.com/?quest=12538
http://db.logon3.com/?quest=12539
http://db.logon3.com/?quest=12540

**_Оракулы_**

http://db.logon3.com/?quest=12570
http://db.logon3.com/?quest=12571

**_Лафу_**

http://db.logon3.com/?quest=12572
http://db.logon3.com/?quest=12573
http://db.logon3.com/?quest=12574
http://db.logon3.com/?quest=12575
http://db.logon3.com/?quest=12576
http://db.logon3.com/?quest=12577
http://db.logon3.com/?quest=12578
http://db.logon3.com/?quest=12580
http://db.logon3.com/?quest=12579
http://db.logon3.com/?quest=12581

**Comment by MedoOf** [comment]
По причине огромной вариативности выполнения заданий цепочки, и существенного времени обработки запроса, есть вариант по сбросу прогресса по заданиям и репутации у всех игроков.
Исключением можно задать тех, кто выполнил достижение https://ru.wowhead.com/achievement=952

А ничего что может быть кто-то фармит дракона из яйца и просто не делает обе фракции? Или риалу тупо похуй как обычно. Сброс репы приведет к хейту и сгоревшим жопам игроков

**Comment by gmRial** [comment]
Предлагайте идеи, пока это не применено.

> По причине огромной вариативности выполнения заданий цепочки, и существенного времени обработки запроса, есть вариант по сбросу прогресса по заданиям и репутации у всех игроков.
> Исключением можно задать тех, кто выполнил достижение https://ru.wowhead.com/achievement=952
> 
> А ничего что может быть кто-то фармит дракона из яйца и просто не делает обе фракции? Или риалу тупо похуй как обычно. Сброс репы приведет к хейту и сгоревшим жопам игроков

Мы открыты для идей, поэтому этот репорт публичный, предлагайте.

**Comment by Hellsingoff** [comment]
Я сам набил вот репу для оракулов и сейчас чисто "фармлю протодракона", а потому сброс прогресса - боль, однако, вполне себе не против данного действия, если это точно "всё починит".

Если это временные костыли и сбросив мы получим временную заплатку, после чего всё "снова забагуется" - каков смысл? Пока я бил репутацию оракулов я вот принципиально не делал квест на блестяшки. Почему? Потому что однажды я делал его полтора часа и поймал только одну блестяшку, из остальных сыпались только тараканы и изредка зайцы. 

Квест был долгое время сломан и сейчас он то ли снова сломался, то ли не особо хорошо починился в принципе.

**Comment by Kodekc** [comment]
Выполнен общий сброс прогресса по всем заданиям

**Comment by MiceRus** [comment]
> Выполнен общий сброс прогресса по всем заданиям

И что это означает? Репу и достижения заново качать?

**Comment by Kodekc** [comment]
Репутацию необходимо прокачивать заново
