### ISSUE TITLE
[Заклинание] ID 26090 - Зуботычина

### ISSUE THREAD

**Issue by kalipsa988** [VirginTeam/WotlkCore#1478]
**Ссылки и комментарии:**

http://db.logon3.com/?spell=26090

**Что работает не так?**

Не работает стан, урон, прерывание каста(скорее всего)
По маникену идут только мисы, спел даже не отображается в журнале боя, если только мисы

**Как должно работать?**

Должен работать в соответствии с описанием спела

Наносит противнику урон и прерывает произнесимое им заклинание. Противник не сможет произносить заклинания той же школы в течение 2 сек..
--

**Шаги для воспроизведения ошибки:**

1. Приручить гориллу
2. Бить спелом 
3. 

**Текущее обновление ядра:**

06.02.19

**Comment by ForesterDev** [comment]
Все работает, просто манекену нечего прерывать, в логе тоже такие вещи не отображаются. На деле вот что:

![image](https://user-images.githubusercontent.com/11771800/52953403-d0a88600-33a0-11e9-83c7-20496399ab02.png)

Стана у этого заклинания нет. А про урон - нужно больше информации, сколько и какой спел должен наносить. У основного спела информации об уроне нет http://db.logon3.com/?spell=26090

**Comment by Santaria** [comment]
Это заклинание и не должно наносить урон. Кривая локализация, как и у аналогичной способности воина...

**Comment by kalipsa988** [comment]
Позже проверю 2х секундное кд после сбития каста. Про стан опечатка. Урона не должно наносить

**Comment by kalipsa988** [comment]
всё работает. закрыл
