### ISSUE TITLE
Конец вражеской пропаганде

### ISSUE THREAD

**Issue by Talikar** [VirginTeam/WotlkCore#1481]
**Ссылки и комментарии:**
https://ru.wowhead.com/quest=27213/конец-вражеской-пропаганде

**Что работает не так?**
Знаю что эта тема раньше уже поднималась но проблема осталась (в добавок из-за неисправности КВ заблокирована дальнейшая цепочка квестов). 
Невозможно арестовать НИПа Гавис Серый Щит так как он союзный (должен быть вражеским).

**Как должно работать?**
НИП Гавис Серый Щит должен быть вражеским и вступить с вами в бой после чего арест будет засчитан.

**Шаги для воспроизведения ошибки:**

1. Получить КВ у https://ru.wowhead.com/npc=23566/калия-гастингс
2. Прийти на место где стоит НИП Гавис Серый Щит
3. Увидеть что НИП союзный и не вступает в бой

**Текущее обновление ядра:**
Build 240 2019-02-02 11:03:31 +0400

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by Kodekc** [comment]
хм, я ранее исправлял эту проблему - https://github.com/VirginTeam/WotlkCore/issues/701

**Comment by Kodekc** [comment]
Нашёл проблему

**Comment by Kodekc** [comment]
https://github.com/VirginTeam/WotlkCore/issues/701
