### ISSUE TITLE
[Игровая механика] Баг лута при убийстве нпц питомцем

### ISSUE THREAD

**Issue by Rorshah** [VirginTeam/WotlkCore#1482]
**Что работает не так?**

Если питомец охотника самостоятельно убил моба, то охотнику лут не доступен.
В этом случае лут считается ничьим.

**Как должно работать?**

Ожидаемый результат: ну натравил я пета на одного, сам стреляю по второму,
лут-то с обоих должен собрать. Мы же типа в группе с петом :)

**Шаги для воспроизведения ошибки:**

1. Охотник + пет
2. Натравить пета на кабанчиков под огри. самому стоять смотреть.
3. после того как пет убьет моба подойти и убедиться что лут
не дается. Можно подумать что он пустой, но кожа тоже не снимается.
Значит в нем чета есть.

**Текущее обновление ядра:**

Build 240

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by kalipsa988** [comment]
https://github.com/VirginTeam/WotlkCore/issues/1036

**Comment by Rorshah** [comment]
надо удалить тот репорт и оставить этот.
Квест-итем - это полбеды. Проблема гораздо ширше.

**Comment by gmRial** [comment]
Сталкивался с таким багом у варлока.

**Comment by ForesterDev** [comment]
https://wow.gamepedia.com/Hunter_pet

> Note: the Hunter will not gain loot or experience from a mob that the pet kills solo. This is a deliberate decision by Blizzard, not a bug. If you intend on pulling mutiple mobs and having your pet kill one or more of them while you focus on others, it would be best to try to get at least one shot or hit on each of the mobs and then allow your pet to do its work on them

Не баг, а близзлайк

**Comment by Hellsingoff** [comment]
На офе во времена бк-лича играл именно охотником. Подтверждаю, отлично это помню. Такая механика - близлайк. Я стрелял в моба укусом, травил на него пета, после чего переключался на второго моба. Только так можно получить награду за обоих. Хотя бы белой атакой надо нанести урон тому, кого убивает пет.
