### ISSUE TITLE
[Задания] ID 10742, 10806 - Решающее сражение

### ISSUE THREAD

**Issue by Santaria** [VirginTeam/WotlkCore#1483]
**Ссылки и комментарии:**

http://db.logon3.com/?quest=10742
http://db.logon3.com/?quest=10806

**Что работает не так?**

Отсутствуют часть скриптов в обоих заданиях.

**Как должно работать?**

https://github.com/TrinityCore/TrinityCore/issues/18604

**Текущее обновление ядра:**

Build 240

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by Kodekc** [comment]
Портированы скрипты с Trinity. Протестировано, работает. Изменения будут применены в ближайшем обновлении
