### ISSUE TITLE
[Задание] ID 10506 - Тяжелая ситуация

### ISSUE THREAD

**Issue by Santaria** [VirginTeam/WotlkCore#1485]
**Ссылки и комментарии:**

http://db.logon3.com/?quest=10506

**Что работает не так?**

Засчитывает задание как после использования порошка, так и при обычном убийстве волков.

**Как должно работать?**

Должно засчитывать только при использовании порошка. Вероятно не удалена старая часть скриптов.

**Текущее обновление ядра:**

Build 240

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by Kodekc** [comment]
Будет исправлено в ближайшем обновлении
