### ISSUE TITLE
[SPELL] ID 62078 - Размах (кошка)

### ISSUE THREAD

**Issue by FilDru** [VirginTeam/WotlkCore#1488]
Плохо машет кот, в то время как медведь машет просто прекрасно.

**Ссылки и комментарии:**

http://db.logon3.com/?spell=62078#sounds 
Размах курильщика.

http://db.logon3.com/?spell=48562
https://ru.wowhead.com/spell=106785/%D1%80%D0%B0%D0%B7%D0%BC%D0%B0%D1%85
Размах здорового друида.

**Что работает не так?**

Кот машет только перед собой, да еще всего на 5 метров.

**Как должно работать?**

Кот машет вокруг себя, со всех сторон на 360 градусов, и аж на целых 8 метров.

**Шаги для воспроизведения ошибки:**

1. Создать друида
2. Прокачать кота
3. Бить в Оргиммаре манекены.

**Текущее обновление ядра:**

Build 240 2019-02-02 11:03:31 +0400. Live Server

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
#

**Comment by Santaria** [comment]
А пруфы-то будут какие-нибудь? На wowhead, так к слову, уже давно не 3.3.5
Я вот открываю странички из архива gamepedia и wowwiki и вижу там:

>Hits all targets considered to be in front of the druid and within melee range.
>5 yd range

https://wow.gamepedia.com/index.php?title=Swipe_(Cat_Form)&oldid=2518883
https://wowwiki.fandom.com/wiki/Swipe_(Cat)?oldid=2185134

Размах медведя по факту вообще отдельная способность, со своими особенностями.
>Patch 3.1.0 (2009-04-14): The  [Bear Form] and  [Dire Bear Form] version of this ability no longer has a targeting requirement and hits targets behind the druid and to the sides.

Вот только к размаху кота это никакого отношения не имеет. 
Все работает правильно сейчас.
