### ISSUE TITLE
[Предмет] ID 42408 - Символ слова силы: Щит

### ISSUE THREAD

**Issue by Gooldark** [VirginTeam/WotlkCore#149]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Данный репорт приобретет особую важность если фиксанут https://github.com/VirginTeam/VirginCore/issues/148

ID 42408 - Символ слова силы: Щит
Заклинание "Слово силы: Щит" также восстанавливает цели количество здоровья, равное 20% поглощенного урона.

**Что работает не так?**

ID 42408 - Символ слова силы: Щит берет в расчет фактическое количество абсорба ID 48066 - Слово силы: Щит.

**Как должно работать?**

ID 42408 - Символ слова силы: Щит должен рассчитываться отдельно от щита. То есть у этого предмета своя формула скалирования:
( 2230 * 1,15 * 1,05 + спд * ( 0,807 + 0,4 ) * ( 1,15 + 0,05 )) * 0,2 = х
где 1,15 - ID 14769 - Улучшенное слово силы: Щит; 1,05(он же 0,05) - ID 52803 - Двоевластие; 0,4 - ID 52800 - Лишнее время.
Затем этот хил усиливается модификаторами исходящего исцеления приста, такие как 1,04 - ID 33190 - Средоточие силы; 1,3 - баф цлк(ID 73828 - Сила Ринна, или аналогичный для орды)
То есть
х * 1,04 * 1,3 = y
Затем на этот хил влияют модификаторы входящего исцеления цели, такие как ID 63650 - Божественность или ID 65139 - Древо Жизни:
y * 1,05 * 1,06

Сложно сказать какой модификатор так влияет на символ(увеличивает мультипликативно базовую часть и аддитивно влияние спд)  ID 52803 - Двоевластие или 0,05 - ID 70798 - Item - Priest T10 Healer 4P Bonus. Склоняюсь к ID 52803 - Двоевластие, так как скорее всего близарды прописали воздействие на символ только талантов, поскольку невидимый модификатор вне арен этот глиф не учитывает. Более подробно здесь - https://github.com/VirginTeam/VirginCore/issues/148.

**Доказательства**

http://wowwiki.wikia.com/wiki/Power_Word:_Shield?oldid=2412012

> Glyph of Power Word: Shield does not take into account the bonus from Improved Power Word: Shield when calculating the healing amount

> The amount healed by Glyph of Power Word: Shield is increased by any talents or effects the target has that increase healing done. For example, if the effect is used on a Restoration Shaman, the heal will be increased by 10% because of Purification. This bug created the commonly held misconception that Focused Power applies twice to Glyph of Power Word: Shield. When a priest tests the effect on herself, Focused Power does apply twice; once correctly and once because of this bug. On any other target the caster's Focused Power will apply only once.

Итак проверим 2 пункт
У паладина Mackasang вкачан талант ID 63650 - Божественность. Более подробно в доказательствах здесь - https://github.com/VirginTeam/VirginCore/issues/147.

http://www.worldoflogs.com/reports/s7qkr5l7nwaqmdx5/xe/?s=8068&e=8428&x=targetName+%3D+"Mackasang"%0D%0A&page=1

> [21:24:08.525] Nashal Glyph of Power Word: Shield Mackasang +2075
[21:24:09.639] Halion hits Mackasang 1156 (A: 12695)

12695 * 0,2 = 2539
2075 / 1,04 / 1,06 / 1,05 = 1792,6256
1,04 - ID 33190 - Средоточие силы; 1,06 - ID 65139 - Древо Жизни; 1,05 - ID 63650 - Божественность.
2539 / 1792,6256 = 1,416358

http://worldoflogs.com/reports/ul76xm556v85ir2v/xe/?x=targetName+%3D+"Spacealien"%0D%0AAND+type+%3D+TYPE_AURA%0D%0AOR+targetName+%3D+"Spacealien"%0D%0AAND+type+%3D+TYPE_DAMAGE%0D%0AOR+targetName+%3D+"Spacealien"%0D%0AAND+type+%3D+TYPE_MISS%0D%0AOR+targetName+%3D+"Spacealien"%0D%0AAND+spell+%3D+"Power+Word%3A+Shield"%0D%0AOR+targetName+%3D+"Spacealien"%0D%0AAND+spell+%3D+"Divine+Aegis"%0D%0AOR+targetName+%3D+"Spacealien"%0D%0AAND+spell+%3D+"Glyph+of+Power+Word%3A+Shield"%0D%0A&page=20

> [22:30:39.275] Caliste Glyph of Power Word: Shield Spacealien +2617
[22:30:39.289] Blood-Queen Lana'thel Shroud of Sorrow Spacealien Absorb (3929)
[22:30:41.301] Blood-Queen Lana'thel Shroud of Sorrow Spacealien Absorb (3055)
[22:30:43.345] Blood-Queen Lana'thel Shroud of Sorrow Spacealien Absorb (3929)
[22:30:45.326] Blood-Queen Lana'thel Shroud of Sorrow Spacealien 1182 (A: 2026, R: 1418)

3929 + 3055 + 3929 + 2026 = 12939
2617 / 1,3 / 1,04 / 1,06 = 1826,0857
где 1,3 - ID 73828 - Сила Ринна, 1,04 - ID 33190 - Средоточие силы; 1,06 - ID 65139 - Древо Жизни.
( 12939 * 0,2 ) / 1826,0857 = 1,417129 почти равно 1,416358

Если бы, согласно пункту 2, модификаторы исходящего исцеления цели влияли на хил, то ID 16213 - Чистота усилил бы хил на 10%, однако это не наблюдается.
То есть пункт 2 с вики не верен. Глиф учитывает только модификаторы исходящего исцеления приста, и модификаторы входящего исцеления цели.

Чтобы доказать что формула глифа равна
( 2230 * 1,15 * 1,05 + спд * ( 0,807 + 0,4 ) * ( 1,15 + 0,05 )) * 0,2
Можно рассчитать спд приста из формулы щита, а затем подставить в формулу выше, цыфры совпадают во всех случаях что я проверял, если необходимо могу написать пару расчетов, в принципе это может сделать каждый.
Формула щита - ( 2230 + спд * ( 0,807 + 0,4 )) * ( 1,15 + 0,05 ) * 1,05 * 1,04 * 1,3

**Текущее обновление ядра:**

29.04.2017. 155 билд

**Перенесено**

http://forum.wowcircle.com/showthread.php?t=631081

**Comment by Kodekc** [comment]
Выведен из этапа разработке по причине сложности реализации скриптов, требующих переписать большую часть действующих скриптов
