### ISSUE TITLE
[Существа] ID 4388 - Молодой черный крепкозуб

### ISSUE THREAD

**Issue by kalambyr18** [VirginTeam/WotlkCore#1492]
**Ссылки и комментарии:**

https://ru.wowhead.com/quest=27217/%D0%B6%D0%B8%D1%80-%D0%BA%D1%80%D0%B5%D0%BF%D0%BA%D0%BE%D0%B7%D1%83%D0%B1%D0%B0

**Что работает не так?**

3 моба на локации 

**Как должно работать?**

Просьба добавить мобов . 4 айтема нужно по кв. 3 моба . Дроп не 100%. 

**Шаги для воспроизведения ошибки:**

1, Взять кв

**Текущее обновление ядра:**

241

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by Kodekc** [comment]
Молодой черный крепкозуб
* Перезаселены. Было = 23 Стало = 48
