### ISSUE TITLE
[Задание] ID 27213 - Конец вражеской пропаганде

### ISSUE THREAD

**Issue by kalambyr18** [VirginTeam/WotlkCore#1493]
**Ссылки и комментарии:**

https://ru.wowhead.com/quest=27213/%D0%BA%D0%BE%D0%BD%D0%B5%D1%86-%D0%B2%D1%80%D0%B0%D0%B6%D0%B5%D1%81%D0%BA%D0%BE%D0%B9-%D0%BF%D1%80%D0%BE%D0%BF%D0%B0%D0%B3%D0%B0%D0%BD%D0%B4%D0%B5

**Что работает не так?**

Нпс , котор нужно победить дружелюбен .

**Как должно работать?**

Должен снять ему хп до минимума и только после он должен тстаь дружелюбен . я не могу его бить изначально.

**Шаги для воспроизведения ошибки:**

1. Взять кв

**Текущее обновление ядра:**

241

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by Kodekc** [comment]
https://github.com/VirginTeam/WotlkCore/issues/701
