### ISSUE TITLE
[Задание] ID 1270 - Побег Вонючки

### ISSUE THREAD

**Issue by kalambyr18** [VirginTeam/WotlkCore#1494]
**Ссылки и комментарии:**

https://ru.wowhead.com/quest=1270/%D0%BF%D0%BE%D0%B1%D0%B5%D0%B3-%D0%B2%D0%BE%D0%BD%D1%8E%D1%87%D0%BA%D0%B8

**Что работает не так?**

Нпс не дает кв .

**Как должно работать?**

Должен давать кв 

**Шаги для воспроизведения ошибки:**

1. Подбежать к нпс 

**Текущее обновление ядра:**

241

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by Kodekc** [comment]
Не воспроизводится. NPC даёт задание без проблем
