### ISSUE TITLE
[Локализация] Задания у Капитан Ниалс ID 2700

### ISSUE THREAD

**Issue by GmAlleria** [VirginTeam/WotlkCore#1495]
**Ссылки и комментарии:**

http://db.logon3.com/?npc=2700

**Что работает не так?**
Отсутствуют диалоги при завершении заданий: 
Разыскивается: Марез Клобук
Разыскивается: Отто и лорд Соколиный Шлем

**Как должно работать?**

Ожидаемый результат — то, чего вы ожидали при выполнении ваших действий. Процесс правильной работы

**Шаги для воспроизведения ошибки:**

1. Шаг один
2. Шаг два
3. Шаг три

**Текущее обновление ядра:**

Build 241 2019-02-08 16:15:10 +0400

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by lebalex77** [comment]
Помимо отсутствия диалога при завершении задания "Разыскивается: Марез Клобук" у персонажа Капитан Ниалс нет также диалога при сдаче задания "Просьба о помощи"
