### ISSUE TITLE
[Поле боя] отображение флага (ВСГ)

### ISSUE THREAD

**Issue by kalipsa988** [VirginTeam/WotlkCore#1496]
**Ссылки и комментарии:**

Визуальный баг

**Что работает не так?**

Если поднимают флаг и ты заходишь на бг др фракции после начала бг, то флаги не правильно отображаются

**Как должно работать?**

Должен отображаться флаг той фракции, чей флаг подняли

**Шаги для воспроизведения ошибки:**

1. поднять флаг (альянса например)
2. зайти на бг (альянсом)
3. увидеть, что несут флаг орды
![wowscrnshot_021819_104858](https://user-images.githubusercontent.com/29568428/52938886-ddfb4b80-3373-11e9-9d9b-f2eef70d4739.jpg)

**Текущее обновление ядра:**

16.02.19

**Comment by ForesterDev** [comment]
Не воспроизводится, Вторым окном зашел после начала бг, ворлдстейты одинаковые
![default](https://user-images.githubusercontent.com/11771800/52934204-282dfe00-336f-11e9-9528-fa9bc0017304.png)

**Comment by kalipsa988** [comment]
Не постоянный, если увижу, скину

**Comment by kalipsa988** [comment]
ошибся в описании бага
Если поднимают флаг и ты заходишь на бг др фракции после начала бг, то флаги не правильно отображаются 
![wowscrnshot_021819_104858](https://user-images.githubusercontent.com/29568428/52935809-76410280-336b-11e9-8237-c062072e076e.jpg)
![Uploading WoWScrnShot_021819_104911.jpg…]()

**Comment by ForesterDev** [comment]
Отредактируйте информацию в репорте согласно актуальной информации

**Comment by Hellsingoff** [comment]
Ещё вот что - на альтераке (и, вроде, ОЗ) шахты отображаются неправильно (вражескими) если зайти в середину боя. Играл пол года-год назад и такого не случалось, сейчас же через раз вижу. Никто не сталкивался? Если сталкивались надо новый репорт открыть уже на шахты

**Comment by Kodekc** [comment]
Должно быть исправлено после обновления, необходимо перепроверить
