### ISSUE TITLE
[Подземелье] Пик Черной Горы (ID 9816 Пиростраж Углевзор)

### ISSUE THREAD

**Issue by gmOverfire** [VirginTeam/WotlkCore#15]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Скриншоты демонстрирующие проблему, выделение проблемных мест с помощью графических редакторов приветствуются. Для описания ошибок, возникающих только в движении, снимите видео **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Миниивент у босса http://ru.wowhead.com/npc=9816
Тюремщик легиона Чернорука http://ru.wowhead.com/npc=10316

**Что работает не так?**

При входе в Зал оков, двери выхода из зала уже открыты, а NPC 10316 просто стоят, при входе игрока в аггрорадиус - нападают на него. Так же, почему-то один из этих NPC ходит в предыдущем зале, Зале Драконов и при этом неактивен, т.е. не может быть атакован игроком. При атаке одного из NPC все остальные прибегают атаковать игрока, включая того NPC бродящего в Зале Драконов. 

**Как должно работать?**

При входе в зал, двери выхода должны быть закрыты, а NPC Тюремщик легиона Чернорука должны поддерживать некое заклинание на боссе, при этом ни самих NPC , ни босса нельзя атаковать. При использовании Алтаря Черной Горы через некоторое время NPC , поддерживающие заклинание, становятся активны и нападают на игрока. После убийства NPC босс постепенно увеличивается и начинает атаковать игрока.
https://youtu.be/asKYQoMPbks?t=1m42s

**Текущее обновление ядра:**

PTR Build 20 2017-04-03 15:25:08 +0400

**Comment by Luchass** [comment]
Проверьте еще раз. Уже должно работать

**Comment by ForesterDev** [comment]
Исправлены остальные проблемы. Будет применено в обновлении
