### ISSUE TITLE
[Заклинание] ID 18275 - Власть над Тенями

### ISSUE THREAD

**Issue by Gooldark** [VirginTeam/WotlkCore#150]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

ID 18275 - Власть над Тенями
Увеличивает количество здоровья, похищаемое вашими заклинаниями темной магии, а также урон, наносимый вашими заклинаниями темной магии и способностью "Укус Тьмы" вашего охотника Скверны, на 15%.

**Что работает не так?**

ID 18275 - Власть над Тенями усиливает количество вытягиваемого здоровья спелов ID 689 - Похищение жизни; ID 47860 - Лик смерти.

**Как должно работать?**

ID 18275 - Власть над Тенями не должно усиливать количество вытягиваемого здоровья спелов ID 689 - Похищение жизни; ID 47860 - Лик смерти. Этот талант увеличивает урон спелов, а эти спелы хилят в зависимости от нанесенного урона цели, поэтому увеличение отхила уже учтено.

**Доказательства**

http://www.warcraftmovies.com/movieview.php?id=148991 - 07:44 - на локе висит боп, лок кидает койл, наносит 1241 урона и отхиливается на 4690. 1241*3*1,26=4690 где 1,26 доспех лока. 09:19 - видны равные цифры урона и отхила от Похищение жизни - 486, 405, 445.

http://www.warcraftmovies.com/movieview.php?id=149541 - 2:19 - лок наносит вару похищеним жизни рвно столько же сколько оно хилит - 807, 807, 322, 323, 323.

**Текущее обновление ядра:**

29.04.2017. 155 билд

**Comment by gmRial** [comment]
Исправлено, после обновления.
