### ISSUE TITLE
[Заклинание] ID 31223 - Мастер скрытности

### ISSUE THREAD

**Issue by Sangue09** [VirginTeam/WotlkCore#1500]
**Ссылки и комментарии:**

http://db.logon3.com/?spell=31223

**Что работает не так?**

Периодически пропадает баф и бонус к 10% урону при входе или выходе из незаметности до истечения 6 секунд. Чаще всего возникает баг, когда слишком много бафов на разбойнике.

**Как должно работать?**
Баф и бонус от таланта должен висеть 6 секунд и не пропадать раньше времени.

**Шаги для воспроизведения ошибки:**

1. Зайти и выйти из незаметности, при нескольких повторов этих действий, талант перестанет работать.

**Текущее обновление ядра:**

Build 242 (18.02.2019)

**Comment by kalipsa988** [comment]
проблема в том, что после выхода из стелса продолжает висеть http://db.logon3.com/?spell=31223 в течении 5 секунд
должно быть так
http://db.logon3.com/?spell=31223 это должно висеть в стелсе, при выходе из него должно быть обновление http://db.logon3.com/?spell=31223 и замена на http://db.logon3.com/?spell=31666, которая висит 6 секунд
проще говоря http://db.logon3.com/?spell=31666 отсутствует

**Comment by kalipsa988** [comment]
![wowscrnshot_022119_192422](https://user-images.githubusercontent.com/29568428/53185488-2a62b780-3610-11e9-85c3-fafdd0cca722.jpg)
как пруфы слов выше, висит вне стелса http://db.logon3.com/?spell=31665 (без таймера), а не http://db.logon3.com/?spell=31666

**Comment by Kodekc** [comment]
spell_rogue.cpp#L457
