### ISSUE TITLE
[Задание] ID 9740 - Солнечные Ворота

### ISSUE THREAD

**Issue by daskolkomozno** [VirginTeam/WotlkCore#1502]
**Ссылки и комментарии:**
https://ru.wowhead.com/quest=9740/%D1%81%D0%BE%D0%BB%D0%BD%D0%B5%D1%87%D0%BD%D1%8B%D0%B5-%D0%B2%D0%BE%D1%80%D0%BE%D1%82%D0%B0#comments

**Что работает не так?**
Не возможно взаимодействовать с солнечными воротами, при на ведении курсора на ворота не появляется колесико взаимодействия. Из одного из кристаллов на берегу не падает красный луч
Фактический результат — тот, который вы наблюдаете 
невозможно уничтожить солнечные ворота
**Как должно работать?**
https://www.youtube.com/watch?v=TSAiZtzHfxY&feature=youtu.be    вот так должно работать
Ожидаемый результат — то, чего вы ожидали при выполнении ваших действий. Процесс правильной работы
Ожидал что все будет работать. 
**Шаги для воспроизведения ошибки:**

1. взять квест
2. попытаться его сделать
3. радоваться если сделал квест

**Текущее обновление ядра:**
![2019-02-23 23 23 28](https://user-images.githubusercontent.com/47899779/53291914-54a8a680-37c3-11e9-8f95-0ea6b409ca86.png)
Не могу информацию о ядре скопировать из чата((ввел команду в строку чата, появилась информация но ее невозможно скопировать или выделить((( можете посмотреть на скриншоте
Можно посмотреть в игре, введите в чат команду  .server info и скопировать строку начиная с Build с номером и датой. Не забывайте указывать, Live Server или PTR Server, где проводилось тестирование.

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by daskolkomozno** [comment]
какое еще формление?...у меня создается впечатление что служба поддержки создана для издевательста...что в моем сообщении не понятного? и что надо оформить чтоб стало еще понятнее?...

**Comment by GmAlleria** [comment]
**Шаги для воспроизведения ошибки:**

**_1. Шаг один это чтоб нормально работала служба внутри игровой поддержки
2. Шаг два ссылка в сообщении на этот ресурс от службы внутриигровой поддержки не кликабельна и ее нельзя скопировать чтоб вставить в браузер
3. Шаг три_**

Не находите что к заданию отношения не имеет? 
Посмотрите на другие репорты, если не понятно.
Текущее обновление ядра: - не указали

**Comment by daskolkomozno** [comment]
я просто казуал...получаю удовольствие от вашего продукта но в процессе выясняю что в вашем продукте есть поломка! не баг а поломка! пишу в службу внутриигровой поддержки но там мне говорят что нужно написать на баг треккер дают ссылку длиной в километр! на которую нельзя кликнуть и которую нельзя скопировать! согласитесь уже ничего общего с получнием удовольствия от игры....пришлось карандашом (КАРАНДАШОМ КАРЛ! в 21м веке) переписывать https://github.com/VirginTeam/WotlkCore/issue на бумажку ,а потом вручную вводить в адресную строку браузера. и что я увидел? англоязычный рессурс на котором без регистрации ничего не могу написать.ладно открываю гугл переводчик чтоб как минимум узнать что такое issue...регистрируюсь! оставляю описание поломки (со второго раза) и ради чего? чтоб кто-то сделал свою работу? и что дальше? ГМ с темже ником что и отвечал мне в игре пишет что я неправльно оформил заявку (ТОТ ЖЕ ГМ КАРЛ!!) сообщения  о поломке в игре было мало? или как? я обещаю стрим на ютюбе с попыткой написать в службу внутриигровой поддержки, переходом по ссылке и регистрацией на вашем багтреккере! ничего общего со словами удобство пользователя это не имеет!

**Comment by d3rkt8mple** [comment]
> 
> 
> я просто казуал...получаю удовольствие от вашего продукта но в процессе выясняю что в вашем продукте есть поломка! не баг а поломка! пишу в службу внутриигровой поддержки но там мне говорят что нужно написать на баг треккер дают ссылку длиной в километр! на которую нельзя кликнуть и которую нельзя скопировать! согласитесь уже ничего общего с получнием удовольствия от игры....пришлось карандашом (КАРАНДАШОМ КАРЛ! в 21м веке) переписывать https://github.com/VirginTeam/WotlkCore/issue на бумажку ,а потом вручную вводить в адресную строку браузера. и что я увидел? англоязычный рессурс на котором без регистрации ничего не могу написать.ладно открываю гугл переводчик чтоб как минимум узнать что такое issue...регистрируюсь! оставляю описание поломки (со второго раза) и ради чего? чтоб кто-то сделал свою работу? и что дальше? ГМ с темже ником что и отвечал мне в игре пишет что я неправльно оформил заявку (ТОТ ЖЕ ГМ КАРЛ!!) сообщения о поломке в игре было мало? или как? я обещаю стрим на ютюбе с попыткой написать в службу внутриигровой поддержки, переходом по ссылке и регистрацией на вашем багтреккере! ничего общего со словами удобство пользователя это не имеет!

https://github.com/VirginTeam/WotlkCore/blob/master/README.md

**Comment by daskolkomozno** [comment]
![2019-02-23 23 23 28](https://user-images.githubusercontent.com/47899779/53291840-fd0a3b00-37c2-11e9-867d-dd4f66fd2114.png)
вот версия ядра...я его не могу скопировать из чата так как вы пишете!...

**Comment by gmRial** [comment]
> вот версия ядра...я его не могу скопировать из чата так как написано в инструкции!

Скачайте аддон Prat или Chatter, и сможете копировать из чата текст, а так же ссылки.

**Comment by daskolkomozno** [comment]
> > вот версия ядра...я его не могу скопировать из чата так как написано в инструкции!
> 
> Скачайте аддон Prat или Chatter, и сможете копировать из чата текст, а так же ссылки.

В вашей инструкции об этом не сказано ни слова((

**Comment by gmRial** [comment]
Потому что инструкция о том как создать репорт, а не как копировать текст из чата игры.
Банально можно руками написать Build xxx и этого будет достаточно.

**Comment by daskolkomozno** [comment]
> Потому что инструкция о том как создать репорт, а не как копировать текст из чата игры.
> Банально можно руками написать Build xxx и этого будет достаточно.

тоесть я вас правильно понимаю? чтоб вы начали делать свою работу я должен указать вам на недостатки для этого вам недостаточно внутриигрового сервиса и вы требуете чтоб я регистрировался на стороннем ресурсе еще и англоязычном и в дополнение ко всему вы хотите еще и чтоб я скачивал сомнительные дополнения которые не нужны для игрового процесса? вам не кажется что если реагировать на сообщения из внутриигровой службы поддержки то во всем этом маразме отпадает необходимость? да и прошло уже  4 дня! четыре дня вы учите меня в коментариях как оформить заявку! думаю вместо писанинины комментариев можно было как-то отреагировать на заявку! тем более что я ее исправил но она все равно со статусом "требует оформления"

**Comment by daskolkomozno** [comment]
> Потому что инструкция о том как создать репорт, а не как копировать текст из чата игры.
> Банально можно руками написать Build xxx и этого будет достаточно

> Потому что инструкция о том как создать репорт, а не как копировать текст из чата игры.
> Банально можно руками написать Build xxx и этого будет достаточно.

У меня создается впечатление что вся эта цифровая бюрократия создана специально чтоб отбить у пользователей желание обращаться к вам за помощью((( а жаль! Я прекрасно понимаю что мои замечания вам не приятны! и вы изо всех сил пытаетесь доказать что это я не прав! и заявку неправильно оформляю и аддон не скачал чтоб копировать не копируемое и блин тупой такой без переводчика не понимаю что такое пруф и issue. но я и не должен...и как бы там ни было один из важнейших дренейских квестов не работает не из-за того что я неправильно оформляю заявку(((

**Comment by gmRial** [comment]
> > Потому что инструкция о том как создать репорт, а не как копировать текст из чата игры.
> > Банально можно руками написать Build xxx и этого будет достаточно.
> 
> тоесть я вас правильно понимаю? чтоб вы начали делать свою работу я должен указать вам на недостатки 

Нет, вы понимаете неправильно.
Починкой багов занимается разработчик, а не служба поддержки (игровые мастера).

> для этого вам недостаточно внутриигрового сервиса и вы требуете чтоб я регистрировался на стороннем ресурсе еще и англоязычном и в дополнение ко всему вы хотите еще и чтоб я скачивал сомнительные дополнения которые не нужны для игрового процесса?

Мы ничего не требуем, мы предлагаем. Можете ничего не скачивать, нигде не регистрироваться, и ничего не делать - ваше право.

> вам не кажется что если реагировать на сообщения из внутриигровой службы поддержки то во всем этом маразме отпадает необходимость? 

Не кажется.

> да и прошло уже 4 дня! четыре дня вы учите меня в коментариях как оформить заявку! думаю вместо писанинины комментариев можно было как-то отреагировать на заявку! тем более что я ее исправил но она все равно со статусом "требует оформления"

И все эти 4 дня тело репорта до сих пор не приведено к требуемому виду. Еще 3 дня и он будет закрыт.

**Comment by daskolkomozno** [comment]
> > > Потому что инструкция о том как создать репорт, а не как копировать текст из чата игры.
> > > Банально можно руками написать Build xxx и этого будет достаточно.
> > 
> > 
> > тоесть я вас правильно понимаю? чтоб вы начали делать свою работу я должен указать вам на недостатки
> 
> Нет, вы понимаете неправильно.
> Починкой багов занимается разработчик, а не служба поддержки (игровые мастера).
> 
> > для этого вам недостаточно внутриигрового сервиса и вы требуете чтоб я регистрировался на стороннем ресурсе еще и англоязычном и в дополнение ко всему вы хотите еще и чтоб я скачивал сомнительные дополнения которые не нужны для игрового процесса?
> 
> Мы ничего не требуем, мы предлагаем. Можете ничего не скачивать, нигде не регистрироваться, и ничего не делать - ваше право.
> 
> > вам не кажется что если реагировать на сообщения из внутриигровой службы поддержки то во всем этом маразме отпадает необходимость?
> 
> Не кажется.
> 
> > да и прошло уже 4 дня! четыре дня вы учите меня в коментариях как оформить заявку! думаю вместо писанинины комментариев можно было как-то отреагировать на заявку! тем более что я ее исправил но она все равно со статусом "требует оформления"
> 
> И все эти 4 дня тело репорта до сих пор не приведено к требуемому виду. Еще 3 дня и он будет закрыт.

Что не так оформлено теперь? Ссылка на вовхед есть?Есть! Неисправность описал? Описал! Как должно работать указал и даже ссылку на ютюб оставил!Шаги для воспроизведения ошибки даже написал! Версию ядра указал? Указал! (если вас устраивала версия ядра написаная в ручную то думаю с таким же успехом вы ее сможете прочитать со скриншота.

**Comment by daskolkomozno** [comment]
Что не так оформлено теперь? Ссылка на вовхед есть?Есть! Неисправность описал? Описал! Как должно работать указал и даже ссылку на ютюб оставил!Шаги для воспроизведения ошибки даже написал! Версию ядра указал? Указал! (если вас устраивала версия ядра написаная в ручную то думаю с таким же успехом вы ее сможете прочитать со скриншота.

**Comment by daskolkomozno** [comment]
спасибо тебе добрый человек!!! кстати этот дядька и в игре постоянно помогает!

**Comment by Kodekc** [comment]
Я портировал скрипты на это задание, похоже, где-то что-то отвалилось, посмотрю

**Comment by daskolkomozno** [comment]
> Я портировал скрипты на это задание, похоже, где-то что-то отвалилось, посмотрю

спасибо большое!!!

**Comment by AatiTheShine** [comment]
Добрый день. Проблема с квестом актуальна и на данный момент. Какие-то действия к предотвращению проблемы осуществляются?

**Comment by daskolkomozno** [comment]
вижу что что-то делали, из четвертого кристалла появился красный луч но с солнечными воротами все равно взаимодействовать не возможно

**Comment by Kodekc** [comment]
Исправлено. Изменения будут применены в ближайшем обновлении
