### ISSUE TITLE
[Заклинание] ID 67102 - Крутящийся шип боли

### ISSUE THREAD

**Issue by MedoOf** [VirginTeam/WotlkCore#1503]
**Ссылки и комментарии:**

http://db.logon3.com/?spell=67102 

**Что работает не так?**

Занижен урон, возможно режется броней, но скорее всего просто занижен % от хп игрока, на который и дамажит спелл, т.к. в обоих случаях цель шаман (около 50% снижения урона от физы) и даже 12к для 25гер это мало.

> [20:40:43.481] Unknown Крутящийся шип боли Avariice 5801

> [20:20:13.777] Unknown Крутящийся шип боли Namiko 6294

**Как должно работать?**

Сложно вычислить точные % от хп, но спелл должен наносить гораздо больше урона. По некоторым форумам там 100%, но это ваншот любого игрока, а по логам игроки выживают всегда после удара. Можно предположить что берется 100% от максимального хп игрока, а потом действуют эффекты снижающие урон в %. 

> [19:48:26.558] Unknown Spinning Pain Spike Flipadelphia 10503 (A: 13491)

Возможно стоит поставить метку уточнить детали, но инфы по этому спелу нет, он не сильно существенен.

**Текущее обновление ядра:**

242

**Comment by ForesterDev** [comment]
Должен снимать 50% от максимального запаса ХП. ПРоблема в том, что режется броней. Протестите после обновления
