### ISSUE TITLE
[Предмет] ID 52001 Сумка с полезными вещами

### ISSUE THREAD

**Issue by kalambyr18** [VirginTeam/WotlkCore#1507]
**Ссылки и комментарии:**

http://db.logon3.com/?item=52001#contains

**Что работает не так?**

По началу внимания особо не обращал, но с 35 лвл примерно по 41 ( танчил подземки варом ) и примерно за 20-25 подземок мне падали только латные наплечники(дроп с сумки по данным лвл по ссылке выше ) . Ни одного кольца. При условии вероятности дропа колец в 50% сомневаюсь, что сумки работают правильно .. Возможно вообще все сумки направильно работают.
upd.: до 46 лвл так ни одного кольца и не дропнулось + пока бегал подземки был игрок котор .жаловался на то же самое .
Просьба пересмотреть вероятность дропа.

**Как должно работать?**

Ну хоть одно кольцо на стаму бы хотелось получить .

**Шаги для воспроизведения ошибки:**

1. Танкануть !
2, Еще раз танкануть !
3, И еще !
4, Скушать "аппетитный кекс".

**Текущее обновление ядра:**

242

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by kalipsa988** [comment]
50% по отношению к 4м шмоткам. у тебя выбор из 2х идёт, так что 50% на плечи и на кольцо + эта сумка падает 35-45, удачи в фарме

**Comment by kalambyr18** [comment]
То есть хочешь сказать я настолько невезучий, что с 20 сумок не получил ни одного кольца с шансом в 50%?

**Comment by kalipsa988** [comment]
да

**Comment by kalambyr18** [comment]
Я так понимаю там что то фиксили по поводу данных сумок . Здорово . А зачем вару латные наплечники на 35 лвл ? Я сейчас качну 46 лвл и что то мне подказывает, что там намудрили с дропом и кольца я так и не увижу .

**Comment by kalipsa988** [comment]
Ну вот с этим моментом согласен, как по мне должен идти дроп шмота от максимально возможного типа брони на данный момент, а не на максимальный тип брони класса в принципе

**Comment by kalambyr18** [comment]
Ни одного кольца так и не дропнулось https://ibb.co/G2ZDVSk ( это я начал собирать плечи после того уже как репорт создал ) . В общем это борода .

**Comment by kalipsa988** [comment]
Завтра, если гма поймаю, то проверю сумки, мне дру 66 жаловался на пустые сумки

**Comment by kalipsa988** [comment]
![image](https://user-images.githubusercontent.com/29568428/53324175-2fb25180-38f1-11e9-81d9-8808ca833b2e.png)
как-то так

**Comment by kalipsa988** [comment]
![wowscrnshot_022519_113325](https://user-images.githubusercontent.com/29568428/53324188-8586f980-38f1-11e9-943a-30e3cb263ae3.jpg)
как-то так

**Comment by kalambyr18** [comment]
ну .. капец я невезучий .. первый раз такое . Окок

**Comment by Kodekc** [comment]
Не выявлено никаких проблем с дропом. Работает правильно
