### ISSUE TITLE
[Задание] ID 13045 - В чащобу

### ISSUE THREAD

**Issue by Nassertia** [VirginTeam/WotlkCore#1508]
**Ссылки и комментарии:**

https://ru.wowhead.com/quest=13045/в-чащобу

**Что работает не так?**

Дракон, с помощью которого нужно непосредственно спасать, не летает нормально.

**Как должно работать?**

Садишься на дракона - летишь, а не ползешь, как он это делает сейчас.

**Шаги для воспроизведения ошибки:**

1. Сесть на протодракона.
2. (Не)лететь.

**Текущее обновление ядра:**

Build 242 2019-02-18 12:08:24 +0400
Live Server

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by ruafelianna** [comment]
Скажите, пожалуйста, починят этот квест когда-нибудь? :( Всё же работало раньше...

**Comment by ForesterDev** [comment]
![image](https://user-images.githubusercontent.com/11771800/58795977-19f9aa00-860d-11e9-9e27-a4823a58047a.png)
Все нормально работает

**Comment by ruafelianna** [comment]
Сейчас да, нормально работает после одного из обновлений) Но на момент написания этого репорта не работало)
