### ISSUE TITLE
[Задание] ID 13133 - Поиски древнего героя

### ISSUE THREAD

**Issue by Nassertia** [VirginTeam/WotlkCore#1509]
**Ссылки и комментарии:**

https://ru.wowhead.com/quest=13133/поиски-древнего-героя

**Что работает не так?**

НПС, которые являются потенциальными Искальдерами(Спящий мьордин) являются агрессивными. Они не нападают на игрока самостоятельно, но если сагрить ближайшего моба - сагрятся и они. С ними нельзя "поговорить" (т.е. разбудить), соответственно, квест никак не выполнить.

**Как должно работать?**

У игрока должна быть возможность разбудить спящих мьординов, чтобы отыскать искальдера. То есть НПС должны быть "зелеными" или "желтыми".

**Шаги для воспроизведения ошибки:**

1. Взять задание.
2. Отправиться в локацию "Залы предков".
3. Найти там агрессивных спящих мьординов.

**Текущее обновление ядра:**

Build 242 2019-02-18 12:08:24 +0400
Live Server

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by Hellsingoff** [comment]
Не "зелеными", а "желтыми" скорее. Нейтральными.
Отписывался в старом тикете уже с неделю назад, но не успел пока написать новый (есть ещё пара тикетов, которые хотелось бы написать, руки не доходят)
https://github.com/VirginTeam/WotlkCore/issues/216
