### ISSUE TITLE
[Предмет] ID 52005 - Сумка с полезными вещами

### ISSUE THREAD

**Issue by kalipsa988** [VirginTeam/WotlkCore#1513]
**Ссылки и комментарии:**

http://db.logon3.com/?item=52005#contains

**Что работает не так?**

в 1 сумке может быть сразу 2 шмотки или не быть ни одной

**Как должно работать?**

Должно падать по 1 шмотки в 1 сумке и не быть пустых

**Шаги для воспроизведения ошибки:**

1.Прописать сумки
2. Открывать
3. Шаг три

**Текущее обновление ядра:**

25.02.19

**Comment by Kodekc** [comment]
Каким классом открывалась сумка, когда выпадало два предмета или не выпадало ничего?

**Comment by kalipsa988** [comment]
друид
![wowscrnshot_022519_114527](https://user-images.githubusercontent.com/29568428/53344529-ea5b4780-3923-11e9-9f6f-53eb1561bdfa.jpg)

**Comment by kalipsa988** [comment]
![wowscrnshot_022519_114509](https://user-images.githubusercontent.com/29568428/53344547-f3e4af80-3923-11e9-81cd-9bbc2130a8b5.jpg)

**Comment by Kodekc** [comment]
Исправлено. Изменения будут применены в ближайшем обновлении
