### ISSUE TITLE
[Заклинание] ID 58426 - Бойня

### ISSUE THREAD

**Issue by shee4** [VirginTeam/WotlkCore#1514]
**Ссылки и комментарии:**

https://ru.wowhead.com/spell=58426
http://db.logon3.com/?spell=58426

**Что работает не так?**

Бафф Бойня (ветка ликвидация) скидывается, несмотря на то, что персонаж находится в невидимости или недавно вышел из неё.

**Как должно работать?**

Бафф Бойни не должен сбрасываться сам, если персонаж в невидимости и висеть 20 секунд после выхода из неё.

**Шаги для воспроизведения ошибки:**

1. Зайти в инвиз
2. Выйти
3. Снова войти в инвиз, пока бафф Бойня висит на персонаже

**Текущее обновление ядра:**

Build 243 2019-02-25 11:34:59 +0400 Life

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by Kodekc** [comment]
Сейчас я перепроверил это. Верно ли я понимаю, таймер обратного отсчета баффа Бойни не отображается после выхода из режима незаметности и входа в режим незаметности повторно? Он пропадает через время вовсе

**Comment by Kodekc** [comment]
Взаимосвязанные проблемы:
https://github.com/VirginTeam/WotlkCore/issues/1500

**Comment by Kodekc** [comment]
spell_rogue.cpp#L545

**Comment by shee4** [comment]
Нет, после выхода из незаметности запускается таймер Бойни. Если, пока он идет, снова войти в незаметность, то повиснет перманентный бафф бойни, но (как я понял в этом заключается баг) таймер не останавливается, и, когда таймер заканчивается, то Бойня спадает. И таймер не перезапускается, если второй раз выйти из незаметности. Пример: я выхожу из невидимости, запускается таймер на Бойню 20 секунд. Откатывается невидимость (5 секунд) и я снова ухожу в невидимость (Появляется перманентный бафф Бойни) и стою в ней. По истечении 15 оставшихся секунд бафф спадает, хоть персонаж всё еще в невидимости.
