### ISSUE TITLE
[Задание] ID 12572 - Боги любят блестящие штучки

### ISSUE THREAD

**Issue by Skellan** [VirginTeam/WotlkCore#1518]
**Ссылки и комментарии:**
https://www.youtube.com/watch?v=GPRTQd8ceIo
Добавьте ссылки с wowhead.com или db.logon3.com на проблемные задания, NPC, заклинания и т.д.

**Что работает не так?**
Не работает нпс Лафу http://ru.wowhead.com/npc=28120 .Он просто ничего не делает. Так же на нпс Лафу агрятся Императорская кобра http://ru.wowhead.com/npc=28011
Фактический результат — тот, который вы наблюдаете

**Как должно работать?**
нпс Лафу должен подходя к местам с блеском должен выкапывать Драгоценные блестяшки http://ru.wowhead.com/item=38575
Ожидаемый результат — то, чего вы ожидали при выполнении ваших действий. Процесс правильной работы

**Шаги для воспроизведения ошибки:**

1. Подхожу к месту с блеском с вызваным нпс и ничего не просходит
2. Шаг два
3. Шаг три

**Текущее обновление ядра:**
Build 199 2018-05-04 15:41:18 +0400
Можно посмотреть в игре, введите в чат команду .server info и скопировать строку начиная с Build с номером и датой. Не забывайте указывать, Live Server или PTR Server, где проводилось тестирование.
**Ссылки и комментарии:**
https://www.youtube.com/watch?v=GPRTQd8ceIo
Добавьте ссылки с wowhead.com или db.logon3.com на проблемные задания, NPC, заклинания и т.д.

**Что работает не так?**
Не работает нпс Лафу http://ru.wowhead.com/npc=28120 .Он просто ничего не делает. Так же на нпс Лафу агрятся Императорская кобра http://ru.wowhead.com/npc=28011
Фактический результат — тот, который вы наблюдаете

**Как должно работать?**
нпс Лафу должен подходя к местам с блеском должен выкапывать Драгоценные блестяшки http://ru.wowhead.com/item=38575
Ожидаемый результат — то, чего вы ожидали при выполнении ваших действий. Процесс правильной работы

**Шаги для воспроизведения ошибки:**

1. Подхожу к месту с блеском с вызваным нпс и ничего не просходит
2. Шаг два
3. Шаг три

**Текущее обновление ядра:**
Build 243 2019-02-25 11:34:59 +0400
Можно посмотреть в игре, введите в чат команду .server info и скопировать строку начиная с Build с номером и датой. Не забывайте указывать, Live Server или PTR Server, где проводилось тестирование.

Скопировал данную заявку с #936 - ошибка такая же, блестящие зоны забагались, выкопать блестяшки невозможно, за все время (несколько дней пытался сделать задание) выкопал только 1(!!) камень в самом начале после взятия квесты. После - только редкие жуки. Починили, б**, цепочку, называется. И сбрасывать уже имеющееся превознесение ради этого мучение - красиво.

**Comment by ForesterDev** [comment]
На тестирование после применения обновления

**Comment by IssueCreatorCircle335** [comment]
Читая описание баги мне трудно было представить что же работало (работает) не так.
За последних пол-года, лично я не наблюдал сложностей с квестом и функционалом помощников 
http://db.logon3.com/?npc=28120
http://db.logon3.com/?spell=51191
http://db.logon3.com/?spell=51192
Все они отлично бегают, разговаривают, и даже останавливаются где нужно с попыткой чего-то выкопать. Просто выкапывалось редко, нужно было запастись терпением, постоять рядом с блестящими точками, и все работало.
И если до последнего обновления (от 01.03.2019) можно было выполнить квест потратив чуть больше времени, то сейчас это стало еще труднее. (создается ощущение, что именно этого "Как_должно_работать?_результата" и добивались, когда фиксили баг)

Хочу сообщить, что за 3 дня бета тестирования даже у меня нервы сдали.
Квест, в принципе выполнимый, только свои "особенности":
На территории квеста расположено 77 точек респауна потенциальных квест-итемов http://db.logon3.com/?npc=28362 (Мерцающая грязь).
Из них раз в день выбирается 1-3 точки, где будет возможно выкопать "Драгоценные блестяшки" 
http://db.logon3.com/?object=190558
http://db.logon3.com/?object=190560
http://db.logon3.com/?object=190561
http://db.logon3.com/?object=190562
http://db.logon3.com/?object=190563
из которых собирается http://db.logon3.com/?item=38575.
Из остальных выкапываются только жуки http://db.logon3.com/?npc=28372 или ничего.

После выкапывания нужного квест-итема мерцающая грязь исчезает на кд (5 мин), а после респауна конкретно этой же точки, с нее снова выпадет блестяшка. (Совпадение? - не думаю)

Повторюсь, точки выбираются СТАТИЧНО на день! Т.е. на всей территории квеста нужно ждать возле одной-двух точек чтобы выкопать 6 "блестяшек" (итого 15-30 минут на квест если ты один на территории). Остальные точки можно даже не стараться копать, из них вылазят жуки, сами точки мерцающей грязи при этом не исчезают на кд, соответственно не обновляются.

Можно было бы сказать, что так и нужно, что такой шанс дропа и т. д. Но, когда помощник копает, он издает характерные звуки (речь), типа: 
"Больше сокровищ! Сокровищ всех видов! Ура, сокровища!" или
"О-о-о, блестяшки!"
и при этом выкапывает... жуков. Хотя даже его речь намекает на обратное...

В общем, проверьте, пожалуйста, шанс дропа квестовых предметов из точек "мерцающей грязи" или шанс на каст "правильного" скила у помощника, уж слишком мало блестяшек на болоте...

П.С. По моему поторопились сбросить репутацию с такими "фиксами".
