### ISSUE TITLE
[NPC] ID 34797 - Ледяной Рев

### ISSUE THREAD

**Issue by MedoOf** [VirginTeam/WotlkCore#1522]
**Ссылки и комментарии:**

http://db.logon3.com/?npc=34797

**Что работает не так?**

Не снимается шкура после убийства

**Как должно работать?**

Должна сниматься, его туша посреди инста чутка мешается

**Текущее обновление ядра:**

243

**Comment by Kodekc** [comment]
В базе прописан соответствующий лут для снятия шкур

**Comment by MedoOf** [comment]
Лут мб и прописан, но тушка багается и лежит в инсте. А шкура не снимается
