### ISSUE TITLE
[Заклинание] ID 8907 - Знак дикой природы

### ISSUE THREAD

**Issue by kalipsa988** [VirginTeam/WotlkCore#1524]
**Ссылки и комментарии:**

http://db.logon3.com/?spell=8907 ( все уровни этого заклинания)

**Что работает не так?**

Перебивается более низкими уровнями этого заклинания, т е если на цели заклинание 5го лв, то любой друль может перебить его 1м уровнем

**Как должно работать?**

Если на цели висит баф к примеру 5го уровня и попытаться кинуть 1й, то должно писать, что на цели висит более мощное заклинание

**Шаги для воспроизведения ошибки:**

1. Бафнуть максимальный уровень заклинания
2. Бафнуть минимальный уровень заклинания
3. Шаг три

**Текущее обновление ядра:**

04.03.19

**Comment by Kodekc** [comment]
А у других классов нет такой же проблемы?

**Comment by kalipsa988** [comment]
Заметил только у друидов

**Comment by kalipsa988** [comment]
исправили, но не полностью

**Comment by kalipsa988** [comment]
1й уровень перебивает любой уровень
