### ISSUE TITLE
[Игровая механика] Урон при падении персонажа

### ISSUE THREAD

**Issue by Santaria** [VirginTeam/WotlkCore#1525]
**Что работает не так?**

Если спрыгнуть с большой высоты на наземном маунте и в момент падения спешится, то обнуляется значение высоты, с которой падал персонаж. Таким образом, если скинуть маунта перед самым приземлением, то можно полностью избежать даже смертельного урона.

**Как должно работать?**

Сброс маунта во время падения не должен обновлять точку, из которой началось падение персонажа.

**Шаги для воспроизведения ошибки:**

https://youtu.be/FYKaAyQEgBw

**Текущее обновление ядра:**

PTR 105

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by kalipsa988** [comment]
исправлено
