### ISSUE TITLE
[Подземелье] Испытание чемпиона (Сундуки с лутом)

### ISSUE THREAD

**Issue by Santaria** [VirginTeam/WotlkCore#1526]
**Что работает не так?**

Сундуки с лутом исчезают после запуска следующего босса. Если лут не успели разролить, то он пропадает. Некоторые игроки специально запускают следующего босса до окончания розыгрыша, чтобы запороть лут другим.

**Как должно работать?**

Сундук не должен исчезать после запуска следующего босса. Должен исчезать после того, как его открыли и закончился таймер распределения добычи.

**Шаги для воспроизведения ошибки:**

1) Создать группу и установить групп лут.
2) Открыть сундук и одним из персонажей не нажимать ни одну из кнопок вплоть до окончания таймера.
3) Запустить следующего босса после открытия сундука.

**Текущее обновление ядра:**

Build 245

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by Rorshah** [comment]
Какие ваши доказательства ? :)
