### ISSUE TITLE
Не работает квест

### ISSUE THREAD

**Issue by OlegWiktorowich** [VirginTeam/WotlkCore#1527]
**Ссылки и комментарии:**

Добавьте ссылки с wowhead.com или db.logon3.com на проблемные задания, NPC, заклинания и т.д. 

**Что работает не так?**
квест Солнечные врата на острове кровавой дымки
Фактический результат — тот, который вы наблюдаете 
4 ключа-крисстала есть, когда их отключаешь ворота не закрываются, квест не выполняется и дополнительного ключа нету. Основная проблема нет 5 ключа для закрытия.
**Как должно работать?**
когда уничтожаешь 4 ключа-крисстала сами ворота должны стать криссталом. уничтожив который, квест будет выполнен. Вроди так.
Ожидаемый результат — то, чего вы ожидали при выполнении ваших действий. Процесс правильной работы
Процесс правильной работы
**Шаги для воспроизведения ошибки:**

1. Шаг один
2. Шаг два
3. Шаг три

**Текущее обновление ядра:**

Можно посмотреть в игре, введите в чат команду .server info и скопировать строку начиная с Build с номером и датой. Не забывайте указывать, Live Server или PTR Server, где проводилось тестирование.

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by Ovalon** [comment]
https://ru.wowhead.com/quest=13058/чтобы-ветер-переменился
Не работает данный квест в Грозовой гряде
Цель, необходимая по квесту (Северный ветер) является дружественной и мертвой. Начать бой с ней невозможно

**Comment by GmAlleria** [comment]
дубль

**Comment by OlegWiktorowich** [comment]
Наталья, заявка еще об одном нерабочем квесте. примете?




>Четверг,  7 марта 2019, 16:18 +03:00 от Наталья <notifications@github.com>:
>
>Closed  #1527 .
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

-- <br/>Олег Барсуков
