### ISSUE TITLE
[Задание] ID 11433 - Спящие великаны

### ISSUE THREAD

**Issue by Senatyan** [VirginTeam/WotlkCore#1530]
https://ru.wowhead.com/quest=11433

**Что работает не так?**

Нету перевода 

**Как должно работать?**

Должен быть перевод

Последнее обновление ядра: Build 245 2019-03-04 17:48:40 +0400
![WoWScrnShot_030919_195255](https://user-images.githubusercontent.com/35963582/54072650-0ce84b80-42a8-11e9-8f52-4eac3f8ed4bc.jpg)

**Comment by Kodekc** [comment]
Найдите перевод ;-) Добавлю
