### ISSUE TITLE
[Задание] ID 11157 - В тисках зла

### ISSUE THREAD

**Issue by Senatyan** [VirginTeam/WotlkCore#1531]
https://ru.wowhead.com/quest=11157

Добавьте ссылки с wowhead.com или db.logon3.com на проблемные задания, NPC, заклинания и т.д. 

Нету перевода

Фактический результат — тот, который вы наблюдаете 
Должен быть перевод
 
Ожидаемый результат — то, чего вы ожидали при выполнении ваших действий. Процесс правильной работы

**Шаги для воспроизведения ошибки:**

1. Шаг один
2. Шаг два
3. Шаг три

Последнее обновление ядра: Build 245 2019-03-04 17:48:40 +0400

![WoWScrnShot_030919_195301](https://user-images.githubusercontent.com/35963582/54072840-6fdae200-42aa-11e9-8fd6-44369a2d982e.jpg)

**Comment by Kodekc** [comment]
Этот текст в какой момент появляется?
