### ISSUE TITLE
Кристаллы телепортации

### ISSUE THREAD

**Issue by Fisessar** [VirginTeam/WotlkCore#1532]
**Ссылки и комментарии:**

https://ru.wowhead.com/object=191229/кристалл-телепортации-на-аметистовую-заставу
https://ru.wowhead.com/object=191230/кристалл-телепортации-в-даларан

**Что работает не так?**

Кристаллы не телепортируют

**Как должно работать?**

Кристаллы должны телепортировать на Аметистовую заставу и в Даларан соответственно

**Шаги для воспроизведения ошибки:**

1. Клик по кристаллу вызывает каст с полоской "Применение", по окончании которого ничего не происходит

**Текущее обновление ядра:**

Build 245 2019-03-04 17:48:40 +0400

**Comment by ForesterDev** [comment]
Кристаллы работают, но требуется выполнение квеста http://db.logon3.com/?quest=12790
