### ISSUE TITLE
Ученица Мирведа - Упрямая Ученица

### ISSUE THREAD

**Issue by ragebow** [VirginTeam/WotlkCore#1533]
**Ссылки и комментарии:**

НИП
Ученица Мирведа
http://db.logon3.com/?npc=15402

Задание 
Упрямая Ученица
http://db.logon3.com/?quest=9254

**Что работает не так?**

Нет "?" над головой, нельзя закончить задание.

**Как должно работать?**

Завершение задания "Упрямая Ученица" при помощи "?".

**Шаги для воспроизведения ошибки:**

1. Начать задание "Упрямая Ученица" у НИП Магистр Ландра Рассветная Странница http://db.logon3.com/?npc=16210
2. Подойти к НИП Ученица Мирведа http://db.logon3.com/?npc=15402

**Текущее обновление ядра:**

Build 245 2019-03-04 17:48:40 +0400

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by GmAlleria** [comment]
Дубль #638
