### ISSUE TITLE
[Игровая механика] Целитель душ в Восточных чумных землях.

### ISSUE THREAD

**Issue by Grunbeld** [VirginTeam/WotlkCore#1535]
**Ссылки и комментарии:**
Cкриншот:
https://i.imgur.com/E1vWuRY.jpg

**Что работает не так?**

Варлоком после смерти в Восточных чумных землях бросило к целителю душ в стартовую локацию рыцарей смерти.

**Как должно работать?**

Должен был попасть к другому ближайшему целителю душ.

**Шаги для воспроизведения ошибки:**

Смерть в области над стартовой локацией дк (на скриншоте область с двумя значками арканитовых кристаллов. Умер около верхнего, примерно 78, 31 координаты).

**Текущее обновление ядра:**

Live Server
Build 246 2019-03-14 17:09:50 +0400

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by ForesterDev** [comment]
![image](https://user-images.githubusercontent.com/11771800/55937297-b0cb6b00-5c49-11e9-8721-71579b369708.png)
Не могу подтвердить, умер примерно по вашим координатам. Уточните детали - более точные координаты, расу.
