### ISSUE TITLE
[Задание] ID 13833 - Густая кровь

### ISSUE THREAD

**Issue by MiceRus** [VirginTeam/WotlkCore#1538]
**Ссылки и комментарии:**
http://db.logon3.com/?quest=13833

Что работает не так?
После убийства мобов персонаж окрашен кровью моба.
При нырянии в воду озера со 100% вероятностью в озере должно появится на этом месте "Лужа крови" http://db.logon3.com/?object=194479

**Фактический результат — тот, который вы наблюдаете** 
Наблюдаю? ВООБЩЕ НЕ НАБЛЮДАЮ!!! Если вчера хотя бы после 6-го моба появилась Лужа, то сегодня я убил 16 мобов и ни разу после ныряния лужа так и не появилась.
Кроме того, поплавок теперь ВООБЩЕ не работает. Т.е. любое занятие, связанное с ловлей рыбы обречено на провал. Классное завтра будет Кулуакское рыбоборье.

Как должно работать?
После каждого ныряния окровавленного персонажа в воду озера на том месте, куда он нырял, должна появится Лужа крови http://db.logon3.com/?object=194479

**Шаги для воспроизведения ошибки:**

1. Взять квест у нипа в Даларане
2. Прилететь на место и убить мамонта (к примеру)
3. Окунуться в воду и увидеть ,что кровь смылась, но лужа не появилась. Ловить негде.

**Текущее обновление ядра:**

Последнее обновление ядра: Build 246 2019-03-14 17:09:50 +0400

**Comment by MiceRus** [comment]
И? Никто даже не обратил внимания на данный пост? Что-то не так оформлено?

**Comment by kalipsa988** [comment]
![WoWScrnShot_031819_133454](https://user-images.githubusercontent.com/29568428/54524294-ad163280-4982-11e9-983d-f1a222192a06.jpg)
я бы вообще закрыл этот репорт

**Comment by MiceRus** [comment]
Еще раз. Лужа крови ДОЛЖНА появляться при КАЖДОМ омывании персонажа, а не рандомно.

**Comment by gmRial** [comment]
> И? Никто даже не обратил внимания на данный пост? Что-то не так оформлено?

За репорт спасибо, надеюсь, шапку репорта в будущем будете так же красиво оформлять.

**Comment by MiceRus** [comment]
Блин. Ничего не понял :) В шапке что-то не так? Или это был сарказм? Те репорты, что я делал - я всегда так же оформлял и не было никаких замечаний.

**Comment by Kodekc** [comment]
Обратите внимание на название репорта, оно должно иметь определённую, заданную стилистику.

**Comment by MiceRus** [comment]
Ок. понял. Обещаю исправиться :)

**Comment by Kodekc** [comment]
Должно быть исправлено. Изменения уже применены, перепроверьте
