### ISSUE TITLE
[Игровая механика] Непобедимый и Прогулочная ракета X-53

### ISSUE THREAD

**Issue by gmRial** [VirginTeam/WotlkCore#1542]
**Ссылки и комментарии:**

http://db.logon3.com/?item=50818
http://db.logon3.com/?item=54860

**Что работает не так?**

Непобедимый дает 310% скорости. Ракета обладает изменяемой скоростью, и если у персонажа есть маунт с 310% скоростью, то она будет летать с такой же. На данный момент, Ракета не учитывает наличие Непобедимого у персонажа.

**Как должно работать?**

Имея Непобедимого, Ракета должна летать с 310% скоростью.

**Шаги для воспроизведения ошибки:**

1. Изучить Непобедимого, полетать на нем, запомнить скорость.
2. Изучить Ракету, полетать на ней и увидеть скорость.
3. Изучить Пепел Алара http://db.logon3.com/?item=32458
4. Полетать на Ракете, увидеть, что скорость изменилась.

**Текущее обновление ядра:**

248

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by ForesterDev** [comment]
Это условие "characters that already had a 310% speed flying mount" распространяется на ИСКЛЮЧИТЕЛЬНО летающих маунтов. Непобедимый же является составным маунтом - совсем другая категория. Есть пруфы? Вероятно что близзлайк

**Comment by gmRial** [comment]
Пруфы найти не удалось.
