### ISSUE TITLE
[Броня] id 40440, 40441, 40442, 40443, 40444 Жуткий латный доспех жестокого гладиатора 

### ISSUE THREAD

**Issue by PISdid** [VirginTeam/WotlkCore#1543]
**Ссылки и комментарии:**
то что ДОЛЖНО быть
https://wowroad.info/?item=40440
https://wowroad.info/?item=40441
https://wowroad.info/?item=40442
https://wowroad.info/?item=40443
https://wowroad.info/?item=40444
то что есть на самом деле
https://ibb.co/KxnMjmG
https://ibb.co/CQGdB6q
https://ibb.co/whr6FLB
https://ibb.co/fHxt3kR
https://ibb.co/NTN0BfF
**Что работает не так?**
Нет показателя брони, нет статов брони 
**Как должно работать?**

Ожидание исправления ошибки достигло 4 месяцев....

**Шаги для воспроизведения ошибки:**

1. Открыть инвентарь
2. Посмотреть на броню
3.Написать об этом

**Текущее обновление ядра:**
Logon 3 wowcircle development
build 248 2019-03-15 15:17:29 +0400

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by Plasmashield** [comment]
Должно? Правда? Этого сета вообще быть не должно

**Comment by PISdid** [comment]
его ввели в продажу, я его купил и вот такая проблема.....

**Comment by Kodekc** [comment]
Это уже исправлялось, вы давно в игре то проверяли?

**Comment by PISdid** [comment]
я вчера скрины сделал

**Comment by gmRial** [comment]
Завтра проверим, что в базе

**Comment by gmRial** [comment]
В базе все значения прописаны.
Обратитесь в центр поддержки для замены предметов (приложите ссылку на репорт).

**Comment by MiceRus** [comment]
Если использовать WOWEquip и сделать запрос к серверу по ID предмета - то ничего не находит.
ДА и по имени - там совсем другие ID предметов

**Comment by Senatyan** [comment]
Может удалить из БД какие - то левые предметы, чтобы игроки больше не покупали/получали дефектные предметы.

**Comment by gmRial** [comment]
Предметы в порядке.
http://joxi.ru/52azoQbIEE0xpA
http://joxi.ru/823x0j6I99wqvA
http://joxi.ru/8AnoZ0dTzzKxLr
http://joxi.ru/KAxoy5xTZZwLJ2
http://joxi.ru/L21zMjQIRRDq5A

**Comment by Santaria** [comment]
Почистить кеш в клиенте надо, у меня в игре этот сет вообще без статов отображался.
