### ISSUE TITLE
[Группа предметов] - динамиты

### ISSUE THREAD

**Issue by kalipsa988** [VirginTeam/WotlkCore#1546]
**Ссылки и комментарии:**

http://db.logon3.com/?item=18641, http://db.logon3.com/?item=6714, http://db.logon3.com/?item=4378, http://db.logon3.com/?item=4365, http://db.logon3.com/?item=4358, http://db.logon3.com/?item=18641,  http://db.logon3.com/?item=10507
(возможно ещё мины, не проверялось)
**Что работает не так?**

Все это скалируется от СПД

**Как должно работать?**

Не должно скалироваться

**Шаги для воспроизведения ошибки:**

1. абуз спд
2. кидание в другого игрока
3. Шаг три

**Текущее обновление ядра:**

20.03.19

**Comment by ForesterDev** [comment]
Неактуально
