### ISSUE TITLE
[Заклинание] ID 53517 - Рев восстановления

### ISSUE THREAD

**Issue by kalipsa988** [VirginTeam/WotlkCore#1547]
**Ссылки и комментарии:**

http://db.logon3.com/?spell=53517

**Что работает не так?**

Если пет стоит за препятствием от ханта и прожать спел, то кд повесит, а баф не даст 

**Как должно работать?**

Должно работать, если пет за препятствием

**Шаги для воспроизведения ошибки:**

1. поставить пета за препятствие
2. прожать спел
3. Шаг три

**Текущее обновление ядра:**

10.07.20

**Comment by ForesterDev** [comment]
У какого пета эта способность?

**Comment by kalipsa988** [comment]
Опустошитель, таланты качать надо

**Comment by ForesterDev** [comment]
Не воспроизводится - способность не используется если цель далеко. Кд не запускается

**Comment by kalipsa988** [comment]
по фану написал так понимаю, проверил спустя год, все на местах осталось, тыкаешь далеко тупо кд вешаешь без бафа
