### ISSUE TITLE
[Предмет] ID 18268 - Ключ от внутренней двери Гордока

### ISSUE THREAD

**Issue by kalipsa988** [VirginTeam/WotlkCore#1548]
**Ссылки и комментарии:**

https://ru.wowhead.com/item=18268/gordok-inner-door-key#comments

**Что работает не так?**

в БД прописан шанс в 85%

**Как должно работать?**

Дроп должен быть 40%
https://wowwiki.fandom.com/wiki/Gordok_Inner_Door_Key

**Шаги для воспроизведения ошибки:**

1. Шаг один
2. Шаг два
3. Шаг три

**Текущее обновление ядра:**

22.03.19

Перенесено https://forum.wowcircle.com/showthread.php?t=646651

**Comment by MedoOf** [comment]
http://web.archive.org/web/20100409153825/https://wowhead.com/npc=14326 - 94%

**Comment by Kodekc** [comment]
Будет установлен 100% шанс выпадения. Изменения будут применены в ближайшем обновлении
