### ISSUE TITLE
[Рейд] - Наксрамас

### ISSUE THREAD

**Issue by kalipsa988** [VirginTeam/WotlkCore#1549]
**Ссылки и комментарии:**

https://ru.wowhead.com/naxxramas#comments

**Что работает не так?**

доступ на второй этаж должен открываться до убийства 4х кварталов инста, то есть доступен сразу

**Как должно работать?**

Доступ на второй этаж должен открываться после убийства 4х кварталов инста

**Шаги для воспроизведения ошибки:**

1. Зайти
2. Тпшнуться на второй
3. Шаг три

**Текущее обновление ядра:**

22.03.19

**Comment by Santaria** [comment]
Из описания патча 3.3.0:
> Чтобы телепортироваться к Сапфирону, больше не нужно убивать последних боссов во всех крыльях подземелья. Теперь с помощью шаров телепортации игроки могут свободно переноситься в Логово Сапфирона и обратно.
