### ISSUE TITLE
Квест "побег из Среброречья"

### ISSUE THREAD

**Issue by Feelini** [VirginTeam/WotlkCore#1556]
**Ссылки и комментарии:**

Квест <a href="https://ru.wowhead.com/quest=12308/%D0%BF%D0%BE%D0%B1%D0%B5%D0%B3-%D0%B8%D0%B7-%D1%81%D1%80%D0%B5%D0%B1%D1%80%D0%BE%D1%80%D0%B5%D1%87%D1%8C%D1%8F" target="_blank">"побег из Среброречья"</a>

**Что работает не так?**

После того, как персонаж запрыгивает на коня, ничего не происходит, а если после этого спрыгнуть с него, то конь начинает атаковать.

**Как должно работать?**

После того, как запрыгиваешь на коня, он должен начать движение к "Приюту Янтарной сосны", а игрок в это время отбивается от вурдалаков, используя способности коня.

**Шаги для воспроизведения ошибки:**

1. Взять квест.
2. Освободить из клетки пленника.
3. Запрыгнуть вместе с ним на коня.
4. Конь не начинает движения.
4. Спрыгнуть с коня.

**Текущее обновление ядра:**

Build 249 2019-03-25 12:59:20. Logon 3.

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by ForesterDev** [comment]
Исправлено
