### ISSUE TITLE
[Предмет] ID 46761 - Стремительный красный крылобег

### ISSUE THREAD

**Issue by Senatyan** [VirginTeam/WotlkCore#1557]
https://ru.wowhead.com/item=46761
https://ru.wowhead.com/item=46751

**Что работает не так?**
В НПЦ http://db.logon3.com/?npc=33557 находятся 2 https://ru.wowhead.com/item=46761 и https://ru.wowhead.com/item=46751. 

**Как должно работать?**

Должен быть один только https://ru.wowhead.com/item=46751, а https://ru.wowhead.com/item=46761/ нужно удалить из НПЦ http://db.logon3.com/?npc=33557

https://ru.wowhead.com/item=46751 - должен быть из - за того, что комментарии в нём идут с патча 3.1.2 и скриншоты с 2009 года. У https://ru.wowhead.com/item=46761/ нету скриншотов и комментариев. Пускай https://ru.wowhead.com/item=46761/ не доступен игрокам, его могли бы дать подержать в ПТР как это было с https://ru.wowhead.com/item=84728/ там мои скриншоты и мой комментарии с 14 года. 

**Шаги для воспроизведения ошибки:**

1. Шаг один
2. Шаг два
3. Шаг три

29.03.2019г.

**Comment by Kodekc** [comment]
Предмет 46761 будет удалён из продажи данного торговца. Изменения будут применены в ближайшем обновлении.
