### ISSUE TITLE
[Задание] ID 12702 - Куриная вечеринка

### ISSUE THREAD

**Issue by Julia987** [VirginTeam/WotlkCore#1559]
**Ссылки и комментарии:**

Проблема с мобами по заданию [Куриная вечеринка](http://db.logon3.com/?quest=12702)

**Что работает не так?**

 [Сбежавшая курица](http://db.logon3.com/?npc=28161#abilities) не ресается или ресается очень долго, т.к. четвертый день не могу их застать.

**Как должно работать?**

Если верить базе даных логона 3, курица должна ресаться каждые 5 сек.

**Шаги для воспроизведения ошибки:**

1. Шаг один
2. Шаг два
3. Шаг три

**Текущее обновление ядра:**

Logon 3 WowCircle Development
Build 249 2019-03-25 12:59:20   +0400

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by gmRial** [comment]
НПЦ находится под текстурами.

**Comment by Kodekc** [comment]
Должно быть исправлено в Build 250. Перепроверьте

**Comment by Julia987** [comment]
Что-то все равно нету. 2 нашла и все, больше нет, новые не появляются.
