### ISSUE TITLE
[Заклинание] ID 43939 - Молитва стойкости

### ISSUE THREAD

**Issue by kalambyr18** [VirginTeam/WotlkCore#1561]
**Ссылки и комментарии:**

https://ru.wowhead.com/spell=43939/%D0%BC%D0%BE%D0%BB%D0%B8%D1%82%D0%B2%D0%B0-%D1%81%D1%82%D0%BE%D0%B9%D0%BA%D0%BE%D1%81%D1%82%D0%B8

**Что работает не так?**

Баф сбрасывается после прохождения подземелья.

**Как должно работать?**

Не должен сбрасываться.

**Шаги для воспроизведения ошибки:**

1. Бафнуть выносливость пристом в подземелье .
2, Пройти и выйти из подземелья .

**Текущее обновление ядра:**

249

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by kalipsa988** [comment]
Такой маразм сделали не давно
Группы:

- теперь при ливе из группы/рейда с игрока будут сниматься рейдовые бафы, также с других игроков будут сниматься бафы от ливнувшего игрока
- убрано отображение ника лутера при FFA луте

**Comment by ForesterDev** [comment]
https://www.youtube.com/watch?v=S2znqLUQZzo&feature=youtu.be&t=1m28s близзлайк
