### ISSUE TITLE
[Достижение] ID1785 Ужин вам не нужен

### ISSUE THREAD

**Issue by cptmarvel** [VirginTeam/WotlkCore#1562]
**Ссылки и комментарии:**

http://db.logon3.com?achievement=1785
 

**Что работает не так?**

После установки сытного угощения "Пир на весь мир" на полях боя, ничего не происходит, достижение не выполняется.

**Как должно работать?**

После установки сытного угощения "Пир на весь мир" на полях боя, достижение должно выполняться.

**Шаги для воспроизведения ошибки:**

1. Зарегистрировать любое из перечисленных полей боя
2. Поставить "Пир на весь мир"
3. Посмотреть, как ничего не происходит

**Текущее обновление ядра:**

Build 251 2019-04-02 14:55:59 +0400

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by Kodekc** [comment]
На всех полях боя не засчитывает критерий или на каком-то конкретном?

**Comment by cptmarvel** [comment]
На всех не засчитывает

**Comment by ForesterDev** [comment]
![image](https://user-images.githubusercontent.com/11771800/55936994-e7ed4c80-5c48-11e9-8266-6a7dc9d10340.png)
Не могу подтвердить

**Comment by cptmarvel** [comment]
На остальных вы пробовали? И я за орду играю, может это значение имеет какое-то?

**Comment by ForesterDev** [comment]
Ну вы же написали, что на всех. Был взят случайный бг и баг не воспроизвелся. Нужно конкретизировать условия для проверки

**Comment by ForesterDev** [comment]
![image](https://user-images.githubusercontent.com/11771800/58954290-cbcddd80-87a9-11e9-93d9-a69a9b6555f0.png)
Работает
