### ISSUE TITLE
Каменная кожа

### ISSUE THREAD

**Issue by Yabanan** [VirginTeam/WotlkCore#1563]
**Ссылки и комментарии:**

https://wowroad.info/?spell=5810#used-by-npc что то по типу вот этого ...

**Что работает не так?**

Не знаю почему, не могу выяснить, но появляется на персонаже. Антиеррор не помогает. Оно приходит иногда по неизвестным обстоятельствам. 

**Как должно работать?**

Его вообще не должно быть.

**Шаги для воспроизведения ошибки:**

1. Шаг один: Чаще всего появляется когда убиваешь мобов/игроков на ОЛО и потом он появляется на бг (убежать от кого то с таким дебафом просто нереально)
2. Шаг два: Отхватывать люлей
3. Шаг три: Ресаться на кладбоне, идти биться, получить дебаф, умереть.

**Текущее обновление ядра:**

Обновление ядра на 8.04.19

![WoWScrnShot_040719_230405](https://user-images.githubusercontent.com/27548782/55686946-8c456980-5991-11e9-918e-2c890b1a780a.jpg)

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by ForesterDev** [comment]
В комбатлоге есть информация, кто накладывает данный спелл?

**Comment by Kodekc** [comment]
Нет ответа от автора репорта. Закрыт, как неактивный.
