### ISSUE TITLE
[Игровая механика] Отправка золота на другую фракцию (Через фамильные предметы)

### ISSUE THREAD

**Issue by Santaria** [VirginTeam/WotlkCore#1567]
**Ссылки и комментарии:**

https://eu.battle.net/forums/ru/wow/topic/1622905086#post-6

![Alt text](https://cdn.discordapp.com/attachments/412316469721038858/566111630363066388/3345.png "Optional title")

**Что работает не так?**

На данный момент можно переслать золото на своего персонажа из другой фракции, если отправить его вместе с фамильным предметом. 

**Как должно работать?**

Золото не должно пересылаться на другую фракцию через почту. Возможность пересылки золота через фамильные предметы является багом.

**Текущее обновление ядра:**

Build 252

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by Rorshah** [comment]
сразу с этим багом нужно будет пофиксить процент на ауке.
Иначе передать золото на другую фракцию с налогом 15% - это будет
бунт.

Не вижу причин исправлять данный баг в условиях что в остальном, касающегося экономики, у нас совсем не как оф-сервер.

**Comment by Santaria** [comment]
Дополнительный вывод золота из игрового мира в целом положительно скажется на игровой экономике. 
Касательно процентов на аукционе. Мое мнение, было бы неплохо вернуть старый внутрифракционный аукцион с 5% комиссией, а в дополнении к нему поставить представителей гоблинского (межфракционного) аукциона в столицах.

**Comment by Rorshah** [comment]
Внутрифракционные аукционы на этом сервере не актуальны.
Количество слотов в орде будет раза в полтора меньше чем на данный момент
на общем ауке.
Альянсовский аук будет практически пустовать.

Про дополнительный вывод говорят уже лет пять. Что бы не делали с ним,
на игру это не влияет никак. Переоцененная проблема.

**Comment by Santaria** [comment]
Ну и если рассматривать этот баг, как "фичу сервера", то тогда возможно стоит без всяких танцев с бубнами разрешить передачу голды/предметов с фракции на фракцию. Тогда заодно и про аук ботов ныть не будут, из-за того, что "они у кого-то там что-то украли". Но Кодекс уже говорил, что он против такого, а значит это баг и его нужно чинить.

**Comment by Rorshah** [comment]
Этот баг в связке с 15%. Он компенсирует это нововведение.
Если его починить = сделать сервер еще хуже.

**Comment by Kodekc** [comment]
Это не ошибка, можно назвать "особенностью". На счёт отправки предметов/золота с фракции на фракцию, мы подумаем, как это сделать, чтоб и пользователям удобно было и чтоб серверу не накладно, а репорт этот закрою
