### ISSUE TITLE
[Игровая механика] Возможность летать без маунта

### ISSUE THREAD

**Issue by Santaria** [VirginTeam/WotlkCore#1568]
**Что работает не так?**

При помощи летающего маунта и некоторых типов ландшафта (мелководье и некоторые другие) можно забагать персонажа так, что он будет летать самостоятельно, без маунта. В этом состоянии полета персонаж может использовать использовать заклинания, атаковать и т.д., а также летать в некоторых локациях, которые не предназначены для полетов (Остров Кель`Данас, начальные локации эльфов крови и дренеев)

**Шаги для воспроизведения ошибки:**

1) Необходимо найти точку в Запределье или Нордсколе, в которой персонажа сбрасывает с маунта, но в этой же точке можно снова призвать его. Обычно это границы между сушей и водой.

2) Призываем летающего маунта и в момент окончания каста взлетаем в воздух. Если все сделано правильно, то персонажа сбросит с маунта, но флаг полета сохранится на нем.

**Текущее обновление ядра:**

Build 252
Предположительно баг появился после недавних обновлений геодаты.

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by Kodekc** [comment]
Нужен пример такой точки для теста

**Comment by Santaria** [comment]
![Alt text](https://cdn.discordapp.com/attachments/412316469721038858/566149866187653130/WoWScrnShot_041219_123647.jpg "Optional title")

**Comment by Kodekc** [comment]
Любая точка в Зангартопи, где идёт соединение земли и воды?

**Comment by Santaria** [comment]
Да, почти любая. И не только в Зангартопи.

**Comment by Santaria** [comment]
Вот в Шаттрате аналогично.
![Alt text](https://cdn.discordapp.com/attachments/412316469721038858/566151595738267658/WoWScrnShot_041219_124345.jpg "Optional title")

**Comment by Kodekc** [comment]
Не удаётся воспроизвести

**Comment by Santaria** [comment]
https://youtu.be/2f8XWjKdykY

**Comment by SanFalkon** [comment]
баг воспроизводится, не только в загрантопи, но и в Норде, эффект возможно отменить только после повторного оседлания маунта, иначе куда б не телепортировался - эффект сохраняется. Работает только в локациях, где возможно использовать летающего маунта, возможно чать проблемы как раз в этом, так как в локах, гдне нет возвожности оседлать летающего маунта, баг не воспроизводится.

**Comment by SanFalkon** [comment]
https://youtu.be/2qWYwD-8jYE
Сегодняшнее воспроизведение

**Comment by Santaria** [comment]
Все видеопруфы фейк, не воспроизводится

**Comment by ForesterDev** [comment]
Исправлено
