### ISSUE TITLE
Репутация с Алдорами/Провидцами

### ISSUE THREAD

**Issue by darling89** [VirginTeam/WotlkCore#1571]
**Ссылки и комментарии:**

Добавьте ссылки с wowhead.com или db.logon3.com на проблемные задания, NPC, заклинания и т.д. 

**Что работает не так?** достижение https://ru.wowhead.com/achievement=1205/герой-шаттрата

Фактический результат — тот, который вы наблюдаете 
при репутации "превознесение" после релога-включился режим войны с Алдорами. снять галочку противника нельзя, взять задания также нельзя.
 квесты 
https://ru.wowhead.com/quest=10211/город-света 
https://ru.wowhead.com/quest=10554/ишана были выполнены
персонаж Мардгир (орда) также Имрахиль, Агасфер

**Как должно работать?** фракция должна быть дружественной, режим войны не должен активироваться спонтанно.

Ожидаемый результат — то, чего вы ожидали при выполнении ваших действий. Процесс правильной работы:

**Шаги для воспроизведения ошибки:**

1. Шаг один
2. Шаг два
3. Шаг три

**Текущее обновление ядра:**
Build 252 2019-04-08 11:01:49 +0400

Можно посмотреть в игре, введите в чат команду .server info и скопировать строку начиная с Build с номером и датой. Не забывайте указывать, Live Server или PTR Server, где проводилось тестирование.

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by ForesterDev** [comment]
Проверьте еще раз на своих персонажах

**Comment by Volendelon** [comment]
Аналогичная проблема, не снимается галочка противник с Алдорами

**Comment by Santaria** [comment]
С провидцами аналогичная проблема

**Comment by chaosweaver407121** [comment]
Аналогичная проблема, автоматически устанавливается статус "Противник" сразу после релога либо использования камня возвращения. и галочку снять невозможно.

**Comment by ForesterDev** [comment]
Исправлено
