### ISSUE TITLE
[NPC] ID 17307 Вазруден Глашатай

### ISSUE THREAD

**Issue by MrShirokow** [VirginTeam/WotlkCore#1573]
**Ссылки и комментарии:**
http://db.logon3.com/?npc=17307

**Что работает не так?**
Босс http://db.logon3.com/?npc=17307.

Фактический результат — тот, который вы наблюдаете 
На полуострове адского пламени в подземелье "Бастион адского пламени" периодически багается ласт босс http://db.logon3.com/?npc=17307. Он взлетает наверх, после чего проваливается в текстуры. Ссылки на скрины:
https://ibb.co/1sWKdjx (дракон ещё сверху)
https://ibb.co/X5gqKgF (дракон уже провалился в текстуры)
Помимо того, если босс не забагался и удалось сделать килл, не засчитывает килл для квеста на монету трансмодификации http://db.logon3.com/?quest=15010.

**Как должно работать?**
При прохождении подземелья, подходя к ласт боссу, дракон должен спуститься на землю, после чего вступить в бой. После завершения боя должен появиться сундук с лутом и всё отлично.

Ожидаемый результат — то, чего вы ожидали при выполнении ваших действий. Процесс правильной работы

**Шаги для воспроизведения ошибки:**

1. Шаг один
2. Шаг два
3. Шаг три

**Текущее обновление ядра:**
Logon 3 WowCircle Development
[00:47:20] Последнее обновление ядра: TrinityCore rev. Build 253 2019-04-15 14:05:56 +0400 (Unix, Release, Static)

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by ForesterDev** [comment]
Исправлено
