### ISSUE TITLE
Приказ хозяина

### ISSUE THREAD

**Issue by nreiv** [VirginTeam/WotlkCore#1575]
**Ссылки и комментарии:**

http://db.logon3.com/?spell=53271

**Что работает не так?**

1. Не снимает замедление от "Правосудие справедливости" http://db.logon3.com/?spell=53407 и не делает ханта невосприимчивым к повторному использованию по нему этой джаги

**Как должно работать?**

"Питомец делает попытку **снять все оплетающие и затрудняющие передвижение эффекты с себя и хозяина, делая обоих невосприимчивыми к подобным эффектам на 4 сек**.."

1. Приказ хозяина должен снимать все затрудняющие передвижение эффекты

**Шаги для воспроизведения ошибки:**

1. Поставить дуэль любому ретро-паладину с шмом, напасть и посмотреть, как он будет бежать за хантом спамя "Правосудие справедливости" http://db.logon3.com/?spell=53407

**Текущее обновление ядра:**

Live Server Build 253 2019-04-15 14.05.56 +0400 

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by ForesterDev** [comment]
https://github.com/VirginTeam/WotlkCore/issues/1577

**Comment by kalipsa988** [comment]
Головокружение от аспекта ханта не снимает, но должно ли ?
