### ISSUE TITLE
Слияние с Тьмой

### ISSUE THREAD

**Issue by nreiv** [VirginTeam/WotlkCore#1576]
**Ссылки и комментарии:**

http://db.logon3.com/?spell=47585

**Что работает не так?**

1. Не снимает замедление от "Правосудие справедливости" http://db.logon3.com/?spell=53407 и не делает приста невосприимчивым к повторному использованию по нему этой джаги

**Как должно работать?**

"Вы растворяетесь во Тьме. Весь получаемый вами урон уменьшается на 90%. Во время действия этого заклинания вы не можете атаковать или читать заклинания, но восполняете 6% маны раз в 1 сек. Время действия – 6 сек.. Можно использовать, даже если на вас наложены эффекты оглушения, страха или немоты. **При использовании рассеивает сковывающие и затрудняющие движение эффекты, а также дает невосприимчивость к ним на время действия заклинания.**"

1. Слияние с Тьмой должно снимать все затрудняющие передвижение эффекты

**Шаги для воспроизведения ошибки:**

1. Поставить дуэль любому ретро-паладину с шмом, напасть и посмотреть, как он будет бежать за пристом/прятаться от него за объектами спамя "Правосудие справедливости" http://db.logon3.com/?spell=53407

**Текущее обновление ядра:**

Live Server Build 253 2019-04-15 14.05.56 +0400 

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by ForesterDev** [comment]
https://github.com/VirginTeam/WotlkCore/issues/1577
