### ISSUE TITLE
Зелье свободы действий

### ISSUE THREAD

**Issue by nreiv** [VirginTeam/WotlkCore#1577]
**Ссылки и комментарии:**

http://db.logon3.com/?item=5634

**Что работает не так?**

Не даёт иммунитет к "Правосудие справедливости" http://db.logon3.com/?spell=53407 

**Как должно работать?**

Использование: Наделяет невосприимчивостью к оглушающим и **затрудняющим передвижение эффектам на 30 сек.**. 

**Шаги для воспроизведения ошибки:**

1. Поставить дуэль ретробаблодину/Зайти на бг/Зайти на оло и найти ретробаблодина, прожать банку и посмотреть, как он будет убегать/прятаться за объектами спамя http://db.logon3.com/?spell=53407 

**Текущее обновление ядра:**

Live Server Build 253 2019-04-15 14.05.56 +0400

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by Santaria** [comment]
https://wowwiki.fandom.com/wiki/Judgement_of_Justice?oldid=1875121

>PvP
The movement speed limit of the judged player is not considered a movement impairing effect, meaning acts such as shape shifting and Hand of Freedom will not remove it. This prevents a player from going above their normal run speed. Thus, for instance, a Druid who is affected by the Judgement will not go any faster than the normal run speed if they shift into Travel Form, a Rogue who uses Sprint will receive no speed boost, and any player riding a mount will receive no speed bonus from doing so.

**Comment by ForesterDev** [comment]
Работает правильно. Правосудие справедливости не является эффектом затрудняющим движение, а это эффект ограничения максимальной скорости движения
