### ISSUE TITLE
Ледяная глыба

### ISSUE THREAD

**Issue by nreiv** [VirginTeam/WotlkCore#1578]
**Ссылки и комментарии:**

http://db.logon3.com/?spell=45438

**Что работает не так?**

При использовании глыбы не снимается/либо не даётся иммун к "Волшебный огонь" http://db.logon3.com/?spell=770 - что делает невозможным использование "Невидимость" http://db.logon3.com/?spell=66

**Как должно работать?**

Вы оказываетесь в середине ледяной глыбы, **которая защищает вас от всех** физических и **магических атак на 10 сек**.., но в течении этого времени вы не можете никого атаковать, двигаться или применять заклинания.

**Шаги для воспроизведения ошибки:**

1. Нажать магом айсблок
2. Спамить друидом фиерифаер

**Текущее обновление ядра:**

Live Server Build 253 2019-04-15 14.05.56 +0400

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by ForesterDev** [comment]
Исправлено
