### ISSUE TITLE
Анимация AOE эффектов

### ISSUE THREAD

**Issue by nreiv** [VirginTeam/WotlkCore#1579]
**Ссылки и комментарии:**

Ссылки на все способности давать не имеет смысла, однако суть дела касается следующих абил: лужа дк, лужа баблодина, флейр ханта, ловушки ханта с АОЕ эффектом и прочие ништяки.

**Что работает не так?**

Вместо того, чтобы лужи заняли своё место на земле, они под неё проваливаются, ввиду чего их не видно как ханту/баблодину/дк/магу/локу и т.д, так и их врагам

**Как должно работать?**

АОЕ эффекты не должны проваливаться под текстуры. как пример, смерть и разложение здорового человека - https://www.wowhead.com/spell=172965/death-and-decay#screenshots:id=483130

**Шаги для воспроизведения ошибки:**

1. Использовать лужу баблодина
2. Использовать дэд ДК
3. Использовать флейр ханта или заюзать его AOE ловушки так, чтобы они прокнули
4. и т.д.

p.s знатокам на заметку: если близзард создают абилу, они всегда дают другим игрокам антиабилу. Если близзард рисуют анимацию спела, то не для того, чтобы она проваливалась под текстуры 

**Текущее обновление ядра:**

Live Server Build 253 2019-04-15 14.05.56 +0400

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by ForesterDev** [comment]
![image](https://user-images.githubusercontent.com/11771800/56562650-edd51d00-65ba-11e9-83cf-1598e8a28b4e.png)
![image](https://user-images.githubusercontent.com/11771800/56562676-fa597580-65ba-11e9-90c4-841436f3507a.png)
![image](https://user-images.githubusercontent.com/11771800/56562720-14935380-65bb-11e9-9461-170d038b396d.png)

**Comment by ForesterDev** [comment]
Репорт не воспроизводится
