### ISSUE TITLE
[Задание]  ID 9805 Благословение Возжигателя

### ISSUE THREAD

**Issue by Volendelon** [VirginTeam/WotlkCore#1580]
**Ссылки и комментарии:**

http://db.logon3.com/?quest=9805

**Что работает не так?**

Не поджигается Южная лаучуга

**Как должно работать?**

Зашел в лачугу - поджёг - выполнил.

**Шаги для воспроизведения ошибки:**

-
**Текущее обновление ядра:**

Build 253 2019-04-15 14:05:16 +0400

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by ForesterDev** [comment]
Исправлено
