### ISSUE TITLE
[Задание] ID 10496 - Прощальные слова Антиона

### ISSUE THREAD

**Issue by chaosweaver407121** [VirginTeam/WotlkCore#1581]
**Ссылки и комментарии:**
http://db.logon3.com/?quest=10496

**Что работает не так?**
Сразу выполнив предыдущий квест "Вызов" и завершив его, оказалось, что следующее задание "Прощальные слова Антиона" у квестодателя отсутствует. Однако единственным требованием для получения задания, является выполнение предыдущего.

Фактический результат — тот, который вы наблюдаете 
Для шаманов данный квест по неизвестным причинам не предлагается, хотя остальные классы его легко получают.

**Как должно работать?**
Для всех классов цепочка заданий должна быть доступна к выполнению

Ожидаемый результат — то, чего вы ожидали при выполнении ваших действий. Процесс правильной работы
Получение задания
**Шаги для воспроизведения ошибки:**

1. Шаг один
2. Шаг два
3. Шаг три

**Текущее обновление ядра:**
Build 253  2019-04-15

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by ForesterDev** [comment]
![image](https://user-images.githubusercontent.com/11771800/58797577-6e068d80-8611-11e9-9036-c9980edba89a.png)
Проверил шаманом - выдает
