### ISSUE TITLE
[Задание] ID 12955 "Унижение соперников"

### ISSUE THREAD

**Issue by penumbra87** [VirginTeam/WotlkCore#1582]
Квест "Унижение соперников" 

https://ru.wowhead.com/quest=12955/%D1%83%D0%BD%D0%B8%D0%B6%D0%B5%D0%BD%D0%B8%D0%B5-%D1%81%D0%BE%D0%BF%D0%B5%D1%80%D0%BD%D0%B8%D0%BA%D0%BE%D0%B2
     
Отсутствует  НПС "Прыгун" которому можно здать квест. 

Отображается на карте месторосположения НПС которому можно здать квест но по факту его там нет.

Хотел бы иметь возможность здать квест.
 
Данный НПС пропал после завершения квеста  
https://ru.wowhead.com/quest=12951/%D0%B8%D0%B7%D0%B2%D0%B5%D1%81%D1%82%D0%B8%D1%8F-%D0%B4%D0%BB%D1%8F-%D0%B1%D0%B0%D1%80%D0%BE%D0%BD%D0%B0.

Просьба сделать возможность завершения данного квеста и взять следующий. 

Спасибо.

**Comment by ruafelianna** [comment]
У меня была аналогичная проблема после открытия Мрачного свода как дружественной локации - данного NPC не было на месте, чтобы начать цепочку квестов на Костяную ведьму.
