### ISSUE TITLE
[Подземелье] ID 209 - Крепость Темного Клыка

### ISSUE THREAD

**Issue by kalambyr18** [VirginTeam/WotlkCore#1583]
**Ссылки и комментарии:**

http://db.logon3.com/?zone=209
http://db.logon3.com/?npc=3850
https://ibb.co/JjDncZj

**Что работает не так?**

Колдун Ашкромб, котор открывает дверь в начале подземелья для дальнейшего прохождения , временами агрится на мобов , убегает за текстуры , дохнет . Либо как в этот раз просто был мертв, когда дверь открыл к нему . 
В итоге подземку не пройти . Это уже не в первый раз . Вы просто откройте дверь и уберите этого нпс оттуда .

**Как должно работать?**

Нпс идет и открывает дверь 

**Шаги для воспроизведения ошибки:**

Зайти в подземку ,пообщаться с нпс .

**Текущее обновление ядра:**

254

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by ForesterDev** [comment]
Исправлено
