### ISSUE TITLE
Наследуемый предмет

### ISSUE THREAD

**Issue by kibukreebok** [VirginTeam/WotlkCore#1584]
Кираса несущего смерть чемпиона

Данный предмет работает неправильно. По порядку.
Так как данный предмет наследуемый кольчужный, на начальных уровнях он должен иметь большое количество брони относительно обычных кольчужных вещей в игре. Тем не менее, вероятнее всего, ему поставлены рейты кожаной брони, так как он сильно проигрывает по показателям кольчужной. Предоставляю скриншот, где сравнивается данная броня 23 уровня и обычная белая кольчуга 5 уровня. Думаю, что более чем понятно, что здесь что-то не то.

Хотелось бы увеличения рейтов до уровня кольчуги, потому что игра на варе(в моем случае), либо пале, становится тяжелее

![WoWScrnShot_051219_221806](https://user-images.githubusercontent.com/50555412/57586801-eba01780-7503-11e9-854c-b567f53b0118.jpg)

**Comment by Santaria** [comment]
Все работает правильно. До 40 уровня этот предмет имеет кожаный тип брони, ибо рассчитан на охотника и шамана, которые не могут носить кольчугу на начальных уровнях.

**Comment by sega693** [comment]
Для латников латы есть (удивительно, да), которые в кольчугу превращаются до 40 лвл. Инта не смутила при покупке?
