### ISSUE TITLE
Талант "Демоническая эгида" не работает

### ISSUE THREAD

**Issue by RomaGol** [VirginTeam/WotlkCore#1585]
**Ссылки и комментарии:**

http://db.logon3.com/?spell=30143 
http://db.logon3.com/?spell=30144
http://db.logon3.com/?spell=30145

**Что работает не так?**

Талант "Демоническая эгида" не увеличивает эффективность заклинаний "Демонический доспех" и "Доспех Скверны", то есть показатели брони не изменяются.

**Как должно работать?**

Увеличение эффективности ваших заклинаний "Демонический доспех" и "Доспех Скверны" на 10%.
Увеличение эффективности ваших заклинаний "Демонический доспех" и "Доспех Скверны" на 20%.
Увеличение эффективности ваших заклинаний "Демонический доспех" и "Доспех Скверны" на 30%.

**Текущее обновление ядра:**

Build 254 2019-04-29 13:26:22 +0400 Live Server 

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by gmRial** [comment]
Проверяйте по фактическому количеству брони в окне с характеристиками персонажа, а не по тултипу.
