### ISSUE TITLE
[Заклинание] ID 59831 - Эликсир Клоаки (Оса)

### ISSUE THREAD

**Issue by Santaria** [VirginTeam/WotlkCore#1586]
**Ссылки и комментарии:**

http://db.logon3.com/?spell=59831

**Что работает не так?**

Если во время действия этого заклинания, использовать способность контроля над другим NPC ("Звериный глаз" охотника, предмет "Пульт управления паровым танком" и т.д.), а затем последовательно отменить сначало баф эликсира, а после баф контроля, то на персонаже сохраняется аура полета от эликсира. 

Таким образом можно летать по всему Нордсколу без каких-либо бафов.

**Шаги для воспроизведения ошибки:**

1. Использовать http://db.logon3.com/?item=44012 до прока http://db.logon3.com/?spell=59831 
2. Использовать предмет http://db.logon3.com/?item=22728 или способность с аналогичным эффектом.
3. Вручную отменить баф http://db.logon3.com/?spell=59831
4. Отменить баф контроля.
5. Попробовать взлететь.

**Текущее обновление ядра:**

Build 254

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by ForesterDev** [comment]
Не воспроизводится

**Comment by Santaria** [comment]
https://youtu.be/WuYGzZnADfc

**Comment by GmAlleria** [comment]
воспроизведите пожалуйста на х1, а не на тесте

**Comment by Santaria** [comment]
На х1 оно воспроизводится ровно таким же образом

**Comment by Santaria** [comment]
Но там, в отличие от теста, если записать видео, то можно получить бан, поэтому лучше не буду этого делать)

**Comment by ForesterDev** [comment]
Исправлено
