### ISSUE TITLE
Задание - Ответный удар (Огненный солнцеворот)

### ISSUE THREAD

**Issue by Volendelon** [VirginTeam/WotlkCore#1593]
**Ссылки и комментарии:**

http://db.logon3.com/?quest=11954

**Что работает не так?**

При взаимодействии с платформой(камень льда) по нажатию на диалог ничего не происходит.

**Как должно работать?**

Нажал на платформу, использовал диалог - призвался нужный НПЦ для квеста.

**Текущее обновление ядра:**

Build 262 2019-06-20 14:27:43 +0400 Logon 3 x1 PvE

**Comment by FilDru** [comment]
http://db.logon3.com/?npc=26216#objective-of
Ссылочка на нужного непися

**Comment by ForesterDev** [comment]
Исправлено
