### ISSUE TITLE
[Задание] ID 11955 - Ахун, Повелитель Холода

### ISSUE THREAD

**Issue by Volendelon** [VirginTeam/WotlkCore#1594]
**Ссылки и комментарии:**

http://db.logon3.com/?quest=11955

**Что работает не так?**

Отсутствует нужный НПЦ для сдачи квеста http://db.logon3.com/?npc=25710#starts в Узилище.

**Как должно работать?**

НПЦ должен стоять в Узилище в пределах проведения праздничного ивента. 

**Текущее обновление ядра:**

Build 262 2019-06-20 14:27:43 +0400 Logon 3 x1 PvE

**Comment by ForesterDev** [comment]
Исправлено
