### ISSUE TITLE
[Задание] ID 11691 - Призовите Ахуна

### ISSUE THREAD

**Issue by Volendelon** [VirginTeam/WotlkCore#1595]
**Ссылки и комментарии:**

http://db.logon3.com/?quest=11691

**Что работает не так?**

Отсутствует объект для сдачи квеста.

**Как должно работать?**

Берете квест, сдаёте его камню льда, призывая тем самым Ахуна. Нужно еще учитывать, что это должно выполняться для 5 человек.

**Текущее обновление ядра:**

Build 262 2019-06-20 14:27:43 +0400 Logon 3 x1 PvE

**Comment by ForesterDev** [comment]
Исправлено
