### ISSUE TITLE
Что с сервером?

### ISSUE THREAD

**Issue by CoH9lgladx** [VirginTeam/WotlkCore#1596]
Здравствуйте уважаемая администрация.
Что с logon3? А точнее с тестовым реалмом(про другие не знаю). Реалм полностью нерабочий. Большинство талантов не прокает, печати паладинов не работают, большинство тринькетов так же не прокают. Будут ли фиксы? Проблема возникла где то недели 2-4 назад.

**Comment by ForesterDev** [comment]
Тест сервер обновлен, проблемы устранены
