### ISSUE TITLE
[Задание] ID15009 - Миссия: Полуостров Адского Пламени (об.)

### ISSUE THREAD

**Issue by Vindenta** [VirginTeam/WotlkCore#1598]
**Ссылки и комментарии:**
http://db.logon3.com/?quest=15009

**Что работает не так?**

Не засчитывает бастионы адского пламени.
При убийстве боса Вазруден  http://db.logon3.com/?npc=17307 именно орка, бос эвейдится.
Либо при убийстве Вазрудена и Назана не засчитывает квест.

**Как должно работать?**

После убийства боса подземелье должно быть засчитано в квест.

**Шаги для воспроизведения ошибки:**

1. Агрим боса
2. Убиваем Вазрудена
3. Бос эвейдится улетая наверх. 

1. Агрим боса
2. Убиваем Вазрудена и Назана
3. Подземелье не засчитывается в квест.

**Текущее обновление ядра:**

Logon 3 WowCircle Development
Последнее обновление ядра: Build 263 2019-06-26 10:35:38 +0400

**Comment by ForesterDev** [comment]
Исправлено
