### ISSUE TITLE
Хприст. Круг исцеления.

### ISSUE THREAD

**Issue by chandlerdima** [VirginTeam/WotlkCore#1599]
**https://ru.wowhead.com/spell=204883/круг-исцеления**

**Сила заклинаний с шмота неверно скалируется на абилке. Отхил от круга исцеления хприста хилит меньше чем должен.**

**На "Круге исцеления" написано: восстанавливает 1293-1429 ед. здоровья. У одетого хприста спд от шмота: 4486 единиц. Таким образом применение круга исцеления должно давать миниум 5779 (1293+4486) ед отхила по одной цели без крита! На практике же "Круг исцеления" дает стабильно ~3865 ед. отхила. И лишь ~5800 при крите!
Так же замечу, что раздетый хприст работает, вроде как, корректно!**

**Шаги для воспроизведения ошибки:**

1. Взять одетого в 6,5 гс хприста.
2. Использовать "Круг исцеления".
3. Посмотреть на отхил.

**Build 263 2019-06-26 10:35:38 +0400**

Основной игровой сервер.

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by Santaria** [comment]
> спд от шмота: 4486
> должно давать (1293+4486)

Это так не работает. У каждого заклинания свой индивидуальный коэфициент для спд/ап

Можешь поставить аддон DrDamage, он рассчитывает каким должен быть урон/исцеление с учетом бафов, талантов и т.д. У меня хприст 70 лвл, часть талантов не взята, но суть думаю понятна:

![Alt text](https://cdn.discordapp.com/attachments/412316469721038858/594376305827512356/65757.png "Optional title")
