### ISSUE TITLE
[Подземелье] Окулус (ID 27654 Дракос Дознаватель)

### ISSUE THREAD

**Issue by gmOverfire** [VirginTeam/WotlkCore#16]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Скриншоты демонстрирующие проблему, выделение проблемных мест с помощью графических редакторов приветствуются. Для описания ошибок, возникающих только в движении, снимите видео **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Неверная работа появляющихся сфер (возможно - http://ru.wowhead.com/spell=50758, http://ru.wowhead.com/spell=50759)

**Что работает не так?**

Скапливается очень много сфер, примерно вдвое больше, чем должно быть.

**Как должно работать?**

Сфер должно быть меньше.
https://www.youtube.com/watch?v=8OqdfJMv0nY#t=0m48s

**Текущее обновление ядра:**

PTR Build 20 2017-04-03 15:25:08 +0400

**Comment by ForesterDev** [comment]
Исправлено, будет применено в обновлении
