### ISSUE TITLE
[Заклинание] ID 49206 - Призыв горгульи

### ISSUE THREAD

**Issue by EksoVio** [VirginTeam/WotlkCore#1600]
**Ссылки и комментарии:**

http://db.logon3.com/?spell=49206

**Что работает не так?**

1. Урон от бомб горгульи занижен, под проками от тринек урон стал меньше, чем ранее.

**Как должно работать?**

1. Урон был примерно в 3 раза выше, что было видно из аддонов по рассчету урона (Skada/Recount) 

**Шаги для воспроизведения ошибки:**

1. Вступить в бой, накопить 60 силы рун и вызвать горгулью.
2. Просмотреть средний урон за один удар горгульи

**Текущее обновление ядра:**

Build 263 2019-06-26 10:35:38 +0400 Live Server

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by ForesterDev** [comment]
Исправлено
