### ISSUE TITLE
[Заклинание] ID 48500 - Семя жизни

### ISSUE THREAD

**Issue by Santaria** [VirginTeam/WotlkCore#1610]
**Ссылки и комментарии:**

http://db.logon3.com/?spell=48500

**Что работает не так?**

Источником исцеления на данный момент является цель, на которую наложено "Семя жизни"

**Как должно работать?**

Источником исцеления должен быть друид, который повесил "Семя жизни"

**Текущее обновление ядра:**

Build 263

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by zyxellgit** [comment]
после той самой обновы, писал в дискорд про орехи шамана и семечку друида, шамана починили а на дру забили. забавно, вроде сами просили в диск отписывать про сломаное обновой
