### ISSUE TITLE
[Подземелье] Очищение Стратхольма (начальный эвент)

### ISSUE THREAD

**Issue by Santaria** [VirginTeam/WotlkCore#1614]
**Ссылки и комментарии:**

http://db.logon3.com/?zone=4100

**Что работает не так?**

1) Отсутствует короткий вариант сценки запуска Артаса.

![Alt text](https://cdn.discordapp.com/attachments/412316469721038858/597653589489483796/WoWScrnShot_070819_105755.jpg "Optional title")

2) Глючно работает http://db.logon3.com/?item=37888 , для очищения некоторых ящиков нужно подойти к ним вплотную.

**Текущее обновление ядра:**

Build 263

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by zyxellgit** [comment]
https://github.com/VirginTeam/WotlkCore/issues/319#issue-238665576

**Comment by Santaria** [comment]
Дубликат
