### ISSUE TITLE
[Задание]Не засчитываются инсты в квестах на монету трансмогрификации

### ISSUE THREAD

**Issue by DarinkaSmile** [VirginTeam/WotlkCore#1621]
**Ссылки и комментарии:**

http://db.logon3.com/?quest=15010
http://db.logon3.com/?quest=15017
**Что работает не так?**

Пока заметила только в этих двух кв. При прохождении "Миссия: Полуостров Адского Пламени" не засчитываются Бастионы Адского Пламени. При прохождении "Миссия: Разные подземелья Burning Crusade" не засчитывается Терраса Магистров.

**Как должно работать?**

Данные инсты должны помечаться пройденными в квесте после убийства всех боссов.

**Шаги для воспроизведения ошибки:**

1. Взять квест
2. Пойти в нужный инст (Бастионы/Терраса)
3. Убить всех боссов и обнаружить, что инст не засчитался в квесте

**Текущее обновление ядра:**

Build 263 2019-06-26 10:35:38 +0400
Live Server

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by ForesterDev** [comment]
Исправлено
