### ISSUE TITLE
[Предметы] Лут с мобов в подземельях Wotlk

### ISSUE THREAD

**Issue by Santaria** [VirginTeam/WotlkCore#1622]
**Что работает не так?**

Лут с мобов перемешан с разных режимов сложности. Так в обычках низкого уровня с мобов могут падать предметы 77-80 уровня, а в героиках наоборот 68+

**Как должно работать?**

В подземельях обычного режима сложности должны падать предметы в диапазоне от минимального рекомендуемого уровня и плюс 2-3 уровня (Например Крепость Утгард (об) с мобов должны падать предметы 68-71 уровня). В героиках 77-80 уровня.

![Alt text](https://cdn.discordapp.com/attachments/412316469721038858/597700014613069824/13.png "Optional title")

**Текущее обновление ядра:**

Build 263

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by Santaria** [comment]
Также в обычках не должно быть эпик бое 80 уровня.
В героиках Яме, Кузне, Залах необходимо снизить шанс дропа рукояти - https://github.com/VirginTeam/WotlkCore/issues/1266

**Comment by ForesterDev** [comment]
Нужно более подробные сведения о предметах и мобах. Лута очень много и перелопачивать весь это бесполезное дело
