### ISSUE TITLE
[Предмет] ID 24106 - Толстое ожерелье из оскверненной стали

### ISSUE THREAD

**Issue by Pbellumm** [VirginTeam/WotlkCore#1623]
**Ссылки и комментарии:**

[Толстое ожерелье из оскверненной стали](http://db.logon3.com/?item=24106)
[Скриншот](https://user-images.githubusercontent.com/52411469/60882092-d28bbc80-a24f-11e9-9ebe-1bbe208a8bc8.jpg)

**Что работает не так?**

Отображаемая стоимость продажи 1с.
Фактическая стоимость продажи 3g 91s 22c
Стоимость выкупа отображается верная.

**Как должно работать?**

Стоимость продажи 3g 91s 22c

**Текущее обновление ядра:**

Build 264 2019-07-08 14:17:10 +0400 Logon 3 x1 PvE

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by ForesterDev** [comment]
Баг клиента
