### ISSUE TITLE
[Заклинание] ID 20216 - Божественное одобрение

### ISSUE THREAD

**Issue by Gooldark** [VirginTeam/WotlkCore#1625]
**Ссылки и комментарии:**

 ID 20216 - Божественное одобрение(http://db.logon3.com/?spell=20216)

**Что работает не так?**

Не всегда дает 100% шанс крита. Сам баф появляется всегда, иногда нет крита от бафа. 

**Как должно работать?**

После использования спела следующее использование Света небес, Вспышки Света или Шока небес должно быть всегда критическим

**Текущее обновление ядра:**

Баг появился ~3 недели назад от 15.07.2019

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by Fxckinmad** [comment]
по состоянию на 24.06.2020 все еще не работает, спустя год
