### ISSUE TITLE
[Задание] ID 12631 - Приглашение (Зул`драк)

### ISSUE THREAD

**Issue by adamant1142** [VirginTeam/WotlkCore#1628]
**Ссылки и комментарии:**
https://ru.wowhead.com/item=38660/колье-нежизни#starts 
не падает с указанных нпс, 4 дня фарма сотни убитых мобов

**Что работает не так?**

Из-за 0% выпадения квеститема нельзя начать цепочку квестов
https://ru.wowhead.com/quest=12631/приглашение

**Как должно работать?**

раньше падал с 2-3 моба

**Шаги для воспроизведения ошибки:**

1. исправить, чтобы выпадал квеститем

"Logon3 Wowcircle"  3.3.5 х1 PVE

**Comment by GmAlleria** [comment]
Выполните или сдайте задание Очищение Драк'Тарона и выбивайте итем
