### ISSUE TITLE
[Задание] ID 9254 - Упрямая ученица

### ISSUE THREAD

**Issue by mikki33** [VirginTeam/WotlkCore#1631]
**Ссылки и комментарии:**

http://db.logon3.com/?quest=9254

**Что работает не так?**

Не возможно сдать задание. Npc стоит на своем месте, а иконки сдачи задания нету.

**Как должно работать?**

Приходим к npc и сдаем задание.

**Шаги для воспроизведения ошибки:**
1.Взять задание.
2. Прийти к нпс на место сдачи.
3. Убедится в том, что задание не сдается.

**Текущее обновление ядра:**
Build 266 2019-07-11 17:32:57 +0400

**Comment by Santaria** [comment]
https://github.com/VirginTeam/WotlkCore/issues/638
