### ISSUE TITLE
[Задание] ID 30 - Испытание Морского Льва

### ISSUE THREAD

**Issue by mikki33** [VirginTeam/WotlkCore#1635]
**Ссылки и комментарии:**

http://db.logon3.com/?quest=30

**Что работает не так?**

Невозможно облуать сундук на дне моря по заданию.

**Как должно работать?**

Возможность облутать сундук на дне моря.

**Текущее обновление ядра:**

Build 267 2019-07-29 12:18:21 +0400 Logon 3 x1 PvE

**Comment by GmAlleria** [comment]
Задание рабочее, отмените и возьмите заново
