### ISSUE TITLE
Не открывается трейд у интенданта Серебряного Авангарда в Ледяной Короне 

### ISSUE THREAD

**Issue by Mymellor** [VirginTeam/WotlkCore#1638]
**Ссылки и комментарии:**

https://ru.wowhead.com/npc=34885
(интендант Серебряного Авангарда в Ледяной Короне)

**Что работает не так?**

Не открывается трейд. При наведении на неё мышкой появляется значок трейда, но собственно обмена не происходит. Как видно на 1м скриншоте, она только болтает и всё.

**Как должно работать?**

Собственно, должен открываться трейд с покупкой за Печати Чемпиона (https://ru.wowhead.com/currency=241) всяких предметов, в том числе и наследуемых.

**Шаги для воспроизведения ошибки:**

2й скрин с отсутствием трейда у интенданта (на котором также видно фул репу с ними), скрин с орчонком, т.е. раньше-то трейд был точно!

**Текущее обновление ядра:**

 Build 267 2019-07-29 12:18:21 +0400

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

![WoWScrnShot_080319_222937](https://user-images.githubusercontent.com/53703413/62424781-5d8b9580-b6dc-11e9-9cb5-582fb3c15714.jpg)

![WoWScrnShot_080319_224222](https://user-images.githubusercontent.com/53703413/62424785-62504980-b6dc-11e9-8919-8a42905007e1.jpg)

**Comment by Santaria** [comment]
Проверила, все работает. Ты достижение превозносимого чемпиона Орды получил со званием "Крестоносца"? Этот интендант только для них.

**Comment by Mymellor** [comment]
Превозносимого чемпиона Орды у меня нет, но раньше-то трейд работал у этого вендора! Я покупал уже у неё наследки для твинов. 
Ачивка вот на скрине "по поням" - у того же интенданта итем покупается ведь

![WoWScrnShot_080419_220935](https://user-images.githubusercontent.com/53703413/62428028-be2ec880-b704-11e9-82bc-0a8a4f5fedd1.jpg)

**Comment by Santaria** [comment]
То, что можно было покупать у нее без ачивки, было багом и его исправили.
