### ISSUE TITLE
[Игровая механика] Восстановление гербовых накидок

### ISSUE THREAD

**Issue by Santaria** [VirginTeam/WotlkCore#1639]
**Что работает не так?**

[Этот](http://db.logon3.com/?npc=28776) и другие аналогичные NPC не восстанавливают накидки, выброшенные из сумок. 

Проверялось на тестовом сервере, на [Гербовой накидке летних небес](http://db.logon3.com/?item=35279)

**Как должно работать?**

Должны восстанавливаться некоторые накидки, которые привязаны к определенным квестам/достижениям. Список этих накидок присутствует во вкладке заклинаний NPC. 

**Текущее обновление ядра:**

Build 268

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by ForesterDev** [comment]
![image](https://user-images.githubusercontent.com/11771800/65883523-439ec400-e3a8-11e9-8461-a3a5a16ef24d.png)
Восстанавливает, для восстановления летних накидок требуется чтобы был выполнен квестhttp://db.logon3.com/?quest=11972
