### ISSUE TITLE
[Задание] ID 4022 - Вкус пламени

### ISSUE THREAD

**Issue by Sinvoid43** [VirginTeam/WotlkCore#1641]
**Ссылки и комментарии:**

https://ru.wowhead.com/quest=4022/%D0%B2%D0%BA%D1%83%D1%81-%D0%BF%D0%BB%D0%B0%D0%BC%D0%B5%D0%BD%D0%B8

**Что работает не так?**

НПС не выдаёт задание (над ним висит восклицательный знак, но на миникарте знака нет)

**Как должно работать?**

НПС выдаёт задание

**Шаги для воспроизведения ошибки:**

1. Шаг один Выполнить все задания предшествующие данному в цепочке квестов
2. Шаг два Постараться взять квест у НПС со шкурой
3. Шаг три Постараться взять квест у НПС без шкуры

**Текущее обновление ядра:**

23.07.2019 build 232 (wow circle x5)

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by ForesterDev** [comment]
![image](https://user-images.githubusercontent.com/11771800/66641012-f97cd480-ec2a-11e9-8fb9-32127e81b564.png)
на х1 работает
