### ISSUE TITLE
[Задание] ID 4903 - Приказ полководца

### ISSUE THREAD

**Issue by Sinvoid43** [VirginTeam/WotlkCore#1642]
**Ссылки и комментарии:**

https://ru.wowhead.com/quest=4903/%D0%BF%D1%80%D0%B8%D0%BA%D0%B0%D0%B7-%D0%BF%D0%BE%D0%BB%D0%BA%D0%BE%D0%B2%D0%BE%D0%B4%D1%86%D0%B0

**Что работает не так?**

НПС(http://db.logon3.com/?npc=9077) не даёт задание(или предмет который выдает это задание https://ru.wowhead.com/item=12563/%D0%BF%D1%80%D0%B8%D0%BA%D0%B0%D0%B7-%D0%BF%D0%BE%D0%BB%D0%BA%D0%BE%D0%B2%D0%BE%D0%B4%D1%86%D0%B0-%D0%BA%D0%BB%D0%B8%D0%BD%D0%BE%D0%B7%D1%83%D0%B1%D0%B0)

**Как должно работать?**

НПС даёт задание(или предмет который даёт это задание при беседе с ним)

**Шаги для воспроизведения ошибки:**

1. Шаг один Постараться взять квест или предмет на квест у нпс.
2. Шаг два На миникарте отображается восклицательный знак, чтобы взять квест.
3. Шаг три Ожидание перезагрузки сервера не помогло
4. Шаг четыре (Я орк воин)

**Текущее обновление ядра:**

23.07.2019 build 232 (wow circle x5)

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by ForesterDev** [comment]
Это багтрекер х1 logon3. И у нас квест работает
