### ISSUE TITLE
[NPC] ID 7868 - Сара Дубильщица

### ISSUE THREAD

**Issue by Sartorin** [VirginTeam/WotlkCore#1650]
**Описание**

Сара Дубильщица https://wowroad.info/?npc=7868#teaches-ability

**Что работает не так?**

После взятия специализации Кожевничество Сила Стихий отсутствует возможность от нее отказаться за плату - не появляется элемент диалога у НПС. Скорее всего, ошибка повторяется и у мастеров других специализаций. Похожая тема: https://forum.wowcircle.com/showthread.php?t=871757

**Как должно работать?**

Должен быть выбор этой опции в диалоге. 

**Шаги для воспроизведения ошибки:**

1. Взять специализацию Кожевничество Сила Стихий.
2. Поговорить с Сарой.
3. Убедиться, что открывается только список рецептов без диалога отмены специализации.

**Текущее обновление ядра:**

Build 268 2019-08-05
Live

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by ForesterDev** [comment]
Нужно сделать кожевничество основной профессией
