### ISSUE TITLE
[Задание] ID 8418 - Создание камня силы

### ISSUE THREAD

**Issue by sam1904** [VirginTeam/WotlkCore#1652]
**Ссылки и комментарии:**

Задание альянса - Создание камня силы, берется у "Командир Ашлам Неутомимый" в Лагере промозглого ветра в Западных чумных землях. Квест в цепочке после квеста "Бездействующие камни Плети".

https://wowroad.info/?quest=8418

**По заданию необходимо собрать по 2 янтарных, синих и зеленых перьев вуду в затонувшем храме на Болотах печали. Каждой из перьев падает с определенного непися.**

Фактически зеленые перья не добываются с нужных неписей.

Ожидаемый результат — то, чего вы ожидали при выполнении ваших действий. Процесс правильной работы

**Шаги для воспроизведения ошибки:**

1. Шаг один
2. Шаг два
3. Шаг три

**Текущее обновление ядра:**

Можно посмотреть в игре, введите в чат команду .server info и скопировать строку начиная с Build с номером и датой. Не забывайте указывать, Live Server или PTR Server, где проводилось тестирование.

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by Pbellumm** [comment]
Падают с очень низким шансом. Раз двенадцать ходил к ним.

**Comment by sam1904** [comment]
А должны падать 100%, как и другие цвета. Это квестовые предметы с конкретных неписаный именных. 



Отправлено из мобильной Почты Mail.ru


понедельник, 23 сентября 2019 г., 9:03 +0300 от notifications@github.com  <notifications@github.com>:

**Comment by sam1904** [comment]
-------- Пересылаемое сообщение --------
От кого: Семён Семён <sam.1904@mail.ru>
Кому: Ответ от Центра поддержки Logon 3 <reply@logon3.com>
Дата: Суббота, 26 сентября 2020, 2:05 +03:00
Тема: Re[2]: Судьба предателя - не сдается [#009114]
 
sam1904
Немезиз
Обнаружена приблизительно 19.09, сегодня также был в ЧХ, проблема осталась. Квест не сдается
 
>Понедельник, 21 сентября 2020, 18:58 +03:00 от Ответ от Центра поддержки Logon 3 < reply@logon3.com >:
> 
>-- reply above this line --
> 
>Уважаемый Семен, Здравствуйте, Семен!
>
>Благодарю Вас за обращение в службу поддержки.
>Для работы над этим запросом мне нужны от Вас дополнительные сведения. Укажите, пожалуйста, необходимую информацию:
> 
>*  Имя учётной записи
>*  Имя персонажа
>*  Дата и время, когда обнаружена проблема  
>С уважением,
>Центр поддержки Logon 3
>  
 
 
 
   
----------------------------------------------------------------------
