### ISSUE TITLE
[Предмет] ID 50164  - Чуть большая порция пива Фраса Сиаби

### ISSUE THREAD

**Issue by GmAlleria** [VirginTeam/WotlkCore#1658]
**Ссылки и комментарии:**

http://db.logon3.com/?item=50164
https://ru.wowhead.com/item=50164/чуть-большая-порция-пива-фраса-сиаби#sold-by

**Что работает не так?**

Отсутствует в продаже у NPC http://db.logon3.com/?npc=37904

**Как должно работать?**

После убийства Саурфанга,  должны появлятся НПС, в продаже должен присутствовать http://db.logon3.com/?item=50164

**Шаги для воспроизведения ошибки:**

1. Шаг один
2. Шаг два
3. Шаг три

**Текущее обновление ядра:**

Build 271 2019-09-25 12:54:43 +0400

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by ForesterDev** [comment]
Данный предмет является частью лута эпохального режима, поэтому в продажу добавлен не будет
