### ISSUE TITLE
[Талант] ID 47586 Двоевластие

### ISSUE THREAD

**Issue by hamletpd** [VirginTeam/WotlkCore#1660]
**Ссылки и комментарии:**

Талант Жрец Послушание
http://db.logon3.com/?spell=47586

Персонаж - Hamletus

**Что работает не так?**

Числовые значения восполнения HP и урона мгновенных заклинаний лечения и нанесения урона не меняются при взятии таланта.

**Как должно работать?**

Числовые значения восполнения HP и урона мгновенных заклинаний лечения и нанесения урона должны увеличиваться на указанный в описании таланта процент.

**Шаги для воспроизведения ошибки:**

1. Проверяем значения восполнения HP или урона мгновенных заклинаний
2. Берём талант
3. Проверяем значения восполнения HP или урона мгновенных заклинаний

**Текущее обновление ядра:**

Build 271 2019-09-25

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by ForesterDev** [comment]
Работает
