### ISSUE TITLE
[Талант] ID 63646 Божественность

### ISSUE THREAD

**Issue by hamletpd** [VirginTeam/WotlkCore#1661]
**Ссылки и комментарии:**

Талант Паладин Защита
http://db.logon3.com/?spell=63646

Персонаж - Haminus

**Что работает не так?**

Числовые значения восполнения HP заклинаний лечения не меняются при взятии таланта.

**Как должно работать?**

Числовые значения восполнения HP заклинаний лечения должны увеличиваться на указанный в описании таланта процент.

**Шаги для воспроизведения ошибки:**

1. Проверяем значения восполнения HP 
2. Берём талант
3. Проверяем значения восполнения HP

**Текущее обновление ядра:**

Build 271 2019-09-25

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by ForesterDev** [comment]
Проверил, работает как со своим отхилом, так и с входящим отхилом (легко проверить, наложить Омоложение друида до взятия таланта и посмотреть цифры, и после наложения)
