### ISSUE TITLE
[Игровая механика] Целитель душ у Логова Ониксии

### ISSUE THREAD

**Issue by Pbellumm** [VirginTeam/WotlkCore#1662]
**Ссылки и комментарии:**

https://wowroad.info/?npc=6491

**Что работает не так?**

После смерти в Логове Ониксии дух возрождается у дальнего кладбища.

**Как должно работать?**

Респаун должен происходить у ближайшего к логову кладбища.
![WoWScrnShot_100219_104432](https://user-images.githubusercontent.com/52411469/66041446-9308ff80-e522-11e9-88ec-79b83ceb3eb4.jpg)

**Шаги для воспроизведения ошибки:**

1. Создать рейд.
2. Умереть в Логове Ониксии. Возможно важно, что умирали у самой Ониксии во время или после фазы её полёта.
3. Возродиться духом.

**Текущее обновление ядра:**

Build 271 2019-09-25 12:54:43 +0400 Logon 3 x1 PvE

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by ForesterDev** [comment]
Должно ли быть так, как описано в репорте? Можете пруфы привести (возможно с классики)

**Comment by sega693** [comment]
В классике точно на дальнем, после 3.2 или каты переделали разве что

**Comment by Pbellumm** [comment]
Репорт был составлен по комментариям рейдеров, которые жаловались, что раньше респ был около пещеры. Видимо дезинформация. Извините.
