### ISSUE TITLE
[Группа заклинаний] Урон от способностей питомца

### ISSUE THREAD

**Issue by Panhandle-rep** [VirginTeam/WotlkCore#1669]
Тром-ка!
Прошу разобрать следующую ситуацию, выявить проблему и устранить ее.

Речь пойдет о том, правильно ли работают способности питомцев охотника.
Я столкнулся с этой ситуацией, играя орком-охотником 80-го уровня с питомцем-осой 80-го уровня. Перед написанием репорта я сверил показания с другими своими петами и с петами другого охотника и не нашел отличий.
Я разбирал проблему на примере следующих способностей питомца:
[Ужалить](http://db.logon3.com/?spell=56631)
[Хлопок](http://db.logon3.com/?spell=52476)
Для оценки правильности работы способностей прилагаю:
[Скриншот из игры для "Ужалить"](https://i89.fastpic.ru/big/2019/1012/bd/_5d367f41a068cae2e3dd126353a090bd.jpg)
[Скриншот из игры для "Хлопок"](https://i87.fastpic.ru/big/2019/1012/75/_174a87d21fc46096f1161c20c6ad7075.jpg)
[Видеоролик какого-то ханта времен WotLK на оффе](https://youtu.be/TWJ59rs04ag), в котором не видно урона от пета на 100-200
[Лог боя какого-то ханта времен WotLK на оффе](http://www.worldoflogs.com/reports/lv7nhjt148gvrwrw/sum/damageDone/?s=2192&e=2420#Drakour) с [детализацией по пету](http://www.worldoflogs.com/reports/lv7nhjt148gvrwrw/details/20/?s=2192&e=2420)

На данный момент способности питомца наносят свой непосредственный урон, беря только модификаторы на общий урон питомца наподобие таланта ["Контроль популяции"](http://db.logon3.com/?spell=52858).
На скриншотах видны цифры боя с [мамонтом](http://db.logon3.com/?npc=29402), имеющим обычную броню и не имеющим сопротивления. 

Хотелось бы, чтобы способности питомца наносили урон, зависящий от параметров питомца "Сила атаки" и "Заклинания", соответственно формулам в описании этих способностей в БД сервера.
Ориентировочно, способность "Ужалить" должна при указанных характеристиках питомца наносить 75+1088х0.33=434 урона вместо 114.
Ориентировочно, способность "Хлопок" должна при указанных характеристиках питомца наносить (143+1088х0.12+2620*0.07)*0.6=274 урона вместо 122 (если считать, что броня мамонта скушает 40% физурона).

Чтобы проверить это, достаточно, играя охотником, натравить питомца на подходящую по уровню цель и пронаблюдать цифры урона от способностей питомца.

Ситуация воспроизведена на live-сервере со следующим обновлением ядра:
Build 272 2019-10-03 10:36:13 +0400

Лок'тар огар!
Чапельник, орк-охотник.

**Comment by ForesterDev** [comment]
Тестируйте после обновления

**Comment by ForesterDev** [comment]
Исправлено
