### ISSUE TITLE
[Игровая механика] Поиск подземелий - переход в инст 

### ISSUE THREAD

**Issue by Plasmashield** [VirginTeam/WotlkCore#167]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

При использовании поиска подземелий некорректно переносит в инст

**Что работает не так?**

1. Некроситет - переносит не в начало инста, а где то снаружи здания 
2. Нижняя часть Черной Горы - переносит к порталу в ЛКТ, а не к порталу Пика черной горы
Возможно их больше

**Как должно работать?**

Должно переносить в начало инста 

**Шаги для воспроизведения ошибки:**

1. Регнуть пп(Некроситет, НЧЧГ)
2. Оказаться в неожиданном месте 

**Текущее обновление ядра:**

Build 157 2017-05-02 14:02:07 +0400  x1 PvE

**Comment by Riazarre** [comment]
Подтверждаю

**Comment by Plasmashield** [comment]
Актуально для НЧЧГ

> 
> 
> Актуально?

**Comment by ForesterDev** [comment]
Исправлено. Будет применено в обновлении
