### ISSUE TITLE
[Задание] ID 9718 - С высоты птичьего полета

### ISSUE THREAD

**Issue by Climss** [VirginTeam/WotlkCore#1674]
**Ссылки и комментарии:**

http://db.logon3.com/?quest=9718

**Что работает не так?**

Облетев озера в форме птицы, квест не засчитывается.

**Как должно работать?**

После того, как все озера будут обследованы, квест считается выполненным. 

**Шаги для воспроизведения ошибки:**

1. Взять квест "С высоты птичьего полета"
2. Активировать "Амулет Буревестника", который дается после взятия задания
3. Облететь озера

**Текущее обновление ядра:**

Build 273 2019-10-14 14:10:59 +0400 Logon 3 x1 PvE

**Comment by Igryniax1** [comment]
Так ответа и нет?

**Comment by Igryniax1** [comment]
починят?)

**Comment by Fedoroff90** [comment]
Почините! последний кв остался на Хранителя мудрости, а 4 месяца он сломан...если не больше

**Comment by vladik666** [comment]
починили, спасибо
