### ISSUE TITLE
[Задание] ID 10674 - Ловля фантастического света

### ISSUE THREAD

**Issue by Climss** [VirginTeam/WotlkCore#1676]
**Ссылки и комментарии:**

http://db.logon3.com/?quest=10674

**Что работает не так?**

Не засчитываются световые сферы при попытке ловли их в ловушку.
![ot1](https://user-images.githubusercontent.com/56660951/67093597-b5ee1180-f1ba-11e9-8db2-1e568a9d709b.jpg)

**Как должно работать?**

Попытки ловли сфер должны засчитываться.

**Шаги для воспроизведения ошибки:**

1. Установить ловушку
2. Дождаться процесса поимки светового шара

**Текущее обновление ядра:**

Build 273 2019-10-14 14:10:59 +0400 Logon 3 x1 PvE

**Comment by vkeda** [comment]
Квест все еще не рабочий, сферы не засчитываются.
Build 283 2019-12-25 14:49:59 +0400

**Comment by Kodekc** [comment]
Будет исправлено в ближайшем обновлении
