### ISSUE TITLE
[Подземелье] Вершина Утгард (ID 26861 Король Имирон)

### ISSUE THREAD

**Issue by Vindenta** [VirginTeam/WotlkCore#1681]
**Ссылки и комментарии:**

http://db.logon3.com/?spell=50334 (способность берсерк в коте и медведе)
https://ru.wowhead.com/npc=26861 (скилы боса)

**Что работает не так?**

Бос во время боя включает способность https://ru.wowhead.com/spell=51750 страх на группу, когда действует берсерк страх кидается на друида.

**Как должно работать?**

Страх не должен кидаться под берсой

**Шаги для воспроизведения ошибки:**

1. Войти в бой с королем
2. Прожать берсерк
3. Наблюдать как страх действует во время берсы

**Текущее обновление ядра:**

Logon 3 WowCircle Development
Последнее обновление ядра: Build 273 2019-10-14 14:10:59 +0400

**Comment by ForesterDev** [comment]
Крики мертвых - это оглушение, а не страх.
