### ISSUE TITLE
[Заклинание] ID 52474 - Укус

### ISSUE THREAD

**Issue by MedoOk** [VirginTeam/WotlkCore#1689]
**Ссылки и комментарии:**

http://db.logon3.com/?spell=52474

**Что работает не так?**

Укус противника, наносящий 118 - 168 ед. урона. 
Ну так и наносит как написано в тултипе, отсутствует скаляция от апа пета

**Как должно работать?**

http://www.worldoflogs.com/reports/ul76xm556v85ir2v/details/84/?s=5898&e=6033
Ну как-то так.

**Шаги для воспроизведения ошибки:**

натравить пета ханта на что угодно и посмотреть урон от автоатаки и укуса

**Текущее обновление ядра:**

с августа 2019

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by MedoOk** [comment]
Видимо является частью этого репорта: https://github.com/VirginTeam/WotlkCore/issues/1669

**Comment by ForesterDev** [comment]
Повтор
