### ISSUE TITLE
[Символ] ID 40902 - Символ разрывания

### ISSUE THREAD

**Issue by FilDru** [VirginTeam/WotlkCore#1694]
**Ссылки и комментарии:**

http://db.logon3.com/?item=40902
http://db.logon3.com/?spell=49800

**Что работает не так?**

"Разорвать" длится базовые 16 сек.

**Как должно работать?**

"Разорвать" должна длиться 20 сек с символом.

**Шаги для воспроизведения ошибки:**

1. Подойти к манекену
2. Набить комбопоинты и спустить их на "Разорвать"
3. Считать секунды

**Текущее обновление ядра:**

Build 281 2019-11-15 11:16:23 +0400. Live Server.

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by MedoOk** [comment]
Скидывать ссылку на спелл, где написано 12 секунд базовое время, и требовать сделать базовое 16? Ты вообще как адекватен?
