### ISSUE TITLE
[Заклинание] ID 46917 - "Хватка Титана"

### ISSUE THREAD

**Issue by zverbabochka** [VirginTeam/WotlkCore#1696]
**Ссылки и комментарии:**
http://db.logon3.com/?spell=46917

**Что работает не так?**
При ношении двуручного оружия в правой и левой руках урон персонажа снижен на 10%.

![Безымянный](https://user-images.githubusercontent.com/57999056/69252668-d13ea900-0bcc-11ea-8a7b-633dfaebdbaf.png)

**Как должно работать?**
При ношении двуручного оружия в правой и левой руках урон персонажа 100%. 

Ожидаемый результат — то, чего вы ожидали при выполнении ваших действий. Процесс правильной работы

**Шаги для воспроизведения ошибки:**

1. Изучение таланта http://db.logon3.com/?spell=46917.
2. Экипировка двуручным оружием.

**Текущее обновление ядра:**

Build 281 2019-11-15 11:16:23 +0400 Logon 3 x1 PvE

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by MedoOk** [comment]
Позволяет держать двуручное дробящее оружие, двуручные топоры или мечи в одной руке. Когда вы держите двуручное оружие в одной руке, то весь наносимый вами физический урон снижается на 10%.
![image](https://user-images.githubusercontent.com/57435425/69254606-92f2bb00-0bc7-11ea-937e-d68b9248511a.png)
