### ISSUE TITLE
[Задание] ID 12855 - Найти преступника

### ISSUE THREAD

**Issue by qwestik06** [VirginTeam/WotlkCore#1699]
**Ссылки и комментарии:**

https://ru.wowhead.com/quest=12855/%D0%BD%D0%B0%D0%B9%D1%82%D0%B8-%D0%BF%D1%80%D0%B5%D1%81%D1%82%D1%83%D0%BF%D0%BD%D0%B8%D0%BA%D0%B0

**Что работает не так?**
Нельзя сесть на Ледокуса ; Не засчитывает часть задания "След прослежен до источника"

**Как должно работать?**
после взятия квеста должно автоматически садить игрока на Ледокуса,тот в свою очередь должен отвезти нас к пещере,должны работать 2 заклинания при этом,За нами Должны бежать Железные дворфы.

**Шаги для воспроизведения ошибки:**

1. Берём квест
2. Нас садят на Ледокуса
3. Ледокус доставляет нас до пещеры
4.Часть задания "След прослежен до источника" засчитывается.

Build 282 2019-12-18 12:39:11 +0400

Можно посмотреть в игре, введите в чат команду .server info и скопировать строку начиная с Build с номером и датой. Не забывайте указывать, Live Server или PTR Server, где проводилось тестирование.

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by GmAlleria** [comment]
Дубликат
