### ISSUE TITLE
[NPC] ID 23282 - Обсидия

### ISSUE THREAD

**Issue by FilDru** [VirginTeam/WotlkCore#1707]
**Ссылки и комментарии:**

http://db.logon3.com/?npc=23282#drops

**Что работает не так?**

При появлении дракон висит наполовину в текстурах. Его невозможно атаковать.

**Как должно работать?**

Он должен быть уязвим.

**Шаги для воспроизведения ошибки:**

1. Собрать 35 Апекситовых осколков для призыва.
2. Призвать дракона в его логове.
3. Увидеть все вышеизложенное

**Текущее обновление ядра:**

Build 284 2019-12-28 16:53:06 +0400 Live server

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by GmAlleria** [comment]
дубль #962
