### ISSUE TITLE
[Задание] ID 10439 -  Пространствус Всепоглощающий

### ISSUE THREAD

**Issue by anakle** [VirginTeam/WotlkCore#1708]
**Ссылки и комментарии:**
https://ru.wowhead.com/quest=10439/%D0%BF%D1%80%D0%BE%D1%81%D1%82%D1%80%D0%B0%D0%BD%D1%81%D1%82%D0%B2%D1%83%D1%81-%D0%B2%D1%81%D0%B5%D0%BF%D0%BE%D0%B3%D0%BB%D0%BE%D1%89%D0%B0%D1%8E%D1%89%D0%B8%D0%B9

**Что работает не так?**
По квесту надо поговорить с Саидом. НПС не реагирует, квест не засчитывается.

**Как должно работать?**

Саид говорит со мной, квест защитывается.

**Шаги для воспроизведения ошибки:**

1. Берется квест у Профессора Дабири
2. НПС Саида нет на месте, он стоит сверху в манагорне рядом с боссом
3. Босс убивается, НПС на нас не реагирует.

**Текущее обновление ядра:**
Build 284 2019-12-28 16:53:06 +0400 Live server

**Comment by Kodekc** [comment]
https://github.com/VirginTeam/WotlkCore/issues/51
