### ISSUE TITLE
любовная лихорадка. не дают опыт за ежедневные квесты

### ISSUE THREAD

**Issue by mama911** [VirginTeam/WotlkCore#1715]
здравствуйте. лог 3 . По ежедневным квестам Любовной лихорадки уже второй день не дает опыт за выполнение. Открытку деньги сердечко дает а опыт нет, хотя написано что должно дать 15 500 опыта. рога ник Ксюха 34 лвл. В чем может быть проблема ?

Добавьте ссылки с wowhead.com или db.logon3.com на проблемные задания, NPC, заклинания и т.д. ru.wowhead.com/love-is-in-the-air

**Что работает не так?**https://ru.wowhead.com/quest=24597/%D0%BF%D0%BE%D0%B4%D0%B0%D1%80%D0%BE%D0%BA-%D0%B4%D0%BB%D1%8F-%D0%BA%D0%BE%D1%80%D0%BE%D0%BB%D1%8F-%D1%88%D1%82%D0%BE%D1%80%D0%BC%D0%B3%D1%80%D0%B0%D0%B4%D0%B0

Фактический результат — опыт недается после здачи квестов (всех ежедневных Любовной лихорадки)

**Как должно работать?**иак как написано на сайте вовхеда

Ожидаемый результат — то, чего вы ожидали при выполнении ваших действий. Процесс правильной работы

**Шаги для воспроизведения ошибки:**

1. Шаг один-первый день проверка здачи всех квестов
2. Шаг два- второй день проверка здачи 2х квестов
3. Шаг три- пишу вам

**Текущее обновление ядра:**- извините, непонимаю где и как смотреть. сегодня 14.02.2020 23.30

Можно посмотреть в игре, введите в чат команду .server info и скопировать строку начиная с Build с номером и датой. Не забывайте указывать, Live Server или PTR Server, где проводилось тестирование.

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by ForesterDev** [comment]
Судя по всему вы ошиблись трекером и баг-репорт не имеет отношения к нашему игровому миру. У нас работает как положено
