### ISSUE TITLE
Некорректная работа мгновенных заклинаний

### ISSUE THREAD

**Issue by tenedanya** [VirginTeam/WotlkCore#1716]
**Ссылки и комментарии:**

Добавьте ссылки с wowhead.com или db.logon3.com на проблемные задания, NPC, заклинания и т.д. 

**Что работает не так?**

При спаме мгновенных заклинаний, примерно одно из десяти не срабатывает. Пишет что - заклинание недоступно. Многие игроки, считают, что так и должно быть, поэтому просто спамят кнопку до срабатывания. 

**Как должно работать?**

Хорошо проверить в чем проблема, можно, если на друиде часто нажимать смены форм.
Кот, медведь, дерево, кот, медведь, дерево.
При корректной работе мгновенный заклинаний, так как сейчас происходит в вов классик, и в вов актуал - вы будете переходить из формы в форму без всяких проблем.
На сервере logon3 смена форм - медведь, кот, дерево, один раз из десяти заканчивается выходом в человека с ошибкой - "Невозможно выполнить заклинание"
Дело в том, что если заклинание по смене форм не выполняется, так  как не отошел кд, то персонаж должен оставаться в предыдущей форме животного. 
1. Персонаж в медведе.
2. жмем кнопку перехода в кота
3. Происходит ошибка, не вовремя нажал, еще кд на заклинане. 
Результат - ошибка остаемся в медведе.

Что происходит сейчас.
1. Персонаж в медведе.
2. жмем кнопку перехода в кота.
3. Ошибка, не вовремя нажал, еще кд
Результат - выбрасывает в человеа.

В чем проблема - бью в коте, вижу что не могу победить, кидаю на себя хоты с выходом из формы, прыгаю в мишку, понимаю, что надо бежать, прыгаю в гепарда - но гепард на срабатывает.. я бегу в человеке.. меня убивают.

Могу сделать видео работы мгновенных заклинаний на официале. И сравнение с логон3.
Разница очевидно, Баг заметен.

**Шаги для воспроизведения ошибки:**

1. Шаг один Прыгаем в форму животного
2. Шаг два Переключаем формы животных не выходя в человека попадая в кд заклинаний
3. Шаг три Получаем выбивание из формы и превращение в человека - что невозможно.

**Текущее обновление ядра:**
Live Serve
12:57:53] Logon 3 WowCircle Development
[12:57:53] Последнее обновление ядра: Build 286 2020-01-30 11:27:02 +0400
[12:57:53] Игроков онлайн: 1312 (максимум: 2737). Игроков в очереди: 0 (максимум: 0).
[12:57:53] Продолжительность работы сервера: 10 Day(s) 6 Hour(s) 57 Minute(s) 22 Second(s).
[12:57:53] Серверная задержка: 13. Средняя серверная задержка: 13
[12:57:53] Следующее начисление очков арены: 23.02.2020  10:20

Можно посмотреть в игре, введите в чат команду .server info и скопировать строку начиная с Build с номером и датой. Не забывайте указывать, Live Server или PTR Server, где проводилось тестирование.

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by ForesterDev** [comment]
Это связано с серверной задержкой - если сервер слегка подлагал, на 100 мс, то на клиенте гкд уже прошло, а на сервере из-за лага - нет. Поэтому сервер и не дает сменить форму, считая, что гкд не прошло. На локальном сервере без задержки таких проблем нет. Исправить не представляется возможным

**Comment by nreiv** [comment]
В данном случае ещё автору стоит отметить, есть ли у него аддоны типа **SnowfallKeyPress** и/или макросы для смены форм. Ну, и как бы формы друидов, как и аспекты хантов при повторном нажатии отменяют ауру, стало быть спамить их не нужно, но если очень хочется, то совет автору, используй в макросах знак восклицания по типу:
`/cast !форма катана`
в таком случае форма отменятся не будет, она будет перезапускаться при повторном нажатии.

**Comment by tenedanya** [comment]
> В данном случае ещё автору стоит отметить, есть ли у него аддоны типа **SnowfallKeyPress** и/или макросы для смены форм. Ну, и как бы формы друидов, как и аспекты хантов при повторном нажатии отменяют ауру, стало быть спамить их не нужно, но если очень хочется, то совет автору, используй в макросах знак восклицания по типу:
> `/cast !форма катана`
> в таком случае форма отменятся не будет, она будет перезапускаться при повторном нажатии.

Никаких макросов. Только руки. 
из аддонов - дбм, грид, кликью, suf, dominos
Все это не использовал при смене форм.
Но даже и это отключал, чтоб проверить этот занятный баг.

Проверил на официале- все работает корректно.
Проверил здесь - все работает с этим странным багом, при отключенных аддонах...

**Comment by nreiv** [comment]
и всё же, конкретно твоя проблема решается написанием макроса, который исключает влияние человеческой реакции и снижает значимость задержек на сервере - и без разницы, какой сервер это будет. ты же играя за катана не спамишь проул, ведь он тоже отменится при повторном нажатии) я предложил тебе простейшее решение проблемы, но при желании из этого решения можно даже преимущество себе создать, например:
```
#showtooltip
/cast [form:1]!гепардиус;[form:0/1/3]!медведиус;
```
так находясь в форме медведя ты перейдёшь в гепарда, а в любой другой форме в медведя, только названия абилок замени на верные решифты

**Comment by tenedanya** [comment]
> и всё же, конкретно твоя проблема решается написанием макроса, который исключает влияние человеческой реакции и снижает значимость задержек на сервере - и без разницы, какой сервер это будет. ты же играя за катана не спамишь проул, ведь он тоже отменится при повторном нажатии) я предложил тебе простейшее решение проблемы, но при желании из этого решения можно даже преимущество себе создать, например:
> 
> ```
> #showtooltip
> /cast [form:1]!гепардиус;[form:0/2/3]!медведиус;
> ```
> 
> так находясь в форме медведя ты перейдёшь в гепарда, а в любой другой форме в медведя, только названия абилок замени на верные решифты

Понимаешь, в чем проблема. Проблема глобального характера. 
Она прослеживается на спаме омоложения, когда на четырех игроков кинулось, на пятого нет.
Эта ошибка прослеживается на спаме щитов, за дц приста, когда четыре щита кинулось, пяты нет.
Просто на друиде - это очень хорошо прослеживается на смене форм. Можно доказать админам - что есть проблема и ее нужно фиксить.
Если бы я пришел и сказал, ребята, если в гкд кидать пять щитов, один не кидается за дц - мне бы сказали - "тебя глючит, у тебя пинг, у тебя глаза балуются"

Но при смене форм друида - четко видно, что идет выполнение заклинания - баг - и вообще выбивает из формы. 
Если бы проблема касалась только смены форм - бог с ним.
Но когда играешь на отслеживание гкд инстант каста, и кидаешь четко в ноль 5 щитов, а у тебя кинулось 4... Ребята, ну это борщ.

**Comment by nreiv** [comment]
> >  
> Понимаешь, в чем проблема. Проблема глобального характера.
> Она прослеживается на спаме омоложения, когда на четырех игроков кинулось, на пятого нет.
> Эта ошибка прослеживается на спаме щитов, за дц приста, когда четыре щита кинулось, пяты нет.
> Если бы я пришел и сказал, ребята, если в гкд кидать пять щитов, один не кидается за дц - мне бы сказали - "тебя глючит, у тебя пинг, у тебя глаза балуются"
> 
в такое и правда слишком сложно поверить, если ты даже не используешь аддоны и макросы. тем более, если речь идёт про пвп сегмент. ведь ты пока стоишь и мышкой таргеты переключаешь спамя щит, ты уже можешь сало/стан/фир/смерч получить или твой таргет может из зоны действия убежать, или на нём викнес от прошлого щита ещё висит). но если ты уверен в том, что такое есть со щитами дц, то записал бы видео и людей, которые заметили похожий баг, может быть тогда твою проблему было бы реально решить, или хотя бы понять устранима ли её причина

**Comment by tenedanya** [comment]
> > > 
> > 
> > 
> > Понимаешь, в чем проблема. Проблема глобального характера.
> > Она прослеживается на спаме омоложения, когда на четырех игроков кинулось, на пятого нет.
> > Эта ошибка прослеживается на спаме щитов, за дц приста, когда четыре щита кинулось, пяты нет.
> > Если бы я пришел и сказал, ребята, если в гкд кидать пять щитов, один не кидается за дц - мне бы сказали - "тебя глючит, у тебя пинг, у тебя глаза балуются"
> 
> в такое и правда слишком сложно поверить, если ты даже не используешь аддоны и макросы. тем более, если речь идёт про пвп сегмент. ведь ты пока стоишь и мышкой таргеты переключаешь спамя щит, ты уже можешь сало/стан/фир/смерч получить или твой таргет может из зоны действия убежать, или на нём викнес от прошлого щита ещё висит). но если ты уверен в том, что такое есть со щитами дц, то записал бы видео и людей, которые заметили похожий баг, может быть тогда твою проблему было бы реально решить, или хотя бы понять устранима ли её причина

Я уже дал исчерпывающие доказательства по ошибке произнесения мгновенного заклинания.
Будучи в форме медведя применяем заклинание кота.
Заклинение успешно - превращаемся в кота.
Заклинание еще на гкд - остаемся в мишке, невозможно выполнить.
В нашем случае, прошло гкд, заклинание начинает выполняться, но происходит ошибка, и заклинание прерывается.
Друид выходит в форму человека.
Лучшая демонстрация ошибок мгновенных заклинаний.
Я специально выбрал именно этот способ демонстрации ошибки. На этом примере лучше всего прослеживается проблема.

С чего ты взял, что я там переключаю мышкой таргет? Я же сказал что использую грид+кликью.
Зачем писать видео, если может зайти каждый и ручками понажимать на смены форм. Если при смене форм, форма не переключится, а заклинателя выбьет в форму человека - баг у всех.
Я проверял на другиг аккаунтах, проверяли други люди, из разных стран.
у всех этот баг инстантовых заклинаний.
Админ ответил - да, проблема есть, но это фриз сервера. На клиента выполнилось заклинание, на сервере нет - синхронизация дала отмену.

Но при этом он отвечает - что типа она нерешаема.
Меня это удивляет. Весь сервер ловит баг раз  5 секунд. А решить проблему нельзя.

**Comment by nreiv** [comment]
> С чего ты взял, что я там переключаю мышкой таргет? 
я делаю очевидные выводы из твоих сообщений

> Будучи в форме медведя применяем заклинание кота.
> Заклинение успешно - превращаемся в кота.
> Заклинание еще на гкд - остаемся в мишке, невозможно выполнить.
> В нашем случае, прошло гкд, заклинание начинает выполняться, но происходит ошибка, и заклинание прерывается.
> Друид выходит в форму человека.

лично у меня не получилось за весь столб маны в ферал ветке воспроизвести этот эффект ни разу, единственное что возможно при неконтролируемом спаме формы - это отмена формы повторным нажатием на ту же кнопку, как я отмечал это ранее) поэтому я тебе и предложил использовать макрос с параметром "!", чтобы твои сверхскоростные нажатия не выбивали тебя из формы зверя)

**Comment by tenedanya** [comment]
> > С чего ты взял, что я там переключаю мышкой таргет?
> 
> я делаю очевидные выводы из твоих сообщений
> 
> > Будучи в форме медведя применяем заклинание кота.
> > Заклинение успешно - превращаемся в кота.
> > Заклинание еще на гкд - остаемся в мишке, невозможно выполнить.
> > В нашем случае, прошло гкд, заклинание начинает выполняться, но происходит ошибка, и заклинание прерывается.
> > Друид выходит в форму человека.
> 
> лично у меня не получилось за весь столб маны в ферал ветке воспроизвести этот эффект ни разу, единственное что возможно при неконтролируемом спаме формы - это отмена формы повторным нажатием на ту же кнопку, как я отмечал это ранее) поэтому я тебе и предложил использовать макрос с параметром "!", чтобы твои сверхскоростные нажатия не выбивали тебя из формы зверя)

Я правильно понял, что ты троль?
Человек тебе четко пишет - использую грид+кликью. Ты мне пишешь "переключаешь таргет мышкой".  Ну хотя бы погуглил, что это за аддоны, если нет опыта и не знаешь о чем это.
Четко написано - "смена форм, как пример ошибки инстант каста", ошибка мгновенных заклинений, глобальная, влияет на все классы, дц, ресторы, мили дд.  Смена форм - только как пример.
Ты сидишь рассуждаешь о макросах. Зачем?
разработчик четко дал ответ - да, проблема есть. 
Разработчик четко пишет - на офе нет четкого ограничение по гкд. Синхрон проще проходит.
Тут есть четкое ограничение. Поэтому есть возможность рассинхрона сервера и клиента.

Ответ получен - а ты что-то там испытываешь, строишь предположения по поводу того, как кто-то мышкой таргеты меняет....
К чему и зачем все это?
