### ISSUE TITLE
[NPC] ID 17225 - Ночная погибель

### ISSUE THREAD

**Issue by Trombocid** [VirginTeam/WotlkCore#1724]
Описание:

Призываемый босс в рейдовом инсте [Каражан].

Что работает не так?

Босс не призывается. Пробовал по-всякому: без кд на инст,  с кд, после полной зачистки рейда. Ранее босс призывался, с задержкой примерно с минуту после активации кв итема. Теперь же не помогают и танцы с бубном.

Как должно работать?

После выполнения соответствующей цепочки кв игрок получает возможность запустить данного босса.

Шаги для воспроизведения ошибки:

1. Выполнить цепочку кв, начиная с https://wowroad.info/?quest=9630 [Записи медива];
2. Получить кв https://wowroad.info/?quest=9644 [Ночная погибель];
3. Вернуться в рейдовый инст [Каражан], пройти на Терассу Мастера;
4. Активировать кв итем https://wowroad.info/?object=194092 [Вороненая урна].
Текущее обновление ядра:

Build 287 2020-02-25 12:08:04 +0400

**Comment by ForesterDev** [comment]
![image](https://user-images.githubusercontent.com/11771800/77294881-6b8b3680-6cfe-11ea-9360-b67f7814b772.png)
Взял квест, нажал на урну - прилетел дракон. Все работает

**Comment by Trombocid** [comment]
А с выполненным кв?
