### ISSUE TITLE
[Подземелье] Пик Черной Горы (ID 9816 Пиростраж Углевзор)

### ISSUE THREAD

**Issue by Vindenta** [VirginTeam/WotlkCore#1725]
**Ссылки и комментарии:**
http://db.logon3.com/?npc=9816

**Что работает не так?**
При нажатии на алтарь бос не запускается, если находишься в группе.
https://youtu.be/B7We0GCRTZE (в группе)

**Как должно работать?**
При нажатии на алтарь бос должен запуститься, как в группе так одним персонажем.
https://youtu.be/77hGxhBHbuM (не в группе запускается)

1. Нажать на алтарь
2. Активируются тюремщики, которых нужно убить
3. Убить тюремщиков
4. Ждать пока бос вырастет
5. Убить Пиростража
После убийства открывается дверь в другую комнату.

https://youtu.be/77hGxhBHbuM (не в группе запускается)
**Шаги для воспроизведения ошибки:**
1. Нажать на алтарь
2. Ждать пока бос вырастет
3. Бос не активируется

**Текущее обновление ядра:**
Logon 3 WowCircle Development
Последнее обновление ядра: Build 287 2020-02-25 12:08:04 +0400

**Comment by nreiv** [comment]
а в чём ошибка то? у тебя шаги по воспроизведению ошибки противоречат сути репорта

**Comment by Vindenta** [comment]
> **Ссылки и комментарии: **
> http://db.logon3.com/?npc=9816
> 
> **Что работает не так? **
> При запуске на алтарь, если не будет в группе.
> https://youtu.be/B7We0GCRTZE (в группе)
> 
> **Как должно работать? **
> Пришёл в голову так же одним персонажем.
> https://youtu.be/77hGxhBHbuM (не в группе запускается)
> 
> 1. Нажать на алтарь
> 2. Активируются тюремщики, которые нужно убить
> 3. Убить тюремщиков
> 4. Ждать пока бос вырастет
> 5. Убить Пиростража 
>    После убийства открывается дверь в другую комнату.
> 
> https://youtu.be/77hGxhBHbuM (не в группе запускается)
> **Шаги для воспроизведения ошибки:**
> 
> 1. Нажать на алтарь
> 2. Ждать пока бос вырастет
> 3. Бос не активируется
> 
> **Текущее обновление ядра:**
> Logon 3 WowCircle Development
> Последнее обновление ядра: Build 287 2020-02-25 12:08:04 +0400

**Comment by nreiv** [comment]
Vindenta, а следующего босса у тебя получалось запустить? который Солакарский огнечервь http://db.logon3.com/?npc=10264 - если нет, то нужно тоже репортануть, у меня вот чёт никакие танцы с бубном не помогают его запустить, правда я в группе не пробовал, но как ты заметил по этому тикету, группой до него и не дойти, если Углевзор не запускается.

**Comment by Myrskyntuoja** [comment]
В группе босс нормально запускается, если все члены группы, находящиеся в инсте, используют алтарь одновременно. На видео видно, что второй участник группы также находится внутри инста, но алтарь не трогает.

**Comment by Plasmashield** [comment]
С воввики: "Breaking the Pyroguard's captivity requires clicking the Blackrock Altar at the floor. As of patch 3.0.8, this no longer requires three people and can be done solo. "

**Comment by Myrskyntuoja** [comment]
Что никак не противоречит текущей логике. Оно не требует трех человек и может быть сделано соло. Не могу, однако, нагуглить ни подтверждения, ни опровержения, что все участники группы должны трогать алтарь.

**Comment by Plasmashield** [comment]
До, конечно не противоречит. Убрали необходимость 3х человек, чтобы можно было запускать одному, поэтому теперь нужно 5 человек. Логика может выйти в окно

**Comment by ForesterDev** [comment]
![image](https://user-images.githubusercontent.com/11771800/77294468-c83a2180-6cfd-11ea-9b2b-afe6df64ccd2.png)
Все нормально запускается и соло. Нужно нажать на алтарь и подождать несколько минут, пока босс наберет силы

**Comment by Plasmashield** [comment]
Соло запускается. Если в пати 2+ тел, то соло не запускается. Не запускается и в 3. Запускается тогда только при нажатии на алтарь всех участников группы. И по ощущениям запуск происходит дольше чем соло

**Comment by Plasmashield** [comment]
Зачем закрыли тикет если баг не починили?
