### ISSUE TITLE
[NPC] ID 22427 - Зарехви

### ISSUE THREAD

**Issue by Anarom** [VirginTeam/WotlkCore#1727]
**Ссылки и комментарии:**
http://db.logon3.com/?npc=22427 - сам NPC
http://db.logon3.com/?spell=41565 - отсутствующий скилл
https://github.com/VirginTeam/WotlkCore/issues/1650 - схожий репорт

**Что работает не так?**
При разговоре с NPC отсутствует опция сброса специализации алхимии. Скорее всего, не работает опция сброса и у других NPC-тренеров специлизаций алхимии (http://db.logon3.com/?npc=19052, http://db.logon3.com/?npc=17909)
**Как должно работать?**
Мастер текущей специализации алхимии должен в диалоге предлагать ее сбросить.
**Шаги для воспроизведения ошибки:**

1. Выучить специализацию алхимии "мастер трансмутации" у  НПЦ http://db.logon3.com/?npc=22427
2. Поговорить с тем же НПЦ
3. Убедиться, что опция сброса специализации отсутствует

**Текущее обновление ядра:**
Build 287 2020-02-25

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by ForesterDev** [comment]
![image](https://user-images.githubusercontent.com/11771800/77293009-dfc3db00-6cfa-11ea-841b-1c58948b8cb3.png)

Все работает. Для отображения опции необходимо иметь алхимию 350 и выше, Мастер трансмутации и уровень игрока выше 68. Возможно, алхимия не выбрана основной профессией

**Comment by Anarom** [comment]
Да, действительно. Извиняюсь за дезинформацию.
