### ISSUE TITLE
[Задание] id 12555 - Оплетающие сети

### ISSUE THREAD

**Issue by gmOpex** [VirginTeam/WotlkCore#173]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Не работает полностью. Сеятели чумы не падают вниз, задание не засчитывается. Убийство кастером без использования тема  квест не засчитывает.

**Что работает не так?**

При использовании http://ru.wowhead.com/item=38515 на http://ru.wowhead.com/npc=28274 не сжигает их и не засчитывает в критерий задания

**Как должно работать?**

При использовании http://ru.wowhead.com/item=38515 на http://ru.wowhead.com/npc=28274 нпс должен оплетаться паутиной визуально, загораться, и умирать, падая на землю. Задание должно засчитываться. https://youtu.be/B1byxXXQTnQ

**Текущее обновление ядра:**
Build 157 2017-05-02 14:02:07 +0400

**Comment by ForesterDev** [comment]
Исправлено. Будет применено в обновлении
