### ISSUE TITLE
[Профессия] Кузнечное дело - баг со специализациями

### ISSUE THREAD

**Issue by alex90456** [VirginTeam/WotlkCore#1739]
**Ссылки и комментарии:**

http://db.logon3.com/?npc=20125   - учитель бронник
http://db.logon3.com/?npc=20124   - учитель оружейник

**Что работает не так?**

Не делал квесты на какую либо специализацию, но смог изучить рецепты бронника и оружейника. Толку от них 0, но всё же.

**Как должно работать?**

Не уверен, что это баг. Возможно, рецепты должны изучаться только по школам кузнечного дела.

**Шаги для воспроизведения ошибки:**

1. Качаем кузнечное дело до 350
2. Не делаем каких-либо квестов на специализацию
3. Идём в Шаттрат к данным NPC (в Стальгорне у аналогичных тренеров)
4. Изучаем доступные (что странно) рецепты у обоих тренеров

**Текущее обновление ядра:**
Build 290 2020-04-29 11:42

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by ForesterDev** [comment]
Будет исправлено после обновления
