### ISSUE TITLE
[Задание] id 13160 - Сногсшибательное зрелище

### ISSUE THREAD

**Issue by gmOpex** [VirginTeam/WotlkCore#174]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

После принятия задания объект:
[Eye of Dominion] GUID: 51289 ID: 193424
 X: 6474.810059 Y: 2041.050049 Z: 571.463989 MapId: 571
Нет госип меню на преображение в ловца как в по заданиям 13147 и 13146

**Что работает не так?**

После принятия задания объект:
[Eye of Dominion] GUID: 51289 ID: 193424
 X: 6474.810059 Y: 2041.050049 Z: 571.463989 MapId: 571
Нет госип меню на преображение в ловца как в по заданиям 13147 и 13146 Задание выполняется прямым убийством http://ru.wowhead.com/npc=31012

**Как должно работать?**

После принятия задания объект:
[Eye of Dominion] GUID: 51289 ID: 193424
 X: 6474.810059 Y: 2041.050049 Z: 571.463989 MapId: 571
Должен преображать в ловца как в заданиях 13147 и 13146 и с помощью его способностей  задание уже выполняется.
https://youtu.be/EwIlFapPsVI

**Текущее обновление ядра:**

Build 157 2017-05-02 14:02:07 +0400

**Comment by ForesterDev** [comment]
Исправлено, будет применено в обновлении
