### ISSUE TITLE
Не засчитывает достижение

### ISSUE THREAD

**Issue by Imiladris** [VirginTeam/WotlkCore#1740]
**Ссылки и комментарии:**
http://db.logon3.com/?achievement=1283 - Повелитель подземелий
http://db.logon3.com/?achievement=637 - Монастырь Алого Ордена
http://db.logon3.com/?npc=3976 - Командир Могрейн из Алого ордена
http://db.logon3.com/?npc=4543 - Волшебник крови Талнос

**Что работает не так?**

По совету ГМа пишу сюда. Есть достижение на Повелителя подземелий. В него входит достижение по Монастырю Алого Ордена. И вот в освоении  МАО не засчитывается 2 босса. Одного босса, Командира, даже 2 раза убивала, так, на всякий случай. Боссы: Волшебник крови Талнос и Командир Могрейн из Алого ордена. Остальных система засчитала. Инст проходило в одиночку.
 
**Как должно работать?**

Собственно, после убийства ожидала, что они засчитаются, как и все предыдущие.

**Шаги для воспроизведения ошибки:**

1. Заходите в нужную локацию
2. Преодолеваете путь до босса
3. Убиваете босса

**Текущее обновление ядра:**
Build 298 2020-05-08 01:05:10 +0300

**Comment by ForesterDev** [comment]
![image](https://user-images.githubusercontent.com/11771800/81657217-5ef2a700-9440-11ea-9593-daeb05355328.png)

Достижение работает, все засчитывает. Возможно, вы как то пропускаете фазу воскрешения Командира Могрейн из Алого ордена, поэтому вам и не засчитывает

**Comment by Myrskyntuoja** [comment]
Фазу, кстати, сложно не пропустить в овергире - слишком быстрое убийство Вайтмейн оставляет командира мертвым. Помогает разоружиться, частично раздеться и постучать по ней кулаками, остановившись при начале воскрешения.

**Comment by Imiladris** [comment]
Уууу, он еще и воскреситься должен..... Что ж, попробую. Спасибо за совет. Будучи новичком в этой игре, не знаю всех нюансов, а ГМ только посоветовал написать сюда о проблеме. Еще раз спасибо!
