### ISSUE TITLE
Талант 63375 Сокрушительный удар бури

### ISSUE THREAD

**Issue by zyxellgit** [VirginTeam/WotlkCore#1741]
**Ссылки и комментарии:**
Сокрушительный удар бури
http://db.logon3.com/?spell=63375

"Удар бури" с вероятностью 50% / 100% может мгновенно восстановить 20% от базового запаса маны.

**Что работает не так?**

![WoWScrnShot_051720_230603](https://user-images.githubusercontent.com/29210390/82156561-27975680-9895-11ea-97a3-e5db49a4f3e1.jpg)

возвращает 879 маны, что с 1 очком, что с 2 в таланте

дает неверное количество маны

**Как должно работать?**
имеем 6336 маны, 20% от 6336 это: 1267.2

может должен возвращать 1267 маны?

**Шаги для воспроизведения ошибки:**

**Текущее обновление ядра:**

Можно посмотреть в игре, введите в чат команду .server info и скопировать строку начиная с Build с номером и датой. Не забывайте указывать, Live Server или PTR Server, где проводилось тестирование.

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by gorechaser** [comment]
вроде бы базовый запас считается без талантов. сбрось таланты и посчитай заново

**Comment by zyxellgit** [comment]
![WoWScrnShot_051820_010107](https://user-images.githubusercontent.com/29210390/82158756-3258e800-98a3-11ea-9745-b09e83169307.jpg)
20% от 6141?  
1228?
