### ISSUE TITLE
[Объекты] ID 32569 - Апекситовый осколок

### ISSUE THREAD

**Issue by Nanokiller1** [VirginTeam/WotlkCore#1742]
**Ссылки и комментарии:**

https://ru.wowhead.com/item=32569/%D0%B0%D0%BF%D0%B5%D0%BA%D1%81%D0%B8%D1%82%D0%BE%D0%B2%D1%8B%D0%B9-%D0%BE%D1%81%D0%BA%D0%BE%D0%BB%D0%BE%D0%BA

https://ru.wowhead.com/item=32677/%D0%B8%D1%81%D1%82%D0%BE%D1%89%D0%B5%D0%BD%D0%BD%D1%8B%D0%B9-%D0%BF%D0%BB%D0%B0%D1%89

исключение
https://ru.wowhead.com/item=32576/%D0%B8%D1%81%D1%82%D0%BE%D1%89%D0%B5%D0%BD%D0%BD%D0%BE%D0%B5-%D1%85%D1%80%D1%83%D1%81%D1%82%D0%B0%D0%BB%D1%8C%D0%BD%D0%BE%D0%B5-%D1%81%D1%80%D0%B5%D0%B4%D0%BE%D1%82%D0%BE%D1%87%D0%B8%D0%B5

**Что работает не так?**

Есть такие вещи как истощенный посох, плащ, палица, выщербленная двуручная секира и т.д., и при воздействии на них 50ю апекситовыми осколками их можно преобразить, так вот при попытке это сделать персонаж говорит что некуда класть и ничего не делает, хоть место в рюкзаке есть. Хотя преобразовать истощенное кристальное средоточие получается.

**Как должно работать?**

Ожидаемый результат — получение нормального предмета.

**Шаги для воспроизведения ошибки:**

1. Шаг один - имеем в рюкзаке 50 апекситовых осколков и выщербленную двуручную секиру
2. Шаг два - пытаемся воздействовать на секиру осколками.
3. Шаг три - персонаж говорит "я больше не унесу", хотя место есть, и выскакивает сообщение "нет места".
Такие же проблемы возникают при преобразовании остальных "истощенных" вещей, кроме истощенного кристального средоточия.

**Текущее обновление ядра:**

Build 298 2020-05-08 01:05:10 +0300

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by FilDru** [comment]
Точно так же, о том что "нет места", сообщается при попытке сшить плащ из 4х чешуек драконов обитающих в Острогорье: Обсидии, Ярокрыла, Чернокрыла и Инсидиона.
