### ISSUE TITLE
Залы отражений

### ISSUE THREAD

**Issue by Pchela88** [VirginTeam/WotlkCore#1747]
Добрый день администрация virgin 3,3,5 х1 PVe 
В залах  отражений , когда пристом кидаешь защиту от страха   ,мобы всё равно накладывают страх . Можно ли решить эту проблему ? Спасибо за внимание

**Comment by gorechaser** [comment]
страх мобов это оглушение

**Comment by Pchela88** [comment]
gorechaser оглушение  страх и оглушение я могу отличить)

**Comment by ForesterDev** [comment]
О каком заклинании идет речь?

Я нашел только http://db.logon3.com/?spell=72321 - к нему Защита от страха предоставляет иммунитет.

Оформите репорт по правилам
