### ISSUE TITLE
[Предмет] ID 51316 - Незапечатанный сундук

### ISSUE THREAD

**Issue by Sayronych** [VirginTeam/WotlkCore#1749]
после убийства Лича не выпал сундук. viruslider logon3 x1. 
Logon 3 WowCircle Development
Build 304 2020-06-09 22:27:39 +0400

**Comment by Sayronych** [comment]
@GmAlleria шаблон напиши понятный, если он есть. а проблема думаю и так понятная без оформления

**Comment by GmAlleria** [comment]
шаблон проще некуда, если не в состоянии прочесть, можно спросить

**Comment by Sayronych** [comment]
@GmAlleria ок. что не так? или что в запросе не понятно ?

**Comment by Vampirikus** [comment]
14.06.2020 Суднук выпал с Лича в ЦЛК 25 гер
