### ISSUE TITLE
[Задание] ID 13216 - Битва при Валхаласе: возвращение Сигрид Дитя Льда

### ISSUE THREAD

**Issue by jaksik27** [VirginTeam/WotlkCore#1752]
Ссылки и комментарии:

[Задание Битва при Валхаласе: возвращение Сигрид Дитя Льда](https://db.logon3.com/?quest=13216)

Что работает не так?

NPC, Сигрид Дитя Льда, создается скриптом после того как квест принимается игроком у Джейрвив из Валхаласа. После создания NPC должен вступить в бой с игроком, но этого не происходит, он стоит на месте и его нельзя атаковать.

Как должно работать?

После получения квеста NPC появляется и вступает в бой с игроком взявшим этот квест. После убийства NPC квест зачитывается и его нужно сдать, получив опыт и награду, поговорив с NPC Гьоннером Безжалостным.

Шаги для воспроизведения ошибки:

1. Взять задание
2. Убить появившегося NPC
3. Сдать задание

Текущее обновление ядра:

Build 308 2020-06-09 22:27:39 +0400

**Comment by jaksik27** [comment]
Почините пожалуйста квест.

**Comment by Kodekc** [comment]
Будет исправлено в ближайшем обновлении

**Comment by Kodekc** [comment]
Всё, можно перепроверять
