### ISSUE TITLE
[Задание] Слабое место Анатолия id 12330

### ISSUE THREAD

**Issue by jaksik27** [VirginTeam/WotlkCore#1754]
Ссылки и комментарии:

[Ссылка на задание](https://db.logon3.com/?quest=12330)
[Ссылка на нпс Татьяна](https://db.logon3.com/?npc=27627)

Что работает не так?

Отсутствует нип Татьяна (id 27627)

Текущее обновление ядра:

Build 310 2020-06-29 14:31:58 +0400

**Comment by Kodekc** [comment]
Так может кто-то взял задание и выполняет его? Она там в единственном экземпляре как бы
