### ISSUE TITLE
Небольшая проблема с рыбалкой.

### ISSUE THREAD

**Issue by Willozwisp** [VirginTeam/WotlkCore#1757]
**Ссылки и комментарии:**

**Что работает не так?**

Во время заброса "поплавка", когда "клюет", при нажатии ПКМ по "поплавку", ничего не происходит до самого конца КД процесса ловли. Как то в чате встречал этот момент, но на то время у меня это было 5% от всего процесса ловли, не сильно напрягало. Сегодня наверное это было 50%. 

**Как должно работать?**

Не знаю как оно должно работать верно, но предполагаю, что если после нажатия ПКМ по "поплавку", должно быть либо выловлено, либо сорвалась, либо еще что-то в этом духе, а не происходить, НИЧЕГО. Да и сорвалась выглядит странным, на ловле рыбы в зоне 300+, а навык 450.

**Шаги для воспроизведения ошибки:**

**Текущее обновление ядра:**

Последнее обновление ядра: Build 315 2020-07-03 12:16:00 +4000

Можно посмотреть в игре, введите в чат команду .server info и скопировать строку начиная с Build с номером и датой. Не забывайте указывать, Live Server или PTR Server, где проводилось тестирование.

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by gorechaser** [comment]
происходит когда поплавок далеко от игрока.

**Comment by Willozwisp** [comment]
> происходит когда поплавок далеко от игрока.

Не заметил такой закономерности, проверю, отпишусь.

**Comment by Willozwisp** [comment]
Таки да. На более дальних "забросах" прокает "ничего". Но мне кажется что это не нормально. Было бы неплохо это как-то исправить. Одно дело ботоводы не заморачиваются по этому поводу, а другое дело сам сидишь ловишь и такое чуток мешает.

**Comment by Kodekc** [comment]
https://github.com/VirginTeam/WotlkCore/issues/1760
