### ISSUE TITLE
[NPC] ID 23731 - Хейзел Лаграс

### ISSUE THREAD

**Issue by gorechaser** [VirginTeam/WotlkCore#1758]
**Ссылки и комментарии:**
https://ru.wowhead.com/npc=23731

**Что работает не так?**
Скриншот. две одинаковые надписи на 2х разных действиях

**Как должно работать?**

должно быть что то типа посмотреть товары, а не остановиться здесь 
**Шаги для воспроизведения ошибки:**

1. найти нпц
2. нажать правой кнопкой на него 

**Текущее обновление ядра:**

Build 315

![WoWScrnShot_070720_195552](https://user-images.githubusercontent.com/61152135/86785001-5c9d7980-c08c-11ea-848e-ec3480ef3676.jpg)

**Comment by Kodekc** [comment]
Будет исправлено в ближайшем обновлении
