### ISSUE TITLE
[Достижение] ID 1956 - Ученье - свет

### ISSUE THREAD

**Issue by Draudem** [VirginTeam/WotlkCore#176]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Достижение невыполнимо.

**Что работает не так?**

Книги, нужные для достижения, не появляются. Появляются только фальшивки и они не исчезают до дисконнекта.

**Как должно работать?**

На местах спауна должны появляться книги, нужные для достижения. Каждая книга в своем определенном месте. Иногда вместо нужных книг должны появляться фальшивки (другие книги, не нужные для достижения). Каждая книга (нужная или нет) после прочтения должна исчезать через 5 минут, и на ее месте через 3-4 часа должна возникать новая книга (либо та же самая, либо ненужная для достижения).

**Текущее обновление ядра:**

Build 157 2017-05-02 14:02:07 +0400

**Comment by Riazarre** [comment]
Подтверждено.
Требуется добавление скриптов книгам.
