### ISSUE TITLE
[Задание]  ID 5204 - Возмездие Света

### ISSUE THREAD

**Issue by Ataninesa** [VirginTeam/WotlkCore#1763]
**Опишите ошибку**
Отсутствует квестовый моб - Ракайа ID 9518

**Как её воспроизвести**
Шаги для воспроизведения поведения:
1. В локации Оскверненный лес спуститься в Джеденар
2. Дойти до Останков Трея Светогорна
3. Убедиться в отсутствии Ракайи

**Ожидаемое поведение**
Ожидал что Ракайа будет находиться рядом с останками Трея Светогорна

**Дополнительная информация**
https://ru.wowhead.com/quest=5204/%D0%B2%D0%BE%D0%B7%D0%BC%D0%B5%D0%B7%D0%B4%D0%B8%D0%B5-%D1%81%D0%B2%D0%B5%D1%82%D0%B0
https://ru.classic.wowhead.com/npc=9518/%D1%80%D0%B0%D0%BA%D0%B0%D0%B9%D0%B0

**Текущее обновление ядра**
Build 315 2020-07-03 12:16:00 +0400
Logon 3 WowCircle Development

**Comment by gorechaser** [comment]
в этом году я его делал. пройди дальше поищи. она может гулять.
