### ISSUE TITLE
[Задание] ID 25229 - Несколько хороших гномов

### ISSUE THREAD

**Issue by LexaZaycev** [VirginTeam/WotlkCore#1766]
**Опишите ошибку**
Задание "несколько хороших гномов" https://db.logon3.com/?quest=25229 невозможно сдать, так как отсутствует НИП сержант инструктор парагон. По этому нпс был ответ, что: В Build 219 были отключены события Падение Залазана и Операция Гномреган на постоянной основе. Но в этом случае нужно отключить возможность взять это задание, так как НИП https://db.logon3.com/?npc=7937 Главный механик Меггакрут по прежнему его выдает.

**Текущее обновление ядра**
Build 316 2020-07-13

**Comment by GmAlleria** [comment]
Цепочка отключена, это задание нужно удалить

**Comment by LexaZaycev** [comment]
Дело в том, что это задание можно взять снова после отмены, но такого не должно быть раз цепочка отключена. Есть скриншот, но не получается прикрепить.
