### ISSUE TITLE
Задание "С высоты птичьего полета"

### ISSUE THREAD

**Issue by vladik666** [VirginTeam/WotlkCore#1768]
Не работает квест. После того как использую **"Амулет буревестника"** превращаюсь в птицу и она сама летит. Когда прилетаю обратно ничего не происходит.
**Как её воспроизвести**
Шаги для воспроизведения поведения:
1. Перейдите к Исиэль Песнь Ветра.
2. Берем квест "С высоты птичьего полета".
3. Применить заклинание «Амулет буревестника» (Прилагается)
4. Смотри ошибку

**Ожидаемое поведение**
После автоматического полета квест должен быть выполненным, но ничего не происходит. Пытался без бафов тоже не получается.

**Дополнительная информация**
https://ru.wowhead.com/quest=9718/%D1%81-%D0%B2%D1%8B%D1%81%D0%BE%D1%82%D1%8B-%D0%BF%D1%82%D0%B8%D1%87%D1%8C%D0%B5%D0%B3%D0%BE-%D0%BF%D0%BE%D0%BB%D0%B5%D1%82%D0%B0
**Текущее обновление ядра**
Полследнее обновление ядра: Build 316 2020-07-13 14:55:36 +0400 
3.3.5а x1
Logon 3 WowCircle Development

**Comment by GmAlleria** [comment]
дубликат

**Comment by vladik666** [comment]
Что это значит "дубликат"?


вт, 21 июл. 2020 г. в 20:49, Наталья <notifications@github.com>:

**Comment by GmAlleria** [comment]
значит дубликат https://github.com/VirginTeam/WotlkCore/issues/1674
