### ISSUE TITLE
Заклинание Божественное одобрение ID-20216

### ISSUE THREAD

**Issue by Holyreiter** [VirginTeam/WotlkCore#1772]
**Опишите ошибку**
Четкое и краткое описание ошибки.
При использовании [https://db.logon3.com/?spell=20216](url) нет описанного эффекта. При применении исцеляющего заклинания на себя, в чате действий пишет что эффект Божественное одобрение рассеивается, а потом применяется само заклинание. При применении [https://db.logon3.com/?spell=20929](url) как атакующего заклинания, сначала применяется заклинание, потом снимается баф Божественного одобрения.
**Как её воспроизвести**
Шаги для воспроизведения поведения:
1. Используем [https://db.logon3.com/?spell=20216](url)
2. Применяем [https://db.logon3.com/?spell=20929](url) на себя/союзника или [https://db.logon3.com/?spell=19942](url), или [https://db.logon3.com/?spell=10328](url)
3. Используем [https://db.logon3.com/?spell=20216](url)
4. Применяем [https://db.logon3.com/?spell=20929](url) на противника
Не зависит от уровня применяемого заклинания.

**Ожидаемое поведение**
Четкое и краткое описание того, что вы ожидали.
После использования Божественного одобрения вероятность критического срабатывания указанных заклинаний должна быть 100%
**Скриншоты**
![image](https://user-images.githubusercontent.com/29518410/88457538-b508af80-ceb1-11ea-808a-d54e074ef60c.png)

**Дополнительная информация**
Не зависит от уровня применяемых заклинаний.

**Текущее обновление ядра**
316 2020-07-16

**Comment by ForesterDev** [comment]
Повтор https://github.com/VirginTeam/WotlkCore/issues/1625
