### ISSUE TITLE
[Задание] id 3382 - На абордаж!

### ISSUE THREAD

**Issue by gmOpex** [VirginTeam/WotlkCore#178]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Не засчитывает задание

**Что работает не так?**

После отражения нескольких волн атак, задание попросту не засчитывается.

**Как должно работать?**

После начала задания нпс дружественные должны подбегать к линии обороны выстроенной из ящиков и биться вместе с игровом, после должны идти волны наг с нарастающим колличеством, как на скриншотах http://wow.zamimg.com/uploads/screenshots/normal/99218-на-абордаж.jpg http://wow.zamimg.com/uploads/screenshots/normal/72794-на-абордаж.jpg
После задание должно засчитываться

**Текущее обновление ядра:**

Build 157 2017-05-02 14:02:07 +0400

**Comment by Luchass** [comment]
Заселение ужасно кривое, поэтому приходится отходить от Ванессы. Этого делать не надо, иначе не засчитывает.

**Comment by ForesterDev** [comment]
Исправлено, будет применено в обновлении
