### ISSUE TITLE
[Предмет] ID 43343 - Символ обшаривания карманов

### ISSUE THREAD

**Issue by funtastik** [VirginTeam/WotlkCore#1780]
**Опишите ошибку**
Не увеличивает дальность действия способности ID 921 на 5 метров.

**Как её воспроизвести**
Шаги для воспроизведения поведения:
1. Подойти к цели с карманами на максимальное расстояние в 10 метров (способность с символом становится активной).
2. Использовать способность "Обшаривание карманов" (ID 921).
3. Увидеть надпись "Вы слишком далеко и не можете обыскать этот труп"

**Ожидаемое поведение**
Должно увеличивать.

**Скриншоты**
Если применимо, добавьте скриншоты, чтобы объяснить вашу проблему.

**Дополнительная информация**
https://db.logon3.com/?spell=921 - способность "Обшаривание карманов"
По факту дальность действия способности с символом становится немного меньше 10 метров.
На 10 метрах появляется окошко с добычей, но забрать ничего нельзя - пишет, что далеко. При этом с того же расстояния МОЖНО использовать, к примеру, Ошеломление ID 51724 (если взят талант на +5 метров).

**Текущее обновление ядра**
Build 317 2020-07-27 15:01:40 +0400

**Comment by ForesterDev** [comment]
![image](https://user-images.githubusercontent.com/11771800/91413806-b59fb780-e85c-11ea-8086-44b2fb0dedd6.png)
Не могу подтвердить

**Comment by funtastik** [comment]
видео:
https://youtu.be/2faxpNPbeGE
суть в том, что способность "Ошеломление" (https://db.logon3.com/?spell=51724) с талантом (https://db.logon3.com/?spell=14094)  - в сумме тоже получается 10 метров - работает на той же дистанции, а "Обшаривание карманов" с символом - окно добычи открывается, но на автолуте/при клике мышкой забрать добычу с максимальной дистанции нельзя (вверху экрана появляется предупреждение).
