### ISSUE TITLE
[Заклинание] 31852 - Ревностный защитник

### ISSUE THREAD

**Issue by akvaLAngist** [VirginTeam/WotlkCore#1782]
**Описание**
Талант "Ревностный защитник" 3го уровня при активации восполняет 3% максимального здоровья, вместо 30%

**Ожидаемое поведение**
При активации таланта 3го уровня, согласно подсказке должно восполниться 30% здоровья

**Скриншоты**
![Ревностный защитник](https://user-images.githubusercontent.com/70424669/91629675-3ee9f200-e9f5-11ea-89e0-43a76056260f.png)

**Текущее обновление ядра**
Build 317 2020-07-27 Live Server

**Comment by akvaLAngist** [comment]
С увеличением уровня и показателя Защиты (в таланте есть оговорка, что количество исцеления также зависит от показателя защиты) ситуация не изменилась.
Талант всё ещё восстанавливает 3% здоровья, вместо 30%
![Ревностный защитник2](https://user-images.githubusercontent.com/70424669/92114937-dbf4c280-ee1b-11ea-9734-fee4a20f44a0.png)

**Comment by ForesterDev** [comment]
Объем исцеления зависит от защиты, которая дается от шмоток, а не получаемым с уровнем. Максимальный объем исцеления достигается при 140 защиты (без учета защиты получаемой от уровня). Работает корректно
