### ISSUE TITLE
Компенсация опыта для персонажей 80 уровня

### ISSUE THREAD

**Issue by mordrethar** [VirginTeam/WotlkCore#1791]
**Опишите ошибку**
За  прохождение поиска подземелий на 80 уровне награда в виде опыта должна компенсироваться золотом

**Как её воспроизвести**
Шаги для воспроизведения поведения:

1. проити поиск подземелий и получить только золото в тултипе поиска подземелий

Как бы не вижу смысла скринить, но если нужно - заскриню колличество золота  за ргер получаемое

**Текущее обновление ядра**
322 2020-09-15 11:35:40 +0400

**Comment by ForesterDev** [comment]
Раньше отображалось количество золота без компенсации, а сейчас - уже с компенсацией.
