### ISSUE TITLE
[Подземелье] Испытание чемпиона

### ISSUE THREAD

**Issue by mordrethar** [VirginTeam/WotlkCore#1792]
**Опишите ошибку**
нет возможности пропустить ивент

**Ожидаемое поведение**
Должен быть диалог на пропуск ивента, с возможностью сразу запустить выход чемпионов

**Дополнительная информация**
As of Patch 3.2.2, if everyone in the group has seen the event since said patch, you have an option to skip the event.
В случае если все участники видели ивент - он должен скипаться

**Текущее обновление ядра**
build 322 live

**Comment by gorechaser** [comment]
если у всех есть ачива https://db.logon3.com/?achievement=4298 то должен быть пропуск. проверь этот момент

**Comment by GmAlleria** [comment]
работает корректно
