### ISSUE TITLE
Не работает бонус от выполнения заданий на 80ур.- не дается дополнительное золото.

### ISSUE THREAD

**Issue by hellthing89** [VirginTeam/WotlkCore#1796]
Не работает бонус от выполнения заданий на 80ур.- не дается дополнительное золото.

**Comment by ForesterDev** [comment]
Дополнительное золото дается. Просто раньше в окне отображалось лишь базовое количество золота, а также формула компенсации была некорректной. Компенсация составляет 6 бронзы за каждое очко опыта. Отображается сразу конечное значение золота. Для примера 2 скрина на 79 и 80 уровне

![image](https://user-images.githubusercontent.com/11771800/98223850-1e499580-1f6c-11eb-9a91-150da130bc23.png)
![image](https://user-images.githubusercontent.com/11771800/98223871-26a1d080-1f6c-11eb-8451-0f4001aaf9a8.png)
