### ISSUE TITLE
[Квесты] ID - Не могу сделать квест на ШМ ("Сила нечестивости")

### ISSUE THREAD

**Issue by llaexzcyj** [VirginTeam/WotlkCore#1797]
**Опишите ошибку**
Проблема конкретно у моего персонажа (паладин Abv). Не могу сделать квест на ШМ (проф). После того как выпью куклу не появляется панель. Квест отменял, брал заново, антиерор делал, кэш чистил, релогался, перепивал куклой после диспела. Нужна помощь.

**Как её воспроизвести**
Шаги для воспроизведения поведения:
1. Взять квест "Сила нечестивости"
2. Нажать на стол под профессором Мерзоцидом

**Ожидаемое поведение**
Должна появиться панель "куклы" для того что бы пить лужи

**Скриншоты**
![image](https://user-images.githubusercontent.com/73535532/97304680-1fdcd480-186d-11eb-93c6-1ce3fa6cbd2c.png)

**Дополнительная информация**
-----

**Текущее обновление ядра**
Build 324 2020-10-21 12:02:59 +0400

**Comment by gorechaser** [comment]
выруби все аддоны....

**Comment by llaexzcyj** [comment]
Я 3 раз пытаюсь сделать этот квест, предыдущий раз я делал его на другом пк и таже самая ошибка, практически без аддонов (был только рекаунт и хилбот). Так же на этом же аккаунте есть воин, на которого квест сделался без проблема с таким же набором аддонов. + нет ни 1 аддона, который менял бы интерфейс игры.

**Comment by gorechaser** [comment]
интересно. антиерор пробни тож мало ли

**Comment by llaexzcyj** [comment]
Цитата: - "Квест отменял, брал заново, **антиерор делал**, кэш чистил, релогался, перепивал куклой после диспела. "

**Comment by gorechaser** [comment]
сори не заметил что делал

**Comment by llaexzcyj** [comment]
Я попробовал сегодня в 10об выпить куклу без адонов на другом ПК- заработало. Буду стараться на следующей неделе сделать это же в 25-ке.

**Comment by GmAlleria** [comment]
задание работает корректно
