### ISSUE TITLE
[Заклинание] ID 67150 - Бонус 2 предметов Т9 охотника

### ISSUE THREAD

**Issue by gylyty** [VirginTeam/WotlkCore#1799]
**Опишите ошибку**
Укус змеи не наносит критический урон.

**Как её воспроизвести**
1. Надеть 2 предмета Т9 и некоторые предметы на крит для удобства тестирования.
2. Подойти к манекену.
3. Применить заклинание «Укус змеи»
4. Посмотреть в журнал боя и не увидеть записей о критическом уроне.

**Ожидаемое поведение**
При моих 34% крита должно быть около 2 тиков крита из 7 попаданий.

**Скриншоты**
http://itmages.su/images/2020/10/29/2db228880f3d6d9efcf6c438bc49c6b9.jpg
**Дополнительная информация**
https://db.logon3.com/?spell=67150
https://db.logon3.com/?spell=49001

**Текущее обновление ядра** 
Build 324 2020-10-21 12:02:59 +0400
Live Server

**Comment by gylyty** [comment]
Зашел на другого охотника - на нём работает. Есть предположение (не моё), что ошибка связана с дренейским бафом.

**Comment by ForesterDev** [comment]
![image](https://user-images.githubusercontent.com/11771800/98512201-5d832980-227f-11eb-974e-8df422b13473.png)
Работает. Сделайте антиеррор
