### ISSUE TITLE
[Задание] 10284 - Побег из Дарнхольда

### ISSUE THREAD

**Issue by Kpukko** [VirginTeam/WotlkCore#1810]
**Опишите ошибку**
При прохождении подземелья Старые предгорья Хилсбрада в Пещерах времени не работает квест.

**Как её воспроизвести**
Шаги для воспроизведения поведения:

1. Поджечь все казармы
2. Спуститься вниз и сдать/взять квест
3. Меня после этого он начинает игнорировать, хотя должен побежать к выходу.

**Ожидаемое поведение**
После того, как NPC дает квест на его освобождение, у него в диалоге появляется команда, при использовании которой он начинает свое путешествие к свободе.

**Скриншоты**
Если применимо, добавьте скриншоты, чтобы объяснить вашу проблему.

**Дополнительная информация**
Добавьте любой другой контекст о проблеме здесь. Добавьте ссылки с wowhead.com или db.logon3.com на проблемные задания, NPC, заклинания и т.д.
https://db.virgin-wow.com//?quest=10284 - Квест Побег из Дарнхольда

**Текущее обновление ядра**
Можно посмотреть в игре, введите в чат команду .server info и скопировать строку начиная с Build с номером и датой. Не забывайте указывать, Live Server или PTR Server, где проводилось тестирование.

Последнее обновление ядра: Build 330 2020-12-17 16:05:34 +0400 
Игроков онлайн : 1437 (Максимум 2017). Игроков в очереди: 0 (максимум: 0)
Продолжительность работы сервера: 1 Day 6 Hours 38 Minutes 21 Seconds.
Персонаж - Kpuk, Орда, 80 уровень, Сервер  Virgin WoW x1 PvE

**Comment by nreiv** [comment]
делал квест 2 дня назад, всё работает. вероятность 99.9%, что ты просто пропускаешь 1 босса, который спускается к баракам после их поджига и трал ждёт завершения этого события, т.е. убийства босса.
