### ISSUE TITLE
Баг с запечатанным сундуком

### ISSUE THREAD

**Issue by Lightmur** [VirginTeam/WotlkCore#1822]
26.01.2021, завершив квест на Темную Скорбь, залутал с лича запечатанный сундук, который сдал квестгиверу, чтобы получить с него лут, однако обратно я получил тот же сундук со значком квеста и теперь, при нажатии на него, мне пишет, что вы уже выполнили это задание, хотя по факту я лут с сундука не получил, то есть квест завершен некорректно.
Вы лутаете запечатанный сундук с последнего босса цлк, завершив квест на Темную Скорбь, жмете на него, получаете квест, который нужно сдать Дариону Могрейну, чтобы взамен получить сундук, нажав на который правой кнопкой мыши вы должны получить около 5 предметов, которые можно обменять на различные предметы у квестгиверов неподалеку, а по факту получаем в сумку тот же самый запечатанный сундук со значком квеста, нажав на который мы видим такую надпись - вы уже выполнили это задание, то есть предметы с этого сундука невозможно обменять и как-то открыть его невозможно. Скриншотов, к сожалению, приложить не смогу, так как на тот момент вышел из игры. 
Запечатанный сундук, о котором идет речь - https://ru.wowhead.com/item=51315/%D0%B7%D0%B0%D0%BF%D0%B5%D1%87%D0%B0%D1%82%D0%B0%D0%BD%D0%BD%D1%8B%D0%B9-%D1%81%D1%83%D0%BD%D0%B4%D1%83%D0%BA

**Comment by Lightmur** [comment]
UPD. Оказывается сундук с лутом у меня лежал в сумке, я его не сразу смог заметить, но теперь возникла другая проблема - квестовые мобы, которым я могу сдать лут и получить взамен предметы, не стоят в цлк, как мне теперь обменять лут с сундука на предметы?

**Comment by GmAlleria** [comment]
Вам необходимо убить Лича, и сразу после боя сдать предметы

**Comment by Lightmur** [comment]
Спасибо, вопрос решен!
