### ISSUE TITLE
[Рейды] id 33346 - Бумбот XE-321

### ISSUE THREAD

**Issue by gmOpex** [VirginTeam/WotlkCore#187]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

НПС http://ru.wowhead.com/npc=33346 при взрыве наносит очень малый дамаг при взрыве http://ru.wowhead.com/spell=62834
https://pp.userapi.com/c637428/v637428153/6b2d9/oT7B310DJio.jpg

**Что работает не так?**

НПС http://ru.wowhead.com/npc=33346 при взрыве наносит очень малый дамаг при взрыве http://ru.wowhead.com/spell=62834
https://pp.userapi.com/c637428/v637428153/6b2d9/oT7B310DJio.jpg

**Как должно работать?**

Способность http://ru.wowhead.com/spell=62834 Должна наносить от 13000 до 16000 дамага, это известно с любого источника по гайдам на данного бсса.

**Текущее обновление ядра:**

Build 157 2017-05-02 14:02:07 +0400

**Comment by ForesterDev** [comment]
Исправлено
