### ISSUE TITLE
[Рейды] id 34004 - Искра жизни

### ISSUE THREAD

**Issue by gmOpex** [VirginTeam/WotlkCore#189]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Мили-атака Искры жизни довольно специфична и должна наносить урон магией природы

**Что работает не так?**

https://pp.userapi.com/c637428/v637428153/6b2f2/iys03ZA4HtM.jpg

**Как должно работать?**

[19:32:51.238] Life Spark hits Holyblades 7565 (R: 1891)
[19:32:54.839] Life Spark hits Lennath 7161 (R: 2153)
[19:33:34.256] Life Spark crits  Mideci *15982* (R: 1998)
[19:33:38.795] Life Spark hits Lennath 6532 (B: 1365, R: 1025)

ссылка с форума: http://forum.wowcircle.com/showthread.php?t=544525

**Текущее обновление ядра:**
Build 157 2017-05-02 14:02:07 +0400

**Comment by ForesterDev** [comment]
Исправлено
