### ISSUE TITLE
[Задание] id 5219 - Цель: Слезы Далсона

### ISSUE THREAD

**Issue by gmOpex** [VirginTeam/WotlkCore#205]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

НПС http://mop.wowroad.info/?npc=11077 спавнится прямо в котле, что делает не возможным его убийство или нанесение урона.

**Что работает не так?**

http://s018.radikal.ru/i518/1705/0a/e038f2922b87.jpg

**Как должно работать?**

НПС должен спавнится рядом с котлом как на скриншоте http://wow.zamimg.com/uploads/screenshots/normal/21339-хранитель-котла-злобиус.jpg

**Текущее обновление ядра:**

Build 157 2017-05-02 14:02:07 +0400

**Comment by ForesterDev** [comment]
Исправлено. Будет применено в обновлении
