### ISSUE TITLE
[Игровая механика] Автоатака

### ISSUE THREAD

**Issue by Rialzarre** [VirginTeam/WotlkCore#206]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Пропадают автоатаки у персонажей, в зависимости от скорости атаки

**Что работает не так?**

Чем быстрее скорость атаки, тем больше атак "пропадают", что является крайне критичным для таких классов, как разбойник, и друид.
Кот, скорость 1.00, за 300 сек нанес 274 атаки.
http://i46.fastpic.ru/big/2017/0516/b3/6ad77cc5321bb3b29a7930f154ebb4b3.jpg

Мишка, скорость 2.50, за 300 сек нанес 116 атак.
http://i46.fastpic.ru/big/2017/0516/16/1e00dce65cc2a9417fccbbc53102e016.jpg

Рога, скорость 1.30, за 120 сек нанес 88 атак.
http://i46.fastpic.ru/big/2017/0516/e2/9577458f7590186a81dfa0ab96e85de2.jpg

**Как должно работать?**

Кот, скорость 1.00, за 300 сек должен нанести 300 атак.
Мишка, скорость 2.50, за 300 сек должен нанести 120 атак.
Рога, скорость 1.30, за 120 сек должен нанести 92 атаки.

Обсуждение по этому репортук велось в теме http://forum.wowcircle.com/showthread.php?t=479232

**Текущее обновление ядра:**

Репорт проверялся на x1 PvE:
```
[16:18:21] Последнее обновление ядра: Build 157 2017-05-02 14:02:07 +0400
[16:18:21] Игроков онлайн: 2693 (максимум: 4810). Игроков в очереди: 0 (максимум: 0).
[16:18:21] Продолжительность работы сервера: 1 Day(s) 17 Hour(s) 16 Minute(s) 58 Second(s).
[16:18:21] Серверная задержка: 30.
```

**Comment by Kodekc** [comment]
Проблема связана с клиент-серверным обменом пакетов (другими словами проблема сетевой-серверной задержки в обмене данными)

**Comment by xARCHIMEDESx** [comment]
Это не возможно компенсировать как-то со стороны сервера? И влияет ли это только на автоатаку, или любая атака может пропасть?

**Comment by xARCHIMEDESx** [comment]
Нет случайно ли тут перерасчета свингтайма со стороны сервера, как в случаи гкд?
Типо относительно статов на сервере считается свингтайм тоже, и сравнивается с тем, что пришло от клиента. Если атака, которая приходит от клиента, попадает в "окно", которое расчитал сервер, то она засчитывается, если не попадает - то не засчитывается. В таком случае, из-за задержки, пакет с атакой не попадает в просчитаное ему окно, в время, в которое он должен был вложится, и атака "пропадает", так как серв ее игнорит. Типо это левое что-то, атака должна быть раньше
