### ISSUE TITLE
[Группа заданий] ID 6622/6624 - Очередь на медобслуживание

### ISSUE THREAD

**Issue by gmOpex** [VirginTeam/WotlkCore#207]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Добавьте описание проблемы здесь.

**Что работает не так?**

НПС http://ru.wowhead.com/npc=12920 и http://ru.wowhead.com/npc=12939 не выдают задания 6622/6624 после выполнения условия получения http://ru.wowhead.com/quest=6623 и http://ru.wowhead.com/quest=6625

**Как должно работать?**

НПС http://ru.wowhead.com/npc=12920 и http://ru.wowhead.com/npc=12939 не выдают задания 6622/6624 после выполнения условия получения http://ru.wowhead.com/quest=6623 и http://ru.wowhead.com/quest=6625

Как должно работать:

НПС http://ru.wowhead.com/npc=12920 и http://ru.wowhead.com/npc=12939 Должны выдавать задания 6622/6624 после выполнения условия получения http://ru.wowhead.com/quest=6623 и http://ru.wowhead.com/quest=6625

**Текущее обновление ядра:**

Build 157 2017-05-02 14:02:07 +0400

**Comment by GmAlleria** [comment]
Актуально в Build 268

**Comment by ForesterDev** [comment]
![image](https://user-images.githubusercontent.com/11771800/87155758-9361d280-c2cc-11ea-8d04-3ae92e001179.png)
![image](https://user-images.githubusercontent.com/11771800/87155928-e045a900-c2cc-11ea-8e9a-667495fcb4b6.png)
