### ISSUE TITLE
[Игровая механика] Неправильная работа системы аггро у мобов.

### ISSUE THREAD

**Issue by Nattpyre** [VirginTeam/WotlkCore#21]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Неправильная работа системы аггро у мобов.

**Что работает не так?**

После того, как моб убьет пета/суммона он просто стоит и ничего не делает.

**Как должно работать?**

После убийства пета/суммона моб должен атаковать следующую цель с максимальным количеством аггро.

**Шаги для воспроизведения ошибки:**

1. Атаковать петом/саммоном моба
2. Ударить разок самому, при этом не переагривая моба с пета/суммона
3. Позволить мобу убить пета/суммона
4. Можно безнаказанно бить моба сколько угодно, он не будет сопротивляться

Проверялось на водяном элементале у мага, но подозреваю, что с остальными петами/суммонами та же ситуация.

**Текущее обновление ядра:**

Live Build 151 2017-04-03 15:25:08 +0400

**Comment by ForesterDev** [comment]
Не удалось воспроизвести.
