### ISSUE TITLE
[Задание] ID 13133 - Поиски древнего героя

### ISSUE THREAD

**Issue by gmOpex** [VirginTeam/WotlkCore#216]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

http://ru.wowhead.com/quest=13133 нпс http://ru.wowhead.com/npc=30886 не следует за персонажем до нпс http://ru.wowhead.com/npc=30232 после применения на http://ru.wowhead.com/npc=30884 http://ru.wowhead.com/item=43166

**Что работает не так?**

http://ru.wowhead.com/quest=13133 нпс http://ru.wowhead.com/npc=30886 не следует за персонажем до нпс http://ru.wowhead.com/npc=30232 после применения на http://ru.wowhead.com/npc=30884 http://ru.wowhead.com/item=43166

**Как должно работать?**
http://ru.wowhead.com/quest=13133 нпс http://ru.wowhead.com/npc=30886 должен следовать за персонажем до нпс http://ru.wowhead.com/npc=30232 после применения на http://ru.wowhead.com/npc=30884 http://ru.wowhead.com/item=43166
https://youtu.be/r4RDcjTL9Uc

**Текущее обновление ядра:**

Build 157 2017-05-02 14:02:07 +0400

**Comment by ForesterDev** [comment]
Исправлено, проверьте после рестарта

**Comment by Skellan** [comment]
Квест снова не работае (билд 194) - при нахождении Искальдера среди спящих НПЦ, на него юзаешь http://wowroad.info/?item=43166 , он просто исчезает и ничегоо не происходит => запоротая цепочка

**Comment by MiceRus** [comment]
Не исправлено! Только что пробовал - точно как описывает Skellan commented 6 days ago.
Искальдер просто исчезает

**Comment by gmKroshka** [comment]
Рекомендую иногда обращать внимание на метки в репорте.
Он был переоткрыт и ожидает правок

**Comment by MiceRus** [comment]
Сорри, увидел Исправлено и подумал что это последнее :)

**Comment by Kodekc** [comment]
Все репорты являются бессрочными

**Comment by levrules** [comment]
210 build. По прежнему не работает :( 16 паков прошло и не изменилась ситуация квеста (

**Comment by VetalOKAY** [comment]
Я не уверен, что его вообще будут фиксить. С таким подходом, как на л3 вообще не удивительно что онлайн скатился, люди уходят ибо неадекватная администрация и нету прогресса по фиксу багов. Зато тут один чудак ГМ отвечает мол, будете флудить вообще не починим :D
На х1 было много знакомых, которые ушли на х5 играть, и не жалеют. Советую и вам, ибо толку нету ждать. Сам давно ушел, но за этой темой слежу подпиской через почту

**Comment by Holyway** [comment]
Ты смотри тебя еще забанят тут сейчас :D

**Comment by VetalOKAY** [comment]
Ой да мне уже не раз "угрожали" местные "угрожатели" (ГИЭМы) мол забанет, вот ваще похуй, не поверишь)

**Comment by ForesterDev** [comment]
Исправлено. Будет применено в обновлении

**Comment by Hellsingoff** [comment]
А точно починили? Точно-точно? Или снова сломали? Все мобы пассивно агрессивны. Не нападают, но и поговорить невозможно. При атаке мешающихся рядом мобов на игрока агрится вся комната квестовых мобов. Но даже если не атаковать никого - всё равно они "красные" (раньше были "жёлтые") и нет возможности разговора. Смотрел за другими игроками - у них все идентично. Никто не может с ними говорить, при атаке мешающих мобов агрится пол комнаты квестовых.

**Comment by Hellsingoff** [comment]
Проверил спустя пару дней - ситуация идентична. Мобы враждебны, а не нейтральны, как следствие не выходит с ними поговорить и цепочка снова мертва.
