### ISSUE TITLE
[Задание] ID 1090 - Приказы Геренцо

### ISSUE THREAD

**Issue by Alexdaros** [VirginTeam/WotlkCore#236]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

В задании Приказы Геренцо не запускается скрипт 

**Что работает не так?**

Не запускается скрипт 

**Как должно работать?**

должен запустится скрипт который должен призвать мобов и игрок должен защитить пузника npc=4276

**Текущее обновление ядра:**
Build 158 2017-05-18 12:45:36 +0400 live сервер

**Comment by Riazarre** [comment]
Нет скрипта на НПЦ 4276

**Comment by Ewropa** [comment]
https://github.com/TrinityCore/TrinityCore/commit/6f7cf0a795308dfa8a99d58974836b4ab0af2177
https://github.com/serayn/rpworld_trinitycore_III/commit/7fc4306134ae7a704cfa3d623e3c122549e2f139

**Comment by Kodekc** [comment]
- Добавлены скрипты для задания. (Merge Trinity)
- Удалены некоторые NPC, которые призываются скриптом.
- Перезаселен Рудник Ветрорезов

Локально протестировано - Работает. Изменения будут применены в ближайшем обновлении
