### ISSUE TITLE
[NPC] ID 10506 - Киртонос Глашатай

### ISSUE THREAD

**Issue by Rialzarre** [VirginTeam/WotlkCore#237]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Множественный призыв босса http://ru.wowhead.com/npc=10506

**Что работает не так?**

1. Босса можно призывать несколько раз за 1 проход. Каждое убийство дает лут.
2. Босса можно призывать без квеста http://ru.wowhead.com/quest=5384

**Как должно работать?**

1. Босс может призываться только 1 раз за пронос инста.
> От bakss (5,511 – 1·12·26) 2010-09-06 (Обновление 3.3.5)		
Призвать можно только 1 раз за 1 поход.

2. Пруфов, к сожалению, не нашел.

**Текущее обновление ядра:**

x1, 158 Билд.

**Comment by Plasmashield** [comment]
А что не так со вторым пунктом? Босс и должен призываться без квеста. После выполнения кв с боссов можно лутать кровь и призывать его, так и должно быть.

**Comment by Riazarre** [comment]
Допускаю, что можно призвать без квеста.
Но факт множественного призыва остается.
