### ISSUE TITLE
[Заклинание] ID 47475 - Мощный удар

### ISSUE THREAD

**Issue by Gooldark** [VirginTeam/WotlkCore#241]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

ID 47475 - Мощный удар
http://wowroad.info/?spell=47475

**Что работает не так?**

Каст мощного удара не останавливает таймер автоатаки на время каста (автоатаки продолжаются во время каста).

**Как должно работать?**

Во время каста мощного удара таймер автоатаки должен останавливаться на время каста.

**Доказательства**

Пруф можно найти в патчноуте 3.0.2(http://eu.battle.net/wow/ru/game/patch-notes/3-0-2): Slam now suspends the weapon swing timer rather than resetting it/Способность «Мощный удар» теперь не сбрасывает отсчет времени между замахами, а временно приостанавливает отсчет.

Сейчас все фурики сервера просто кастуют мощный удар во всех дырах в ротации, выигрывая на этом 1-2к дпса. А должны использовать его только по проку Прилив крови.
Видео с серкуля - https://youtu.be/3YU6f9dxXBw

Аддон Кварц показывает что свинг тайм приостанавливается на время каста мощного удара.

**Текущее обновление ядра:**

28.05.2017.

**Перенесено**

http://forum.wowcircle.com/showthread.php?t=598163

**Comment by MedoOf** [comment]
> 10/16 12:55:59.008  SWING_DAMAGE,0x000000000046AFE7,"Фупфпуфкуфкп",0x511,0xF1300079AA07A1AB,"Героический тренировочный манекен",0x10a28,286,0,1,0,0,0,nil,1,nil
> 10/16 12:56:00.510  SPELL_DAMAGE,0x000000000046AFE7,"Фупфпуфкуфкп",0x511,0xF1300079AA07A1AB,"Героический тренировочный манекен",0x10a28,50783,"Мощный удар",0x1,846,0,1,0,0,0,1,nil,nil
> 10/16 12:56:00.676  SWING_DAMAGE,0x000000000046AFE7,"Фупфпуфкуфкп",0x511,0xF1300079AA07A1AB,"Героический тренировочный манекен",0x10a28,230,0,1,0,0,0,nil,nil,nil

**Comment by gmRial** [comment]
Исправлено, после обновления.
