### ISSUE TITLE
[Группа заданий] 6069/6070 - Путь охотника

### ISSUE THREAD

**Issue by gmOverfire** [VirginTeam/WotlkCore#242]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Что работает не так?**

Предлагаются два задания (тролль), хотя цепочка уже выполнена. 

**Как должно работать?**
 
Не должно быть этих квестов, если персонаж начал выполнение квестов на приручение питомца, либо уже выполнил.

**Текущее обновление ядра:**

Live: Build 158

**Comment by ForesterDev** [comment]
Исправлено. Будет применено в обновлении
