### ISSUE TITLE
[Заклинание] ID 49576 - Хватка смерти

### ISSUE THREAD

**Issue by Gooldark** [VirginTeam/WotlkCore#243]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

ID 49576 - Хватка смерти

**Что работает не так?**

ID 49576 - Хватка смерти не имеет минимальную дистанцию в пвп

**Как должно работать?**

ID 49576 - Хватка смерти должна иметь минимальную дистанцию в пвп равную 8 метров, так же как у чаржа. При использовании спела ближе чем 8 метров должна выскакивать красная фраза "Target is too close" в верху экрана.
В пве я подозреваю спел так же не должен притягивать цель в тех же условиях, однако скорее всего он юзался как таунт(этот момент не точный, так как были видео на босах, где дк юзал его в упор, но как известно боссов грип не притягивает итак).

**Доказательства**

Старая тема - http://forum.wowcircle.com/showthread.php?t=387250

http://www.mmo-champion.com/threads/699292-Heroic-Lich-King-Kill-PTR-3-3-3-Build-11623?p=7401005&viewfull=1#post7401005
Блю пост an unintended change as a result of a bug trying to fix something else. Death Grip won't change between 3.3.2 and 3.3.3.
Что переводиться, как - Непреднамеренное изменение в результате ошибочной попытки фиксануть что-то еще. Дес грип не хотят менять между 3.3.2 и 3.3.3.

То есть близарды допустили непреднамеренный фикс.

http://eu.battle.net/wow/ru/game/patch-notes/4-0-6

Упоминание в кате - Ранее в подсказке к способности «Хватка смерти» не указывалось, что для ее применения в PvP требуется минимальная дистанция в 8 метров. Это было исправлено. 

Похоже, что Близард допустили опечатку в кате, и этой фразой имели ввиду что минимальный радиус убран, так как тултип никогда не менялся, и даже были видосы с более поздних версий каты, где видно грипы в упор. То есть баг просуществовал с 3.3.3 до 4.0.6 и это подтверждают видео:
https://www.youtube.com/watch?v=ufVSmB_hH0s - 4:28
http://4put.ru/pictures/max/1046/3213782.jpg
http://www.warcraftmovies.com/movieview.php?id=145367 - 11:10
http://4put.ru/pictures/max/1046/3213762.jpg
https://www.youtube.com/watch?v=77B8XGBXarw - 0:55
https://www.youtube.com/watch?v=haY0S9aaoh0 - 5:55

**Текущее обновление ядра:**

28.05.2017.

**Comment by Saramalar** [comment]
https://forum.wowcircle.com/showthread.php?t=387024
В данной теме приведено не мало пруфов, что это фикс с ПТРа, которого на лайве не было.
