### ISSUE TITLE
[Игровая механика] Прохождение подземелья через систему поиска подземелий

### ISSUE THREAD

**Issue by gmRial** [VirginTeam/WotlkCore#244]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)
**Описание**

Баг в системе ПП, актуальный для игроков низких уровней.

**Что работает не так?**

При прохождении ПП, игроки могут выгнать кого-либо с подземелье через голосование. После чего, лидер регает ПП, и берет в группу персонажа 80-уровня. 
Чар 80-го уровня проносит все подземелье, все остальные члены группы получают опыт, и деньги. При убийстве последнего босса - остальным членам группы засчитывается успешное прохождение ПП, и выдается сумка с наградой и дополнительный опыт.
http://joxi.ru/l2ZR0VbhwavKq2

**Как должно работать?**

Если лидер берет высокоуровневого игрока в группу - он не может регнуть ПП до тех пор, пока все игроки не будут соответствовать критериям поиска. Если группа уже стоит в очереди - она выходит из очереди, соответственно если высокоуровневый игрок пронесет подземелье - награду в виде сумки и доп. опыта никто не получит.

**Шаги для воспроизведения ошибки:**

1. Зарегать поиск подземелий соло, или в составе группы.
2. Начать прохождение.
3. Исключить одного игрока.
4. Заново встать в очередь.
5. Взять высокоуровневого игрока.
6. Ничего не делать, ждать, пока высокоуровневый игрок пройдет подземелье.

**Текущее обновление ядра:**

PTR: Build 28

**Comment by ForesterDev** [comment]
Требуется повторная проверка (не воспроизводится)

**Comment by gmKroshka** [comment]
Будет исправлено после обновления
