### ISSUE TITLE
[Существа] ID 32408 - Матиас Нетлер

### ISSUE THREAD

**Issue by gmOpex** [VirginTeam/WotlkCore#255]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

http://ru.wowhead.com/npc=32408 ошибка фазирования. После выполнения задания http://ru.wowhead.com/quest=13393 и http://ru.wowhead.com/quest=13304 не появляется в фазе игрока, или фаза игрока не меняется.

**Что работает не так?**

http://ru.wowhead.com/npc=32408 ошибка фазирования. После выполнения задания http://ru.wowhead.com/quest=13393 и http://ru.wowhead.com/quest=13304 не появляется в фазе игрока, или фаза игрока не меняется.

**Как должно работать?**

После выполнения задания http://ru.wowhead.com/quest=13393 или http://ru.wowhead.com/quest=13304 должен сразу же появится нпс http://ru.wowhead.com/npc=32408 что собственно и видно на последних секундах видео https://youtu.be/bDYESrLAT0g

**Текущее обновление ядра:**

Build 159 2017-05-29 11:50:59 +0400

**Comment by MiceRus** [comment]
Так и не поправили? А что такого сложного? Ну запихайте вы этого мальчишку во все фазы

**Comment by Talikar** [comment]
Ребят 2019 на дворе а цепочка так и не исправлена! Изменения будут??
