### ISSUE TITLE
[Задание] ID 6621 - Король Гиблой Чащи

### ISSUE THREAD

**Issue by gmRial** [VirginTeam/WotlkCore#258]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Что работает не так?**

По заданию http://ru.wowhead.com/quest=6621 нельзя установитьhttp://ru.wowhead.com/item=16972 в нужной точке.
После установки должны спавниться http://ru.wowhead.com/npc=12921, после них http://ru.wowhead.com/npc=12918, после его убийства должен спавниться объект http://ru.wowhead.com/object=178227, в котором лежит http://ru.wowhead.com/item=16976

Сейчас квест выполняется хаком, http://wowroad.info/?item=16976 лежит в единственном http://wowroad.info/?npc=12921 рядом с местом установки знамени.

**Как должно работать?**

Должен работать правильно. 
https://youtu.be/JU6SOq_1tJM?t=56

**Текущее обновление ядра:**

Virgin: Build 159

**Перенесено**

http://forum.wowcircle.com/showthread.php?t=390364

**Comment by Kodekc** [comment]
Исправлено. Реализованы базовые скрипты. Изменения будут применены в ближайшем обновлении
