### ISSUE TITLE
[Задание]  ID 8924 - В поисках эктоплазмы

### ISSUE THREAD

**Issue by murdalak** [VirginTeam/WotlkCore#259]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

В задании неправильно падают квест предметы

**Что работает не так?**

Предметы падают с нужных мобов независимо от того, ставил игрок "Дистиллятор эктоплазмы" или нет

**Как должно работать?**

Квест итемы должны падать только при установке игроком на землю Дистиллятора эктоплазмы

**Шаги для воспроизведения ошибки:**

1. Берём квест
2. Убиваем квест мобов для квеста в Силитусе/Зимних ключах/Восточных чумных землях без установки дистиллятора эктоплазмы
3. Лутаем квест предмет

**Текущее обновление ядра:**

Build 159 2017-05-29 11:50:59 +0400

**Comment by Devinette** [comment]
http://forum.wowcircle.com/showthread.php?t=637941&p=5762136&viewfull=1#post5762136
