### ISSUE TITLE
[Задание] ID 11494 - Заряженные молнией артефакты

### ISSUE THREAD

**Issue by Ewropa** [VirginTeam/WotlkCore#26]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Не работает задание http://ru.wowhead.com/quest=11494

**Что работает не так?**

При "диалоге" с верстаком, диалога как такового нет, ничего не происходит, все стоит мертво и персонаж не "лезет на верстак" 

**Как должно работать?**

Одеваем костюм голема и топаем по координатам 72.72 67.56 - там будет спуск к раскопкам.
Ходим по раскопкам и ищем кристаллы. У кристаллов используем умение голема "Сбор информации". Если дворфы пристают, то используем умение "Блеф", не дожидаясь очередных фраз от них.

**Шаги для воспроизведения ошибки:**

1. Примерять костюм
2. Поговорить с верстаком

**Текущее обновление ядра:**

Build 151 2017-04-03 15:25:08 +0400

**Comment by ForesterDev** [comment]
Исправлено, проверьте после обновления

**Comment by MiceRus** [comment]
Не работает! Что там исправили - не в курсе. Но хоть в голема и садишься - ничего не собирается
Сколько ни жал на кнопку "Сбор информации" так ни одного и не засчитали.
Ачив опять в пролете.

**Comment by gmKroshka** [comment]
Будет исправлено после обновления
