### ISSUE TITLE
[Заклинание] ID 33831 - Сила природы

### ISSUE THREAD

**Issue by Gooldark** [VirginTeam/WotlkCore#261]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

ID 33831 - Сила природы

Репорт незначительный, продолжение https://github.com/VirginTeam/VirginCore/issues/85

**Что работает не так?**

Когда друид вызывает трентов на всех в округе появляется анимация зеленой вспышки.(возможно от этого включается пвп флаг или каким-то образом может зависать комбат)

**Как должно работать?**

Анимация зеленой вспышки должна быть только у трентов

**Текущее обновление ядра:**

03.06.2017

**Comment by ForesterDev** [comment]
Исправлено
