### ISSUE TITLE
[Заклинание] ID 48113 - Молитва восстановления

### ISSUE THREAD

**Issue by Gooldark** [VirginTeam/WotlkCore#262]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Баг очень важный.
http://wowroad.info/?spell=48113
ID 48113 - Молитва восстановления и все временные петы: временные петы: элем мага, клоны, тренты, волки, горгуля, финда.

**Что работает не так?**

а) Молитва восстановления может перепрыгивать на временных петов, так же как и использоваться на них, но при получении урона петами, молитва назад в группу не возвращается и исчезает при отхиле пета.

б) Молитва прыгает в беспорядочной последовательности

в) Когда молитва исцеляет цель на приста вешается комбат, так же та цель с которой вылетает молитва восстановления получает комбат.

**Как должно работать?**

а) Молитва восстановления должна иметь возможность возвращаться в пати после хила временных петов.

б) Молитва должна прыгать на цель с наименьшим количеством хп в процентном соотношении!!!

в) Не должна вводить исцеляемую цель в комбат, так же как и приста. Бой должен появляться только один раз при наложении(не срабатывании, а первом наложении) пристом этого спела, на цель в бою.

**Доказательства**

https://www.youtube.com/watch?v=EwLOcI4h_kg - 0:56 - прист кидает в рогу молитву, затем она перепрыгивает на элема, на котором висит порча, и после получения урона возвращается в рога, а потом опять улетает в элема. Самих бафов невидно, так как молитву сразу сбивают, но зато хорошо видна анимация.

а) По идее если вар даст бш в приста, то прист должен иметь возможность вызвать на него финду, дать в себя молитву, и затем выхиливаться за счет того что она прыгает между финдой и пристом, но сейчас это не работает, молитва не возвращается с временных петов.

б) в этом же видео, в том же моменте видно что молитва прыгает преимущественно между элемом и рогой, так как у них наименьшие значение хп в процентах. 

Лог: http://worldoflogs.com/reports/ul76xm556v85ir2v/log/
Фильтр:[{"spellNames": ["Prayer of Mending"], "actorNames": ["Caliste"]}]

По логу видно, что молитва возвращается в пала Wiingman, так как он сильно проседает.

> [22:12:54.910] Caliste casts Prayer of Mending on Wiingman
[22:12:55.066] Caliste's Prayer of Mending fades from Gamadias
[22:12:55.066] Wiingman gains Prayer of Mending from Caliste
[22:12:55.547] Caliste's Prayer of Mending fades from Wiingman
[22:12:55.565] Caliste Prayer of Mending Wiingman +6929
[22:12:55.565] Kaetzchen gains Prayer of Mending from Caliste
[22:12:55.612] Caliste's Prayer of Mending fades from Kaetzchen
[22:12:55.861] Caliste Prayer of Mending Kaetzchen +5831 (O: 1098)
[22:12:55.861] Wiingman gains Prayer of Mending from Caliste
[22:12:57.413] Caliste's Prayer of Mending fades from Wiingman
[22:12:57.483] Caliste Prayer of Mending Wiingman +0 (O: 6929)
[22:12:57.483] Jinhe gains Prayer of Mending from Caliste
[22:13:11.321] Caliste's Prayer of Mending fades from Jinhe
[22:13:11.604] Caliste Prayer of Mending Jinhe +5094 (O: 1836)
[22:13:11.604] Wiingman gains Prayer of Mending from Caliste
[22:13:11.946] Caliste's Prayer of Mending fades from Wiingman
[22:13:12.351] Caliste Prayer of Mending Wiingman +*13512*

в) в отличие от орехов молитва может срабатывать от дот, собственно это и вызывает забагивание комбата на целях

Ситуация: рог, на котором висят доты, залосал чтобы рестелснуться. Противник переключился на приста. Прист хилиться и вешает на себя молитву. В свою очередь молитва срабатывает, перелетает на рогу, где еще раз срабатывает от дот и держит рога в комбате. В итоге рог не может рестелснуться.

**Текущее обновление ядра:**

03.06.2017

**Перенесено**

http://forum.wowcircle.com/showthread.php?t=569399
http://forum.wowcircle.com/showthread.php?t=529554

**Comment by ForesterDev** [comment]
Исправлено
