### ISSUE TITLE
[Заклинание] ID 53341 - Руна оплавленного ледника

### ISSUE THREAD

**Issue by zyxellgit** [VirginTeam/WotlkCore#268]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Руна оплавленного ледника http://wowroad.info/?spell=53341
прок от руны должен использоваться на ударах магии льда или тьмы (ледяной удар, воющий ветер, итп)

**Что работает не так?**

прок от руны сливается на автоатаку некроз http://wowroad.info/?spell=51465
http://forum.wowcircle.com/attachment.php?attachmentid=366157&d=1471544249

**Как должно работать?**

некроз(или озноб) не должен использовать прок от руны

**Comment by Riazarre** [comment]
А где пруфы?

**Comment by zyxellgit** [comment]
ахз как пруфать, пойдет коммент с вовхеда? http://www.wowhead.com/forums&topic=54444/question-about-cinderglacier
на вовциркуле уже были такие темы 3 года назад http://forum.wowcircle.com/showthread.php?t=300246
как я понял цитата с элитистов "Blood Boil, Icy Touch, Death Coil and any Scourge Strike will consume a charge of the buff. Death and Decay, diseases and appropriate weapon procs will be buffed by the damage but not consume a charge"

**Comment by Riazarre** [comment]
Думаю сойдет, разработчик посмотрит и решит.

**Comment by zyxellgit** [comment]
а чего подтверждать если никто не чинил?

**Comment by GmAlleria** [comment]
Подтверждать актуальность, достаточно написать Актуально, без лишних слов
