### ISSUE TITLE
[Задание] ID 11495 - Нежный звук грома

### ISSUE THREAD

**Issue by Ewropa** [VirginTeam/WotlkCore#27]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Не работает задание [Нежный звук грома](http://ru.wowhead.com/quest=11495)

**Что работает не так?**

При "диалоге" с верстаком, диалога как такового нет, ничего не происходит, все стоит мертво и персонаж не "лезет на верстак" 

**Как должно работать?**

https://www.youtube.com/watch?v=O98BhP_zJBU&feature=youtu.be

**Шаги для воспроизведения ошибки:**

1. Примерять костюм
2. Поговорить с верстаком

**Текущее обновление ядра:**

Build 151 2017-04-03 15:25:08 +0400

**Comment by ForesterDev** [comment]
Исправлено, проверьте после обновления

**Comment by MiceRus** [comment]
В голема садишься. Идешь к руне. Жмешь кнопку и ничего!

**Comment by ForesterDev** [comment]
В пещере ивент с участием Локена, после него засчитывается квест 
![image](https://user-images.githubusercontent.com/11771800/38493290-b40fa726-3c02-11e8-9fa2-51c37ab2343b.png)
