### ISSUE TITLE
[Задание] id 11703 - Добраться до Гетри

### ISSUE THREAD

**Issue by nikonavr** [VirginTeam/WotlkCore#272]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

По квестовой цепочке отправили поговорить с НПС. НПС стоит, ему нельзя сдать квест.

**Что работает не так?**

Нельзя сдать квест и продолжить квестовую цепочку
http://imgur.com/a/MIYl7

**Как должно работать?**

Завершить у НПС квест - http://ru.wowhead.com/quest=11703
Получить новый квест - http://ru.wowhead.com/quest=11705

**Шаги для воспроизведения ошибки:**

1. Взять квест http://ru.wowhead.com/quest=11703
2. Придти к Тенелову Гетри
3. ?????
4. Квест невозможно сдать 

**Текущее обновление ядра:**

Logon 3 WowCircle Development
[20:50:20] Последнее обновление: Build 159 2017-05-29 11:50:59 +0400
logon3 WotLK x1

**Comment by Riazarre** [comment]
Видимо, #106 не исправлен окончательно.

**Comment by nikonavr** [comment]
Сегодня прилетел к нипу, квест завершил, взял новый. Все работало нормально
http://imgur.com/a/wYzDG

**Comment by Riazarre** [comment]
Потому что после проверки, Гетри был перемещен на свое место разработчиком.

**Comment by Ewropa** [comment]
Там несколько причин зависания скриптов
1. вайп
2. не реснулся нип http://ru.wowhead.com/npc=25618 при запуске задания http://ru.wowhead.com/quest=11705, http://ru.wowhead.com/npc=25729 пришел на стрелку, но его там никто не ждет - это одна из 99% причин зависания скрипта

**Comment by Ewropa** [comment]
http://forum.wowcircle.com/showthread.php?t=569473

**Comment by Mystic1813** [comment]
до сих пор не взаимодействует .

**Comment by gmRial** [comment]
Пока репорт не будет исправлен, обращайтесь в игровым мастерам в игре через систему тикетов.

**Comment by Kodekc** [comment]
Актуальный репорт?

**Comment by Rorshah** [comment]
Если не чинили значит актуальный.
Что за вера в то что всё само исправится :)

**Comment by Kodekc** [comment]
Множество раз просто переписывали это задание и никак оно не заработает нормально, что там за алгоритмы забагивания, что скрипты не отрабатывают нормально

**Comment by Pavlov718** [comment]
Наверное, нужно было бы ГМ-ам его потестить, что бы понять актуально или нет

**Comment by GmAlleria** [comment]
дубль #106
