### ISSUE TITLE
[Группа NPC] Стражники Штормграда

### ISSUE THREAD

**Issue by Luchass** [VirginTeam/WotlkCore#274]
**Описание:**

http://wowroad.info/?npc=68
http://wowroad.info/?npc=1976
http://wowroad.info/?npc=1423

**Что работает не так?**

Часть NPC ходит по текстурам (особенно на Соборной площади), часть расположена не в том месте.
http://i.imgur.com/dbtQ5cb.jpg
http://i.imgur.com/x4YgP67.jpg

**Как должно работать?**

Не должно так быть

**Текущее обновление ядра:**

Build 29 Open Test

**Comment by Kodekc** [comment]
Теперь после перезаселения, где-то по два-три стражника в одной точке координат
