### ISSUE TITLE
[Рейд] Испытание крестоносца/Испытание великого крестоносца (ID 65920 Настигающие шипы)

### ISSUE THREAD

**Issue by gmKroshka** [VirginTeam/WotlkCore#28]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

После закапывания Ануб'Арака, на случайного игрока вешается дебафф [Вас преследует Ануб'арак](http://wowroad.info/?spell=67574) и за игроком начиняют гоняться [Настигающие шипы](http://wowroad.info/?spell=67574).После того, как они догоняют игрока и протыкают [Прокалыванием](http://wowroad.info/?spell=65919), либо не догоняют (спрятался за ледяной лужей), они забагиваются - стоят на месте вплоть до истечения времени, когда Ануб'Арак должен вылезти из под земли,. В рабочем варианте, дебафф [Вас преследует Ануб'арак](http://wowroad.info/?spell=67574) должен переброситься на другого живого игрока и гоняться за ним.
Актуально во всех режимах сложности

**Что работает не так?**

Ануб'Арак не выбирает новую цель для преследования

**Как должно работать?**

Ануб'Арак преследует нового игрока

**Шаги для воспроизведения ошибки:**

1. Получаем дебаф [Вас преследует Ануб'арак](http://wowroad.info/?spell=67574)
2. Умираем, либо заходим за лужу

**Текущее обновление ядра:**

Build 151 2017-04-03 15:25:08 +0400

**Comment by MedoOf** [comment]
Up

**Comment by MedoOf** [comment]
Работает
