### ISSUE TITLE
[Задание] ID 12607 - Поимка мамонта

### ISSUE THREAD

**Issue by TheBezik** [VirginTeam/WotlkCore#280]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Нету NPC Твердобивневый мамонт

**Что работает не так?**

NPC нету, Раньше они были, но квестовый предмет не использовался. 

**Как должно работать?**

Должны быть NPC - Твердобивневый мамонт и работать уздечка для мамонта.

**Шаги для воспроизведения ошибки:**

1. Взять квест: Поимка мамонта
2. Наблюдать отсутствие NPC

**Текущее обновление ядра:**

Build 159 2017-05-29 11:50:59 +0400

Можно посмотреть в игре, введите в чат команду .server info и скопировать строку начиная с Build с номером и датой. Не забывайте указывать, Live Server или PTR Server, где проводилось тестирование

**Comment by pavaknsk** [comment]
Твердобивневые мамонты есть, хоть и меньше, чем должно быть, но при касте на них уздечки ничего не происходит.

**Comment by odino4estvo** [comment]
Спустя год, квест так и не поправили... ай ай ай.

**Comment by gmOverfire** [comment]
@odino4estvo и?
Репорт может висеть день/неделю/месяц/год/два и т.п., это нормально.

**Comment by gmOverfire** [comment]
К слову, задание работает, мамонты есть http://joxi.ru/DrloLO6Tvq09xA
Но квестовый предмет не юзается, это да. Хотя и без него можно сесть на мамонта.

**Comment by Anarom** [comment]
Все еще не работает... мамонты есть, но уздечка не юзается

**Comment by wewedetiy** [comment]
квест не работает, нет мамонта....

**Comment by gmOverfire** [comment]
Квест работает, мамонты тут http://db.logon3.com/?npc=28379

**Comment by wewedetiy** [comment]
теперь мамонты есть, уздечка не работает, юзаешь а в ответ ничего

**Comment by Hellsingoff** [comment]
Сегодня пробовали. Сесть не используя уздечку нет возможности, применение уздечки не даёт ничего. Квест на данный момент не работает судя по всему.

**Comment by SergeyVyach** [comment]
поправьте квест, пожалуйста

**Comment by ForesterDev** [comment]
Исправлено, будет применено в обновлении
