### ISSUE TITLE
[Группа NPC] - Восточные чумные земли

### ISSUE THREAD

**Issue by murdalak** [VirginTeam/WotlkCore#282]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

В восточных чумных землях, в часовне последней надежды находятся нейтральные по отношению к игроку npc-квестгиверы, которых игрок случайно может атаковать. Это "Римблат Землекрушитель" [ID=16134], "Роган Убийца" [ID=16131], "Охотник Леопольд" [ID=16132] и "Матеус Обрушивающий Гнев" [ID=16133]. Эти npc не относятся к фракциям, т.е. это не относится к случаю когда игрок может поставить "противник" против какой-либо фракции и получит возможность атаковать npc.

**Что работает не так?**

Игрок может атаковать любого из них.

**Как должно работать?**

У игрока не должно быть возможости атаковать этих npc.

**Шаги для воспроизведения ошибки:**

1. Подходим к любому из данных npc и начинаем бой

**Текущее обновление ядра:**

Build 159 2017-05-29 11:50:59 +0400

**Comment by Kodekc** [comment]
Исправлено. Изменения будут применены в ближайшем обновлении
