### ISSUE TITLE
[Группа NPC] id 2784 - Магни Бронзобород, id 7999 -Тиранда Шелест Ветра

### ISSUE THREAD

**Issue by zyxellgit** [VirginTeam/WotlkCore#289]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

пошли мы тут значицца по ачиве  "за орду" http://ru.wowhead.com/achievement=619

**Что работает не так?**
бьем лидеров этих а у них невосприимчивость к  чуме http://ru.wowhead.com/spell=138490, ознобу http://ru.wowhead.com/spell=55095, к чумке с удара чумы http://ru.wowhead.com/spell=56361
возможно еще к каким

**Как должно работать?**

вроде все болячки,проклятия итд и тп на них должно вешаться
![wowscrnshot_061117_021801](https://user-images.githubusercontent.com/29210390/27014062-63e8286c-4f0a-11e7-83b9-85d2adb34bec.jpg)

**Шаги для воспроизведения ошибки:**

1. Шаг один
2. Шаг два
3. Шаг три

**Текущее обновление ядра:**
Последнее обновление ядра: Build 159 2017-05-29 11:50:59 +0400

**Comment by zyxellgit** [comment]
вроде не один бронзобород, еще на тиранде было кажись http://ru.wowhead.com/npc=7999
надо всех чтоль идти смотреть?

**Comment by Riazarre** [comment]
Ну конечно, желательно на всех перепроверить.

**Comment by Riazarre** [comment]
Подтверждаю, Тиранда тоже невосприимчива.

**Comment by Kodekc** [comment]
Нет точной информации по иммунитетам лидеров фракций.

**Comment by gmOverfire** [comment]
Был бы иммунитет - это бы освещалось на многих источниках, в т.ч. на вовхеде в руско- и агнлоязычных комментариях, датированных < 2010 годом.
