### ISSUE TITLE
[Заклинание] Id 65661 - Угроза Тассариана

### ISSUE THREAD

**Issue by duressq** [VirginTeam/WotlkCore#291]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Способность наносит в двое больше урона чем должна.

**Что работает не так**

 Персонаж делает дополнительный  удар правой рукой, а не  дополнительный удар левой, что приводит к двойному урону способностей. 

**Как должно работать?**

Талант должен наносить дополнительный удар ЛЕВОЙ рукой.

Дополнительные удары левой рукой от таланта должны наносить меньше урона и способности должны бить в зависимости от урона левой руки и оружия в ней.

**Comment by duressq** [comment]
Build 159 2017-05-29

**Comment by Gooldark** [comment]
пруфов нет чтоль? не советую фиксить без инфы все подряд.

**Comment by duressq** [comment]
Вот как работает талант https://www.youtube.com/watch?v=0HFZvIl9fDc 
Дополнительный урон такой же как основной, а должен быть намного меньше.
Правильная работа https://www.youtube.com/watch?v=iQZoR8-FB4I
Баг очевиден.

**Comment by Riazarre** [comment]
Видео с других пираток не может быть доказательством правильной работы.

**Comment by duressq** [comment]
А то что дополнительный урон такой же как основной не является доказательством не правильной работы?

**Comment by duressq** [comment]
http://eu.battle.net/wow/en/game/patch-notes/3-2-0
В патч ноуте четко написано, что удар должен наносить половину урона.

**Comment by duressq** [comment]
Достаточно что бы тему закрыли и починили баг?
Не ок играть когда у спека в двое завышен урон

**Comment by Riazarre** [comment]
Разработчик прочтет и решит, достаточно ли информации или нет.

**Comment by duressq** [comment]
Ну и че с темой?
Месяц назад сделал баганые фросты бегают бьют. Что нужно больше информации значек вы убрали, чинить собираетесь?

**Comment by Gooldark** [comment]
пару логов с офы:
http://worldoflogs.com/reports/ul76xm556v85ir2v/details/220/
http://worldoflogs.com/reports/rt-1lqg7umi678ncyix/details/19/

**Comment by gmRial** [comment]
Исправлено, после обновления.
