### ISSUE TITLE
[NPC] ID 10776 - Айс Вентурон

### ISSUE THREAD

**Issue by murdalak** [VirginTeam/WotlkCore#305]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Моб не появляется

**Что работает не так?**

Моб не появляется в данже

**Как должно работать?**

Моб должен появиться в подземелье Вершина Чёрной горы после убийства и снятия шкуры с босса Зверь

**Шаги для воспроизведения ошибки:**

1. Идём в Вершину Чёрной горы
2. Убиваем Зверя
3. Снимаем шкуру

**Текущее обновление ядра:**

Build 160 2017-06-15 12:40:01 +0400

**Comment by Devinette** [comment]
http://forum.wowcircle.com/showthread.php?t=508540

**Comment by sega693** [comment]
Описание:
http://db.logon3.com/?npc=10776#summoned-by Айс
http://db.logon3.com/?npc=10430#skinning Зверь

Что работает не так?
Моб не появляется в данже

Как должно работать?
> Судя по английским комментариям Айс Вентурон появляется после "свежевания" Зверя, т.е. снятия шкуры после убийства. Так что, если Вы обладаете сием навыком - флаг Вам в руки! Если нет, то обратитесь за помощью к шкуродёру. Удачи =)

Шаги для воспроизведения ошибки:
Идём в Вершину Чёрной горы
Убиваем Зверя
Снимаем шкуру

Текущее обновление ядра:
Build 177 2017-11-28 11:50:44 +0400
