### ISSUE TITLE
[Группа предметов] Свитки силы/ловкости

### ISSUE THREAD

**Issue by TepaMeTp** [VirginTeam/WotlkCore#306]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

http://wowroad.info/?item=43464 и http://wowroad.info/?item=43466 неправильно взаимодействуют с другими баффами

**Что работает не так?**

http://wowroad.info/?item=43464 http://wowroad.info/?item=43466 сбиваются http://wowroad.info/?spell=48073  http://wowroad.info/?spell=48074
http://wowroad.info/?item=43464 http://wowroad.info/?item=43466 стакаются с http://wowroad.info/?spell=57623 http://wowroad.info/?spell=48470 
При этом свиток не баффает игрока, если на нем висит http://wowroad.info/?spell=48073 http://wowroad.info/?spell=57623

**Как должно работать?**
http://wowroad.info/?item=43464 http://wowroad.info/?item=43466 не должны сбиваться http://wowroad.info/?spell=48073  http://wowroad.info/?spell=48074, т.к. характеристики разные
С http://wowroad.info/?spell=48470 и http://wowroad.info/?spell=57623 возможны два варианта

Вариант №1 - http://wowroad.info/?item=43464 http://wowroad.info/?item=43466 считаются "большим" баффом и должны заменяться http://wowroad.info/?spell=57623 http://wowroad.info/?spell=58646

Вариант №2 - http://wowroad.info/?item=43464 http://wowroad.info/?item=43466 считаются "малым" баффом и должны заменяться http://wowroad.info/?spell=48470

**Шаги для воспроизведения ошибки:**

1. Шаг один - баффнуть на себя http://wowroad.info/?item=43464 илиhttp://wowroad.info/?item=43466
2. Шаг два - баффнуть на себя http://wowroad.info/?spell=57623
3. Шаг три - для проверки "отмены" баффнуть http://wowroad.info/?spell=48073

**Текущее обновление ядра:**

 Build 160 2017-06-15 12:40:01 +0400

**Comment by ForesterDev** [comment]
Исправление применено. Проверьте сейчас

**Comment by TepaMeTp** [comment]
Проверено, дух свитки не сбивает, горн сбивает.

**Comment by zyxellgit** [comment]
свиток ловкости http://db.logon3.com/?item=43464 не накладывается поверх рыбы на ловкость http://db.logon3.com/?item=42999,
![wowscrnshot_120717_010227](https://user-images.githubusercontent.com/29210390/33683050-6ae7ea22-daeb-11e7-826f-0be89a61be68.jpg)


но если сначала использовать свиток а потом еду, то работает 
![wowscrnshot_120717_010319](https://user-images.githubusercontent.com/29210390/33683016-4aedf982-daeb-11e7-9f8b-f0288bdb45d9.jpg)

**Comment by kalipsa988** [comment]
с чего ты взял, что дар дикой природы не должен стакаться со свитками на силу и агилу?
свитки с силой и агилой должны перебиваться горном и не должны накидываться, если горн весит
Это покажется абсурдом, но пристобафы должны мешать накладыванию свитков
https://ru.wowhead.com/item=43464/%D1%81%D0%B2%D0%B8%D1%82%D0%BE%D0%BA-%D0%BB%D0%BE%D0%B2%D0%BA%D0%BE%D1%81%D1%82%D0%B8-viii#english-comments вся инфа тут
