### ISSUE TITLE
[Задание] ID 9165 - Подорожная

### ISSUE THREAD

**Issue by Luchass** [VirginTeam/WotlkCore#31]
**Описание:**

http://ru.wowhead.com/quest=9165
http://wowroad.info/?quest=9165

**Что работает не так?**

Стражник Дидье (ID 16226) не идет с мулами. Задание нельзя никак пройти

**Как должно работать?**

Стражник Дидье должен идти с мулами два раза в день. Если его провести он должен дать задание вместе с Подорожной (ID 22593). Приедет Фельдмаршал Чамберс (ID 16254) и у него можно будет подписать ее. Сдать задание

**Шаги для воспроизведения ошибки:**

1. Взять задание
2. Ничего происходит

**Текущее обновление ядра:**

PTR Build 20 2017-04-05 12:06:47 +0400

**Comment by ForesterDev** [comment]
Исправлено
