### ISSUE TITLE
[Задание] ID 11065 - Ловим летучих скатов!

### ISSUE THREAD

**Issue by Lexwood** [VirginTeam/WotlkCore#314]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Не засчитывается привод НИП "Пойманный летучий скат" в конечную точку.

**Что работает не так?**

НИП "Пойманный летучий скат" при сопровождении его в конечную точку на Заставе Стражи Небес (27,51) исчезает, но его поимка не засчитывается в счетчик прогресса выполнения задания.

**Как должно работать?**

При достижении конечной точки НИП "Пойманный летучий скат" должен исчезнуть, а нам должны засчитать его в прогресс выполнения задания (1/5 Поймано летучих скатов).

**Шаги для воспроизведения ошибки:**

1. В Острогорье (Запределье) на локации Застава Стражи небес взять у НИПа "Страж небес Кати" задание "Ловим летучих скатов!"
2. Атаковать НИП "Летучий скат" (находятся неподалеку), снизив его уровень здоровья до <30% и использовать на нем квестовый предмет "Веревочный аркан"
3. Довести появившегося НИП "Пойманный летучий скат" в конечную точку на Заставе Стражи Небес (27,51)

**Текущее обновление ядра:**

Build 160 2017-06-15 12:40:01 +0400

**Comment by Wunder29** [comment]
Почините уже этот КВ (есть мнение, что это сделать много проще "Самых маленьких созданий")
Остался 1 КВ до "на пиках скал"

**Comment by odino4estvo** [comment]
Аналогично. Остался один квест на закрытие ачивы...

**Comment by Awegod** [comment]
Когда будет информация о фиксе квеста? Заявка весит почти год.

**Comment by gmKroshka** [comment]
Информации нет

**Comment by SergeyVyach** [comment]
Просим также обратить внимание на этот квест + следующий за ним дейлик, так как неработоспособность закрывает квестовую цепочку.

**Comment by MiceRus** [comment]
кого интересует прокачка, если бабки исправно капают в казну?

**Comment by Kodekc** [comment]
Внесены исправления. Будут применены в ближайшем обновлении
