### ISSUE TITLE
[Задание] ID 11954 - Ответный удар

### ISSUE THREAD

**Issue by DarkCloud069** [VirginTeam/WotlkCore#317]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Невозможно получение данного ежедневного квеста с огненного солнцеворота http://ru.wowhead.com/quest=11954, а соответственно и невозможен фарм пылающих цветов.

**Что работает не так?**

Квест невозможно взять у Старейшина Служителей Земли - http://ru.wowhead.com/npc=26221.

**Как должно работать?**

Это задания должно быть ежедневным, его можно брать и выполнять каждый день пока не закончится праздник.

**Шаги для воспроизведения ошибки:**

1. Прийти в любую столицу и попытаться взять этот квест у нпс
2. Обнаружить, что нпс не дает квест.

**Текущее обновление ядра:**

Build 160 2017-06-15 12:40:01 +0400

**Comment by Draudem** [comment]
Ты говоришь, что невозможно ПОВТОРНОЕ получение. А этот квест на нашем сервере разве дают хоть один раз?

**Comment by DarkCloud069** [comment]
подправил репорт
