### ISSUE TITLE
[Задание] ID 3566 - Восстань, Обсидион!

### ISSUE THREAD

**Issue by murdalak** [VirginTeam/WotlkCore#321]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Нельзя убить Обсидиона и Латорика Чёрного

**Что работает не так?**

После активации алтаря Сунтары появляется Латорик Чёрный, который ведёт диалог с Дориусом. После диалога Латорик исчезает, а Обсидион также лежит неактивным

**Как должно работать?**

После диалога Латорик должен напасть на игрока вместе с Обсидионом, чтобы игрок мог их убить

**Шаги для воспроизведения ошибки:**

1. Берём квест 
2. Активируем алтарь
3. Смотрим диалог

**Текущее обновление ядра:**

Build 160 2017-06-15 12:40:01 +0400

**Comment by GmAlleria** [comment]
Обсидион не активируется, если репутацию с Пиратской бухтой указать враждебными, часть задания можно выполнить убив Латорика Черного

**Comment by Vindenta** [comment]
https://youtu.be/QSY3-xtYVME - включена враждебность (можно лутануть голову, обсидион не активен)
https://youtu.be/qMwcLp36DOw - просто диалог который заканчивается без нападения нпс на персонажа
Logon 3 WowCircle Development
Последнее обновление ядра: Build 267 2019-07-29 12:18:21 +0400

**Comment by ForesterDev** [comment]
Фикс судя по всему не попал в это объявление, залью заново
