### ISSUE TITLE
[NPC] ID 16905 - Непреклонный колдун

### ISSUE THREAD

**Issue by Rialzarre** [VirginTeam/WotlkCore#322]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Что работает не так?**

Когда у моба заканчивается мана для заклинаний, он стоит на месте. Игрок может отойти и не получать урона. 
UPD: Мобы ватные. В прямом смысле. https://youtu.be/FkHMR1OCTkg

**Как должно работать?**

Моб должен подбежать к игроку, и бить врукопашную, пока не накопит маны для заклинания.

**Текущее обновление ядра:**

PTR Build 31
UPD: Virgin Build 162

**Comment by Ewropa** [comment]
не воспроизводится баг, мобы прекрасно атакуют, после того как слили ману

**Comment by Riazarre** [comment]
Добавил видео в репорт, актуально по сегодняший день на живом сервере.

**Comment by Vampirikus** [comment]
Актуально
Колдун наносит 1 удар и стоит ничего не делает
