### ISSUE TITLE
[Задание] ID 12121 - Увидимся в другом мире

### ISSUE THREAD

**Issue by Rorshah** [VirginTeam/WotlkCore#326]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Невозможно выполнить задание

**Что работает не так?**

не засчитывает задание

**Как должно работать?**

1. взял задание
2. Добежал до гонга.
3. стукнул в гонг.
4. постоял подождал когда из тебя вышел дух
5. Добежать до НИПа внутри склепа, который засчитывает задание

**Шаги для воспроизведения ошибки:**
Все делать как описано.
1-4 работает. 5. не выходит.

**Текущее обновление ядра:**

[19:37:34] Ïîñëåäíåå îáíîâëåíèå ÿäðà: Build 160 2017-06-15 12:40:01 +0400
[19:37:34] Èãðîêîâ îíëàéí: 4257 (ìàêñèìóì: 4527). Èãðîêîâ â î÷åðåäè: 0 (ìàêñèìóì: 0).
[19:37:34] Ïðîäîëæèòåëüíîñòü ðàáîòû ñåðâåðà: 2 Day(s) 5 Hour(s) 13 Minute(s) 45 Second(s).
[19:37:34] Ñåðâåðíàÿ çàäåðæêà: 112.
[19:37:34] Ñëåäóþùåå íà÷èñëåíèå î÷êîâ àðåíû: 02.07.2017  10:22

**Comment by Riazarre** [comment]
Нельзя поговорить с НПС

**Comment by nordwindd** [comment]
Насколько я помню, бить в гонги нужно с южной стороны - иначе не запускается ивена и не будет защитано условие "Смерть полководца Джин'аррака".
После этого можно спокойно сдавать квест НИПу внутри склепа.

**Comment by Rorshah** [comment]
Да. Странное дело. Ударил с южной стороны (т.е. там три гонга, один возле входы и два других подальше - вот еще немного дальше от входа чем те два других) и засчитало квест и квестгивер внутри стоит со знаком вопроса. Может конечно за это время поправили, но в целом итог: квест выполнил.
