### ISSUE TITLE
[Задание] ID 1948 - Волшебные предметы

### ISSUE THREAD

**Issue by Luchass** [VirginTeam/WotlkCore#33]
**Описание:**

http://ru.wowhead.com/quest=1948
http://wowroad.info/?quest=1948

**Что работает не так?**

После использования 10 тотемных палочек Сухокожих (Item Id 7273) не появляется Заряженный молнией жезл (Object Id 103662), с которого берется одноименный предмет (Item Id 7272), требуемый для задания.

**Как должно работать?**

Появление заряженного молнией жезла

**Шаги для воспроизведения ошибки:**

1. Использовать 10 тотемных палочек Сухокожих около Внешнего Круга Обуздания в Нагорье Арати
2. Жезл не появляется

Скрипт:
https://github.com/Cryostorm/SunwellCore/blob/fb958096a149be3a51d888b6e05fdb81241f7b0b/sql/quest%20fixes/zones/ek_kalimdor.sql#L75
https://github.com/Cryostorm/SunwellCore/blob/fb958096a149be3a51d888b6e05fdb81241f7b0b/src/server/scripts/World/go_scripts.cpp#L102

**Текущее обновление ядра:**

PTR Build 20 2017-04-05 12:06:47 +0400

**Comment by ForesterDev** [comment]
Исправлено, проверять после обновления
