### ISSUE TITLE
[Задание] ID 12690 - Нам это на руку

### ISSUE THREAD

**Issue by Rorshah** [VirginTeam/WotlkCore#332]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

http://wowroad.info/?quest=12690
Способ выполнения задания

**Что работает не так?**

ну там по заданию надо подчинить http://wowroad.info/?npc=28843
подвести к толпе квестовых чувачков и обилками
законтроленного моба всех растерзать.
Но по факту ни одна абилка урона никому не наносит.
Приходится всех опять же убивать самому вручную.

**Текущее обновление ядра:**

[23:25:05] Èãðîêîâ îíëàéí: 3710 (ìàêñèìóì: 5064). Èãðîêîâ â î÷åðåäè: 0 (ìàêñèìóì: 0).
[23:25:05] Ïðîäîëæèòåëüíîñòü ðàáîòû ñåðâåðà: 3 Day(s) 9 Hour(s) 1 Minute(s) 18 Second(s).
[23:25:05] Ñåðâåðíàÿ çàäåðæêà: 39.
[23:25:05] Ñëåäóþùåå íà÷èñëåíèå î÷êîâ àðåíû: 09.07.2017  10:22

**Comment by Rorshah** [comment]
забавно. Не работает. до сих пор.
Что обидно.. 60 тел с полным ХП вручную вынести - и за них 0 опыта.

**Comment by Rorshah** [comment]
забавно. Прошел еще год. Не работает. до сих пор.
Что обидно.. 60 тел с полным ХП вручную вынести - и за них 0 опыта.

**Comment by pigheadby** [comment]
актуально
