### ISSUE TITLE
[Задание] ID 12713 - Предательство

### ISSUE THREAD

**Issue by Rorshah** [VirginTeam/WotlkCore#333]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

http://wowroad.info/?quest=12713
способ исполнения

**Что работает не так?**

необходимый для выполнения подконтрольный моб бездействует против Драккуру
http://wowroad.info/?npc=28931

**Как должно работать?**

законтролил моба и разорвал Драккуру

**Текущее обновление ядра:**

[00:08:55] Ïîñëåäíåå îáíîâëåíèå ÿäðà: Build 160 2017-06-15 12:40:01 +0400
[00:08:55] Èãðîêîâ îíëàéí: 2868 (ìàêñèìóì: 5064). Èãðîêîâ â î÷åðåäè: 0 (ìàêñèìóì: 0).
[00:08:55] Ïðîäîëæèòåëüíîñòü ðàáîòû ñåðâåðà: 3 Day(s) 9 Hour(s) 45 Minute(s) 7 Second(s).
[00:08:55] Ñåðâåðíàÿ çàäåðæêà: 33.
[00:08:55] Ñëåäóþùåå íà÷èñëåíèå î÷êîâ àðåíû: 09.07.2017  10:22

**Comment by Rorshah** [comment]
Ну пока в обличии плети Дракуру не агрится. Если снять обличие то идут ваншоты от Друкуру а законтроленный моб.. ну такое вобщим, как и раньше.
Щас призову бисовых гильдийцев. Может поможет.

**Comment by Nimlotnik** [comment]
Квест всё так же не работает... с 17 года квесты висят... ужас... может дадите мне write доступ к БД я сам поправлю эти квесты (напишу сюда фикс, а вы примените если посчитаете нужным)

**Comment by Climss** [comment]
Актуально
Build 273 2019-10-14 14:10:59 +0400 Logon 3 x1 PvE

**Comment by pigheadby** [comment]
актуально
