### ISSUE TITLE
[Задание] ID 3982 - Что происходит?

### ISSUE THREAD

**Issue by odino4estvo** [VirginTeam/WotlkCore#334]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Меня прислал сюда Тралл, и я нахожусь под его покровительством. Неужели ты думаешь, что эти фигляры смогли бы меня поймать? Я разведчик, и я им поддался специально, чтобы собрать информацию. *Гор'шак понижает голос.*
Император Тауриссан похитил принцессу Стальгорна. Она сейчас здесь, в этом городе! Надо думать, когда старый Магни об этом узнал, его чуть удар не хватил. *Гор'шак смеется.* 
Тихо! Слышишь? Это стражники! ЗАЩИЩАЙСЯ!

**Что работает не так?**

После взятия квеста у НПС "Командир Гор'Шак" не появляются нужные для убийства НИП, после убийства, которых засчитывается выполнение вышеуказанного квеста... Квест на форуме циркуля висит с 2014 года, последний раз на форуме в этой теме я отписывался еще за февраль месяц нынешнего года... Неужели так и не починили? Рушится очень важная и интересная цепь квестов... Решил поднять этот тике и здесь... 

**Как должно работать?**

Цитирую с форума: "После взятия квеста появляются мобы в несколько волн, от которых нужно защитить квестодателя Командир Гор'шак. После их убийства квест сдается этому же НИПу и получается следующий кв в цепи"

Ожидаемый результат — то, чего вы ожидали при выполнении ваших действий. Процесс правильной работы:

"Вступите в схватку со стражниками и останьтесь в живых." (аля вовхеад...)

**Шаги для воспроизведения ошибки:**

1. Взятие квеста у НПС http://wowroad.info/?npc=9020
2. Подождать, пока сработают скрипты разговора и появления мобов...
3. Перебить их, сдать квест, и взять следующий...

**Текущее обновление ядра:**

Build 162 2017-07-03

**Comment by Santaria** [comment]
https://github.com/TrinityCore/TrinityCore/issues/11115
