### ISSUE TITLE
[Задание] ID 13152 - Визит к доктору

### ISSUE THREAD

**Issue by Rorshah** [VirginTeam/WotlkCore#335]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**
http://wowroad.info/?quest=13152
Доктор пропадает на 50% ХП

**Что работает не так?**

Первая часть работает отменно.
Жмякаешь на прикованную цепь, Заплатень освобождается, выходит Доктор Сабнок..
Небольшой разговор и начинается бой.
примерно на середине боя Доктор просто испаряется. Заплатень спустя пару секунд тоже куда-то девается.
и всё.
При этом нет разницы бить Доктора или просто смотреть. 
Спустя какое-то время эти два персонажа просто испаряются

**Как должно работать?**

ну не знаю. Предположу что пришел, запустил ивент, убил доктора. Квест завершен.

**Шаги для воспроизведения ошибки:**

**Текущее обновление ядра:**

[17:41:27] Ïîñëåäíåå îáíîâëåíèå ÿäðà: Build 162 2017-07-03 14:02:08 +0400
[17:41:27] Èãðîêîâ îíëàéí: 3426 (ìàêñèìóì: 4821). Èãðîêîâ â î÷åðåäè: 0 (ìàêñèìóì: 0).
[17:41:27] Ïðîäîëæèòåëüíîñòü ðàáîòû ñåðâåðà: 2 Day(s) 4 Hour(s) 3 Minute(s) 10 Second(s).
[17:41:27] Ñåðâåðíàÿ çàäåðæêà: 35.
[17:41:27] Ñëåäóþùåå íà÷èñëåíèå î÷êîâ àðåíû: 09.07.2017  10:22

**Comment by Riazarre** [comment]
Оформляйте заголовки по шаблону, плиз.

**Comment by ForesterDev** [comment]
https://github.com/VirginTeam/WotlkCore/issues/1515
