### ISSUE TITLE
[Игровая механика] ПвП-флаг

### ISSUE THREAD

**Issue by ar4i2018** [VirginTeam/WotlkCore#337]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Бью элитного моба в Нордсколе ([Алистос](http://ru.wowhead.com/npc=27249)), подошли два игрока противоположной фракции и убили меня, хоть PvP режим у меня был отключен.
Похожие ситуации повторяются неоднократно. Бывает что PvP включается сам по себе (Никого не бил, ничего такого не делал.)

**Что работает не так?**

Что-то работает не так — это 100%.

**Как должно работать?**

Нормально должно работать!

**Шаги для воспроизведения ошибки:**

1. Шаг один. 10 раз убедиться что PvP режим отключен.
2. Шаг два. Пойти по своим делам.
3. Шаг три. Получить по щам от игроков противоположной фракции.

**Текущее обновление ядра:**

WoW Circle 3.3.5a x1 PvE 
Build 162 2017-07-03 14:02:08 +0400

**Comment by Ewropa** [comment]
все то оно так, но есть одно "но"
если как говоришь чуваки пришли с включенным пвп режимом, а ты моба бьешь массовыми заклинаниями, то как думаешь, можешь шмальнуть и стоящего рядом игрока с пвп режимом?
Думаю, можешь и у тебя автоматически включается пвп режим

**Comment by TepaMeTp** [comment]
Пвп режим включается при каком-либо активном действии (атака/бафф) с включенным пвп режимом или же при использовании противоположной фракцией пульта управления паровым танком. Возможно есть еще какие-либо предметы, способные вызвать активацию пвп режима без каких-либо действий со стороны "жертвы"

**Comment by Riazarre** [comment]
Неинформативно, нужно более детальное описание всех проблем.

**Comment by ar4i2018** [comment]
@Риазарре, Подробнее некуда. Просто идешь, а пвп режим может включиться сам по себе. Т.е не так. Пвп режим выключен(Иконки пвп режима нет. Когда наводишь на пвп режим, галочка стоит на "Отключить"), но  игроки могут меня убить.
@Эвропа, Я играл друидом-медведем. Массовыми атаками в одну цель не бил. Вар сделал рывок ко мне и они меня вдвоем убили. (Они стояли далеко)

**Comment by Riazarre** [comment]
@ar4i2018 были ли у вас какие-либо pvp квесты?

**Comment by ar4i2018** [comment]
@Riazarre не было

**Comment by zyxellgit** [comment]
поддерживаю. Есть вероятность попасть на пвп даже если ПвП квестов нет, флаг выключен, и не в зоне впвп. 
доказательств нету, только недоумение от факта

**Comment by ar4i2018** [comment]
@Riazarre , какая информация вам нужна?

**Comment by Riazarre** [comment]
@ar4i2018 я считаю, что желательны подробности, конкретные случаи с детальным описанием, чтобы разработчик смог понять, что конкретно нужно поправить. Он уберет этот тег, если он не нужен.

**Comment by ForesterDev** [comment]
Нет дополнительно информации
