### ISSUE TITLE
[Группа заданий] Атака пехоты

### ISSUE THREAD

**Issue by Luchass** [VirginTeam/WotlkCore#34]
**Описание:**

Альянс:
http://wowroad.info/?quest=13284
http://ru.wowhead.com/quest=13284

Орда:
http://wowroad.info/?quest=13301
http://ru.wowhead.com/quest=13301

**Что работает не так?**

Полностью не работает ивент задания. Командиры отрядов никуда не идут.

**Как должно работать?**

Они должны идти вверх по горе. Игрок их должен сопроводить. Задание засчитывается.

**Шаги для воспроизведения ошибки:**

1. Взять квест
2. Ничего не происходит

**Текущее обновление ядра:**

PTR Build 20 2017-04-05 12:06:47 +0400

**Comment by Riazarre** [comment]
Актуально.
