### ISSUE TITLE
[Задание] ID 12259 - Тан Волдруна

### ISSUE THREAD

**Issue by ar4i2018** [VirginTeam/WotlkCore#341]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Задание [[Тан Волдруна]](http://ru.wowhead.com/quest=12259)

Дракон "Огнедышащий" не летает, а ползает по земле. Из-за этого нельзя подобраться к квестовому мобу чтобы начался бой, и весь нанесенный урон моб отхиливает.
Может он не летает из-за того что у меня не изучены полеты в Нордсколе? =)

**Что работает не так?**

Дракон не летает, из-за этого нельзя подобраться к квестовому мобу.

**Как должно работать?**
[Видео](https://www.youtube.com/watch?v=L_V8m20WhCQ&feature=youtu.be)

**Текущее обновление ядра:**

WoW Circle 3.3.5a x1 PvE
Build 162 2017-07-03 14:02:08 +0400

**Comment by Riazarre** [comment]
Добавьте ссылку на задание и заголовок перепишите.

**Comment by Rorshah** [comment]
в орде не работает точно. хорошо твина качал - подлетел на птичке и убил наверху.

http://wowroad.info/?quest=12259
