### ISSUE TITLE
[Задание] ID 2381 - Грабь награбленное

### ISSUE THREAD

**Issue by KochevnikRUS** [VirginTeam/WotlkCore#342]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Квест в Кабестане "Грабь награбленное" - после использования Х.О.Ч.У., попугай Полли уменьшается в размерах, но не в лвле, тем самым оставаясь неубиваемым. Квест для разбойников Орды. 

**Что работает не так?**
Попугай Полли не уменьшается в лвле, а лишь в размерах.

**Как должно работать?**

После использования Х.О.Ч.У., попугай Полли уменьшается в размерах и лвле, становясь 18 лвла, тем самым появляется возможность его ликвидации.

**Шаги для воспроизведения ошибки:**

1. Берется квест и ХОЧУ
2. Приходишь к сундуку, открываешь, появляется попугай
3. Получаешь от него люлей

**Текущее обновление ядра:**
WoW Circle 3.3.5a x1 PvE
Build 162 2017-07-03 14:02:08 +0400

**Comment by Riazarre** [comment]
Добавьте ссылку на задание, и отредактируйте заголовок.

**Comment by zyxellgit** [comment]
видимо это http://ru.wowhead.com/quest=2381

**Comment by Riazarre** [comment]
Воздержитесь в будущем от нецензурных выражений в репорте, плиз.

**Comment by ProjectADTP** [comment]
Ошибка до сих пор не исправлена

**Comment by gmKroshka** [comment]
У данного репорта и не стоит отметка об исправлении

**Comment by ProjectADTP** [comment]
В таком случае могу всем посоветовать попросить помощи у 50-80 лвлов в локации

**Comment by wizardy73** [comment]
Квест так и не исправлен. =( Обидно... А звать на помощь - это не спортивно! А я за честную игру! =)
