### ISSUE TITLE
[NPC] ID 26379 - Командир Агмар

### ISSUE THREAD

**Issue by gmOpex** [VirginTeam/WotlkCore#343]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

НПС http://ru.wowhead.com/npc=26379 не восстанавливает свой изнчальный пул и положение после выполнения одного из скриптов, завязанных на нем. Скорей всего http://ru.wowhead.com/quest=12140

**Что работает не так?**

http://s018.radikal.ru/i500/1707/62/586d7ff53db0.jpg

**Как должно работать?**

НПС после завершения скрипта задания должен восстанавливать изначальный пул и возвращаться 
на свой трон. Можно применить систему диспавна.

**Текущее обновление ядра:**
[10:11:41] Logon 3 WowCircle Development
[10:11:41] Последнее обновление ядра: Build 162 2017-07-03 14:02:08 +0400
[10:11:41] Игроков онлайн: 432 (максимум: 4650). Игроков в очереди: 0 (максимум: 0).
[10:11:41] Продолжительность работы сервера: 2 Day(s) 10 Hour(s) 50 Minute(s) 24 Second(s).
[10:11:41] Серверная задержка: 12.
[10:11:41] Следующее начисление очков арены: 16.07.2017  10:22

**Comment by gmKroshka** [comment]
Будет исправлено после обновления
