### ISSUE TITLE
[Заклинание] ID 54907 - Внезапный порыв

### ISSUE THREAD

**Issue by gmOpex** [VirginTeam/WotlkCore#345]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Отсутствие КД и ГКД спелла http://ru.wowhead.com/spell=54907

**Что работает не так?**

http://ru.wowhead.com/spell=54907 нет не КГД не КД

**Как должно работать?**

ГКД секунда КД 10 секунд

**Текущее обновление ядра:**

Последнее обновление ядра: Build 162 2017-07-03 14:02:08 +0400

**Comment by Riazarre** [comment]
ГКД - 1.5 секунды, или пруф что у него секунда.
