### ISSUE TITLE
[Задание] ID 13257 - Глашатай войны

### ISSUE THREAD

**Issue by Luchass** [VirginTeam/WotlkCore#35]
**Описание:**

http://ru.wowhead.com/quest=13257
http://wowroad.info/?quest=13257

**Что работает не так?**

Не работает ивент задания.

**Как должно работать?**

https://www.youtube.com/watch?v=TwMSBSbe_ZM (Начало)

**Шаги для воспроизведения ошибки:**

1. Взять задание
2. Ничего не происходит

**Текущее обновление ядра:**

PTR Build 20 2017-04-05 12:06:47 +0400

**Comment by djex777** [comment]
До сих пор не работает!

**Comment by gmOverfire** [comment]
Подобные комментарии не ускорят фиксы.

**Comment by djex777** [comment]
А что ускорит? Многим багам по кв уже около года.

**Comment by Kodekc** [comment]
@djex777 , да, это так, есть репорты и с большим сроком ожидания. Ничего не может ускорить процесс реализации именно этого задания. Пользователям рекомендуется просто отслеживать информацию и по мере возможности дополнять её.

**Comment by gmRial** [comment]
Следующий квест #1205
