### ISSUE TITLE
[Задание] ID 310 - Злейшие соперники

### ISSUE THREAD

**Issue by xotab007** [VirginTeam/WotlkCore#351]
**Описание:**

Купленный Эль не отдаётся Нипу. Нип не уходит и невозможно выполнить квест.

**Что работает не так?**

Нельзя начать разговор с НИПом, при нажатии на него не открывается диалоговое окно.

**Как должно работать?**

Должно открыться окно при нажатии на НИПа, он должен взять Эль и пойти на верх. (http://ru.wowhead.com/quest=310)

**Шаги для воспроизведения ошибки:**

1. По квесту Злейшие соперники прибегаем в пивоварню, указанную в квесте
2. Покупаем Громовой Эль
3. Спускаемся в подвал и видим там НИПа.
4. При нажатии на него должно открыться диалоговое окно, в котором игрок отдает ему Эль (но этого окна нет)

**Текущее обновление ядра:**

Logon 3, 3.3.5a x1 [Virgin x1 PvE]
Build 162 2017-07-03 14:02:08 +0400
Продолжительность работы сервера: 1 Day(s) 20 Hour(s) 2 Minute(s) 15 Second(s)

**Comment by Ewropa** [comment]
Его же правили уже, неужели скрипты зависают...

**Comment by LexaZaycev** [comment]
Недавно пытался сделать этот кв, но тоже не получилось отдать НИПу Громовой Эль.

**Comment by OakSorcerer** [comment]
Позади НИПа по имени Ярвен Грозовар должна стоять бочка с тем самым элем. Её там нет, судя по всему после диалога с бочкой активируется диалог с Ярвеном. Но так как бочки нет, то и возможности пройти этот квест тоже нет :(

**Comment by Grandhades** [comment]
Все еще не работает

**Comment by MiceRus** [comment]
По прежнему не работает

**Comment by AstralBlitz1** [comment]
Квест все ещё не работает. Отсутствует даже бочка, которую необходимо заменить(( Админы исправьте пожалуйста эту проблему, ведь это начальная локация! Заранее благодарен
![WoWScrnShot_051719_215922](https://user-images.githubusercontent.com/50879644/58110213-c728f700-7bf7-11e9-8138-9337fe213c25.jpg)

**Comment by gorechaser** [comment]
До сих пор не работает квест. держу в курсе 
![WoWScrnShot_031020_182643](https://user-images.githubusercontent.com/61152135/76308170-c97e4e00-62fc-11ea-85fe-117dc31febcf.jpg)
![WoWScrnShot_031020_182651](https://user-images.githubusercontent.com/61152135/76308176-cb481180-62fc-11ea-8f7a-4c9f45bf57a5.jpg)
