### ISSUE TITLE
[Предмет] ID 427485 Матричный перфограф 3005-D

### ISSUE THREAD

**Issue by KochevnikRUS** [VirginTeam/WotlkCore#357]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

В подземелье "Гномреган", около босса Толпогон 9-60, находится Матричный перфограф 3005-D. С ним проблемы - он не даёт рецепт для инженера взамен "Карта безопасного доступа ДЕЛЬТА" (id 9327)

**Что работает не так?**

Приходишь с картой доступа ДЕЛЬТА, нажимаешь правой кнопкой, в итоге открывается диалоговое окно, но без возможностей что-либо сделать, лишь почитать текст, что нужна карта.

**Как должно работать?**

1.Запустить Матричный перфограф 3005-D и пролистать весь диалог
2. Получить Чертеж: анти-перенаправляющий луч

**Текущее обновление ядра:**

Build 162 2017-07-03 14:02:08 +0400

**Comment by atomck** [comment]
11.02.2019  диалог с Матричный перфограф 3005-D есть но не активный(нажимаешь и ничего)
https://ibb.co/sqmHMzS
