### ISSUE TITLE
[Задание] ID 11101 (11097) - Самая Опасная Ловушка

### ISSUE THREAD

**Issue by Rialzarre** [VirginTeam/WotlkCore#360]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Что работает не так?**

После взятия квеста ничего не происходит. Нельзя повторно поговорить с квестгивером.
Возможно, 11097 так же не работает.

**Как должно работать?**

При взятии квеста, должны появляться мобы, от которых нужно защитить лагерь.

**Текущее обновление ядра:**

Virgin Build 162

**Comment by djex777** [comment]
Будет работать?

**Comment by MiceRus** [comment]
Скоро год отмечать будем :)
