### ISSUE TITLE
[Группа заклинаний] Символы

### ISSUE THREAD

**Issue by Gringer444** [VirginTeam/WotlkCore#364]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

34913, 41109
при необходимости список будет дополнен всеми символами.

**Что работает не так?**

При входе в игру приходится обновлять баффы (если они были наложены ДО выходы из игры), иначе не учитывается бонус от символа.
Некорректно работает символ, обновление заклинания решает проблему.

**Как должно работать?**

При входе в игру бонусы от символов должны учитываться, баффы должны давать именно тот эффект, который ожидается.
Например, приходится обновлять "Раскаленный доспех", иначе при расчете % крит. удара заклинаний не учитывается бонус от символа.

**Текущее обновление ядра:**

WoW Circle 3.3.5a x1 PvE
Build 162 2017-07-03 14:02:08 +0400

**Comment by Gringer444** [comment]
С "Символом печати мудрости" аналогичная ситуация. Не работает (после входа в игру) до тех пор, пока не обновить "Печать мудрости". Скажите пожалуйста, нужно ли создавать отдельный баг-репорт?

**Comment by Gringer444** [comment]
Возможно, проблема не в способности, а в символах (прочитайте пожалуйста предыдущий комментарий)

**Comment by Riazarre** [comment]
Так оно и есть, при заходе в мир не учитываются бонусы от символов, проблема общая.
Репорт переделал.

**Comment by Gringer444** [comment]
Спасибо.
