### ISSUE TITLE
[Задание] ID 6041 - Дымок над Водою

### ISSUE THREAD

**Issue by odino4estvo** [VirginTeam/WotlkCore#366]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Подробно: берется квест, к нему прилагается квест-итем http://wowroad.info/?item=15736 с 10-ю зарядами, с его помощью нужно уничтожить 8 штук http://wowroad.info/?npc=12247. (координаты указаны!) В чем суть проблемы, как писали ранее в предыдущих темах, да, я читал, и проблема до сих пор остается, так что убедительная просьба не ставить модераторам "дубликат", и тд.тп., все кто знает, кто пытался сделать или уже делал давно, то в таких зиккуратах установлены точки взрыва, возле которых нужно применять квест-итем. После применения взрывчатки, задание должно засчитать +1 к его исполнению, а всего таких 8. Как писали ранее в предыдущих темах с таким заданием, цитирую > "**Задание работает, и работает правильно, т.е. раза один и тот же зикурант Вы уничтожить не сможете, поэтому следите, что уничтожили, а что нет, иначе будете делать задание по новой**", это лажа. Я тщательно прохожу задания, что приходится отмечать той же ручкой, что я сделал а что нет. В моем случае был paint, скриншот прикрепляю. Дело в том, что первых 4е зиккурата я взорвал на ура, следующих 4, не засчитывало. Квест брал по новой. Выполнял, на второй раз я смог взорвать всего лишь 2 зиккурата, остальные не засчитывало, в третий раз, сделал тоже 2, остальные же - ноль реакции. Проверял, охранники зиккурата, или как их там зовут, стражи пусть будут, он всего один, были убиты, использовал квест-итем на точке взрыва, ни-че-го, бегал да прыгал вокруг точки взрыва, ни-че-го. Заметил такой прикол, что если выполняем задание, взрывая эти зиккураты, после одного-двух а той и трех успешно выполненых взрывов, а на четвертый раз в задание не засчитывает, то и последовательные 5-6-7-8 оно не засчитает. Даже если применить бомбу на одном и той же точке взрыва несколько раз. Проблема в том, что зарядов мало. Большая вероятность того, что квест будет провален, и да, придется брать его по новой. Это морока я считаю, квест так не должен работать. 

**Как должно работать?**

После использования http://wowroad.info/?item=15736 возле сооружений плети должно засчитывать +1 к заданию, бывает что после 4-го взрыва последующие точки взрыва уже не засчитываются, скриншоты прикрепляю!  На Скрине №1 (который последний) он бесполезный правда, отмечено зеленым которые я взорвал, красным - которые уже не работают. Если делать в другой последовательности, т.е. брать другие точки, они будут работать, а отмеченные мною например, рабочие, уже нет... Прикрепил скрины уже после 4го-выполненного зиккурата. Скриншоты предоставляют доказательство что подальшие взрывы в разных зиккуратах уже не засчитывает... Убедительная просьба решить проблему с заданием! Заранее спасибо! Надеюсь услышать от разных игроков слова аналогичны моей проблеме.
![9](https://user-images.githubusercontent.com/27158518/28488697-cd752b9a-6eb8-11e7-9741-ee76df817dbe.jpg)
![1](https://user-images.githubusercontent.com/27158518/28488699-d408962c-6eb8-11e7-911e-92b722d7bbbc.jpg)
![2](https://user-images.githubusercontent.com/27158518/28488700-d428a872-6eb8-11e7-8a87-858d3c99113e.jpg)
![3](https://user-images.githubusercontent.com/27158518/28488701-d43d272a-6eb8-11e7-8fc3-b765fdce9fea.jpg)
![4](https://user-images.githubusercontent.com/27158518/28488704-d43f9f96-6eb8-11e7-9cef-7d0ef7cdd101.jpg)
![5](https://user-images.githubusercontent.com/27158518/28488702-d43ed3a4-6eb8-11e7-98f2-3ae3838d0bc8.jpg)
![6](https://user-images.githubusercontent.com/27158518/28488705-d4424228-6eb8-11e7-9bc0-235d11c15cb5.jpg)
![7](https://user-images.githubusercontent.com/27158518/28488703-d43f46e0-6eb8-11e7-8c1f-dba13318782d.jpg)
![8](https://user-images.githubusercontent.com/27158518/28488706-d4488f66-6eb8-11e7-860d-22685adbd1d5.jpg)

**Шаги для воспроизведения ошибки:**

1. Заходим в зиккурат, юзаем взрывчатку.
2. Взрыв *(бывает) не засчитывается.
3. И подальшие взрывы тоже засчитыватясь уже не станут.

**Текущее обновление ядра:**
 
Текущий 162, но это было замечено 12.02.2017, после 17.00 по МСК! 
http://forum.wowcircle.com/showthread.php?t=641522

**Comment by LexaZaycev** [comment]
Вчера тоже пробовал сделать этот квест. В одной из попыток бомба сработала только с ВОСЬМОГО раза. Иногда первые 2-3 башни засчитывают, а остальные нет. И как уже писалось выше - в связи с тем что количество бомб ограничено квест невозможно сделать. пробовал раз 10 этот квест сделать, но больше пяти башен взорвать не удалось.
