### ISSUE TITLE
[Задание] - Миссия: Полуостров адского пламени (гер)

### ISSUE THREAD

**Issue by kapron9** [VirginTeam/WotlkCore#367]
**Описание:**

Задания "миссия; полуостров адского пламени гер." 

**Что работает не так?**

При прохождение подземелья (гер.), не засчитывается его прохождение в задание.

**Как должно работать?**

После прохождения подземелья (гер) должно засчитываться в список пройденных в задании.

**Текущее обновление ядра:**

Virgin Build 162

**Comment by ForesterDev** [comment]
Исправлено
