### ISSUE TITLE
[Игровая механика] Спелы, которые дают бафы и при использовании не тратят гкд

### ISSUE THREAD

**Issue by Gooldark** [VirginTeam/WotlkCore#371]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

ID 16188 - Природная стремительность(http://wowroad.info/?spell=16188), 
ID 17116 - Природная стремительность(http://wowroad.info/?spell=17116), 
ID 14177 - Хладнокровие(http://wowroad.info/?spell=14177)
Возможно, что это далеко не все поломанные спелы, перечислил лишь те что знаю.

**Что работает не так?**

Обычно эти спелы использутся в купе со селами на которые тратиться этот баф за счет макроса:
> /use Природная стремительность
/use Циклон

Когда игрок использует макрос, иногда баф вешается, но не работает. Скорее всего, баг возникает из-за того, что обычно игроки быстро клацают по макросу, вследствие чего баф багается. На офе, кстати, такие макросы срабатывали только при двойном использовании. 1-ый клик - появление бафа, 2-ой клик - использование спела.

**Как должно работать?**

Не должно быть таких ситуаций когда баф висит, но работать он не хочет.

**Шаги для воспроизведения ошибки:**

1. Написать подобный макрос описанный выше
2. Быстро клацать на него

**Текущее обновление ядра:**

25.07.2017.

**Comment by kalipsa988** [comment]
Дополнение:
http://db.logon3.com/?spell=5384 и различные банки на реген маны/хп
