### ISSUE TITLE
[Задание] id 11090 - Покорить Покорителя

### ISSUE THREAD

**Issue by Rialzarre** [VirginTeam/WotlkCore#377]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)
**Описание**

Квеститем http://ru.wowhead.com/item=32825
НПЦ http://ru.wowhead.com/npc=22357 

**Что работает не так?**

1. При использовании итема на маунте НПЦ эвейдится.
2. При использовании итема на земле, первый тик убивает НПЦ (урон несколько миллиардов)
3. При достижении 1% хп НПЦ не уходит к порталу.
Задание не работает в принципе.

**Как должно работать?**

> Пушку можно использовать находясь верхом, а главное нужно использовать находясь верхом на летающем животном. 
> 
> Летайте вокруг него, уворачивайтесь от метеоров которые собьют вас на землю, терпите шадоу болты и увечья. На 1% Покоритель двинется к порталу. дождитесь окончания шествия и можно двигатся за наградой)

**Перенесено**

http://forum.wowcircle.com/showthread.php?t=398080

**Текущее обновление ядра:**

Virgin Build 163

**Comment by MiceRus** [comment]
Блин. До сих пор не работает. :(
Что ж так долго? (это риторический вопрос)

**Comment by makfinova** [comment]
Все еще не работает((

**Comment by gmKroshka** [comment]
Сообщения об исправлении репорта ещё и не было. Репорт не взят в работу
