### ISSUE TITLE
[Задание] ID 12237 - Полет защитника Стражей Зимы

### ISSUE THREAD

**Issue by imbaScorn** [VirginTeam/WotlkCore#378]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

При помощи этого свистка ты можешь призвать грифона Стражей Зимы. Взбирайся на него и направляйся к руинам деревни Стражей Зимы, ныне известным как Поля Падальщиков, на юго-восток отсюда. Когда доберешься до полей, смотри в оба и ищи беспомощных селян Стражей Зимы. Когда заметишь кого-то из них, опускайся ниже и с помощью грифона подбери несчастного. Привези спасенного сюда, на грифонью площадку.

**Что работает не так?**

Не работает сам маунт, летать на нём не возможно, только бегать с обычной скоростью игрока. Не работает посадка селян на маунта. Работает ли высадка селян проверить не представляется возможным.
Так же сами селяне должны бегать в страхе в районе Крепости стражей зимы, они толпятся в одном месте и атакуют мобов, чего делать не должны. Так же мобы атакуют их, чего тоже не должно быть.
https://www.youtube.com/watch?v=ABmtYcba50A - небольшой отрезок видео для наглядности.

**Как должно работать?**

Сразу после получения вызывается квестовый маунт и игрок должен летать, брать по одному селянину, который бегает в страхе в округе Крепости стражей зимы и высаживать их в самой крепости в зоне мастера перелетов. 
Вот ссылка на видео как он должен работать - https://www.youtube.com/watch?v=6G1ugutT9T4

**Шаги для воспроизведения ошибки:**

1. Выполняем цепочку квестов которые приводят к квесту "Полет защитника Стражей Зимы"
2. Берем данный квест у Командир грифонов Урик.
3. Вызываем специального маунта из появившегося итема и собственно остальное уже расписано.

**Текущее обновление ядра:**

Logon 3 WowCircle Development
Текущее обновление ядра: Build 163 2017-07-25 11:59:12 +0400
wow lich king 3.3.5.a PVE x1

**Comment by Nimlotnik** [comment]
Квест всё так же не работает, и всё та же проблема

**Comment by Anarom** [comment]
Актуально до сих пор
