### ISSUE TITLE
[задание] ID 13394 - Всё к худшему

### ISSUE THREAD

**Issue by mirjetto** [VirginTeam/WotlkCore#383]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**
id 13394 - всё к худшему (http://wowroad.info/?quest=13394) WOTLK 3.3.5a live server

**Что работает не так?**
Невозможно взять квест т.к. нпс Матиас Нетлер(http://wowroad.info/?npc=32408) не появился 
возле отремонтированного разрушителя, тем самым прервал цепочку квестов.

**Как должно работать?**
После завершения квеста "Ремонт в полевых условиях" (http://wowroad.info/?quest=13393) должен появится Матиас Нетлер и начать цепочку квестов.

**Шаги для воспроизведения ошибки:**

1. Выполнить цепочку квестов начиная с "Разведка провала"(http://wowroad.info/?quest=13386)
2. Дойти до квеста "Ремонт в полевых условиях" (http://wowroad.info/?quest=13393)

**Текущее обновление ядра:**
Build - 163 (Build - 51) 25.07.17

**Comment by Scoren** [comment]
https://github.com/VirginTeam/VirginCore/issues/255 дубликат

**Comment by gmOverfire** [comment]
Закрыто. Дубль.
