### ISSUE TITLE
[Заклинание] ID 20467 - Правосудие повиновения

### ISSUE THREAD

**Issue by Gooldark** [VirginTeam/WotlkCore#386]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

 ID 20467 - Правосудие повиновения(http://wowroad.info/?spell=20467)

Все атаки ближнего боя наносят от до дополнительного урона от светлой магии. Высвобождение энергии этой печати мгновенно наносит цели от до ед. урона от светлой магии.

**Что работает не так?**

Неверная формула нанесения урона, сейчас она такая:
D = (0.13 * SP + 0.08 * AP + 0.24 * WD * M) * (1 + 0.1 {Искусство войны}), где M - глобальный мультипликатор урона (стаки Отмщения, Гнев карателя, Священная война и т.д.)

**Как должно работать?**

Формула должна быть такой:
D = (0.13 * SP + 0.08 * AP + 0.19 * WD) * (1 + 0.1 {Искусство войны}) * M

**Доказательства**

1) Тултип самого клиента wow 3.3.5a
2) ДрД
3) Патчноут - http://wowwiki.wikia.com/wiki/Patch_3.2.0
> Seal of Command: Redesigned. This seal now deals 36% weapon damage on every swing, and deals substantially less judgement damage.

**Текущее обновление ядра:**

9.12.2015

**Перенесено**

http://forum.wowcircle.com/showthread.php?t=505951

**Comment by xARCHIMEDESx** [comment]
Ап!)

**Comment by xARCHIMEDESx** [comment]
Ап!

**Comment by gmKroshka** [comment]
Не нужно "апать". Никак не поможет исправлению

**Comment by xARCHIMEDESx** [comment]
Я думал, что как на форуме, подскочит вверх. Но тут так не работает( Больше не буду
