### ISSUE TITLE
[Заклинание] ID 12043 - Величие разума

### ISSUE THREAD

**Issue by Gooldark** [VirginTeam/WotlkCore#387]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

ID 12043 - Величие разума(http://wowroad.info/?spell=12043)

**Что работает не так?**

Если включить данный спел, затем релогнуться, то после использования любого спела нельзя юзать Мощь тайной магии(http://wowroad.info/?spell=12043). Причем если после юза релогнуться, баф Величие разума опять повеситься, хотя его уже использовали. 

**Как должно работать?**

Думаю баг исчезнет если сделать удаление этого бафа при релоге. Либо нужно как-то убрать забагивание проверки на наличие этого бафа, так как серв распознает что баф есть, хотя его нет.

**Доказательство**

https://www.youtube.com/watch?v=1MDT3CRjlx8

**Текущее обновление ядра:**

25.11.2015

**Перенесено**

http://forum.wowcircle.com/showthread.php?t=501827

**Comment by ForesterDev** [comment]
Баг не воспроизводится. После релога и использования спела, через секунду Мощь тайной магии юзается
