### ISSUE TITLE
[Заклинание] ID 49158 - Взрыв трупа

### ISSUE THREAD

**Issue by Gooldark** [VirginTeam/WotlkCore#391]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

ID 49158 - Взрыв трупа
Взорвать труп, нанося 166 ед. урона от темной магии всем противникам в радиусе 10 м. Если цель не выбрана, взрывается ближайший труп. Остатки механизмов и элементалей не могут быть взорваны.

**Что работает не так?**

а) Вызывается гкд даже если нет трупа для взрыва(для клиента он не отображается, но реально он есть)
б) Если, когда у вурдалака идет гкд нажать на него взрыв трупа(или вурдалак в контроле), у дк потратиться рунник, а взрыв не будет кастоваться.

**Как должно работать?**

а) Гкд не должно вызываться если поиск трупа спелом не удался.
б) Если, когда у вурдалака гкд нажать взрыв, то после гкд пет должен начать каст взрыва.

**Доказательства**

а) Доказательств нет, но на мой взгляд это логичная механика(на усмотрение разработчика).
б) http://www.warcraftmovies.com/movieview.php?id=149533 - 6:58 и далее, дк разворачивается на рога, отправляет на него вурдалака.
Вурдалак бьет спелом рогу, и пока у него идет гкд, дк жмет взрыв трупа, как только гкд у вурдалака заканчивается начинается каст взрыва.

**Текущее обновление ядра:**

15.12.2015

**Перенесено**

http://forum.wowcircle.com/showthread.php?t=507771
http://forum.wowcircle.com/showthread.php?t=492865

**Comment by gmRial** [comment]
Исправлено, после обновления.
