### ISSUE TITLE
[Заклинание] ID 59159 - Гром и молния

### ISSUE THREAD

**Issue by Gooldark** [VirginTeam/WotlkCore#393]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

ID 59159 - Гром и молния(http://wowroad.info/?spell=59159)
ID 23920 - Отражение заклинания(http://wowroad.info/?spell=23920)

**Что работает не так?**

ID 59159 - Гром и молния(http://wowroad.info/?spell=59159) отражается рефлектом

**Как должно работать?**

Отражение заклинания (и другие виды рефлектов) никак не должен влиять на Гром и молния, так как это аое спел

**Доказательства**

https://www.youtube.com/watch?v=sgONe6VzeKM - 1:30 - вар получает тандер, когда на нем висит рефлект.

**Текущее обновление ядра:**

06.08.2017

**Перенесено**

http://forum.wowcircle.com/showthread.php?t=538764

**Comment by ForesterDev** [comment]
https://youtu.be/7ZJ-3SgDC70?t=195
https://youtu.be/xIQKDDNMzB4?t=769
Отклонено
