### ISSUE TITLE
[Заклинание] ID 49048 - Залп

### ISSUE THREAD

**Issue by Gooldark** [VirginTeam/WotlkCore#394]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

ID 49048 - Залп(http://wowroad.info/?spell=49048)

**Что работает не так?**

Отсутствует полоска каста

**Как должно работать?**

Должна быть видна полоска каста

**Текущее обновление ядра:**

06.08.2017

**Перенесено**

http://forum.wowcircle.com/showthread.php?t=534728

**Comment by Kodekc** [comment]
Указан не правильный ID заклинания же, просьба перепроверить и ссылаться на http://db.logon3.com

**Comment by Kodekc** [comment]
https://web.archive.org/web/20100522095151/http://ru.wowhead.com/spell=49048
Не понял, что к чему, заклинание мгновенное, от куда должна взяться полоска каста

**Comment by sega693** [comment]
http://puu.sh/zsYcn/eb8aec4d8f.jpg Может надо сделать его мгновенным тогда? О_о

**Comment by kalipsa988** [comment]
Тогда на другую тему нужно писать
