### ISSUE TITLE
[Заклинание] ID 47996 - Перехват

### ISSUE THREAD

**Issue by Gooldark** [VirginTeam/WotlkCore#395]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

ID 47996 - Перехват(http://wowroad.info/?spell=47996)
Рывок к противнику, наносящий 189 ед. урона и оглушающий противника на 3 sec.

**Что работает не так?**

скалируется от спд

**Как должно работать?**

скалироваться от спд не должно

**Доказательства**

https://www.youtube.com/watch?v=aqvgRj9qJvM
0:21 - чарж нанес 218 урона критом. 189x2x0,6=226 (0,6 - учет армора манекена)
на серкле урон выше даже не критом.

**Текущее обновление ядра:**

06.08.2017

**Перенесено**

http://forum.wowcircle.com/showthread.php?t=553868

**Comment by ForesterDev** [comment]
Неактуально
