### ISSUE TITLE
[Заклинание] ID 57934/34477 - Маленькие хитрости/Перенаправление

### ISSUE THREAD

**Issue by Gooldark** [VirginTeam/WotlkCore#397]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

ID 57934 - Маленькие хитрости
ID 34477 - Перенаправление

**Что работает не так?**

Наложение данных эффектов на цель которой будет передаваться агр вводит ханта/рога в бой.(если цель находится в бою разумеется)

**Как должно работать?**

Эти эффекты не вешают на цель баф, не исцеляют цель, следовательно не должны переносить комбат на ханта/рога.

**Доказательства**

Прямых доказательств к сожалению нет, поэтому возможно репорт неверен.
Этот баг больше ханта касается, так как получение комбата со 100-а метров, после чего можно использовать отрыв иногда вызывает незаслуженное преимущество.

**Текущее обновление ядра:**

07.08.2017

**Перенесено**

http://forum.wowcircle.com/showthread.php?t=534733

**Comment by kalipsa988** [comment]
спелы передают агро на перса, соответственно должны вешать бой
