### ISSUE TITLE
[Задание] ID 12996 —  Тренировочный заезд

### ISSUE THREAD

**Issue by ar4i2018** [VirginTeam/WotlkCore#399]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Задание — [[Тренировочный заезд]](http://ru.wowhead.com/quest=12996).
При взятии квеста даются [[Поводья]](http://ru.wowhead.com/item=42481).

**Что работает не так?**

У боевой медведицы-матриарха есть 3 атаки: "Трепка" — Мощная лобовая атака, наносящая 1360-1840 ед. урона. Она почему-то бьет по 400, но критует по 1000; "Мощный удар" — Отбрасывает противника, нанося 500 ед. физического урона. Эта атака вообще не работает. Т.е жмешь на нее и вообще ничего не происходит; "Рывок" — Рывок в сторону противника, оглушая его на 3 секунды. Эту способность за весь бой даже не удалось использовать из-за того, что не работает "Рывок". Ее удастся использовать только перед началом боя.

**Как должно работать?**

[Видео](https://www.youtube.com/watch?v=XwP3cXx0RNE&feature=youtu.be).
"Мощный удар" должен отбрасывать противника и наносить ему урон... или хотя бы наносить урон.

**Текущее обновление ядра:**

Build 163 2017-07-25 11:59:12 +0400

**Comment by Riazarre** [comment]
Вроде не впервые репорт делаете, а заголовок привести к утвержденному виду забываете.
