### ISSUE TITLE
[Подземелье] Яма Сарона (ID 70827 Ледяные осколки)

### ISSUE THREAD

**Issue by gmOverfire** [VirginTeam/WotlkCore#4]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Скриншоты демонстрирующие проблему, выделение проблемных мест с помощью графических редакторов приветствуются. Для описания ошибок, возникающих только в движении, снимите видео **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Заклинание Ледяные осколки http://wowroad.info/?spell=70827

**Что работает не так?**

Суть бага в анимации заклинания. 
У нас (тайминг примерный):
0 сек - Показывается область поражения заклинания.
1 сек - С потолка падает кусок льда.
1-1.5 сек - Наносится урон.
6-7 сек - Область поражения пропадает.
https://youtu.be/yV3OiGS3ZvI

**Как должно работать?**

0 сек - Показывается область поражения заклинания.
3.5 сек - Область поражения пропадает.
4 сек - С потолка падает кусок льда.
4 сек - Наносится урон (одновременно с предыдущим событием).
https://youtu.be/XSQx8uYc8cA

**Comment by Riazarre** [comment]
Работает на тринити.

**Comment by ForesterDev** [comment]
Исправлено, проверить после обновления
