### ISSUE TITLE
[Предмет] ID 37012 - Поводья скакуна Всадника без головы

### ISSUE THREAD

**Issue by sadboy1337** [VirginTeam/WotlkCore#400]
Описание:
http://ru.wowhead.com/item=37012
Наблюдается корявая анимация полета выше указанного маунта(все это происходит 50 на 50 либо идет корявая анимация либо идет нормальная но с камера становится чутка выше персонажа)

Что работает не так?

Анимация

Как должно работать?

Должно работать как обычный бег 

Шаги для воспроизведения ошибки:

1. Изучить полет на 60 лвл
2. Сесть на маунта
3. Увидеть своими глазами

Текущее обновление ядра:

Build 163 2017-07-25 11:59:12 +0400

**Comment by Riazarre** [comment]
Ссылку на предмет добавьте, и заголовок согласно шаблона переделайте.

**Comment by Kodekc** [comment]
Можно видео прикрепить, чтоб понять, что именно не так

**Comment by kalipsa988** [comment]
https://www.youtube.com/watch?v=nIaGmyOgtNA&feature=youtu.be вот видео с багом

**Comment by kalipsa988** [comment]
в конце получилось нормальный полёт сделать

**Comment by kalipsa988** [comment]
https://www.youtube.com/watch?v=dePCaxLp4Hw&feature=youtu.be доп инфа, во время простого бега криво работает прыжок

**Comment by ForesterDev** [comment]
Повтор
