### ISSUE TITLE
[Заклинание] ID 8143 - Тотем трепета

### ISSUE THREAD

**Issue by Gooldark** [VirginTeam/WotlkCore#404]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

ID 8143 - Тотем трепета(http://wowroad.info/?spell=8143)
и ID 10326 - Изгнание зла(http://wowroad.info/?spell=10326)

**Что работает не так?**

Тремор сбивает фир пала

**Как должно работать?**

Тремор не должен сбивать фир пала

**Доказательства**

http://www.warcraftmovies.com/movieview.php?id=149601 - 21:08 пет бегает в фире, а тотем его не снимает. Это точно был тремор, бафов/дебафов других тотемов нет, тотем каменного когтя быстро исчезает (этот простоял с 21:02 до 21:41).

**Текущее обновление ядра:**

13.08.2017

**Перенесено**

http://forum.wowcircle.com/showthread.php?t=649939

**Comment by ForesterDev** [comment]
Исправлено, будет применено в обновлении
