### ISSUE TITLE
[Подземелье] Чертоги Камня (ID 27977 Кристаллус)

### ISSUE THREAD

**Issue by Rialzarre** [VirginTeam/WotlkCore#41]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Урон от способности босса проходит сквозь эффекты невосприимчивости.

**Что работает не так?**

Урон от способности http://wowroad.info/?spell=61546 проходит сквозь эффект невосприимчивости мага.
В зависимости от расстояния до цели урон корректный:
Вплотную:
`12:20:05> "[Раскалывание]" [Миссисболтон] наносит [Skywillburn] 11314 единиц физического урона.`
~30 метров:
`12:20:36> "[Раскалывание]" [Миссисболтон] наносит [Skywillburn] 2187 единиц физического урона.`
Под иммуном:
`12:20:49> На [Skywillburn] накладывается эффект "[Ледяная глыба]" [Skywillburn].`
`12:20:49> [Skywillburn] находится под воздействием эффекта "[Гипотермия]" [Skywillburn].`
`12:20:51> [Skywillburn] обладает невосприимчивостью к заклинанию "[Раскалывание]" [Кристаллус].`
`12:20:51> "[Раскалывание]" [Миссисболтон] наносит [Skywillburn] 8978 единиц физического урона.`

**Как должно работать?**

Урон не должен проходить сквозь эффекты невосприимчивости.

**Текущее обновление ядра:**

PTR: Build 20 2017-04-05 12:06:47 +0400

**Comment by Santaria** [comment]
Механика способности взята с аналогичной способности у Груула. Вероятно особенность пробивать айсблок/бабл также взята от туда, т.е. не является багом.

https://www.wowhead.com/spell=33654
>Ice Block and Divine Shield will NOT prevent Shatter damage done to or by you. Ouch.
