### ISSUE TITLE
[Задание] ID 10988 - Вороньи камни

### ISSUE THREAD

**Issue by LothlorienElf** [VirginTeam/WotlkCore#410]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Не работает задание Вороньи камни (http://wowroad.info/?quest=10988)

**Что работает не так?**

Пустельга, которую призываю для поиска фрагментов, не ищет их, зависает на одном месте. Поиск фрагментов становится невозможным.

**Как должно работать?**

Пустельга должна прилетать к месту фрагмента и игрок должен собрать нужное количество данных фрагментов.

**Шаги для воспроизведения ошибки:**

1. Получение задания от Дозорный Элайра (http://wowroad.info/?npc=22981)
2. Получение вместе с заданием Манок для пустельги (http://wowroad.info/?item=32315)
3. В Лесу Террокар, Скеттис призыв пустельги
4. Пустельга указывает местоположение предметов, сбор нужного количества
5. Сдача квеста Арторну Песня Ветра (http://wowroad.info/?npc=22924)

**Текущее обновление ядра:**

Build 163 2017-07-25 11:59:12 +0400

**UPDATE**

На следующий день зашла в игру, камни появились, только пустельга вообще никак не нужна.
Квест сдать получилось.

**Comment by Lexwood** [comment]
Build 178 2017-12-05 11:53:10 +0400
Не работает. Птица появляется, но ничего не делает. Камней самих по себе нет.
