### ISSUE TITLE
[Задание] ID 12673 - Сбор кристаллов

### ISSUE THREAD

**Issue by pavaknsk** [VirginTeam/WotlkCore#413]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**
В квесте Сбор кристаллов можно подчинить упыря, у него есть спелл "Добыча кристалла гнили". 
По использованию спелла упырь должен схватить кристалл гнили и убежать с ним к Дракуру.
**Что работает не так?**

Упырь на этот спелл не реагирует.
**Как должно работать?**

Упырь должен схватить кристалл гнили и убежать с ним к Дракуру при использовании спелла "Добыча кристалла гнили"

**Шаги для воспроизведения ошибки:**

1. Взять квест
2. Подчинить упыря
3. Собрать кристалл

**Текущее обновление ядра:**
Logon 3 WowCircle Development
Последнее обновление ядра: Build 163 2017-07-25 11:59:12 +0400
х1

Очень жду рабочего квеста, с Уважением, Pavak.

**Comment by Devinette** [comment]
https://github.com/VirginTeam/VirginCore/issues/7

**Comment by nordwindd** [comment]
15.08.2017 этот квест сделал.
Шаги для выполнения:
1. Взять квест.
2. Подчинить упыря.
3. Подвести упыря к кристалу гнили (кнопка "следовать" на панели питомца).
4. Собрать кристалл (кнопка "Добыча кристалла гнили" на панели питомца).

**Comment by pavaknsk** [comment]
Выполнил по инструкции выше. Работает.

**Comment by Rorshah** [comment]
Делал хантом. Пока питомец был при мне подчинение не работало.
Прогнал своего питомца - подчинился этот.
Квест выполнил.
