### ISSUE TITLE
[NPC] id 15114 - Газ'ранка

### ISSUE THREAD

**Issue by gmRial** [VirginTeam/WotlkCore#416]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)
**Ссылки:**

https://ru.wowhead.com/npc=15114
https://ru.wowhead.com/npc=15114/%D0%B3%D0%B0%D0%B7%D1%80%D0%B0%D0%BD%D0%BA%D0%B0#comments:id=282900 - описание суммона

**Что работает не так?**

НПЦ можно суммонить огромное количество раз за 1 рейд.

**Как должно работать?**

НПЦ должен вызываться только 1 раз за сохранение рейда (как боссы в инстансе).
Все последующие призывы действовать не должны, но достижение даваться должно (если его нет)!

>  От poppylark (240 – 2) 2008-10-20 (Обновление 3.0.2)
> For The Deadliest Catch Achievement .. 
> 
> At level 70, you can easily swim to Pagle's Point, having to kill only a few fish along the way.
> 
> When Gahz'ranka is summoned, only the person that actually performs the summoning will receive the Achievement. However, if you are able to kill Gahz'ranka (which my husband and I were easily able to do .. Feral Druid \ Enh Shaman) and have an additional 5 fish and a lure, you can re-summon the boss immediately. Gahz'ranka will not reappear, but if a different person performed the summoning, they will also get the Achievement.

Изифарм книжки...

**Текущее обновление ядра:**

Virgin Build 163

**Comment by gmKroshka** [comment]
Будет исправлено после обновления
