### ISSUE TITLE
[Заклинание] ID 51722 - Долой оружие

### ISSUE THREAD

**Issue by Gooldark** [VirginTeam/WotlkCore#420]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

 ID 51722 - Долой оружие(http://wowroad.info/?spell=51722)
и
 ID 871 - Глухая оборона(http://wowroad.info/?spell=871),  ID 48952 - Щит небес(http://wowroad.info/?spell=48952),  ID 2565 - Блок щитом(http://wowroad.info/?spell=2565) возможно ID 19263 - Сдерживание(http://wowroad.info/?spell=19263).

**Что работает не так?**

ID 51722 - Долой оружие при использовании на цель с бафом Глухой обороны, Щита небес, Блока щитом, Сдерживания отменяет эти бафы.

**Как должно работать?**

ID 51722 - Долой оружие не должно отменять баф Глухой обороны, Щита небес, Блока щитом, Сдерживания отменяет эти бафы. 

Скорее всего баг появился после фикса, когда для Долой оружие сделали дополнительную проверку на наличие щита и огнестрельного. Напомню, до того фикса вар/хант могли снимать оружие для правой руки и избегать дизармов, вследствие чего могли беспрепятственно применять Глухую оборону/Сдерживание. Так же у Долой оружие есть эффект отмены бафа, когда при использовании спела у вара отменяется бш. 

Иначе говоря у Долой оружие должна остаться проверка на наличие оружия в левой руке и огнестрельного, при этом отмена бафов требующих наличия оружия в левой руке не должна быть.

**Текущее обновление ядра:**

18.08.2017

**Comment by ForesterDev** [comment]
Исправлено
