### ISSUE TITLE
[Заклинание] ID 48441 - Омоложение

### ISSUE THREAD

**Issue by Gooldark** [VirginTeam/WotlkCore#421]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

ID 48441 - Омоложение(http://wowroad.info/?spell=48441) и
ID 70664 - Item - Druid T10 Restoration 4P Bonus (Rejuvenation)(http://wowroad.info/?spell=70664) 

> На каждом такте заклинание "Омоложение" с вероятностью 2% может перейти на следующего союзника. Время его действия при этом обновляется.

**Что работает не так?**

При срабатывании сет-бонуса, за базовое значение перешедшего исцеления принимается не величина Омоложения, а фактический размер исцеления на исходном игроке, и происходит повторный расчет модификаторов, как минимум повышающих исцеление(таланты, проки экипировки на силу заклинаний). 

**Как должно работать?**

Должно накладываться исцеление в размере базового с учетом модификаторов исцеления друида-кастера и сторонних, действующих на цель перехода.

**Текущее обновление ядра:**

18.08.2017

**Перенесено**

http://forum.wowcircle.com/showthread.php?t=509231

**Comment by gmRial** [comment]
Исправлено, после обновления.
