### ISSUE TITLE
[Заклинание] ID 710 - Изгнание

### ISSUE THREAD

**Issue by Gooldark** [VirginTeam/WotlkCore#423]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

ID 710 - Изгнание(http://wowroad.info/?spell=710)

Изгнание противника. В течение 20 sec. противник не может совершать никаких действий, однако становится неуязвим. Заклинание можно применять только против одного противника единовременно. **Применение "Изгнания" на цель, которая еще находится под его воздействием, отменяет заклинание.** Действует только на демонов и элементалей.

**Что работает не так?**

Если на цели висит бан и сверху еще раз его повторно использовать, то при отмене бана будет багаться диминишинг на все время пребывания цели в мире.
То есть если отменить бан, диминишинг на всегда запомнит что уже 1 раз был контроль, и следующий будет в 2 раза короче.

В итоге если 3 раза отменить бан будет иммун к нему до релога

**Как должно работать?**

Отмена Изгнания никак не должна влиять на диминишинг

**Текущее обновление ядра:**

18.08.2017

**Перенесено**

http://forum.wowcircle.com/showthread.php?t=384592

**Comment by ForesterDev** [comment]
Исправлено
