### ISSUE TITLE
[Заклинание] ID 53209 - Выстрел химеры

### ISSUE THREAD

**Issue by Gooldark** [VirginTeam/WotlkCore#426]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

ID 53209 - Выстрел химеры(http://wowroad.info/?spell=53209)
Вы наносите 125% урона от оружия, обновляя действие текущего "Укуса". Кроме того, в зависимости от вида "Укуса" активируется дополнительный эффект:

"Укус змеи" – моментально наносит 40% дополнительного урона спообности.

"Укус гадюки" – моментально восполняет 60% маны, вытянутой этой способностью.

"Укус скорпида" – пытается обезоружить противника на 10 сек. Этот эффект срабатывает не чаще, чем раз в минуту.

И
ID 1978 - Укус змеи(http://wowroad.info/?spell=1978),
ID 3034 - Укус гадюки(http://wowroad.info/?spell=3034),
ID 3043 - Укус скорпида(http://wowroad.info/?spell=3043) +
ID 58410 - Мастер ядоварения(http://wowroad.info/?spell=58410),
ID 31823 - Чистота сердца(http://wowroad.info/?spell=31823).

**Что работает не так?**

Выстрел химеры обновляет время действия укусов до полного времени действия, несмотря на то что у цели могут быть вкачаны таланты Мастер ядоварения, Чистота сердца.

**Как должно работать?**

Мастер ядоварения, Чистота сердца должны влиять на обновленное время действия Укус змеи, Укус гадюки, Укус скорпида.

**Доказательства**

http://www.warcraftmovies.com/movieview.php?id=163895
04:46 - хант стреляет в мутилейта дотой, которая висит 10 сек, и при обновлении получает 10 сек времени действия, вместо 21.
Жаль год назад не нашел пруфов, удалось бы избежать бага.

видимо механика обновления времени действия дот до полного значения действует только на алока, шп, сову, шамана.

**Текущее обновление ядра:**

18.08.2017

**Перенесено**

http://forum.wowcircle.com/showthread.php?t=539619

**Comment by ForesterDev** [comment]
Исправлено, будет применено в обновлении
