### ISSUE TITLE
[Заклинание] ID 53297 - Токсичные укусы

### ISSUE THREAD

**Issue by Gooldark** [VirginTeam/WotlkCore#427]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

ID 53297 - Токсичные укусы(http://wowroad.info/?spell=53297)

Урон, наносимый вами по цели, находящейся под действием вашего эффекта "Укус змеи", увеличивается на 3%. Если "Укус виверны" был рассеян, рассеявший сам оказывается под его воздействием на 50% от оставшегося времени его действия.

**Что работает не так?**

не реализована механика таланта: Если "Укус виверны" был рассеян, рассеявший сам оказывается под его воздействием на 50% от оставшегося времени его действия.

**Как должно работать?**

талант должен вешать на цель, сдиспейлившей сон, новый сон с 50% оставшегося времени действия

**Текущее обновление ядра:**

18.08.2017

**Перенесено**

http://forum.wowcircle.com/showthread.php?t=613826

**Comment by ForesterDev** [comment]
Исправлено, будет применено в обновлении
