### ISSUE TITLE
[Подземелье] Ан'Кахет (ID 29308 Принц Талдарам)

### ISSUE THREAD

**Issue by Rialzarre** [VirginTeam/WotlkCore#43]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Босс - манекен. Использует только 2 заклинания из своего арсенала.
Справедливо к об. и гер. режимам.

**Что работает не так?**

[Исчезновение ID 55964](http://ru.wowhead.com/spell=55964) - не использует
[Объятия вампира ID 55959](http://ru.wowhead.com/spell=55959) - не использует
Есть каст [Создание сферы огня ID 55931](http://ru.wowhead.com/spell=55931,) но сферы не наносят урон, просто летают.
Вместо цели, наносит урон абилкой [Кровожадность ID 55968](http://ru.wowhead.com/spell=55968) самому себе, и сразу же от этого вылечивается на 1% абилкой [Кровожадность ID 55970](http://ru.wowhead.com/spell=55970).
```
4/7 14:01:56.497  SPELL_CAST_SUCCESS,0xF13000727C3A526C,"Принц Талдарам",0x10a48,0xF13000727C3A526C,"Принц Талдарам",0x10a48,55968,"Кровожадность",0x1
4/7 14:01:56.497  SPELL_DAMAGE,0xF13000727C3A526C,"Принц Талдарам",0x10a48,0xF13000727C3A526C,"Принц Талдарам",0x10a48,55968,"Кровожадность",0x1,17812,0,1,0,0,0,nil,nil,nil
4/7 14:01:56.497  SPELL_HEAL,0xF13000727C3A526C,"Принц Талдарам",0x10a48,0xF13000727C3A526C,"Принц Талдарам",0x10a48,55969,"Кровожадность",0x1,4583,0,0,nil
4/7 14:01:56.596  SPELL_AURA_APPLIED,0xF13000727C3A526C,"Принц Талдарам",0x10a48,0xF13000727C3A526C,"Принц Талдарам",0x10a48,55970,"Кровожадность",0x1,BUFF
```

**Как должно работать?**

https://youtu.be/qQR4rIEHV7Q?t=115

**Текущее обновление ядра:**

Virgin: Build 151 2017-04-03 15:25:08 +0400

**Comment by Riazarre** [comment]
Как работает на тринити.
[Исчезновение ID 55964](http://ru.wowhead.com/spell=55964) - не использует
[Объятия вампира ID 55959](http://ru.wowhead.com/spell=55959) - не использует
Кастует [Создание сферы огня ID 55931](http://ru.wowhead.com/spell=55931,), сферы дамажат.
Наносит урон абилкой цели [Кровожадность ID 55968](http://ru.wowhead.com/spell=55968) и вылечивается. [Кровожадность ID 55970](http://ru.wowhead.com/spell=55970).
