### ISSUE TITLE
[Заклинание] ID 55534 - Совершенствование самоцвета

### ISSUE THREAD

**Issue by Hellsingoff** [VirginTeam/WotlkCore#430]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

По неясной причине работает на очень ограниченном списке самоцветов, исключает получение некоторых самоцветов как факт.

**Что работает не так?**

По описанию и логике шанс на совершенную огранку должен быть у всех камней определенной категории (например, низкоуровневые камни WotLK), но по факту я уже несколько раз убеждался что даже за несколько сотен огранок у некоторых самоцветов нет данного шанса, тогда как у работающих "правильно" этот шанс составляет около 15-20%.
Пример:
Сегодня за сотню огранок [http://wowroad.info/?item=39938](url) вышло ноль [http://wowroad.info/?item=41458](url)
Однако ограняя три сотни соседних [http://wowroad.info/?item=39934](url) я получил примерно 15-20% шанса получить [http://wowroad.info/?item=41461](url), причём были проки сразу двух совершенных камней с одной огранки.
Так же вышло ноль совершенных камней при огранке пары сотен [http://wowroad.info/?item=39960](url)

**Как должно работать?**

Нормально должно работать.

Честно, я не опишу точную категорию камней, на которые должно распространяться данное заклинание, так как не был ювелиром на официальных серверах времен 3.3.5. Но мы явно не должны иметь **НЕПОЛУЧАЕМЫХ** камней. Если есть совершенный камень - должен быть и шанс прока огранки.

**Шаги для воспроизведения ошибки:**

1. Шаг один
Получить сотню+ камней
2. Шаг два
Огранить
3. Шаг три
Не получить ни одного прока совершенной огранки.
4. Шаг четыре, дополнительно.
Огранить соседний камень того же уровня и цвета, получить достаточно много совершенных камней, чесать в затылке и думать "как так-то?".

**Текущее обновление ядра:**

Logon 3 WowCircle Development
Последнее обновление ядра: Build 163 2017-07-25 11:59:12 +0400

Живой сервер, не птр.

**Comment by Devinette** [comment]
Нужны доказательства, что на официальной версии было иначе

**Comment by Hellsingoff** [comment]
Честно говоря не знаю как доказать это в условиях отсутствия опыта ювы на офе в личе. Комментарий к камню, который я тут так и не получил за сотню огранок на вовхэде всего один.
http://ru.wowhead.com/item=41458#english-comments
Я думаю, если бы этот камень было невозможно получить - на вовхэд подняли бы эту тему. А так - всего 1 коммент, да и тот описывает этот гем как годный для низкого бюджета. Годный неполучаемый гем? Нонсенс.
Ко второму приводимому мной в пример камню тоже нет отрицательных комментариев на вовхэд, только 2 нейтральных. Неужели это похоже на комментарий неполучаемого камня?
http://ru.wowhead.com/item=39960#english-comments
Не знаю чем ещё аргументировать мою точку в реалиях прошедших 9 лет от лича на офе.
