### ISSUE TITLE
[Заклинание] ID 54349 - Полная власть над демонами

### ISSUE THREAD

**Issue by Darkremains** [VirginTeam/WotlkCore#432]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

ID 54349 - Полная власть над демонами (http://wowroad.info/?spell=54347)
ID 54349 - Полная власть над демонами (http://wowroad.info/?spell=54348)
ID 54349 - Полная власть над демонами (http://wowroad.info/?spell=54349)

**Что работает не так?**

Нет увеличения вероятности критического удара питомца на (10%/20%/30%) от вероятности критического удара чернокнижника (проверены http://wowroad.info/?spell=688 и http://wowroad.info/?spell=30146).

**Как должно работать?**

Вероятность критического удара питомца должна увеличиваться на (10%/20%/30%) от вероятности критического удара чернокнижника.

**Шаги для воспроизведения ошибки:**

1. Шаг один
2. Шаг два
3. Шаг три

**Текущее обновление ядра:**

Build 35 2017.08.01 PTR
Похоже, что проблема очень старая (возможно со смены ядра)

**Comment by Gringer444** [comment]
Где пруфы, братишка?

**Comment by Darkremains** [comment]
Бес:
[Без таланта](https://youtu.be/04fQT2erz5M)
[Талант 1/3](https://youtu.be/8JNXXeTNl7A)
[Талант 2/3](https://youtu.be/RTY8v5T2b5k)
[Талант 3/3](https://youtu.be/ma1JcfyHIR4)
Страж Скверны:
[Без таланта](https://youtu.be/W_4Xs5KT1hw)
[Талант 1/3](https://youtu.be/NZeLbTgwess)
[Талант 2/3](https://youtu.be/SomEwaHmnzg)
[Талант 3/3](https://youtu.be/fKjsth_vo18)

Такие устроят?

**Comment by Riazarre** [comment]
Выборка из 200 ударов кажется неубедительной, имхо, я бы по 1000 ударов делал минимум.

**Comment by Darkremains** [comment]
Страж Скверны:
[Без таланта](https://youtu.be/Lavv_AA1cq4)
[Талант 1/3](https://youtu.be/Rrin_nTsUuI)
[Талант 2/3](https://youtu.be/_yp0olyNDRQ)
[Талант 3/3](https://youtu.be/FcblnD1QGao)
Бес:
[Без таланта](https://youtu.be/UM2ybNBf0e8)
[Талант 1/3](https://youtu.be/pbQZLC7Gco4)
[Талант 2/3](https://youtu.be/jqlwFH-IMas)
[Талант 3/3](https://youtu.be/D7M6RUQGIjE)

Теперь более убедительно? Или есть еще какие-то вопросы?

**Comment by Gooldark** [comment]
Да не нужно столько пруфов, ты только свое личное время тратишь, достаточно было 2-х скриншетов один с 1000 ударов без тала, второй 1000 ударов с талом, да и разработчик сам может глянуть есть баг или нет. Тут вот в чем проблема, важно знать должен ли этот передавать шанс крита, или именно рейтинг критического удара. Кончено написано что передает шанс крита, но увы часто тултипы не отражают действительность. Если есть подтверждение что именно передавал талант, то это было бы очень хорошо увидеть в этой теме.

**Comment by Darkremains** [comment]
Английского тултипа хватит?
[1](http://pixs.ru/showimage/WoWScrnSho_3240832_27380619.jpg)
[2](http://pixs.ru/showimage/WoWScrnSho_1829072_27380622.jpg)

**Comment by Gooldark** [comment]
Конечно хотелось бы вов вики или инфы с какого нибудь старого форума. Но если нет так нет. Думаю что у петов нету понятие рейтинга крита, возможно действительно близы просто переносили часть крита петам.

**Comment by Darkremains** [comment]
3 месяца прошло, есть новости?

**Comment by Gooldark** [comment]
Как пофиксят, так пофиксят

**Comment by ForesterDev** [comment]
Будет исправлено после обновления

**Comment by MedoOf** [comment]
Работает 1/3 точно, остальные не проверял

**Comment by ForesterDev** [comment]
Исправлено
