### ISSUE TITLE
[Задание] ID 181 - Взгляни на звёзды

### ISSUE THREAD

**Issue by Repenator** [VirginTeam/WotlkCore#433]
**Описание:**

Не работает задание "Взгляни на звёзды" http://ru.wowhead.com/quest=181

**Что работает не так?**

У нужного огра не выпадает квест итем http://ru.wowhead.com/item=1968. Пробовал 3 раза, ни одного раза не выпал. Возможно процент выпадения слишком маленький.

**Как должно работать?**

Квест итем должен упасть со 100% вероятностью.

**Шаги для воспроизведения ошибки:**

1. Прийти в искомую пещеру.
2. Убить искомого огра и снять с него лут.

**Текущее обновление ядра:**

Build 163 2017-07-25 11:59:12 +0400

**Comment by Devinette** [comment]
Задание выполняли самостоятельно или в группе?

**Comment by Repenator** [comment]
В группе

Отправлено из мобильной Почты Mail.Ru

Понедельник, 21 августа 2017 г., 14:09 +0800 от Мария  <notifications@github.com>:
Задание выполняли самостоятельно или в группе?

**Comment by Repenator** [comment]
Однако сопартиец был в другой локации.

Отправлено из мобильной Почты Mail.Ru

Понедельник, 21 августа 2017 г., 14:09 +0800 от Мария  <notifications@github.com>:
Задание выполняли самостоятельно или в группе?

**Comment by Devinette** [comment]
Выполняйте квест без группы, самостоятельно

**Comment by Repenator** [comment]
То есть квест работает, но только не в составе группы?

**Comment by Repenator** [comment]
Попытался выполнить задание без группы, та же проблема.

**Comment by Hellsingoff** [comment]
У меня есть хант, у него 90% квест итемов не дропаются. Даже тех, у которых шанс 100%. Долго и муторно общался с поддержкой. Изначально был ответ "ваша проблема, похоже, имеет массовый характер", но по итогу - "мы не смогли воспроизвести это на тестовом сервере". 

Не помог ни сброс в личном кабинете, ни сброс талантов, ни смена пета. Только смена персонажа. Другой персонаж в группе с тем же магом, с кем я играл ранее, сразу исправил ошибку. Вывод - иногда багуется конкретный персонаж. Проверяйте другие квесты. Если там будет так же - я бы посоветовал кинуть перса в мусорку сразу, так как я мудохался с поиском проблемы и общением с поддержкой достаточно длительное время и без результатов. (Проблемы начались на 20 уровне, брошен перс был на 62)

Другие квесты работают точно нормально? Пробовали многократно убивать данного NPC? Мне падали квестовые предметы порой с десятого раза, не очень ясно от чего конкретно зависели обстоятельства, но в итоге предмет я получал. Просто долго и мучительно.

**Comment by gmOpex** [comment]
Пробовал выполнять. Предмет не упал. Внес правки по шансу дропа. Должен падать со 100% шансом

**Comment by ForesterDev** [comment]
Работает
