### ISSUE TITLE
[Предмет] ID 50045 - Символ извечной воды

### ISSUE THREAD

**Issue by MedoOf** [VirginTeam/WotlkCore#434]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Символ извечной воды. http://wowroad.info/?item=50045

**Что работает не так?**

При установке символа у элементаля воды падает количество здоровья до 3к и урон до 600.

**Как должно работать?**

Хп и урон не должны изменяться, должна пропадать нова у элема и он должен становиться постоянным питомцем.

**Шаги для воспроизведения ошибки:**

1. Символ извечной воды
2. Призвать элементаля воды
3. Посмотреть на его запас здоровья и урон

**Текущее обновление ядра:**
Logon 3 WowCircle Development
[09:13] Ïîñëåäíåå îáíîâëåíèå ÿäðà: Build 163 2017-07-25 11:59:12 +0400

**Comment by Kodekc** [comment]
Внесены исправления. Будут применены в ближайшем обновлении

**Comment by gmRial** [comment]
ХП элементаля действительно падает, но если переодеть любой предмет из экипировки - оно скаллируется. При перепризыве (например, после использования маунта), пару секунд ХП остается базовым, после чего происходит перерасчет характеристик и ХП вырастает.
Урон в пределах нормы.
