### ISSUE TITLE
[Заклинание] ID 63468 - Пронзающие выстрелы

### ISSUE THREAD

**Issue by MedoOf** [VirginTeam/WotlkCore#435]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

http://wowroad.info/?spell=63468. Неправильная скаляция урона при увеличении процентных модификаторов. 

**Что работает не так?**

Пронзающие выстрелы наносят 31,5% от критического урона "Прицельный выстрел", "Верный выстрел" и "Выстрел химеры". Также Пронзающие выстрелы усиливаются процентными модификаторами урона (истерия, прок т10 ханта, баф цлк и другие).
http://forum.wowcircle.com/showthread.php?t=95581&page=129&p=6019096&viewfull=1#post6019096 - ссылка на скрин где пронзающие с котом, рогой, укусом ланы и бафом цлк наносят 29% от общего урона.

**Как должно работать?**

Пронзающие выстрелы должны наносить 30% урона от критов "Прицельный выстрел", "Верный выстрел" и "Выстрел химеры", и не усиливаться ничем, кроме дебафа от увечье ферала или травма армс вара на боссе, т.к. все % модификаторы уже подействовали на способность, которая и вызвала прок пронзающих.

**Шаги для воспроизведения ошибки:**

1. Взять все бафы увеличивающие урон от кровотечений в %
2. Нанести хантом 1-3 миллиона урона
3. Посмотреть на урон от пронзающих

**Текущее обновление ядра:**

Logon 3 WowCircle Development
[09:56] Ïîñëåäíåå îáíîâëåíèå ÿäðà: Build 163 2017-07-25 11:59:12 +0400

**Comment by Rorshah** [comment]
Не знаю при чем там модификаторы, но все должно считаться достаточно просто.
Итоговый рекаунт.
Смотрим критический урон от Прицельного, верного и выстрела химеры.
Суммируем.
Умножаем на 0,3 (считаем что всё накровоточило, хотя последние криты могут недодикать, но то копейки). Получаем урон от Пронзающих выстрелов. Если в рейде есть кот/мишка добавляем еще 30% от их бафа, т.е. полученную сумму умножаем на 1,3. Сравниваем с рекаунтом Пронзающих выстрелов. Сходится ? все ок. Не сходится ? нужно править.

**Comment by MedoOf** [comment]
Пронзающие выстрелы наносят  31,5% от критического урона "Прицельный выстрел", "Верный выстрел" и "Выстрел химеры". Также Пронзающие выстрелы усиливаются процентными модификаторами урона (истерия, прок т10 ханта, баф цлк и другие).
Пронзающие выстрелы должны наносить 30% урона от критов "Прицельный выстрел", "Верный выстрел" и "Выстрел химеры", и не усиливаться ничем, кроме дебафа от увечье ферала или травма армс вара на боссе, т.к. все % модификаторы уже подействовали на способность, которая и вызвала прок пронзающих.

**Comment by ForesterDev** [comment]
https://forum.wowcircle.com/showthread.php?t=454543 это старый репорт, в котором исправлялось влияние модификатора Мастерского выслеживания на урон пронзающих стрел. Соответственно двойное скалирование от чего то идет, а от чего-то - нет.  Нужно дополнить репорт

**Comment by MedoOf** [comment]
Что значит дополнить? Талант на выслеживание должен апать да, как и дебафы увечье/травма на боссе. Но больше то ничего не должно, что конкретно нужно проверить и дополнить?
Кусок лога с 25гер:

> [18:29:21.760] Черныйлифчик Верный выстрел Саурфанг Смертоносный *12413*
> [18:29:21.949] Саурфанг Смертоносный afflicted by Пронзающие выстрелы from Черныйлифчик
> [18:29:22.080] Черныйлифчик casts Выстрел химеры on Саурфанг Смертоносный
> [18:29:22.573] Черныйлифчик Выстрел химеры Саурфанг Смертоносный *19301*
> [18:29:22.732] Саурфанг Смертоносный's Пронзающие выстрелы is refreshed by Черныйлифчик
> [18:29:23.715] Черныйлифчик Пронзающие выстрелы Саурфанг Смертоносный 2394

Получаем что (12413+19301)*0,3/8*1,05*1,3=1623
У нас же там 2394.
Напишите хотя бы существующую формулу пронзающих, откуда игрокам знать что там проверять? Баф цлк? Таланты ханта? Дебафы на боссе?

**Comment by MedoOf** [comment]
Таланты охотника: http://db.logon3.com/?spell=35029
http://db.logon3.com/?spell=35030
http://db.logon3.com/?spell=19507
http://db.logon3.com/?spell=19508
http://db.logon3.com/?spell=19509
Талант питомца:
http://db.logon3.com/?spell=61680
http://db.logon3.com/?spell=61681
http://db.logon3.com/?spell=52858
Таланты ретрика, аркана, бма увеличивающие урон всех в группе: http://db.logon3.com/?spell=31869
http://db.logon3.com/?spell=31579
http://db.logon3.com/?spell=31582
http://db.logon3.com/?spell=31583
http://db.logon3.com/?spell=34455
http://db.logon3.com/?spell=34459
http://db.logon3.com/?spell=34460
Сетовый бонус 2т10: http://db.logon3.com/?spell=70728
Не должны оказывать влияние на урон пронзающих выстрелов
Также НЕ ДОЛЖНЫ оказывать влияние - баф цлк, баф от укуса ланы, баф от порталов в ивк на валькириях, материальность халиона, истерия, дебаф комбата/армса и прочее.

ДОЛЖНЫ влиять таланты охотника:http://db.logon3.com/?spell=52783
http://db.logon3.com/?spell=52785
http://db.logon3.com/?spell=52786
http://db.logon3.com/?spell=52787
http://db.logon3.com/?spell=52788
Дебафы на урон от кровотечений (Apply Aura: Mod Mechanic Damage Taken Percent (Кровоточащий)), накладываемые заклинаниями: http://db.logon3.com/?spell=46854
http://db.logon3.com/?spell=46855
http://db.logon3.com/?spell=33917

**Comment by Rorshah** [comment]
Щас хантов понерфим и надо будет за магов браться.

**Comment by Kodekc** [comment]
Исправлена формула расчета урона Пронзающий выстрелов при взаимодействии с аурами, повышающими урон. Необходимо перепроверить

**Comment by MedoOf** [comment]
Работает. По крайней мере таланты, баф цлк, истерия, бонус т10 точно работает. Укус ланы и порталы на валькириях в ивк позже проверится.
