### ISSUE TITLE
[NPC] ID 15242 - Защитник-наездник на нетопыре

### ISSUE THREAD

**Issue by Gringer444** [VirginTeam/WotlkCore#437]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Зангартопь. Застава Болотной Крысы. Некорректное поведение НПЦ (и, возможно, неверное месторасположение)

**Что работает не так?**

При приближении к данному НПЦ вешается бой.
P.S. Wowroad говорит, что такие НПЦ находятся только на Полуострове Адского Пламени, в Траллмаре.

**Как должно работать?**

НПЦ должен нормально реагировать на членов дружественной фракции (в данном случае - Орды)
И, возможно, вообще не должен находится в выше указанном месте.

**Шаги для воспроизведения ошибки:**

1. Прилететь в Зангартопь
2. Прилететь на Заставу Болотной Крысы
3. Приблизиться к НПЦ

**Текущее обновление ядра:**

WoW Circle 3.3.5a x1 PvE
Build 163 2017-07-25 11:59:12 +0400

**Comment by Santaria94** [comment]
https://www.youtube.com/watch?v=hBOjPHXsj6c&feature=youtu.be - видео по одному из квестов с Застава Болотной Крысы. На нем видно, что подобных наездников на нетопырях на заставе нет.

Также стоит отметить, что данные НПС не заселены в Зангартопи, а появляются из-за какого-то скрипта и через некоторое время пропадают, а затем вновь появляются.
