### ISSUE TITLE
[Задание] ID 10867 - Ответ будет только один

### ISSUE THREAD

**Issue by any7hing** [VirginTeam/WotlkCore#438]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Разаани, нужно убивать мобов в их лагере, после нескольких килов должен появится квестовый моб которого надо убить и залутать

**Что работает не так?**

квестовый моб не появляется, должен появляться после 10-15 килов, он не появляется даже после 50

**Как должно работать?**

квестовый моб должен появляться после нескольких килов мобов в лагере

**Шаги для воспроизведения ошибки:**

1. берете квест
2. летите в лагерь
3. бьете мобов

**Текущее обновление ядра:**

 Последнее обновление ядра: Build 163 2017-07-25 11:59:12 +0400
L3x1PVE

**Comment by gmKroshka** [comment]
http://forum.wowcircle.com/showthread.php?t=429909
