### ISSUE TITLE
[Предмет] ID 181068, 181069 - Большая обсидиановая глыба и Маленький кусочек обсидиана

### ISSUE THREAD

**Issue by Plasmashield** [VirginTeam/WotlkCore#442]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Отсутствуют обсидиановые жилы(маленькие и большие) в ак20 и ак40. Как следствие невозможно получить http://wowroad.info/?item=22202

**Что работает не так?**

http://wowroad.info/?object=181068
http://wowroad.info/?object=181069
Не спавнятся в ак20 и ак40 ни при каких условиях

**Как должно работать?**
С вовхэда:

"These are random from mining. they come from the trash before moam, and the trash before Ossirian. the mobs drop a deposit to mine when they die. there is no limit to how many of these you can mine per run, its just luck. Moam drops a larger deposit to mine, so increased chance there. They are used for blacksmithing to create various epic items. usually sell for around 50g"
"These are mineable nodes that spawn next to a mob when it dies, once per mob killed, and only from Moam in Ruins of Ahn'Qiraj and Anubisath Defender in Temple of Ahn'Qiraj (found before and after the Twin Emperors)."

**Шаги для воспроизведения ошибки:**

1. Зайти в данжи, убить анубисатов всех видов
2. Не обнаружить жил
3. Пуская слезы смотреть на рецы для которых требуется http://wowroad.info/?item=22202

**Текущее обновление ядра:**

Build 163 2017-07-25 11:59:12 +0400

**Comment by Kodekc** [comment]
К сожалению, нет информации о заселении данных объектов, по этому их нет в игре. Если ситуация изменится и получится найти информацию о заселении, обязательно добавим их в то место, где они должны быть.

**Comment by Plasmashield** [comment]
В плане заселение? В тикете вроде написано, что они должны появляться после убийства анубисатов, а также после убийства Моама и Осириана. Я пока не нашел видео, где четко видно как это происходит в случае с обычными анубисатами. А вот с Моамом нашел:
https://youtu.be/MKKRoddXURE
https://youtu.be/9UStUPWbFds
https://youtu.be/Wm01IIaTs14

**Comment by Kodekc** [comment]
Ну я ж не возьму с головы данные и не могу просто так бацнуть объекты, где мне хочется.

**Comment by Oleksiymir** [comment]
Ну так после Моама же можно поставить? Видос скинули вам.

**Comment by ForesterDev** [comment]
Иправлено, будет применено в обновлении
