### ISSUE TITLE
[Достижение] ID 2154 - Поле Бранни

### ISSUE THREAD

**Issue by ar4i2018** [VirginTeam/WotlkCore#444]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Не дается достижение [[Поле Бранни]](http://ru.wowhead.com/achievement=2154).
"Одержите верх над Трибуналом Веков в Чертогах Камня в героическом режиме, чтобы Бранн Бронзобород не получил ни одного повреждения."
Прошел подземелье четыре раза, но достижение так и не дали. Мобы до Бранна даже не добрались. 
Последние два раза проверял, чтобы у Брана было 100%. Так и было, у Бранна 100%, а достижения нет.

**Что работает не так?**

Не дается достижение.

**Текущее обновление ядра:**

Build 163 2017-07-25 11:59:12 +0400

**Comment by ForesterDev** [comment]
![image](https://user-images.githubusercontent.com/11771800/58955773-dd18e900-87ad-11e9-9f2a-a0b2f9d207c1.png)
Все работает
