### ISSUE TITLE
[Задание] ID 3062 - Темное сердце

### ISSUE THREAD

**Issue by deexeq** [VirginTeam/WotlkCore#446]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Что работает не так?**

По нужным координатам не призывается [Эдана Коготь Ненависти](http://wowroad.info/?npc=8075)
Нашёл видео аналогичной проблемы:
https://www.youtube.com/watch?v=QjrMHd8e9xw
**Как должно работать?**

Должна призываться

**Текущее обновление ядра:**

Build 163

**Comment by sega693** [comment]
http://db.logon3.com/?quest=3062 квест
http://db.logon3.com/?item=9530 рог

> Трубить в рог надо где-то около 40,5:8,5. Если у вас нет аддона выставляющего координаты, найдите камень бубликом -- у него в отверстии что-то летает и пузырится. Он стоит на коротенькой тропинке с фонариками.

> Рог выбивается с гарпий 41.12 Фералас. Сама Эдана вызывается 41.8
