### ISSUE TITLE
[NPC] id 25802 - Кау Гроза Мамонтов

### ISSUE THREAD

**Issue by gmOverfire** [VirginTeam/WotlkCore#447]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Что работает не так?**

По неизвестным причинам может быть в текстурах.

**Как должно работать?**

Должен быть только на своем месте http://ru.wowhead.com/npc=25802#map

**Текущее обновление ядра:**

Virgin Build 163

**Comment by Kodekc** [comment]
Если у кого-то будет больше информации об этом, то добавьте комментарий в этот репорт. Пока исправлять нечего, так как способа воспроизведения нет

**Comment by gmOverfire** [comment]
В ходе наблюдений было выявлено, что НПЦ проваливается под текстуры, будучи под воздействием http://db.logon3.com/?spell=46316
Способы воспроизведения могут быть разными.
1. НПЦ сидя на http://db.logon3.com/?npc=25881 может "упасть" в текстуры, если Морию убивают в страхе.
2. НПЦ может сам провалиться в текстуры, будучи в страхе.
3. НПЦ можно добить в страхе, и он провалится под текстуры.

**Comment by Nimlotnik** [comment]
Когда починят? Из за этого невозможно выполнить 2 ачивки: "ДЭГОЖ наш пригож" и "борьба в борейщине". Всего то и надо что запретить на него фир. Ибо на оффе он сам не фирится только его прислужники.

**Comment by ForesterDev** [comment]
Протестируйте после обновления
