### ISSUE TITLE
[Задание] ID 13380 - Возглавить нападение

### ISSUE THREAD

**Issue by MyWorldik** [VirginTeam/WotlkCore#451]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

http://ru.wowhead.com/quest=13380
Технология инфразеленого излучения позволяет нам оставаться "невидимыми" прямо под носом у Плети! Больше того, мы установили инфразеленые излучатели на специально сконструированные бомбардировщики... но вовсе не для того, чтобы скрыть эти машины от глаз врага, нет! Мы используем излучение как щит!
Ступай туда, где стоит Карен Нет, попроси бомбардировщик. Лети в Зону бомбардировки... используй щиты и пушку для защиты, а бомбометы – понятное дело, для бомбометания. В общем, потренируйся, а потом возвращайся ко мне. Я дам тебе новое задание, которое будет уже посерьезнее!

**Что работает не так?**

Когда говоришь с Карен - бомбардировщик не летит, ничего не происходит. Над зоной бомбардировки и на них летают бомбардировщики, но они баганые - когда в них садишься, то не можешь управлять и стрелять. 

**Как должно работать?**

Поговорить с НПС Карен, она присылает бомбардировщик, полететь на зону бомбардировки и убивать элитных мобов

**Шаги для воспроизведения ошибки:**

1. Шаг один
2. Шаг два
3. Шаг три

**Текущее обновление ядра:**
Build 163 2017-07-25, 11:59:12, +0400

**Comment by Riazarre** [comment]
Ссылку на задание в описание добавьте, заголовок отредактируйте

**Comment by MyWorldik** [comment]
Отредактировано

**Comment by Climss** [comment]
Актуально
Build 277 2019-10-30 12:31:19 +0400 Logon 3 x1 PvE

**Comment by vkeda** [comment]
Не засчитывает капитанов и горгулей в квест.
Бомбардировщика нет.
Build 282 2019-12-18 12:39:11 +0400
