### ISSUE TITLE
[Заклинание] ID 54490 - Заградительные стрелы

### ISSUE THREAD

**Issue by Gooldark** [VirginTeam/WotlkCore#453]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Есть вероятность что работает правильно, но это легче определить по коду.
 ID 54490 - Заградительные стрелы(http://wowroad.info/?spell=54490)
С вероятностью 40% после произнесения заклинания "Чародейская вспышка" и с вероятностью 20% после произнесения заклинаний "Чародейский обстрел", "Огненный шар", "Ледяная стрела" или "Стрела ледяного огня" время применения последующего заклинания "Чародейские стрелы" сократится на 2.5 с, затраты маны снизятся на 100% и стрелы будут создаваться каждые 0,5 секунды.

**Что работает не так?**

Шанс срабатывания от применения Чародейской вспышки равен 8% за каждый ранг таланта (40% для 5/5)

**Как должно работать?**

Шанс срабатывания от применения Чародейской вспышки должен быть равен 10% за каждый ранг таланта (50% для 5/5).

**Доказательства**

http://forum.wowcircle.com/showthread.php?t=703120

**Текущее обновление ядра:**

31.08.2017

**Comment by gmRial** [comment]
Исправлено, после обновления.
