### ISSUE TITLE
[Заклинание] ID 61316 -Чародейская гениальность Даларана

### ISSUE THREAD

**Issue by kalipsa988** [VirginTeam/WotlkCore#454]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Баф не по уровню:**

Добавьте описание проблемы здесь.

**Баф http://wowroad.info/?spell=61316 кидается на лоу лв на +60 инты, как и на 80е**

Фактический результат — тот, который вы наблюдаете

**https://www.youtube.com/watch?v=Wg_LMBLDAQY&spfreload=10 в этом видео сам баг и как его делать**

Ожидаемый результат — то, чего вы ожидали при выполнении ваших действий. Процесс правильной работы

**Шаги для воспроизведения ошибки:**

1. Найти мага с http://wowroad.info/?spell=61316
2. Взять его лоу лв в пати
3. Попросить бафнуть http://wowroad.info/?spell=61316

**Последнее обновление ядра: Build 163 2017-07-25 11:59:12 +0400**

Можно посмотреть в игре, введите в чат команду .server info и скопировать строку начиная с Build с номером и датой. Не забывайте указывать, Live Server или PTR Server, где проводилось тестирование

**Comment by gmKroshka** [comment]
Будет исправлено после обновления
