### ISSUE TITLE
[Игровая механика] Заклинания, временно блокирующие угрозу от персонажа.

### ISSUE THREAD

**Issue by Trombocid** [VirginTeam/WotlkCore#456]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Если маг во время действия http://wowroad.info/?spell=55342 [Зеркальное изображение], либо прист во время действия http://wowroad.info/?spell=586 [Уход в тень] получает бафф, снижающий уровень трита, будь то http://wowroad.info/?spell=1038 [Длань спасения], http://wowroad.info/?spell=3411 [Вмешательство], и т.д., трит багается и подскакивает до небес. При этом далее снизить уровень трита игрока или забрать танку противника на себя не представляется возможным никаким образом. 

**Что работает не так?**

Многократное повышение уровня трита баффом, который напротив должен его снижать.

**Как должно работать?**

Уровень трита должен быть адекватно снижен на указанное значение.

**Шаги для воспроизведения ошибки:**

1. Вступить магом/пристом в бой.
2. Прожать иллюзий/уход в тень.
3. Получить бафф, снижающий уровень трита.

**Текущее обновление ядра:**

Build 163 2017-07-25 11:59:12 +0400

**Comment by TepaMeTp** [comment]
http://forum.wowcircle.com/showthread.php?t=573291
Темка со старого форума.
По всей видимости fade эффекты (заморозка уровня угрозы) вешают временное отрицательное значение
У клонов мага
(6) Apply Aura #103: Mod Total Threat (Fade) Значение: -90000000

У пристов
(6) Apply Aura #103: Mod Total Threat (Fade) Значение: -55

У расовой эльфов (по вовроад, ога)
(6) Apply Aura #103: Mod Total Threat (Fade) Значение: -90000000

**Comment by Trombocid** [comment]
Актуально
Build 305 2020-06-09 22:27:39 +0400
