### ISSUE TITLE
[Задание] id 12540 - Исполнение приказа

### ISSUE THREAD

**Issue by MyWorldik** [VirginTeam/WotlkCore#457]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

http://ru.wowhead.com/quest=12540
Что ж, <парень/подружка>, у Ракжака есть для тебя очень, очень важное дело. Следопыт выследил к северу отсюда у реки раненого длинноязыкого. Иди и поймай его.

Не бери охотника в этот раз, охотник его захочет убивать. А я хочу спрятать его у себя. Я буду тыкать в него, а он будет говорить мне разные вещи.

Теперь иди и притащи мне длинноязыкого.

**Что работает не так?**

Раненый оракул стоит живой. При нажатии на НПС поле пустое, квест не сдается

**Как должно работать?**
 Найти раненого оракула и сдать ему квест

**Шаги для воспроизведения ошибки:**

1. Шаг один
2. Шаг два
3. Шаг три

**Текущее обновление ядра:**

Последнее обновление ядра: Build 163 2017-07-25 11:59:12 +0400

**Comment by Riazarre** [comment]
Нужно подтверждение актуальности, или репорт будет отклонен.

**Comment by MyWorldik** [comment]
Актуально
2 окт. 2017 г. 13:45 пользователь "Overfire" <notifications@github.com>
написал:

**Comment by Ewropa** [comment]
нужна запись бага, чтоб посмотреть, что не так

**Comment by anmaxien** [comment]
Квест по прежнему не рабочий, невозможно прокачать репутацию с волчерами. НПЦ никак не реагирует на игрока, просто стоит зеленый пассивный

**Comment by MyWorldik** [comment]
Актуально
9 дек. 2017 г. 14:52 пользователь "anmaxien" <notifications@github.com>
написал:

**Comment by gmOpex** [comment]
Полностью исправный квест "тестирование от 23.01.18"

**Comment by anmaxien** [comment]
Квест по прежнему не рабочий. НПЦ просто зеленый как и был. Скриншоты готовы и могу предоставить если обьясните как на этом форуме их загружать

**Comment by gmOpex** [comment]
https://b.radikal.ru/b29/1801/59/03de89e84dec.jpg

https://d.radikal.ru/d11/1801/8d/d59050dce00a.jpg

https://d.radikal.ru/d28/1801/e6/9343bce0e754.jpg

понятия не имею на каком сервере вы делаете задания.С логон1 не путаете?

**Comment by anmaxien** [comment]
эм... я играю на х1.))) logo3.wowcircle.com
могу связаться с Вами в игре и в пати показать что все очень плохо

**Comment by anmaxien** [comment]
я так понимаю на починку задания забит болт?
@Kodekc Kodekc added ✘ Не воспроизводится  and removed ❢ Задания  ✘ Работает правильно  labels 2 days ago

**Comment by anmaxien** [comment]
все ясно, очередное подтверждение криворукости и некомпетентности наших админов. тема закрыта

**Comment by vanuat** [comment]
Up! 
Квест по прежнему не работает!
