### ISSUE TITLE
[Задание] ID 13417 - Братья Бронзобороды

### ISSUE THREAD

**Issue by MyWorldik** [VirginTeam/WotlkCore#458]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

http://ru.wowhead.com/quest=13417

**Что работает не так?**

Квест берется, но Бронзобород с ветролетом сразу пропадают. Когда улетаешь и возвращаешься, то он появляется, садишься. Как только вылетаешь из ямы, выбрасывает из ветролета и квест не засчитывается.

**Как должно работать?**

Забраться ветролет и прикрывать Бранна от железных дворфов

**Шаги для воспроизведения ошибки:**

1. Шаг один
2. Шаг два
3. Шаг три

**Текущее обновление ядра:**

Build 163 2017-07-25 11:59:12 +0400

**Comment by Riazarre** [comment]
Добавляйте ID в заголовок :)

**Comment by Kodekc** [comment]
Три раза правил уже фазирование по этому заданию и всё не успешно :-(

**Comment by MiceRus** [comment]
Не знаю, что там правили, а квест вообще не берется.
Висит восклицательный знак, при попытке взять квест вообще ничего не происходит. Даже диалога нет.
Бронзобород сидит в ветролете и его иконка такого цвета, как буд-то он далеко

**Comment by gmKroshka** [comment]
Будет исправлено после обновления
