### ISSUE TITLE
[Рейд] Черный храм (ID 23419 Воплощение мечты)

### ISSUE THREAD

**Issue by olegklim1991** [VirginTeam/WotlkCore#461]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

[Подземелье]Черный храм- (ID 23419) Воплощение мечты

**Что работает не так?**

у данного босса http://ru.wowhead.com/npc=23419 не работает спелл http://ru.wowhead.com/spell=41350
вернее работает спел ,но не полностью
нет переодического теряния маны 300 маны в 5 сек

**Как должно работать?**

дописать в спелл теряние маны 300 в 5 сек

**Шаги для воспроизведения ошибки:**

1. бить босса
2. при фул мане ничего не делать и будет видно что мана не отнимается

**Текущее обновление ядра:**
#38 Build - 163 (Build - 51)
Live Server

**Comment by ForesterDev** [comment]
Исправлено, проверьте после обновления

**Comment by olegklim1991** [comment]
работает босс как надо,хадкорчик обеспечен)
