### ISSUE TITLE
Танец Теней

### ISSUE THREAD

**Issue by junked** [VirginTeam/WotlkCore#462]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Невозможно сесть на маунт или флай под бафом Танец Теней.

**Что работает не так?**

Баф Танец Теней не дает сесть на маунта. Приходится писать макрос на снятие шд при касте маунта.

**Как должно работать?**

Баф Танца Теней не мешает садится на маунта, и никуда не пропадает пока его эффект не закончится по истечении времени.

**Шаги для воспроизведения ошибки:**

1. Включаем Танец Теней
2. Пытаемся сесть на маунта

**Текущее обновление ядра:**

Live Server, Build 163 2017-07-25 11:59:12 +0400

**Comment by Riazarre** [comment]
Пруф, что это неправильно?
