### ISSUE TITLE
Исчезновение

### ISSUE THREAD

**Issue by junked** [VirginTeam/WotlkCore#466]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Исчезновение не сбрасывает мобов с игрока. Нашел проблему фармя инсты именно Запределья, баг проявляется так же и на обычных мобах в его локациях. В Нордсколе и Азероте тестил достаточно бегло, возможно что это проявляется и там. 

**Что работает не так?**

Исчезновение не сбрасывает мобов с игрока. Если мобов много, Исчезновение может сбросить лишь частично некоторых. Даже если проюзать Исчезновение, прожать спринты, отбежать от бегущих за игроком мобов и еще раз прожать Исчезновение, то ничего не произойдет, мобы будут бежать за игроком пока их не убьют или они не выйдут за аггро радиус, если это не инстанс.

Есть догадка, что так происходит когда моб увидел рогу в стелсе, после чего рога жмет ваниш а моб его по прежнему видит.

https://youtu.be/F0P_x7d32PI
https://youtu.be/NruGRmmA7gw (где то с 25 секунды можно смотреть)
https://youtu.be/8RKAGaIbvzA (с 15 секунды смотреть)

**Как должно работать?**

Исчезновение сбрасывает комбат и мобов с игрока. Игрок во время действия бафа исчезновения практически невидим ни для кого, моб никак не может повторно сагрится, особенно если он лоу лвл.

**Шаги для воспроизведения ошибки:**

1. Заходишь в пачку мобов, желательно в инсте Запределья.
2. Юзаешь Исчезновение

Если не выходит то:

1. Заходишь в пачку мобов так, что бы моб тебя увидел
2. Юзаешь Исчезновение

**Текущее обновление ядра:**

Live Server, Build 163 2017-07-25 11:59:12 +0400

**Comment by Riazarre** [comment]
Заголовок согласно шаблону, ссылку на заклинание в описание.
https://github.com/VirginTeam/VirginCore/wiki/%D0%A1%D1%82%D0%B0%D0%BD%D0%B4%D0%B0%D1%80%D1%82%D0%B8%D0%B7%D0%B0%D1%86%D0%B8%D1%8F-%D0%B7%D0%B0%D0%B3%D0%BE%D0%BB%D0%BE%D0%B2%D0%BA%D0%BE%D0%B2-%D0%B4%D0%BB%D1%8F-%D1%80%D0%B5%D0%BF%D0%BE%D1%80%D1%82%D0%BE%D0%B2

**Comment by junked** [comment]
Мне это меньше всего надо, я тут практически уже не играю. Сами оформляйте.
