### ISSUE TITLE
[Задание] id 13373 - Последнее слово техники

### ISSUE THREAD

**Issue by Rialzarre** [VirginTeam/WotlkCore#468]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Что работает не так?**

Нет возможности побеседовать с НИП http://ru.wowhead.com/npc=31839

**Как должно работать?**

> Поговорите с Риззи Храпокруткой, что стоит рядом с квестгивером: она посадит вас на бомбардировщик. Самолет имеет несколько режимов: противовоздушная оборона (растреливает гарпий), бомбометание (убивает мобов внизу) и режим ремонта (тушит пожар и восстанавливает щит). Вовремя переключайтесь между этими режимами и выполнение квеста вам обеспечено.

Задание можно выполнить, убивая требуемых нпц ручками, но это крайне долго, неудобно и муторно, т.к. большая часть НПЦ элитные.

**Текущее обновление ядра:**

Virgin Build 163

**Comment by gmKroshka** [comment]
http://forum.wowcircle.com/showthread.php?t=522418

**Comment by b4vrn** [comment]
Насколько я понимаю, основным препятствием в выполнении квеста является не невозможность поговорить с нпс 31839, а отсутствие целевых нпс "Капитан из зоны бомбардировки" [https://ru.wowhead.com/npc=32410/капитан-из-зоны-бомбардировки](url) . 
Совершенно случайно наткнулся на них, невидимых, пачкой стоящих по координатам 55.3 66.9. 
Возможно, информация кому-нибудь поможет.
![wowscrnshot_090418_051017](https://user-images.githubusercontent.com/35558481/45007041-8440d800-b004-11e8-9a58-943e39ee2934.jpg)

**Comment by CallOBock** [comment]
> Насколько я понимаю, основным препятствием в выполнении квеста является не невозможность поговорить с нпс 31839, а отсутствие целевых нпс "Капитан из зоны бомбардировки" [https://ru.wowhead.com/npc=32410/капитан-из-зоны-бомбардировки](url) .
> Совершенно случайно наткнулся на них, невидимых, пачкой стоящих по координатам 55.3 66.9.
> Возможно, информация кому-нибудь поможет.
> ![wowscrnshot_090418_051017](https://user-images.githubusercontent.com/35558481/45007041-8440d800-b004-11e8-9a58-943e39ee2934.jpg)

А кто-нибудь вообще занимается решением данных проблем, скрипты кто-нибудь пишет? Может это всё в пустоту отправлено

**Comment by gmRial** [comment]
Как выбираются репорты, а так же ход всех исправлений можно узнать с нашего дискорда.

**Comment by Climss** [comment]
Актуально
Build 278 2019-11-01 17:15:07 +0400 Logon 3 x1 PvE

**Comment by FilDru** [comment]
Актуально, Капитанов по прежнему нет, да и с неписем сажающим на самолет по прежнему поговорить нельзя.
Build 316 2020-07-13 14:55:36 +0400

**Comment by Hellsingoff** [comment]
Баг актуален, капитаны не там где надо и невидимы, с НПС говорить невозможно
