### ISSUE TITLE
[Предмет] ID 18660 Увеличитель мира

### ISSUE THREAD

**Issue by Holyway** [VirginTeam/WotlkCore#471]
**Описание:**

http://ru.wowhead.com/item=18660 при использование совместно с другими уменьшающими эффектами уменьшает до состояния когда не видно модельку(при использовании уменьшителя мира+несколько бафов уменьшения персонажа становится видно в перевёрнутом виде)

**Что работает не так?**

Эффект уменьшения http://ru.wowhead.com/item=18660 складывается с другими уменьшающими бафами

**Как должно работать?**

Эффект уменьшения http://ru.wowhead.com/item=18660 должен перемножаться с другими уменьшающими бафами

**Шаги для воспроизведения ошибки:**

Использовать http://ru.wowhead.com/item=18660
Наложить еще уменьшающий баф например http://ru.wowhead.com/spell=16595
Теперь персонажа не видно,при накладывании других уменьшающих эффектов персонаж будет увеличиваться в перевёрнутом виде

**Текущее обновление ядра:**

Build 163 2017-07-25 11:59:12 +0400

**Comment by ForesterDev** [comment]
![image](https://user-images.githubusercontent.com/11771800/75655628-b542ad00-5c7b-11ea-8a02-287fb83e8256.png)

Неактуально
