### ISSUE TITLE
[Задание] ID 25285 - Входит и выходит!

### ISSUE THREAD

**Issue by gmKroshka** [VirginTeam/WotlkCore#48]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Для выполнения задания необходимо сесть в механотанк

**Что работает не так?**

Персонаж не садится в механотанк, твкнув по танку, появляется еще один танк, тыкаем еще и еще один появляется и так до бесконечности, но в танк перс не садиться и испытать Систему катапультирования не представляется возможным

**Как должно работать?**

Персонаж должен садиться в танк и система должны быть испытана.

**Шаги для воспроизведения ошибки:**

1. Берем квест
2. Нажимаем на Механотанк

**Текущее обновление ядра:**

PTR Build 20 2017-04-05 12:06:47 +0400

**Comment by SergeyVyach** [comment]
пожалуйста, сделайте этот квест!

**Comment by Awegod** [comment]
Исправлять не будете?

**Comment by Santaria94** [comment]
Кстати можно заметить, что при посадке в танк у него полностью отсутствуют способности.
У http://db.logon3.com/?npc=39682 должна быть способность http://db.logon3.com/?spell=74153

**Comment by d3rkt8mple** [comment]
почините плиз...вся цепочка не работает из-за этого квеста(или откройте следующие квесты)
а у орды например аналогичная цепочка работает полностью
