### ISSUE TITLE
[Подземелья] Верхний ярус Черной горы

### ISSUE THREAD

**Issue by kalipsa988** [VirginTeam/WotlkCore#480]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Отсутствует 1 босс. http://wowroad.info/?npc=10264 из-за не рабочего ивента

**Что работает не так?**

Нет босса http://wowroad.info/?npc=10264 и нельзя получить лут с него
При использовании http://wowroad.info/?object=175245 лутается предмет http://wowroad.info/?item=13371, но больше ничего не происходит

**Как должно работать?**
При использовании объекта Огонь отцов должен начаться ивент: появляется 6 волн по 2 моба с интервалом примерно 30 сек, после их уничтожения появляется сам босс. http://wowroad.info/?npc=10264
**Шаги для воспроизведения ошибки:**

1. Зайти в Верхний ярус Черной горы
2. Дойти до http://wowroad.info/?object=175245 и лутануть http://wowroad.info/?item=13371
3. Увидеть, что ничего не произойдёт

**Текущее обновление ядра:**
Последнее обновление ядра: Build 163 2017-07-25 11:59:12 +0400

**Comment by sega693** [comment]
дубль с https://github.com/VirginTeam/VirginCore/issues/13
