### ISSUE TITLE
[Заклинание] ID 7386 - Раскол брони

### ISSUE THREAD

**Issue by TSayf7kov** [VirginTeam/WotlkCore#482]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

На способность ["Раскол брони"](http://wowroad.info/?spell=7386 ) не действуют таланты, снижающие её стоимость (["Направленная ярость" ](http://wowroad.info/?spell=29792)и "[Прокол"](http://wowroad.info/?spell=12811))

**Что работает не так?**
При вкинутых талантах 3/3 "Направленная ярость" и 3/3 "Прокол" на панели действий стоимость "Раскол брони" отображается корректно (9 ед. ярости), но на самом деле способность требует и расходует 15 ед. ярости.

**Как должно работать?**

 "Раскол брони" должен требовать 9 ед.ярости при 3/3 "Направленная ярость" и 3/3 Прокол"

**Шаги для воспроизведения ошибки:**

1. Смотрим расходы ярости для "Раскол брони"  в подсказке на панели и реальные при ударе.
2.  Вкидываем одно или несколько очков в один или оба таланта "Направленная ярость" и Прокол"
3. Видим, что стоимость для "Раскол брони" изменилась только в подсказке на панели действий. Реальный расход остался 15 единиц.

**Текущее обновление ядра:**
Logon 3 WowCircle Development, x1, PvE
Build 163 2017-07-25 11:59:12 +0400

**Comment by Riazarre** [comment]
Подтверждаю баг. 
Талант так же снижает стоимость http://wowroad.info/?spell=20243, снижает корректно, как визуально так и фактически.

**Comment by Gooldark** [comment]
http://wowwiki.wikia.com/wiki/Sunder_Armor?oldid=2456697

>     Puncture: Reduces the rage cost by up to 3. While useful, tanks tend to have plenty of rage anyways, and so this talent isn't as important as it might at first seem.
    Focused Rage: Reduces the rage cost by up to 3. Together with Improved Sunder Armor, this can make Sunder Armors very cheap and quick to apply. Again, not a key talent, but certainly useful, especially when both talents are used. 

Хотя в принципе и тултипа достаточно

**Comment by ForesterDev** [comment]
Исправлено, проверьте после обновления
