### ISSUE TITLE
[Задание] ID 13172 - Семена Хаоса

### ISSUE THREAD

**Issue by Rialzarre** [VirginTeam/WotlkCore#486]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Что работает не так?**

Мобов практически нет, за 1 полет убил только 30 штук.

**Как должно работать?**

https://youtu.be/FmJRsvaRo90 - квест выполнен за 1 полет.

**Текущее обновление ядра:**

Virgin Build 163

**Comment by GmAlleria** [comment]
Актуально в Build 268

**Comment by Climss** [comment]
Взяв грифон-скелета и облетев  карьер, нужные мобы отсутствуют для выполнения задания.
![image](https://user-images.githubusercontent.com/56660951/68042320-a22acb00-fce3-11e9-89a9-be5b1ea999fb.png)
Build 278 2019-11-01 17:15:07 +0400 Logon 3 x1 PvE

**Comment by vkeda** [comment]
Квест все еще не рабочий
Build 282 2019-12-18 12:39:11 +0400

**Comment by IAlex35** [comment]
Подтверждаю: "Взяв грифон-скелета и облетев карьер, нужные мобы отсутствуют для выполнения задания."
Квест все еще не рабочий
Build 285 2020-01-20 15:17:51 +0400

**Comment by ValeriiRomaniuk** [comment]
Всё ещё повторяется(

![WoWScrnShot_040420_013042](https://user-images.githubusercontent.com/27921560/78410067-009e0180-7614-11ea-82fe-868cc02363e7.jpg)
![WoWScrnShot_040420_013034](https://user-images.githubusercontent.com/27921560/78410070-01369800-7614-11ea-9ed9-d56f97287bb5.jpg)
![WoWScrnShot_040420_013038](https://user-images.githubusercontent.com/27921560/78410071-01cf2e80-7614-11ea-8305-817238a41bbb.jpg)

Build 287 2020-02-25 12:08:04 +0400
