### ISSUE TITLE
[Предмет] id 52676 - Ларь хранителя энергии

### ISSUE THREAD

**Issue by gmOverfire** [VirginTeam/WotlkCore#491]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Что работает не так?**

Не дается мешочек за прохождение Окулуса через систему случайных подземелий.

**Как должно работать?**

Когда вы выбираете рандом героик и это оказывается Окулус, в честе с Эрегоса (http://ru.wowhead.com/item=52676) появится мешочек с дополнительным лутом. Там могут быть рарные гемы, еще две эмблемы триумфа и шанс дропа маунта. 

**Текущее обновление ядра:**

Virgin Build 163

**Comment by ForesterDev** [comment]
Не актуально
