### ISSUE TITLE
[Задание] ID 13369 - Против воли рока

### ISSUE THREAD

**Issue by Razama1234** [VirginTeam/WotlkCore#50]
**Описание:**

Нет скриптов у задания [Против воли рока](http://wowroad.info/?quest=13369)

**Что работает не так?**

При использовании портала, созданного [Джайной](http://wowroad.info/?npc=32346), нас переносит в Оргриммар для аудиенции с военочальником Орды Траллом. [Джайна](http://wowroad.info/?npc=32364) тоже должна там присутствовать. Но нас сразу при встрече убивает Тралл. 

**Как должно работать?**

После телепортации у нас должна пройти встреча с Траллом, по истечении которой можно будет сдать квест.

**Шаги для воспроизведения ошибки:**

1. Взять квест.
2. Доложить Джайне о готовости.
3. Войти в портал.

**Текущее обновление ядра:**

Build 151 2017-04-03 15:25:08 +0400

**Comment by DarkCloud069** [comment]
https://www.youtube.com/watch?v=yXnAZZC6OTU вот видео с этого квеста

**Comment by Rorshah** [comment]
Да. Квест впечатляет.
Замануха типа - ткни портальчик сдай квестик, все будет ОК, не парься.
И ты оказываешься трупом в Огри, Дух ресается в Дуротаре.
Тот вариант когда проще воскреситься с дебафом и камнем уйти домой
не солоно хлебавши.

Зачет.

**Comment by Kodekc** [comment]
Задание не реализовано, скриптов нет, информации нет.

**Comment by Rorshah** [comment]
Есть же ссылки на видео, как должно работать.
Какая еще информация нужна ?

**Comment by Senatyan** [comment]
Проблема в том, что нету отдельной локации для этого кв. Поэтому идёт тупо ТП в Огри где конечно же Тралл убивает он думает ты как обычный игрок у него.

**Comment by Kodekc** [comment]
Разработчик, у нас не Кашпировский, чтоб по видео задания чинить. Для реализации задания нужна конкретная информация, которую можно получить только с старых данных официального проекта игры, такими данными мы пока не обладаем. Подобные задания, которых давно уже нет в игре, но они существуют могут долгое время находится не реализованными.

**Comment by Senatyan** [comment]
ТС попробуй тупо прийти в Огри поменяется фаза может поможет тебе сдать кв.

**Comment by Kodekc** [comment]
Фазирование само собой не поменяется

**Comment by Rorshah** [comment]
Ну сделать фазирование в огри наверное действительно сложно. Я в этом не разбираюсь.
Но хотя б портал сломать можно ?
Чтоб не тратить н-минут на маску. Некоторые не могут сутками сидеть в игре
и потеря тех минут бывает очень обидной.
Если уж не работает, то пусть перестанет работать на портале ?

**Comment by Senatyan** [comment]
Как они почили кто проверит?
https://www.aldoran.ru/page/%5Bwotlk%5D-ispravleniya-na-3.3.5_16-06-2015.html
Не сочтите за рекламу

**Comment by Senatyan** [comment]
Ещё информация http://mmoarch.wikia.com/wiki/The_Battle_for_the_Undercity человек собрал всю инфу об кв цепочке, координаты какие спеллы юзает нпц и прочая информация надеюсь разработчику поможет.

**Comment by Rorshah** [comment]
Я думаю, даже если портавать в пустую белую комнату, в которой будут Джайна
и Тралл с вопросиком - уже никто не зметит подмены. 
Главное чтоб в комнате еще был портал в настоящий штормград к королю рину.

**Comment by ForesterDev** [comment]
Проверяйте после обновления
