### ISSUE TITLE
[Заклинание] ID 49004 - Запах крови

### ISSUE THREAD

**Issue by v-sazhin** [VirginTeam/WotlkCore#500]
**Описание:**

http://wowroad.info/?spell=49004  - срабатывает от смены экипировки. 

**Что работает не так?**

После смены предметов, в которых меньше выносливости идет ложное срабатывание таланта, как в случае, если бы вы получили урон. 
С вероятностью 100%, хотя вкачан 1\3

**Как должно работать?**

Срабатывать не должен, в описание таланта четко прописано: после получения удара, парирования или уворота.

**Шаги для воспроизведения ошибки:**

Меняем экипировку с танка на дд, появляется бафф от таланта. 

**Текущее обновление ядра:**

Build 164, х1 Pve (не тестовый сервер), 20.09
21.09 воспроизвести баг не удалось. Возможно помог релог, возможно еще что-то

**Comment by Devinette** [comment]
Пожалуйста, оформите тему согласно правилам

**Comment by ForesterDev** [comment]
Не воспроизводится
