### ISSUE TITLE
[Игровая механика] - Урон питомцев/тотемов/взрывчатки в статистике на бг

### ISSUE THREAD

**Issue by kalipsa988** [VirginTeam/WotlkCore#501]
**Описание:**
Не засчитывает урон петов

**Что работает не так?**
а) Не засчитывает урон петов/тотемов/взрывчаток в статистику бг
https://www.youtube.com/watch?v=bv_V498jDUo&feature=youtu.be
б) Не засчитывает урон по петам/тотемам в статистику бг

**Как должно работать?**
а) Урон от петов/тотемов/взрывчатки и прочего должен заносится в статистику бг
б) Урон по петам/тотемам должен заносится в статистику бг

**Шаги для воспроизведения ошибки:**

1. Зайти на бг хантом/локом/шаманом
2. Натравить пета/тотем на противника и не бить его самому
3. Увидеть что урон от пета не заносится в статистику
4. Побить пета и увидеть, что урон не заносится

**Текущее обновление ядра:**

Последнее обновление ядра: Build 163 2017-07-25 11:59:12 +0400

**Comment by Kodekc** [comment]
Требуется доказательство, что это должно быть занесено в статистику

**Comment by kalipsa988** [comment]
на офе работает занесение урона питомецев в статистику, а механика бг не менялась с ванилы

**Comment by kalipsa988** [comment]
вот видео с офы https://www.youtube.com/watch?v=nnOstQWZp7c на нём видно занос урона пета в статистику, повторюсь, механика бг не менялась с ванилы

**Comment by kalipsa988** [comment]
Дополнение
Во вкладку почётные победы заносятся почётки за убийство любого лв.
Должны заноситься только почётки за убийство персов +-5 от имеющегося

**Comment by kalipsa988** [comment]
Пока закрою, после обновы проверю и если что открою
