### ISSUE TITLE
[Задание] ID 11080 - Излучение Реликвии 

### ISSUE THREAD

**Issue by odino4estvo** [VirginTeam/WotlkCore#509]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Необходимо взаимодействовать с реликвией для получения условия задания "Испытайте на себе излучение от апекситовой реликвии"

**Что работает не так?**

Используя один "Апекситовый осколок" на реликвии, при чем любой, она не активируется. Диалог с ними есть, но при выборе "Вставить осколок" реликвия не запускается в "работу". 

**Как должно работать?**

Все просто. Повторить 8 серий всплесков фейерверков 4 цветов, каждая последующая серия длиннее предыдущей на 1 всплеск, не ошибитесь в течение 8 серий и задание выполнено.
**Шаги для воспроизведения ошибки:**

1. Найти в Острогорье одну из этих реликвий.
2. Подойти к ней, активируя ее с помощью одного осколка.

**Текущее обновление ядра:**

Build 164 2017-09-21 
Прикладываю скрины. На втором у одного игрока такая же самая была проблема.
![wowscrnshot_092417_081536](https://user-images.githubusercontent.com/27158518/30779836-6b2970b2-a104-11e7-8236-f1df80623149.jpg)
![wowscrnshot_092417_082201](https://user-images.githubusercontent.com/27158518/30779837-6b2b5922-a104-11e7-8195-e16bf88cf58d.jpg)

**Comment by LothlorienElf** [comment]
Я смогла активировать реликвию друидом в форме птицы немного взлетев.
На ядре 163 выполняла квесты без проблем, взлетать не приходилось.

**Comment by gmKroshka** [comment]
Задание работает
