### ISSUE TITLE
[Задание] ID 10439 - Пространствус Всепоглощающий

### ISSUE THREAD

**Issue by Luchass** [VirginTeam/WotlkCore#51]
**Описание:**

http://ru.wowhead.com/quest=10439
http://wowroad.info/?quest=10439

**Что работает не так?**

Присутствуют не все скрипты задания. Капитан Саид (NPC Id 20985) идет один. 

**Как должно работать?**

https://www.youtube.com/watch?v=0lQMRoZae70

**Шаги для воспроизведения ошибки:**

1. Взять задание
2. Обратиться к Саиду
3. Саид идет один

**Текущее обновление ядра:**

PTR Build 20 2017-04-05 12:06:47 +0400

**Comment by odino4estvo** [comment]
Проблема так и остается, невозможно по сей день поговорить с Саидом. Проблеме столько лет, хотя-бы частично сделайте что-нибудь. Скриншот прикрепляю. Даже после убийства босса 1vs1, Саид неактивен. Баг на баге...
![1](https://user-images.githubusercontent.com/27158518/30538593-66fffb64-9c77-11e7-91ee-0f2d7aea69c4.jpg)
