### ISSUE TITLE
[Задание] ID 12236 Урсок, бог-медведь

### ISSUE THREAD

**Issue by alexo85** [VirginTeam/WotlkCore#513]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание**
Задание никак не запускается и нету Урсока
**Что работает не так?**
Не работает нпс Тур Яролап ID 27328
Фактический результат — тот, который вы наблюдаете**
Задание никак не сделать минуя этого нпс
**Как должно работать?**
https://www.youtube.com/watch?v=zYKRwLZ4N4g
Ожидаемый результат — то, чего вы ожидали при выполнении ваших действий. Процесс правильной работы

**Шаги для воспроизведения ошибки:**

1. Тур Яролап неактивный нпс

**Текущее обновление ядра:**
Build 164 2017-09-21 12:45:47 +0400
Можно посмотреть в игре, введите в чат команду .server info и скопировать строку начиная с Build с номером и датой. Не забывайте указывать, Live Server или PTR Server, где проводилось тестирование

**Comment by kotslik** [comment]
Добавлю от себя уточнение: задание работает, но с проблемами, схожими с http://wowroad.info/?quest=12270 , т.е. вероятно, нпс, участвующий в квесте, http://wowroad.info/?npc=27328 , забагивается через некоторое количество запусков. 28.10, при попытке выполнить этот квест, я застал его в форме медведя и без какой-либо возможности активации диалога и отсутствующим Урсоком на его месте, а на следующий день, после ребута квест был рабочий, т.е. Тур Яролап был в форме фурболга (как и должен), диалоги активировались, Урсок призвался, квест засчитало после его убийства.
