### ISSUE TITLE
[Игровая механика] Шанс промаха заклинаний и мили атак

### ISSUE THREAD

**Issue by Gooldark** [VirginTeam/WotlkCore#514]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

а) Шанс промаха ближнего боя
б) Шанс промаха заклинаний

**Что работает не так?**

Неверно рассчитывается шанс промаха для разнице в лвле 3 и более.

**Как должно работать?**

а) Шанс промаха у игроков зависит от навыка оружия и защиты, у мобов и петов навык защиты и оружия равен лвлу * 5, таким образом у моба 80 лвла по 400 очков.
Когда t – h <= 10(где t навык защиты атакуемого, h навык атаки атакующего), то действует формула:
19(при наличии оружия в левой руке) + 5 + 0.1(t – h)% - шанс промаха
Когда t – h > 10(где t навык защиты атакуемого, h навык атаки атакующего), то действует формула:
19(при наличии оружия в левой руке) + 6 + 0.4(t – h – 10)% - шанс промаха

То есть по боссам шанс промаха 8% с одним оружием и 27% с двумя.
Разумеется, мили спелы рассчитываются так, будто у игрока одно оружие.

б) Когда y - x <=2 (где х лвл атакующего, а y лвл атакуемого) формула должна быть такой:
4 - (y - x)% - шанс промаха
Когда y – x > 2 (где х лвл атакующего, а y лвл атакуемого) для пве формула должна быть такой:
6 - 11(y - x)% - шанс промаха
для пвп:
6 - 7(y - x)% - шанс промаха

Таким образом и был рассчитан реальный лвл боссов на офе(83), так как по ним шанс промаха 17%.
Для обеих механик применима аддитивная механика расовых умений и талантов, которые дают шанс промаха при наличии соответствующих эффектов у атакуемых целей.

**Доказательства**

http://wowwiki.wikia.com/wiki/Hit?oldid=2414568
http://wowwiki.wikia.com/wiki/Spell_hit?oldid=2414471

**Текущее обновление ядра:**

29.09.2017

**Comment by gmRial** [comment]
Исправлено, после обновления.
