### ISSUE TITLE
[Игровая механика] Ловушки охотника

### ISSUE THREAD

**Issue by Gooldark** [VirginTeam/WotlkCore#515]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

ID 60192 - Замораживающая стрела(http://wowroad.info/?spell=60192), 
ID 13795 - Обжигающая ловушка(http://wowroad.info/?spell=13795), 
ID 1499 - Замораживающая ловушка(http://wowroad.info/?spell=1499), 
ID 13809 - Ледяная ловушка(http://wowroad.info/?spell=13809), 
ID 13813 - Взрывная ловушка(http://wowroad.info/?spell=13813), 
ID 34600 - Змеиная ловушка(http://wowroad.info/?spell=34600)

**Что работает не так?**

а) Неверное количество очков невидимости, благодаря которым рассчитывается расстояние с которого можно увидеть стелс.

б) Отсутствует флайтайм на установку ловушек.

в) Неверная дальность срабатывания - 3 метра от центра ловушки к центру фрейма цели.

**Как должно работать?**

а) Ловушки должны быть видны если между центром модельки и центром ловушки менее 10 метров, при том условии что у игрока нет других модификаторов позволяющих видеть ловушки.

б) Должен быть флайтайм, в зависимости от дальности полета(у обычных трап небольшой в ~0.1 сек).

в) Дальность срабатывания ловушки от центра к центу должна быть 5 метров(как мили атака).

В клиенте стоит дальность 2, но наверное это не диаметр аое, а дальность срабатывания точечного спела, а спелы рассчитываются: дальность спела+ половины хитбоксов. 
То есть 3/2(хитбокс ловушки)+2(дальность спела)+3/2(хитбокс цели)= 5 метров радиус.

**Доказательства**

а) https://www.youtube.com/watch?v=4owolp7UdSo - 3:26 - лок увидел ловушки которые были поставлены заранее, на 3:30 лок отходит и одна ловушка успевает исчезнуть из зоны видимости, через пару секунд вторая, это значит что в том месте и была максимальная дальность обнаружения ловушек.
По хорошему лучше прийти на то место и повторить, то что там происходило, тогда можно будет точно знать максимальную дальность видимости по дефолту. На мой взгляд там метров 10 было.

б) https://www.youtube.com/watch?v=6UAFUzmv7Dw - 8:47 - на начало этой секунды хант кидает трапу, срабатывает уже на 49-ой. То же видео 7:07 - где-то в середине этой секунды устанавливается трапа к середине 8-ой секунды маг уже в трапе, что доказывает время готовности 1 сек.

в) https://www.youtube.com/watch?v=6UAFUzmv7Dw 9:37 - аномальная дальность срабатывания трапы, тут есть все 5 метров.

**Шаги для воспроизведения ошибки:**

б) 
1. Написать в чат /cobmbatlog
2. Использовать ID 60192 - Замораживающая стрела(http://wowroad.info/?spell=60192) на максимальную дистанцию.
3. Выйти из игры и получить запись в блокноте(папка Logs название WoWCombatLog) нечто подобное:
> 9/10 09:58:58.555  SPELL_CAST_SUCCESS,0x00000000003A01A9,"Апар",0x511,0x0000000000000000,nil,0x80000000,60192,"Замораживающая стрела",0x10
9/10 09:58:58.555  SPELL_CREATE,0x00000000003A01A9,"Апар",0x511,0xF11002F4EB09677A,"Замораживающая стрела I ",0x4111,60202,"Замораживающая стрела",0x10
9/10 09:58:59.624  SPELL_AURA_APPLIED,0x00000000003A01A9,"Апар",0x511,0x0000000000366281,"Shamaxa",0x548,60210,"Эффект замораживающей стрелы",0x10,DEBUFF

**Перенесено**

http://forum.wowcircle.com/showthread.php?t=390571&page=3
http://forum.wowcircle.com/showthread.php?t=595299
http://forum.wowcircle.com/showthread.php?t=556085

**Текущее обновление ядра:**

29.09.2017

**Comment by isafou** [comment]
актуально

**Comment by Defiz** [comment]
актуально жи

**Comment by Defiz** [comment]
Максимально актуальный и жизненно необходимый репорт (особенно пункт "в") 
Особенно когда такое происходит на всех боссах 
![скрин 1](https://user-images.githubusercontent.com/64416545/85908291-33bfed80-b81d-11ea-98a3-f022d528ef26.jpg)

**Comment by ForesterDev** [comment]
Исправлено
