### ISSUE TITLE
[Игровая механика] ID 1183 - Достижение Пиво года

### ISSUE THREAD

**Issue by kalipsa988** [VirginTeam/WotlkCore#517]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Пиво не приходит на почту.
**Что работает не так?**

Людям с ачивой http://ru.wowhead.com/achievement=2796, не приходит каждый месяц 1го числа на почту пиво

**Как должно работать?**

Если на персонаже есть ачива http://ru.wowhead.com/achievement=2796, то каждый месяц 1го числа на почту должно приходить сообщение с пивом данного месяца,
Пример сообщения;
От: Клуб "Пиво месяца"
Тема: Осеннее пиво
Приложения: http://ru.wowhead.com/item=37497

Здравствуйте, <имя>!

В этом месяце мы празднуем наступление осени! Нам кажется, что новое пиво месяца как нельзя лучше передает настроение этого сезона. Однако не верьте нам на слово – попробуйте сами!

Если вам понравились дегустационные образцы, вы всегда можете приобрести больше у наших распространителей.

Пейте на здоровье!

Клуб "Пиво месяца".

**Шаги для воспроизведения ошибки:**

1. Получить ачиву http://ru.wowhead.com/achievement=2796 
2. Ждать

**Текущее обновление ядра:**
Последнее обновление ядра: Build 164 2017-09-21 12:45:47 +0400

**Comment by Ewropa** [comment]
Приход пива не реализован на сервере, покупайте его в таверне у продавца пива

**Comment by kalipsa988** [comment]
так должно быть

**Comment by Ewropa** [comment]
Должно, но не приходит) пользуйтесь тем что есть, а так нужна реализация данного события

**Comment by kalipsa988** [comment]
что же за бред ты написал...

**Comment by kalipsa988** [comment]
я выше всё описал же, зачем писать факты, которые выше описаны?

**Comment by Ewropa** [comment]
еще раз напишу, данная механика не реализована на сервер, ждите когда это реализуется (а это не приоритетно), а пока пользуйтесь тем, что есть сейчас.

**Comment by ForesterDev** [comment]
Будет реализовано в следующем обновлении
