### ISSUE TITLE
[Рейд] Храм Ан'Киража (ID 15509 Принцесса Хухуран)

### ISSUE THREAD

**Issue by Plasmashield** [VirginTeam/WotlkCore#521]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Неверная работа способностей Исступление и Берсерк(не нашел их на вовроад). Крайне критичная проблема для всей 60 движухи на х1 !
А так же способность http://wowroad.info/?spell=26180 

**Что работает не так?**
Основная проблема:
При применение способностей Исступление и Берсерк, Хухуран плюет болтами раз в 1.5 сек. 
Так же, когда босс впадает в Берсерк, она по прежнему применяет способность Исступление.
Вторично:
Цели, подвергшиеся воздействию http://wowroad.info/?spell=26180 , не получают 3-4к урона от сил природы при диспеле этого яда.
Подвержена эффектам провокации(таунту).

**Как должно работать?**

При применение способностей Исступление и Берсерк, Хухуран должна плевать в 15 ближайших целей раз в 3 секунды, при этом скорость ее МИЛИ атаки удваивается(а не скорость плевков, как у нас).
Способности Исступление и Берсерк не могут применяться одновременно. До 30% хп босса периодически накладывается Исступление, а начиная с 30% Исступление более не накладывается, а заменяется на Берсерк.
Цели, подвергшиеся воздействию http://wowroad.info/?spell=26180 , должны получать 3-4к урона от сил природы при диспеле этого яда.
Иммун к таунту.

**Шаги для воспроизведения ошибки:**

1. Шаг один
2. Шаг два
3. Шаг три

**Текущее обновление ядра:**

Build 164 2017-09-21 12:45:47 +0400 Live Server

**Comment by Santaria94** [comment]
Ссылки на способности

[http://ru.wowhead.com/spell=26052](url) - **Ядовитый удар**

[http://ru.wowhead.com/spell=26068[](url) - **Берсерк**
_Apply Aura: Periodically trigger spell **Ядовитый удар**. Интервал: 2 секунды_

[http://ru.wowhead.com/spell=26051](url) - **Исступление**
_Apply Aura: Periodically trigger spell **Ядовитый удар**. Интервал: 4 секунды_

Возможно интервалы **Ядовитого удара** работают корректно, однако из-за одновременно активных **Берсерка** и **Исступления** способность триггерится параллельно от того и от другого.

Одновременно активные **Берсерк** и **Исступление** возможно какая-то глобальная ошибка в механике, т.к. **Хромаггус** [http://ru.wowhead.com/npc=14020](url), например, также впадает в берсу и исступление одновременно.

**Comment by Plasmashield** [comment]
Я очень сомневаюсь, что на вовхеде актуальная для лича инфа по скилам. В гайде 2006 года было сказано про "Berserk: At 30%, Huhuran doubles her attack speed and releases Poison Bolt Volleys every 3 seconds."

**Comment by Plasmashield** [comment]
Просто оставлю это тут
https://github.com/scriptdev2/scriptdev2/commit/172f9d9a15de41af0feb4daaaffa54eacc1bb08a

**Comment by Riazarre** [comment]
> Одновременно активные Берсерк и Исступление возможно какая-то глобальная ошибка в механике, т.к. Хромаггус, например, также впадает в берсу и исступление одновременно.

Проблема скорее в коде этих существ.
Судя по скрипту Хухуран https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/Kalimdor/TempleOfAhnQiraj/boss_huhuran.cpp нужно просто добавить проверку на Берсерк в условие Исступления, тогда она не должна использовать Исступление в Берсерке.
```            //Frenzy_Timer
            if (!Frenzy && Frenzy_Timer <= diff)
            {
				if (!Berserk)
				{
					DoCast(me, SPELL_FRENZY);
					Talk(EMOTE_FRENZY_KILL);
					Frenzy = true;
					PoisonBolt_Timer = 3000;
					Frenzy_Timer = urand(25000, 35000);
				}
                
            } else Frenzy_Timer -= diff;
```
Все остальное в принципе работает корректно, на собранном ядре Тринити Плевок идет каждые 7-10 секунд, Ядовитый удар спамится только во время действия Берсерка / Исступления.
Про иммун к таунту - есть достоверная информация?

**Comment by Plasmashield** [comment]
Про иммун к таунту сказано на воввики и аналогичном комменте на вовголове(2006г вроде)
Есть еще видео от лица танка, где отлично видна их ротация(агро срывалось только набором трита, таунт не использовался вообще)
https://youtu.be/jOF2JenCbl8

**Comment by Oleksiymir** [comment]
Сделайте уже Храм Ан Кираж нормальный, пожалуйста. Из-за Хухуран и братьев его пройти сейчас не имеется возможности! Вам же все написали. Обратите внимание и сделайте уже какие нибудь шаги по этому вопросу.

**Comment by sega693** [comment]
в чем сложность воткнуть вот это?
`if (!Berserk)`

**Comment by Oleksiymir** [comment]
Эй! Почините Хухуран и братьев! Зачем мы вдонили в т3 и играем на сервере, если вы не хотите чинить для ряда игроков проблему? Ан Кираж ведь один из топовых данжей на ваниле был. Вам же все скинули и обьяснили. Почините, пожалуйста.

**Comment by ForesterDev** [comment]
Исправлено, будет применено в обновлении
