### ISSUE TITLE
[Задание] ID 12919 - Месть короля Бурь

### ISSUE THREAD

**Issue by Razama1234** [VirginTeam/WotlkCore#53]
**Описание:**

Нерабочий квест

**Что работает не так?**

Нельзя сесть на гиганта и вследствие квест предоставляется трудновыполнимым. На нас накладывается [аура](http://ru.wowhead.com/spell=55430), которая снимается через продолжительное время или смертью игрока. При этом гигант клонирует себя. При попытке сесть на нижнюю копию происходит зависание игрока (релог решает проблему), при попытке оседлания второго гиганта ничего не происходит.

**Как должно работать?**

После взятия квеста мы садимся на гиганта, у нас появляется панель управления, и с помощью него убиваем мобов.

**Шаги для воспроизведения ошибки:**

1. Взять квест.
2. Доложить о готовности гиганту.

**Текущее обновление ядра:**

Build 151 2017-04-03 15:25:08 +0400

**Comment by Immoretall** [comment]
![wowscrnshot_052917_023353](https://cloud.githubusercontent.com/assets/29028790/26533054/fb92be84-441a-11e7-9702-a3b784214646.jpg)
![wowscrnshot_052917_023407](https://cloud.githubusercontent.com/assets/29028790/26533053/fb925f7a-441a-11e7-9389-900e4c6a2f0e.jpg)
![wowscrnshot_052917_023411](https://cloud.githubusercontent.com/assets/29028790/26533055/fb96f13e-441a-11e7-98bd-574f626db5ef.jpg)
![wowscrnshot_052917_023426](https://cloud.githubusercontent.com/assets/29028790/26533057/fb97ce60-441a-11e7-8a44-db88940ed2fd.jpg)
![wowscrnshot_052917_023507](https://cloud.githubusercontent.com/assets/29028790/26533052/fb91b2b4-441a-11e7-884a-15e14b080da7.jpg)
![wowscrnshot_052917_023521](https://cloud.githubusercontent.com/assets/29028790/26533056/fb97370c-441a-11e7-9ca4-edb7f4acba7a.jpg)
![wowscrnshot_052817_192126](https://cloud.githubusercontent.com/assets/29028790/26533058/fbaa6b06-441a-11e7-9c58-411b3e2cc9e2.jpg)
![wowscrnshot_052917_023327](https://cloud.githubusercontent.com/assets/29028790/26533059/fbada9c4-441a-11e7-9785-9ea54e1f1680.jpg)
Так это выглядит сейчас.

**Comment by MiceRus** [comment]
Сейчас не работает. Сесть - вроде садишься, но из клетки он не выходит и ни с кем не дерется.
И вообще, вместо перса на плечи ему садится он сам :)

**Comment by gmKroshka** [comment]
Будет исправлено после обновления
