### ISSUE TITLE
[Рейд] Ульдуар - кд

### ISSUE THREAD

**Issue by sega693** [VirginTeam/WotlkCore#532]
Описание:
Кд на рейд

Что работает не так?
Дается кд при появлении 1 босса http://ru.wowhead.com/npc=33113 . После убийства двух Ульдуарский великан перед ним. http://db.logon3.com/?npc=34105 в 25, http://db.logon3.com/?npc=33237 в 10 http://ru.wowhead.com/npc=33237 

Как должно работать?
Должно даваться кд только после убийства босса

Шаги для воспроизведения ошибки:
Убить великанов

Текущее обновление ядра:
Build 165 2017-10-05 16:02:40 +0400 Live Server

**Comment by Kodekc** [comment]
Пока сделано специально не близзлайк, чтоб избежать ошибок с кд, если сервер крашнется или уйдёт в перезагрузку. Как добудем с оффы более корректные методы, реализуем иначе.
