### ISSUE TITLE
[Задание] ID 12980 - Секрет доспехов

### ISSUE THREAD

**Issue by dreaddy1488** [VirginTeam/WotlkCore#540]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Для выполнения задания необходимо прилететь в Мастерскую Мимира и поговорить с неким рабочим Током, который должен осмотреть доспех.

**Что работает не так?**

Однако данного рабочего в Мастерской нет, на его месте стоит враждебный НПС. Соответственно, выполнить данный квест не представляется возможным.

**Как должно работать?**

Видимо, нужно поговорить с дружественным НПСом и вернуться к тому, кто давал квест.

**Шаги для воспроизведения ошибки:**

1. В Грозовой Гряде выполняете преквест Доспехи тьмы.
2. Берете данный квест в локации Снежные равнины.
3. Летите в Мастерскую Мимира, которая находится по другую сторону горы.

**Текущее обновление ядра:**

Build 165 2017-10-05 16:02:40 +0400

**Comment by Riazarre** [comment]
Проблема осталась, нпц 30190 висит в воздухе.

**Comment by ForesterDev** [comment]
Будет исправлено в обновлении
