### ISSUE TITLE
[Рейд] Храм Ан'Киража (ID 15299 Нечистотон)

### ISSUE THREAD

**Issue by sega693** [VirginTeam/WotlkCore#544]
Описание:
http://db.logon3.com/?npc=15299 
http://db.logon3.com/?npc=15667

Что работает не так?
При убийстве капель, хп босса может уйти "в минус", и его тело появляется без лута.

Подобным образом (только еще хуже) раньше багался босс в АМК.

Как должно работать?
Должен быть лут.
> Висидус уязвим к холоду, поэтому очень важно, чтобы во время боя по нему шло как можно БОЛЬШЕ (именно кол-во) фрост атак. У Висидус есть несколько состояний, в которые он переходит после определённого кол-ва фрост атак, все состояния отображаются эмоутами. Главная цель рейда довести Всисидуса до состояния полной заморозки, разбить его и уничтожить пузыри, которые спавнятся после расщепления. Чем больше пузерей убьёте - тем меньше хитов останется у Висидуса. 
> "Viscidus explodes." - Когда Висидус взрывается, он разбивается на 20 маленьких Globs of Viscidus, которые распологаются вокруг Висидуса на определённом расстоянии. Эти "шарики" начнут двигаться по наравления к боссу. Сначала медленно, потом всё быстрее и быстрее. 
> За каждый убитый шар, хиты Висидуса уменьшаются на 5%. 

Шаги для воспроизведения ошибки:
1. оставить боссу мало хп
2. Бить фрост атаками
3. после заморозки бить мили
4. убить все Капли

Текущее обновление ядра:
Build 165 2017-10-05 16:02:40 +0400 Live Server

**Comment by Plasmashield** [comment]
Вообще, у нас капель мало, разлетаются они не так, как должны и двигаются очень медленно . И почему то двигаются они не к боссу, их можно просто заагрить и тащит куда угодно.
