### ISSUE TITLE
[Рейд] Руины Ан'Киража (ID 15369 Аямисса Охотница)

### ISSUE THREAD

**Issue by sega693** [VirginTeam/WotlkCore#546]
Описание:
http://ru.wowhead.com/npc=15369#comments
http://db.logon3.com/?npc=15555 и http://db.logon3.com/?spell=25721

Что работает не так?
При чардже вара (возможно и от других эффектов) в Личинку http://db.logon3.com/?npc=15555 она мгновенно использует Кормление http://db.logon3.com?spell=25721 на игрока на алтаре, находясь на любом расстоянии.

Как должно работать?
Должна продолжать обычное движение

Шаги для воспроизведения ошибки:
1. спулить босса
2. дождаться личинку
3. сделать чардж

Текущее обновление ядра:
Build 165 2017-10-05 16:02:40 +0400 Live Server

**Comment by Kodekc** [comment]
- Проведена корректировка урона
(Будет применено в ближайшем обновлении)
