### ISSUE TITLE
[NPC] ID 14354 - Пузиллин

### ISSUE THREAD

**Issue by ivgas** [VirginTeam/WotlkCore#548]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Механика NPC - Pusillin (Dire Maul - East) http://wowroad.info/?npc=14354

**Что работает не так?**

Последний этап ивента Pusillin Chase не работает - NPC возвращается в начало инстанса и с ним нельзя взаимодействовать.

**Как должно работать?**

NPC Pusillin должен при первом разговоре начать ивент - Pusillin Chase, который в итоге делал бы его враждебным и позволял убить. С него падает важный лут - Crescent Key, необходимый для открытия дверей в DM.

**Шаги для воспроизведения ошибки:**

1. Зайти в подземелье Dire Maul - East
2. Поговорить с NPC Pusillin http://wowroad.info/?npc=14354 в первый раз и 4 последующих раза
3. Дойти до места, в котором он должен быть после окончания ивента (NPC там нет, он вернется в начало инстанса)
**Текущее обновление ядра:**

Build 167 2017-10-11 10:49:14 +0400
Live

**Comment by Devinette** [comment]
Пожалуйста, исправьте ссылки на ссылки из http://wowroad.info/

**Comment by ivgas** [comment]
Обновил.

**Comment by Kodekc** [comment]
Исправлено. Изменения будут применены в ближайшем обновлении
