### ISSUE TITLE
Баг на БГ (БЕРЕГ) by Kikimor

### ISSUE THREAD

**Issue by Kikimor1** [VirginTeam/WotlkCore#549]
Пушка которая находится на воротах, к примеру на красных, синих воротах. 
Пушкой можно двигаться, стрелять
![wowscrnshot_101117_175404](https://user-images.githubusercontent.com/32711763/31450297-c1fc233e-aeb1-11e7-92b3-f6e2985d48ab.jpg)
![wowscrnshot_101117_175506](https://user-images.githubusercontent.com/32711763/31450299-c2188f10-aeb1-11e7-8d2a-d7a208cb8b2a.jpg)
# FIXPLEASE

**Comment by Devinette** [comment]
Оформите репорт согласно правилам, пожалуйста
