### ISSUE TITLE
[Игровая механика] Свингтайм автовыстрелов охотника

### ISSUE THREAD

**Issue by Gooldark** [VirginTeam/WotlkCore#550]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Автовыстрелы охотника

**Что работает не так?**

Автовыстрелы охотника не имеют общего свинг тайма с автоатакой.

**Как должно работать?**

Когда охотник делает автовыстрел должен запускаться свинг тайм и на мили атаку(время рассчитывается как для оружия дальнего боя), и наоборот после совершения атаки в ближнем бою должен запускаться свинг тайм на автовыстрел(в данном случае время должно рассчитываться как для оружия ближнего боя)

**Шаги для воспроизведения ошибки:**

1. Подойти близко к манекену
2. Сделать автовыстрел и быстро подойти в упор
3. Увидеть автоатаку сразу после выстрела
4. Сделать автоатаку и бысто отойти на расстояние выстрела
5. Увидеть автоатаку и автовыстрел без задержки

**Доказательства**

Тема с л1 http://forum.wowcircle.com/showthread.php?t=678062

Видео https://www.youtube.com/watch?v=CaNJOEWoOWQ&feature=youtu.be - 2:17 и далее после выстрела, когда кабанчик подбегает в упор, хант какое-то время не может его бить.

**Текущее обновление ядра:**

11.10.2017

**Comment by kalipsa988** [comment]
исправлено
