### ISSUE TITLE
[Подземелье] Нексус (ID 26769 Командир Пивобород)

### ISSUE THREAD

**Issue by Rorzak** [VirginTeam/WotlkCore#563]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Отсутствует Босс "Командир Пивобород" в Нексусе на героическом уровне сложности, за Орду (за Альянс не играл не знаю)

http://ru.wowhead.com/npc=26796

**Что работает не так?**

Босс не появляется

**Как должно работать?**

На героике должен быть босс в Зале покоя

**Шаги для воспроизведения ошибки:**

1. Поставить босса в Зале покоя, что в Нексусе на героическом уровне сложности

**Текущее обновление ядра:**

Последнее обновление ядра: Build 167 2017-10-11 10:49:14 +0400

**Comment by ForesterDev** [comment]
Исправлено, будет применено в обновлении
