### ISSUE TITLE
[Рейд] Плато Солнечного Колодца (ID 24850 24892 Калесгос, Сатроварр Осквернитель)

### ISSUE THREAD

**Issue by sega693** [VirginTeam/WotlkCore#564]
Описание:
http://db.logon3.com/?npc=24850 Калесгос 
http://db.logon3.com/?npc=24892#abilities Сатроварр Осквернитель
http://db.logon3.com/?spell=45032 Проклятие безграничной агонии

Что работает не так?
В бою с боссом Калесгос в портале демон Сатроварр Осквернитель начинает спамить очень много Проклятие безграничной агонии. У всего рейда падает фпс до нуля, затем вылетает ошибка о нехватке памяти.
http://puu.sh/y3wK5/74fd2055e2.jpg
http://puu.sh/y3yhp/b02b4c5c51.png

Как должно работать?
Не должен зависать клиент вов/ Не так часто спамится Проклятие.

Шаги для воспроизведения ошибки:
1. спулить босса
2. дождаться каста http://db.logon3.com/?spell=45032

Текущее обновление ядра:
Build 167 2017-10-11 10:49:14 +0400 Live Server

**Comment by olegklim1991** [comment]
2 года хожу в санвел на фул(правда там работает пару боссов криво),но такой ошибки не разу не было,перенеси игру на другой диск,а то с системного не гуд играть

**Comment by sega693** [comment]
Особенно когда системный диск - ssd. Окда. С компом сам как-нибудь разберусь, спасибо.
Еще парочка скринов. И повторюсь, такая фигня была у ВСЕГО рейда (20чел). Если его быстро зергануть проблемы вероятно не будет, но это нефига не нормально. Рейд довольно слабый был в плане дпс да, до половины хп босса такого хаоса не было.
http://puu.sh/y57cH/c02b45e822.jpg 
http://puu.sh/y57do/da32ec9e04.jpg 
http://puu.sh/y57f0/2d93e4dff5.jpg

**Comment by sega693** [comment]
А когда вот это было применено? 
> Плато солнечного колодца:
> Полностью переписан скрипт босса Калесгос
Втроем проверили сегодня. Этот дебаф так же быстро между игроками летает. Но когда мало народу не зависает клиент.

**Comment by sega693** [comment]
http://puu.sh/ypqsS/0aa264725b.jpg Еще немножко пентаграмм.
Да в 9 человек почти не провисает на хорошем железе. Но многие жаловались на сильные лаги. В 10 уже заметней. В тот раз было около 20, когда критом вылетало.

**Comment by Santaria94** [comment]
Актуально

**Comment by olegklim1991** [comment]
актуально ,ги 70 не может убить 1 боcса в плато

**Comment by SergeyVyach** [comment]
Просим обратить внимание на эту проблему и по возможности ее пофиксить

**Comment by ForesterDev** [comment]
Проверьте после обновления сервера

**Comment by olegklim1991** [comment]
сам спел может и не так вешается,но визуальный эффект остался,все равно фпс проседает капец как

**Comment by SergeyVyach** [comment]
Подтверждаю, на боссе, когда внутри портала демон кастует, сильно проседает фпс, что наблюдается до завершения боя.

**Comment by olegklim1991** [comment]
зачем закрывать тему если вы её не починили

**Comment by SergeyVyach** [comment]
Почините пожалуйста плато, мы о многом не просим. Единственный рейд, куда мы с гильдией попасть не можем.
