### ISSUE TITLE
[Задание] ID 9164 Пленники Смертхольма

### ISSUE THREAD

**Issue by assdawr** [VirginTeam/WotlkCore#568]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Следопыт Ведоран (http://wowroad.info/?quest=9164) ведет себя неправильно

**Что работает не так?**

Аптекарь Инит (http://wowroad.info/?npc=16208), Ученик Варнис (http://wowroad.info/?npc=16206)
лежат в бессознательном состоянии, через диалог их можно вернуть в сознание, после чего их спасение засчитывается.
Следопыт Ведоран (http://wowroad.info/?quest=9164) в свою очередь ведет себя агрессивно, бьет ближайшего к нему моба- Боргот Кровопускатель (http://wowroad.info/?npc=16247), хотя возможно Боргот нападает первым, и благополучно умирает, после чего с ним нельзя взаимодействовать. К тому же, если после смерти Ведорана ждать его респауна (по информации из http://wowroad.info/?quest=9164 респ 10 минут) на том же месте где его убили, то ресаться он не будет. Ждал реса возле входа в Смертхольм (координаты 36.2-70.5), в этом случае ресается так как и положено- через 10 минут после смерти. Если успеть спасти Ведорана, то квестовый диалог проходит не до конца, он просто убегает и его спасение не засчитывается (в случае если Ведоран находится в бою), если Ведоран не умирает до того как выйдет из боя, то он "возвращается" на стол и квестовой диалог проходит до конца, его спасение засчитывается. 
**Как должно работать?**

Ведоран должен вести себя так же как и остальные "бессознательные"
**Шаги для воспроизведения ошибки:**
0. Сделать первый квест в цепочке: "Приводящее в сознание зелье" (http://wowroad.info/?quest=9877)
1. Взять квест "Пленники Смертхольма" у Аптекарь Рензитен (http://wowroad.info/?npc=16198)
2. Подойти к Аптекарю  Инит (http://wowroad.info/?npc=16208), убить стоящего рядом моба Джурион Обманщик, поговорить с аптекарем. Аптекарь убегает и ее спасение засчитывается в квест.
3. повторить п.2 для Ученик Варнис (http://wowroad.info/?npc=16206)
4. Далее возможны 3 варианта: 
   4а. Приходим к Следопыт Ведоран (http://wowroad.info/?quest=9164), видим его хладное тело. Ждем 8 минут, убиваем всех мобов в зале, далее бежим ко входу в Смертхольм и ждем оставшиеся 2 минуты, опять бежим к Ведорану, разговариваем с ним, спасение засчитывается.
  4б. Приходим к Следопыт Ведоран (http://wowroad.info/?quest=9164), видим что он сражается. Спасаем Ведорана, заводим диалог до того как он вышел из боя. Диалог проходит не до конца, Ведоран убегает на выход, исчезает в неизвестном направлении, где его убивают. Спасение не засчитывается.
  4в. Приходим к Следопыт Ведоран (http://wowroad.info/?quest=9164), видим что он сражается. Спасаем Ведорана, заводим диалог после того того как он вышел из боя. Диалог проходит, квест засчитывается.

**Текущее обновление ядра:**

Build 167 2017-10-11 10:49:14 +0400 live сервер

**Comment by Santaria94** [comment]
Актуально

**Comment by gmRial** [comment]
#734
