### ISSUE TITLE
[Задание] id 13069 - Пристрели их

### ISSUE THREAD

**Issue by Rialzarre** [VirginTeam/WotlkCore#569]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Задание не работает.

**Что работает не так?**

НПЦ 30330 спавнятся только в одной точке.
Выстрелы с пушки не проивзодят никакого эффекта, НПЦ не убиваются.
Визуальный баг: НПЦ перемещаются по воздуху так, будто по земле (анимация ходьбы).

**Как должно работать?**

Стреляем, убиваем.

**Текущее обновление ядра:**

PTR Build 42

**Comment by MiceRus** [comment]
Не понятно - квест в стадии исправления или нет?

**Comment by gmOverfire** [comment]
Все репорты с метками ожидают фиксов.
Как только репорт будет исправлен, мы проставим соответствующую метку.
