### ISSUE TITLE
[Подземелье] Темный Лабиринт - (ID 18732 Великий мастер Ворпил)

### ISSUE THREAD

**Issue by gmRial** [VirginTeam/WotlkCore#57]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Некорректная работа механик босса.

**Что работает не так?**

1. Врата Бездны http://ru.wowhead.com/npc=19224 появляются сразу все (5 шт), агрятся на игрока, прибегают к нему и бьют его.
2. Путник Бездны http://ru.wowhead.com/npc=19226 быстро бежит к боссу.
3. Перед использованием http://ru.wowhead.com/spell=39363 босс телепортирует всех игроков на постамент, затем практически сразу же телепортирует их в другое место - коридор за ним/либо центр комнаты перед ним.
```
.gps точки в коридоре: X: -150.282013 Y: -264.303009 Z: 17.086020
.gps точки в комнате:  X: -351.381989 Y: -264.303009 Z: 12.687359 
```

**Как должно работать?**

1. Врата Бездны должны стоять там, где заспавнились, не должны агриться на игроков и бить их..
2. Путник Бездны должен медленно идти к боссу.
3. Босс должен телепортировать игроков только в одну точку:
`X: -252.882004 Y: -264.303009 Z: 17.086359`
Видео: https://youtu.be/1zn538fRQ98

**Текущее обновление ядра:**

PTR: Build 20 2017-04-05 12:06:47 +0400

**Comment by MiceRus** [comment]
Так чего с боссом-то? Ведь так и не пашет нормально

**Comment by ForesterDev** [comment]
Будет исправлено после обновления

**Comment by ForesterDev** [comment]
Исправлено
