### ISSUE TITLE
[Задание] ID 12362 - Кулек конфет

### ISSUE THREAD

**Issue by Kubanez** [VirginTeam/WotlkCore#570]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Не начисляется опыт за квесты ивента

**Что работает не так?**

При выполнении заданий "Кулек конфет" (http://ru.wowhead.com/quest=12362 и аналогичные по прочим тавернам) не начисляется опыт

**Как должно работать?**

При выполнении заданий "Кулек конфет" начисляется опыт

**Шаги для воспроизведения ошибки:**

1. Найти кулек конфет (http://ru.wowhead.com/object=190065)
2. Выполнить квест (http://ru.wowhead.com/quest=12362)
3. Получить предмет "пригоршня конфет" (http://ru.wowhead.com/item=37586), не получить опыт

**Текущее обновление ядра:**
Logon3 WowCircle Development
Build 168 2017-10-23 17:03:00 +04:00

**Comment by Devinette** [comment]
Вставьте ссылки из вовхед

**Comment by sega693** [comment]
Один раз дается за каждый кулек же. В плане если ты через год собираешь - экспы нет. Как и костры всякие.

**Comment by Kubanez** [comment]
Ну так проблема как раз в том, что не собирал я их :(
