### ISSUE TITLE
[NPC] ID 10558 - Певчий форрестен

### ISSUE THREAD

**Issue by anmaxien** [VirginTeam/WotlkCore#571]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**
Респавн рарного НПЦ Певчий Форрестен

**Что работает не так?**

За сегодняшний день пронесли разными чарами Стратхольм 96 раз. Ни 1 раза этот моб, с которого падает флейта и т.05 сапоги необходимые для квестовой цепочки не появился в инсте. ГМы конечно могут рассказывать что моб рарный и спавнится не всегда, но он не спавнится вообще.

**Как должно работать?**
Для справки, почитайте вовхед, как на офе он спавнится, с каким примерным % и сравните с нашим сервером

**Шаги для воспроизведения ошибки:**

Проверьте спавнится ли он вообще и какой у него %

**Comment by Devinette** [comment]
ставьте ссылки из вовхед

**Comment by zyxellgit** [comment]
http://ru.wowhead.com/npc=10558 Певчий Форрестен
http://ru.wowhead.com/item=13379 Флейта
1 коммент "Hearthsinger Forresten в Стратхолме. Босс не рарный, но он имеет несколько возможных точек респауна. "  http://ru.wowhead.com/item=13379#comments
 (шанс дропа ~19%)

**Comment by anmaxien** [comment]
При чем тут несколько точек респавна? Мы 80-ками выносил фулл страт больше 20 раз за день. Этот НПЦ ни разу вообще нигде не спавнится. Все мобы зачищены -- инст пустой. Его нигде нет. И так уже довольно долго дела обстоят

**Comment by anmaxien** [comment]
Проблема по прежнему актуальна. Без этого НПЦ невозможно собрать т0.5 на мага

**Comment by anmaxien** [comment]
Сегодня были в Страте, НПЦ присутствует. По идее тему можно закрывать, все ведь работает.

**Comment by Kodekc** [comment]
У него два места появления, скорей всего вы смотрели только в одному и подумали, что его не существует в мире совсем. Работает правильно, репорт закрыт.

**Comment by Santaria** [comment]
Нужно переоткрыть репорт, проблема актуальна. NPC должен всегда появляться в подземелье, но в разных точках. Чуть выше уже кидали комментарий с потверждением.

Сейчас он похоже входит в группу случайных нпц, которые заселяются в подземельях. Если повезло, то стоит всегда до следующего рестарта, если не повезло - игроки его не видят вообще.
https://github.com/VirginTeam/WotlkCore/issues/1019

**Comment by ForesterDev** [comment]
Исправлено
