### ISSUE TITLE
[Рейд] Ульдуар 25 (Огненный Левиафан)

### ISSUE THREAD

**Issue by ghost** [VirginTeam/WotlkCore#572]
**Описание:**

Подземелье Ульдуар 25 . Босс- огненный левиафан. после убийства пушек( на ачив Оборонная пушка 25 )  рейд вайпнулся , получилась следующая картина : Утюг стоит в стане , на нём дебаф "оглушение" который обновляется каждые 1.5 секунды, перед боссом осталась последняя машина - Разрушитель , у неё 13% хп и не отнимается .

**Что работает не так?**
 После вайпа всего рейда,висит бой на инсте, инст не ресается . 

Фактический результат — тот, который вы наблюдаете
 Дальше пройти невозможно.

**Как должно работать?**
умер рейд - машины реснулись - бой на инсте пропал.

**Текущее обновление ядра:**
![wowscrnshot_102917_164701](https://user-images.githubusercontent.com/33198755/32144389-0aa6120a-bcc9-11e7-8032-c1cb01a1ec59.jpg)

![wowscrnshot_102917_155010](https://user-images.githubusercontent.com/33198755/32144391-1cd575ec-bcc9-11e7-8b23-7caab715f90a.jpg)
![wowscrnshot_102917_155012](https://user-images.githubusercontent.com/33198755/32144392-1cf5f7ae-bcc9-11e7-8ff6-326a35e4ac21.jpg)

**Comment by kalipsa988** [comment]
![wowscrnshot_110617_171555](https://user-images.githubusercontent.com/29568428/32445512-fcc6511e-c316-11e7-8f24-ac7958d115dc.jpg)
При убийстве 2х пушек в 25ке багается отключение системы и босс в манекена превращается

**Comment by kalipsa988** [comment]
если есть свободный гм, то могу прям щас помочь

**Comment by Kodekc** [comment]
Проблема связана с 25-ткой, запрыгиваешь на босса, убиваешь 2 пушки, скрипт босса зависает, таймер постоянно обновляется

**Comment by ForesterDev** [comment]
Исправлено. Будет применено в обновлении

**Comment by gmRial** [comment]
Уничтожение пушек не вызывает перегрузку во всех сложностях, требуется доработка.

**Comment by kalipsa988** [comment]
не исправлено

**Comment by Kodekc** [comment]
Что конкретно не исправлено? Проблемы описанные в репорте сохранились в полном объёме?

**Comment by kalipsa988** [comment]
надо на тест идти и смотреть, столько обнов прошло уже, мб новое что-то появилось

**Comment by ForesterDev** [comment]
Нет фидбека - репорт закрыт
