### ISSUE TITLE
[Игровая механика] Таунты и тотемы

### ISSUE THREAD

**Issue by Gooldark** [VirginTeam/WotlkCore#573]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

ID 56222 - Темная власть(http://wowroad.info/?spell=56222)
ID 20736 - Отвлекающий выстрел(http://wowroad.info/?spell=20736)
ID 6795 - Рык(http://wowroad.info/?spell=6795)
ID 62124 - Длань возмездия(http://wowroad.info/?spell=62124)
ID 355 - Провокация(http://wowroad.info/?spell=355)

**Что работает не так?**

Все тотемы не имеют иммуна к таунтам - (6) Apply Aura #11: Taunt

**Как должно работать?**

Тотемы должны быть иммуны к таунтам

Суть репорта заключается в возможности уничтожать граудинг(http://wowroad.info/?spell=8177) таунтом, на данный момент граудинг исчезает, если использовать таунт, хотя исчезать не должен при том что перенаправление таунта должно происходить.

У грипа(http://wowroad.info/?spell=49576) тоже должен быть иммун, однако он должен уничтожать граудинг, и тут скорее всего такая ситуация вызвана тем, что таунт часть Хватки смерти

**Доказательства**

http://www.warcraftmovies.com/movieview.php?id=137567 -15:11 граудинг словил таунт, но при этом не исчез, так как на нем выскочил иммун, а не на роге.
http://www.fotohost.by/image/28mO

http://www.warcraftmovies.com/movieview.php?id=137567 - 4:58 - тоже виден иммун грипа, но граудинг исчезает.

**Текущее обновление ядра:**

29.10.2017

**Comment by Gooldark** [comment]
В принципе это лишь часть репорта https://github.com/VirginTeam/VirginCore/issues/209
тотемы должны быть имунны к любым бафам/дебафам.

**Comment by gmOverfire** [comment]
Будет исправлено после обновления.
