### ISSUE TITLE
[NPC] ID 18450 Шиенорский колдун

### ISSUE THREAD

**Issue by deexeq** [VirginTeam/WotlkCore#576]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Малое заселение NPC Шиенорский колдун (http://wowroad.info/?npc=18450)

**Что работает не так?**

Малое заселение данного NPC.

**Как должно работать?**

Должно быть больше

**Текущее обновление ядра:**

Build 168 2017-10-23 17:03:00 +0400

**Comment by sega693** [comment]
по вовхеду 14 у нас 3 всего..
https://ru.wowhead.com/npc=18450/шиенорский-колдун
Build 217 2018-08-09 16:14:07 +0400

**Comment by Kodekc** [comment]
[Существа] ID 18450 - Шиенорский колдун
* Перезаселены. Было = 3 Стало = 12

Изменения будут применены в ближайшем обновлении
