### ISSUE TITLE
[Подземелье] Аукенайские гробницы (ID 18371 Ширрак Страж Мертвых)

### ISSUE THREAD

**Issue by gmRial** [VirginTeam/WotlkCore#58]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Неверная работа заклинания босса.

**Что работает не так?**

Ширрак вешает 4 стака дебафф http://ru.wowhead.com/spell=32264 на всем радиусе действия его ауры.

**Как должно работать?**

Стаки должны прибавляться/отниматься по мере приближения/удаления к боссу.
Судя по англ. комментариям с вовхеда времен TBC - кастеры, стоящие на максимальном рендже получали 1 стак.

**Текущее обновление ядра:**

PTR: Build 20 2017-04-05 12:06:47 +0400

**Comment by ForesterDev** [comment]
![image](https://user-images.githubusercontent.com/11771800/55943843-6ac9d380-5c58-11e9-8244-96003a5aac0f.png)
![image](https://user-images.githubusercontent.com/11771800/55943856-71584b00-5c58-11e9-852d-c5719b409972.png)
![image](https://user-images.githubusercontent.com/11771800/55943862-787f5900-5c58-11e9-80f8-39bc273ce7c4.png)
![image](https://user-images.githubusercontent.com/11771800/55943871-7fa66700-5c58-11e9-8654-0554feced808.png)
Все работает
