### ISSUE TITLE
[Рейд] Логово Груула - Дверь

### ISSUE THREAD

**Issue by sega693** [VirginTeam/WotlkCore#585]
Описание:
http://ru.wowhead.com/gruuls-lair
http://wowroad.info/?npc=19044

Что работает не так?
Можно закрыть дверь перед боссом http://wowroad.info/?npc=19044

Как должно работать?
Дверь не должна быть "кликабельной"

Шаги для воспроизведения ошибки:
Нажать на дверь
http://puu.sh/yfcgu/9ba87514dd.jpg

Текущее обновление ядра:
Build 168 2017-10-23 17:03:00 +0400

**Comment by Devinette** [comment]
Пруфы

**Comment by sega693** [comment]
Пруфы чего? о_О
Не очевидно что игроки не должны закрывать намертво дверь перед боссом?

**Comment by ForesterDev** [comment]
исправлено
