### ISSUE TITLE
[Задание] ID 12541 & 12602 - Тролльский дозор: в подмастерья к алхимику!

### ISSUE THREAD

**Issue by odino4estvo** [VirginTeam/WotlkCore#586]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Помогите алхимику Финкльштейну в Хеб'Валоке в приготовлении сыворотки правды. Когда вы будете готовы приступить к работе, скажите об этом алхимику и выполняйте все его указания.

**Что работает не так?**

После взятия одного или двух одновременно квестов http://wowroad.info/?quest=12541 / http://wowroad.info/?quest=12602 у НПС http://wowroad.info/?quest=12541 нет диалога для запуска задания... Т.е. по сути, задания выдает, но скрипт не срабатывает, нужно собрать ингредиенты, который он по-очереди оглашает... 

**Как должно работать?**

После взятия заданий, говорим с алхимиком, у него должна появится строчка диалога "Я готов!", после которой, бегаем по комнаткам и приносим ему (или лутаем в котел) ингредиенты по очереди. Из-за чего нельзя взять символический квест как награду http://wowroad.info/?quest=12604, оно дается за ежедневные патрулирования, если успеваем уложиться менее чем за 20 минут. Пробовал отменить и взять по новой, результат такой же, в течении трех дней ситуация аналогична. Пробовал начинать делать задание http://ru.wowhead.com/quest=12587 в первую очередь у алхимика, а так же в последнюю очередь. 

**Шаги для воспроизведения ошибки:**

1. Взять задания http://wowroad.info/?quest=12541 / http://wowroad.info/?quest=12602
2. Выполнить его/их в отведенный срок.
3. Сдать квесты. 

**Текущее обновление ядра:**

Build 168
![image](https://user-images.githubusercontent.com/27158518/32414498-f7e4c144-c230-11e7-89a2-72ca513b3683.png)

**Comment by odino4estvo** [comment]
Не знаю как, но после 171-ой обновы квест заработал! Заметил, что убрали у Алхимика ежедневное задание "В подмастерье к Алхимику", (оно 2-ое по скрину), оставив только 1-е по скрину, берем кв, и все работает, собрал ингредиенты, бросал в бочку, сварили зелье, квест завершен!

**Comment by gmKroshka** [comment]
Проблема актуальна.
НПЦ предлагает два квеста.
Взяв один квест и отменив его, НПЦ более не выводит строчку диалога "Я готов/готова"

**Comment by gmKroshka** [comment]
http://forum.wowcircle.com/showthread.php?t=615738
