### ISSUE TITLE
[Задание] ID 10861 - Гнездовье Литик: превентивный удар

### ISSUE THREAD

**Issue by deexeq** [VirginTeam/WotlkCore#587]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Задание требует корректировки.

**Что работает не так?**

1. При использовании Проклятое яйцо (http://wowroad.info/?object=185211) ничего не происходит;
2. Злобный птенец (http://wowroad.info/?npc=22337) присутствует в заселении в Гнездовье Литик.

**Как должно работать?**

1. При использовании Проклятое яйцо (http://wowroad.info/?object=185211) из него должен появляться либо Злобный птенец (http://wowroad.info/?npc=22337) либо "Здоровый" (для условия Освобождено птенцов (3));
2. Злобный птенец (http://wowroad.info/?npc=22337) должен появляться только из Проклятое яйцо (http://wowroad.info/?object=185211).

**Текущее обновление ядра:**

Build 168 2017-10-23 17:03:00 +0400

**Comment by Santaria** [comment]
https://github.com/TrinityCore/TrinityCore/commit/d90a161619a96f8259a4d2052f6524393f7245e8
https://github.com/TrinityCore/TrinityCore/commit/0c4a74ee4555b7252f7a18eb2f7fd42be0319bba
