### ISSUE TITLE
[Подземелье] Черные топи

### ISSUE THREAD

**Issue by Rialzarre** [VirginTeam/WotlkCore#59]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Некорректная работа подземелья (комплексный репорт)

**Что работает не так?**

1. Черный ягуар http://ru.wowhead.com/npc=18982 гуляют без инвиза.
2. Некоторые НПЦ "ходят" по воздуху (http://ru.wowhead.com/npc=17952, http://ru.wowhead.com/npc=18983, http://ru.wowhead.com/npc=18982).
3. Охранитель времени http://ru.wowhead.com/npc=17918 находится рядом с Медивом.
4. Текст, который говорит Медив при запуске - не локализован.
>Медив кричит: What is this? Champions, coming to my aid? I sense the hand of the dark one in this. Truly this sacred event bears his blessing?
5. При спавне портала - визуально он пропадает. Порталы спавнятся очень быстро, друг за другом.
6. Появляющиеся неэлитные адды (http://ru.wowhead.com/npc=21818, http://ru.wowhead.com/npc=18994, http://ru.wowhead.com/npc=18995, http://ru.wowhead.com/npc=17835, http://ru.wowhead.com/npc=17892) стоят на месте, и появляются только в одном месте.
`X: -2041.060059 Y: 7042.080078 Z: 22.570807`
7. Текст, который говорит Эонус при смерти - не локализован.
> Эонус кричит: It is only a matter...of time.
8.  Отсутствует скрипт на появление http://ru.wowhead.com/npc=17023 из портала и уход назад.

**Как должно работать?**

1. Кошки должны быть в инвизе.
2. НПЦ должны ходить только по земле.
3. Охранитель времени не должен быть в инсте, только если его призовет игрок с использованием итема http://ru.wowhead.com/item=24289. Если игрок покидает инст - НПЦ должен пропадать.

4. Текст для локализации:
>Медив кричит: Что это? Герои, пришли мне на помощь? Я чувствую за этим волю темного владыки. Воистину это событие несет печать его темного благословления?
5. Портал должен быть визуально виден до тех пор, пока не будет убит его хранитель. Через 15 секунд должен спавниться новый портал (в случае с боссом - через 2 минуты).
6. Появляющиеся адды должны бежать к Медиву и пытаться пробить барьер. Адды должны спавниться во всех порталах.
7. Текст для локализации:
> Эонус кричит: Мы победим! Это всего лишь вопрос... времени.
8. НПЦ должны выйти, сказать фразу - и вернуться обратно через портал.

Видео правильной работы: https://youtu.be/GxS5jzMWzes

**Текущее обновление ядра:**

PTR: Build 20 2017-04-05 12:06:47 +0400

**Comment by ForesterDev** [comment]
Исправлено
