### ISSUE TITLE
[Объект] ID 182541 - Шишка олембы

### ISSUE THREAD

**Issue by deexeq** [VirginTeam/WotlkCore#595]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Нужна корректировка заселения (http://wowroad.info/?object=182541).

**Что работает не так?**

Слишком малое заселение.

**Как должно работать?**

Должно быть больше (http://ru.wowhead.com/object=182541).

**Текущее обновление ядра:**

Build 168 2017-10-23 17:03:00 +0400

**Comment by Ewropa** [comment]
по базе данного объекта заселено 56 шт, но нужна еще проверка

**Comment by Kodekc** [comment]
[Объекты] ID 182541 - Шишка олембы
* Перезаселены. Было = 56 Стало = 178

Изменения будут применены в ближайшем обновлении
