### ISSUE TITLE
Храм Ан'Киража (ID 15275, 15276 Близнецы Императоры)

### ISSUE THREAD

**Issue by Plasmashield** [VirginTeam/WotlkCore#598]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

http://ru.wowhead.com/npc=15276#abilities http://wowroad.info/?npc=15276
http://ru.wowhead.com/npc=15275#abilities http://wowroad.info/?npc=15275
Неверная работа способности Двойной телепорт http://ru.wowhead.com/spell=800

**Что работает не так?**

1. Отсутствует 2х секундный стан после телепорта.
2. Отсутствует иммун к таунтам.
3. Иногда что-то непонятное происходит с агро после телепорта 

**Как должно работать?**

1. После телепорта должна быть 2х секундная задержка перед тем, как они начнут атаковать вновь.
https://youtu.be/nHXfSDVX_ZA тут отлично видна 2х секундная задержка.
2. У обоих боссов должен быть полный иммун ко всем таунтам(сейчас кастер таунтится дк\палом, а мили - варом). Я не думаю, что тут нужны какие то пруфы.
3. После телепорта в ближайшую цель прилетает агро на несколько тысяч трита. Должно быть что то вроде 1.5-8к, точной инфы нет, но у нас прилетало по 20+, а такого быть не должно)

**Шаги для воспроизведения ошибки:**

1. Шаг один
2. Шаг два
3. Шаг три

**Текущее обновление ядра:**

Build 48 2017-11-06 15:02:10 +0400

**Comment by Kodekc** [comment]
- Проведена корректировка урона

**Comment by Santaria94** [comment]
> Добавлен иммунитет (Будет применено в ближайшем обновлении)

На данный момент у них агро после телепорта кривовато работает, бывает оно вешается вообще на кого-то с противоположной стороны. Сейчас это контрится таунтом. Может если приделывать им иммун к таунту, то только после того как будет починено агро у них? Я конечно понимаю, что иммун должен быть, но таунты это сейчас единственная контра другого бага.

**Comment by ForesterDev** [comment]
У них полностью сбрасывает лист аггро в 0 после телепорта. Любые действия игроков (отхилы, бафы и т.д.) начнут вырабатывать аггро заново

**Comment by Plasmashield** [comment]
Именно поэтому после каждого телепорта у них есть 2х секундная задержка, после которой они начинают бить. А так же они должны агриться на ближайшую цель, которой прилетает рандомное кол-во трита. На этом построена вся тактика на них, когда перед телепортом следующий танк становился в центр босса, что бы быть ближайшей целью и босс агрился на него

**Comment by Kodekc** [comment]
Можете добавить к репорту по больше ссылок на видео с убийством этого босса? Эта информация пригодится, чтоб понять некоторые механики в реализации.

**Comment by Plasmashield** [comment]
https://youtu.be/PVuPmDuGXpI
https://youtu.be/0waV0Zo46JE
https://youtu.be/wjD_T6NbPkI
Так же стоит добавить http://wowroad.info/?spell=568 которая у нас срабатывала при нахождении в милизоне босса http://wowroad.info/?npc=15276 , а должна срабатывать только при нанесении физ урона

**Comment by Oleksiymir** [comment]
Прошло 4 месяца, но их так и не починили. 80-е его по тактике(которая тут возможно, ибо они пашу тне правильно) не всегда убивают, а про 60 я вообще молчу. 2-х сек. стан необходим для набора агро ибо без него они срываются на прошлые цели и соответственно сбегаются.

**Comment by ForesterDev** [comment]
Исправлено, проверьте после обновления

**Comment by sega693** [comment]
https://github.com/VirginTeam/WotlkCore/issues/636 еще плиз

**Comment by Plasmashield** [comment]
Иммун к таунтам так и не добавлен
