### ISSUE TITLE
[Задание] ID 13664 - Падение черного рыцаря

### ISSUE THREAD

**Issue by Petkevich1994** [VirginTeam/WotlkCore#601]
Описание:

Нет квеста  http://ru.wowhead.com/quest=13664 у нпс Рыцарь Райдалла. Предыдущий квест http://ru.wowhead.com/quest=13663 выполнил и всё на этом.

Что работает не так?

Нет квеста в цепочке.

Как должно работать?

За квестом http://ru.wowhead.com/quest=13663 должен следовать http://ru.wowhead.com/quest=13664
**Шаги для воспроизведения ошибки:**

1. Сдать квест http://ru.wowhead.com/quest=13663
2. Взять квест http://ru.wowhead.com/quest=13664

Имя персонажа Slavakpss (может проблема только у меня)

Текущее обновление ядра:

Build 173 2017-11-08 19:06:21 +0400

**Comment by sega693** [comment]
С вовхеда

-Сделал этот квест, а следующий по цепочке не дает. Есть идеи в чем дело?
-Продолжение цепочки (следующий квест) появится только после того как вы станете чемпионом хотя бы одной фракции.
