### ISSUE TITLE
[Группа Заклинаний] Инвиз (2 уровень) + Животный Инстинкт

### ISSUE THREAD

**Issue by Exs4xev** [VirginTeam/WotlkCore#603]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

http://forum.wowcircle.com/showthread.php?t=573142
Данная тема уже поднималась несколько раз. Невозможно сказать что именно не работает. Либо из-за таланта http://wowroad.info/?spell=16949, либо же из-за самого скилла
Есть подозрение, что инвиз 2 уровня фигово работает, а вследствие чего и талант ничего не апает.
**Что работает не так?**

Невозможно протестировать в игре, т.к. ни талант, ни скилл не поддаются тесту на проверку "что не так с инвизом"

**Как должно работать?**

Ферал должен иметь инвиз, в котором при вкаченном таланте шанс быть незамеченным увеличивается, но даже с ним любая сова со старфолом издалека выбивает тебя из него. Как? Мне не понятно.

**Шаги для воспроизведения ошибки:**
-
**Текущее обновление ядра:**

сегодня. не прописывал .s inf

**Comment by Kodekc** [comment]
Сомнительный репорт, проверьте то, не знаю что, найдите и почините неведанную ошибку, будет репорт вечно валяться в баг-трекере
