### ISSUE TITLE
[Подземелье] Пик Черной Горы - Зал Драконов/Зал Оков

### ISSUE THREAD

**Issue by Myrskyntuoja** [VirginTeam/WotlkCore#604]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Пройти из Зала Драконов в Зал Оков не представляется возможным.

**Что работает не так?**

В Зале Драконов находятся 7 небольших комнат с мобами Ткач ужаса из легиона Чернорука (ID 9817), Призыватель из легиона Чернорука (ID 9818), Ветеран легиона Чернорука (ID 9819). Кроме них, на полу каждой из комнат также находятся активные руны, которые деактивируются при убийстве всех указанных мобов в данной комнате. Проблема в том, что из 7 рун активны и успешно деактивируются только 4.
После того, как убиты все указанные мобы:
x1 PvE: не открывается дверь, непосредственно ведущая в Зал Оков. Дверь, ведущая из Зала Драконов в коридорчик с подъемом перед Залом Оков, активна и может быть открыта вручную.
PTR: не открывается дверь, ведущая из Зала Драконов в коридорчик.

**Как должно работать?**

Убийство всех указанных мобов в Зале Драконов должно приводить к деактивации всех 7 рун и открытию дверей, преграждающих путь в Зал Оков (где находится Пиростраж Углевзор, ID 9816).

**Шаги для воспроизведения ошибки:**

1. Войти в Пик Черной Горы, от входа повернуть налево (верхняя часть), попасть в Зал Драконов
2. Убить мобов во всех 7 комнатах, обращая попутно внимание, что в 4 комнатах по правой стороне руны успешно деактивируются, а в 3 по левой неактивны изначально.
3. Попытаться пройти дальше в Зал Оков, понять, что это невозможно.

**Текущее обновление ядра:**

x1 PvE Build 171 2017-11-07 16:56:13 +0400
PTR Build 51 2017-11-08 19:06:21 +0400

![wowscrnshot_110917_202522](https://user-images.githubusercontent.com/33525145/32621087-e4a92888-c58f-11e7-9b98-0f4ffe78bf12.jpg)
![wowscrnshot_110917_202538](https://user-images.githubusercontent.com/33525145/32621096-e73e19c8-c58f-11e7-8d30-df6c3070d178.jpg)

**Comment by Myrskyntuoja** [comment]
UPD: проверил поведение на x3 Liberty (Build 51 2017-08-02 15:34:47 +0400), руны ведут себя точно так же, но это не препятствует прохождению подземелья, т.к. обе двери открыты.

**Comment by Riazarre** [comment]
Прекрасный репорт спасибо, закрою старый, т.к. в этом более актуальная информация.
#74
