### ISSUE TITLE
[NPC] ID 21838 - Терокк

### ISSUE THREAD

**Issue by gmKroshka** [VirginTeam/WotlkCore#616]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Затруднено убийство существа [Терокк](http://ru.wowhead.com/npc=21838). 

**Что работает не так?**

Во время боя с NPC он вешает на себя [Божественный щит](http://ru.wowhead.com/spell=40733), который должен сниматься в специальных зонах. Но зоны не появляются, щит висит постоянно.

**Как должно работать?**

Во второй фазе Терокк кастует на себя щит, блокирующий любой урон, щит не имеет временных рамок и сбивается одним лишь способом : по небу начинают летать Стражи Небес и скидывают бомбы - от них появляется голубоватое облако, держится не долго, подводить к нему Терокка нужно заранее. Куда скинут бомбу можно узнать по синему дымку (типа сигнальной ракеты) струящемуся из земли.

Если бой идёт слишком долго (точное временя неизвестно) Стражи перестают летать - и Терокка уже нет возможности добить

**Шаги для воспроизведения ошибки:**

1. Вызвать NPC при помощи груды костей и итема
2. Довести NPC до использования Божественного щита
3. Наслаждаться вечным баблом

**Текущее обновление ядра:**

Build 175 2017-11-13 15:53:58 +0400

**Comment by gmKroshka** [comment]
UpTest

**Comment by Scoren** [comment]
Ну, бабл можно снять оттащив Террока к воде, и бабл спадет. Потом добивайте.

**Comment by gmKroshka** [comment]
http://forum.wowcircle.com/showthread.php?t=485605

**Comment by gmRial** [comment]
Исправлено, после обновления.
