### ISSUE TITLE
[Предмет] ID 50709/50415 - Бринтролль, Костяной Судья

### ISSUE THREAD

**Issue by Gooldark** [VirginTeam/WotlkCore#62]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Что работает не так?**

Бринтролль, Костяной Судья ID 50709 и Похищение жизни ID 71839
Бринтролль, Костяной Судья ID 50415 и Похищение жизни ID 71838

а) имеет неверный РРМ у пала и дк

б) прокают от наложения Кровавой чумы(ID 55078) при использовании Мора(ID 50842) и Удара чумы(ID 49921), прокают от Печати мщения(ID 42463) и Печати порчи(ID 53739)

**Как должно работать?**

а) У пала РРМ должен быть 2, у дк 1,5

б) не должен прокать от наложения Кровавой чумы(ID 55078), Печати мщения(ID 42463) и Печати порчи(ID 53739)

**Текущее обновление ядра:**

09.04.2017. птр 20-ый билд

**Перенесено**

http://forum.wowcircle.com/showthread.php?t=630106

**Comment by Kodekc** [comment]
Внесены исправления. Будут применены в ближайшем обновлении
