### ISSUE TITLE
[Подземелье] Забытый город - Север

### ISSUE THREAD

**Issue by Plasmashield** [VirginTeam/WotlkCore#621]
**Описание:**

Не выдаются бафы у стражников при выполнении трибьют рана

**Что работает не так?**

При убийстве http://wowroad.info/?npc=11501 ,без убийства всех стражников в инсте, боссы не выдают бафы

**Как должно работать?**

Если убить http://wowroad.info/?npc=11501 не убив ни одного огра-босса, получив у http://wowroad.info/?npc=14353 бафф http://wowroad.info/?spell=22799 все огры в инсте становятся дружелюбными, а огры-боссы должны выдавать следующие бафы:
http://wowroad.info/?npc=14321 - http://wowroad.info/?spell=22817
http://wowroad.info/?npc=14326 - http://wowroad.info/?spell=22818
http://wowroad.info/?npc=14323 - http://wowroad.info/?spell=22820

https://youtu.be/yFAEbbo3VlA

**Шаги для воспроизведения ошибки:**

1. Выполнить трибьют ран
2. Подойти к боссам 
3. Увидеть отсутствие диалоговых окон

**Текущее обновление ядра:**

Build 175 2017-11-13 15:53:58 +0400

[//]: # (** Всё, что ниже и выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Теперь можете заполнять поля выше, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Comment by ForesterDev** [comment]
Исправлено, проверьте после обновления
