### ISSUE TITLE
[Предметы] ID 31154 - Бронзовое ожерелье

### ISSUE THREAD

**Issue by kalambyr18** [VirginTeam/WotlkCore#631]
**Описание:**

Бронзовое ожерелье http://wowroad.info/?item=31154

**Что работает не так?**

Уменьшение урона не фиксированное 2ед. Нет брони - уменьшение урона 2 ед. Есть броня - уменьшение меньше двух единиц.

**Как должно работать?**

Должно уменьшать урон на 2ед. всегда , не важно сколько брони на персонаже . Комм с вовхеда : Having 50% damage reduction through armor actually makes this necklace twice as effective as at 0% damage reduction, far from making it only half as effective. Imagine a mob that hits for a basic 100 damage. With 50% reduction that becomes 50. With this necklace, that then becomes 48 - that's 4% less than 50. With 0% damage reduction, the mob would hit for 100. This necklace would reduce it to 98, which is only 2% less than 100. More armor means this kind of effect becomes more powerful.

**Шаги для воспроизведения ошибки:**

Вот уменьшение урона на 2 ед если брони нет : 

http://screenshot.ru/upload/image/SUQK
http://screenshot.ru/upload/image/SUQL

Вот уменьшение урона на 1 ед если броня есть : 

http://screenshot.ru/upload/image/SUkq
http://screenshot.ru/upload/image/SUkt

Ожерелье работает не правильно.

**Текущее обновление ядра:**

175 2017-11-13 16:53:58 +04:00

[//]: # (** Всё, что ниже и выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Теперь можете заполнять поля выше, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Comment by gmOverfire** [comment]
Будет исправлено после обновления.
