### ISSUE TITLE
[Задание] ID 9254 - Упрямая ученица

### ISSUE THREAD

**Issue by Hargell79** [VirginTeam/WotlkCore#638]
**Описание:**
Ученица Мирведа не завершает задание http://db.logon3.com/?quest=9254

**Что работает не так?**
На NPC Ученица Мирведа отсутствует иконка завершения задания, NPC задание не завершает

**Как должно работать?**
Ожидаемый результат — возможность завершить задание

**Шаги для воспроизведения ошибки:**
Безусловное воспроизведение, шагов для воспроизведения не требуется

**Текущее обновление ядра:**
Build 177 2017-11-28

[//]: # (** Всё, что ниже и выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Когда требуется указать ссылку на игровые данные, используйте нашу базу данных: http://db.logon3.com **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Теперь можете заполнять поля выше, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Comment by aibolit94** [comment]
тоже самое над NPS отсутствует иконка для сдачи задания

**Comment by aibolit94** [comment]
# [Задание] ID 9254 - Упрямая ученица
задание не здаётся

**Comment by Santaria94** [comment]
Квест рабочий. 
Багается сам NPC во время одного из ее квестов, если не ошибаюсь, то проблемным является этот - http://db.logon3.com/?quest=8488

Точный момент забагивания не помню, то ли если кто-то из игроков не взял этот квест после сдачи квеста http://db.logon3.com/?quest=8487 или наоборот не сдал его после защиты NPC.

**Comment by Skroopa** [comment]
действительно, квест не работает.

**Comment by ForesterDev** [comment]
Внес изменения в работу скрипта, протестируйте после обновлени

**Comment by gmKroshka** [comment]
Жалобы продолжают поступать

> Невозможно сдать квест, так как отсутсвует возможность общение с Ученицой Мирведой

**Comment by Kodekc** [comment]
Требуется найти чёткий алгоритм забагивания NPC, в слепую пробовали переписывать задание, не помогает исправление.

**Comment by Santaria94** [comment]
http://db.logon3.com/?quest=8488 - проблема проявляется во время выполнения этого задания, если далеко убегать с квестовыми мобами, доводя их до эвейда. Их убийство не засчитывается для выполнения задания, а NPC-квестодатель зависает, не реагируя на игроков.
