### ISSUE TITLE
[Игровая механика]- Line of sight (LOS)

### ISSUE THREAD

**Issue by kalipsa988** [VirginTeam/WotlkCore#639]
**Описание:**

Не кастует.

**Что работает не так?**

Деревья, тележки, камни, скалы, заборы и прочая-прочая грязь блокирует заклинания и способности в Outdoor.

**Как должно работать?**

Деревья, тележки, камни, скалы, заборы и прочая-прочая грязь не должна мешать касту в Outdoor (пруфы ниже)
На офе всегда было и есть до сих пор так, что можно использовать заклинания через мусор, который я перечислял выше

**Шаги для воспроизведения ошибки:**

1. Зайти за текстуру(центральный пень на всг к примеру)
2. Пробнуть кастануть отхил или урон по кому то

**Текущее обновление ядра:**

Последнее обновление ядра: Build 177 2017-11-28 11:50:44 +0400
Пруфы
1 Главный пруф WoWWiki - http://wowwiki.wikia.com/wiki/Line_of_sight
Примечания к самому тезису Line of sight (LOS) в низу текста
2 Так же покапался в видеороликах старых и всем известных игроков (Vurtne, Вевер):

Офф времен классики:
http://www.warcraftmovies.com/movieview.php?id=21974 - 4.39 рога стреляет через пенек.
https://www.youtube.com/watch?v=c4bgggKMvQU - 0.28, 1.49, 4.41 касты через камни и деревья.

Офф времен БК:
http://www.warcraftmovies.com/movieview.php?id=39506 - 10.05 - кастует через камень

Офф времен ЛК:
http://www.warcraftmovies.com/movieview.php?id=154367 - 3.43, 14.16 - касты через тележки на бг и деревья в елвин форесте.
http://www.warcraftmovies.com/movieview.php?id=133973 - 22.44 каст через текстуры, и на 3.37 специально отходит за статую, чтобы незаметно кинуть прокнувший пиробласт.

Офф времен Каты:
http://www.warcraftmovies.com/movieview.php?id=187633 - 09.09- кидает пиробласт через дерево
3 Это на легионе сейчас.
 1. Касты и ШС роги через забор и камни в дуротаре на офе:

https://youtu.be/IO8eM6t3Ssc
https://youtu.be/6tB9Mg97qiY

2. Касты через деревья в элвин форесте на офе:

https://youtu.be/3aPG2fYTrYM
(это каст у нас https://www.youtube.com/watch?v=QZv92xEP7ss&feature=youtu.be)
3. Касты через огромные пни или это камни в центре Варсонга на офе:

https://youtu.be/adThNVKHOKg
https://youtu.be/FPJzO9PP17g

**Comment by Gooldark** [comment]
Обсуждали этот момент в канале активистов. Вроде как администрация решила не ставить фикс, так как игроки итак думают что текстуры дырявые.

**Comment by kalipsa988** [comment]
фиксану ли бы тогда на всг горы и заборы, что бы не стреляли через них и чарджи не делали

**Comment by gmOverfire** [comment]
А горы и заборы, увы, близзлайк :(

**Comment by kalipsa988** [comment]
Актуально

**Comment by ForesterDev** [comment]
Мы обсуждали этот момент командой еще давно - реализовать подобное возможно, но мы не будем. Препятствование деревьями и камнями (M2 объектами) уже прижилось за долгие годы и выглядит куда естественней и динамичней. Есть вещи, которые не разумно реализовывать у нас, несмотря на другую работу на оффе (как например общее КД на об/гер)
