### ISSUE TITLE
[NPC] ID 9596 - Баннок Люторез 

### ISSUE THREAD

**Issue by sega693** [VirginTeam/WotlkCore#642]
**Описание:**
http://db.logon3.com/?npc=9596

**Что работает не так?**
Отсутствует. За 20+ обновлений данжа не был ни разу

**Как должно работать?**
Должен спавниться

**Шаги для воспроизведения ошибки:**

1. зайти в инст
2. не обнаружить моба

**Текущее обновление ядра:**
Build 177 2017-11-28 11:50:44 +0400

**Comment by sega693** [comment]
https://github.com/VirginTeam/VirginCore/issues/693 
вы уверены насчет 12%?
По коментам вх спавнится каждые 3-4 захода

> After farming for the Arcanite Reaper plans I've seen him spawn 8 out of 31 runs

**Comment by Kodekc** [comment]
- [x] Возможность появления изменена до 24%
- [x] Добавлены базовые способности

Изменения будут применены в ближайшем обновлении.
