### ISSUE TITLE
[Задание] ID 12967 - Сражение со стихиями

### ISSUE THREAD

**Issue by deexeq** [VirginTeam/WotlkCore#643]
**Описание:**

Нужна корректировка [задания](http://db.logon3.com/?quest=12967).

**Что работает не так?**

Проблема с управляемым в ходе задания [Храппи](http://db.logon3.com/?npc=30124):
1) Имеет лишнюю способность [Разбудите Храппи](http://db.logon3.com/?spell=56752), которую убрали после патча 3.0.8 (судя по комментариям с wowhead), из-за этого управляемый [Храппи](http://db.logon3.com/?npc=30124) не должен периодически "засыпать".
2) Способность [Бросок снежка](http://db.logon3.com/?spell=56753) можно использовать на любых персонажей.
3) Во время действия [Сбор снега](http://db.logon3.com/?spell=56750) способность [Бросок снежка](http://db.logon3.com/?spell=56753) можно использовать несколько раз.
4) [Сугроб](http://db.logon3.com/?object=192075) не пропадает после использования [Сбор снега](http://db.logon3.com/?spell=56750)

**Как должно работать?**

1) Не должно быть способности [Разбудите Храппи](http://db.logon3.com/?spell=56752).
2) Способность [Бросок снежка](http://db.logon3.com/?spell=56753) можно использовать только на [Пылающий загробник](http://db.logon3.com/?npc=30125) и вражеских игроков (судя по комментариям с wowhead).
3) Во время действия [Сбор снега](http://db.logon3.com/?spell=56750) способность [Бросок снежка](http://db.logon3.com/?spell=56753) можно использовать 1 раз.
4) [Сугроб](http://db.logon3.com/?object=192075) должен пропадать.

Так же у [Пылающий загробник](http://db.logon3.com/?npc=30125) нужно уменьшить время возрождения - примерно 15-30 сек.

https://youtu.be/f_X-sUR1wG4?t=89

**Текущее обновление ядра:**

Build 178 2017-12-05 11:53:10 +0400

[//]: # (** Всё, что ниже и выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Когда требуется указать ссылку на игровые данные, используйте нашу базу данных: http://db.logon3.com **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Теперь можете заполнять поля выше, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Comment by Kodekc** [comment]
- [x] Убрал способность разбудите Храппи
- [x] Храппи теперь не будет засыпать в момент выполнения задания
