### ISSUE TITLE
[NPC] ID 23690, 24791 - Черпорог, Молодой черпорог

### ISSUE THREAD

**Issue by deexeq** [VirginTeam/WotlkCore#650]
**Описание:**

Нужна корректировка здоровья.

**Что работает не так?**

Неверное количество здоровья.

**Как должно работать?**

[Черпорог](http://db.logon3.com/?npc=23690) и [Молодой черпорог](http://db.logon3.com/?npc=24791) должны иметь одинаковое количество здоровья равное 6,986.

**Текущее обновление ядра:**

Build 178 2017-12-05 11:53:10 +0400

[//]: # (** Всё, что ниже и выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Когда требуется указать ссылку на игровые данные, используйте нашу базу данных: http://db.logon3.com **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Теперь можете заполнять поля выше, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Comment by Kodekc** [comment]
Исправлено. Изменения будут применены в ближайшем обновлении
