### ISSUE TITLE
[Задание] ID 10211 - Город света

### ISSUE THREAD

**Issue by Zloiapache** [VirginTeam/WotlkCore#657]
Квест "Город света" http://ru.wowhead.com/quest=10211

Добавьте описание проблемы здесь.

В задании "Город света" NPC Кадгара проваливается в текстуру и пропадает. Прошёл квест через несколько дней когда поставил метку на NPC. Каким то чудом он вылез из под пола и пошёл показывать Шаттрат.

Фактический результат — тот, который вы наблюдаете

Появляется NPC Кадгара он начинает двигаться и проваливается в текстуру

Ожидаемый результат — то, чего вы ожидали при выполнении ваших действий. Процесс правильной работы

НПС Кадгара должен провести вас по Шаттрату и рассказать историю жителей.

**Шаги для воспроизведения ошибки:**

1. Взять квест у Кадгара
2. Появляется NPC Кадгара он начинает двигаться и проваливается в текстуру

**Текущее обновление ядра:**
Logon 3 WowCircle Development
Build 178 2017-12-05 11:53:10 +0400

**Comment by Kodekc** [comment]
Вообще, он никуда идти не должен, а призывает существо, которое и показывает город... Скрипт старинный, но обрабатывается ядром, поставлю соответствующую метку.
