### ISSUE TITLE
[Задание] ID 5713 - Каждый выстрел – в цель

### ISSUE THREAD

**Issue by SergeyVyach** [VirginTeam/WotlkCore#658]
Описание:
Задание http://db.logon3.com/?quest=5713 не засчитывается как выполненное.

Что работает не так?
После защиты нпс от мобов задание должно пометиться как выполненное, однако этого не происходит.

Как должно работать?
Ожидаемый результат — возможность завершить задание

Шаги для воспроизведения ошибки:
Безусловное воспроизведение, шагов для воспроизведения не требуется

Текущее обновление ядра:
Build 178 2017-12-05

**Comment by SergeyVyach** [comment]
+ в тему

**Comment by gmKroshka** [comment]
Будет исправлено после обновления
