### ISSUE TITLE
[Задание] ID 10284 - Побег из Дарнхольда

### ISSUE THREAD

**Issue by Crerf** [VirginTeam/WotlkCore#661]
**Описание:**

При прохождении инста Старые предгорья Хилсбрада в Пещерах времени не работает квест.

**Что работает не так?**

Дается цепочка, в которой нужно освободить Тралла. Казармы взорваны, к Траллу спустился, квест на его освобождение взял, но идти он никуда не хочет.

**Как должно работать?**

После того, как нпс дает квест на его освобождение, у него в диалоге появляется команда, при использовании которой он начинает свое путешествие к свободе.

**Шаги для воспроизведения ошибки:**

1. Взорвать все казармы
2. Спуститься вниз и сдать/взять квест
3. Меня после этого он начинает игнорировать, хотя должен побежать к выходу.

**Текущее обновление ядра:**
[13:52:50] Logon 3 WowCircle Development
[13:52:50] Последнее обновление ядра: Build 178 2017-12-05 11:53:10 +0400
[13:52:50] Игроков онлайн: 2293 (максимум: 2293). Игроков в очереди: 0 (максимум: 0).
[13:52:50] Продолжительность работы сервера: 3 Hour(s) 7 Minute(s) 16 Second(s).

Персонаж - Crerf, орда, 80 уровень. Сервер Логон3.

**Comment by sega693** [comment]
вчера нормально прошел в героике. Правда квест сделан 100лет назад. Но скрипт на запуск тралла к самому кв не привязан ведь наверно.

**Comment by Kodekc** [comment]
**C++ Script:** ScriptName = npc_thrall_old_hillsbrad

**Comment by gmKroshka** [comment]
Исправлено, будет применено в обновлении

**Comment by ruafelianna** [comment]
Добрый день! У меня также наблюдается эта проблема: нет диалога с Траллом.

Build 240 2019-02-02 11:03:31 +0400 (WowCircle Logon3 х1 3.3.5а)
Обычный режим инста (не героик).

**Comment by Immposible** [comment]
Не работает ваш кв,2020 год а кв не работают...
