### ISSUE TITLE
[Задание] ID 12470 - Тайна бесконечности

### ISSUE THREAD

**Issue by ilp2401** [VirginTeam/WotlkCore#665]
**Описание:**

Во время прохождения квеста "тайна бесконечности" http://ru.wowhead.com/quest=12470. Ваш персонаж из будущего обращается в неверном роде.

**Что работает не так?**

Обращается в женском роде к персонажу мужского (пример: я не могу поверить что раньше носила такое).

**Как должно работать?**

Должен обращаться в верном склонении.

**Шаги для воспроизведения ошибки:**

Появляется по мере прохождения квеста "тайна бесконечности" http://ru.wowhead.com/quest=12470

**Текущее обновление ядра:**

Build 178 2017-12-05 11:53:10 +0400

**Comment by Santaria94** [comment]
Также отсутствует локализация завершения задания

> Ты видел Ноздорму? Бессмыслица какая-то.
<Хроми пару секунд обдумывает ваши слова.>
На самом деле, это отличная новость! Мы и понятия не имели, куда делся Повелитель Времени. Мы знали только, что он исчез, отправившись решать очень важные проблемы.
Итак, хотя вожак драконов Бесконечности и не объявился, тебе удалось выяснить кое-что важное: Ноздорму жив и здоров – и снова борется с ними!
Спасибо тебе, <название>!
