### ISSUE TITLE
[Задание] ID 13007 - Железный колосс

### ISSUE THREAD

**Issue by Ewropa** [VirginTeam/WotlkCore#68]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Нет скриптов на задание http://ru.wowhead.com/quest=13007

**Что работает не так?**

Не работает сфера по управлению Прирученным йормунгар, Железного колосса приходится убивать в ручную

**Как должно работать?**

Заюзал сферу и убил колоса
http://www.youtube.com/watch?v=aoXa_0tIHRs
**Шаги для воспроизведения ошибки:**

1. Попробовать использовать сферу
2. Она не робит

**Текущее обновление ядра:**

PTR: Build 20 2017-04-05 12:06:47 +0400

**Comment by ForesterDev** [comment]
Исправлено, будет применено в обновлении
