### ISSUE TITLE
[Предмет] ID 39656 - Эфес меча Тираэля

### ISSUE THREAD

**Issue by Julia987** [VirginTeam/WotlkCore#684]
Описание:
Не работает спутник [Мини-Тариэль](http://ru.wowhead.com/item=39656)

Что работает не так?:
Отсутствует реакция на команду /dancе или /танец; /sleep или /спать 

Как должно работать?
 Спутник Мини-Тираэль должен танцевать уникальный танец, когда к нему применить команду /dancе или /танец; и спать когда к нему применить команду /sleep или /спать 

Текущее обновление ядра:
Build 186 2017-12-29 12:06:40 +0400

**Comment by gmKroshka** [comment]
Подкрепите доказательствами, пожалуйста

**Comment by Julia987** [comment]
Вот видео как он должен работать. А у нас на эти команды нет реакции.
[https://www.youtube.com/watch?v=w4GHxMnhuvg](url)
[https://www.youtube.com/watch?v=3qzkCxlW31k](url)

**Comment by Julia987** [comment]
[https://www.youtube.com/watch?v=w4GHxMnhuvg](url)

**Comment by Julia987** [comment]
Видео как он должен работать при применении к нему команд /танец и /спать. У нас на эти команды реакции нет.
[Mini Tyrael](https://www.youtube.com/watch?v=3qzkCxlW31k)
[Mini Tyrael](https://www.youtube.com/watch?v=w4GHxMnhuvg)

**Comment by ForesterDev** [comment]
У него нет реакции на /спать, он сам периодически впадает в спячку. 

Скрипты пета будут реализованы в ближайшем обновлении

**Comment by Julia987** [comment]
"Предметы: реализованы скрипты Мини-Тираэля"
Все равно не реагирует ни на команду "/спать", ни на команду "/танец"

**Comment by gmKroshka** [comment]
Обновление не применено на х1 еще. Проверьте на тесте

**Comment by Julia987** [comment]
на тесте так же не работает

**Comment by gmKroshka** [comment]
Значит дождемся сообщения от разработчика об установке обновления на х1 и проверим снова

**Comment by Julia987** [comment]
Изменения на тесте уже вступили в силу, реагирует на команду /танец, но через 15-30 сек он начинает сам засыпать или вступать в исступление и так по кругу, танец прерывается. Вобщем в основном живет своей жизнью, не знаю так оно должно быть или нет, но этот его сон и исступление через некоторое время начинает надоедать.

"[22:58:50]Вы танцуете с Мини-Тираэлем.
[22:59:10]Мини-Тираэль внезапно засыпает.
[22:59:25]Мини-Тираэль впадает в исступление!
[22:59:40]Мини-Тираэль внезапно засыпает.
[23:00:10]Мини-Тираэль внезапно засыпает.
[23:00:25]Мини-Тираэль впадает в исступление!
[23:00:40]Мини-Тираэль внезапно засыпает.
[23:01:10]Мини-Тираэль внезапно засыпает.
[23:01:25]Мини-Тираэль впадает в исступление!"

**Comment by Julia987** [comment]
Теперь с петом нереально бегать. То он засыпает, то впадает в исступление и все эти эмоции спамит  в чат и этот его флуд уже надоедает. Когда с ним танцуешь, он себе может внезапно уснуть или просто остановиться и танец прерывается.

**Comment by Julia987** [comment]
Будете дорабатывать? Так и нереально с ним бегать. Безпрерывно спамит эмоции в чат и сбивается танец сам по себе.

**Comment by ForesterDev** [comment]
Исправлено, теперь питомец не будет засыпать в движении и в танце. Будет применено в обновлении
