### ISSUE TITLE
[Заклинание] ID 73799 - Жнец душ

### ISSUE THREAD

**Issue by Wassab** [VirginTeam/WotlkCore#686]
**Описание:**

[http://db.logon3.com/?spell=73799](http://db.logon3.com/?spell=73799)
Неправильная работа способности Жнец душ во всех сложностях.

**Что работает не так?**

Урон Жнеца душ (наложения и доты) понижается броней и эффектами понижающими получаемый физический урон и не подвержен частичному резисту.

**Как должно работать?**

Урон Жнеца душ (наложения и доты) не должен понижаться броней и эффектами понижающими получаемый физический урон. А должен понижаться эффектами понижающими получаемый магический урон. Урон при наложении (50% урона от оружия) должен подвергаться частичному резисту, дот часть не должна подвергаться частичному резисту.

**Шаги для воспроизведения ошибки:**

[http://worldoflogs.com/reports/mdprj1k1x67zaot5/xe/?enc=bosses&boss=36597&x=spell+%3D+"Soul+Reaper"](http://worldoflogs.com/reports/mdprj1k1x67zaot5/xe/?enc=bosses&boss=36597&x=spell+%3D+"Soul+Reaper") - лог урона жнеца на офе.
[http://www.worldoflogs.com/reports/s69j9r127uamovzq/xe/?x=spell+%3D+"Жнец+душ"](http://www.worldoflogs.com/reports/s69j9r127uamovzq/xe/?x=spell+%3D+"Жнец+душ") - лог урона жнеца у нас.

Попытаюсь объяснить. Возьмем к примеру урон жнеца из лога с офа:

> [19:15:47.105] The Lich King Soul Reaper Sco 57233 (R: 7749)
[19:15:47.105] Sco afflicted by Soul Reaper from The Lich King
[19:15:52.151] The Lich King Soul Reaper Sco 56529 (A: 915)

Первый урон - это 50% урона от оружия, второй урон - дот чать (70000 урона). Т.к. на офе часть резиста рассчитывалась до модификаций аурами цели, можем рассчитать какой урон был до снижения и потом понять чем он снижался. Я взял этот участок лога, т.к. танк под него не прожимался.

7749 - это 10процентный резист
77490 - весь урон
77490-7749=69741 - урон до снижения
69741 * 0,9 * 0,97 * 0,94 =57231 - урон полученный танком
0,9 - оборонительная стойка
0,97 - Великое благословение неприкосновенности (прото)
0,94 - Улучшенная оборонительная стойка (тир 7 талант прото ветки, уменьшает получаемый от заклинаний урон на 6%)

Дот чать:
56529+915=57444
70000 * 0,9 * 0,97 * 0,94=57443
Те же эффекты снижения урона.

Теперь урон на нашем сервере:

> [21:00:07.774] Король-лич Жнец душ Dannygirl 16735
[21:00:07.774] Dannygirl afflicted by Жнец душ from Король-лич
[21:00:12.653] Король-лич Жнец душ Dannygirl 17051

Бис дк, брони ~36000 это ~68% снижения физ урона против боссов.
Из эффектов понижающих получаемый урон:
Власть льда - 0,92
Клинковая ограда - 0,95
Великое благословение неприкосновенности (прото) - 0,97
Исцеление предков (тир 3 талант шамана ветки исцеление) - 0,90

Первая часть урона приблизительно равна половине урона автоатаки лича.
Вторая часть урона:
17051/0,92/0,95/0,97/0,9=22347
22347/70000=0,319
1-0,319=68,1% - броня танка

Баг очень облегчает прохождение энкаунтера. Если будут вопросы - отвечу.
P.S. Из первой части урона жнеца можно высчитать фактический урон лича на офе. Позже постараюсь оформить репорт, т.к. урон лича у нас немного ниже чем на офе.

**Текущее обновление ядра:**
Build 186 2017-12-29

[//]: # (** Всё, что ниже и выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Когда требуется указать ссылку на игровые данные, используйте нашу базу данных: http://db.logon3.com **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Теперь можете заполнять поля выше, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Comment by MedoOf** [comment]
http://www.worldoflogs.com/reports/4w9mqavzpn69xpqv/xe/?x=spell+%3D+"Жнец+душ"
Собственно вот, сделали бинарный резист, естественно после резиста и дота не вешается.

> **Как должно работать?**
> 
> Урон Жнеца душ (наложения и доты) не должен понижаться броней и эффектами понижающими получаемый физический урон. А должен понижаться эффектами понижающими получаемый магический урон. Урон при наложении (50% урона от оружия) должен подвергаться частичному резисту, дот часть не должна подвергаться частичному резисту.

**Comment by ForesterDev** [comment]
Какое значение резиста у танка в этих ситуациях?

**Comment by MedoOf** [comment]
130 скорее всего, сложно проверить если персонаж не твой. Но там происходит полный резист, такого же не должно быть.

**Comment by ForesterDev** [comment]
![image](https://user-images.githubusercontent.com/11771800/53344114-52615c00-392b-11e9-9b18-95d22f953e6a.png)

Способность Жнец душ не считает бинарной в ядре, проверил с резистом в 130 (и 260 под мастером аур) - ни одного полного резиста за 30 ударов. Возможно такое происходит при определенных аурах либо талантах. Нужно найти причину

**Comment by ForesterDev** [comment]
![image](https://user-images.githubusercontent.com/11771800/53345651-d49f4f80-392e-11e9-8620-790519e80242.png)
Удалось воспроизвести, по факту вообще не связано с уровнем резиста персонажа. Причина пока не ясна

**Comment by MedoOf** [comment]
[такая же картина, танк тоже дк](http://www.worldoflogs.com/reports/0eonazoxkrzqts73/xe/?s=5189&e=6208&x=spell+%3D+"Жнец+душ")
Еще вот что странно:
[20:47:24.501] Король-лич Жнец душ Ахилесдк Resist (47476)
Получается в резист уходит весь урон, но при этом отображается сколько его должно быть, а не как обычно полный резист:[20:47:54.609] Король-лич Жнец душ Ахилесдк Resist

**Comment by ForesterDev** [comment]
В проблеме разобрался, в связи с тем что спел имеет в своей маске помимо школы магии тьмы еще и физику, то в расчет сопротивления берет броню игрока. Это будет исправлено в обновлении
