### ISSUE TITLE
[Задание] ID 2399- Росток папоротника

### ISSUE THREAD

**Issue by WarFoll2** [VirginTeam/WotlkCore#692]
**Описание:**
Невозможно сдать кв.

**Что работает не так?**
 При разговоре с нип "Деналан" не возможно сдать кв.

**Как должно работать?**
Поговорите с нип "Деналан" и он дает кв который можно сразу завершить.

**Шаги для воспроизведения ошибки:**

1. Сначала выполняем преквест "Мерцающий росток"
2. Сдаем кв "Мерцающий росток" нипу "Деналан"
3. Идет диалог и после диалога  нип "Деналан" выдает кв "Росток папоротника" который нельзя взять или сдать.

**Текущее обновление ядра:**
Build 186 2017-12-29 12:06:40 +0400 (Live Server)

**Comment by gmKroshka** [comment]
https://github.com/VirginTeam/WotlkCore/issues/886
