### ISSUE TITLE
[Заклинание] ID 24818 - Пагубное дыхание и кд некоторых спеллов

### ISSUE THREAD

**Issue by sega693** [VirginTeam/WotlkCore#694]
**Описание:**
http://db.logon3.com/?spell=24818

и способности с задержкой кд (спелы, восстановление которых начинается не сразу), например 
http://db.logon3.com/?spell=5384 
http://db.logon3.com/?spell=34477
http://db.logon3.com/?spell=57934
http://db.logon3.com/?spell=1784
http://db.logon3.com/?spell=5215

**Что работает не так?**
при получении дебафа от Дыхания забагиваются данные способности - нельзя применить до релога

**Как должно работать?**
должно быть стандартное время восстановления + 10сек * (кол-во стаков)

**Шаги для воспроизведения ошибки:**

1. получить дебаф Дыхания
2. прожать спелл, например Притвориться мертвым http://db.logon3.com/?spell=5384 
3. встать после "смерти"
4. увидеть, что способность более недоступна для применения вообще (до релога)

**Текущее обновление ядра:**
 Build 186 2017-12-29 12:06:40 +0400

**Comment by ForesterDev** [comment]
Исправлено, тестируйте после обновления
