### ISSUE TITLE
[Задание] ID 6394 - Кирка Тазз'рила

### ISSUE THREAD

**Issue by Santaria94** [VirginTeam/WotlkCore#697]
**Описание:**

http://db.logon3.com/?quest=6394
Неверное время восстановления квест-объекта.

**Что работает не так?**

http://db.logon3.com/?object=178087 - текущее время восстановления 10 мин.

**Как должно работать?**

Время восстановления должно составлять - 15 секунд.

http://ru.wowhead.com/item=16332#english-comments
**От Magmarrax (7,226 – 1·14·77) 2010-09-22 (Обновление 3.3.5)**
It has a 15 second respawn time, so there won't be any fighting for the pick.

**Текущее обновление ядра:**

Build 186

[//]: # (** Всё, что ниже и выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Когда требуется указать ссылку на игровые данные, используйте нашу базу данных: http://db.logon3.com **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Теперь можете заполнять поля выше, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Comment by Luchass** [comment]
Исправлено. Проверяйте после обновления.
