### ISSUE TITLE
[NPC] ID 24812 - Штормовой великан

### ISSUE THREAD

**Issue by gmOpex** [VirginTeam/WotlkCore#700]
**Описание:**

Отсутствие скриптов нпс и способностей

**Что работает не так?**
нет способностей:
http://ru.wowhead.com/spell=50100
http://ru.wowhead.com/spell=50105
http://ru.wowhead.com/spell=50084
Бьет только автоатакой
[11:36:56] AIName:  ScriptName: generic_creature
[11:36:56] Flags Extra: 0
[11:36:56] MechanicImmuneMask: 0

**Как должно работать?**

Периодичное использование спеллов:
http://ru.wowhead.com/spell=50100
http://ru.wowhead.com/spell=50105
http://ru.wowhead.com/spell=50084

**Текущее обновление ядра:**

[11:45:59] Logon 3 WowCircle Development
[11:45:59] Последнее обновление ядра: Build 186 2017-12-29 12:06:40 +0400
[11:45:59] Игроков онлайн: 1006 (максимум: 5933). Игроков в очереди: 0 (максимум: 0).
[11:45:59] Продолжительность работы сервера: 1 Day(s) 7 Hour(s) 19 Minute(s) 52 Second(s).
[11:45:59] Серверная задержка: 12.
[11:45:59] Следующее начисление очков арены: 14.01.2018  10:22

[//]: # (** Всё, что ниже и выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Когда требуется указать ссылку на игровые данные, используйте нашу базу данных: http://db.logon3.com **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Теперь можете заполнять поля выше, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Comment by ForesterDev** [comment]
Исправлено. Будет применено в обновлении
