### ISSUE TITLE
[Задание] ID 11134 - Конец вражеской пропаганде 

### ISSUE THREAD

**Issue by LexaZaycev** [VirginTeam/WotlkCore#701]
**Описание:**
http://db.logon3.com?quest=11134

Добавьте описание проблемы здесь.

**Что работает не так?**
Гаваса Серого Щита невозможно арестовать, так как он дружественный
Фактический результат — тот, который вы наблюдаете

**Как должно работать?**
Гавис Серый Щит должен быть враждебным
Ожидаемый результат — то, чего вы ожидали при выполнении ваших действий. Процесс правильной работы

**Шаги для воспроизведения ошибки:**

1. Шаг один
2. Шаг два
3. Шаг три

**Текущее обновление ядра:**
Build 186 2017-12-29 12:06:40 +0400

[//]: # (** Всё, что ниже и выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Когда требуется указать ссылку на игровые данные, используйте нашу базу данных: http://db.logon3.com **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Теперь можете заполнять поля выше, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Comment by Kodekc** [comment]
Исправлено. Изменения будут применены в ближайшем обновлении

**Comment by Kodekc** [comment]
Исправлена ошибка, когда при понижении HP НИПа, он исчезал, а после возрождался, как дружелюбный. Изменения будут применены в ближайшем обновлении
