### ISSUE TITLE
[Существа] ID 23420 - Воплощение гнева

### ISSUE THREAD

**Issue by sega693** [VirginTeam/WotlkCore#703]
**Описание:**
http://db.logon3.com/?npc=23420#drops

**Что работает не так?**
Моментально исчезает тело после убийства - нельзя получить лут

**Как должно работать?**
Должен лежать труп и быть лутабельным

**Шаги для воспроизведения ошибки:**
1. Убить
2. Не успеть заметить как босс исчез

Говорят, если убить на подъеме перед комнатой с боссом лут будет, но это не точно.

**Текущее обновление ядра:**
Build 186 2017-12-29 12:06:40 +0400

**Comment by ForesterDev** [comment]
Проверьте после обновления, скрипт босса полностью переписан

**Comment by olegklim1991** [comment]
все работает спасибо
