### ISSUE TITLE
[Существа] ID 14601- Черноскал

### ISSUE THREAD

**Issue by sega693** [VirginTeam/WotlkCore#707]
**Описание:**
http://db.logon3.com/?npc=14601#drops
http://ru.wowhead.com/npc=14601

**Что работает не так?**
Нет перчаток т2 в луте
http://db.logon3.com/?item=16920
http://db.logon3.com/?item=16899
http://db.logon3.com/?item=16913
http://db.logon3.com/?item=16928
http://db.logon3.com/?item=16907
http://db.logon3.com/?item=16964
http://db.logon3.com/?item=16948
http://db.logon3.com/?item=16940
http://db.logon3.com/?item=16956

**Как должно работать?**
Должны быт перчатки т2 в луте.
На вовхеде и в атлас-луте они есть во всех трех драконах
http://db.logon3.com/?npc=11983 
http://db.logon3.com/?npc=11981
http://db.logon3.com/?npc=14601

**Шаги для воспроизведения ошибки:**
1. убить
2. полутать

**Текущее обновление ядра:**
Build 186 2017-12-29 12:06:40 +0400

**Comment by Kodekc** [comment]
- [x] Обновлена информация о добыче предметов и золота с NPC, согласно архивам wowhead.
- [x] Усилена атака ближнего боя (белый урон) и обновлено базовое время атаки

Изменения будут применены в ближайшем обновлении.
