### ISSUE TITLE
[Задание] ID 648 Спасти КПХ-17/TN!

### ISSUE THREAD

**Issue by Rorshah** [VirginTeam/WotlkCore#711]
[http://db.logon3.com/?quest=648](http://db.logon3.com/?quest=648)

Что работает не так?

Неадекватное поведение курицы.
Как сомнамбула ходит вперед-назад по маршруту, собирает кучу треша, ни на что не реагирует.

Как должно работать?

Идя по ходу маршрута и получив удар от моба курица вступает в бой.
По истечении боя курица возвращается в место начала боя и продолжает свой маршрут.

Текущее обновление ядра:

Build 187

[//]: # (** Всё, что ниже и выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Когда требуется указать ссылку на игровые данные, используйте нашу базу данных: http://db.logon3.com **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Теперь можете заполнять поля выше, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Comment by Luchass** [comment]
В патче 3.2.0 ей еще укоротили маршрут и призывающихся мобов, а в конце она должна улетать (http://db.logon3.com/?spell=68499).

http://wowwiki.wikia.com/wiki/Quest:Rescue_OOX-17/TN!

**Comment by Rorshah** [comment]
Квест по прежнему невыполним.
билд 241

**Comment by Kodekc** [comment]
ScriptName = npc_OOX17

**Comment by Kodekc** [comment]
Поправлю некоторые флаги, может станет лучше. Сам маршрут движения и призыва некоторых NPC на С++
