### ISSUE TITLE
[Рейд] Храм Ан'Киража (ID 15589 Око К'Туна)

### ISSUE THREAD

**Issue by sega693** [VirginTeam/WotlkCore#712]
**Описание:**
http://db.logon3.com/?npc=15589
http://db.logon3.com/?spell=26029 Свирепый взгляд

**Что работает не так?**
Нет анимации каста. Босс краснеет и бьет лучем визуально в одну точку, но сам урон проходит по дуге, как и должно быть. Невозможно определить в какую сторону убегать = ловишь невидимые ваншоты, если не зерганул до каста.

**Как должно работать?**
43750-56250 Шедоу дамага любому кто попадет в Луч. Луч выходит из зрачка Глазика по радиусу комнаты. Сам глаз при этом краснеет и вращается довольно медленно По или Против часовой стрелки ровно на 180 градусов. Место начала луча тоже выбирается случайно. Когда и откуда пойдет Луч можно понять но покраснению Глазика и некоему темному облачку в месте начала луча.

**Шаги для воспроизведения ошибки:**
1. Спулить 
2. Дождаться каста
3. Словить ваншот

**Текущее обновление ядра:**
Build 187 2018-01-24 12:42:58 +0400

**Comment by ForesterDev** [comment]
Тестируйте после обновления
