### ISSUE TITLE
[Задание] ID 5219 - Цель: Слезы Далсона

### ISSUE THREAD

**Issue by NotYourLevel** [VirginTeam/WotlkCore#714]
**Описание:**

НПС http://db.logon3.com/?npc=11077 спавнится прямо в котле, что делает не возможным его убийство или нанесение урона.

**Что работает не так?**

http://s018.radikal.ru/i518/1705/0a/e038f2922b87.jpg

**Как должно работать?**

НПС должен спавнится рядом с котлом как на скриншоте http://wow.zamimg.com/uploads/screenshots/normal/21339-хранитель-котла-злобиус.jpg

**Шаги для воспроизведения ошибки:**

1. Шаг один
2. Шаг два
3. Шаг три

**Текущее обновление ядра:**

Build 187 2018-01-24 12:42:58

[//]: # (** Всё, что ниже и выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Когда требуется указать ссылку на игровые данные, используйте нашу базу данных: http://db.logon3.com **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Теперь можете заполнять поля выше, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Comment by gmKroshka** [comment]
https://github.com/VirginTeam/WotlkCore/issues/205
