### ISSUE TITLE
[Задание] ID 8970 - Я вижу в твоём будущем остров Алькац...

### ISSUE THREAD

**Issue by Sangriento** [VirginTeam/WotlkCore#717]
**Описание:**
http://db.logon3.com/?quest=8970
**Что работает не так?**

НИП Бодли не выдает следующий по цепочке квест http://db.logon3.com/?quest=8985

**Как должно работать?**

На персонажа должен быть наложен эффект http://db.logon3.com/?spell=5017

**Шаги для воспроизведения ошибки:**

1. Сдать квестовые итемы http://db.logon3.com/?item=22094
2. Возможно, если сдавать квест в режиме невидимости, нпс не может выбрать персонажа в таргет и наложить заклинание
3. Шаг три

**Текущее обновление ядра:**

Build 187 2018-01-29 Live Server. Ник Cillian

[//]: # (** Всё, что ниже и выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Когда требуется указать ссылку на игровые данные, используйте нашу базу данных: http://db.logon3.com **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Теперь можете заполнять поля выше, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Comment by Kodekc** [comment]
https://github.com/VirginTeam/WotlkCore/issues/794
