### ISSUE TITLE
нет дейликов на репутацию Сыны Ходира

### ISSUE THREAD

**Issue by dlkjfalkf** [VirginTeam/WotlkCore#718]
Нет дейлика жар и холод http://db.logon3.com/?quest=12981
а именно нет Наковальня Фьорна http://db.logon3.com/?object=192071 которая дает этот квест
Нет дейлика Звуки рога Ходира http://db.logon3.com/?quest=12977 
а именно нет Рог Ходира http://db.logon3.com/?object=192078 которая дает этот квест
Нет дейлика  Полировка шлема http://db.logon3.com/?quest=13006 
а именно нет Шлем Ходира http://db.logon3.com/?object=192080 которая дает этот квест
Нет дейлика Бросая копье Ходира http://db.logon3.com/?quest=13003
а именно нет Копье Ходира http://db.logon3.com/?object=192079 которая дает этот квест

Явно проблема в скрипте или еще в чем, не отображаются объеты которые должны давать задания ежедневные

Build 187 2018-01-24 12:42:58 +0400

**Comment by Kodekc** [comment]
Мне кажется проблема конкретно у вашего персонажа, а не общая. Пробовали поспрашивать друзей/знакомых, кто выполнял эти задания недавно?

**Comment by dlkjfalkf** [comment]
всмысле моя проблема??? все квесты цепочек я сделал, там мне доступно только 2 квеста на сдачу итемов на репу и http://ru.wowhead.com/quest=12994. Скорее всего это у вас опять проблемы в движке или коде или скрипте, Знакомы отвечают, че за квесты? за баджи репу все делают, один бадж-500 репы.

**Comment by Kodekc** [comment]
Можете воспользоваться нашей базой данных для Wotlk: http://db.logon3.com и понять, что все задания присутствуют в игре

**Comment by dlkjfalkf** [comment]
обновил топик

**Comment by Kodekc** [comment]
Вы не видите эти объекты только в том случае, если находитесь в другой фазе, в правильной фазе вы должны находиться, если сделали все преквесты

**Comment by dlkjfalkf** [comment]
я все преквесты и сделал. Даже уверен что если один преквест и не был бы сделан то другие квестопредметы серавно должны быть видны

**Comment by Kodekc** [comment]
Укажите имя персонажа

**Comment by dlkjfalkf** [comment]
Тимог,

**Comment by Kodekc** [comment]
Завтра проверю

**Comment by Ewropa** [comment]
https://github.com/VirginTeam/WotlkCore/issues/445

**Comment by lambazta** [comment]
Таже проблема. После выполнения цепочек в деревне не появляются предметы (шлем, копье, горн), и соответственно, не возможно взять дейлики на них.

**Comment by lambazta** [comment]
Ник персонажа Flatiron
