### ISSUE TITLE
Просмотр талантов у цели

### ISSUE THREAD

**Issue by Rorshah** [VirginTeam/WotlkCore#719]
**Описание:**

Ну к примеру в Даларане взял какого-то чувачка в цель 
и смотрю значит его таланты

**Что работает не так?**

таланты постоянно сбрасываются. 
Думал-думал и че оказалось ?
Показывает постоянно таланты по маусоверу - на кого мышка
легла того таланты и смотрим

**Как должно работать?**

Не должны таланты прыгать.
Цель если не меняешь - таланты показывает именно его,
независимо куда мышка легла

**Шаги для воспроизведения ошибки:**

1. Взять в цель игрока
2. Открыть в просмотре его таланты
3. Мышкой пошарить по экрану, чтоб там другие игроки еще стояли

**Текущее обновление ядра:**

Build 187 от 24-01-2018.

[//]: # (** Всё, что ниже и выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Когда требуется указать ссылку на игровые данные, используйте нашу базу данных: http://db.logon3.com **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять заголовки для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Теперь можете заполнять поля выше, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Comment by Kodekc** [comment]
Основание какое для исправление, почему считаете, что так работать не должно?

**Comment by Rorshah** [comment]
Это более чем логично.
Если я осматриваю цель - то и таланты должны быть целевые.
А не нонеймов по случайному маусоверу.
Постоянно слышу вопросы от пришедших игроков с других серверов
по этому поводу: "что за баганные сервак" - типа того.

Можно посмотреть на офе, если такое есть там. Не думаю что это что-то 
революционное чтобы это меняли.

**Comment by Kodekc** [comment]
Мы бы были ради посмотреть в актуальной версии, но на официальном проекте игры, давно уже поменяли таланты и их отображение. На самом деле я лично не в курсе, как должно быть и ваших слов явно будет недостаточно, чтоб взяли это в работу, требуется более весомая аргументация.

**Comment by Rorshah** [comment]
нет так нет.
Пусть сервер остается "баганым" :)

**Comment by Kodekc** [comment]
Пока это нельзя назвать ошибкой, пока это не будет доказано. Если вы этим не будете заниматься, то репорт закрою.

**Comment by Rorshah** [comment]
не буду конечно.
я Вам указал одну из причин почему в народе логон3 зовут баганым сервером.
Вы, отклонив данный репорт, автоматически утвердите что это норма для логон3.

Это же "удобно" когда просматриваешь таланты в Даларане и никак их не можешь 
посмотреть, потому что народ так и бегает под указателем мыши ;).
Стоит на этом настоять, ага :)

**Comment by Kodekc** [comment]
Я не верю в сплетни и надуманные утверждения, не видел ещё ни одного рабочего сервера, где нет багов, так можно сказать о любом сервере, не только о нашем, даже на официальном проекте игры есть баги. Вопрос тут в другом, если вы пришли сюда сообщить об ошибке, будьте добры аргументировать свою точку зрения. Здесь не стол заказов, а трекер ошибок, где дискуссия, факты, расчёты и аналитика не пустые слова, никто не намерен тратить своё время в пустую.

**Comment by ForesterDev** [comment]
Этот баг не на сервере, а связан с аддонами. Скорее всего с GearScore. Удалите и попробуйте

**Comment by Rorshah** [comment]
Да. Помогло.
Спасибо!
