### ISSUE TITLE
[Задание] ID 12671 - Разведывательный полет

### ISSUE THREAD

**Issue by Razama1234** [VirginTeam/WotlkCore#72]
**Описание:**

Квест не работает как надо. 

**Что работает не так?**

Вертолетом можно лететь вперёд, влево или вправо, приземлиться при этом не представляется возможным. Ещё судя по всему скорость полёта после взятия управления на себя очень низкая.

**Как должно работать?**

[Видео.](https://www.youtube.com/watch?v=Kn5xjJIKrOQ)

**Шаги для воспроизведения ошибки:**

1. Взять квест.
2. Дождаться подбития вертолёта и управление переходит к тебе.

**Текущее обновление ядра:**

Build 151 2017-04-03 15:25:08 +0400

**Comment by Rorshah** [comment]
сделал этот квест позавчера. никаких проблем или неудобств не испытал.

**Comment by ForesterDev** [comment]
Работает
