### ISSUE TITLE
[Достижение] ID 2043 - Повалить увальня

### ISSUE THREAD

**Issue by XxRagdajxX** [VirginTeam/WotlkCore#720]
**Описание:**

Добрый день!

В игровом процессе обнаружилась ошибка, а именно некорректная работа падающего меча на боссе Свала Вечноскорбящая в подземелье Вершина Утгард. В результате данной ошибки в работе системы невозможно получить достижение "Повалить увальня".

**Что работает не так?**

Суть проблемы заключается в том, что когда подводишь Увальня из плети под меч, ничего не происходит. Отображение анимации падающего меча отсутствует, и как следствие по Увальню не проходит урон. Три ведьмы просто исчезают и ничего не происходит.

**Как должно работать?**
В момент падения меча, когда под ним стоит Увалень с 5% ХП должен проходить урон от данного падения и Увалень должен умирать.

**Шаги для воспроизведения ошибки:**

1. Подвести Увальня под падающий меч.
2. Не убивать ведьм и ждать, пока пройдет каст.
3. В результате отсутствие анимации падающего меча и урона по игроку (который в данный момент находится по идеи в контроле под мечом) и по Увальню.

**Текущее обновление ядра:**

Build 187 2018-01-24 12:42:58 +0400

[//]: # (** Всё, что ниже и выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Когда требуется указать ссылку на игровые данные, используйте нашу базу данных: http://db.logon3.com **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять заголовки для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Теперь можете заполнять поля выше, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Comment by ForesterDev** [comment]
Исправлено, проверьте после обновления
