### ISSUE TITLE
[Подземелье] Регистрация случайного подземелья - лоу ЛВЛ

### ISSUE THREAD

**Issue by Ewropa** [VirginTeam/WotlkCore#722]
Регистрация случайного подземелья для низкоуровневых персонажей

**Что работает не так?**

зайти в игру, встать в очередь на случайное подземелье, получить приглашение, принять его, переместиться в подземелье и быть, в последствии исключенным из него, причем попавшая группа дальше проходит подземелье, но уже с приглашенным туда 80 лвл персонажем

**Как должно работать?**

зайти в игру, встать в очередь на случайное подземелье, получить приглашение, принять его, переместиться в подземелье, пройти подземелье, если же исключили, то оставшаяся группа должна добрать себе игрока с разбегом +-5 лвл от уровня подземелья, но никак выше, т.е. при появлении в пати высокоуровневого персонажа не должно давать возможность продолжать проходить случайное подземелье, т.е. группа должна исключаться из очереди.

**Шаги для воспроизведения ошибки:**

указал выше

**Текущее обновление ядра:**

Думаю на обоих так творится

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by gmOverfire** [comment]
#244
