### ISSUE TITLE
[Рейды] - Хранители в Ульдуаре

### ISSUE THREAD

**Issue by Jigglypuff715** [VirginTeam/WotlkCore#723]
**Ссылки и комментарии:**

http://i.piccy.info/i9/6f58aef844c168ca5d025f184a7676df/1517468448/264064/1217919/WoWScrnShot_020118_085036.jpg
Не жмется/не работает диалог с нпс, после которого у йога появляется http://db.logon3.com/?npc=33412
То же самое с остальными тремя хранителями.
**Что работает не так?**
Не работает диалог с дружественными нпс - копиями хранителей (Мимирон, Фрея, Торим, Ходир) для запуска изи мода на йоге. 

**Как должно работать?**

Кнопочка диалога должна нажиматься с нпсами (дружественными копиями хранителей) которые появляются после убийства каждого хранителя. Нпсы у входа в тоннели к каждому хранителю.

**Шаги для воспроизведения ошибки:**

1. Убиваем любого хранителя из четырех.
2. Возвращаемся к центральному кругу во внутреннем святилище Ульдуара. На входе к тоннелю, ведущему к комнате с убитым хранителем, появляется его дружественная для нас копия.
3. Жмём диалог с дружественным нпс хранителем.
4. Проверяем наличие хранителя у Йога, хотя сами френдли нпс после диалога должны пропасть, на сколько помню.

**Текущее обновление ядра:**

Последнее обновление ядра: Build 187 2018-01-24 12:42:58 +0400

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by ForesterDev** [comment]
Исправлено, будет применено в обновлении
