### ISSUE TITLE
[Заклинание] ID 20552 - Проращивание

### ISSUE THREAD

**Issue by Mulfseyn** [VirginTeam/WotlkCore#725]
**Ссылки и комментарии:**

http://ru.wowhead.com/spell=20552

**Что работает не так?**

Не добавляет навык травничества на 15

**Как должно работать?**

Рассовая пассивка должна добавлять 15 к навыку травничества 

**Шаги для воспроизведения ошибки:**

1. Взятие профессии "Травничество" 

**Текущее обновление ядра:**

Build 187 2018-01-24 12:42:58 +0400

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by gmKroshka** [comment]
Правила оформления репортов находятся по ссылке
https://github.com/VirginTeam/WotlkCore

**Comment by ForesterDev** [comment]
![image](https://user-images.githubusercontent.com/11771800/35721784-1fc614de-080d-11e8-80f5-47aca5fded93.png)
Проверил, не воспроизводится

**Comment by gmRial** [comment]
#1177

**Comment by gmKroshka** [comment]
Исправлено, будет применено в обновлении
