### ISSUE TITLE
[Существа] Волхан - 28587

### ISSUE THREAD

**Issue by sega693** [VirginTeam/WotlkCore#726]
**Ссылки и комментарии:**
http://db.logon3.com/?npc=28587#abilities
http://db.logon3.com/?spell=52238 Пламенрав

**Что работает не так?**
Отхиливается на фулл хп при юзе http://db.logon3.com/?spell=52238

**Как должно работать?**
Не должен отхиливаться

https://www.youtube.com/watch?v=vxu2sfmfaTc гайд
и еще рандомные видосики 
https://www.youtube.com/watch?v=sNK2FKbFawk
https://www.youtube.com/watch?v=hGkTN2gIg_8

**Шаги для воспроизведения ошибки:**

1. бить босса
2. увидеть как он 5 раз регенится на фулл хп

**Текущее обновление ядра:**
Build 187 2018-01-24 12:42:58 +0400

**Comment by ForesterDev** [comment]
Исправлено, будет применено в обновлении
