### ISSUE TITLE
баг http://db.logon3.com/?search=ледяной+доспех#abilities ледяной доспех

### ISSUE THREAD

**Issue by dlkjfalkf** [VirginTeam/WotlkCore#727]
баг http://db.logon3.com/?search=ледяной+доспех#abilities ледяной доспех
**Что работает не так?**
со всеми талантами должно быть - скорость передвижения снижается на 50%, а время между атаками увеличивается на 25%
Фактический результат — тот, который вы наблюдаете 
скорость передвижения снижается на 30%, а время между атаками увеличивается на 25%
как будто таланты не задействованы

**Как должно работать?**
со всеми талантами должно быть - скорость передвижения снижается на 50%, а время между атаками увеличивается на 25%

Ожидаемый результат — то, чего вы ожидали при выполнении ваших действий. Процесс правильной работы
со всеми талантами должно быть - скорость передвижения снижается на 50%

**Покрайней мере это написано в бафе противника**

Тоже самое с конусом холода http://db.logon3.com/?search=конус+холода
вместо 70% замедляет на 50%

Ледяная стрела http://db.logon3.com/?search=ледяная+стрела
вместо 60% замедляет на 40%

Стрела ледяного огня http://db.logon3.com/?search=Стрела+ледяного+огня
вместо 60% замедляет на 40%

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by gmOverfire** [comment]
Проверяйте по факту, а не по тому, что написано в тултипе.
