### ISSUE TITLE
[Задание] ID 24645 - Конец Королевской компании 

### ISSUE THREAD

**Issue by dlkjfalkf** [VirginTeam/WotlkCore#729]
нет квеста - Конец Королевской компании 
 http://db.logon3.com/?quest=24645#criteria-of

**Что работает не так?**
после выполнения квеста Разговор по душам... http://db.logon3.com/?quest=24576 не появился квест - Конец Королевской компании  http://db.logon3.com/?quest=24645#criteria-of
который нужен для получения достижения http://db.logon3.com/?achievement=1695 Опасная любовь

Фактический результат — тот, который вы наблюдаете 

Не появился квест Конец Королевской компании 

**Как должно работать?**

после сдачи квеста Разговор по душам...  должен появится квест Конец Королевской компании

Ожидаемый результат — то, чего вы ожидали при выполнении ваших действий. Процесс правильной работы
после сдачи квеста Разговор по душам...  должен появится квест Конец Королевской компании
**Шаги для воспроизведения ошибки:**
1. фикисте баг
2. люди смогут брать квест
3, все счастливы

**Текущее обновление ядра:**
Build 187 2018-01-24 12:42:58 +0400

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by dlkjfalkf** [comment]
какое еще оформление? все же написал

**Comment by Kodekc** [comment]
Пожалуйста, начните со стартовой страницы багтрекера: https://github.com/VirginTeam/WotlkCore
Прочитайте особенно информацию про заголовки, благодарю за потраченное время, мы обязательно рассмотрим ваш репорт.

**Comment by dlkjfalkf** [comment]
квест доступен, ачива получена, можно удалять
