### ISSUE TITLE
[Задание] ID 13086 - Последний рубеж

### ISSUE THREAD

**Issue by Razama1234** [VirginTeam/WotlkCore#73]
**Описание:**

Квест работает некорректно.

**Что работает не так?**

Когда садишься на пушку все мобы на поле боя исчезают. В итоге приходится делать всё вручную.

**Как должно работать?**

Садишься за пушку, расстреливаешь 100 пауков и 3 дракона, сдаёшь квест.
[Видео.](https://www.youtube.com/watch?v=4zucBTj8-Pw)

**Шаги для воспроизведения ошибки:**

1. Взять квест.
2. Сесть за пушку.
3. Слезть с неё, мобы появляются, пушка исчезает.

**Текущее обновление ядра:**

Build 151 2017-04-03 15:25:08 +0400

**Comment by Rorshah** [comment]
Вообще пушек не вижу при взятом задании.
Серверу был уже 1 день без перезапуска. Может они убиваются...
или кто-то на них катается..

**Comment by Scoren** [comment]
Trinity работает частично, урон от пушки по драконам не проходит, они не вводятся в бой.

**Comment by Rorshah** [comment]
Сразу после перезапуска сервера полетел туда - работает отлично. Стреляет попадает убивает. Задание сделал за 5 минут. Еще раз. Проблема в том что пушки убиваются или кем-то перебегают на другое место.

**Comment by ar4i2018** [comment]
Квест вообще чинить собираются?

**Comment by Riazarre** [comment]
Преквест выполняется в фазе 2. Этот квест проходит в фазе 64. После выполнения квеста, игрок и пушка в которой он сидит переходят в фазу 1. После сдачи квеста, игрок переходит в фазу 128. 
Соответственно, новый игрок, взявший квест - не видит пушек, т.к. они в другой фазе.
Пушки не должны менять фазу, и должны оставаться в фазе 64. Это касается и постаментов, на которых пушка стоит.

**Comment by dlkjfalkf** [comment]
при посадки на пушку не видно мобов которых надо убить для цели задания
при вылете чуть дальше мобов видно, но проподает пушка

**Comment by gmOverfire** [comment]
Ну да, это описано в предыдущем комментарии :)

**Comment by gmOverfire** [comment]
+ баг, если сесть в пушку, она стреляет "под себя", хотя снаряд визуально улетает по направлению указателя выстрела. Лечится небольшим перемещением пушки ближе к краю постамента, но из-за этого зависает клиент игры у всех в зоне видимости.

**Comment by djex777** [comment]
Квест реально выполнить только вручную.

**Comment by MiceRus** [comment]
Ну и когда уже квест заработает?
Как вернуть перса в нефазированный мир, чтобы остальные НПЦ были видны?

**Comment by Kodekc** [comment]
Проблемы с видимостью понятны, пока не решаемы, надо будет портировать некоторые изменения с trinity, которые позволяют индивидуально задавать дальность прорисовки NPC/объектов, эта система у них появилась недавно, как раз для подобных ситуаций.

**Comment by ForesterDev** [comment]
Репорт в настоящее время актуален? Протестил - вроде все работает

**Comment by Rorshah** [comment]
Последний раз этой весной делал.
Некоторые драконы недосягаемы. Буквально парочка (самый правый и по дороге который)
идут в зачет.
Но в целом сделал без нервов, пушкой, а не вручную как раньше.
