### ISSUE TITLE
[quest] Приказы для Чёрного рыцаря ID 13663

### ISSUE THREAD

**Issue by Umkaod** [VirginTeam/WotlkCore#733]
05.02.2018

Ссылки и комментарии:

[quest] Приказы для Чёрного рыцаря ID 13663 (http://ru.wowhead.com/quest=13663)
[npc] Грифон Черного рыцаря (http://ru.wowhead.com/npc=33513#english-comments)

Что работает не так?

   Выше указанный npc (грифон) не долетает до предполагаемого места - грифон пропадает и Игрок (Пользователь) начинает падать и ударившись об скалы умирает.
   Не засчитывается подпункт квеста "Грифон Чёрного рыцаря подчинён"; как следствие, не имеется возможным выполнить весь квест. 

Как должно работать?

   Грифон с Пользователем должны долететь до предполагаемого места и должен засчитаться подпункт "Грифон Чёрного рыцаря подчинён" данного квеста.

Шаги для воспроизведения ошибки:

1) Взять квест "Приказы для Чёрного рыцаря" (+ дают предмет "Волшебная уздечка");
2) Заюзать предмет "Волшебная уздечка" на npc "Грифон Черного рыцаря";
3) Далее грифон начнёт самостоятельно перемещать Игрока (Пользователя) и в момент его перелёта с материка на нужный остров он пропадает и Игрок падает.

Текущее обновление ядра:

logon 3 (WoWLK 3.3.5a // x1 PvE)
#39 Build - 169 // Kodekc, 06.11.2017 14:30

**Comment by gmOverfire** [comment]
Отключите ауру скорости, если вы паладин, смените спек, если вы вкачали в талантах ускорение передвижения верхом.
Квест работает.
