### ISSUE TITLE
[NPC] ID 39066 - Инспектор Кромс Гвоздезуб

### ISSUE THREAD

**Issue by Apkazox** [VirginTeam/WotlkCore#735]
**Ссылки и комментарии:**
Инспектор Кромс Гвоздезуб - http://db.logon3.com/?npc=38066

**Что работает не так?**
После выполнения задания [Разговор по душам] - http://db.logon3.com/?quest=24657
NPC выдаёт финальный квест только в одном варианте, для 71-80.
[Конец Королевской компании] - http://db.logon3.com/?quest=24666
Персонажи 5-70 уровня остаются без дейлика и достижения 
[Опасная любовь] - http://db.logon3.com/?achievement=1695
Не проверялось для Орды.

**Как должно работать?**
Идеальный вариант
После выполнения задания [Разговор по душам] - http://db.logon3.com/?quest=24657
NPC выдаёт финальный вариант квеста в зависимости от уровня персонажа.
[Конец Королевской компании]
Требуется уровень: 5   - http://db.logon3.com/?quest=24658
Требуется уровень: 14 - http://db.logon3.com/?quest=24659
Требуется уровень: 23 - http://db.logon3.com/?quest=24660
Требуется уровень: 32 - http://db.logon3.com/?quest=24662
Требуется уровень: 41 - http://db.logon3.com/?quest=24663
Требуется уровень: 51 - http://db.logon3.com/?quest=24664
Требуется уровень: 61 - http://db.logon3.com/?quest=24665
Требуется уровень: 71 - http://db.logon3.com/?quest=24666

Простой вариант
Заменить текущий квест
Требуется уровень: 71 - http://db.logon3.com/?quest=24666
на 
Требуется уровень: 5   - http://db.logon3.com/?quest=24658

**Шаги для воспроизведения ошибки:**
1. Создал гнома.
2. Получил 6 уровень.
3. Взял начало цепочки в Стальгорне:
NPC - Младший инспектор - http://db.logon3.com/?npc=38293
Стартовый квест - Необычные ароматы - http://db.logon3.com/?quest=24804
4. Очередность квестов в цепочке, выполняем всю:
Необычные ароматы - http://db.logon3.com/?quest=24804
Дышать нечем! - http://db.logon3.com/?quest=24655
Позаимствовать духи - http://db.logon3.com/?quest=24656
Фейерверки в "Позолоченной розе" - http://db.logon3.com/?quest=24848
По горячим следам - http://db.logon3.com/?quest=24849
Разговор по душам... - http://db.logon3.com/?quest=24657
5. После сдачи
квеста Разговор по душам... - http://db.logon3.com/?quest=24657
NPC Инспектор Кромс Гвоздезуб - http://db.logon3.com/?npc=38066 
выдает диалоговое окно с текстом 
"Не нравится мне эта "Королевская химическая компания"... совсем не нравится." 
И мы не видим ни один из вариантов задания [Конец Королевской компании], которые я уже пережевал в этом посте.

**Текущее обновление ядра:**
Build 188 2018-02-05 15:05:15 +0400

P.S.: проще оформить документы на квартиру, чем тут правильный баг-репорт.

**Comment by Apkazox** [comment]
Что означает этот тег?

**Comment by gmKroshka** [comment]
Помоему, он однозначен-не воспроизводится ошибка, о которой Вы говорит)

**Comment by Apkazox** [comment]
Расщепил на атомы шаги для воспроизведения ошибки, уровни для теста 5-70.

**Comment by Kodekc** [comment]
Судя по тому, что я проверил, как это работает сейчас, после задания http://db.logon3.com/?quest=24657 становится доступным задание http://db.logon3.com/?quest=24792, это является неправильным?

**Comment by Apkazox** [comment]
http://db.logon3.com/?quest=24792
Требуется уровень: 78

я же писал весь репорт и проверку для персонажей 5-70 уровня, 71-80 всё работает.

**Comment by Kodekc** [comment]
Задания все у NPC есть, тут проблема в другом, в условиях их выдачи, я понимаю, что вы написали, но не понимаю последовательность указанную в базе данных.

**Comment by Apkazox** [comment]
Ну я тоже не программист, хотя репорт накатал (крестится левой рукой).
Условия в БД не указаны, только вариации с требованием уровня, думаю это уже больше к разработчикам.

Опять же, простой вариант:
Заменить текущий квест
Требуется уровень: 71 - http://db.logon3.com/?quest=24666
на
Требуется уровень: 5 - http://db.logon3.com/?quest=24658

Одна замена откроет доступ всем от 5 до 80 уровня, все счастливы, хоть и не близлайк.

**Comment by Kodekc** [comment]
Хочется сделать правильно, а не так, как проще. Мы либо делаем так, как должно работать, либо никак. Задания не будут заменены. Я выше написал, какие условия сейчас стоят у задания 24657

**Comment by Apkazox** [comment]
Первая цепочка квестов -> вариации дейликов [Конец Королевской компании].
Затем если вы имеете 78+ -> получаете дополнительную цепочку из двух квестов (http://db.logon3.com/?quest=24792 + http://db.logon3.com/?quest=14488) 
и в следующие дни http://db.logon3.com/?quest=14488 становиться еще одним дейликом (бонус только для 78+)

**Comment by Apkazox** [comment]
Я описал суть проблемы, необходимых вариант, накидал ссылок... Вы сами убедились в странности выдачи квеста. Какая еще информация требуется?

**Comment by Kodekc** [comment]
Информация о правильности цепочек заданий, это в целом пометка не только для вас, но и для нас, что у нас не хватает информации, чтоб проверить и сделать правильно.

**Comment by BrainTT** [comment]
на данный момент существует проблема у орды для 80лвл. не у всех, но есть и такие же как я. 
после выполнения кв http://db.logon3.com/?quest=24576, появляется http://db.logon3.com/?quest=24793, далее http://db.logon3.com/?quest=14488. после убийства химиков сдал кв. по идее должен был появиться кв http://db.logon3.com/?quest=24652. после которого полаешь достижение http://db.logon3.com/?achievement=1695. но ни на первый день, ни на второй, ни на третий он не появился. странно то, что некоторые персонажи могут получить достижение, а некоторые нет. на данный момент кв http://db.logon3.com/?quest=24652 до сих пор нету. достижение http://db.logon3.com/?achievement=1693 только изза него остается в подвешенном состоянии.

**Comment by Apkazox** [comment]
BrainTT, как говаривал один мой друг - легче год подождать, чем вовремя починят.

**Comment by BrainTT** [comment]
не очень оптимистично звучит. я уже даже все второстепенные ачивы запилил.

**Comment by Apkazox** [comment]
Можно ли расшарить db.logon3.com/?quest=24659 моему персу в вов с тем же ником?

**Comment by BrainTT** [comment]
Apkazox, вовхед говорит, что квестом нельзя поделиться и в игре тоже не получается. уже пробовал

**Comment by Kodekc** [comment]
Исправлено. Применено. Изменения вступят после рестарта сервера.

**Comment by Apkazox** [comment]
Ничего не изменилось.

**Comment by Kodekc** [comment]
Попробуйте на новом персонаже. Подозреваю, что проблема именно в этом, на локальной версии сервера, не наблюдаю проблему.

**Comment by Apkazox** [comment]
А старого на помойку? Расшарьте хотя бы раз квест, решите проблему в рамках перса.

**Comment by Kodekc** [comment]
Сперва нужно проверить эту теорию и если она подтвердиться, то будут применены другие изменения, которые разбагают старых персонажей.

**Comment by Apkazox** [comment]
На новых персонажах также нет изменений.

**Comment by BrainTT** [comment]
после вчерашнего рестарта появился кв http://db.logon3.com/?quest=24652 у ордынского нпс. Насколько я понял на брекет 51-60 лвл (я 80). После выполнения кв получил http://db.logon3.com/?achievement=1695 и закрыл эвент Любовная лихорадка. Спасибо за работу

**Comment by Apkazox** [comment]
BrainTT, линк на брекет 71-80, он и до рестарта работал для этих лвлов.

**Comment by BrainTT** [comment]
Apkazox, это альянс Apkazox. У нас в орде половина 80х лвлов не могли получить эту ачиву.

**Comment by Apkazox** [comment]
http://logon3.com/support/tickets.php?id=4799

**Comment by ForesterDev** [comment]
Проверьте после ребута сервера

**Comment by Apkazox** [comment]
12.02.18 
20:55 по серверу, ситуация с мобом та же.
Рестарт был примерно в 14:00 по серверу.
Build 189.

**Comment by Apkazox** [comment]
Утренный рестарт зарешал.
**Работает, сворачиваем лавочку.**
