### ISSUE TITLE
Задание quest=13369 Против воли рока

### ISSUE THREAD

**Issue by Rorshah** [VirginTeam/WotlkCore#742]
http://db.logon3.com/?quest=13369

**Что работает не так?**

Портануло в огри и меня там охрана замесила я даже проявиться не успел.
Это была не драка. Это было расщепление.

**Как должно работать?**

https://www.youtube.com/watch?v=yXnAZZC6OTU
Должно портануть в огри, но там какая-то параллельная реальность.
Добрый Тралл и охрана. Сдаешь там задание, все дела.

**Шаги для воспроизведения ошибки:**

1. Взять задание
2. Попросить Джайну сорганизовать портал в Огри
3. Жамкнуть на портал и умереть

**Текущее обновление ядра:**

Build 188

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by Kodekc** [comment]
https://github.com/VirginTeam/WotlkCore/issues/50
