### ISSUE TITLE
[NPC] ID 37675 - Специалист по связям с общественностью

### ISSUE THREAD

**Issue by Apkazox** [VirginTeam/WotlkCore#743]
**Ссылки и комментарии:**
Специалист по связям с общественностью <Королевская химическая компания> - http://db.logon3.com/?npc=37675

**Что работает не так?**
(почти пол ивента работает не так...)
Данная непись выдавала http://db.logon3.com/?quest=24629
первый раз - начале ивента, второй раз - при обновлении билда.
Нет выбора дейликов, нет самих дейликов каждый день.
Кэш чистил, тоже самое. Многие писали про бред после 18:00, проверил, квестов также не было

**Как должно работать?**
Моб должен выдавать один из трех квестов
рандомно и каждый день
Квесты:
http://db.logon3.com/?quest=24629
http://db.logon3.com/?quest=24635
http://db.logon3.com/?quest=24636

**Шаги для воспроизведения ошибки:**
Врядли вы это воспроизведете, опрос игроков показал что поломка у всех.
1. Надо было зайти на начало ивента, сдать квест.
2. После обновления сервера моб опять выдал квест, тот же самый
3. В остальные дни он стоит с окном текста.

**Текущее обновление ядра:**
Build 188 2018-02-05 15:05:15 +0400

P.S. От таких "милых" поломок люди не станут больше донатить на ивент товары, просто портит впечатление.

**Comment by Kodekc** [comment]
Исправлено. Применено, заработает после рестарта сервера.

**Comment by Apkazox** [comment]
Проблема была в том, что квест появлялся 1 раз на рестарт. Ну поживем, увидим.

**Comment by Apkazox** [comment]
Работает, луцк вам.
