### ISSUE TITLE
[Группа объектов] - Школы тайной магии

### ISSUE THREAD

**Issue by Apkazox** [VirginTeam/WotlkCore#744]
**Ссылки и комментарии:**
Группа из объектов в восьми точках спавна:
Школы тайной магии – **Введение** (http://db.logon3.com/?object=192708)
Школы тайной магии – **Отречение** (http://db.logon3.com/?object=192709)
Школы тайной магии – **Сотворение** (http://db.logon3.com/?object=192710)
Школы тайной магии – **Предсказание** (http://db.logon3.com/?object=192711)
Школы тайной магии – **Чаротворство** (http://db.logon3.com/?object=192713)
Школы тайной магии – **Иллюзия** (http://db.logon3.com/?object=192865)
Школы тайной магии – **Некромантия** (http://db.logon3.com/?object=192866)
Школы тайной магии – **Трансмутация** (http://db.logon3.com/?object=192867)
а также все побочные книги на тех же точках.

**Что работает не так?**
Обновляет все точки только после рестарта сервера. Не исчезают книги, не относящиеся к ачивке.

**Как должно работать?**
Респавн рандомной новой книги в точке спустя 3 часа после прочтения текущей.
Рестарт сервера обновляет все точки.
Хлам-книги также исчезают после прочтения.

**Шаги для воспроизведения ошибки:**
1. Подождать 3 часа.
2. Подождать N\A часов.
3. Сравнить результаты спавна сразу же после рестарта.

**Текущее обновление ядра:**
Build 189 2018-02-09 13:59:40 +400

**P.S.: Само достижение не трогайте, оно работает! (для мазохистов или рестарт-ботов)** 
**[Ученье – свет!]** - http://db.logon3.com/?achievement=1956

**Comment by sega693** [comment]
https://github.com/VirginTeam/WotlkCore/issues/176 давно висит про них, но без ссылок

**Comment by Kodekc** [comment]
Старую закрыл, это более точный репорт.

**Comment by Apkazox** [comment]
sega693, само достижение работает, если сидеть над каждой точкой и ждать рестарта... Но это лютый бред.

**Comment by VirginGuard** [comment]
Реализован корректный деспавн книжек по достижению Ученье - свет. Теперь после первого прочтения книга будет исчезать в течение 3 минут, затем появляться случайная в течение 3 часов
