### ISSUE TITLE
[Игровая механика] БГ 10-19

### ISSUE THREAD

**Issue by Apkazox** [VirginTeam/WotlkCore#745]
**Ссылки и комментарии:**
До сих пор 10-19 неизменен даже на офе.

**Что работает не так?**
10-18, 19
Брекет почти вымер, 10-18 иногда еще пытаеться вздохнуть, 19 лежит в ожидании реса.

**Как должно работать?**
10-19 Варсонг.
(Арати, Око как бонус контент, хотя никто 8 на 8 не собирал еще.)

**Шаги для воспроизведения ошибки:**
Нет никаких шагов. 
Просто идея с разделением уровней нелепа для такого онлайна.
(Давайте сделаем еще брекет на каждый лвл! 10-10, 11-11... Восемьдесят видов бг!)
Из новинок вы бы могли просто оставить новые карты под минимал рег 5х5, но вернуть лвл брекет.

**Текущее обновление ядра:**
Build 189, поломка в самой идее.

**Надеюсь твинки 10-19 в комментариях ниже плюсанут за возврат, в ваших же интересах вернуть к жизни мёртвых персов!**

**Comment by kalipsa988** [comment]
во первых не для баг-трекера
во вторых на форуме тема есть
в третьих в дискорде канал #feedback

**Comment by Apkazox** [comment]
создать 3-4 канала и жонглировать запросами, циркл ван лав

**Comment by Senatyan** [comment]
Автор не путай как было и есть на оффе.
Раньше на оффе было, если память не изменяет 10-15, 16-19 и т.д.
Сейчас можно регнуть 10 лвл и получишь временный ап до 19 и ср. хп дамаг.  то есть ты наравне со всеми практически разница маленькая. Не будет как в Личе 19 парни фармят 10 ребят

**Comment by kalipsa988** [comment]
http://forum.wowcircle.com/showthread.php?t=757695 вот вам тема, там обсуждайте
