### ISSUE TITLE
[Заклинание] ID 30533 - Портал Бездны

### ISSUE THREAD

**Issue by olegklim1991** [VirginTeam/WotlkCore#746]
**Ссылки и комментарии:**

http://ru.wowhead.com/spell=30533

**Что работает не так?**

Бегают темные круги за игроками(сам портал)

**Как должно работать?**

Должны появляться и оставаться на месте.Не должны бегать за игроками.

Открытие массивных врат Бездны, которые держатся 6 sec. и раз в 2 сек. наносят 1053 to 1287 ед. урона от темной магии всем противникам в выбранной области.
--

**Шаги для воспроизведения ошибки:**

1. Спулить босса
2. Подождать когда появится круги
3. увидить что они бегают за игроком

**Текущее обновление ядра:**

 х1 PvE WoTlk Build 189

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by ForesterDev** [comment]
Дайте больше информации - на каком боссе, когда эта способность используется

**Comment by olegklim1991** [comment]
аркатрац 1 босс

**Comment by Thirdbearr** [comment]
http://wowroad.info/?quest=13369 
![wowscrnshot_031318_214725](https://user-images.githubusercontent.com/37348481/37366440-1cccc794-2709-11e8-9a7f-77db581865d8.jpg)
После телепортации все мобы (включая босса) начинают бить моего персонажа. 
Как должно быть - https://www.youtube.com/watch?v=yXnAZZC6OTU.

**Comment by olegklim1991** [comment]
парень удали этот комментарий,не туда добавил не порти мою тему

**Comment by Thirdbearr** [comment]
olegklim1991, я не шарю. А куда добавлять?

**Comment by olegklim1991** [comment]
https://github.com/VirginTeam/WotlkCore/issues вот ссылка,нажимай зеленую кнопку и добавляй

**Comment by ForesterDev** [comment]
Исправлено, будет применено в обновлении)

**Comment by olegklim1991** [comment]
спасибо,еще б шарики с молниями убрали было б гуд
