### ISSUE TITLE
[NPC] ID 35507 - Чаротворец Исиан

### ISSUE THREAD

**Issue by Holyway** [VirginTeam/WotlkCore#748]
**Ссылки и комментарии:**

http://db.logon3.com/?npc=35507

**Что работает не так?**

НПС могут атаковать игроки орды

**Как должно работать?**

НПС должен быть не доступен для атаки ордынцам

**Шаги для воспроизведения ошибки:**

1. Приникнуть ордынским персонажем к НПС(например используя флаймаунта)
2. Убить НПС

**Текущее обновление ядра:**

Build 189 2018-02-09

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by Kodekc** [comment]
Исправлено. Изменения будут применены в ближайшем обновлении
