### ISSUE TITLE
[Задание] ID 13305 - Все к худшему

### ISSUE THREAD

**Issue by lambazta** [VirginTeam/WotlkCore#750]
http://db.logon3.com/?quest=13305

Невозможно взять задание т. к. в данной точке отсутсвует НПС Матиас Нетлер http://db.logon3.com/?npc=32408

Обе предыдущие цепочки выполнены

1. Прилететь на место
2. Увидеть собранный разрушитель, рядом с который должен стоять НПС
3. НПС нет на месте

Build 189 2018-02-09 13:59:40 +0400

Ник персонажа Flatiron

**Comment by Kodekc** [comment]
NPC находится в определённой фазе, скорей всего проблемы с фазированием, по этому вы его не видите и считаете, что его нет.
Требуется изучение баг репорта для выявления ошибки.

**Comment by MiceRus** [comment]
Когда уже исправят-то? А то застопорилось продвижение по цепочке

**Comment by Kodekc** [comment]
https://github.com/VirginTeam/WotlkCore/issues/255
