### ISSUE TITLE
[Игровая механика] Собирательные профессии

### ISSUE THREAD

**Issue by kalipsa988** [VirginTeam/WotlkCore#752]
**Ссылки и комментарии:**

http://wowwiki.wikia.com/wiki/Patch_3.1.0 (англ версия)
http://ru.wow.wikia.com/wiki/%D0%9E%D0%B1%D0%BD%D0%BE%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5_3.1.0 (рус версия)
Собирательские навыки
У способностей "Крепость", "Знаток анатомии" и "Кровь земли" теперь есть требования к уровню игрока в зависимости от степени владения соответствующим навыком: ученик (1), подмастерье (1), умелец (10), искусник (25), мастер (40), великий мастер (55).
При добыче руды, собирании трав и снятии шкур больше не бывает неудачных попыток.

**Что работает не так?**

При добыче руды, собирании трав и снятии шкур иногда есть неудачные попытки

**Как должно работать?**

При добыче руды, собирании трав и снятии шкур больше не бывает неудачных попыток.

**Шаги для воспроизведения ошибки:**

1. Взять травничество/горку
2. Найти залежи/траву
3. Собирать

**Текущее обновление ядра:**

Последнее обновление ядра 18.02.2018

**Comment by Kodekc** [comment]
Исправлялось же 15.12.2017

**Comment by kalipsa988** [comment]
Я тоже думал так, но при прокачке травы и горки неудачи были довольно часто

**Comment by kalipsa988** [comment]
Вчера вот видел, когда горку качал

**Comment by kalipsa988** [comment]
https://www.youtube.com/watch?v=toCaRg7e6Cg&feature=youtu.be
https://www.youtube.com/watch?v=mFsJhEUpfH4&feature=youtu.be
Записал сегодня

**Comment by ForesterDev** [comment]
Проверьте еще после обновления
