### ISSUE TITLE
[Задание] ID 12692 - Возвращение охотника на личей

### ISSUE THREAD

**Issue by lishker** [VirginTeam/WotlkCore#755]
**Ссылки и комментарии:**
http://wowroad.info/?npc=28659
http://wowroad.info/?npc=28668
http://wowroad.info/?npc=28667
http://wowroad.info/?quest=12692

**Что работает не так?**
убиваю Артруиса и собака на дает квест к ним в деревню
Фактический результат — тот, который вы наблюдаете 

**Как должно работать?**
опускаю хп Артруиса Бессердечнго до определенного значения. и на меня агрятся два моба Зепик Охотник на Горлоков и Джалут. убиваю джалута и  бреру квест у Зепик Охотник на Горлоков Возвращение охотника на личей

**Шаги для воспроизведения ошибки:**

1. Убил Джалута
2. Убиваю Артруиса Бессердечнго
3. Беру квест у Зепик Охотник на Горлоков

**Текущее обновление ядра:**
Build 189 2018-02-19

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by lishker** [comment]
квесты все сделаны у оракулов. и репутация превознесение.

**Comment by Ewropa** [comment]
после убийства Артруиса Бессердечного должен вначале Вам дать http://db.logon3.com/?quest=12582, а лишь затем задание http://wowroad.info/?quest=12692

**Comment by lishker** [comment]
и его нету вообще квестов нет

**Comment by lishker** [comment]
ни у одного ни у дрогого 3 дня проверял

**Comment by Ewropa** [comment]
надо смотреть, примерную проблему знаю, нужно теперь время

**Comment by lishker** [comment]
??

**Comment by lishker** [comment]
время на что? можно по конкретнее??

**Comment by odino4estvo** [comment]
У меня была та самая ситуация, отписался в центр поддержку, я проходил проверку вместе с гм'ом, а через какое-то время мне прописали квест в квестлист. когда я был в игре, так что, мой совет, сразу обратись в ЦП! Удачи!

**Comment by lishker** [comment]
ссылку дашь?

**Comment by odino4estvo** [comment]
Да, пожалуйста!
[http://logon3.com/support/](url)

**Comment by gmOverfire** [comment]
Проблема была исправлена, проверяйте после обновления.
Если у кого то она повторится, убедитесь, что у Вас выполнены все преквесты (смотреть тут http://ru.wowhead.com/quest=12654#comments:id=1066787) и оформите заявку в центре поддержки: http://logon3.com/support/
