### ISSUE TITLE
НПЦ - Айс Вентурон

### ISSUE THREAD

**Issue by Eneyra** [VirginTeam/WotlkCore#756]
**Ссылки и комментарии:**

http://db.logon3.com/?npc=10776
http://db.logon3.com/?npc=10430

**Что работает не так?**

При снятии шкуры со Зверя (http://db.logon3.com/?npc=10430) ничего не происходит

**Как должно работать?**

При снятии шкуры со Зверя должен появляться НПЦ http://db.logon3.com/?npc=10776 и давать квест

**Шаги для воспроизведения ошибки:**

1. Сходить в УБРС
2. Обшкурить босса
3. Ничего не произойдет

**191:**

Можно посмотреть в игре, введите в чат команду .server info и скопировать строку начиная с Build с номером и датой. Не забывайте указывать, Live Server или PTR Server, где проводилось тестирование.

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by Kodekc** [comment]
https://github.com/VirginTeam/WotlkCore/issues/305
