### ISSUE TITLE
[Задание] ID 11066 - Нам нужно больше летучих скатов!

### ISSUE THREAD

**Issue by Awegod** [VirginTeam/WotlkCore#757]
http://ru.wowhead.com/quest=11066

Что работает не так?
 Скаты цепляются, доводятся до НПС и в момент когда исчезают, должно засчитывать. Но они просто исчезают без следа.

Как должно работать.
Скаты цепляются, доводятся до НПС и в момент когда исчезают, должно засчитывать.

Последнее обновление.
Build 191 2018-02-20

**Comment by gmKroshka** [comment]
Взаимосвязано
https://github.com/VirginTeam/WotlkCore/issues/314
