### ISSUE TITLE
Проседание по мане, у многих персов!

### ISSUE THREAD

**Issue by Aelita-wizard** [VirginTeam/WotlkCore#758]
**Ссылки и комментарии:**

Проседание по мане, у многих персов!
Проверено на персе Aelita. Сервер logon3 WoW Circle 3.3.5a x1

**Что работает не так?**

Проблема с жестким проседанием по мане у мага, опрос в олл чате показал что у палов, шамов, жрецов, друидов... то же самое. 
Последняя проверка 22.02.18
Началось после падения сервера в выходные, а  именно 18.02.18
В инстах мана высаживается в ноль ОЧЕНЬ быстро и никакие приблуды не спасают

**Как должно работать?**

Мана падает в разы быстрее чем должна. Должна не улетать так быстро.

**Шаги для воспроизведения ошибки:**

1. Взять мага 
2. Пойти бить мобов
3. Афигеть что от 10 слабых сереньких мобов у 80-ника упала мана в ноль.

**Текущее обновление ядра:**

Build 192 2018-02-22 11:56:19 +0400
Сервер logon3 WoW Circle 3.3.5a x1

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by Kodekc** [comment]
Не информативно

**Comment by Aelita-wizard** [comment]
Я не знаю как правильно оформить ,чтобы было информативно. И почитала и
видео посмотрела. Помогите, пожалуйста, ведь есть проблема, а я даже не
знаю как правильно написать чтобы вам о ней сообщить.

2018-02-22 12:54 GMT+02:00 Kodekc <notifications@github.com>:

**Comment by Kodekc** [comment]
Чтоб понять суть проблемы, требуются какие-то факты, какие-то данные, чтоб ими оперировать. Проседаю по мане, это не информативно.

**Comment by Aelita-wizard** [comment]
Так подойдёт?
Место действия:
Континет Восточные Королевства
Игровая зона: Альтеракские горы
Конкретно: Уступ Коррана и Возвышенность Соферы
Кто: Уровень 80, Класс Маг, GS 5992, уровень маны 24393.  Без бафов.
Противник: Уровень 33, Вор, Волшебник, Приступник Синдиката, Общее
количество 33 штуки
Время 22.02.18: 13.20 - 13.24
Использованые заклинания:
Живая бомба, уровень 3 - 33 раза
Огненный взрыв уровень 11 - 3 раза
Чародеский взрыв уровень 11 - 4 раза
Скачок - 4 раза
Остаток маны 262


22 февраля 2018 г., 13:03 пользователь Kodekc <notifications@github.com>
написал:

**Comment by Aelita-wizard** [comment]
Восполнение маны 326 в покое, 163 в действии

22 февраля 2018 г., 13:27 пользователь Яна Яна <yavaeva.ya@gmail.com>
написал:

**Comment by Apkazox** [comment]
Попробуй убить десяток мобов, кинуть сюда рекаунт, расписать ссылками с базы данных спеллы и их стоимость, после доказать что остаток меньше положенного. Не думаю что тебе тут верха пояснят за оформление пруфов.

**Comment by gmOverfire** [comment]
Нужно подтверждение актуальности, или репорт будет закрыт.

**Comment by Aelita-wizard** [comment]
Актуально

26 февр. 2018 г. 9:08 ДП пользователь "Overfire" <notifications@github.com>
написал:

**Comment by gmOverfire** [comment]
Это не подтверждение актуальности, где пруфы?

**Comment by gmOverfire** [comment]
За 2 дня нет никакой информации, подтвержающей наличие бага.
Автору, рекомендую изучить материалы этого раздела форума: http://forum.wowcircle.com/forumdisplay.php?f=487
