### ISSUE TITLE
[Подземелье] Глубины Черной горы - (ID 9156 Посол Огнехлыст)

### ISSUE THREAD

**Issue by gmRial** [VirginTeam/WotlkCore#76]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Некорректная работа босса

**Что работает не так?**

Неправильный призыв существ http://ru.wowhead.com/npc=9178, адды появляются из ниоткуда рядом с боссом.

**Как должно работать?**

Вокруг площадки, где стоит босс, есть руны. `Doodad_DarkIronDwarfRune_x01`
Перед появлением аддов, руны загораются, появляются адды - и бегут к боссу.
https://youtu.be/3mIkmIdpEW4?t=214
После убийства босса руны должны "вспыхнуть"

**Текущее обновление ядра:**

PTR: Build 20 2017-04-05 12:06:47 +0400

**Comment by ForesterDev** [comment]
Исправлено, будет применено в обновлении
