### ISSUE TITLE
аркан маг проблема с заклинанием

### ISSUE THREAD

**Issue by foars92** [VirginTeam/WotlkCore#760]
**Ссылки и комментарии:**

Чародейские стрелы    http://db.logon3.com/?spell=42846
пример на видео - https://www.youtube.com/watch?time_continue=1&v=74pjRvE00Wc
x1 3.3.5 lk 
ник - graylife

**Что работает не так?**

Во время каста при нажатии заклинания чародейские стрелы заклинание уходит в кд

**Как должно работать?**

до завершения каста ничего  не должно происходить

**Шаги для воспроизведения ошибки:**

1. Кастуем Чародейская вспышка
2. Во время каста жмем Чародейские стрелы

**Текущее обновление ядра:**

Build 192 2018-02-22 

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by foars92** [comment]
пример на видео - https://www.youtube.com/watch?time_continue=1&v=74pjRvE00Wc

**Comment by gmOverfire** [comment]
Воспроизвести не удается, скорее всего дело в вашем клиенте/аддонах.

**Comment by foars92** [comment]
С этим клиентом и с этими аддонами на тестовом сервере проблемы нету, проблема только на этом персонаже.
(На x100 тоже проблемы нету с этим клиентом и с этими аддонами)
