### ISSUE TITLE
[Задание] ID 13110 - Неупокоенные

### ISSUE THREAD

**Issue by Ronelown** [VirginTeam/WotlkCore#762]
**Ссылки и комментарии:**

http://db.logon3.com/?quest=13110 Неупокоенные

**Что работает не так?**

У меня у одного на сервере не работает данный квест. Души не окрапляются(Юзаю квест итем, и ничего). Данный квест является одним из цепочки на "Вершину Рыцарей" но цепочка у меня сделана а квест выпал, делал давно в 2013 году. (Превый раз заметил неисправность 13.10.2017 не доходили руки написать

**Как должно работать?**

При окраплении трупов должно засчитывать окропление.

**Шаги для воспроизведения ошибки:**

1. Взять квест
2. Окропить Тела
3. Увидеть что все работает
4. Проверял на 7 персонажах, спрашивал в олчате. Не работает только у меня
P.S. Будьте добры не оставьте без внимания могу при ГМе показать что не так!

**Текущее обновление ядра:**

Build 192 2018-02-22

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by gmOverfire** [comment]
Задание работает, проблема у конкретного персонажа.
