### ISSUE TITLE
[Задание] ID 12581 - Бремя героя

### ISSUE THREAD

**Issue by Ronelown** [VirginTeam/WotlkCore#763]
**Ссылки и комментарии:**

Добавьте ссылки с wowhead.com или db.logon3.com на проблемные задания, NPC, заклинания и т.д. 

**Что работает не так?**
Мульд не дает данный квест. 2м персонажам с аккаунта дал, 3м другим не дает, квесты прервал в 2015.

**Как должно работать?**
При вызови Мульда должен давать квест "Бремя героя"!
**Шаги для воспроизведения ошибки:**

1. Взять мяч мульда
2. Вызвать мульда
3. Увидеть что квеста нету

**Текущее обновление ядра:**

Build 192 2018-02-22

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by gmOverfire** [comment]
Проверяйте после обновления сервера.
