### ISSUE TITLE
[Заклинание] ID 70546 - Ловушка призраков ЦЛК

### ISSUE THREAD

**Issue by zyxellgit** [VirginTeam/WotlkCore#765]
**Ссылки и комментарии:**
http://db.logon3.com/?spell=70546 Ловушка призраков или  ловушка перед большими скелетами и в коридорах чумодельни в ЦЛК

**Что работает не так?**

Разбойники видят ловушки, но не могут их обезвредить

**Как должно работать?**
Ловушки видны разбойникам и обезвреживаются http://db.logon3.com/?spell=1842 чтобы деактивировать вызов Заклятый страж http://db.logon3.com/?npc=37007

Build 192 2018-02-22 11:56:19 +0400

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by zyxellgit** [comment]
http://ru.wowhead.com/spell=70547#english-comments

**Comment by zyxellgit** [comment]
Cleptor 2009-12-21 (Обновление 3.3.0)

These traps can be disarmed from a much bigger distance than most other traps. I could disarm them almost as soon as they became visible to me. I disarmed these traps without any problems. Is was never even close to getting caught.

**Comment by ForesterDev** [comment]
Исправлено, будет применено в обновлении
