### ISSUE TITLE
[Игровая механика] Увеличенная скорость передвижения

### ISSUE THREAD

**Issue by zurokot** [VirginTeam/WotlkCore#766]
**Что работает не так?**

После выполнения миссии Око Акеруса персонаж начинает бегать как будто он использует спидхак, и после того как вы перемещаетесь в начальную локацию "Разлом смерти", этот баг **временно** пропадает, но после того как вы умираете и воскресли(возможно вы должны умереть и воскреснуть несколько раз) вы снова начинаете очень быстро бегать, и я считаю, что это неправильно т. к. все миссии проходятся на раз.

**Как должно работать?**

Ну после выполнения мисси вы должны бегать под баффом короля лича, но не так быстро как после выполнения данной миссии.

Ожидаемый результат — убрать этот баг. И разбанить игрока Сиранал от бана за читы, хотя данный игрок не использовал их, и в этом был виноват баг.

**Шаги для воспроизведения ошибки:**

1. Шаг один использовать око Акеруса
2. Шаг два не доходя то конечного пути , когда вы можете самостоятельно управлять оком ,выйти из ока

**Текущее обновление ядра:**

Неизвестно т. к. меня забанили из-за этого бага, формулируя это так, что я использовал читы. 

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by gmOverfire** [comment]
Удалось воспроизвести.
1. Взять задание http://db.logon3.com/?quest=12641
2. Использовать http://db.logon3.com/?object=191609
3. Дождаться, когда Око Акеруса полетит в Дольный Очаг и в чате появится надпись: `[10:05:40] Око Акеруса устремляется к цели.`
4. Использовать http://db.logon3.com/?spell=52694 на панели Ока (5 скилл).
5. Проверить скорость передвижения `[10:06:15] Speed: 35 yds/sec, 115.2 kph, 71.6 mph, 500% normal run speed`

**Comment by zurokot** [comment]
Так я не понимаю получилось ли у вас воспроизвести данный баг. Я скину видео как получилось у меня https://www.youtube.com/watch?v=oKcHcv4IVb8

**Comment by gmKroshka** [comment]
> Удалось воспроизвести.
кажется, чётко написано

**Comment by zurokot** [comment]
ой, сори ,с телефона писал. Не заметил

**Comment by ForesterDev** [comment]
Исправлено, будет применено в обновлении
