### ISSUE TITLE
[Задание] ID 8728 Хорошая новость и плохая новость

### ISSUE THREAD

**Issue by Bloodnoire** [VirginTeam/WotlkCore#768]
**Ссылки и комментарии:**

http://ru.wowhead.com/quest=8728

**Что работает не так?**

NPC Нарайн Причудень не дает квест Хорошая новость и плохая новость. Нет квеста в диалоговом окне.

**Как должно работать?**

Должен быть квест в диалоговом окне

**Шаги для воспроизведения ошибки:**

1. Получить квест
2. Собрать необходимые для задания предметы
3. Сдать квест

**Текущее обновление ядра:**

WoW Circle Wotlk Development 3.3.5a
WoW Circle Core: Last Update: 12.02.2018 Updetepack: 157 
WoW Circle DB: Last Update: 31.12.2017 Updetepack: 215 
Wotlk 3.3.5a x100 орда

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by gmKroshka** [comment]
Вы обратились не по адресу
Это баг-трекер Logon 3
Могу лишь немного помочь, информация по ссылке http://forum.wowcircle.com/showthread.php?t=761411&p=6367588&viewfull=1#post6367588
