### ISSUE TITLE
[Подземелье] Глубины Черной горы - (ID 9019 Император Дагран Тауриссан)

### ISSUE THREAD

**Issue by Rialzarre** [VirginTeam/WotlkCore#77]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Манекен

**Что работает не так?**

Босс не использует способности. Адды в комнате просто стоят.

**Как должно работать?**

Если есть живые адды в комнате с боссом - они должны бежать ему на помощь.
Босс должен использовать свою абилку http://ru.wowhead.com/spell=15636
https://youtu.be/3mIkmIdpEW4?t=484

**Текущее обновление ядра:**

PTR: Build 20 2017-04-05 12:06:47 +0400

**Comment by ForesterDev** [comment]
Абилку юзает https://snag.gy/kgfFyd.jpg
