### ISSUE TITLE
[NPC] ID 22037 - Кузнец Горлунк

### ISSUE THREAD

**Issue by dreaddy1488** [VirginTeam/WotlkCore#770]
**Ссылки и комментарии:**

NPC - http://ru.wowhead.com/npc=22037

**Что работает не так?**

С NPC Кузнец Горлунк нет лута.

**Как должно работать?**

С NPC Кузнец Горлунк должен быть лут.

**Шаги для воспроизведения ошибки:**

1. Прилететь в Долину Призрачной Луны.
2. Убить NPC Кузнец Горлунк.
3. Убедиться в том, что лута нет.

**Текущее обновление ядра:**

Build 192 2018-02-22 11:56:19 +0400

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by gmOverfire** [comment]
http://db.logon3.com/?npc=22037#drops

**Comment by dreaddy1488** [comment]
ну так форма и не падает

**Comment by Kodekc** [comment]
Есть ли какие-то особые условия дропа этих предметов?

**Comment by Senatyan** [comment]
Создал бдк. Одел и пошёл убивать кузнеца упал кв итем только.
![wowscrnshot_030418_021133](https://user-images.githubusercontent.com/35963582/36938825-9de6077e-1f51-11e8-8c6b-c6d70fe73bbd.jpg)
