### ISSUE TITLE
Квест 

### ISSUE THREAD

**Issue by Vendeeta** [VirginTeam/WotlkCore#772]
"Три властелина огня" ID8961
     
     

Ссылки и комментарии:

http://ru.wowhead.com/quest=8961
http://ru.wowhead.com/quest=9248#comments 
http://ru.wowhead.com/item=20404#comments ссылка на квест по репутации с Кругом Кенария тоже не здаётся лут "зашифрованный сумеречный текст"

**Что работает не так?**

выполняя цепочку квестов на сэт для роги "Сэт покрова тьмы" под конец я наткнулся на кв "Три властелина огня" убивл босса Пиростража Созерцателя Углей забрал с него лут по квесту " уголь углевзора", Убил босса Лорда Оплавителя забрал лут "Огневит оплавителя" и пошол в Силитус за 3им боссом Огорцогом тут я остановился на нем его чтобы вызвать требуется сэт сумеречного сектанта, я выбил с мобов этот сэт, но в добавок к сэту чтобы юзнуть камень нужна шея "Статусный медальон сумеречного сектанта" на форуме пишут что ее можно взять здав НПС Ауриэли Золотой лист большой сверкающий осколок и талисманы бездны, нашел эти все ингредиенты пошол здавать пишет что я не могу здать чтобы получить эту шею. У НПС висит совсем другой квест под названием "Скромный подарок" опять же этот кв нужно выполнять только по призыву этого же босса что и квест " Три властелина огня" я не знаю проверил все ссылки сайты гайды по выполнению этого квеста все проверил в игре, но никакого результата. 
**Как должно работать?**

Я не знаю как должен работать квест, но почините его пожалуйста

**Шаги для воспроизведения ошибки:**

1. Шаг один
2. Шаг два
3. Шаг три

**Текущее обновление ядра:**

Build 192 2018-02-22 11:56:19 +0400
[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by gmOverfire** [comment]
Изучите
http://db.logon3.com/?quest=8332
http://db.logon3.com/?quest=8323

И если действительно не работает, мы ждем верно оформленный репорт.

**Comment by Vendeeta** [comment]
спасибо все ракботает
