### ISSUE TITLE
[Задание] ID 8990 -  Еще одна важная составляющая заклинания

### ISSUE THREAD

**Issue by Vendeeta** [VirginTeam/WotlkCore#775]
Черная гора НПС Бодли

**Ссылки и комментарии:**

http://ru.wowhead.com/quest=8970#comments
http://ru.wowhead.com/quest=8985#english-comments
http://ru.wowhead.com/quest=8985 
http://ru.wowhead.com/item=22227

**Что работает не так?**

После здачи квеста "Я вижу в твоем будущем остров Алькац.."  у НПС Бодли в черной горе просто нет квеста он мне ничего не дал просто завершилась цепочка, а сэт "Покрова тьмы" я так и не получил до конца...

**Как должно работать?**

Вам лучше знать я не знаю как он должен работать

**Шаги для воспроизведения ошибки:**
Ошибок как таковых нет просто продолжения квеста нет.
1. Шаг один 
2. Шаг два
3. Шаг три

**Текущее обновление ядра:**

Build 192 2018-02-22 11:56:19 +0400 PVE X1

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by Vendeeta** [comment]
какое оформление как оформить правильно ссылки есть квеста нету сами посмотрите сэт так и не даделал хотя цепочка сложнее намного чем на киражского танка

**Comment by Kodekc** [comment]
Исправлено. Изменения будут применены в ближайшем обновлении

**Comment by tinuwiel** [comment]
Добрый день. У Вас тут указанно  VirginGuard added ✔ Исправлено and removed ✔ Ожидает применения labels 3 days ago. Но квест по прежнему недоступен, сегодня в 12 дня примерно проверяли. После сдачи квеста "Я вижу остров Алькац в твоем будущем" Бодли не дает никаких заданий.

**Comment by tinuwiel** [comment]
Пока что задание не доступно у Бодли. Проверяла в понедельник

**Comment by Amfinia** [comment]
Проверяли сегодня. Квеста нет.

**Comment by tinuwiel** [comment]
Вчера проверяли 5.04.18 пока нет

**Comment by zqk87** [comment]
13.04.2018 Не работает

**Comment by gmKroshka** [comment]
Репорт уже был открыт заново, дождитесь повторных правок

**Comment by Kodekc** [comment]
На текущем, 197 Build, ошибка сохраняется и задание не работает? Проверьте, пожалуйста.

**Comment by tinuwiel** [comment]
22.05.18 по прежнему актуально. никак не сделаем кв. и не начнем качаться дальше. поскорее бы уже)))

**Comment by tinuwiel** [comment]
4 месяца уже прошло, вы не в состоянии починить квестовую цепочку?!

**Comment by gmKroshka** [comment]
Может пройти еще 4х4 месяца, прежде чем разработчик рассмотрит проблему. Мы не устанавливаем сроки исправления, наберитесь терпения

**Comment by gmKroshka** [comment]
Будет исправлено после обновления
