### ISSUE TITLE
[NPC] ID 7382 - Рыжая полосатая кошка

### ISSUE THREAD

**Issue by Santaria94** [VirginTeam/WotlkCore#776]
**Ссылки и комментарии:**

http://db.logon3.com/?npc=7382

**Что работает не так?**

Выглядит совсем не рыжей полосатой, а черной монотонной, прям как бомбейская. 

**Как должно работать?**

Должна выглядеть рыжей полосатой, как-то так http://ru.wowhead.com/npc=7382
Кстати призываемый игроком спутник выглядит как надо, проблема только с кошкой, которая принадлежит Донни Антании
**Шаги для воспроизведения ошибки:**

1. Заглянуть в гости к http://db.logon3.com/?npc=6367
2. Не задавать вопросов, зачем ей топор.
3. Посмотреть на окрасы ее кошечек, которые шарохаются неподалеку и сравнить с их описанием в названии.

**Текущее обновление ядра:**

Билд 192

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by Kodekc** [comment]
Странный какой-то репорт, может просто модель в wotlk старая, а потом её заменили? Если это так, то с этим ничего поделать нельзя.

**Comment by Senatyan** [comment]
Я согласен с Кодекс. Вот старая 2007 года шакального качества картинка 
![43802- - -](https://user-images.githubusercontent.com/35963582/36934861-0f4c31e6-1f1a-11e8-847e-d33a00d3f0c2.jpg)
С учётом, что в БФА обновят многие модельки, то теперь стоит ориентироваться по старым скриншотам.

**Comment by Senatyan** [comment]
Репорт неверный, у автора 1. настройки графики на минимум 2 патчи 3. цветовая слепота
Раньше кошка была без усов, что подтверждает скриншот 2007 года с вовхеад
![wowscrnshot_030318_195606](https://user-images.githubusercontent.com/35963582/36935194-d6a8534c-1f1e-11e8-999e-81891214285a.jpg)
В 2012 скорее всего в Катаклизме ей добавили усы
![wowscrnshot_030318_200921](https://user-images.githubusercontent.com/35963582/36935221-490851c6-1f1f-11e8-95bd-5cb8c59ff306.jpg)

**Comment by Santaria94** [comment]
![wowscrnshot_030318_234611](https://user-images.githubusercontent.com/32459796/36937424-55739588-1f3d-11e8-8ae9-9f44edeae98b.jpg)
![wowscrnshot_030318_234556](https://user-images.githubusercontent.com/32459796/36937427-55b79d5a-1f3d-11e8-8fcc-6f368f576301.jpg)

Проблемный NPC, который находиться в игровом мире и его аналог-спутник, который призывается игроком. Патчи никакие не стоят, настройки на максималках.

**Comment by Kodekc** [comment]
Нашёл ошибку. Исправлено. Изменения будут применены в ближайшем обновлении
