### ISSUE TITLE
[Заклинание] ID 1454 - Жизнеотвод

### ISSUE THREAD

**Issue by Myrkur213** [VirginTeam/WotlkCore#779]
**Ссылки и комментарии:**

Жизнеотвод http://db.logon3.com/?spell=1454

**Что работает не так?**

Жизнеотвод потребляет абсурдное количество здоровья.

**Как должно работать?**

При использовнии должен тратить столько здоровья, сколько должен дать маны.

**Шаги для воспроизведения ошибки:**

1. Зайти на лока 6 уровня
2. Навести курсор на способность "Жизнеотвод"
3. Мрачно охуеть от жизни, обнаружив, что чтобы восполнить 27 маны, нужно потратить 78 хп. Это при том, что у тебя этого хп не полных две сотни.

Проблема, очевидно, в формуле.  При расчёте вычитаемого хп, к фиксированному значению прибавляется дух вместо спд. И так со всеми рангами. На хай лвле это не так заметно, но на на лоу пользоваться спелом крайне проблематично.

**Текущее обновление ядра:**

Build 192 2018-02-22

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by gmOverfire** [comment]
Будем рады получить подтвержденную формулу для этого заклинания времен 3.3.5a

**Comment by Myrkur213** [comment]
http://wowwiki.wikia.com/wiki/Life_Tap
Patch 3.3.3 (2010-03-23): This spell no longer scales with spirit, and instead scales with spell power.

**Comment by gmOverfire** [comment]
Допустим, что в формулу
> Преобразование [2000+Дух*1.5] ед. здоровья в [2000*1+СПД*.5*1] ед. маны. Сила заклинаний повышает количество получаемой маны.
вместо Дух подставим СПД, получится подобное: http://joxi.ru/xAeDPebfpG1kD2

**Comment by Myrkur213** [comment]
Согласен, глупо получается. Я не смог найти точную формулу, всё что у меня есть, это ссылка выше. Формула должна быть одинаковой для расчёта и хп и маны. Формула для расчёта маны должна быть использована для расчёта хп. Тогда всё встанет на свои места.

**Comment by Santaria94** [comment]
Пост от 2010-03-03 с www.mmo-champion.com
> Life Tap - Now converts [ 150% of Spirit + 1490 ] health into [1490 + Spell Power * 0.5 ] mana. (Old - [300% of Spirit + 1490] health into [1490 + Spirit * 3 Mana]
> 
> im not good at calculating thing, so please tell me if iam wrong!
> 
> is this a nerf? imo life tap needs a buff so this is strange for me imo!

https://www.mmo-champion.com/threads/699311-Life-tap-nerfs

**Comment by ForesterDev** [comment]
Тултип отображает верное количество забираемого хп. Формула сейчас верная
