### ISSUE TITLE
[Заклинание] Молниеносные рефлексы

### ISSUE THREAD

**Issue by Mogulka** [VirginTeam/WotlkCore#782]
**Ссылки и комментарии:**

http://db.logon3.com/?spell=13789

**Что работает не так?**

Талант разбойника молниеносные рефлексы повышает скорость атаки ближнего боя менее чем на 10%, как указано в описании таланта

**Как должно работать?**

Талант разбойника молниеносные рефлексы должен повышает скорость атаки ближнего боя на 10%

**Шаги для воспроизведения ошибки:**

1. Прокачиваем талант разбойника молниеносные рефлексы в ветке бой на максимум (3 раза)
2. Скорость атаки ближнего боя вырастает на 10 % !!!!

**Текущее обновление ядра:**

Build 192 2018-02-22 11:56:19 +0400

**Comment by gmOverfire** [comment]
Талант работает корректно.
