### ISSUE TITLE
[Заклинание] ID 1836 - Благоволение света

### ISSUE THREAD

**Issue by zyxellgit** [VirginTeam/WotlkCore#783]
**Ссылки и комментарии:**

http://db.logon3.com/?spell=31836  Благоволение света
**Что работает не так?**

не уменьшает на 0.5 сек, уменьшает на 0.4
![wowscrnshot_030518_232814](https://user-images.githubusercontent.com/29210390/36992758-c064f9fe-20cd-11e8-9e41-92bc9180ffc3.jpg) без прока

![wowscrnshot_030518_232817](https://user-images.githubusercontent.com/29210390/36992774-cbc61af8-20cd-11e8-9c73-5e25a4764ba0.jpg) с проком

1.946-1.557=0.389

**Как должно работать?**

уменьшение каста на 0.5 сек
**Шаги для воспроизведения ошибки:**

1. Шаг один
2. Шаг два
3. Шаг три

**Текущее обновление ядра:**
[23:27:54] Logon 3 WowCircle Development
[23:27:54]  Build 192 2018-02-22 11:56:19 +0400

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by sega693** [comment]
Там же от базовых (3 сек или сколько?) вычитается сначала 0.5, а потом хастой режется. Ну а чем больше значение без хасты, тем больше срезается. Ну или как-то так. Без шмота попробуй (без хасты хотя бы).

**Comment by zyxellgit** [comment]
проверил голым персом, все работает верно, уменьшение каста на 0.5
отмена репорта )
