### ISSUE TITLE
[Игровая механика] - Маунты с привязкой к фракции

### ISSUE THREAD

**Issue by kalipsa988** [VirginTeam/WotlkCore#786]
**Ссылки и комментарии:**

http://db.logon3.com/?achievement=879, http://db.logon3.com/?item=13086, и другие маунты

**Что работает не так?**

При рероле не всегда маунты одной фракции удаляются/заменяются на маунтов с другой фракции

**Как должно работать?**

При рероле все маунты имеющие привязку к фракции должны удаляться или заменяться на маунтов другой фракции

**Шаги для воспроизведения ошибки:**

1. Изучить несколько маунтов к примеру из ачивы http://db.logon3.com/?achievement=879
2. Сделать рерол
3. Посмотреть все ли маунты поменялись на маунтов другой фракции

**Текущее обновление ядра:**
06.03.2018

**Comment by Kodekc** [comment]
В нашей базе данных на вебе проверь каждого маунта, чтоб у него была приписка "Этот предмет превратится в ---, если вы перейдете за ---". У кого такого не будет, вот в репорт и напиши.

**Comment by kalipsa988** [comment]
Если у вас есть эта гора и вы измените фракцию, ваш монстр будет преобразован в соответствующий ранг : 

Night Elf to Tauren: 
-  Ancient Frostsaber превращается в  Green Kodo
-  Black Nightsaber превращается в  Teal Kodo

Faction  change не удаляет Ancient Frostsaber с вашего монстра но ваш персонаж орды не может его использовать (или увидеть его в списке монтирования). Если у вас есть фактический предмет (  Reins of the Ancient Frostsaber ), он будет преобразован в  Green Kodo .
с ВОВХЕДА англ комментарий

**Comment by kalipsa988** [comment]
Получается что если вы перейдёте с альянса на орду то ваш:
Узда белого жеребца,  Узда игреневого коня меняется на Рог полярного волка,  Рог рыжего волка
Поводья ледопарда,  Поводья ночного саблезуба меняется на Бирюзовый кодо,  Зеленый кодо
Снежный баран,  Черный баран меняется на Свисток красного крапчатого ящера,  Свисток палевого ящера
Белый механодолгоног модель Б,  Льдисто-синий механодолгоног модель А не изменяется, так как у нежити нет подобных маунтов, но и использовать на орде вы его не сможете 
Аналогично для перехода с орды на альянс

**Comment by gmOverfire** [comment]
Речь шла про НАШУ базу данных, а не вовхед.
Предметы http://db.logon3.com/?item=12303, http://db.logon3.com/?item=12302 не заменяются, т.к. были удалены из игры еще в ванилле.
В целом, должно работать верно.
