### ISSUE TITLE
[Заклинание] ID 49048 - Залп

### ISSUE THREAD

**Issue by kalipsa988** [VirginTeam/WotlkCore#790]
**Ссылки и комментарии:**

http://db.logon3.com/?spell=49048 - наша БД
https://web.archive.org/web/20100522095151/http://ru.wowhead.com/spell=49048 - старый вовхед

Применение | Мгновенное действие 

**Что работает не так?**

Имеет каст 0.4 секунды

**Как должно работать?**

Применение должно быть мгновенным 
**Шаги для воспроизведения ошибки:**

1. Открыть книгу заклинаний
2. Увидеть тайминг применения 

**Текущее обновление ядра:**

07.03.2018

**Comment by sega693** [comment]
Шаги для воспроизведения ошибки:
или попытаться выстрелить на ходу

**Comment by Librariane** [comment]
Заклинание должно иметь время применения, насколько помню 0,5с. Это подтверждается наличием события начала применения  begins to cast в логах
http://worldoflogs.com/reports/470kj62u5d5d1uo0/xe/?x=spell+%3D+%22Multi-Shot%22

точно такое же событие есть например у заклинания Верный выстрел, про которое точно известно что оно обладает временем применения
http://worldoflogs.com/reports/470kj62u5d5d1uo0/xe/?x=spell+%3D+%22Steady+Shot%22

а вот для заклинаний не обладающий временем применения (мнгновенное действие) такого события нет, например для Выстрела химеры
http://worldoflogs.com/reports/470kj62u5d5d1uo0/xe/?x=spell+%3D+%22Chimera+Shot%22

**Comment by Librariane** [comment]
http://www.noob-club.ru/index.php?topic=1104.0
Залп
Имеет "скрытое время" каста 0.5 секунды, что означает необходимость остановиться для выстрела. КД отсчитывается с момента отпускания кнопки выстрела (т.е., с началом каста).

**Comment by gmOverfire** [comment]
Работает правильно.
