### ISSUE TITLE
[Задание] ID 10851 - Тотем врага моего

### ISSUE THREAD

**Issue by b4vrn** [VirginTeam/WotlkCore#794]
**Ссылки и комментарии:**

http://ru.wowhead.com/quest=10851

**Что работает не так?**

Данный квест должен выдаваться NPC Вызыватель духов Догар (22312) после выполнения квеста Как понять Мок'Натал (10846).
Квест является начальным в длинной цепочке квестов, без которых выполнение достижения "Хранитель мудрости" невозможно.

**Как должно работать?**

При условии выполнения пре-квеста Как понять Мок'Натал (10846), квест Тотем врага моего (10851) должен выдаваться NPC Вызыватель духов Догар (22312).

**Шаги для воспроизведения ошибки:**

1. Выполнить квест Как понять Мок'Натал (10846)
2. Попытаться взять квест Тотем врага моего (10851)
**Текущее обновление ядра:**

Build 192 2018-02-22 11:56:19 +0400

**Comment by Kodekc** [comment]
Исправлено. Изменения будут применены в ближайшем обновлении
