### ISSUE TITLE
[Лут] ID 17952 - Темноводный кроколиск

### ISSUE THREAD

**Issue by Holyway** [VirginTeam/WotlkCore#800]
**Ссылки и комментарии:**

http://db.logon3.com/?npc=17952#skinning

**Что работает не так?**

С мобов нельзя снять шкуру

**Как должно работать?**

С мобов должна сниматься шкура

**Шаги для воспроизведения ошибки:**

1. Убить моба
2. Осознать что шкурку снять нельзя

**Текущее обновление ядра:**

Build 192 2018-02-22

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by Kodekc** [comment]
Исправлено. Изменения будут применены в ближайшем обновлении
