### ISSUE TITLE
[Заклинание] ID 26573 - Освящение

### ISSUE THREAD

**Issue by Xpamyjlya** [VirginTeam/WotlkCore#804]
**Ссылки и комментарии: http://ru.wowhead.com/spell=26573 **

**Что работает не так?**

После использования способности она сразу же исчезает

**Как должно работать?**

Под ногами должна появиться земля с разломами желтого цвета и 

Освящает участок земли, на котором вы стоите, нанося X ед. урона от светлой магии в течение 9 sec всем противникам, находящимся в области действия.

**Шаги для воспроизведения ошибки:**

1. Использовать способность

**Comment by Homo97Sapiens** [comment]
Извиняюсь за дурацкий вопрос, но... Ты точно уверен, что лужа исчезает? Может, тебе просто так кажется? Если да, то включи "проецирование текстур" в "Изображение" -> "Эффекты"

**Comment by Xpamyjlya** [comment]
Так бы мобам дамаг наносился.

**Comment by gmKroshka** [comment]
Баг-трекер Легиона находится по [ссылке](https://github.com/VirginTeam/LegionCore)
Этот раздел предназначен для патча Лича
