### ISSUE TITLE
[Заклинание(талант)] ID 250714 - Благословенный молот

### ISSUE THREAD

**Issue by Xpamyjlya** [VirginTeam/WotlkCore#805]
**Ссылки и комментарии:**

**Что работает не так?**

После использования молота он сразу же пропадает

**Как должно работать?**

Бросок благословенного молота, который летит по расходящейся спирали, нанося 131600 to 148400 ед. урона от светлой магии всем противникам, которых заденет. После усиления молот наносит 9400 to 10600 ед. дополнительного урона от светлой магии раз в 1 сек. в течение 6 sec.
--

**Шаги для воспроизведения ошибки:**

1. Использовать способность

**Comment by gmKroshka** [comment]
Баг-трекер Легиона находится по [ссылке](https://github.com/VirginTeam/LegionCore)
Этот раздел предназначен для патча Лича
