### ISSUE TITLE
Иллидана, Ярость Бури. Черный храм

### ISSUE THREAD

**Issue by SergeyVyach** [VirginTeam/WotlkCore#807]
Что работает не так?
Во второй фазе после призыва элементалей, босс пускает лучи, образования лужу, которая работает некорректно. В итоге вайп рейда.

Как должно работать?
Босс дает лужу, которая не следует за игроком. 

Текущее обновление ядра:
Build 193 2018-03-15 13:54:11 +0400

**Comment by ForesterDev** [comment]
Исправлено, проверьте после обновления
