### ISSUE TITLE
Еще одна важная составляющая заклинания

### ISSUE THREAD

**Issue by tinuwiel** [VirginTeam/WotlkCore#809]
Добрый день. У Вас тут указанно https://github.com/VirginTeam/WotlkCore/issues/775 что квест исправлен. Но квест по прежнему недоступен на 18.03.18 22.00. После сдачи квеста "Я вижу остров Алькац в твоем будущем" Бодли не дает никаких заданий.

**Comment by VirginGuard** [comment]
Вы можете писать свой комментарий даже в закрытый репорт, чем открывать новый. Пожалуйста не создавайте новый репорт, если старый был недавно закрыт, как исправленный, вы очень поможете команде проекте, если просто сообщите в закрытом репорте суть проблемы.
