### ISSUE TITLE
[Игровая механика] Заклинания, ускоряющие скорость передвижения на маунтах

### ISSUE THREAD

**Issue by gmOverfire** [VirginTeam/WotlkCore#810]
**Ссылки и комментарии:**

Аура паладина http://db.logon3.com/?spell=32223 - Аура воина Света (паладин): +20% к скорости передвижения верхом.
Таланты паладина http://db.logon3.com/?spell=26022 (ранг 1), http://db.logon3.com/?spell=26023 (ранг 2): +8%, +15% к скорости передвижения пешком и верхом.
Таланты ДК http://db.logon3.com/?spell=51983 (ранг 1), http://db.logon3.com/?spell=51986 (ранг 2): +10%, +20% к скорости передвижения верхом.
Таланты охотника http://db.logon3.com/?spell=19559 (ранг 1), http://db.logon3.com/?spell=19560 (ранг 2): +5%, +10% к скорости передвижения верхом

**Что работает не так?**

Проверим в 6 случаях: без маунта, наземный маунт 60%, наземный маунт 100%, летающий маунт 150%, летающий маунт 280%, летающий маунт 310%

Для проверки скорости персонажа используем макрос:
```
/script x=GetUnitSpeed("target") DEFAULT_CHAT_FRAME:AddMessage(format("Speed: %d yds/sec, %.1f kph, %.1f mph, %d%% normal run speed",x,x*3600/1093.6133,x*45/22,x/7*100))
```

1. Без маунта - всё работает верно.

2. Маунт 60%: 
Без талантов и ауры 159% - корректно
С аурой 192% (192-159 = 33%) - больше на **~13%**
С талантом паладина 1 ранга 172% (172-159 = 13%) - больше на **~5%**
С талантом паладина 2 ранга 183% (183-159 = 24%) - больше на **~9%**

3. Маунт 100%
Без талантов и ауры 200% - корректно
С аурой 240% (240-200 = 40%) - больше на **20%**
С талантом паладина 1 ранга 216% (216-200 = 16%) - больше на **8%**
С талантом паладина 2 ранга 230% (230-200 = 30%) - больше на **15%**
С талантом ДК 1 ранга 220% (220-200 = 20%) - больше на **10%**
С талантом ДК 2 ранга 240% (240-200 = 40%) - больше на **20%**
С талантом ханта 1 ранга 209% (209-200 = 4%) - больше на **~4%**
С талантом ханта 2 ранга 220% (220-200 = 20%) - больше на **10%**

4. Маунт 150%
Без талантов и ауры 250% - корректно
С аурой 300% (300-250 = 50%) - больше на **30%**
Таланты паладина не работают на полет - корректно

5. Маунт 280%
Без талантов и ауры 380% - корректно
С аурой 456% (456-380 = 76%) - больше на **56%**
Таланты паладина не работают на полет - корректно
С талантом ДК 1 ранга 417% (417-380 = 37%) - больше на **27%**
С талантом ДК 2 ранга 456% (456-380 = 76%) - больше на **56%**
С талантом ханта 1 ранга 209% (399-380 = 19%) - больше на **~14%**
С талантом ханта 2 ранга 220% (417-380 = 37%) - больше на **27%**

6. Маунт 310%
Без талантов и ауры 409% - корректно
С аурой 492% (492-409 = 83%) - больше на **~63%**
Таланты паладина не работают на полет - корректно
С талантом ДК 1 ранга 451% (451-409 = 42%) - больше на **~32%**
С талантом ДК 2 ранга 492% (492-409 = 83%) - больше на **~63%**
С талантом ханта 1 ранга 209% (430-409 = 21%) - больше на **~11%**
С талантом ханта 2 ранга 220% (451-409 = 42%) - больше на **~32%**

**Как должно работать?**

http://db.logon3.com/?spell=32223 должна прибавлять строго +20% к скорости передвижения верхом.
http://db.logon3.com/?spell=26022 (ранг 1), http://db.logon3.com/?spell=26023 (ранг 2): должны прибавлять строго +8%, +15% к скорости передвижения пешком и верхом.
http://db.logon3.com/?spell=51983 (ранг 1), http://db.logon3.com/?spell=51986 (ранг 2): должны прибавлять строго +10%, +20% к скорости передвижения верхом.
http://db.logon3.com/?spell=19559 (ранг 1), http://db.logon3.com/?spell=19560 (ранг 2): должны прибавлять строго +5%, +10% к скорости передвижения верхом.

**Текущее обновление ядра:**

Virgin 193 Build.

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by sega693** [comment]
> должна прибавлять строго +20% к скорости передвижения верхом.
Это откуда?
http://ru.wowhead.com/spell=32223#comments:id=1194826

> +100%
> Быстрый маунт + АвС: 240% (17 y/s)

как раз как написано на вх и получилось у вас. И по всем остальным тоже.

200% + 0.2 * 200% = 240%

**Comment by gmOverfire** [comment]
Согласен. Закрыто.
