### ISSUE TITLE
[Заклинание] ID 48574 - Глубокая рана

### ISSUE THREAD

**Issue by This-is-fizfac** [VirginTeam/WotlkCore#812]
Ссылки и комментарии:
http://db.logon3.com/?spell=48574
Исполосовывает противника, нанося ему СА/100+176 ед. урона от кровотечения и дополнительно 3583+СА0.18 ед. урона в течение 9 сек. Длина серии приемов увеличивается на 1.

Что работает не так?
Мгновенный урон, при использовании спела, подвержен срезу броней.

Как должно работать?
Броня не должна влиять на первоначальный урон

Текущее обновление ядра:
15.03.2018

Доказательства:
http://wowwiki.wikia.com/wiki/Rake?oldid=2378621
Patch 2.0.1 (05-Dec-2006): The initial damage is no longer mitigated by armor.
Тоже самое показывает доктор демедж

**Comment by ForesterDev** [comment]
Исправлено, будет применено в обновлении
