### ISSUE TITLE
[Заклинание] ID 50334, 48564 - Берсерк и Увечье (медведь)

### ISSUE THREAD

**Issue by sega693** [VirginTeam/WotlkCore#814]
**Ссылки и комментарии:**
http://db.logon3.com/?spell=50334
http://db.logon3.com/?spell=48564

**Что работает не так?**
Берсерк не сбрасывает кд мангла

**Как должно работать?**
При юзе Берсерка должно сбрасываться кд на Увечье (медведь)

https://wow.gamepedia.com/Patch_3.0.3
>  [Berserk]: Now clears the cooldown on  [Mangle] (Bear).

**Шаги для воспроизведения ошибки:**

1. ударить манглом
2. прожать берсу
3. ждать кд мангла

**Текущее обновление ядра:**
Build 193 2018-03-15 13:54:11 +0400

**Comment by ForesterDev** [comment]
Исправлено, будет применено в обновлении
