### ISSUE TITLE
Сообщения аукциона о покупках

### ISSUE THREAD

**Issue by lexzerg** [VirginTeam/WotlkCore#822]
**Ссылки и комментарии:**

непонятные сообщения

**Что работает не так?**

От аукционного дома в системном чате всегда пишет "предмет перекуплен" - неважно ставка сделана, выкуп сделан, или на самом же деле кто-то перебил ставку мою. 

**Как должно работать?**

Сообщения должны отражать реальные действия которые происходят с лотами.

**Шаги для воспроизведения ошибки:**

1. купить товар по выкупу
2. сделать ставку
3. дождаться пока ставку перебьют

**Текущее обновление ядра:**

Build 193 2018-03-15 13:54:11 +0400 x1pve virgin (live?)

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by ForesterDev** [comment]
Исправлено, будет применено в обновлении
