### ISSUE TITLE
[Задание] ID 348 - Лихорадка тернистой долины

### ISSUE THREAD

**Issue by turtuy187** [VirginTeam/WotlkCore#824]
**Ссылки и комментарии:**

http://ru.wowhead.com/quest=348 Квест

**Что работает не так?**

Не появляется знак вопроса над знахарем Унбагва (http://ru.wowhead.com/npc=1449) для начала квеста, NPC просто стоит и ничего не делает.

**Как должно работать?**

Знахарь Унбагва просит принести клык гориллы, после чего он вызывает горилл и в конце должен быть сам Мокка (http://ru.wowhead.com/npc=1514)

**Текущее обновление ядра:**

Build 193 2018-03-15 13:54:11 +0400

Персонаж Туртуй (logon3).

**Comment by Ewropa** [comment]
если персонаж за орду. то знак и не появится, задание http://db.logon3.com/?quest=349 почему-то привязано только к альянсу

**Comment by LexaZaycev** [comment]
Делал пару месяцев назад этот кв. Работало, но криво. Нужно было сагрить гориллу и подвести к нпц, после этого появился знак вопроса над ним.

**Comment by Kodekc** [comment]
Посмотрел условия, он выдаёт задание http://ru.wowhead.com/quest=349, если принято и не выполнено задание http://ru.wowhead.com/quest=348
Не уверен, что условия правильные, требуется поискать информацию

**Comment by Kodekc** [comment]
Исправлено. Изменения будут применены в ближайшем обновлении
