### ISSUE TITLE
[Игровая механика] - Озеро Ледяных Оков

### ISSUE THREAD

**Issue by Ewropa** [VirginTeam/WotlkCore#825]
**Ссылки и комментарии:**
1. NPC видны только представителям фракции, контролирующей крепость:
http://ru.wowhead.com/npc=34300
http://ru.wowhead.com/npc=30876
http://ru.wowhead.com/npc=30877
http://ru.wowhead.com/npc=30873
http://ru.wowhead.com/npc=30872
http://ru.wowhead.com/npc=30875

> От Aysik (3,821 – 13·44) 2008-12-30 (Обновление 3.0.3)		
> Видны только представителям фракции, контролирующей крепость.

2. NPC видны всегда, не важно чья фракции, контролирующей крепость
http://ru.wowhead.com/npc=30842
http://ru.wowhead.com/npc=30846
http://ru.wowhead.com/npc=30845
http://ru.wowhead.com/npc=30848
http://ru.wowhead.com/npc=30849
http://ru.wowhead.com/npc=30847

> Ибо теряется смысл заданий, там 2 вида заданий, одни получаем при контроле крепости, другие при контроле противоположной фракции 

**Что работает не так?**

Все NPC видны только контролирующей фракции

**Как должно работать?**

Все описано в п. 1

**Шаги для воспроизведения ошибки:**

Сходить на ОЛО

**Текущее обновление ядра:**

Logon 3 WowCircle Development
[11:35:36] Последнее обновление ядра: Build 193 2018-03-15 13:54:11 +0400

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by sega693** [comment]
вы же сами коммент скопировали о_О
От Aysik (3,821 – 13·44) 2008-12-30 (Обновление 3.0.3)
Видны только представителям фракции, контролирующей крепость.

и там еще полно таких
> От fisben (1,412 – 4·14) 2010-09-14 (Обновление 3.3.5) |   |  
> ааа есть все таки, просто надо чтобы озеро контролировало ваша сторона (орда или альянс), тогда они там появляются.

http://ru.wowhead.com/npc=30876#comments:id=561319

> A huge bonus to controlling Wintergrasp is the quick farming of air, water, fire, earth, and shadow crystals by means of the "revenant" elementals.

**Comment by gmOverfire** [comment]
Будет исправлено после обновления.
