### ISSUE TITLE
[Задание] ID 311 - Возвращение к Марлетте

### ISSUE THREAD

**Issue by SergeyVyach** [VirginTeam/WotlkCore#827]
Ссылки и комментарии:

http://ru.wowhead.com/quest=311 квест

Что работает не так?

После завершения квеста 310 нет возможности взять следующий.

Как должно работать?
Завершить квест 310 и с бочки взять 311.

Текущее обновление ядра:

Build 193 2018-03-15 13:54:11 +0400

**Comment by gmKroshka** [comment]
Задание http://db.logon3.com/?quest=308 выполняли?

**Comment by SergeyVyach** [comment]
да

**Comment by gmKroshka** [comment]
Напишите, пожалуйста, Ваш ник

**Comment by SergeyVyach** [comment]
Заявку оставил, меня направили сюда

**Comment by Ewropa** [comment]
если смотреть по базе, то доступ к заданию открывает это задание http://db.logon3.com/?quest=308

**Comment by gmOverfire** [comment]
Игроку вся информация была сообщена в игре, не сделаны преквесты.

**Comment by SergeyVyach** [comment]
Все преквесты были выполнены, проблема актуальна

**Comment by gmOverfire** [comment]
Преквесты НЕ сделаны, задание http://db.logon3.com/?quest=308 НЕ сделано.

**Comment by gmOverfire** [comment]
Проблема описана в #834
