### ISSUE TITLE
[Задание] ID 13481 Валим Отсюда!

### ISSUE THREAD

**Issue by Deilona** [VirginTeam/WotlkCore#831]
**Ссылки и комментарии:**
http://ru.wowhead.com/quest=13481

**Что работает не так?**

Когда берёш квест Нпс дожен начать идти а ты его охранять ( провести) Нпс не идёт стоит на месте из за чего выполнение квеста невозможно.

**Как должно работать?**

Нпс должен идти к точке назначения

**Comment by Deilona** [comment]
КАК добавить эту этикетку я не понимаю ??

**Comment by gmKroshka** [comment]
Оформите репорт по правилам
https://github.com/VirginTeam/WotlkCore
