### ISSUE TITLE
Проблема с цепочкой кв на Dungeon Set 2 

### ISSUE THREAD

**Issue by zqk87** [VirginTeam/WotlkCore#832]
**Ссылки и комментарии:**

http://wowroad.info/?quest=8986

**Что работает не так?**

Делал я квесты на хантовский д2, и все шло на удивление хорошо, пока не наткнулся на проблему: вот этот вот гном http://wowroad.info/?npc=16033 отправил меня выполнять задание http://wowroad.info/?quest=8970 Успешно выполнив задание и достав ему все 20 порций кровавой ламинарии я сдал квест, после которого должен был открыться следующий квест http://wowroad.info/?quest=8986 ,но квест Бодли мне не предлагает.

**Как должно работать?**

Бодли должен дать мне далее по цепочке один из 4-х квестов(выбранный игрой случайным образом) http://wowroad.info/?quest=8986 и открыть доступ к заданиям на Праваю часть амулета Лорда Вальтхалака.

**Шаги для воспроизведения ошибки:**

1. Шаг один
2. Шаг два
3. Шаг три

**Текущее обновление ядра:**

193 2018-03-15 13:54:11 +0400

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by gmKroshka** [comment]
Изучали информацию в предыдущем репорте?  https://github.com/VirginTeam/WotlkCore/issues/382#issuecomment-320276442

**Comment by Ewropa** [comment]
для дальнейшего прохождение нужно еще выполнение этого задания http://db.logon3.com/?quest=8964

**Comment by zqk87** [comment]
Изучил,меч добыл. Я все кв сделал по цыпочке, а он(бодли) тупо не дает кв.

**Comment by zqk87** [comment]
Короче можно положить болт? я так понял

**Comment by gmKroshka** [comment]
Ник Ваш сообщите или оставьте тикет в игре. Проверю выполнение квестов

**Comment by zqk87** [comment]
Ник в игре Beatsmastery

**Comment by zqk87** [comment]
а что такое тикет? ^^

**Comment by gmKroshka** [comment]
http://forum.wowcircle.com/showthread.php?t=50&p=4605064&viewfull=1#post4605064

**Comment by gmKroshka** [comment]
Преквесты у Вас выполнены.
Репорт по данной проблеме уже есть
https://github.com/VirginTeam/WotlkCore/issues/775
Ожидайте исправлений, либо комментариев разработчика по ссылке выше

**Comment by zqk87** [comment]
ок спасибо
