### ISSUE TITLE
[NPC] ID 18411 - Дарн Ненасытный

### ISSUE THREAD

**Issue by gmRial** [VirginTeam/WotlkCore#835]
**Ссылки и комментарии:**

http://ru.wowhead.com/npc=18411

**Что работает не так?**

НПЦ можно "загнать" в текстуры за пределами его маршрута, либо в другую локацию (возможно, с использованием читов). НПЦ не восстанавливает свое местоположение после убийства командой.

**Как должно работать?**

Должен гулять строго по маршруту.

**Текущее обновление ядра:**

Build 193

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by Santaria** [comment]
http://db.logon3.com/?npc=18411
Где-то между 3 и 4 путевой точкой сбился с пути и начал двигаться в сторону Леса Тероккар сквозь текстуры. В итоге улетел по воздуху куда-то через невидимую стенку и пропал из поля зрения.

![Alt text](https://cdn.discordapp.com/attachments/412316469721038858/529936671639207946/WoWScrnShot_010219_103505.jpg "Optional title")
![Alt text](https://cdn.discordapp.com/attachments/412316469721038858/529936671446138890/WoWScrnShot_010219_103410.jpg "Optional title")
![Alt text](https://cdn.discordapp.com/attachments/412316469721038858/529936670062280736/WoWScrnShot_010219_103622.jpg "Optional title")
![Alt text](https://cdn.discordapp.com/attachments/412316469721038858/529936666891386901/WoWScrnShot_010219_103910.jpg "Optional title")

**Comment by gmRial** [comment]
![image](https://user-images.githubusercontent.com/26819342/50683613-78a60200-1034-11e9-8a7a-59d4014ca42e.png)

**Comment by ForesterDev** [comment]
Маршруты переписаны, надо будет протестировать после обновления
