### ISSUE TITLE
[NPC] ID 28362 - Мерцающая грязь

### ISSUE THREAD

**Issue by gmOverfire** [VirginTeam/WotlkCore#838]
**Ссылки и комментарии:**

**http://db.logon3.com/?npc=28362** НПЦ
http://db.logon3.com/?quest=12704
http://db.logon3.com/?quest=12572
http://db.logon3.com/?spell=51441
http://db.logon3.com/?npc=28371
http://db.logon3.com/?spell=51442

**Что работает не так?**

1. Умирает после респавна, из-за чего невозможно выполнить квесты.
2. Проверить наличие заклинания для вызова зайца.

**Как должно работать?**

1. Не должен умирать сразу же.
2. Есть шанс на призыв зайца, за убийство которого должен быть бафф на 50% к скорости передвижения.

**Шаги для воспроизведения ошибки:**

1. Взять один из квестов.
2. Призвать спутника-оракула.
3. Попытаться найти блестяшки.

**Текущее обновление ядра:**

Build 194

**Comment by MiceRus** [comment]
Сделали бы уж автокомплит и не мучились и людей не мучили. Не такие уж там и награды и сложность за этот квест ,а вот дальнейшее выполнение ачивок просто заторможено

**Comment by gmKroshka** [comment]
Автокомплита не будет, дожидайтесь исправления задания

**Comment by MiceRus** [comment]
Уже не один месяц ждем. Что еще остается делать?

**Comment by gmKroshka** [comment]
> 	gmOverfire opened this issue 20 days ago

Ну почти "не один месяц", да.
Информации о сроках исправления нет

**Comment by Hellsingoff** [comment]
![123](https://user-images.githubusercontent.com/30525127/39645179-dac46e2c-4ff0-11e8-8ca3-b5f83f5b4774.png)
Не подскажете по какому хитрому методу это получилось? Пытался повторить пол часа, но вторую достать не вышло.

**Comment by SergeyVyach** [comment]
поправьте квест, блокирует цепочку заданий

**Comment by ForesterDev** [comment]
Исправлено, будет применено в обновлении
