### ISSUE TITLE
[Лут] ID 51999 - Сумка с полезными вещами

### ISSUE THREAD

**Issue by kalipsa988** [VirginTeam/WotlkCore#839]
**Ссылки и комментарии:**

http://db.logon3.com/?item=51999#contains

**Что работает не так?**

Пояса падают по максимальному типу брони персонажа

**Как должно работать?**

Должно падать не зависимо от типа брони персонажа, т е магам падают кольчужные и кожаные пояса, друлям ткань и кольчуга, варам кожа и ткань, и тд
Сумка выше ЛВ работает правильно.
**Шаги для воспроизведения ошибки:**

Открывать http://db.logon3.com/?item=51999 за разные классы

**Текущее обновление ядра:**

28.03.2018

Как пруфы большое количество твинков шаманов/друлей с тканевыми поясами из сумки
И сегодня на лока 50го упали кольчужные запястья

**Comment by sega693** [comment]
http://ru.wowhead.com/item=51999#comments:id=929897

> Если вам попадается доспех, то тип доспеха будет максимальным из тех что вы умеете носить.

**Comment by sega693** [comment]
http://ru.wowhead.com/item=51999#comments:id=929897

> Если вам попадается доспех, то тип доспеха будет максимальным из тех что вы умеете носить.

http://ru.wowhead.com/item=51999#comments:id=911912

> If you recieve an item with variable armor type, it is the highest armor type your class can wear at that level range.

Так что репорт должен ровно наоборот быть. На кой черт магу латы?
"Сумка с **полезными** вещами" в конце концов.
