### ISSUE TITLE
[Общая механика] Эффекты увеличения скорости каста

### ISSUE THREAD

**Issue by Gooldark** [VirginTeam/WotlkCore#84]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Все эффекты увеличения скорости каста которые можно повесть на союзника стакаются между собой, хотя не должны.

**Что работает не так?**

а) Придание сил(ID 10060), Жажда крови(ID 2825) и Героизм(ID 32182) стакаются друг с другом.

б) Придание сил(ID 10060) можно повесть на вара или рога

в) На цель одновременно можно повесить Придание сил(ID 10060) и Мощь тайной маги(ID 12042)

**Как должно работать?**

а) Хаст от Жажда крови(ID 2825) или Героизм(ID 32182) должен подавлять хаст от Придание сил(ID 10060), в то же время 20% экономии маны должен действовать. 
Жажда крови(ID 2825) + Героизм(ID 32182) должны заменять друг друга по принципу кто дольше провисит!

Остальные вариации с бафами на хасту должны действовать(имеется ввиду Изничтожение(ID 47197) + Придание сил(ID 10060) или Жажда крови(ID 2825) + Стылая кровь(ID 12472)). То есть фикс должен касаться только спелов которые можно повесить на другую цель кроме себя.

б) Должна отсутствовать возможность повесить на вара или рога(возможно ДК) Придание сил(ID 10060)

**Шаги для воспроизведения ошибки:**

1. Повесить на одну цель Придание сил(ID 10060), Жажда крови(ID 2825) и Героизм(ID 32182)
2. Скастовать что либо.

**Текущее обновление ядра:**

11.04.2017 птр 21 билд

**Доказательства**

а) http://wow.gamepedia.com/index.php?t...&oldid=2376360

> Does not not stack with [Bloodlust]/ [Heroism] or other haste effects which can be applied to others.

http://www.warcraftmovies.com/movieview.php?id=161647

В этом видео видно что пи отдают под вены, это один из лучших магов офа, не думаю что они сливали бы пи только ради экономии маны.

http://www.warcraftmovies.com/movieview.php?id=123049 - 09:46 - на маге только вены, фб кастуется 1,6+ сек.
09:56 - к венам добавляется бл, фб начинает кастоваться за 1,3 сек

http://www.warcraftmovies.com/movieview.php?id=149601 - 02:15 - маг в таргете лока под венами и краденым блом получает геру, в итоге видно 2 дебафа на геру и вены, а так же бл заменился на геру, так как время ее действия было бы больше чем бла которое уже действовало. 

б) http://wowwiki.wikia.com/wiki/Power_Infusion

> Patch 2.1.0 (22-May-2007): This ability is now unuseable on Rogues or Warriors.

в) http://wow.gamepedia.com/index.php?title=Power_Infusion&oldid=2376360

> This ability will no longer stack with [Arcane Power]. If you gain both at the same time, Arcane Power will take precedence.

> Does not stack with [Arcane Power]. If Arcane Power is already active, a priest casting Power Infusion will receive an error message "A more powerful spell is already active." If Power Infusion is already active on the mage, activating Arcane Power will override it.

Полагаю это из-за снижение маны и повышения маны этими спелами, а не из-за хасты и урона. Так как думаю что бл должен стакаться с мощью.

Вот лог в котором видно что Мощь тайной магии должно заменять Придание сил,
Придание сил провисело только 3 сек, затем маг использовал Мощь тайной магии и Придание сил исчезло. При этом героизма не было, поэтому тут чистое взаимодействие этих двух спелов.

Жажда крови/Героизм + Мощь тайной магии могут взаимодействовать, что видно дальше по логу.

http://www.worldoflogs.com/reports/s7qkr5l7nwaqmdx5/xe/?x=spell+%3D+"Arcane+Power"+OR%0D%0Aspell+%3D+"Power+Infusion"+OR%0D%0Aspell+%3D+"Heroism"

> [18:28:19.119] Nashal casts Power Infusion on Roenn
[18:28:19.166] Roenn gains Power Infusion from Nashal
[18:28:22.489] Nashal's Power Infusion fades from Roenn
[18:28:22.489] Roenn gains Arcane Power from Roenn
[18:28:22.489] Roenn casts Arcane Power
[18:28:28.914] Chaosfire's Arcane Power fades from Chaosfire
[18:28:37.457] Roenn's Arcane Power fades from Roenn

**Перенесено**

http://forum.wowcircle.com/showthread.php?t=501819

**Comment by MedoOk** [comment]
[ссылка](http://worldoflogs.com/reports/c8cxbvus1gxkxbcp/xe/?s=12306&e=13862&x=spellID+%3D+12472%0D%0AOR+spellID+%3D+10060%0D%0AOR+spellID+%3D+2825%0D%0Aor+(sourcename+%3D+"Mønøxïdê"%0D%0Aand+spellid+%3D+42897)&page=5)
[00:38:07.468] Mønøxïdê gains Icy Veins from Mønøxïdê
[00:38:07.468] Mønøxïdê casts Icy Veins
[00:38:12.906] Mønøxïdê begins to cast Arcane Blast
[00:38:14.296] Mønøxïdê begins to cast Arcane Blast
[00:38:14.359] Mønøxïdê Arcane Blast The Lich King 20682
[00:38:15.734] Mønøxïdê begins to cast Arcane Blast
время каста 1.4
[00:38:23.968] Mønøxïdê gains Bloodlust from Applesaus
[00:38:25.515] Mønøxïdê begins to cast Arcane Blast
[00:38:26.609] Mønøxïdê begins to cast Arcane Blast
[00:38:26.796] Mønøxïdê Arcane Blast The Lich King 11273
[00:38:26.796] Applesaus's Bloodlust fades from Wrutanks
[00:38:27.453] Mønøxïdê's Icy Veins fades from Mønøxïdê
время каста 1.1
[00:38:35.015] Mønøxïdê begins to cast Arcane Blast
[00:38:35.203] Mønøxïdê Arcane Blast The Lich King *25433*
[00:38:36.218] Mønøxïdê begins to cast Arcane Blast
[00:38:36.390] Mønøxïdê Arcane Blast The Lich King *25976*
[00:38:37.421] Mønøxïdê begins to cast Arcane Blast
время каста 1.2
[00:38:38.812] Mønøxïdê Arcane Blast The Lich King 11579
[00:38:40.843] Applesaus's Bloodlust fades from Mønøxïdê

**Comment by MedoOk** [comment]
https://www.youtube.com/watch?v=CU89yRJHdgQ
