### ISSUE TITLE
[Лут] ID 51999-52005 - Сумка с полезными вещами 

### ISSUE THREAD

**Issue by sega693** [VirginTeam/WotlkCore#840]
**Ссылки и комментарии:**
http://db.logon3.com/?item=51999#see-also
http://db.logon3.com/?item=52000
http://db.logon3.com/?item=52001
http://db.logon3.com/?item=52002
http://db.logon3.com/?item=52003
http://db.logon3.com/?item=52004
http://db.logon3.com/?item=52005

**Что работает не так?**
Падает рандомный тип брони: магам - латы, варам - ткань и т.д.

**Как должно работать?**
Латникам падают латы, тканникам - ткань и т.д.

http://ru.wowhead.com/item=51999#comments:id=929897
> Если вам попадается доспех, то тип доспеха будет максимальным из тех что вы умеете носить.

http://ru.wowhead.com/item=51999#comments:id=911912
> If you recieve an item with variable armor type, it is the highest armor type your class can wear at that level range.

**Шаги для воспроизведения ошибки:**
1. Пройти пп
2. Открыть сумку

**Текущее обновление ядра:**
Build 194 2018-03-26 13:15:58 +0400

**Comment by kalipsa988** [comment]
отсутствует кожаный пояс с меткой волшебника

**Comment by Santaria94** [comment]
Trinity
https://github.com/raczman/TrinityCore/commit/87d978f52cfd799a83e011a5815c0f87f0695469

**Comment by kalipsa988** [comment]
исправлено
вопрос к автору но http://db.logon3.com/?item=52002 например, если не изучать хантом/шаманом кольчугу на 40 уровне, то в теории я не могу носить её, не должна ли в этом случае падать кожа, сейчас падает кольчуга ?

**Comment by kalipsa988** [comment]
необходимо поставить фильтр по максимально возможному типу брони на данный момент, с 52001 и далее можно заметить, что варам, палам, шаманам, хантам, при не изученных латах/кольчуге, падают максимально возможный тип брони в зависимости от класса, а не на данный момент
