### ISSUE TITLE
[Игровая механика] Оружие с доп уроном от магии

### ISSUE THREAD

**Issue by kalipsa988** [VirginTeam/WotlkCore#842]
**Ссылки и комментарии:**

http://db.logon3.com/?item=1482, http://db.logon3.com/?item=1318, http://db.logon3.com/?item=4446, http://db.logon3.com/?item=7682, http://db.logon3.com/?item=9718, http://db.logon3.com/?item=936
ПС маленькая часть предметов

**Что работает не так?**

Не работают дополнительные очки урона от магии

**Как должно работать?**

Данный урон должен повышать автоатаку игрока.
На примере http://db.logon3.com/?item=1482 при силе атаки 444. Урон состоит из: урона самого меча (29-55) + урон от магии (4-8) + урон от силы атаки (444/14*2.7=85.6). Итого должно быть 118-149. На деле имеем 114-141. То есть как раз 4-8 не хватает.

**Шаги для воспроизведения ошибки:**

1. Взять любую пуху из списка 
2. Побить паладина под БОП белыми атаками
3. Увидеть одну невосприимчивость

**Текущее обновление ядра:**

29.03.2018

**Comment by kalipsa988** [comment]
![wowscrnshot_032918_131312](https://user-images.githubusercontent.com/29568428/38083809-5d0ad9d0-3353-11e8-9e3b-f9acacb28426.jpg)

**Comment by Gooldark** [comment]
Так тот урон что написан это усредненный прок, это оружие и не должно наносить отдельный урон от магии кроме редкого прока.

**Comment by Gooldark** [comment]
Насколько знаю так это должно работать

**Comment by kalipsa988** [comment]
О каком проке речь ?

**Comment by gmRial** [comment]
Исправлено, после обновления.
