### ISSUE TITLE
[Задание] ID 13418 - Подготовка к войне

### ISSUE THREAD

**Issue by gmKroshka** [VirginTeam/WotlkCore#843]
**Ссылки и комментарии:**

Задание [Подготовка к войне](http://db.logon3.com/?quest=13418)
Проблемное существо [Старший капитан Джастин Бартлетт](http://db.logon3.com/?npc=30344)

**Что работает не так?**

Отсутствует [Старший капитан Джастин Бартлетт](http://db.logon3.com/?npc=30344) на корабле, некому сдавать задание.

**Как должно работать?**

НПЦ должен находиться на корабле

**Шаги для воспроизведения ошибки:**

1. Взять задание
2. Прилететь на Усмиритель небес

**Текущее обновление ядра:**

Последнее обновление ядра: Build 194 2018-03-26 13:15:58 +0400

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by gmKroshka** [comment]
Дополнение
http://forum.wowcircle.com/showthread.php?t=413252

**Comment by gylyty** [comment]
опять его нет на корабле.
