### ISSUE TITLE
Мобы в подземелье "Непроглядная пучина"

### ISSUE THREAD

**Issue by kalambyr18** [VirginTeam/WotlkCore#847]
Ссылки и комментарии:

http://ru.wowhead.com/blackfathom-deeps

Что работает не так?

Мобы сбрасывают агро: У моба остается мало хп, отбегает , становится фуловым , агро сбрасывается. Мобы бегают по воде . Скриншоты места в котором это происходит(выделил зеленым): 
http://screenshot.ru/upload/image/aLPO
http://screenshot.ru/upload/image/aLPV

Как должно работать?

Не должны бегать по воде , сбрасывать агро .

Шаги для воспроизведения ошибки:

В месте на скриншотах в подземелье заагрить мобов , постараться убить.

Текущее обновление ядра:

Build 194 2018-03-26 13:15:58 +0400

**Comment by gmOverfire** [comment]
Оформите репорт по шаблону.
