### ISSUE TITLE
[Игровая механика] ID 22888 - Ободряющий клич Драконоборца

### ISSUE THREAD

**Issue by kalipsa988** [VirginTeam/WotlkCore#848]
**Ссылки и комментарии:**

http://ru.wowhead.com/spell=22888#english-comments

**Что работает не так?**

а) Баф даётся только на мосту штормграда для альянса
б) Отсутствует скалирование с уровнем 
в) Баф вешается на уровни 1-80
**Как должно работать?**

а)Баф должен даваться на всех игроков определённой фракции по торговому кварталу штормграда

б) Most probably, the formula for spell crit rating and melee attack power is as simple as
140 * / 60
and for melee and ranged crit rating
70 * / 60
Пруф http://wowwiki.wikia.com/wiki/Rallying_Cry_of_the_Dragonslayer
в) Должен вешаться только на уровни с 1 по 63, пруф выше

**Шаги для воспроизведения ошибки:**

1. Сдать http://db.logon3.com/?item=19003
2. Пройтись с моста дальше по штормграду
3. Увидеть отсутcвие бафов в шторме
4. Увидеть на любом уровне +120
**Текущее обновление ядра:**

31.03.2018

**Comment by Plasmashield** [comment]
В личе крит 140, а не 70

**Comment by kalambyr18** [comment]
При сдаче кв "Голова Ониксии " не дается баф ни на мосту , ни в других районах Штормграда.

**Comment by kalipsa988** [comment]
это указано в тикете!

**Comment by kalipsa988** [comment]
пункт "а"

**Comment by kalipsa988** [comment]
баф даётся только на мосту, проверял вчера

**Comment by ForesterDev** [comment]
Хотя, для головы 60 уровня, пожалуй, должны быть аналогичные скрипты, раз в орде они присутствуют.

**Comment by kalipsa988** [comment]
В принципе можно выбить голову они 60го лв, может она не кидает

**Comment by gmKroshka** [comment]
Будет исправлено после обновления

**Comment by kalipsa988** [comment]
Альянс
Не даёт баф на самом мосту штормграда, по сути, что бы получить баф игроку, который сдаёт голову, нужно бежать на торговую площадь
Орда
Не даёт баф дальше моба, которому сдавать голову, примерный радиус бафа от моба до столба, банк/аук/полётка/вход не даёт баф

**Comment by kalipsa988** [comment]
Перетест:
Альянс, всё работает, но судя по комменту с вовхеда, да и в нашей бд точка есть, должно ещё даваться на златоземье 
https://ru.wowhead.com/spell=22888/%D0%BE%D0%B1%D0%BE%D0%B4%D1%80%D1%8F%D1%8E%D1%89%D0%B8%D0%B9-%D0%BA%D0%BB%D0%B8%D1%87-%D0%B4%D1%80%D0%B0%D0%BA%D0%BE%D0%BD%D0%BE%D0%B1%D0%BE%D1%80%D1%86%D0%B0#comments
От FXGaz (1 215 - 2 · 17 ) 2010-06-14 (Обновление 3.3.3) |   |  

Сегодня в златоземье у всех был этот бафф (у мобов даже) 
Мастхэвчик @ Разувий

**Comment by kalipsa988** [comment]
Перетест:
Орда
всё работает
