### ISSUE TITLE
[Заклинание] ID 50392 - Власть нечестивости 

### ISSUE THREAD

**Issue by 0nlyunfa** [VirginTeam/WotlkCore#849]
**Ссылки и комментарии:**

http://wowroad.info/?spell=48265 

**Что работает не так?**

Власть нечестивости добавляет 15% к скорости передвижения , сейчас эффект действует только на бег (пеший ход) без маунта , на маунте - бонуса к скорости передвижения нет

**Как должно работать?**

Власть должна добавлять скорость передвижения верхом .
**Шаги для воспроизведения ошибки:**

https://youtu.be/IcdGTtV-jRY
https://youtu.be/yYXorqGpqWE
https://youtu.be/GtLq-9JotIs

**Текущее обновление ядра:**

Можно посмотреть в игре, введите в чат команду .server info и скопировать строку начиная с Build с номером и датой. Не забывайте указывать, Live Server или PTR Server, где проводилось тестирование.

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by zyxellgit** [comment]
на передвижение ВЕРХОМ вроде идет http://db.logon3.com/?spell=51267 На коне бледном

**Comment by 0nlyunfa** [comment]
это талант
стойка даёт 15% скорости передвижения (не скорости БЕГА или ХОДЬБЫ , а именно передвижения , как верхом - так и пешком)

**Comment by zyxellgit** [comment]
От asktgm (5,786 – 1·14·59) 2008-08-22 (Обновление 3.0.1) |   
Does not seem to affect your speed while mounted.

zeroshens 2012-04-24 (Обновление 4.3.4)
On a Pale Horse will increase your mounted speed, as well as reduce the time of slows on your character.

http://ru.wowhead.com/spell=48265#english-comments

а еще такой репорт был http://forum.wowcircle.com/showthread.php?t=312186

**Comment by 0nlyunfa** [comment]
комментарии не актуальны для 3.3.5
репорт вообще с логон 1 - какое отношение имеет ?
найду видео кину на днях
должно давать скорость передвижения и на маунте и пешком (потому что в описании не указано конкретно какой тип передвижения - действует на оба)

**Comment by ForesterDev** [comment]
https://eu.battle.net/forums/en/wow/topic/2037905094
Only movement speed on foot
https://us.battle.net/forums/en/wow/topic/1921697856
No

However, On a Pale Horse does though.

Отклонено
