### ISSUE TITLE
[Задание] ID 15002 - Миссия: Степи

### ISSUE THREAD

**Issue by gmKroshka** [VirginTeam/WotlkCore#851]
**Ссылки и комментарии:**

http://db.logon3.com/?quest=15002

**Что работает не так?**

Не засчитывает подземелье Курганы Иглошкурых

**Как должно работать?**

Курганы Иглошкурых засчитаны, задание выполнено

**Шаги для воспроизведения ошибки:**

1. Взять задание
2. Пройти Курганы Иглошкурых

**Текущее обновление ядра:**

Последнее обновление ядра: Build 194 2018-03-26 13:15:58 +0400

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by ForesterDev** [comment]
Исправлено, будет применено в обновлении
