### ISSUE TITLE
регистратор гильдий

### ISSUE THREAD

**Issue by wagnes91** [VirginTeam/WotlkCore#853]
Орда 
Регистратор Гильдии
При попытке отдать  хартию ГИ(10 человек подписали), не нажимается сама строчка(задание)  Зарегистрировать Хартию гильдии!
удаление папки кэш и использование антиэрор в личном кабинете не помогло исправить данную проблему !

**Comment by gmKroshka** [comment]
Какое название гильдии задаете?
