### ISSUE TITLE
quest=9644 quest=10901

### ISSUE THREAD

**Issue by krapter** [VirginTeam/WotlkCore#855]
**Ссылки и комментарии:**

Добавьте ссылки с wowhead.com или db.logon3.com на проблемные задания, NPC, заклинания и т.д. 

не прилетает

не прилитает нажимал на урну 

**Как должно работать?**

прилетает Босс убиваю его и забираю по заданию требуемое...

**Шаги для воспроизведения ошибки:**

1. Шаг один
2. Шаг два
3. Шаг три

**Текущее обновление ядра:**

Можно посмотреть в игре, введите в чат команду .server info и скопировать строку начиная с Build с номером и датой. Не забывайте указывать, Live Server или PTR Server, где проводилось тестирование.

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by gmKroshka** [comment]
Оформите репорт по шаблону

**Comment by krapter** [comment]
чтО?? я не понимаю что написали вы.. меня перевили с форума сюда чтоб как то я мог добиться своих квестов которых не могу выполнить..

**Comment by gmKroshka** [comment]
Я пока что Вас тоже не понимаю)
Описания оформления репорта https://github.com/VirginTeam/WotlkCore

**Comment by krapter** [comment]
самое главное я отправил ид квестов.. и всё этим сказано.. и ещё я ко многим обращался.. что меня направили на форум.. и все почти пишут что они выросли с этого возраста и не собераються разбираться гдето что работает что нет им без разнецы.. а ребя та то нармальные . и им проверить 5 минут их если не меньше..

**Comment by krapter** [comment]
если меня не обнадёжат здесь на сщёт этих квестов я буду отвечать всем что это неизвестно когда исправят или вапще исправят ...

**Comment by olegklim1991** [comment]
всё работает,для начала сделай цепочку квестов,и пройди геры бкашные,а потом только и клацай на урну,так что тему можно закрывать

**Comment by olegklim1991** [comment]
крошка,он написал репорт по ночной погибели http://ru.wowhead.com/quest=9644 сам кв,это нпц http://ru.wowhead.com/npc=114895,бесят тупые репорты по бк если люиди даже не знают как эта погибель вызывается

**Comment by krapter** [comment]
а у откуда у меня эти квесты если выговорите -думаети что я не выполнил цепочку квестов????02.04.2018, 21:53, "olegklim1991" <notifications@github.com>:всё работает,для начала сделай цепочку квестов,и пройди геры бкашные,а потом только и клацай на урну,так что тему можно закрывать

**Comment by gmKroshka** [comment]
Всё действительно работает. Урна юзается, Погибель прилетает. Каждую неделю бываю в Каражане, проблем не возникало
