### ISSUE TITLE
[Игровая механика] - Иммунитеты к Кровотечениям

### ISSUE THREAD

**Issue by sega693** [VirginTeam/WotlkCore#856]
**Ссылки и комментарии:**
Все кровотечения: http://db.logon3.com/?spell=48574 http://db.logon3.com/?spell=49800 http://db.logon3.com/?spell=12867 http://db.logon3.com/?spell=47465 роговские и т.д.

Многие мобы/боссы, особенно БК и классик -контента, невосприимчивы к блидам
Конкретно для примера : 
ВСЕ боссы Санвела, кроме Калесгоса:
http://db.logon3.com/?npc=24892 Сатроварр Осквернитель
http://db.logon3.com/?npc=24882 Бруталл
http://db.logon3.com/?npc=25038 Пророк Скверны
http://db.logon3.com/?npc=25165 Леди Сакролаш
http://db.logon3.com/?npc=25166 Главная чернокнижница Алитесса
http://db.logon3.com/?npc=25741 М'ууру
http://db.logon3.com/?npc=25840 Энтропий
http://db.logon3.com/?npc=25315 Кил'джеден 
трешь Санвела:
http://db.logon3.com/?npc=25507 Заступник клана Солнечного Клинка
http://db.logon3.com/?npc=25599 Гончая Катаклизма
http://db.logon3.com/?npc=25508 Страж из клана Темного Меча. И все остальные НЕ-эльфы 
прочее:
http://db.logon3.com/?npc=6109 Азурегос (дракон)
http://db.logon3.com/?npc=18848 Злобный инструктор(демон) в Темный лабиринт
http://db.logon3.com/?npc=19219 Механо-лорд Конденсарон в Механаре
http://db.logon3.com/?npc=19735 Разрушитель Бурегорна в Механаре
http://db.logon3.com/?npc=24777 Часовой из клана Солнечного Клинка в Терраса Магистров
http://db.logon3.com/?npc=23394 Часовой-патрульный в БТ

http://db.logon3.com/?npc=17796 Анжинер Паропуск в Паровое подземелье

Трешь Ульдуара (не весь), ЧК и много где еще
http://db.logon3.com/?zone=4273
http://db.logon3.com/?zone=4264

также https://github.com/VirginTeam/WotlkCore/issues/820 и https://github.com/VirginTeam/WotlkCore/issues/823

**Что работает не так?**
невосприимчивы к блидам.

**Как должно работать?**
НЕ должно быть иммунитета на 3.3+ патче вообще

В гайдах об иммуне не указано, а с позднего БК — начала ВотЛК такие иммунитеты вообще выпилены были даже там, где они имелись

В частности https://github.com/VirginTeam/WotlkCore/issues/820

https://www.youtube.com/watch?v=SWi_4kX4hvI древний видос где видно тики дот
https://www.youtube.com/watch?v=YJDrv1DN0OE если постараться можно разглядеть "растерзать"
на каждого так искать или хватит??

https://www.youtube.com/watch?v=OQIdYAtZi3E тут отлично видно доты ферала и роги на Пророке
https://www.youtube.com/watch?v=OYXJYscnAOI

**Шаги для воспроизведения ошибки:**
1. ударить любым спелом с блидом

**Текущее обновление ядра:**
Build 194 2018-03-26 13:15:58 +0400

**Comment by ForesterDev** [comment]
Для большей части из списка будет удален иммунитет

**Comment by sega693** [comment]
Похоже только у боссов Санвела удалили. У треша там же имун остался.
http://db.logon3.com/?npc=15691 Смотритель в Каражане еще
