### ISSUE TITLE
Побег из Среброречья

### ISSUE THREAD

**Issue by MiceRus** [VirginTeam/WotlkCore#859]
Квест не засчитывается выполненным!
**Как должно работать?**

ДА как на оффе! Вы же Близлайк!

ЗЫ: А может мне вообще самому весь код написать?
Если хотите нормальный багтрекер - так сделайте нормалные поля ввода, не звездочками и стретолчками указывайте что и как вводить!

**Comment by gmKroshka** [comment]
Можете и код написать. 
А можете оформить верно репорт по шаблону. 
https://github.com/VirginTeam/WotlkCore
