### ISSUE TITLE
[Группа заклинаний] Снятие контроля

### ISSUE THREAD

**Issue by Gooldark** [VirginTeam/WotlkCore#86]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Что работает не так?**

Воля отрекшихся (ID 7744) и PvP-аксессуар (ID 42292) имеют несвязанные кд

Возможно что баг касается и других спелов! Поэтому неплохо было бы во время фикса глянуть какие еще кд в механике не связаны.

**Как должно работать?**

При использовании Воля отрекшихся(ID 7744) или PvP-аксессуар(ID 42292)  должно появляться 45-и секундное кд у этой группы спелов.

**Шаги для воспроизведения ошибки:**

1. Создать отрекшегося, одеть тринькет, подождать кд.
2. Нажать на рассовую или тринькет, релогнуться

**Текущее обновление ядра:**

11.04.2017 птр 21 билд

**Перенесено**

http://forum.wowcircle.com/showthread.php?t=653406

**Comment by ForesterDev** [comment]
Исправлено
