### ISSUE TITLE
[Задание] ID 11999 - Обшарить трупы

### ISSUE THREAD

**Issue by Stormik-uu** [VirginTeam/WotlkCore#860]
**Ссылки и комментарии:**

Задание "Обшарить трупы" http://ru.wowhead.com/quest=11999

**Что работает не так?**

Не выпадает предмет
Планы из Садов Лунного Покоя http://ru.wowhead.com/item=35783
**Как должно работать?**

Должен выпасть предмет

**Шаги для воспроизведения ошибки:**

1. Обшарить трупы
2. Должен выпадать с каждого трупа Личный скарб охотника на магов http://ru.wowhead.com/item=35792#created-by-spell
Он не выпадает вообще

**Текущее обновление ядра:**

Build 194 2018-03-26 Logon 3 WowCircle Development

**Comment by ForesterDev** [comment]
Исправлено

**Comment by MiceRus** [comment]
А как долго проходит с момента отметки "Ожидает применения" и самого применения исправления?
Только что обшарил с десяток трупов - ничего.

**Comment by gmOverfire** [comment]
Отслеживать статус применения обновлений сервера можно в нашем дискорде.
Ну и как правило, мы здесь метки меняем после обновления.
