### ISSUE TITLE
[Заклинание] ID 24425 - Дух Зандалара

### ISSUE THREAD

**Issue by Endorphine1** [VirginTeam/WotlkCore#861]
**Ссылки и комментарии:**

Добавьте ссылки с wowhead.com или db.logon3.com на проблемные задания, NPC, заклинания и т.д. 
http://db.logon3.com/?spell=24425
**Что работает не так?**
Баф можно получить с 1 по 63 уровень. Использование таких мощных бафов на 19 уровне полностью руинит игру на брекете. 
Фактический результат — тот, который вы наблюдаете 
Баф накладывается на каждого игрока, находящегося на острове зандалар в тернистой долине при сдаче кв http://db.logon3.com/?quest=8183
**Как должно работать?**
баф накладывается верно, судя по комментариям на вовхеде так было и на офф сервере
"i got this at lvl 19 and it gave me +50 stats "
Ожидаемый результат — то, чего вы ожидали при выполнении ваших действий. Процесс правильной работы
Но это вносит дикий дисбаланс в игре на 19 уровне. Если была возможность как то пофиксить этот баф, например, сделать его тип магия, как свитки, которые можно диспелить\пуржить, то было бы дико здорово. 
**Шаги для воспроизведения ошибки:**

1. Шаг один - убить хаккара в рейде зулгуруб и взять квестовый итем
2. Шаг два - привести толпу 19 твинков на остров в тернистой долине, где сдается кв.
3. Шаг три - сдать кв и полутать баф на +50 ко всем статам. 

**Текущее обновление ядра:**

Можно посмотреть в игре, введите в чат команду .server info и скопировать строку начиная с Build с номером и датой. Не забывайте указывать, Live Server или PTR Server, где проводилось тестирование.

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by kalipsa988** [comment]
1. Работает правильно-нечего чинить 
2. Не можешь своей шайкой баф получить, не надо сразу фиксить

**Comment by ForesterDev** [comment]
Близзлайк. Отклонено
