### ISSUE TITLE
[Заклинание] ID22888 - Ободряющий клич Драконоборца

### ISSUE THREAD

**Issue by Endorphine1** [VirginTeam/WotlkCore#862]
**Ссылки и комментарии:**

Добавьте ссылки с wowhead.com или db.logon3.com на проблемные задания, NPC, заклинания и т.д. 
http://db.logon3.com/?spell=22888
http://ru.wowhead.com/spell=22888#english-comments
**Что работает не так?**
Не производится скалирование бафа от уровня персонажа
Фактический результат — тот, который вы наблюдаете 
Скалирования нет. Баф слишком сильный для игроков низкого уровня
**Как должно работать?**
Most probably, the formula for spell crit rating and melee attack power is as simple as
140 * <character level> / 60
and for melee and ranged crit rating
70 * <character level> / 60

Ожидаемый результат — то, чего вы ожидали при выполнении ваших действий. Процесс правильной работы
140 * 19 / 60 = 44.33  - мили ап
70 * 19 / 60 = 22.16 (рейндж и мили крит)

А еще можно аналогично https://github.com/VirginTeam/WotlkCore/issues/861 сделать баф рассеивающимся.
**Шаги для воспроизведения ошибки:**

1. Шаг один - убить ониксию и взять квестовый итем http://db.logon3.com/?item=18422
2. Шаг два - притащить в столицу, где выполняются кв, толпу 19 лвла.
3. Шаг три - сдать кв, получить баф на себя и всех окружающих.

**Текущее обновление ядра:**

Можно посмотреть в игре, введите в чат команду .server info и скопировать строку начиная с Build с номером и датой. Не забывайте указывать, Live Server или PTR Server, где проводилось тестирование.

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by kalipsa988** [comment]
дубликат #848
