### ISSUE TITLE
[Заклинание] ID 69762 - Освобожденная магия

### ISSUE THREAD

**Issue by Knaufbest** [VirginTeam/WotlkCore#864]
**Ссылки и комментарии:**

Добавьте ссылки с wowhead.com или db.logon3.com на проблемные задания, NPC, заклинания и т.д. 

**Что работает не так?**
 http://wowroad.info/?spell=69762 Кидается на 5 хилов.
Фактический результат — тот, который вы наблюдаете 
http://wowroad.info/?spell=69762 кидается на 5 хилов.
**Как должно работать?**
http://wowroad.info/?spell=69762 Кидается МАКСИМУМ на 2 хилов.
Ожидаемый результат — то, чего вы ожидали при выполнении ваших действий. Процесс правильной работы

**Шаги для воспроизведения ошибки:**

1. Собрать рейд 25 hm и попробовать убить Синдрагосу в 5 хилов рейдом 6,1-6,2к гс.
2. Узреть 5 освобожденок на 5 хилах.
3. Страдать.

**Текущее обновление ядра:**

Можно посмотреть в игре, введите в чат команду .server info и скопировать строку начиная с Build с номером и датой. Не забывайте указывать, Live Server или PTR Server, где проводилось тестирование.

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by gmKroshka** [comment]
Пруфы бы увидеть

**Comment by Knaufbest** [comment]
https://www.youtube.com/watch?v=-Fsy4TbCVBg 
https://www.youtube.com/watch?v=mmD_Wrnbe0c&t=128s 
Пара отличных гильдий своего времени. На обоих видео из рейда выбегает не больше двух хилов.
Второй момент: Радиус взрыва Освобожденки. На киркле она бахает за пол карты, что так же невозможно.

**Comment by gmKroshka** [comment]
Видео из двух рейдов не послужат доказательством. Нужна подтверждённая информация. Как и на счёт радиуса.

**Comment by Knaufbest** [comment]
И сколько мне нужно скинуть видосов с ютуба что бы поняли что босс работает не правильно?

**Comment by gmKroshka** [comment]
Видео не послужат доказательством) Я могу сделать такую подборку видео, после которой заявлю, что освобождёнка вообще не должна на хилов вешаться)
Откуда Вы вообще взяли цифру 2? Почему не 3? Почему не 1?

**Comment by Knaufbest** [comment]
На вовроаде, вовхеде, нет детальной механики каждого спела. Уже часа 4 рыщу. Тут уж извиняйте. Но изучив тонну видосов актуального времени можно понять что и как работает. Вчера мы снесли 10 боссов и за весь инст упало человек 5. Теперь синдрагоса сложнее Лича и Халиона. 
Объясняю почему именно 2: 8-9 лет назад на офе выходил очередной фикс синдрагосы и лича, и многие игроки того времени помнят про эту цифру. Если помните, лича убили позней осенью только спустя 1,5 месяца и после нескольких фиксов. Но не в этом суть.

Второй момент: давайте от обратного! Вы действительно считаете что освобожденка теперь должна висеть по кд на всех хилах? Мало того что хилить некому, так она еще рвет метров на 25. Убивать босса в 8 хилов+? Абсурд! Правда же?

**Comment by Knaufbest** [comment]
И тогда небольшая просьба: пусть этот вопрос обработает человек игравший на офе в актуальное время 3,3,0. Спасибо.

**Comment by sega693** [comment]
Механика хоть одного босса вообще делает различие между хилами и дд?

**Comment by Santaria94** [comment]
https://www.mmo-champion.com/threads/698132-Sindragosa-and-Unchained-Magic

> We didn't run a caster DPS for a few attempts and were only getting 1 at a time on each healer... then we got in a mage and suddenly it was 2 at a time 1 on the mage and 1 on a healer. Wonder if it's some mechanic Blizz implemented to stop 2 healers from getting it in 10 man.

> Unchained Magic is a 'smart' debuff, much like the -healing debuff ret pallies and enhance shamans receive on General Vezax. Each time it's cast, it's put on 1 healer and 1 ranged dps caster (ele sham, warlock, mage, spriest, boomkin). If there is no ranged caster, that instance of the debuff is skipped, and only a healer gets the debuff.

> It works like stated above
1 Caster DPS + 1 Healer is afflicted.
In the case of 0 Caster DPS (Hunters are excluded here, they get the melee debuff, Chilled to the Bone)
1 Healer is afflicted.
We downed her last night on 10-man, and I was the only Caster DPS present (Warlock). 100% Uptime on Unchained Magic on me during Groundphases, with no way to remove it. T'was great fun jumping around 50% of the time.
