### ISSUE TITLE
[Задание] ID 8484 - Знак мира

### ISSUE THREAD

**Issue by dmikhaylov-ru** [VirginTeam/WotlkCore#866]
**Ссылки и комментарии:**

квест Знак мира http://ru.wowhead.com/quest=8484

**Что работает не так?**
1. квест берётся при репе "Равнодушие" с фракцией Древобрюхи (http://ru.wowhead.com/faction=576)
2. в сумке есть квестовый предмет http://ru.wowhead.com/item=21155, но квест не возможно сдать

**Как должно работать?**
1. задание должно быть доступным только с репутацией "Превознесение" с Древобрюхами 

2. цитата с http://ru.wowhead.com/quest=8484

По завершении этого задания вы получите:

    14,175 опыта
    500 репутации с Альянс

**Шаги для воспроизведения ошибки:**

1. на момент получения квеста моя репутация с Древобрюхами "Равнодушие"
2. квест берётся у http://ru.wowhead.com/npc=11555
3. перемещаемся в Стальгорн, пытаемся сдать http://ru.wowhead.com/npc=2784

**Текущее обновление ядра:**

Build 194 2018-03-26 13:15:58 +0400

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by ForesterDev** [comment]
Исправлено

**Comment by zyxellgit** [comment]
![World Of Warcraft Screenshot 2019 05 29 - 00 51 45 90](https://user-images.githubusercontent.com/29210390/59149802-c5529680-8a33-11e9-8c2d-fdfeddc4508c.png)
а чо не сдается
