### ISSUE TITLE
[Общая механика] Призыв петов и сброс кд

### ISSUE THREAD

**Issue by Gooldark** [VirginTeam/WotlkCore#87]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Что работает не так?**

При призыве(дисмаунт не в счет) Призыв стража Скверны(ID 30146), Призыв охотника Скверны(ID 691), Призыв суккуба(ID 712), Призыв демона Бездны(ID 697), Призыв беса(ID 688), Воскрешение мертвых(ID 46584) у петов не сбрасывается кд.

**Как должно работать?**

При призыве(дисмаунт не в счет) Призыв стража Скверны(ID 30146), Призыв охотника Скверны(ID 691), Призыв суккуба(ID 712), Призыв демона Бездны(ID 697), Призыв беса(ID 688), Воскрешение мертвых(ID 46584) у петов должно сбрасываться кд.

**Шаги для воспроизведения ошибки:**

1. Вызвать пета
2. Использовать спел пета с большим кд
3. Перепризвать

**Текущее обновление ядра:**

11.04.2017 птр 21 билд

**Доказательства**

http://www.warcraftmovies.com/movieview.php?id=149601
18:41 - пет дает кс, лок юзает фелдом зовет пета, у пета фул хп и сброшены кд. Правда вот дебафы остались, но не все, стана нету от ресуммона и дебафа от геры.

http://www.warcraftmovies.com/movieview.php?id=160059
3:12 секунд дк отдает отгрызть магу и взрывает пета далее 3:50 сек дк вызывает пета и отгрызть не на кд.( кд на вызов пета 30 секунд , на отгрызть 1 минута).

**Перенесено**

http://forum.wowcircle.com/showthread.php?t=373329

**Comment by kalipsa988** [comment]
у локов починили, закройте
