### ISSUE TITLE
[Предмет] ID 38914 - Свиток чар для плаща - броня III

### ISSUE THREAD

**Issue by kalambyr18** [VirginTeam/WotlkCore#871]
**Ссылки и комментарии:**

http://db.logon3.com/?item=38914
http://db.logon3.com/?item=10518

**Что работает не так?**

При попытке зачарить , пишет цель низкого лвл .

**Как должно работать?**

Должен чарить . Плащ 45 лвл 

**Шаги для воспроизведения ошибки:**

Взять свиток с чаркой и попробовать зачарить плащ.

**Текущее обновление ядра:**

build 194 2018-03-26

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by ForesterDev** [comment]
http://db.logon3.com/?item=38914
Требуется предмет для персонажей не ниже 35-го уровня

http://db.logon3.com/?item=10518
Требуется уровень: 20

Все верно

**Comment by kalambyr18** [comment]
Да, но вот чарка http://db.logon3.com/?item=38940 на данном плаще http://screenshot.ru/upload/image/afXb . А вот http://ru.wowhead.com/item=10518 без ограничения по лвл на данный плащ с соотв комментарием про чарку на 12 ловкости "Awesome cloak. I just made it and equiped it at level 20. This can be very useful on many long jumps of cliffs like the ones in AB and also retain full health after rezing in WSG and jumping off that ledge to get back to midfeild. I am working on the mats for 12 Agi ench for this cloak since the cloak is a level 45 item. For those thinking about leveling Eng to get this item for the 20-29 BG bracket I would highly recomend it. It cost me on the thrall server just around 150 gold to level from 0 to 225 Eng (after selling back some stuff I crafted). Wich is not bad being that you can spend 100g on other cloaks such as Tigersrtike //www.wowhead.com/?item=13108 wich can not have the +12 Agi ench added and is also ugly as sin.." Также в базе http://wowroad.info/?item=10518 на данный плащ нет ограничения по лвл

**Comment by kalipsa988** [comment]
из-за ручных привязок шмота к лв не вешаются многие чарки, которые должны вещаться, поэтому пробуй чарить их обменом, а не свитками
