### ISSUE TITLE
[Задание] ID 12572 - Боги любят блестящие штучки

### ISSUE THREAD

**Issue by Hellsingoff** [VirginTeam/WotlkCore#872]
**Ссылки и комментарии:**

[Боги любят блестящие штучки](http://db.logon3.com/?quest=12572)

**Что работает не так?**

Нечего выкапывать. Блестящих объектов нет.

**Как должно работать?**

Блестящие объекты должны присутствовать. Их должен выкапывать призываемый игроком NPC.

**Шаги для воспроизведения ошибки:**

1. Шаг один
Взять задание
2. Шаг два
Призвать моба
3. Шаг три
Не обнаружить ни одной блестяшки

**Текущее обновление ядра:**

Build 194 2018-03-26 13:15:58 +0400
Лайв

_Без этого задания невозможен ачив на задания в низине, а значит и любой иной ачив на хранителя мудрости_

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by Pavlov718** [comment]
Уже есть репорт по этому кв https://github.com/VirginTeam/WotlkCore/issues/838
Надеемся починят в скором времени
