### ISSUE TITLE
Не выпадает колье нежизни из иссхоших троллей

### ISSUE THREAD

**Issue by prokvust** [VirginTeam/WotlkCore#874]
**Ссылки и комментарии:**

Колье http://ru.wowhead.com/item=38660 http://db.logon3.com/?item=38660

**Что работает не так?**

Нет в луте после убийства 50+ иссохших троллей (шанс по wowhead 11%, БД логона 3 100%)

**Как должно работать?**

Выпадать с первого - второго иссохшего тролля

**Шаги для воспроизведения ошибки:**

Убил более 50 троллей

**Текущее обновление ядра:**

Live server Build 194 2018-03-26 13:15:58 +0400

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by prokvust** [comment]
Проквуст. тикет дважды писал, про выполнение квеста тоже смотрели. Сказали еще пофармить, если не выпадет - написать тут

**Comment by prokvust** [comment]
Тоже нет, сейчас еще попробую

**Comment by prokvust** [comment]
Может это как то связано с тем что очищение драк тарона висит в списке выполненных, но не сдано ?

**Comment by prokvust** [comment]
Сдам, отпишу после результат

**Comment by prokvust** [comment]
"Змеевидное колье" выпало после завершения квеста "очищение драк'тарона"

**Comment by gmKroshka** [comment]
Замечательно. Удачи в выполнении заданий
