### ISSUE TITLE
[Рейды] Плато солнечного колодца

### ISSUE THREAD

**Issue by zyxellgit** [VirginTeam/WotlkCore#883]
**Ссылки и комментарии:**

**Что работает не так?**

у всех боссов иммун к глубокая рана http://db.logon3.com/?spell=48574  и разорвать http://db.logon3.com/?spell=49800 
![wowscrnshot_041718_002816](https://user-images.githubusercontent.com/29210390/38831726-b97264f6-41d9-11e8-9bc9-55f72100c7ae.jpg)
![wowscrnshot_041718_002831](https://user-images.githubusercontent.com/29210390/38831775-df60d724-41d9-11e8-8f6c-0cf2d30383dd.jpg)
 

**Как должно работать?**

пруфов обратного не искал ибо к.м.к это очевидно

**Текущее обновление ядра:**
Build 194 2018-03-26 13:15:58 +0400

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by kalipsa988** [comment]
в #856 всё это описанно

**Comment by zyxellgit** [comment]
по поиску "плато" не нашел,
ок выпиливаюсь
