### ISSUE TITLE
[Задание] ID 15000 - Миссия: Монастырь Алого ордена

### ISSUE THREAD

**Issue by junked** [VirginTeam/WotlkCore#884]
Квест: Миссия: Монастырь Алого ордена

Перепутали собор с библиотекой.

<a href="http://piccy.info/view3/12253455/733b74309a46b6835f786f49aceb3c64/1200/" target="_blank"><img src="http://i.piccy.info/i9/6f1734c44f90a2352387074d4cc1a2c6/1523916378/60022/1237794/Snymok_ekrana_2018_04_17_v_0_59_02_800.jpg" alt="Piccy.info - Free Image Hosting" border="0" /></a><a href="http://i.piccy.info/a3c/2018-04-16-22-06/i9-12253455/800x450-r" target="_blank"><img src="http://i.piccy.info/a3/2018-04-16-22-06/i9-12253455/800x450-r/i.gif" alt="" border="0" /></a>

**Comment by ForesterDev** [comment]
Исправлено, будет применено в обновлении
