### ISSUE TITLE
[Подземелья] Сила Ринна не распространяется на Слово Силы: Щит

### ISSUE THREAD

**Issue by Ziamba** [VirginTeam/WotlkCore#885]
Описание:
Усиление Сила Ринна (http://db.logon3.com/?spell=60964) в рейдовом подземелье Цитадель Ледяной Короны не работает на поглощение от заклинания жреца Слово Силы: Щит (http://db.logon3.com/?spell=48066).
Во внутриигровом описании усиления Сила Ринна (http://db.logon3.com/?spell=60964) присутствует строка "Эффект исцеляющих и поглощающих заклинаний усилен на 30%".
Для жреца послушания этот эффект не работает для заклинания Слово Силы: Щит (http://db.logon3.com/?spell=48066).

Фактический результат:
Объем поглощения от Слова Силы: Щит не меняется вне зависимости от того, действует ли на игрока усиление Сила Ринна в подземелье Цитадель Ледяной Короны или нет.

Ожидаемый результат:
Эффект усиления Сила Ринна, исходя из внутриигрового описания, должен увеличивать объем поглощаемого урона от Слова Силы: Щит на 30%.

Шаги для воспроизведения ошибки:

1. Войти в игру персонажем класса жрец 80-го уровня.
2. Установить на вкладке Символы панели Таланты Символ слова силы: Щит (http://db.logon3.com/?item=42408)
3. Пригласить в группу любого другого персонажа, создать рейд.
3. Подойти ко входу в подземелье Цитадель Ледяной Короны (http://db.logon3.com/?zone=4812), не заходя внутрь.
4. Используя заклинание Слово Силы: Щит (http://db.logon3.com/?spell=48066) добиться НЕкритического эффекта исцеления от символа (http://db.logon3.com/?item=42408). Запомнить/записать значение.
5. Войти в подземелье (http://db.logon3.com/?zone=4812).
6. Повторить действия из п. 4.
7. Убедиться, что значения, полученные в п. 4. и п. 6. почти идентичны. Ожидаемое различие - 30%.

8***. (Альтернативный вариант) Посмотреть поглощение Слово Силы: Щит (http://db.logon3.com/?spell=48066) можно, используя сторонние Адд-оны (Recount, Skada). 
Для этого необходимо, повесив только 1 заклинание Слово Силы: Щит (http://db.logon3.com/?spell=48066), не имеющее критического исцеления от символа, получать урон от существ в Цитадели Ледяной Короны до спадения щита. А после повторить эксперимент вне подземелья.
И посмотреть поглощение в соответствующей вкладке Адд-она.

Текущее обновление ядра:
Build 194 2018-03-26 13:15:58 +0400

**Comment by Morfem** [comment]
https://github.com/VirginTeam/WotlkCore/issues/148 предыдущая тема по абсорбу: "В зонах, где нет среза хила на аренах, должен быть невидимый модификатор который увеличивает количество абсорба для этих спелов на 30%. Данный модификатор заменяется на срез хила на аренах, и заменяет баф цлк при их наличии." Т.е. абсорб и должен быть одинаковым в ЦЛК и вне её.

**Comment by Ziamba** [comment]
Проверил для Слова Силы Щит. Объем поглощения такой, как должен быть по формуле, указанной в #148. Действительно действует 30% усиление и в ЦЛК, и вне его.
