### ISSUE TITLE
[Задание] ID 2399 - Росток папоротника

### ISSUE THREAD

**Issue by ghost** [VirginTeam/WotlkCore#886]
**Ссылки и комментарии:**

1) http://db.logon3.com/?npc=2080
2) http://db.logon3.com/?object=7510

**Что работает не так?**

Квест сдается сразу при принятии у NPC Деналан (ссылка 1)

**Как должно работать?**

Должен сдаваться объекту Росток папоротника (ссылка 2)

**Шаги для воспроизведения ошибки:**

1. Выполняем преквест http://db.logon3.com/?quest=931
2. Берем квест.
3. Видим сразу кнопку "Завершить"

**Текущее обновление ядра:**

Сервер: 3.3.5 х1 PVE
Build 194 2018-03-26 13:15:58 +0400

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by gmKroshka** [comment]
Будет исправлено после обновления
