### ISSUE TITLE
[Предмет] ID 44508 - Discovery!

### ISSUE THREAD

**Issue by gmLanoressa** [VirginTeam/WotlkCore#887]
**Ссылки и комментарии:**

http://db.logon3.com/?item=44508

**Что работает не так?**

Не изучается рецепт.

**Как должно работать?**

Должна обучать случайному новому рецепту алхимии

**Шаги для воспроизведения ошибки:**

1. Получаем данный предмет (Исследование трав Нордскола 5.6% или покупаем с рук (она БоЕ))
2. Используем

**Текущее обновление ядра:**

Сервер: 3.3.5 х1 PVE
Build 194 2018-03-26 13:15:58 +0400

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by Santaria94** [comment]
http://ru.wowhead.com/item=44508/discovery#comments судя по комментам ничего оно открывает, все правильно работает.

**Comment by gmLanoressa** [comment]
Посмотрите внимательнее комментарии:

После очередного патча возникла проблема - перестали открываться рецепты. Раньше на каждое исследование приходилось по открытию. Теперь же уже 5 "пять" раз подряд никаких открытий - только рандомно сваренные флаконы. Мне посоветовали проверить, может я уже все, что можно открыла. На вовхеде данных по возможностям открытия не об

Не знаю, после кул дауна создает как новые зелья, так и старые, и дает новый рецепт.

Появляется у алхимиков автоматически, прокает при крафте эликсиров из трав Запределья и выше.

Не работает, если выучены все рецепты, открывающиеся при Исследовании трав Нордскола.
 
На старом ядре у нас (до 14го года) работало, кстати. Я им в алхимке пару зелий открывала. А вот в катаклизме ее работоспособность убрали.

**Comment by Santaria94** [comment]
На wowhead комментарии именно со времен лича указывают на то, что ничего с этого предмета не изучается:

"использовал этот рецепт, в результате получил не новый какойто рецепт, а просто 2 элика инты на 70 лвл, чтото я не до конца понимаю смысл этой "Находки!"" (Обновление 3.0.3)

"Да уж... близзы напороли с "находкой" 
Ничего не открывается... что с ней делать с этой находкой теперь уже не особо понятно..." (Обновление 3.1.3)

"Появилась во время очередного "Иследования..."
Похоже теперь она бесполезна, так как ничего не даёт..." (Обновление 3.3.0)

---------------

Не знаю, что у вас там работало на старом ядре. Старое ядро - это то, что стоит и сейчас на л1. Вот комментарий с их базы 2013 года - ""Появляется у алхимиков при http://wowway.ru/?spell=60893. Не даёт ничего, только место в сумке занимает. Если не юзается, можно смело выкидывать.""

**Comment by ForesterDev** [comment]
Не должен ничему обучать. Обычная пустышка. Локализацию поправлю
