### ISSUE TITLE
ежедневный квест "месяц" делать??

### ISSUE THREAD

**Issue by lishker** [VirginTeam/WotlkCore#888]
http://ru.wowhead.com/quest=12704
http://ru.wowhead.com/npc=28122
http://ru.wowhead.com/item=38575

не возможно найти места где npc выкапывает Драгоценные блестя а если и найдешь хоть одно том обязательно жуки

нужно подвести Мульда к условному месту где блестит и он выкопает жука,зайца или Драгоценные блестяшки

Build 194 2018-03-26 13:15:58 +0400

**Comment by gmKroshka** [comment]
Не нужно дублировать репорты.
