### ISSUE TITLE
[Группа заклинаний] Призыв вурдалаков Рыцаря Смерти

### ISSUE THREAD

**Issue by Gooldark** [VirginTeam/WotlkCore#89]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Что работает не так?**

а) Неверное время простоя при призыве Воскрешение мертвых(ID 46584)(на данный момент 5 сек) Так же отсутствует анимация для окружающих.

б) Для Войско мертвых(ID 42650) отсутствует время простоя

**Как должно работать?**

а) Время простоя должно быть 4,165 сек, для окружающих должна быть показана анимация(код Birth[22]).

б) У Войско мертвых(ID 42650) тоже должно быть время простоя

**Текущее обновление ядра:**

11.04.2017 птр 21 билд

**Доказательства**

а) У анимации Birth[22] 4165 фремов, 1 фрейм = 1 мс
http://www.fotohost.by/image/2AOE

б) http://www.warcraftmovies.com/movieview.php?id=154835 - 7:23 видно как дк вызывает вурдалаков и они вылезают из земли.

**Перенесено**

http://forum.wowcircle.com/showthread.php?t=499273

**Comment by ForesterDev** [comment]
- пункт б исправлен

**Comment by zyxellgit** [comment]
а еще все вурдалаки сбегаются в 1 точку, и получается вместо войска!! 1 вурдалак (визуально)
![wowscrnshot_062717_181845](https://user-images.githubusercontent.com/29210390/27646090-32ad29c0-5c41-11e7-8981-7923e6dd1bdd.jpg)

**Comment by zyxellgit** [comment]
ура, бегает толпа!!а Гулдарк говорил "Еще лет 5 пройдет когда это будут фиксить, а то и больше, так как это очень сложная механика, при этом не значительная."
прошло всего 14 месяцев

**Comment by Gooldark** [comment]
И что там исправилось? Теперь просто 3 точки появилось к которым бегут вурдалаки, и это кривая заплатка которую лучше не ставить. По тому что на офе все нпс при атаке/преследовании стараются занять свободную точку у цели, и пока цель не будет окружена нпс не будут становиться друг в друга, так что тут еще править и править.

**Comment by nikalight** [comment]
там ещё скалирование хп у вурдалаков не работае :)

**Comment by Kodekc** [comment]
Перепроверьте и создайте отдельный репорт на эту проблему.
