### ISSUE TITLE
[Игровая механика] Выбор цели слизняками (Профессор Мерзоцид)

### ISSUE THREAD

**Issue by Rorshah** [VirginTeam/WotlkCore#894]
**Ссылки и комментарии:**
25гер версия рейда.

Слизни на профЕ:
http://db.logon3.com/?npc=37562
http://db.logon3.com/?npc=37697

**Что работает не так?**

Зеленый выбирает с зеленым дебафом. 
Красный выбирает с красным дебафом

**Как должно работать?**

Слизни выбирают цель независимо от дебафа
Лог с офа:

2476 | 27 Jun 2010 | 08:32 | 72.08M | 140728.6 | Mental | EU-Nordrassil

http://www.worldoflogs.com/reports/rt-3b2o27q08vd9dxmb/xe/?s=12577&e=13089&x=spell+%3D+%22Gas+Variable%22%0D%0AOR+sourceName+%3D+%22Gas+Cloud%22%0D%0AOR+spell+%3D+%22Ooze+Variable%22%0D%0AOR+sourceName+%3D+%22Volatile+Ooze%22

```
....
[21:49:10.676] Thewuch afflicted by Ooze Variable from Thewuch
...
[21:49:25.230] Thewuch afflicted by Gaseous Bloat from Gas Cloud
...
[21:49:27.289] Gas Cloud's Gaseous Bloat (9) fades from  Thewuch
[21:49:27.289] Gas Cloud Gaseous Bloat  Thewuch 16607 (R: 1812)
[21:49:29.193] Gas Cloud's Gaseous Bloat (8) fades from Thewuch
[21:49:29.193] Gas Cloud Gaseous Bloat Thewuch 11247 (R: 3221)
...
```
Также в сети есть и видео времен лича где такой фокус прослеживается.

## Важно не переусердствовать!!
**Слизни не должны выбирать одну и туже цель, как оно было однажды на нашем сервере.**

**Шаги для воспроизведения ошибки:**

Сходить в 25гер, дожить до переходки.

**Текущее обновление ядра:**

Build 194 2018-03-26

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by Rorshah** [comment]
Вроде "Судя по описанию самих заклинаний дебафа" никогда не работало у нас.

Вот тайминг и видео с оффа, раз логи читать нет возможности:

Определяем баф и таргет по фреймам рейда.
1:30 - Шаман с зеленым дебафом - его выбирает оранжевый слизень.
1:40 - Паладин с зеленым дебафом - его выбирает оранжевый слизень.
6:53 - Паладин с оранжевым дебафом - его выбирает зеленый слизень.
7:01 - Шаман с зеленым дебафом - его выбирает оранжевый слизень.
7:06 - Друид с оранжевым дебафом - его выбирает зеленый слизень.
https://www.youtube.com/watch?v=SJHO6DptO9Q

**Comment by Kodekc** [comment]
Протестируйте, должно работать, цвет слизня должен соответствовать дебафу, либо смысл от этого дебафа утрачивается

**Comment by Rorshah** [comment]
смысл дебафа что полрейда бьет одного слизня, а вторые полрейда другого.
Однако сам слизень волен выбирать рандомную цель. Судя по логам и видео с офа.
У нас слизни выбирают по цвету. И это НЕправильно.

**Comment by Kodekc** [comment]
Почему не правильно то, когда описание дебафа говорит об обратном?

**Comment by Rorshah** [comment]
Есть логи. Есть видео. С официального сервера Близард времен wotlk.
Все эти вещи говорят что цель выбирается рандомно. По факту.
Не глядя на описание.
Этому есть объяснение ?
Если нет, то необходимо сделать близлайк не взирая на описание.

**Comment by Rorshah** [comment]
Как вариант могу предложить такое решение данного казуса:
В обычке выбирает по цвету.
В герах (откуда логи и видео) выбирает не взирая на дебаф.
А так как база пиратская в описании дебафа по тупому не стали ничего менять и геровский дебаф по ошибке скопирован с обычки.

**Comment by xARCHIMEDESx** [comment]
https://www.youtube.com/watch?v=ys7epFlq2zA&feature=youtu.be&t=2m16s
Приста выбирает красный, друля - зеленый, на них обоих красный дебаф
На 2 переходке уже по цвету выбирает
Смотрел еще другое видео, где так же двух человек с одним цветом выбирают разные слизни
Мне кажется, пруфов достаточно, что б твердить, что выбор слизня - рандомный и не зависит от цвета дебафа цели

**Comment by Rorshah** [comment]
https://youtu.be/ScEF0k-f6r8?t=153
Вот еще видео, где у красного слизня на переходке в таргете паладин с зеленым дебафом.

Просто можно взять любое видео того времени и там будет видно что слизни выбирают рандомную цель.
Дебаф влияет только на урон игроков: бьют слизня согласно цвета своего дебафа.

**Comment by Rorshah** [comment]
"Уточнить детали" - поставьте вопрос, что непонятно ? Что уточнять ?

**Comment by Kodekc** [comment]
Накидайте в репорт ссылки на видео/логи и прочее, я передам информацию разработчику

**Comment by MedoOf** [comment]
Не забудьте про то что у нас в 10гер существует баг когда 2 слизня могут выбрать 1 цель, если это же всплывет в 25, то будет не слишком хорошо

**Comment by Rorshah** [comment]
по трем видео, мне кажется, можно сделать выводы.
В конце концов не все же снимали видео своих убийств профессора.
Не стоит затягивать. 
У профессора-гер есть еще баг с паловским диваном, есть баг с уроном красного слизня по рейду.
Все это есть на гитхабе. Каждый из этих трех багов меняет тактику на убийство профессора. 
Вплоть до трех танков вместо двух сегодняшних.

**Comment by Rorshah** [comment]
https://youtu.be/9VSAzlYMAWU?t=106 вот тут зеленый кидается на чувака с красным дебафом. Вобщим видео миллион, просто не везде рейд-фреймы позволяют определить дебаф на цели. Но как я вижу вообще можно брать рандомный бой/видео и там такой факт, как выбор цели слизня безотносительно дебафа - будет проявляться.

**Comment by Kodekc** [comment]
Это только так себя ведут в 25гер?

**Comment by Rorshah** [comment]
А эта фишка с двумя слизнями на переходке и дебафами на игроках только в 25 гер и есть.

**Comment by xARCHIMEDESx** [comment]
В 10гер же 2 слизня но без дебафов, нет?

**Comment by Rorshah** [comment]
два слизня но без дебафов да. Соответственно там ошибки нет - слизни выбирают и так рандомно.

**Comment by xARCHIMEDESx** [comment]
Ну вот, репорт касается только режима 25гер, пруфов, думаю, достаточно.

**Comment by Rorshah** [comment]
ну оно так и было написано в стартовом сообщении. 25гер. важно не переусердствовать, чтобы слизни не выбирали одного игрока одновременно.

**Comment by Rorshah** [comment]
Что-то еще нужно уточнять ?

**Comment by Rorshah** [comment]
Если убрать метку "Уточнить детали" и добавить метку "ЦЛК" репорт починится быстрее ?

**Comment by Kodekc** [comment]
Применены изменения, требуется тестирование
