### ISSUE TITLE
[Задание] ID 592 - Спасение Йеннику

### ISSUE THREAD

**Issue by gmKroshka** [VirginTeam/WotlkCore#895]
**Ссылки и комментарии:**

[Спасение Йеннику](http://db.logon3.com/?quest=592)
[Самоцвет Души](http://db.logon3.com/?item=3912)

**Что работает не так?**

При использовании [Самоцвет Души](http://db.logon3.com/?item=3912) на [Йеннику](http://db.logon3.com/?npc=2530) по НПЦ проходит большой урон и он погибает
`Kroshka начинает использовать "Освобождение Йеннику".
"Освобождение Йеннику" Kroshka наносит Йеннику 1903 единицы урона от темной магии (избыточный урон: 1667).
Kroshka убивает Йеннику!
Йеннику погибает.`
`Kroshka начинает использовать "Освобождение Йеннику".
"Освобождение Йеннику" Kroshka наносит Йеннику 1903 единицы урона от темной магии (избыточный урон: 1397).
Kroshka убивает Йеннику!
Йеннику погибает.`
Задание выполнялось персонажем 80го уровня. Если с персонажа снять экипировку, задание выполняется, НПЦ не погибает
`Wunderbar начинает использовать "Освобождение Йеннику".
"Освобождение Йеннику" Wunderbar наносит Йеннику 1 единицу урона от темной магии.`

**Как должно работать?**

Использование [Самоцвет Души](http://db.logon3.com/?item=3912) на [Йеннику](http://db.logon3.com/?npc=2530) не наносит смертельного урона вне зависимости от уровня и экипировки персонажа.

**Шаги для воспроизведения ошибки:**

1. Взять задание
2. Использовать итем на НПЦ

**Текущее обновление ядра:**

Build 194 2018-03-26 13:15:58 +0400

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by IssueCreatorCircle335** [comment]
Выполнял задание Варом 80-го уровня. НПС не умирал.
Есть подозрение что спелл от "Самоцвет Души" берет из статов персонажа СПД, соответственно урон идет намного больше необходимого.

**Comment by Hellsingoff** [comment]
Одетый маг - ваншот при использовании самоцвета
Голый маг - 1 урона от темной магии, квест пройден.

**Comment by gmKroshka** [comment]
Будет исправлено после обновления
