### ISSUE TITLE
Задание "Обшарить трупы"

### ISSUE THREAD

**Issue by dmikhaylov-ru** [VirginTeam/WotlkCore#896]
**Ссылки и комментарии:**

http://ru.wowhead.com/quest=12000

**Что работает не так?**

Неделю хожу по локации, обшариваю эти трупы. За раз прохожу по 7-10 респаунов. Процесс обшаривания выглядит ненормально: кликаю по трупу, он разворачивается и исчезает. Никакого лута с него не падает.

**Как должно работать?**
В ходе выполнения квеста, с трупов обязательно должен лутаться http://ru.wowhead.com/item=35792#created-by-spell, который с вероятностью в 10% должен содержать http://ru.wowhead.com/item=35783

**Шаги для воспроизведения ошибки:**

**Текущее обновление ядра:**

Build 194 2018-03-26 13:15:58 +0400 

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by gmKroshka** [comment]
Пользуйтесь поиском. Задание исправлено, ожидает применения

**Comment by dmikhaylov-ru** [comment]
ну, мало ли, там задание с id 11999 - ордынское =)
Спасибо! =)
