### ISSUE TITLE
[Задание] ID 12261 - Отрезать пути к отступлению

### ISSUE THREAD

**Issue by MiceRus** [VirginTeam/WotlkCore#908]
**Ссылки и комментарии:**

http://ru.wowhead.com/quest=12261
**Что работает не так?**
Волны мобов есть, Тотем заряжается.
Пишет - зарядка завершена ,но не засчитывается в результат

**Как должно работать?**

По окончании зарядки должно засчитать что тотем зарядился
**Шаги для воспроизведения ошибки:**

1. Берем квест у НПЦ http://ru.wowhead.com/npc=26593
2. Бежим на точку, указанную в тексте и вызываем Тотем уничтожения
3. Отбиваем атаки мобов, во время которых тотем заряжается.
4. Появляется надпись Тотем уничтожения полностью заряжен!, но в квесте так и не засчитывается

**Текущее обновление ядра:**
22:32:03] Logon 3 WowCircle Development
[22:32:03] Последнее обновление ядра: Build 197 2018-04-23 12:44:18 +0400

**Comment by SergeyVyach** [comment]
поправьте, пожалуйста. обрывает цепочку

**Comment by CONSOLNY** [comment]
Квест не засчитывается

**Comment by Mystic1813** [comment]
не засчитывается

**Comment by ForesterDev** [comment]
Исправлено. Будет применено в обновлении
