### ISSUE TITLE
Поиски древнего героя задание

### ISSUE THREAD

**Issue by Adrinalinio** [VirginTeam/WotlkCore#909]
Поиск Древнего Героя

http://ru.wowhead.com/quest=13170

Не берется под контроль

После окончания каста на амулета моб просто исчезает

**Как должно работать?**
Пробудить спящего мьордина и с некоторой вероятностю пробудится Искальдер, послечего на нем же нужно использовать Амует костяной ведьмы, моб должен взятся пож контроль и его нужно привести к костяной ведьме.
Ожидаемый результат — Взятие под Контроль Искальдера.

**Шаги для воспроизведения ошибки:**

1) Берете квест у Костяная ведьма.
2) Заходите в 28, 47. Внутри находите спящих и пробуждаете их. С некоторым шансом одним из таких спящих окажется Искальдер. Как только увидите его, используйте амулет, который дала колдунья. 
**Текущее обновление ядра:**
Build 197 2018-04-23 12:44:18 +0400

**Comment by gmKroshka** [comment]
Вы уверены в ссылке на задание?

**Comment by MiceRus** [comment]
Ссылка не верна.
И такая заявка уже есть https://github.com/VirginTeam/WotlkCore/issues/216
