### ISSUE TITLE
[Подземелье] Вершина Утгард (ID 26693 Скади Безжалостный)

### ISSUE THREAD

**Issue by gmRial** [VirginTeam/WotlkCore#91]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Босс (ID 26693) работает некорректно.

**Что работает не так?**

Босс не агрится, убивает первого в агролисте, после его смерти продолжает на него агриться (в таргет не берет). Но во время действия заклинания Вихрь (ID 50228) босс берет одного из членов группы в таргет, после чего агрится на того, кого убил первым. 

**Как должно работать?**

Босс должен агриться и работать как и все остальные.

**Шаги для воспроизведения ошибки:**

1. Запустить ивент.
2. Пережить 3 волны.
3. Выстрелить гарпунами в босса.
4. Пытаться сагрить босса после приземления.

**Текущее обновление ядра:**

Virgin: Build 151 2017-04-03 15:25:08 +0400

**Comment by Riazarre** [comment]
На текущий момент, Build 163 - не работает.
Работает на тринити, предлагаю взять оттуда. Босс корректно агрится, хитбокс босса в норме, у нас же он завышен.

**Comment by Santaria94** [comment]
Также у босса есть ошибка в лут-листе.
http://db.logon3.com/?item=44151 на данный момент падает также и в обычном режиме сложности, хотя должно падать только в героическом.

**Comment by gmKroshka** [comment]
Будет исправлено после обновления
