### ISSUE TITLE
[Заклинание] ID 48113 - Молитва восстановления

### ISSUE THREAD

**Issue by Jigglypuff715** [VirginTeam/WotlkCore#910]
**Ссылки и комментарии:**
Разрешено или нет, но вот http://forum.wowcircle.com/showthread.php?t=456388
http://db.logon3.com/?spell=48113 Собственно адски занижен хпс хприста и дц на личе 25 гер из-за не работающего в комнате этого спела. В пвп так же есть трудности ибо нельзя разогнать молитву с помощью свд.

**Что работает не так?**

Не срабатывает при нанесении урона от некоторых способностей игроков и боссов. Проверено что не срабатывает от аое в комнате на личе в героике http://db.logon3.com/?spell=73655 (кажется эта ссылка) и от http://db.logon3.com/?spell=48158. 

**Как должно работать?**

Молитва должна срабатывать при получении любого урона и лечить персонажа. В комнате перескакивать с игрока на игрока хиля каждого при любом получении урона.

https://wow.gamepedia.com/Prayer_of_Mending

Prayer of Mending (PoM) is a reactive priest healing buff similar to [Earth Shield]. 
It will not actually heal the target when cast on them, but instead place a buff on the target. 
When the buffed target takes any damage, the buff will heal the target, and move to another 
random raid member within 20 yards. The buff has 5 charges, and will not proc from 
environmental damage (falling, lava, fatigue, etc) nor damage that is absorbed, such as 
with [Power Word: Shield] or [Divine Aegis]. Spells that reduce the caster's own HP such 
as Warlock [Life Tap] will not proc PoM, although any spells that actually cause damage to 
the caster, such as warlock [Hellfire], will still proc the effect.
Heals from Prayer of Mending can crit.
Prayer of Mending does not proc from absorbed damage. This creates an antagonistic relationship between PoM and shields such as  [Power Word: Shield]. PoM's 30-second duration allows it to outlast a single PW:S cast, although heals from Discipline priests will still proc Divine Aegis on targets.
**Шаги для воспроизведения ошибки:**

1. Бафаемся молитвой.
2. Кастуем свд слово тьмы смерть или топаем в комнату на личе гер.
3. Молитва не хилит и не снимается.

**Текущее обновление ядра:**

Можно посмотреть в игре, введите в чат команду .server info и скопировать строку начиная с Build с номером и датой. Не забывайте указывать, Live Server или PTR Server, где проводилось тестирование.

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by Jigglypuff715** [comment]
Build 197 2018-04-23 12:44:18 +0400 
х1 pve

**Comment by ForesterDev** [comment]
Исправлено
