### ISSUE TITLE
[Заклинание] ID 48113 - Молитва восстановления

### ISSUE THREAD

**Issue by Trombocid** [VirginTeam/WotlkCore#912]
**Ссылки и комментарии:**

Взаимодействие двух http://db.logon3.com/?spell=48113 от разных игроков на одной цели.

**Что работает не так?**

Молитва от одного игрока на какой-либо цели заменяется молитвой от иного игрока просто пропадая. 

**Как должно работать?**

Обе молитвы должны остаться на цели и сработать. Полагаю корень зла аналогичен древней проблеме хпалов с их частицей, когда аналогично одна частица просто заменяла другую. На данный момент, если я не ошибаюсь, баг исправлен и на одной цели могут спокойно висеть и работать две частицы. Если обратиться к тултипу абилки, ничего подобного, допустим, щиту земли рестор шамана, мы там не увидим. Т.е. не сработавшая молитва справедливо должна исчезнуть, если прист перекастует оную в ту или иную цель, но не должна пропадать, если в ту же цель бросает молитву второй прист.

**Шаги для воспроизведения ошибки:**

1. Бросаем в союзника молитву восстановления с одного приста;
2. Бросаем в ту же цель молитву восстановления со второго приста;
3. Первая молитва пропадает.

**Текущее обновление ядра:**

Build 197 2018-04-23 12:44:18 +0400

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by Kodekc** [comment]
https://github.com/VirginTeam/WotlkCore/issues/262

**Comment by ForesterDev** [comment]
https://wowwiki.fandom.com/wiki/Prayer_of_Mending

> Multiple ProMs on a target do not stack, even when cast by different priests.

> Patch 6.0.2 (14-October-2014): Prayer of Mending from multiple Priests can now be on the same target, and can be on multiple targets from the same Priest, but the ability has a 1.5-second cast time (up from instant cast).
