### ISSUE TITLE
[Задание]  - Очищение Кель'Делара

### ISSUE THREAD

**Issue by kumaramur** [VirginTeam/WotlkCore#914]
**Ссылки и комментарии:**

http://ru.wowhead.com/quest=24553#screenshots

**Что работает не так?**

После телепорта в инст подходим к колодцу, происходит короткий диалог, юзаем итем висящий в воздухе, он исчезает, но не появляется в сумке, закончить кв не возможно без итема. Антиэррор и очиска кэша не помогают

**Как должно работать?**

Диалог кажется должен быть дольше, мобы агрятся, потом понимают что все нормально, юзаем итем, получаем  "Восстановленный Кель'Делар
"и через телепорт отправляемся в Даларан сдавать квест.

**Шаги для воспроизведения ошибки:**

1. Берем квест http://ru.wowhead.com/quest=24553#comments у нпс на острове
2. Стражник телепортирует в инст
3. Спускаемся к колодцу

**Текущее обновление ядра:**

Logon 3 WowCircle Development
Build 197 2018-04-23 12:44:18 +0400

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by gmKroshka** [comment]
Проверяйте сегодня после установки хотфиксов

**Comment by kumaramur** [comment]
Это был хотфикс? Если да, то он не помог.

**Comment by gmKroshka** [comment]
Отмените задание и возьмите заново. Всё работает
