### ISSUE TITLE
[NPC] ID 23434 - Командир Хобб

### ISSUE THREAD

**Issue by deexeq** [VirginTeam/WotlkCore#915]
**Ссылки и комментарии:**

[Командир Хобб](http://db.logon3.com/?npc=23434)

**Что работает не так?**

Пропала текстура, виден только топор:
<a href="http://uploads.ru/AzRCK.jpg"><img src="http://s4.uploads.ru/t/AzRCK.jpg" border="0" /></a>

**Как должно работать?**

Должен быть виден.

**Текущее обновление ядра:**

Build 198 2018-04-24 18:25:21 +0400

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by MiceRus** [comment]
Он потому и не виден, что стыдно за отсутствие действия по квесту, который он дает :)

**Comment by Ewropa** [comment]
Командир вышел из тени, ожидайте обновления =)
