### ISSUE TITLE
[Игровая механика] - Выход из боя на ОЛО

### ISSUE THREAD

**Issue by ghost** [VirginTeam/WotlkCore#920]
**Что работает не так?**

При ливе с боя на ОЛО игрока не портует с ОЛО, он остается там и может совершать любые действия. При этом помимо зачета заданий ему идет в зачет на ачиву участие на ОЛО, дается знак ОЛО, засчитываются квесты и хонор, как полноценному участнику сражения.

**Как должно работать?**

Во время битвы за ОЛО игроков, находящихся вне рейда, участвующего в данном мероприятии, должно телепортировать из локации. Раньше ТПшило на границу между ОЛО и ЛК. По мне так в идеале было бы, чтобы телепортировало по месту привязки камня.

**Шаги для воспроизведения ошибки:**

1. Заходим на ОЛО
2. Принимаем приглашение.
3. Ливаем

**Текущее обновление ядра:**

build 198 2018-04-24

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by MiceRus** [comment]
А еще бы исправить поведение запроса на участие в сражении при пролете на "такси". Всегда, когда летишь на "такси" (не на персональном маунте) мимо ОЛО, тебя ТПшит в точку границы.

**Comment by Kodekc** [comment]
Эти моменты переписывались ранее, что из этого актуально, а что нет? Может кто-то предоставить свежую информацию?
