### ISSUE TITLE
[Заклинание] ID 70769 - Божественная буря!

### ISSUE THREAD

**Issue by Brigor5555** [VirginTeam/WotlkCore#923]
http://ru.wowhead.com/spell=70769

Заклинание "Божественная Буря" наносит маленький урон при экипировке с гсом 6,700

При заявленном уроне в информации о персонаже в размере 3322-4105
данный скил как минимум должен выдавать этот максимум

Ожидаемый результат — перерасчёт нанесения урона данным заклинанием

Шаги для воспроизведения ошибки: 
Шаг 1: Включите тексты боя
Шаг 2: Бейте манекен и вы удивитесь как много наносит данный скил у ретро паладина 

![wowscrnshot_042818_192329](https://user-images.githubusercontent.com/38813231/39398679-e177e2ca-4b19-11e8-8d2b-67d3f471b9fb.jpg)

Текущее обновление ядра:Build 198 2018-04-24 18:25:21 +0400

**Comment by Librariane** [comment]
Вовсе и не должен, поскольку
1. в характеристиках персонажа отображается обычный урон оружием, а урон Бури зависит от нормализованного урона оружием. И последний в случае ШМа со скоростью 3.7 будет меньше, поскольку рассчитывается по скорости 3.3 (как для двуручного оружия).
2. Буря наносит физический урон, соответственно он снижается броней цели. И это снижение ни в тултипе, ни в параметрах персонажа не отображается.
