### ISSUE TITLE
[Заклинание] ID 5782 - Страх

### ISSUE THREAD

**Issue by Zmei37** [VirginTeam/WotlkCore#924]
http://wowroad.info/?spell=5782

**Что работает не так?**

Ник: Лодочник
Лвл: 29
Раса: Гном
Класс: Чернокнижник
У заклинания Страх у лока кд после применения 30 сек, у остальных как и должно быть без кд

**Как должно работать?**

Без КД, скрины не знаю как тут кидать...(

**Comment by Zmei37** [comment]
![wowscrnshot_043018_225906](https://user-images.githubusercontent.com/38867970/39465148-7d576550-4d2a-11e8-84a3-43314cb94872.jpg)
![wowscrnshot_043018_225852](https://user-images.githubusercontent.com/38867970/39465179-a07b9b96-4d2a-11e8-8dd3-649bbc5f0487.jpg)
![wowscrnshot_043018_225849](https://user-images.githubusercontent.com/38867970/39465180-a098dff8-4d2a-11e8-95cf-3d6264734381.jpg)
![wowscrnshot_043018_225708](https://user-images.githubusercontent.com/38867970/39465181-a0b6a42a-4d2a-11e8-86bb-9943a6f3c1f9.jpg)
![wowscrnshot_043018_225857](https://user-images.githubusercontent.com/38867970/39465182-a0d418e8-4d2a-11e8-8dd4-347fedbee6bc.jpg)

**Comment by Zmei37** [comment]
не помогло...

**Comment by ForesterDev** [comment]
Переустановите клиент.
