### ISSUE TITLE
[Задание] ID 1719 - Побоище

### ISSUE THREAD

**Issue by Siritkam** [VirginTeam/WotlkCore#926]
**Ссылки и комментарии:**
Баг найден, играя за орду, за воина андеда
http://db.logon3.com/?quest=1719

**Что работает не так?**

В задании требуется встать на решётку, после чего появляются квестовые мобы, но
по факту, когда наступаешь на решётку, появляется сообщение, что это условие выполнено, но в журнале оно не отмечается как выполненное, в результате мобы необходимые для выполнения квеста не появляются, что само собой не позволяет выполнить квест и получить стойку берсерка.

**Как должно работать?**

Должно быть: попсле захода на рештку, зрители сидящие на трибунах у решетки поочередно начинают атаковать игрока, после победы над ними появляется главный квестовый моб [Большой Вилл](http://db.logon3.com/?npc=6238)

**Шаги для воспроизведения ошибки:**

1. Шаг один - взять квест "Побоище"
2. Шаг два - Наступить на решётку
3. Шаг три - убедиться в том что квест сломан

**Текущее обновление ядра:**
Build 198 2018-04-24, Live server
Можно посмотреть в игре, введите в чат команду .server info и скопировать строку начиная с Build с номером и датой. Не забывайте указывать, Live Server или PTR Server, где проводилось тестирование.

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by Kodekc** [comment]
**C++ Script:** ScriptName = npc_twiggy_flathead

**Comment by gmOverfire** [comment]
Будет исправлено после обновления.

**Comment by gmKroshka** [comment]
Проблема актуальна вновь

**Comment by Kodekc** [comment]
Существует ли ошибка до сих пор или скрипт отрабатывает нормально? Если есть ошибка, то требуются детали этой ошибки

**Comment by Kodekc** [comment]
Репорт закрыт, как исправленный, при тестировании не обнаружено ошибок. В случае, если проблема имеет место быть, добавьте алгоритм забагивания скриптов или последовательность действий, что делал ваш персонаж, что привело к ошибке.
