### ISSUE TITLE
[Игровая механика] Ауры паладина

### ISSUE THREAD

**Issue by MiceRus** [VirginTeam/WotlkCore#928]
**Ссылки и комментарии:**

http://ru.wowhead.com/spell=183425

**Что работает не так?**

http://db.logon3.com/?spell=10293

**Как должно работать?**

ГКД должен быть 0!

**Шаги для воспроизведения ошибки:**

Включить ауру благочестия и тут же попытаться включить любую другую ауру.
Получим сообщение о невозможности произнесения заклинания
Именно из-за этого непонятно откуда взявшегося ГКД на смену аур и не работают макросы связанные с аурами, взятые из http://worldof.ru/warcraft/paladin/paladin-macro
Если не хотите проверять, то уж поверьте - на всех ОФФ серверах эти макросы работают.
И даже на НЕОФФ (https://merlin.org.ua/wowhead2/?spell=10290)
Видео, демонстрирующее, что ДО одного из обновлений все хоть с костылем, но работало имеется 
http://forum.wowcircle.com/showthread.php?t=780807&p=6451756&viewfull=1#post6451756
**Текущее обновление ядра:**
[10:47:20] Logon 3 WowCircle Development
[10:47:20] Последнее обновление ядра: Build 198 2018-04-24 18:25:21 +0400

**Comment by MiceRus** [comment]
Не совсем понял - какое еще оформление требуется?
ГКД у аур паладина должно быть 0. Что еще нужно оформить-то?
Сейчас даже в базе сервера написан, что ГКД 1,5 секунды. Хотя ВСЕГДА в WOW ауры паладинов не имели ГКД вообще.

**Comment by Rorshah** [comment]
ну на вовхэде, к примеру, на ауры стоят разные ГКД.
Если у благочестия 0 секунд http://ru.wowhead.com/spell=183425
то у сосредоточенности 1,5 секунд. http://ru.wowhead.com/spell=79963
Другие не проверял.

**Comment by MiceRus** [comment]
Ту ауру, что Вы привели не используют паладины. Это аура НИПа.
Аура воина света - ГКД 0 - http://ru.wowhead.com/spell=39440
Аура благочестия - ГКД 0 - http://ru.wowhead.com/spell=183425
Аура воздаяния - ГКД 0 -http://ru.wowhead.com/spell=203797
Аура сосредоточенности - ГКД 0- http://wowroad.info/?spell=19746 (на вовхеде отсутствует ввиду упразднения ауры)
И так со всеми аурами.
Я не знаю ,откуда на ЛОГОН3 взяли ГКД аур. Это только админам известно

**Comment by gmOverfire** [comment]
http://ru.wowhead.com/spell=39440 - прокает от предмета http://ru.wowhead.com/item=31856
http://ru.wowhead.com/spell=183425 - добавлено в 7.0.1
http://ru.wowhead.com/spell=203797 - добавлено в 7.0.1

Ну а базы данных других пираток не пруф.

**Comment by Rorshah** [comment]
http://et.worldofwarcraft.wikia.com/wiki/Paladin_auras
Вот тут пишут что 
`They are free to cast, with the only cost being the global cooldown`
Намекая что ГКД все-таки имеется.

**Comment by MiceRus** [comment]
Хорошо. Пусть будет Аура воина света иметь ГКД. Но... применение-то мгновенное!
Значит любое другое действие, которое идет за ним в макросе ДОЛЖНО выполняться не прерывая его.
Так? А на самом деле - прерывает. По крайней мере вызов маунта точно.
Я еще раз позволю себе напомнить ,что подобный макрос использовался на всех версиях ВОВ и всегда был рабочий. Но вот на этом сервере он не работает.
#showtooltip Затерянный во времени протодракон
/cast [nomounted] !Аура воина Света
/cast [nomounted, noflyable] Скакун; [nomounted, flyable] Затерянный во времени протодракон
/cast [mounted] !Аура благочестия
/dismount [mounted]

**Comment by gmOverfire** [comment]
Вы же пишете что должно работать
> **Как должно работать?**
> ГКД должен быть 0!
ГКД есть, это подтверждается другими источниками.

А взаимодействие маунтов и аур паладина, мне кажется, другой вопрос.

**Comment by MiceRus** [comment]
Я не разбираюсь в программировании данных вещей, и мне Вы можете говорить все что угодно.
Дело не во взаимодействии аур и маунтов.
Дело в том, что скрипт макрос абсолютно рабочий на всех серверах, кроме вашего.
И на пиратках и на офе. А нерабочий он не из-за ГКД, а из-за того, что ПРИМЕНЕНИЕ ауры не мгновенное! Вы меня запутали с этим ГКД. Оно вообще тут не причем.
И я не разобрался, кинулся смотреть.

**Comment by gmOverfire** [comment]
http://db.logon3.com/?spell=32223
`Применение | Мгновенное действие`

Про ГКД писали Вы, помните? В первое сообщение гляньте.

**Comment by MiceRus** [comment]
Да, потому что сам запутался.
То, что в базе у вас прописано "применение мгновенное" - на самом деле в игре не так.
И на видео я это показал.

**Comment by MiceRus** [comment]
Бесполезно! На русском сервере какие-то аглицкие need proof.
что такое Нид пруф? Какой еще пруф Вам нужен, если я на видео все привел?
Или Вам надо видео с оффсайта? А ссылки на оффорум, на котором обсуждаются макросы не подойдет?

**Comment by kalipsa988** [comment]
Начну с того, что ты в самом начале ошибку грубую сделал
у тебя ссылка на способность ЛЕГИОНА

**Comment by kalipsa988** [comment]
Добавлено в обновлении 7.0.1

**Comment by MiceRus** [comment]
И как найти ссылку на 3.3.5а на вовхеде, когда там уже все давно обновлено?
Ну и вообще - я совершил ошибку, что стал привязывать все к ГКД, а он тут вообще не при делах.
т.к. сама по себе аура применяется мгновенно. В смысле, должна применяться, т.е. следующее за ней действие не должно прерывать применение ауры. О мгновенности написано везде.
Так вот, именно этой самой мгновенности и нет.
потому макрос и не работает.

**Comment by kalipsa988** [comment]
ГКД должно быть

**Comment by kalipsa988** [comment]
кинь ссылку на обсуждение того макроса что ли

**Comment by MiceRus** [comment]
Ка же мне Вам объяснить, что если бы ГКД действовал на эту ауру, то НИКОГДА паладины не пользовались бы макросом, который я привел выше. Понимаете? Он бы был нерабочим!
А он был и есть рабочий на ВСЕХ серверах ,кроме ЭТОГО.

**Comment by sega693** [comment]
ссылка на макросы в первом посте

**Comment by kalipsa988** [comment]
сайт какой-то пиратки и по нему должны гкд убирать?

**Comment by MiceRus** [comment]
https://eu.battle.net/forums/ru/wow/topic/2123455942#post-4
https://forexdengi.com/threads/23097-kto-igraet-v-wow-3.3.5?p=3239466
https://vk.com/topic-21884306_23712602
Я так понимаю, ссылки не на вовхед и не на офф форум не подходят?
Я не помню, в каком месте оффа нашел его первый раз. Но точно помню, что дата того постав была где-то начало 2010 года. Т.е всяко не Легион

**Comment by kalipsa988** [comment]
во всех бд 335 гкд есть, оверфай пруфы приводил нормальные, а чел опирается на сайт пиратки какой-то, при этом в самом начале кидая ссылку на спел легиона, где гкд 0

**Comment by MiceRus** [comment]
Причем тут ГКД? 
/cast [nomounted] !Аура воина Света
/cast [nomounted, noflyable] Скакун; [nomounted, flyable] Затерянный во времени протодракон
/cast [mounted] !Аура благочестия
/dismount [mounted]
Разберем по пунктам?
Итак, если ГКД влияет, то получается, что Аура воина Света должна применится, но вторая строчка выполниться не должна?

**Comment by MiceRus** [comment]
Да! Вот еще вопрос. В базе LOGON3 никаких изменений нет, однако на прошлой версии (та что на тесте - я видео снял) макрос работал. Так где тогда ошибка? на тестовом или тут?

**Comment by kalipsa988** [comment]
/ cast [nomounted]! Аура воина Света 
/ cast [nomounted, noflyable] Скакун; [nomounted, flyable] Затерянный во времени протодракон 
/ cast [установлен]! Аура благочестия 
/ снят [смонтирован] 
в этом макросе полно ошибок

**Comment by kalipsa988** [comment]
извиняюсь, из-за переводчика у меня пробелы в макросе писало

**Comment by MiceRus** [comment]
Ладно. ЗАкрываю тему.
Надо же - весь мир пользовался. Я сам им пользовался на оффе, а оказывается - тут полно ошибок.

**Comment by kalipsa988** [comment]
/cast [nomounted, noflyable] Скакун; [nomounted, flyable] Затерянный во времени протодракон
по этой строчке постоянно флай маунт призывается

**Comment by MiceRus** [comment]
Я прямо сейчас им пользуюсь. Но только не включается аура воина.
В Лпларане жму - садится на коня. Жму на площадке красса - садится на дракона

**Comment by MiceRus** [comment]
Я прямо сейчас им пользуюсь. Но только не включается аура воина.
В Лпларане жму - садится на коня. Жму на площадке красса - садится на дракона

**Comment by MiceRus** [comment]
Можете подойти посмотреть. Перс Perecvet

**Comment by MiceRus** [comment]
Огромное спасибо за исправленные ауры!
И извиняюсь за несколько грубоватый тон в некоторых своих сообщениях.
Еще раз СПАСИБО!
Все работает идеально!
Даже более того - исправили так, что теперь и строчка "костыль" не нужна!
