### ISSUE TITLE
не робит бонус от 2 т9 ханта

### ISSUE THREAD

**Issue by Accycc** [VirginTeam/WotlkCore#930]
http://db.logon3.com/?spell=67150

Фактический результат
при одетом в 2т9  http://db.logon3.com/?spell=67150 и использовав http://db.logon3.com/?spell=13554 при тике не критует

Ожидаемый результат —  тик должен критовать

Шаги для воспроизведения ошибки:
1. одеть на ханта 2т9
2. использовать на манекен http://db.logon3.com/?spell=1355 
3.посомтреьт на тики укуса змеи

Текущее обновление ядра: Build 198 2018-04-24 18:25:21 +0400

**Comment by gmKroshka** [comment]
Изучите правила оформления репорта и используйте шаблон, который уже работает при создании новой проблемы
https://github.com/VirginTeam/WotlkCore

**Comment by Accycc** [comment]
так пойдет?

**Comment by sega693** [comment]
http://puu.sh/AfdVJ/21f7b15508.jpg всё работает

**Comment by Accycc** [comment]
![wowscrnshot_050318_161420](https://user-images.githubusercontent.com/30463088/39578614-abbbbcd0-4ef5-11e8-8383-af68104eee2a.jpg)
ни 1го прока

**Comment by kalipsa988** [comment]
т9 3х типов если что, может какой-то из сетов не работает

**Comment by Accycc** [comment]
ну т9.1

**Comment by ForesterDev** [comment]
![image](https://user-images.githubusercontent.com/11771800/39582728-a848bdaa-4eff-11e8-9cce-d4581b46ae60.png)
Проверил, все работает

**Comment by sega693** [comment]
у меня по 1 куску 245 и 232 были. Да и вряд ли разница есть

**Comment by Accycc** [comment]
вы об оденьте т9, у всех на серве спрашиваю, ни у кого не робит

**Comment by Accycc** [comment]
Kodekc добавлен ✘ Работает правильно  где исправно когда не исправно

**Comment by kalipsa988** [comment]
![wowscrnshot_050318_131958](https://user-images.githubusercontent.com/29568428/39588735-0a8be53c-4f05-11e8-992c-2c8c0e80561d.jpg)
вот Об шмот

**Comment by Kodekc** [comment]
Разработчик прикрепил вам скриншот выше, где проверено и видно, что работает, пойдите на тестовый и сами проверьте. В полном обвесе персонаж если, не факт, что проблема в т9

**Comment by Accycc** [comment]
ну гляньте наверху, скрин я выложил из 48 раз хоть раз критануть должен был, весь день слежу за проком ни разу не было, у всех хантов спрашиваю кто в т9 ни у кого не прокает

**Comment by kalipsa988** [comment]
т9 232 или 245?

**Comment by kalipsa988** [comment]
![wowscrnshot_050318_135413](https://user-images.githubusercontent.com/29568428/39590559-f746cbd6-4f09-11e8-97bc-119cd7a68bda.jpg)
в 232 проки есть, проблема индивидуальная, попробуй антиерор в лк сделать

**Comment by Accycc** [comment]
вот щас нашел еще 2их хантов с т9 232илвл у них тоже не критует, так что зайдите на х1 и там тестите а не на вашем тест сервере

**Comment by kalipsa988** [comment]
у меня на х1 нет 232, а прописывать мне его не будут там и насколько я знаю обновы одинаковые на обоих серверах

**Comment by Accycc** [comment]
ну тогда в чем проблема, ни у кого на х1 не работает бонус а на тест сервере у вас работает, раз у вас одинаковы обновы

**Comment by kalipsa988** [comment]
подгород, но если интересно, то вот
![wowscrnshot_050318_200751](https://user-images.githubusercontent.com/29568428/39591869-c031c944-4f0d-11e8-8bf2-aa10a26a4dd3.jpg)

**Comment by kalipsa988** [comment]
доказано

**Comment by Accycc** [comment]
увидел) но антиерор мне не помог)
