### ISSUE TITLE
[Задание] ID 25285 - Входит и выходит!

### ISSUE THREAD

**Issue by Awegod** [VirginTeam/WotlkCore#931]
Описание:

Для выполнения задания необходимо сесть в механотанк

Что работает не так?

Персонаж не садится в механотанк, твкнув по танку, появляется еще один танк, тыкаем еще и еще один появляется и так до бесконечности, но в танк перс не садиться и испытать Систему катапультирования не представляется возможным

Как должно работать?

Персонаж должен садиться в танк и система должны быть испытана.

Шаги для воспроизведения ошибки:

 1.Берем квест
 2.Нажимаем на Механотанк
Текущее обновление ядра:

Build 198 2018-04-24 18:25:47 +0400

**Comment by gmKroshka** [comment]
https://github.com/VirginTeam/WotlkCore/issues/48
