### ISSUE TITLE
Ободряющий клич драконоборца

### ISSUE THREAD

**Issue by kalambyr18** [VirginTeam/WotlkCore#932]
**Ссылки и комментарии:**

http://ru.wowhead.com/spell=22888
http://ru.wowhead.com/item=49643

**Что работает не так?**

(Проверял за Альянс)
Нет бафа "Ободряющий клич драконоборца" после сдачи кв "Голова Ониксии".  При сдаче кв "Голова Нефариана" все хорошо и баф дается (правда только на мосту Штормграда).

**Как должно работать?**

После сдачи кв "Голова Ониксии" игроки в Штормграде должны получить баф "Ободряющий клич драконоборца"

**Шаги для воспроизведения ошибки:**

1, Выполнить кв "Голова Ониксии "
2, -

**Текущее обновление ядра:**

Build 198 2018-04-24

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by kalipsa988** [comment]
дубликат #848

**Comment by gmKroshka** [comment]
https://github.com/VirginTeam/WotlkCore/issues/848

**Comment by kalambyr18** [comment]
В вашем репорте написано что баф дается на мосту  ,а не во всем Штормграде . Я же пишу что бафа после сдачи "Голова Ониксии " нет вообще .

**Comment by gmKroshka** [comment]
Вы можете добавить эту информацию в открытом репорте в комментариях

**Comment by kalipsa988** [comment]
Что работает не так?

а) Баф даётся только на мосту штормграда (альянс) и Алея силы (орда)
