### ISSUE TITLE
[Валюта] ID 121, 122,123,124,125,321 - Почетные знаки

### ISSUE THREAD

**Issue by kalipsa988** [VirginTeam/WotlkCore#933]
**Ссылки и комментарии:**

http://db.logon3.com/?currency=121, http://db.logon3.com/?currency=124, http://db.logon3.com/?currency=122, http://db.logon3.com/?currency=123,http://db.logon3.com/?currency=321,http://db.logon3.com/?currency=125
**Что работает не так?**

Не выдаются за отыгранное поле боя

**Как должно работать?**

Почетные знаки боя были награждены игроками, которые участвуют в битвах. В конце матча каждому игроку на поле битвы было присуждено либо: один почетный знак за потерю, две почетные чести за ничью или три почетных чести за победу. Игроки, которые покидают поля битвы до матча, не получают никаких знаков.

**Шаги для воспроизведения ошибки:**

1. Отыграть любое бг

**Текущее обновление ядра:**

03.05.2018

**Comment by Santaria94** [comment]
они были упразднены в патче 3.3.3

**Comment by kalipsa988** [comment]
Начиная с патча 3.3.3 , почетные знаки битвы больше не могут использоваться в качестве валюты для предметов, вместо этого теперь их можно обменять на бригадирских генералов в Оргриммаре, Штормграде и Даларане на 185 почетных очков каждый. В Cataclysm все оставшиеся Знаки Почета будут преобразованы в Почетные Очки , навсегда удаляющие валюту.

**Comment by kalipsa988** [comment]
http://wowwiki.wikia.com/wiki/Mark_of_Honor пруф

**Comment by kalipsa988** [comment]
@Kodekc  пруфы посмотри сначала

**Comment by Kodekc** [comment]
В 3.3.3 их перестали выдавать, а в последующих патчах конвертировали для тех игроков, что оставили их на персонажах, пачноуты пойди поизучай, если найдёшь что-то, прикрепляй.

**Comment by kalipsa988** [comment]
убедил
