### ISSUE TITLE
[Задание] ID 12572 - Боги любят блестящие штучки

### ISSUE THREAD

**Issue by alexo85** [VirginTeam/WotlkCore#936]
**Ссылки и комментарии:**
https://www.youtube.com/watch?v=GPRTQd8ceIo
Добавьте ссылки с wowhead.com или db.logon3.com на проблемные задания, NPC, заклинания и т.д. 

**Что работает не так?**
Не работает нпс Лафу http://ru.wowhead.com/npc=28120 .Он просто ничего не делает. Так же на нпс Лафу агрятся Императорская кобра http://ru.wowhead.com/npc=28011
Фактический результат — тот, который вы наблюдаете 

**Как должно работать?**
нпс Лафу должен подходя к местам с блеском должен выкапывать Драгоценные блестяшки http://ru.wowhead.com/item=38575
Ожидаемый результат — то, чего вы ожидали при выполнении ваших действий. Процесс правильной работы

**Шаги для воспроизведения ошибки:**

1. Подхожу к месту с блеском с вызваным нпс и ничего не просходит
2. Шаг два
3. Шаг три

**Текущее обновление ядра:**
Build 199 2018-05-04 15:41:18 +0400
Можно посмотреть в игре, введите в чат команду .server info и скопировать строку начиная с Build с номером и датой. Не забывайте указывать, Live Server или PTR Server, где проводилось тестирование.

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by MiceRus** [comment]
Да сделайте уже с этим квестом что-нить? Целая цепочка выпала из игры, плюс 4 ачивки в пролете.

**Comment by gmOverfire** [comment]
#838

**Comment by Skellan** [comment]
Задание вновь работает некорректно, и ради этого вы сбрасывали весь прогресс у большинства игроков? За час раскопок эти долбаных камней дропнулась только 1 штука. Зачем урезать дроп в разы, в чем смысл? 

Logon 3. 3.3.5 x1
