### ISSUE TITLE
проблемы с талантом у шамана

### ISSUE THREAD

**Issue by lishker** [VirginTeam/WotlkCore#939]
http://wowroad.info/?spell=52456
http://wowroad.info/?spell=65991

вкачиваю талант усиливающие тотемы который дает прибавку ловкасти и силы тотему, он ни чего не добовляет.
Изначально когда качался талант работал, но после того как сбросил таланты эффект пропал

build 199 2018-05-04

**Comment by lishker** [comment]
под хохлому расписать что ли, или что тут не понятного, дурацкий сайт

**Comment by gmOverfire** [comment]
> Изначально когда качался талант работал, но после того как сбросил таланты эффект пропал

что и логично, без вкачаного таланта эффекта и не будет.
Если проблема реально имеет место быть - оформите по шаблону репорт заново.
