### ISSUE TITLE
[NPC] ID 25038 - Пророк скверны (Туман)

### ISSUE THREAD

**Issue by sega693** [VirginTeam/WotlkCore#940]
**Ссылки и комментарии:**
http://db.logon3.com/?npc=25038

**Что работает не так?**
Дракон летит и разливает туман/дым/облако по рандомной траектории (возможно за игроками, как на иллидане было)

**Как должно работать?**
Должен разливаться как на скринах ниже
Дракон пролетает ровно по прямой вдоль всей комнаты, никуда не сворачивая во время полета. С запада на восток или наоборот

http://drimmers.ucoz.ru/_bl/0/32569575.jpg север
http://drimmers.ucoz.ru/_bl/0/24308607.jpg юг
http://drimmers.ucoz.ru/_bl/0/06358447.jpg "суперюг"
https://www.youtube.com/watch?v=alCepkRJKLk также видео. только самая южная позиция не выделяется там

**Шаги для воспроизведения ошибки:**

1. дождаться фазы со взлетом

**Текущее обновление ядра:**
Build 199 2018-05-04 15:41:18 +0400

**Comment by sega693** [comment]
Также босс пропадает после ресстарта/дисконнекта - пропадает возможность пройти дальше

**Comment by sega693** [comment]
Может просто откроете огненную стену после босса? Если починить его нет возможности

**Comment by Santaria94** [comment]
> Может просто сделаете чтоб огненная стена после Брутала открывалась сразу?
Мне кажется это плохая идея. Можно будет тогда во время боя с Пророком забегать туда во время тумана, что облегчит его убийство.

**Comment by sega693** [comment]
Закрывать при пуле :D 
Я просто не знаю что еще предложить, А ты тоже прекрасно понимаешь, что фикса мы дождемся лишь когда брекет загнется -_-

**Comment by sega693** [comment]
Дыхание туманом исправлено, но теперь до него дожить невозможно из-за скелетов, которые правильно работали ранее https://github.com/VirginTeam/WotlkCore/issues/979
