### ISSUE TITLE
[Заклинание] ID 47240 - Демонический союз

### ISSUE THREAD

**Issue by Accycc** [VirginTeam/WotlkCore#944]
http://db.logon3.com/?spell=47240

Фактический результат
при проке http://db.logon3.com/?spell=47240 дает всего 1 спд
https://www.youtube.com/watch?v=sZGXsceomJY
+ко всему не от каждого крита прокает http://db.logon3.com/?spell=47240

Ожидаемый результат — при проке http://db.logon3.com/?spell=47240 должен давать 10% от моего спд

Шаги для воспроизведения ошибки:
1.Критануть петом в любого моба либбо манекен

**Comment by gmOverfire** [comment]
Проблема подтверждена.
Но прокает постоянно (не забываем про кд в 20 секунд).

**Comment by Accycc** [comment]
моя извиняться, забыл про кд)

**Comment by Kodekc** [comment]
Исправлено СПД от Демонического союза. Изменения будут применены в ближайшем обновлении
