### ISSUE TITLE
[Задание] ID 648 - Спасти КПХ-17/TN!

### ISSUE THREAD

**Issue by kalambyr18** [VirginTeam/WotlkCore#945]
**Ссылки и комментарии:**

http://ru.wowhead.com/quest=648/17-tn

**Что работает не так?**

На нпс ,которого нужно сопроводить, агрятся мобы . Нпс не реагирует на них никак, просто бежит и агрит остальных . В итоге за нпс бежит 20 мобов . Даже если удается их убить . То примерно через пол пути нпс разворачивается и бежит в гору ! В текстуры ! 

**Как должно работать?**

На нпс напали , тот разворачивается и идет обратно , чтоб у игрока было время убить мобов, как это обычно и бывает на всех кв по сопровождению нпс! Нпс не должен бежать в текстуры , где никак за ним не проследить .

**Шаги для воспроизведения ошибки:**

1. Взять квест на сопровождение .
2. Сопроводить

**Текущее обновление ядра:**

build 200 2018-05-10

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by Ewropa** [comment]
https://github.com/VirginTeam/WotlkCore/issues/711
