### ISSUE TITLE
[Группа предметов] - Рецепты

### ISSUE THREAD

**Issue by Eneyra** [VirginTeam/WotlkCore#947]
**Ссылки и комментарии:**

http://ru.wowhead.com/item=32747
http://ru.wowhead.com/item=30323
http://ru.wowhead.com/item=32753
http://ru.wowhead.com/item=42178

**Что работает не так?**

На нашем сервере данные рецепты недоступны игрокам и не прописаны в лут.

**Как должно работать?**

Первые 3 рецепта должны падать из соответствующих подземелий, с таким же шансом, с которым падают аналогичные рецепты из этих же подземелий.
4 рецепт должен падать с любого моба в норде при наличии скила портняжного дела (wowhead.com: Think this drops off every type of mob in northrend much like the heavy frostweave book you also need tailoring to be able to roll on this item but you dont need the 400 skill so you could have a lvl 1 skill and still find this.)
3 рецепта появились еще в бк а 4 - с выходом ЛК, и, судя по комментарием игроков из актуальных на тот момент версий игры, вполне успешно падали в то время.

**Шаги для воспроизведения ошибки:**

1. Проверить аукционный дом
2. Зачистить подземелья
3. Спросить любых старых игроков
Также можно чекнуть http://db.logon3.com/ там также эти предметы числятся как недоступные.

**Текущее обновление ядра:**
Build 200

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by gmKroshka** [comment]
https://github.com/VirginTeam/WotlkCore/issues/764
Можете дополнить уже существующий репорт
