### ISSUE TITLE
[Игровая механика] - Поиск подземелий (Права лидера группы)

### ISSUE THREAD

**Issue by Santaria94** [VirginTeam/WotlkCore#950]
**Ссылки и комментарии:**

На данный момент лидер группы обладает следующими особыми правами:

|| Ручной добор игроков в группу.
|| Возможность передать лидерство другому участнику группы.

Обе функции приводят к различным ошибкам и эксплойтам в работе системы поиска подземелий, таким как:

|| Многократная передача лидерства группы может привести к ошибке в системе поиска подземелий, после чего группа удаляется из нее. Пропадает "глаз", как следствие возможность добора игроков, а также награды за прохождение подземелья.

|| Ручной добор позволяет добавлять в группу любых игроков, которые в том числе не соответствуют требованиям подземелья. Так в низкоуровневые подземелья через систему поиска могут быть взяты высокоуровневые персонажи (подробнее #244 ), что является эксплойтом, которым пользуются недобросовестные игроки. 
Также в некоторых случаях при подобном доборе система все же не допускает игрока в подземелье, при этом если его исключить голосованием или он сам покинет группу, то произойдет ошибка в системе поиска подземелий, описанная в предыдущем пункте.

**Что работает не так?**

Функции ручного добора и передачи лидерства в системе поиска подземелий, которые приводят к различным ошибкам.

**Как должно работать?**

Система поиска подземелий имеет свой специальный механизм добора игроков и должен использоваться только данный механизм. Лидер группы не должен иметь возможность вручную добирать игроков в группу.

Функция передачи лидерства не имеет никакой практической ценности, но при этом при ее использовании могут возникать различные ошибки. Думаю ее стоит также отключить, если таковая возможность есть.

**Текущее обновление ядра:**

Билд 200

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by Kodekc** [comment]
https://github.com/VirginTeam/WotlkCore/issues/244
