### ISSUE TITLE
[Рейд] Логово Груула - Минимальный уровень входа

### ISSUE THREAD

**Issue by Santaria94** [VirginTeam/WotlkCore#954]
**Ссылки и комментарии:**

http://db.logon3.com/?zone=3923

http://wow.blizzwiki.ru/index.php?title=%D0%9B%D0%BE%D0%B3%D0%BE%D0%B2%D0%BE_%D0%93%D1%80%D1%83%D1%83%D0%BB%D0%B0
http://ru.wow.wikia.com/wiki/%D0%9B%D0%BE%D0%B3%D0%BE%D0%B2%D0%BE_%D0%93%D1%80%D1%83%D1%83%D0%BB%D0%B0

> Игрок выше 65-го уровня сможет попасть в подземелье

В актуальном аддоне Атлас для 3.3.5 - также указан минимальный уровень 65

**Что работает не так?**

На данный момент минимальный уровень входа - 70

**Как должно работать?**

Минимальный уровень входа должен быть - 65

**Текущее обновление ядра:**

Билд 200

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by deexeq** [comment]
Дополню:
As people said, all raids are for 70+, except Karazhan - 68. But also Gruul's Lair and Magtheridon's Lair require only lv65 to enter (or required the last time I checked).

**Comment by ForesterDev** [comment]
Исправлено
