### ISSUE TITLE
[Задание] ID 13133 - Поиски древнего героя

### ISSUE THREAD

**Issue by vitti2011** [VirginTeam/WotlkCore#957]
Ссылки и комментарии:
http://ru.wowhead.com/quest=13133

Что работает не так?
После пробуждения http://ru.wowhead.com/npc=30718 появляется http://ru.wowhead.com/npc=30884, используя на него http://ru.wowhead.com/spell=3921 он должен стать http://ru.wowhead.com/npc=30886, но он не подчиняется, а просто исчезает.

Как должно работать?
http://ru.wowhead.com/npc=30884 должен подчиниться и стать http://ru.wowhead.com/npc=30886

Шаги для воспроизведения ошибки:
1. Берем квест у НПЦ http://ru.wowhead.com/npc=30232
2. Бежим на точку, указанную в тексте и пробуждаем http://ru.wowhead.com/npc=30718 чтобы появился http://ru.wowhead.com/npc=30884.
3. Подчиняем его http://ru.wowhead.com/spell=3921, но НПС просто исчезает.

Текущее обновление ядра:
Logon 3 WowCircle Development
Последнее обновление ядра: Build 200 2018-05-10 11:41:15 +0400

**Comment by gmKroshka** [comment]
https://github.com/VirginTeam/WotlkCore/issues/216

**Comment by vitti2011** [comment]
Зачем закрывать тикет? Дубликат, прошлогоднего тикета, а кв еще не пофиксили. Прошел год, а кв не пофикисли, Карл! Мде...

**Comment by gmKroshka** [comment]
Репорты не имеют "срока годности". Проблема уже зафиксирована, повторная фиксация не требуется

**Comment by vitti2011** [comment]
Значит предпринимать что-либо вы еще год не будете, понятно...
До свидания.

**Comment by VetalOKAY** [comment]
капец... замените вашего лентяя разраба!!

**Comment by VetalOKAY** [comment]
всё блять в стиле л3, всё под чистую удаляют, вместо того чтобы работать

**Comment by gmOverfire** [comment]
За речью следите, или мы закроем Вам доступ к трекеру.
Ваши действия могут привести к противоположному от желаемого Вами результата, не стоит злоупотреблять.

**Comment by VetalOKAY** [comment]
ахаха пиздец... щас бы вместо того чтобы чинить, писать о том, что вообще не починим 
:DDD
Только на л3 это возможно
