### ISSUE TITLE
[Предмет] ID 176089 - Неопалимые латные рукавицы

### ISSUE THREAD

**Issue by sega693** [VirginTeam/WotlkCore#959]
**Ссылки и комментарии:**
http://db.logon3.com/?object=176089
http://db.logon3.com/?item=12812
http://db.logon3.com/?quest=5103
http://db.logon3.com/?quest=5124

**Что работает не так?**
Рукавицы http://db.logon3.com/?item=12812 лутаются только при выполнении второго квеста в цепочке (id-5124)
Приходится бежать туда-обратно два континента

**Как должно работать?**
Должны лутаться при выполнении первого квеста (id-5103) 

> 1. Go to "Firebrand" area of LBRS.
> 2. Click on body to acquire quest.
> **3. IMPORTANT! Click on object on the ground next to the body in order to get your Unfired Plate Gauntlets.**
> 4. Go to Everlook in Winterspring to turn in the quest

> when you talk to the human remains and get the quest, the unfired gauntlets object is on the ground next to you. Pick it up and you can now loot the quest item from it.

Судя по коментам в 3.0.3 был такой же баг, и в 3.1 фиксанули

**Шаги для воспроизведения ошибки:**
1. Взять первый кв
2. лутануть перчатку и не получить лут

**Текущее обновление ядра:**
Build 200 2018-05-10 11:41:15 +0400

**Comment by zanku666** [comment]
2 дня назад делал этот квест, проблемм небыло. Попробуй сделать активной даную профу, ибо я так сделал перед тем как идти за перчатками

**Comment by sega693** [comment]
смысл в том, что я взял кв (но не мог взять перчатки) - сдал его в зимних ключах - пошел назад за итемом для следующего кв (который уже дает рецепт)
А должны сразу лутаться, без повторной беготни

**Comment by zanku666** [comment]
хм, я сразу брал у Малифоя квест на рецепт, без первой части

**Comment by sega693** [comment]
На мейне так же было. На твинке - нет. Я посчитал, что делал первый кв 100 лет назад мейном. хз

**Comment by zanku666** [comment]
сам квест у Малифоя я взял год назад когда он еще не работал, потом когда-то я увидел его в баг-трекере в пофиксенных и вот только теперь лутнул перчатки и доделал его
