### ISSUE TITLE
[NPC] ID 2748 - Аркедас

### ISSUE THREAD

**Issue by kalambyr18** [VirginTeam/WotlkCore#960]
**Ссылки и комментарии:**

http://ru.wowhead.com/uldaman
http://ru.wowhead.com/npc=2748

**Что работает не так?**

В случае вайпа , босс больше не вызывается с платформы (не аквтивна ) и пройти подземелье не получается .
http://screenshot.ru/upload/image/atZH

**Как должно работать?**

Жмешь на платформу , босс становится активным 

**Шаги для воспроизведения ошибки:**

1. Вайпнуться на Боссе 
2, Попробовать нажать на платформу

**Текущее обновление ядра:**

build 200 2018-05-10

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by ForesterDev** [comment]
Исправлено, будет применено в обновлении
