### ISSUE TITLE
[Заклинание] ID 19263 - Сдерживание

### ISSUE THREAD

**Issue by kalipsa988** [VirginTeam/WotlkCore#961]
**Ссылки и комментарии:**

http://db.logon3.com/?spell=19263

**Что работает не так?**

а) Если охотника под детеренсом бьют от 3 и больше врагов, то проходят автоатаки, абилки Причем при 1х1 детеренс это все не пропускает
б) Не вешается http://db.logon3.com/?spell=34477 под действием Сдерживания
**Как должно работать?**

а) Должен парировать все атаки независимо от количества атакуемых
б) Должен вешаться под действием Сдерживания

**Шаги для воспроизведения ошибки:**

1. Прожать в замесе
2. Умереть

**Текущее обновление ядра:**

19.05.2018

**Comment by Santaria94** [comment]
Парировать можно только атаки, которые наносятся спереди. Еще охотник мог быть под дизармом, а без оружия парировать невозможно. Также есть физические удары, которые нельзя парировать, например - http://db.logon3.com/?spell=7384 , http://db.logon3.com/?spell=62322

Возможно есть и другие нюансы, это первое, что пришло в голову.

**Comment by kalipsa988** [comment]
Изменения патча 3.2.0
Теперь эта способность позволяет охотнику парировать заклинания и атаки сзади, а также спереди. Теперь появился новый эффект визуального эффекта заклинания.
Пруфы http://wowwiki.wikia.com/wiki/Deterrence

**Comment by kalipsa988** [comment]
Проще написать что должно пробивать детеренс:

Воин:
Превосходство
Сокрушительный бросок
Героический бросок

Охотник:
Укус росомахи (пет)

Разбойник:
Отравляющий укол

Рыцарь смерти:
Рунический удар

Чернокнижник:
Стрела хаоса

Также пробивают детеренс абилки из стелса:

Разбойник (причем пробивают как из инвиза так и в Танце теней):
Гаррота
Подлый трюк
Внезапный удар

Друид:
Накинуться
Наскок

Больше никакие атаки и магия в детеренс не проходят.

**Comment by Librariane** [comment]
kalipsa988
С каких пор Стрела хаоса должна проходить в Сдерживание?

**Comment by kalipsa988** [comment]
потому что она абсолютно всё пробивает

**Comment by kalipsa988** [comment]
вот видео с АТ, где лок пробивает детер стрелой
https://youtu.be/fWJgy9Q6o1Y?t=101

**Comment by gmOverfire** [comment]
АТ не показатель.

**Comment by kalipsa988** [comment]
да тебе любой пвпшер на любом серве скажет, что проходит стрела хаоса в детеренс

**Comment by sega693** [comment]
бабл
https://eu.battle.net/forums/ru/wow/topic/17616783521#post-2 дети легиона говорят, что пробивал
https://eu.battle.net/forums/ru/wow/topic/6689309068?page=1#post-15 дети пандарии говорят, что пробивал, но их слова опровергают
https://eu.battle.net/forums/ru/wow/topic/3110231202#post-15 то же самое, только чуть раньше

https://www.noob-club.ru/blue/50016/9446154983_Vopros_po_povodu_varlokov.html перекопированный блюпост про имун

правда я хз зачем это тут)

**Comment by ForesterDev** [comment]
Нет никаких приведенных пруфов бага, хотя бы комбатлог с проблемой. Не воспроизводится

**Comment by kalipsa988** [comment]
Не закрывай пока что, если на бг в замес попасть смогу и запишу комбатлог

**Comment by kalipsa988** [comment]
не актуально, закрываю
