### ISSUE TITLE
[Игровая механика] - Питомцы

### ISSUE THREAD

**Issue by kalipsa988** [VirginTeam/WotlkCore#965]
**Ссылки и комментарии:**

**Что работает не так?**

Питомец постоянно уходить за спину цели

**Как должно работать?**

Они должны забегать за спину, но если цель разворачивается, то он не должен повторно забегать.

**Шаги для воспроизведения ошибки:**

1. натравить пета на противника
2. увидеть, что при движении пет постоянно уходит за спину

**Текущее обновление ядра:**

21.05.2018

**Comment by zyxellgit** [comment]
https://youtu.be/mmD_Wrnbe0c?t=410 а тут вот на синдре вертели и петы бегают за спину

**Comment by kalipsa988** [comment]
1. Вот пруфы http://www.warcraftmovies.com/movieview.php?id=163895 - 3:05 - пет просто в лицо бьет приста
2. у синдры очень большая моделька, вполне возможно что она сдвинулась
либо, у больших моделек немного по другому работает
3. Откройте репорт

**Comment by kalipsa988** [comment]
уберите наклейку "Работает правильно", если не работает правильно

**Comment by kalipsa988** [comment]
После последнего обновления стали бегать правильно. Закрываю

**Comment by kalipsa988** [comment]
Баг через раз срабатывает, когда варом блок щитом прожимаешь и тебя в спину пет бьёт по кд, это вывозит

**Comment by Kodekc** [comment]
Пока репорт останется переоткрытым, требуется много времени для изучения проблемы в поиске пути и исправления его

**Comment by kalipsa988** [comment]
07.02.19 починилось как-то само, закрою пока что
