### ISSUE TITLE
[Группа NPC] - Жители деревни Погребальных Костров

### ISSUE THREAD

**Issue by Santaria94** [VirginTeam/WotlkCore#966]
**Ссылки и комментарии:**

> Жители Погребальных Костров были прокляты, поэтому ночью происходит их превращение в ужасное обличье воргенов, а с рассветом они вновь становятся людьми. Однако, несмотря на все трудности, деревня все же продолжает обслуживать зашедших путников.

http://db.logon3.com/?npc=3528
http://db.logon3.com/?npc=1891
http://db.logon3.com/?npc=1894
http://db.logon3.com/?npc=3532
http://db.logon3.com/?npc=3530
http://db.logon3.com/?npc=1895

**Что работает не так?**

Не работает превращение жителей деревни в воргенов.

**Как должно работать?**

В 21:00 по серверному времени жители деревни должны быть превращены в воргенов.

http://db.logon3.com/?npc=3528 ==> http://db.logon3.com/?npc=3529
http://db.logon3.com/?npc=1891 ==> http://db.logon3.com/?npc=1892
http://db.logon3.com/?npc=1894 ==> http://db.logon3.com/?npc=1893
http://db.logon3.com/?npc=3532 ==> http://db.logon3.com/?npc=3533
http://db.logon3.com/?npc=3530 ==> http://db.logon3.com/?npc=3531
http://db.logon3.com/?npc=1895 ==> http://db.logon3.com/?npc=1896

**Текущее обновление ядра:**

Build 202

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by deexeq** [comment]
https://youtu.be/wWmsHIIfoxY
https://youtu.be/lMJQeRCPQeM

**Comment by ForesterDev** [comment]
Реализовано. Будет применено в обновлении
