### ISSUE TITLE
[Предмет] ID 5634 - Зелье свободы действий

### ISSUE THREAD

**Issue by zanku666** [VirginTeam/WotlkCore#967]
**Ссылки и комментарии:**

http://db.logon3.com/?item=5634

**Что работает не так?**

Не работает http://db.logon3.com/?item=5634 . Жму зелье, и меня под ним замедляют/станят. Что есть оно что нет никакой разницы.

**Как должно работать?**

Должна быть невосприимчивость от замедления и оглушения если зелье выпито до боя.

**Шаги для воспроизведения ошибки:**

1. Выпить зелье
2. Смотреть как над тобой издиваются (замедляют, станят)
3. Проклинать это зелье

**Текущее обновление ядра:** Build 202

**Comment by Kodekc** [comment]
Требуется конкретика от чего именно пытались защититься этим зельем.
Во-первых, она защищает только от эффектов: Пойманный в ловушку, Оплетён, Оглушен
Во-вторых, не влияет на эффекты, уже действующие на заклинателя.

**Comment by kalipsa988** [comment]
вчера на бг пытался замедлить лока под фласской, невосприимчивость выдало

**Comment by kalipsa988** [comment]
*Не срабатывала фласка от сапа, ослепления разбойника, стан лока*
она и не должна от них срабатывать, это потеря контроля, а не замедление или стан

**Comment by Kodekc** [comment]
Мне кажется, что всё в порядке с этим предметов, просто проведите сравнение, что вы пытаетесь снять или вам снимают и сопоставьте это эффектам
