### ISSUE TITLE
[NPC] ID 30474 - Северный Ветер 

### ISSUE THREAD

**Issue by IssueCreatorCircle335** [VirginTeam/WotlkCore#969]
**Ссылки и комментарии:**

Проблема при выполнении задания http://db.logon3.com/?quest=13058 
Для выполнения необходимо сразится с http://db.logon3.com/?npc=30474 - целевой НИП по заданию.
Используем http://db.logon3.com/?item=42918 чтобы "перенестись назад во времени" (увидеть необходимого НИПа)

**Что работает не так?**

Под баффом http://db.logon3.com/?spell=56863 пытаемся сразится с http://db.logon3.com/?npc=30474 
Вешается комбат, но НИП недоступен для взаимодействия.
("эту цель атаковать нельзя" или "нельзя применить способность к этой цели")

**Как должно работать?**

НИП http://db.logon3.com/?npc=30474 не строит из себя недотрогу, вступает в бой.

**Шаги для воспроизведения ошибки:**

1. Берем квест http://db.logon3.com/?quest=13058 
2. Подлетаем в Храм жизни
3. Используем http://db.logon3.com/?item=42918 
4. Находим http://db.logon3.com/?npc=30474 
5. Бьем.

**Текущее обновление ядра:**

Build 202 2018-05-21

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by ForesterDev** [comment]
Исправлено
