### ISSUE TITLE
Бегство

### ISSUE THREAD

**Issue by kalambyr18** [VirginTeam/WotlkCore#977]
**Ссылки и комментарии:**

http://ru.wowhead.com/quest=863

**Что работает не так?**

1, Нпс бежит лежа
2, После того как сопроводил нпс ничего не происходит http://screenshot.ru/upload/image/aDDz
 
**Как должно работать?**

Лежа не бегают. Кв должен засчитываться по факту сопровождения 

**Шаги для воспроизведения ошибки:**

1. Взять кв
2, Сопроводить

**Текущее обновление ядра:**

Build 203

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by ForesterDev** [comment]
Обе проблемы не воспроизводятся

**Comment by ForesterDev** [comment]
Воспроизвелось после нескольких попыток. Будет исправлено
