### ISSUE TITLE
Свобода!

### ISSUE THREAD

**Issue by kalambyr18** [VirginTeam/WotlkCore#978]
**Ссылки и комментарии:**

http://ru.wowhead.com/quest=898

**Что работает не так?**

Нпс не возвращается при получении урона . Агрит кучу мобов , просто идет дальше . Проходить невозможно http://screenshot.ru/upload/image/aDDL

**Как должно работать?**

Урон идет по нпс тот разворачивается или останавливается, чтоб было время буить мобов, отпиться и т.д.

**Шаги для воспроизведения ошибки:**

1. Взять кв на сопровождение
2, сопроводить

**Текущее обновление ядра:**

build 203

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by ForesterDev** [comment]
Исправлено
