### ISSUE TITLE
[NPC] ID 25038 - Пророк скверны (Демонические испарения)

### ISSUE THREAD

**Issue by sega693** [VirginTeam/WotlkCore#979]
**Ссылки и комментарии:**
http://db.logon3.com/?npc=25038 Босс
http://db.logon3.com/?spell=45402 Демонические испарения (Demonic Vapor)
http://db.logon3.com/?spell=46931
http://db.logon3.com/?npc=25268 скелеты

**Что работает не так?**
Из каждого луча должно спавниться 10 скелетов. Всего 2 луча за фазу. В сумме 20 скелетов
У нас же даже их овер 100500, считать бесполезно (см. скрины) Т.к. самих лучей более двух
http://puu.sh/Az1iO/1a6db814d0.jpg
http://puu.sh/Az1k0/34c7f36ce2.jpg
http://puu.sh/Az1lb/daefe177b7.jpg
http://puu.sh/Az1my/fad329f6a4.jpg

**Как должно работать?**
Должно быть быть только два луча и всего 20 скелетов из них. 
До последнего апдейта с перескриптовкой босса они спавнились правильно

> Demonic Vapor: в начале каждой воздушной фазы Фелмист кастует в случайного человека в рейде зеленый луч. Луч ездит по полю за убегающим игроком, оставляя за собой след. Из следа выползают многочисленные скелеты, которых должны собирать танки.
> Луч и след бьют попавших в них на 4к натур дамаги. Луч длится 10 секунд, сразу за первым лучом босс сдает второй опять в случайную цель. Может так получиться, что два луча будут в одного и того же человека.

рандомные древние видосы. Скелетов явно меньше чем у нас
https://www.youtube.com/watch?v=zKIepv2-Yjo 1:50
https://www.youtube.com/watch?v=hXdShKK7fT4 1:50 3:10 4:30 5:50
https://www.youtube.com/watch?v=DITc0fahADs 1:05 4:05

**Шаги для воспроизведения ошибки:**
1. Дождаться взлета и каста луча
2. Офигеть от кол-ва скелетов. Даже фпс проседает заметно, но не критично

**Текущее обновление ядра:**
Build 203 2018-05-28 16:37:46 +0400

**Comment by sega693** [comment]
Так же у босса остался имунитет к кровотечениям https://github.com/VirginTeam/WotlkCore/issues/856 
https://www.youtube.com/watch?v=OQIdYAtZi3E тут отлично видно доты ферала и роги
https://www.youtube.com/watch?v=OYXJYscnAOI

**Comment by ForesterDev** [comment]
Исправлено, проверьте после обновления
