### ISSUE TITLE
[NPC] ID 330, 390 - Принцесса, Кабаний эскорт

### ISSUE THREAD

**Issue by Santaria94** [VirginTeam/WotlkCore#980]
**Ссылки и комментарии:**

http://db.logon3.com/?npc=330
http://db.logon3.com/?npc=390

**Что работает не так?**

Из комментариев к квесту - http://ru.wowhead.com/quest=88 следует, что в бою с Принцессой ей помогает ее свита, которая всегда ходит с ней. Сейчас же они нейтральны и никак не защищают ее.

**Как должно работать?**

Принцесса и ее эскорт должны быть агрессивными по отношению к игроку. Если принцесса атакована, то ее эскорт должен защищать ее.

**Текущее обновление ядра:**

Build 204

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by ForesterDev** [comment]
Исправлено
