### ISSUE TITLE
[Предмет] ID 3386 - Эликсир излечения

### ISSUE THREAD

**Issue by kalipsa988** [VirginTeam/WotlkCore#982]
**Ссылки и комментарии:**

http://db.logon3.com/?item=3386

**Что работает не так?**

Излечивает 1-2 яда

**Как должно работать?**

Всегда должен излечиваеть от четырех ядов, уровень которых не превышает 60.
**Шаги для воспроизведения ошибки:**

1. повесить много ядов
2. прожать фласку

**Текущее обновление ядра:**

06.06.2018

**Comment by ForesterDev** [comment]
![image](https://user-images.githubusercontent.com/11771800/41189246-d9b70f74-6bdb-11e8-9f33-25469aa516c0.png)
Работает корректно

**Comment by kalipsa988** [comment]
он не излечивает когда 4 одинаковых яда

**Comment by kalipsa988** [comment]
нигде не сказано, что излечивает только разные яды, так что должен излечивать и одинаковые

**Comment by kalipsa988** [comment]
попробуй 4 укуса змеи повесить и прожать фласку

**Comment by kalipsa988** [comment]
она излечит рандомно

**Comment by ForesterDev** [comment]
Одинаковые тоже диспелит. Вероятно проблема в сопротивлении дебаффов к рассеиванию
