### ISSUE TITLE
[NPC] ID 127 - Мурлок-волнолов

### ISSUE THREAD

**Issue by Santaria94** [VirginTeam/WotlkCore#983]
**Ссылки и комментарии:**

http://db.logon3.com/?npc=127

**Что работает не так?**

Слишком маленькое количество NPC по сравнению с другими мурлоками. Для прохождения квеста  http://db.logon3.com/?quest=152 приходится ждать 2-3 респа данных мурлоков, даже при отсутствии конкуренции.

**Как должно работать?**

Заселить большое количество нпс, чтобы их было примерно как и других мурлоков, т.е. хотя бы 10-15.

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by ForesterDev** [comment]
Исправлено
