### ISSUE TITLE
Мистер Каюк

### ISSUE THREAD

**Issue by kalambyr18** [VirginTeam/WotlkCore#984]
**Ссылки и комментарии:**

http://ru.wowhead.com/npc=646
Один из боссов в "Мертвые копи"

**Что работает не так?**

Если босса отводить , то после того как даст стан и бежит на танка, агро прыгает с танка на других игроков в группе (это не срыв агро ). Сейчас к примеру умер в итоге хил ! http://screenshot.ru/upload/image/aUL1

**Как должно работать?**

Босс бежит к тому игроку на ком больше агро . Агро не прыгает каждую секунду между танком и другими игроками группы ! 

**Шаги для воспроизведения ошибки:**

1. Заагрить босса
2. Отвести 
3. Получить стан
4, Смотреть на кого агрится босс пока бежит к танку

**Текущее обновление ядра:**

build 204

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by ForesterDev** [comment]
Исправлено, проверяйте после обновления
