### ISSUE TITLE
Цепочка квестов после "Средство для устрашения"

### ISSUE THREAD

**Issue by sselgnos** [VirginTeam/WotlkCore#985]
**Ссылки и комментарии:**

**Что работает не так?**
После выполнения квеста http://db.logon3.com/?quest=12822 "Средство для устрашения" нельзя взять квесты "Безупречный план" http://db.logon3.com/?quest=12823 и "Выдающийся подрывник" http://db.logon3.com/?quest=12824 у НПЦ Джино, а можно взять только при условии, что квест "Средство для устрашения" должен быть активным. Цепочка квестов важна для получения ачивок и для поиска Места крушения Громаша.

**Как должно работать?**

Вышеуказанные квесты можно взять даже после выполнения "Средство для устрашения", а не только во время выполнения.

**Шаги для воспроизведения ошибки:**

1. Выполнить цепочку квестов, включая квест "Средство для устрашения"
2. Джино не даёт последующие квесты

**Текущее обновление ядра:**

Последнее обновление ядра: Build 204 2018-05-30 12:21:57 +0400
Основной сервер х1 PVE

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by ForesterDev** [comment]
Проверите после обновлени
