### ISSUE TITLE
[NPC] ID 424 - Браконьер из стаи Красногорья

### ISSUE THREAD

**Issue by Santaria94** [VirginTeam/WotlkCore#986]
**Ссылки и комментарии:**

http://db.logon3.com/?npc=424
https://classicdb.ch/?npc=424

**Что работает не так?**

Неправильное заселение NPC. Очень маленькая численность. 

**Как должно работать?**

Должно быть больше NPC. Выше приведена ссылка на классик-базу, где расположение NPC наиболее приближенное к тому, как должно быть. Также стоит отметить, что в области заселения есть небольшие лагеря. Вот вокруг них и должно быть основное скопление NPC (У нас же там 1-2 моба, а то и вовсе пустые палатки стоят)

https://cdn.discordapp.com/attachments/412316469721038858/454327905351237635/g3.jpg
https://cdn.discordapp.com/attachments/412316469721038858/454327903845613588/g2.jpg
https://cdn.discordapp.com/attachments/412316469721038858/454327900725051402/g1.jpg

**Текущее обновление ядра:**

204

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by ForesterDev** [comment]
Исправлено
