### ISSUE TITLE
[NPC] ID 32930 - Кологарн (Удар по темени)

### ISSUE THREAD

**Issue by sega693** [VirginTeam/WotlkCore#987]
**Ссылки и комментарии:**
http://db.logon3.com/?npc=32930 Кологарн
http://db.logon3.com/?spell=63356 Удар по темени

**Что работает не так?**
Бьет по предбис танку (264-284илвл) по 60к+ урона

**Как должно работать?**
Не должна так прошибать, в т8-т9 гире пережить невозможно. Про доп. урон не сказано ни в одном гайде
> Удар по темени: специальная атака, накладывающая на танка стакающийся дебуфф Хруст доспеха (уменьшает армор на 25% на 45 секунд - героик, на 6 секунд - нормал).

**Шаги для воспроизведения ошибки:**
1. Спулить
2. Словить ваншот

**Текущее обновление ядра:**
Build 203 2018-05-28 16:37:46 +0400

**Comment by ForesterDev** [comment]
Доп урон - http://ru.wowhead.com/spell=64715. Вызывается вместе с основной способностью

**Comment by ForesterDev** [comment]
Урон был скорректирован
