### ISSUE TITLE
[Общая механика] Переход в инст

### ISSUE THREAD

**Issue by Manulli** [VirginTeam/WotlkCore#99]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

При попытке зайти в ЦЛК25об попадаю в текстуру, интерфейс не работает, повисло кд

**Что работает не так?**

[Собственно, фактический результат](http://s010.radikal.ru/i311/1704/55/859ea67747ect.jpg)
Могу изменять настройки, все остальное (чат, абилки, даже выход из игры) не работает. Другие люди меня в онлаине не видят, после релога появляюсь в таверне.

**Как должно работать?**

Как всегда должно работать, не мне вам рассказывать как в цлк ходить

**Шаги для воспроизведения ошибки:**

1) Взять рейд
2) Зайти (на своих двоих, не через сум) в инст

**Текущее обновление ядра:**

build 153 2017-04-13

**Comment by ForesterDev** [comment]
Такое происходит в редких случаях, если запулили босса в момент когда вы прогружаетесь в инст
