### ISSUE TITLE
[Задания] ID 349 - Лихорадка Тернистой долины

### ISSUE THREAD

**Issue by kalambyr18** [VirginTeam/WotlkCore#990]
**Ссылки и комментарии:**

http://ru.wowhead.com/quest=26597
http://ru.wowhead.com/npc=1449

**Что работает не так?**

Неактивен нпс по кв Знахарь Унбагва

**Как должно работать?**

Должен разговаривать

**Шаги для воспроизведения ошибки:**

1. Попытаться пообщаться с квестовым нпс

**Текущее обновление ядра:**

build 204

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by Ewropa** [comment]
ссылка на задание не верная, вот задание которое было в 3.3.5 http://ru.wowhead.com/quest=349
