### ISSUE TITLE
Форум!

### ISSUE THREAD

**Issue by MiceRus** [VirginTeam/WotlkCore#991]
ДА просто не знаю, как связаться админами форума!
Кто придумал капчу из картинок использовать?У вас она постоянно ломается!
Среди картинок появляется одна очень мелкая, которая после перетаскивания в нужное место меняет внутри свою картинку и подтвердить что я не робот никак не получается.
И потом. почему это вдруг я полгода заходил на форум нормально а сегодня вдруг он меня забыл?

**Comment by MiceRus** [comment]
ДА походу у вас там все сломалось!
Даже пазлы не воспринимает! Чего там заумного-то - две картинки на место поставить? Однако нет - пишет красный круг.
Вы уж коли игру не можете нормально сделать - так форум хотя бы не трогайте

**Comment by gmKroshka** [comment]
У форума свои администраторы. Мы не имеет к поломкам и недоработка этой площадки никакого отношения. Обратиться к администрации можно в группе ВК/дискорде/игре
