### ISSUE TITLE
[NPC] ID 16416 - Бронн Выкрутас

### ISSUE THREAD

**Issue by deexeq** [VirginTeam/WotlkCore#992]
**Ссылки и комментарии:**

[Бронн Выкрутас](http://db.logon3.com/?npc=16416) ([wowhead](http://ru.wowhead.com/npc=16416))

**Что работает не так?**

Стоит в Круговзоре.

**Как должно работать?**

Должен находиться за пределами Круговзора.

**Текущее обновление ядра:**

Build 204 2018-05-30 12:21:57 +0400

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by ForesterDev** [comment]
Исправлено
