### ISSUE TITLE
[NPC] ID 16857 - Хищный землерой

### ISSUE THREAD

**Issue by Santaria94** [VirginTeam/WotlkCore#994]
**Ссылки и комментарии:**

http://ru.wowhead.com/npc=16857
https://www.youtube.com/watch?v=prMePkDI2XM

> These guys won't de-aggro easily -- since they can't move from their spot, running out of their attack range alone won't exit you from combat. You've just gotta keep running.

> Cannot be affected by Death Grip by Death Knights.

> Cannot be effected by Hunters "Scatter Shot"

**Что работает не так?**

1) Некорректная анимация.
2) Передвижение NPC.
3) Отсутствует иммунитет к способностям, влияющих на изменение местоположения цели.

**Как должно работать?**

1) NPC изначально зарыт под землей. Когда NPC атакует игрока, он вылезает из под земли и анимация, соответственно, должна изменятся.
2) NPC не должен передвигаться, его местоположение всегда статично.
3) Связано с предыдущим пунктом. NPC должен иметь иммунитет к таким способностям, как Хватка смерти, Гром и Молния, Тайфун, Взрывная волна, а также, вероятно, к любым эффектам контроля, дезориентации, страха.

**Текущее обновление ядра:**

Игровой сервер 204

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by ForesterDev** [comment]
Исправлено. 1. Появление нпц при аггро, исчезновение при эвейде. 2. НПЦ в мили стоит, но если игрок убегает - он должен закапываться и преследовать за ним пока он в аггро зоне. 3. Исправлено
