### ISSUE TITLE
[NPC] ID 5172 - Остротерн <Наставник чернокнижников>

### ISSUE THREAD

**Issue by Santaria94** [VirginTeam/WotlkCore#996]
**Ссылки и комментарии:**

http://db.logon3.com/?npc=5172
http://ru.wowhead.com/npc=5172

**Что работает не так?**

NPC не заселен. 

**Как должно работать?**

NPC должен находится в Стальгорне по координатам 50 : 6

**Текущее обновление ядра:**

204

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by ForesterDev** [comment]
Исправлено
