### ISSUE TITLE
[NPC] ID 48, 203 -  Скелет-воин, Маг-скелет

### ISSUE THREAD

**Issue by Santaria94** [VirginTeam/WotlkCore#998]
**Ссылки и комментарии:**

http://db.logon3.com/?npc=48
http://db.logon3.com/?npc=203

http://ru.wowhead.com/npc=48
http://ru.wowhead.com/npc=203

**Что работает не так?**

Заселение:
1) http://db.logon3.com/?npc=48 не должно быть в Болотине.
2) Численность http://db.logon3.com/?npc=48 и http://db.logon3.com/?npc=203 должна быть выше.

**Как должно работать?**

https://www.youtube.com/watch?v=EStJXo5bOM4 - видео с более поздних патчей, но там этот участок не особо изменен, по нему видно, что NPC больше примерно в 1.5-2 раза.

Точки заселения с классической базы:
http://vanillawowdb.com/?npc=48
http://vanillawowdb.com/?npc=203

**Текущее обновление ядра:**

204

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by ForesterDev** [comment]
Исправлено
