### ISSUE TITLE
[NPC] ID 771 - Командор Сквернстром

### ISSUE THREAD

**Issue by Santaria94** [VirginTeam/WotlkCore#999]
**Ссылки и комментарии:**

http://db.logon3.com/?npc=771
http://db.logon3.com/?spell=3488

**Что работает не так?**

Примерно на 10% NPC использует способность _Воскресение Сквернстрома_. После применения способности, если не убить его до окончания каста, умирает и создается его копия (в целом все правильно). 

Однако старое тело можно облутать. Затем довести нового NPC до 10%, он также убьет себя и создаст копию, с которых можно поднять лут. Таким образом можно повторять цикл бесконечно и лутать рарника сколько угодно.

Также после применения способности за новым NPC сохраняется новая стартовая позиция, в которой убил себя предыдущий Командор. Таким образом NPC можно "увести" на огромные расстояния, например в стартовую локацию, где он будет убивать низкоуровневых игроков.

**Как должно работать?**

1) Вероятно при суициде со старого тела не должно быть лута.
2) Должен возвращаться на позицию первоначального NPC.

**Шаги для воспроизведения ошибки:**

1. Довести NPC примерно до 10%
2. Позволить применить способность http://db.logon3.com/?spell=3488 

**Текущее обновление ядра:**

204

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by Santaria94** [comment]
Также, предположительно, может возникнуть баг с респауном. Например, спустя 8 часов, в катакомбах окажется не один, а 5, 10 или 20 Сквернстромов - в зависимости от того, сколько копий было убито. Однако это проверить возможности не было.

**Comment by ForesterDev** [comment]
Исправлено
